stt001-13.otr
MonlamAI/STT001 pull request #10
Opened 2023-01-26 04:04 UTC by jigmasth

This file is stt001-13.otr which was done by JIGMAT RINCHEN. 14 min audio.

2023-04-05 05:01 UTC, geshecelon requested changes
01:57 སྤྱིར་ཤེས་པ་ལ་ཕྲ་རགས་མང་པོ་ཞིག་བཤད་ཀྱི་འདུག་བ། ཤེས་པ་རགས་པ་དེ་ཚོར་འགྲེས་ང་ཚོའི་མངོན་དུ་གྱུར་ནས་མངོན་གྱུར་ཆགས་དེ་ཡི་འདུག། ༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས་༽ ཤེས་པ་ཕྲ་མོའི་རིགས་མང་པོ་གཅིག་ཕལ་ཆེར་ལྐོག་གྱུར་རེད།

02:07 ད་ཤིན་ཏུ་ལྐོག་གྱུར་ཡང་ཡོང་གི་མེད་འགྲོ། བྱས་ཙང་ད་དེ་འདྲ་གཅིག་གི་ཨ་ནི་རྒྱུན་གྱི་གང་ལ་བསམ་བློ་གཏོང་དགོས་བྱུང་ན་ལྐོག་གྱུར་རེད་འདུག་ག། ༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས་༽

02:18  བྱས་ཙང་ད་མཐོང་བ་མངོན་གྱུར་ཙམ་མ་གཏོགས་ཁས་མི་ལེན་མཁན་གཅིག་གིས། ཨ་ནི་ལྐོག་གྱུར་གྱི་གནས་དོན་ཞིག་གཏན་ལ་འབེབས་དགོས་བྱུང་ན། 

02:28 ཁོ་མ་ཤེས་པ་རེད་མ་རྙེད་པ་རེད༼དེ་ལ་ཚགས་དུང་ཞིག་ཆད་འདུག༽མ་གཏོགས། དེ་མེད་པར་རྙེད་པ་རྩ་བ་ཉིད་ནས་མ་རེད་བ། ད་འདི་སྔོན་ལ་ག་རེ་ཟེར་གོ་རེ་གཞི་རུ་གཅིག་བྱས། གནས་དོན་དེ་གཅིག་ཆགས།

03:01  དེ་འདྲ་ཡིན་དུས་ཙ་ནས་ཁོ་ཕྱི་གཟུགས་ཅན་ལ་ཉེར་ལེན་གྱི་རྒྱུ་དགོས་པ་༼འདིར་ཚགས་དུང་མི་དགོས་༽། ནང་བཞིན་ང་རང་ཚོས་ནང་གི་རྣམ་པར་ཤེས་པ་ལ་ཡིན་ནས་ཉེར་ལེན་གྱི་རྒྱུ་དགོས་ཀྱི་རེད་ཅེས་

03:20 ལ་ཁོ་རང་གཅིག་གོ་མནན་ནས་འགྲོ་ཡ་ཡོད་པ་གཅིག་ཁོ་གཉིས་བོ་འདི་མི་འདྲ་བ་ཞིག་ཆགས་ཀྱི་འདུག་ག།༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས་༽

04:00 མཚམས་འདི་བར་གུས་པར་ནོར་བཅོས་བྱས་ཟིན། རྗེས་སུ་མུ་མཐུད་དེ་ཞུ་རྒྱུ་ཡིན།

2023-04-06 13:07 UTC, geshecelon requested changes
04:40 བཏོན་ནས་རྣམ་རྟོག་༼རྣམ་རྟོག་ཞེས་པ་ལན་གསུངས་འདུག༽གི་འཕྲོ་འདུ་བཀག་ནས་ཨ་ནེ་དེ་༼འདི་༽གང་ནས་ཤེས་པ་སོ་མ་མ་བཅོས་པའི་མྱོང་ཞིག་དེ་གལ་ཆེན་པོ་རེད་ཤག། ༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས།༽
04:52 ད་འདི་འདྲ་ཐོག་ནས་ཤེས་པ་ཟེར་ཡ་ཁོ་རང་ངོ་བོ་གང་འདྲ་ཞིག་འདུག་ག་ དེའི་རང་བཞིན་དེ་གཅིག་ཤེས་ཡོང་དུས་ཙ་ནས་
05:00 དེ་དང༌རིགས་མཐུན་པའི་ད་རིགས་འདྲའི་རྒྱུ་ཞིག་དགོས་༼གི་༽རེད་དགོས་༼གི་༽མ་རེད། ད་ཁ་སང་ལབ་པ་ནང་བཞིན། ཀླད་པ་ལས་ཤེས་པ་སྐྱེ་པ་༼ཀྱི་ཡོད་༽རེད། 
05:10 ཀླད་པས་བརྟེན་བྱེད་ཡོད་རེད། དེ་འདྲ་ཡིན་ནས་ཀླད་པ་དེ་རྫས་རགས་པ་རེད་ཤེས་པ་ལྟས་༼ལྟོས་༽ན་
05:21 དཔེ་༼ར་པོ་༽ཆ་བཞག་ན། ཚན་རིག་པ་གཅིག་གིས་སྐབས་ཤིག་འགྲེལ་བཤད་འདི་འདྲ་ཞིག་བྱུང། གཞན་གྱི་སྡུག་བསྔལ་མཐོང་ནས་༼འེས་༽

05:40 མྱོང་སའི་ཀླད་པ་དེ་གཅིག་པ་རེད་ཟག་ ང་འདི་ཡམ་ཞ་འུ་༼ཞེ་པོ་༽ཞིག་མཚན་སོང། དེ་དུས་ལབ་ཡ་༼ལབ་ཡིན་༽ཨ་ལས་ད་ཀླད་པ་དེ་ལྐུག་སེ་བྱུང་ང་ཞེས་ལབ་ཡིན་
06:10 ད་བློ་སྐྱེས་ཡོང་དུས་ཙ་ནས། སེམས་ལ་ཡ་མི་བདེ་བ་ཡོང་ཡ་འདི་དང་དུ་ལེན་པ་རེད་ལ། གཞི་རྩ་དེ་སྙིང་སྟོབས་འདུག་བ༼ག༽། རང་གི་སྡུག་བསྔལ་གྱིས་མནར་བའི་གནས་སྐབས་
06:19 ལ་ཡ། མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་ཐོག་ཏུ་བབས་ནས་དེས་མནན་པ་ཞིག་རེད་བ། ཀླད་པས་དེ་གཉིས་ངོས་འཛིན་འདི་༼གཉིས་ཀྱི་༽དབྱེ་བ་འབྱེད་ཤེས་ཀྱི་མེད་པའི་ཟོ་འདྲ་པོ་ཞིག་འདུག་ དེ་དུས་ཤེས་སོང་
06:29 དེ་ཡང་ད་མུ་མཐུད་ནས་ཞིབ་འཇུག་བྱེད་དགོས་ཡ་རེད་ཅེས་ནས་སྐད་ཆ་བྱུང།  བྱས་ཙང་འདི་འདྲ་ཡིན་དུས་དེས་ན་གལ་སྲིད་འདི་བདེན་པ་ཡིན་ན་རེད་ད། ༼ཁོ་༽སྡུག་བསྔལ་གྱི་ཚོར་བ་དེ་ཙམ་ཞིག་རེད་མ་གཏོགས།
06:39  སྡུག་བསྔལ་དེ་ཡོང་སྟངས་གང་འདྲས་ཡོང་པ་འདི་ཀླད་པའི་ནུས་པའི་གང་ནས་ཤེས་ཀྱི་མི་འདུག་བ་༼ག༽། དངོས་གནས་བྱས་ན་ཤེས་པའི་གང་ནས་ཁྱད་པར་ཞི་འུ་༼ཞེ་པོ་༽ཞིག་ཡོད་རེད་བ་ད།

06:58 ཇི་ཙམ་གྱིས་གཞན་བདེའི་བསམ་ཡ་གི་བློ་འདི་ཤུགས་ཆེ་བ་ཡོད་པ་ཚོད་ཀྱིས། སྙིང་སྟོབས་ཆེ་བ་ཡོང་གི་ཡོད་རེད། སྙིང་སྟོབས་ཆེ་བ་ཡོད་པའི་ཚོད་ཀྱིས། སེམས་ཁྲལ་ཉུང་བ་ཡོད་རེད། སེམས་མ་སྐྱིད་པ་ཉུང་བ་ཡོད་རེད།
07:09   ཕན་གྱི་འདུག་བ་༼ག་༽དགོས་ཀྱི་འདུག་བ་༼ག་༽། དེ་སྤེལ་དགོས་ཡ་རེད་བ། དང་དུ་ལེན་དགོས་ཡ་ཞིག་རེད་བ། དགོས་པ་ཞིག་རེད་འདུག་བ་༼ག༽།
07:18 རང་གི་སྡུག་བསྔལ་ཞིག་མནར་དེ་བ་འདི་མི་འདོད་པ་རེད་བ། དུས་ནམ་ཡང་མི་དགོས་པ་རེད་བ། རང་ཉིད་སྡུག་བསྔལ་གྱིས་མནར་དེ་ཡི་སྡུག་བསྔལ་འདི་
07:28 མི་འདོད་པ་ཡིན་དུས་ཙ་ནས། ང་ཚོས་ཐར་པ་བསྒྲུབ་ཀྱི་ཡིན་ཐམས་ཅད་མཁྱེན་པའི་གོ་འཕང་བསྒྲུབ་ཀྱི་ཡིན་ཟེར་ཡ་འདི་དེར་ཐུག་པ་རེད་བ།  རེད་བ་༼ཡ་༽ གཞན་གྱི་སྡུག་བསྔལ་བསམ་ཡ་འདི་
07:36 རང་ལ་ཕན་གྱི་འདུག་བ། ཕན་གྱི་ཡོད་ཙང་འདི་དགོས་ཡ་རེད་བ་ ༼རེད་དེ་༽འོན་ཀྱང་༼འོན་ཀྱང་དེ་མེད་པ་ལྟ་བུ་འདུག་༽བླང་བྱ་དང་དོར་བྱ་གཉིས་ཀ་ལོགས་ཀླད་པ་གཅིག་གིས་རྟེན་བྱེད་ཀྱི་ཡོད་ན། 
07:44 ཡ་མཚན་པོ་རེད་སོང་ང་མི་འདུག་གེ། ༼ག་ཡི་རྗེས་ལ་ཤད་མི་དགོས་༽ ཙ་བ་དེ་འདྲ་འདྲ་པོ་རེད།  ད་འིད་འདྲ་ཡིན་དུས་ཤེས་པའི་རྣམ་གཞག་ཆ་ཚང་ཞིག་༼ཅིག་༽ཀླད་པའི་གང་ནས་འགྲེལ་བཤད་རྒྱབ་ཡ་ཞེ་དྲག་ཁག་པོ་རེད།
07:55 རགས་པ་རགས་པ་རགས་པ་རགས་པ་རགས་པ་ཞིག་འགྲེལ་བཤད་རྒྱབ་ཀྱི་ཡོད་རེད་མ་གཏོགས། དེ་འདྲ་ཡིན་དུས་འགྲེལ་བཤད་ཆ་ཚང་རྒྱབ་མ་ཐུབ་ཡ་ཞིག་གི་ཞི་༼གཞི་༽འདི་ཀྱི་ཨ་ནེ་འགྲེལ་བཤད་ཆ་ཚང་རྒྱ་མ་ཐུབ་
08:04 ཡ་འདི་ཤེས་པའི་རང་བཞིན་ཡོངས་སུ་རྫོགས་པ་ཀླད་པ་དེ་ནས་བྱུང་བ་རེད་ཅེས་ལབ་ཐུབ་ཞེ་དྲག་ཁག་པོ་རེད། 
08:12 ད་དེ་ཡང༌། ༼wishful thinking༽ ཟོ་འདྲ་ཆག་གི་ཡོད་ན་གང་ཤེས་ད་༼wishful thinking༽༼ཧེ་ཧེ་ཧེ་ཧེ་༽ཆག་གི་ཡོད་ན་གང་ཤེས་ཅི་བྱེད་ད་
08:20 མཚམས་འདི་ནས་རྗེས་སུ་ནོར་བཅོས་བྱ་རྒྱུ་ཡིན།

2023-04-09 04:51 UTC, geshecelon requested changes
08:12 ད་དེ་ཡང༌། ༼wishful thinking༽༼ཝིཤི་ཧྥུལ་ཐིན་ཁིན།༽ ཟོ་འདྲ་ཆག་གི་ཡོད་ན་གང་ཤེས་ད་༼wishful thinking༽༼ཝིཤི་ཧྥུལ་ཐིན་ཁིན།༽ཆག་གི་ཡོད་ན་གང་ཤེས་ཅི་བྱེད་ད་
08:20 ད་གང་ལྟར་ད་རིང་སང་ཉིན་མུ་མཐུད་ནས་ཡར་རྒྱས་འགྲོ་ཡི་རེད་ལ། ལྟ་ཡ་འདུག་བ་བསམ་བློ་བཏང་ཤག་འདུག་བ། ད་འདི་རྙོག་དྲ་གཅིག་འདི་རེད་བ་རྙོག་དྲ་གཅིག་

08:20 ད་གང་ལྟར་ད་རིང་སང་ཉིན་མུ་མཐུད་ནས་ཡར་རྒྱས་འགྲོ་ཡི་རེད་ལ། ལྟ་ཡ་འདུག་བ་བསམ་བློ་བཏང་ཤག་འདུག་བ། ད་འདི་རྙོག་དྲ་གཅིག་འདི་རེད་བ་རྙོག་དྲ་གཅིག་
08:29 འདི་འཛམ་གླིང་ག་རེ་བྱས་ནས་ཆགས་བ་རེད།  འོ་འདི་རེད་ད་༼why༽༼ཝེ།༽ལབ་བ་ཡིན་ན། འཛམ་གླིང་ཆགས་སྟངས་ ༼how༽༼ཧའོ།༽ ལབ་བ་ཡིན་ན་ཏོག་ད་བཤད་ཐུབ་ཀྱི་རེད། 
08:39 ༼what ༽༼ཝཊི།༽ ༼ལབ་པ་ཡིན་ན་༽ཏོག་༼སེ་༽བཤད་ཐུབ་ཀྱི་རེད། འཛམ་བུ་གླིང་གང་འདྲ་ཞིག་རེད་ལབ་ན་འདི་ཏོག་༼སེ་༽བཤད་ཐུབ་ཀྱི་རེད།  འཛམ་བུ་གླིང། ཉི་མ། གཟའ་སྐར་དེ་བཤད་ཐུབ་ཀྱི་རེད། ༼ galaxy༽༼གྷ་ལེག་སི།༽ འདི་གང་ནས་བཤད་ཐུབ་ཀྱི་རེད་བ། ༼how ༽༼ཧའོ།༽ ༼སེ་༽ལབ་ན་བཤད་ཐུབ་ཀྱི་རེད།
08:50  ལོ་ཐེར་འབུམ་ཁ་ཤས་གོང་ནས་ད་ཆགས་པ་རེད་ཉི་མ་འདུགས་ཆགས་པ་རེད། ཨ་ནི་འདི་མཐའ་ལ་ཡ་བསྐོར་བསྡད་མཁན་འདི་འདུགས་འདུགས་ཆགས་པ་རེད་ཅེས་འགྲེལ་བཤད་ཞིག་བརྒྱབ་ཐུབ་ཀྱི་རེད་བ། 
09:00 ད་༼why ༽༼ཝེ།༽༼སེ་༽ལབ་པ་ཡིན་ན་ད་འགྲེལ་བཤད་མི་འདུག་བ༼ག་༽། ད་༼philosophy ༽༼ཧྥིལོ་སོ་ཧྥིས།༽ གང་འགྲོ་་དེ་ཡི་ཡོད་རེད་བ། ཨ་ནི་ད་
09:09 རྒྱུ་མེད་ལས་སྐྱེས་པ་རེད་ཅེས་ལབ་ན་༼ད་༽དེ་འདི་གཏི་ཐུག་རེད། ད་ཤེས་ཀྱི་མི་འདུག་དོན་ལ་ད་ཤེས་ཀྱི་མི་འདུག་ལབ་པ་རེད་བ་ད། རྒྱུ་མེད་ལས་སྐྱེས་པ་ལབ་ན་ད་འདི་
09:18 ད་འདི་རྙོག་དྲ་ཚ་བོ་ཞི་འུ་༼ཞེ་པོ་༽འདུག་ད་འདི་རྒྱུ་མེད་ལ་སྐྱེས་མིན་འདྲོ་བ་ཅེས་་ལབ་ཞག་ན་ཨ་ནི་་ཡག་པ་འདུག་བ་༼ག་༽།
09:26  ད་འདི་བརྩད་གཅོད་བྱེད་ཡ་མགོ་ན་དགོས་བྱེད་གོ་ཡི་མི་འདུག་བ ༼ག་༽། ད་རྒྱུ་མེད་ལས་སྐྱེས་པ་བཤད་པ་ཡིན་ན། ཨ་ནི་ཧ་ཅང་ཐལ་བ་རེད།
09:31 དེས་དེ་དུས་རྒྱུ་དང་རྐྱེན་་༼ལས་༽ རྒྱུ་དང་༼ད་ལྟའི་༽ད་ལྟའི་གནས་སྐབས་ལ་ཡ་ཁོ་རྒྱུ་དང་རྐྱེན་ལ་ལྟོས༌བསྡད་མཁེན་ཁོ་རྒྱུ་རྐྱེན་ལ་རག་ལས་བསྡད་མཁེན་འདི་འདྲའི་གཅིག་
09:38 ཐོག་མར་འགོ་ཚུགས་པའི་ཁ་ཐུག་ལ་ཡ་རྒྱུ་རྐྱེན་གང་ཡང་མེད་པར་གློ་བུར་བྱུང་བ་རེད་ཅེས་ལབ་ན། དེ་རིགས་པའི་ལམ་ལས་འདས་པ་རེད་བ་བློབ་་་་་་་་༼ལབ་ཆོག་ཡ་མིན་འདུག་ག༽
09:47 ད་འོ་ན་རྒྱུ་ལས་སྐྱེས་པ་ཡིན་ན། རྒྱུ་ག་བ་ལས་སྐྱེས་པ་རེད།  ད་འུ་ཐུག་ནས་རྟག་པའི་རྒྱུ་ལས་སྐྱེས་པ་རེད་ཅེས་གྲངས་ཅན་པས་བཤད་ཡོང་ཀྱི་ཡོད༼ཚགས་དུང་ཞིག་དགོས་འདུག༽རེད།
ད་འདི་ཁག་པོ་ཞེ་དྲག་རེད། 
09:57 རྒྱུ་ལ་འགྱུར་བ་མེད་མཁན་གཅིག་གི་འབྲས་བུ་འགྱུར་བ་ཡོད་མཁན་གཅིག་ཡོང་ཐུབ་ཡ་མེད་པ་རེད། ཇི་ཙམ་གྱིས་འབྲས་བུར་༼ལ་༽འགྱུར་བ་འགྲོ་ཡི་ཡོད་པ་འགྱུར་བ་ག་རེ་ཟེ་ཇི་ཙམ་གྱིས་
10:10 འབྲས་བུ་ལ་འགྱུར་ཡོད་པ་བདེའི་ཚོད་ཀྱིས་ཁོ་རྒྱུ་དེ་ཁོ་རང་འགྱུར་བའི་ཅན་ཞིག་ཡོང་ཡོད་རེད་མ་གཏོགས་རྒྱུ་ལ་འགྱུར་བ་མེད་ན། ༼འེས༽རྒྱུ་ཡི་འབྲས་བུ་མ་སྐྱེས་པའི་གནས་སྐབས་ཤིག་དང༌། རྒྱུ་ཡི་འབྲས་བུ་སྐྱེས་པའི་གནས་སྐབས་བཞག་ཐུབ་ཡ་ཁག་པོ་ཞེ་དྲག་རེད།
10:20 ཨ་ནི་རྒྱུས་བྱ་བ་བྱེད་ཅེས་ཡོང་ཡ་ཁུ་ནས་ཡོད་མ་རེད། བྱས་ཙང་འདི་འདྲའི་ཡིན་དུས་ཙ་ནས་རྟག་པའི་རྒྱུ་ལས་འབྲས་བུ་ཨ་ནི་སྐྱེས་་པ་ཟེར་ཡ་འདི་ཡོང་ཡ་ཡོད་མ་རེད། ཞེ་དྲག་ཁག་པོ་རེདཤག། ༼ག་ཡི་རྗེས་ལ་ཤད་མི་དགོས།༽ 
མཚམས་འདི་ནས་རྗེས་སུ་བྱེད་ཆོག

2023-04-12 10:48 UTC, geshecelon requested changes
10:20 ཨ་ནི་རྒྱུས་བྱ་བ་བྱེད་ཅེས་ཡོང་ཡ་ཁུ་ནས་ཡོད་མ་རེད། བྱས་ཙང་འདི་འདྲའི་ཡིན་དུས་ཙ་ནས་རྟག་པའི་རྒྱུ་ལས་འབྲས་བུ་ཨ་ནི་སྐྱེས་་པ་ཟེར་ཡ་འདི་ཡོང་ཡ་ཡོད་མ་རེད། ཞེ་དྲག་ཁག་པོ་རེདཤག། ༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས།༽
10:30 ད་དེ་ནས་མར་ཕྱི་ནས་ཕྱེད་ཀ་རྟག་པ་ཡིན་པའི་ཟོ་འདྲ་པོ། ཕྱེད་ཀ་དངོས་པོ་ཡིན་པའི་ཟོ་འདྲ་བོ་ཞིག་ད་འཇིག་རྟེན་བཀོད་པ་པོའི་དཀོན་མཆོག་ཅེས་ལབ་ཡོང་ན། ༼ཧ་ཧ་༽ མཁྱེན་བརྩེ་ནུས་པ་མཐར་ཐུག་པ་ཡིན་དུས་ཙ་ནས། དངོས་པོ་ཡིན་པའི་ཟོ་འདྲ་པོ།
10:40  ད་རྟག་ཏུ་གནས་མཁན་རེད། རང་བྱུང་གི་སྐྱེས་བུ་རེད་ཅེས་རྗོད་༼ཟེར་དུས་ཙ་ན་༽ན། རྟག་པ་ཡིན་པའི་ཟོ་འདྲ་པོ་ད་འདི་འདྲ་ཞིག་བཤད་དགོས་བྱུང་ན་པའི་རྙོག་དྲ་ཚ་པོ་རེདཤག། འཇིག་རྟེན་བཀོད་པ་པོ་འདི་གང་འདྲས་བྱུང་བ་རེད། 
10:50 དེ་གང་འདྲས་ཞིག་རེད། གང་འདྲས་བྱུང་བ་རེད།  ག་རེ་བྱས་ནས་བྱུང་བ་རེད་ཅེས་ན་༼ཟེར་ན་༽པའི་༼དཔེ་༽རྙོག་དྲ་ཚ་པོ་རེད།  ཨ་ནི་ད་
11:00 ག་རེ་ཟེར་གོ་རེ་ཕ་གི་ནང་པ་རང་གི་མཁྱེན་པའི་བདག་ཉིད་དང༌། བརྩེ་བའི་བདག་ཉིད། ནུས་པའི་བདག་ཉིད་དེ་འདྲ་ཞིག་གིས་ད་ང་ཚོ་རྙོག་དྲའི་དཀྱིལ་ལ་བཅུག་འདུག་བ། ༼ག་༽ ༼ཧ་ཧ་༽
ད་ད་ནང་པ་རང་གི་ངོས་ནས་བཤད་སྟངས་རེད་ད་
11:19 ད་ལྟ་བ་༼ད་འོ་༽འདི་འདྲའི་རེད། མཁྱེན་པའི་བདག་ཉིད་དང༌། བརྩེ་བའི་བདག་ཉིད། ནུས་པའི་བདག་ཉིད་ཞིག་༼ཅིག་༽གིས་ད་བཀོད་ནས། བཀོད་པའི་འབྲས་བུར་འདྲ་པོ་འདི་ད་དཀོན་མཆོག་རང་ཡིན་པའི་ག་རེ་ཟེར་གོ་རེ་ཐུག་

11:40 ད་འདི་བཟོ་མི་དགོས་པ་བཟོས་སོང་༼ཧ་ཧ་ཧ་ཧ་༽བྱས་ཙང་འདི་འདྲ་ཡིན་དུས་ཙ་ནས་རྙོག་དྲ་འདུག་བ༼ག༽།
11:50 ད་འདི་འདྲ་ཡིན་དུས་རྒྱུ་མེད་རྐྱེན་མེད་ལས་བྱུང་བ་དེ་རིགས་པ་དང་འགལ་གྱི་འདུག། ༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས།༽ རྟག་པའི་རྒྱུ་ལས་སྐྱེས་པ་དེ་འདི་རིགས་པ་དང་འགལ་གྱི་འདུག་ 
12:00 སྐྱེས་བུས་རང་བྱུང་རྟག་པ་རང་བྱུང་གི་སྐྱེས་བུས་བཀོད་པ་དེ་རིགས་པ་དང་འགལ་གྱི་འདུག། ༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས།༽ འགལ་འདུ་ཞི་འུ་ཞིག་འདུག་ད་ག་རེ་ཟེར་ན། ཨ་ནི་

12:20 འཇིག་རྟེན་སེམས་ཅན་ཞིག་ཡོད་པ་ཡིན་ཙང། སྣོད་ཀྱི་འཇིག་རྟེན་འདི་ཆགས་པ་རེད། ད་ལས་ཟེར་ཁན་དེའི་གང་སླེབས་ཀྱི་འདུག་བ༼ག༽། 
12:30 བྱས་ཙང་ག་ད་་ཐོག་མ་ཡོད་རེད་བས་ཟེར་ཡ་སྐད་ཆ་འདི་རེད། ༼འེས་༽ད་ལྟ་རྟག་པའི་རྒྱུ་དང༌། རྒྱུ་མེད་ལས་སྐྱེས་པ་དང༌། འཇིག་རྟེན་བཀོད་པ་པོ་ཞེས་༼ཟེར་ནས་༽བཤད་དགོས་ཀྱི་༼ཡ་༽
12:40 གནད་འགག་ཐུག་ས་གཅིག་འདི། ཐོག་མ་བཞག་ན་མ་བདེ་བ་ཆགས་ཀྱི་ཡོད་པ་རེད། བྱས་ཙང་ཐོག་མ་ཞག་དགོས་ཀྱི་འདུག་བ༼ག༽། 

13:01 ༼འེས་༽ང་འདི་ཚོས་མང་པོ་ཞིག་ཡང་མཐའ་གཞན་འགོག་པའི་རིགས་པ་ཞེས་ནས་ད་འདི་འདྲ་ཡང་ཡོང་སྲིད་པ་རེད།
13:10  ད་ག་རེ་བྱས་ནས་བྱུང་བ་རེད་ལབ་དུས། ཨ་ནི་༼why༽༼ཝེ།༽ལབ་ཡོང་དུས། ༼possibility༽འདི་གཅིག་༼possibility༽འདི་གཅིག་༼possibility༽འདི་གཅིག་སྲིད་པ་རེད། འདི་གཅིག་སྲིད་པ་རེད། 
13:20 འདི་གཅིག་སྲིད་པ་རེད། ད་དེ་ལ་འགལ་འདུ་འདུག། དེ་ལའང་འགལ་འདུ་འདུག་ དེ་ལའི་འགལ་འདུ་འདུག་  ད་དི་འགལ་འདུ་ཏོགས་༼སེ་༽ཉུང་བ། 
13:30 ད་ང་ཚོས་ཐོག་མ་མེད་པ་ཞིག་བཤད་པ་ཡིན་ན། ཧོབ་འདི་གང་ལ་རིགས་འགའ་ཤས་ཡང་འདི་མ་བདེ་བ་ཞིག་ཆགས་ཀྱི་ཡོད་རེད། ད་འདོད་པ་ཁེངས་ཡོང་གི་ཡོད་མེད་ངས་མི་ཤེས་འདི། 
13:37 གང་ལྟར་འདོད་ཚུལ་དེ་ལ་གནོད་པ་ཉུང་བ་རེད། སྒྲུབ་བྱེད་མང་བ་རེད། འོ་འདི་འདྲ་ཞིག་རེད་ཤག། ༼ག་ཡི་རྗེས་ལ་ཤད་བྲི་མི་དགོས།༽

2023-04-17 06:18 UTC, geshecelon requested changes
00:10  སྒོ་ལྔའི་ཤེས་པས་ཐད་ཀར་སྤྱོད་ཡུལ་དུ་ཡོད་པ་ཞིག་ཡིན་དགོས་ཡི་མ་རེད་པ་  རེད་པ་ད་   ༼འེས་༽ལྐོག་ཏུ་གྱུར་པའི་དོན་མང་པོ་ཞིག་ཡོད་རེད་བ་

00:19  དཔེར་ན་མི་རྟག་པ་ཕྲ་མོ་འདྲ་པོ་ཆ་བཞག་ན༑ འདི་ང་ཚོ་ང་ཚོའི་མངོན་སུམ་གྱུར་ཐུབ་ཡ་མི་འདུག་བ་༼ག༽ ཁོ་བསམ་བློ་བཏང་ནས་ཚོད་དཔག་བྱེད་ཐུབ་པ་ཞིག་འདུག་མ་གཏོགས་   ད་ད་རིང་ཁ་སང་

00:29 གཅིག་ཚན་རིག་གིས་རྡུལ་ཕྲ་མོའི་གང་ལ་མར་གཅིག་(atom) ༼ཨེ་ཊོམ༽ དེ་འདྲ་མ་སླེབས་ཡེང་དུས་ཙ་ནས་ཁོ་སྐད་གཅིག་སྐད་གཅིག་གིས་


 01:04  སྔ་མོ་༼ད་འེས་༽ཆོས་ལུགས་འཛམ་གླིང་བཀོད་པ་པོ་འདོད་མཁན་གྱི་ཆོས་ལུགས་ཚོའི་ནང་ལོག་ལ་ཡ་འཛམ་གླིང་འདི་གཅིག་པོ་གཅིག་མ་གཏོགས་ཙམ་གཞན་དག་གསུང་གི་ག་ཡོ་མ་རེད། 



01:20 དཀོན་མཆོག་གི་བཀོད་པ་རེད་ཟེར་ཡ་བཟོ་འདྲོ་བོ་འདི་གང་འགྲོ་དེའི་འདུག་བ༼ག༽།   བྱས་ཙང་འདི་འདྲ་ཡིན་དུས་གང་ལྟར་དེ་ཚེ་དེའི་དུས་ཀྱི་མ་རྟོགས་པ་དང་མ་ཤེས་པ་མང་པོ་ཞིག་དེ་འདྲས་ཤེས་ཀྱི་ཡོད་རེད་བ། 



01:57 སྤྱིར་ཤེས་པ་ལ་ཕྲ་རགས་མང་པོ་ཞིག་བཤད་ཀྱི་འདུག་བ། ཤེས་པ་རགས་པ་དེ་ཚོར་འགྲེས་ང་ཚོའི་མངོན་དུ་གྱུར་ནས་མངོན་གྱུར་ཆགས་དེ་ཡི་འདུག༼སྟེ༽ ཤེས་པ་ཕྲ་མོའི་རིགས་མང་པོ་གཅིག་ཕལ་ཆེར་ལྐོག་གྱུར་རེད།

02:07 ད་ཤིན་ཏུ་ལྐོག་གྱུར་ཡང་ཡོང་གི་མེད་འགྲོ།༼འདི་ལ་ཤད་མི་དགོས་༽ བྱས་ཙང་ད་དེ་འདྲ་གཅིག་གི་ཨ་ནི་རྒྱུན་གྱི་གང་ལ་བསམ་བློ་གཏོང་དགོས་བྱུང་ན་ལྐོག་གྱུར་རེད་འདུག་ག



02:49 ཁོ་རྒྱུ་དེ་ལ་ལྷན་ཅིག་བྱེད་པའི་རྐྱེན་ཡོདརེད་འདི། ཉེར་ལེན་གྱི་རྐྱེན་ཡོད་རེད། ཉེར་ལེན་མེད་ན་ད་གང་ལྟར་རྒྱུ་རྒྱུ་གང་ཞིག་འབྲས་བུ་དེའི་ངོ་བོར་འགྱུར་འགྲོ་མཁན་ཞིག་ཉེར་ལེན་གྱི་རྒྱུ་ཟེར་ཡ་གཅིག་བཤད་ཀྱི་འདུག་བ༼ག༽།


03:20 ལ་ཁོ་རང་གཅིག་གོ་མནན་ནས་འགྲོ་ཡ་ཡོད་༼བསྡད་༽པ་གཅིག་ཁོ་གཉིས་བོ་འདི་མི་འདྲ་བ་ཞིག་ཆགས་ཀྱི་འདུག་ག དངོས་པོའི་གཤིས་ཀ་མི་འདྲ་བ་གཅིག་གི་
03:29 རང་རང་གི་ཉེར་ལེན་གྱི་རྒྱུ་འདི་མི་འདྲ་བ་ཞིག་སླེབས་དགོས་ཡི་༼གི་༽རེད་བ། ས་འདི་འདྲ་ཡིན་དུས་ཙ་ནས་ད་ད་ལྟའི་ཤེས་པའི་རྒྱུན་འདི་སྐྱེ་ཁ་མའི་ཤེས་པ་ཤེས་པ་དང༌

03:50 ཤེས་པ་ལ་ཡ། གསལ་རིག་ཟེར་བ་ཡག་པོ་ཞིག་ཤེས་དགོས་ཀྱི་ཡོད་རེད། ༼དཔེར་ན་༽ད་སྤྱིར་བཏང་མི་ཚོས་ཕར་བཞག་ནས་ བསྟན་པའི་༼དཔེར་ན་༽དཔེ་ཆ་སྦྱོང་མཁན་ཚེས་ཁ་ནས་གསལ་རིག་ཅེས་ནས་བརྒྱ་ཕྲག་སྟོང་ཕྲག་

04:20 ངོ་འཕྲོད་པ་ཞིག་ཕལ་ཆེར་ཡོད་པ་རེད། དེ་གལ་ཆེན་པོ་འདུག་བ་༼ག་༽སྔོན་ལ་ཐར་པ་ཐམས་ཅད་མཁྱེན་པ་ཕར་བཞག་ སྔོན་ལ་ང་རང་ཚོའི་༼འེས་༽ག་རེ་ཟེར་གོ་འདི་༼འེས༽
04:30 ག་རེ་ཟེར་གོ་ཕ་གི་དངོས་པོ་གཏན་ལ་ཕབ་ཡའི་ནང་ལོག་ལ་གཟུགས་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་ཞེས་བཤད་དེ་ཡ་ཡི་ཤེས་པ་ཟེར་ཡ་འདི་ཡག་པོ་ཞིག་ངོས་འཛིན་ཡ་ལ་ད་༼ཅིག༽གསལ་རིག་གི་མྱོང་བ་འདྲ་པོ་འདུགས་

05:00 དེ་དང༌རིགས་མཐུན་པའི་ད་རིགས་འདྲའི་རྒྱུ་ཞིག་དགོས་གི་རེད་དགོས་གི་མ་རེད། ད་ཁ་སང་ལབ་པ་ནང་བཞིན། ཀླད་པ་ལས་ཤེས་པ་སྐྱེ་ཀྱི་པ་༼ཡོད་༽རེད། 

05:21 དཔེ་༼ར་པོ་༽ཆ་བཞག་ན། ཚན་རིག་པ་གཅིག་གིས་སྐབས་ཤིག་འགྲེལ་བཤད་འདི་འདྲ་ཞིག་བྱུང། གཞན་གྱི་སྡུག་བསྔལ་འེས་མཐོང་ནས་
05:29 སེམས་ལ་ཡ་མི་བདེ་བ་ཡོད་དེ་བ་དེ་དང་མི་བདེ་༼བ་༽ཡོད་པས་གནས་སྐབས་དང༌། ཨ་ནི་རང་གི་སྡུག་བསྔལ་གྱིས་རང་ལ་མི་བདེ་བ་ཡོད་དེ་བའི་མི་བདེ་བའི་ཚོར་བ་

05:49 ངས་དེ་དུས་རྩེད་མོ་འདྲ་ཙེད་བཅས་རེད་བ་ད་ཏ་ཧ་ལས་པའི་ཁྱད་པར་ཆེན་པོ་ཡོད་རེད་བ། གཞན་གྱི་སྡུག་བསྔལ་བསམས་ནས། དེ་ལ་བརྟེན་ནས་སེམས་མི་བདེ་བ་ཡོད་དེ་བ་འདི་སྙིང་སྟོབས་འདུག་བ༼ག༽། 

06:19 ལ་ཡ། མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་ཐོག་ཏུ་བབས་ནས་དེས་མནན་པ་ཞིག་རེད་བ། ཀླད་པས་དེ་གཉིས་ངོས་འཛིན་འདི་༼གཉིས་༽དབྱེ་བ་འབྱེད་ཤེས་ཀྱི་མེད་པའི་ཟོ་འདྲ་པོ་ཞིག་འདུག་ དེ་༼འདྲའི༽དུས་ཤེས་སོང་
06:29 དེ་ཡང་ད་མུ་མཐུད་ནས་ཞིབ་འཇུག་བྱེད་དགོས་ཡ་རེད་ཅེས་ནས་སྐད་ཆ་བྱུང།  བྱས་ཙང་འདི་འདྲ་ཡིན་དུས་དེས་ན་༼དཔེར་ན་༽གལ་སྲིད་འདི་བདེན་པ་ཡིན་ན་རེད་ད། ཁོ་སྡུག་བསྔལ་གྱི་ཚོར་བ་དེ་ཙམ་ཞིག་རེད་མ་གཏོགས།

07:18 རང་གི་སྡུག་བསྔལ་༼གྱི་༽ཞིག་མནར་དེ་བ་འདི་མི་འདོད་པ་རེད་བ། དུས་ནམ་ཡང་མི་དགོས་པ་རེད་བ། ༼རང་གི་༽རང་ཉིད་སྡུག་བསྔལ་གྱིས་མནར་དེ་ཡི་སྡུག་བསྔལ་འདི་
07:28 མི་འདོད་པ་ཡིན་དུས་ཙ་ནས། ང་ཚོས་ཐར་པ་བསྒྲུབ་ཀྱི་ཡིན་ཐམས་ཅད་མཁྱེན་པའི་གོ་འཕང་བསྒྲུབ་ཀྱི་ཡིན་ཟེར་ཡ་འདི་དེར་ཐུག་པ་རེད་བ་ཡ༼ཡ་མི་འདུག༽།  རེད་བ་༼ཡ་༽ གཞན་གྱི་སྡུག་བསྔལ་བསམ་ཡ་འདི་
07:55 རགས་པ་རགས་པ་རགས་པ་རགས་པ་རགས་པ་ཞིག་འགྲེལ་བཤད་རྒྱབ་ཀྱི་ཡོད་རེད་མ་གཏོགས། དེ་འདྲ་ཡིན་དུས་འགྲེལ་བཤད་ཆ་ཚང་རྒྱབ་མ་ཐུབ་ཡ་ཞིག་༼ཅིག༽གི་གཞི་འདི་ཀྱི་ཨ་ནེ་༼འེས་མ་རེད་ད་༽འགྲེལ་བཤད་ཆ་ཚང་རྒྱ་མ་ཐུབ་

ཁྱེད་རང་གིས་ངོས་ནས་འགོ་ནས་བཀའ་སློབ་དེ་ཉན་ནས་གཟབ་གཟབ་བྱས་ནས་གཟིགས་རོགས།

2023-04-27 06:59 UTC, jigmasth commented
Plz approve it.

2023-05-22 05:31 UTC, merged