STT001-08
MonlamAI/STT001 pull request #11
Opened 2023-01-26 17:54 UTC by Topchen2023

Final
Done and please check.

2023-04-04 04:53 UTC, Tenzindharten requested changes
༡. 00:00 ད་ཨོ་[འདི་]དེ་འདྲའི་[ཀྱི་]རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས། ཐར་པ་ཟེར་[ཡས་]ཡག་ཀྱི་སྐད་ཆ་དེ་སླེབ[ས་]ཡོང་གི་འདུག་བ།
༢. 00:04 ཐར་པ་དེ་ཕྱི་ལོག[ས]་ཀྱི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། [གཅིག་དག་ཞིང་བཟོ་འདྲ་གཅིག་མ་ཡིན་པ། བསྐྱར་ཟློས་རེད་བཞག ]
༣.  00:07 གཅིག་དག་ཞིང་བཟོ་འདྲ་གཅིག་མ་ཡིན་པ། ཐར་པ་ཟེར་ཡག་དེ་[འདི་]ནང་སེམས་རྒྱུད་ཀྱི་[ལྟ]ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཨིའི་ཟག་པའི་སྐྱོན་[འདི]དེ་གའི་དེ་མེད་པ་ཆགས་ཀྱིས།[བྱེད་]
༤. 00:16 [འདི་]དེའི་རྩ་བ་བདག་ཏུ་འཛིན་པ་རེད།   བདག་ཏུ་འཛིན་པ་མེད་པ། བདག བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་ཨེ་ནི་གཉེན་པོ་བྱས་ནས། 
༥.  00:23 [ད་ལྟ་]བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕར་འགགས་སོང་ན།  [ཨ]ཨེ་ནི་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 
༦. 00:35 སྡུག་བསྔལ་འདེ་ཉེ་བར་ཞི་བ་རེད་། སྡུག་བསྔལ་ལས་ཐར་བ་རེད་ཟེར་ཡ་།   ཐར་པ་ཅིག་བཤད་དེ་འདྲའི་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། [འདིའི་གསུང་ཕབ་གནང་ཡ་དེ་ཏག་ཏག་བསྡད་མི་འདུག བསྐྱར་ཞིབ་གནང་དགོས། ]
༧. 00:36 ཨེ་ནི་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་[ཞིག་]ཆགས་ཡོང་གི་འདུག་ག འཛམ་བུ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་[པའི་]་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོད་རེད་དེ།[ཏེ་། ]
༨. 00:43 ཡིན་ནས་[འདིའི་]དེའི་ནང་ནས་བདག་མེད་པ་ཟེར་མཁན་[་ཞེས་པ་]དེ་གསུང་མཁན་[འདི་]དེ། སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་[ཀྱང]་མི་འདུག་ག [བ་།]

༢༠༢༣་༠༤་༤

2023-04-04 06:13 UTC, Tenzindharten requested changes
00:48 འོ་[འདི]དེ་འདྲས་[འདྲ]་ཡིན་དུས་ད་[ཏ]་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། ད་སེམས་ཅན་ལ་འཚེ་བ་[མི་བྱེད་པ་ཙམ་དེ་]
00:57 མི་བྱེད་པ་ཙམ་དེ། [འདི་]གཅེར་བུ་བ་[པར་]ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་[པར་]རེད། 
01:02 མུ་སྟེགས་རྒྱལ་བ་པ། ཨིའི་ཨིའི་མཧཱ་ཝིར་རྒྱལ་བ་པ། ཁོང་གི་ད་རྗེས་འབྲངས། བྱས་མུ་སྟེགས་གཅེར་བུ་བ་[པ་]རྒྱལ་བ་པ་ཟེར་མཁན་དེ[འདི་]གའི་དེ། [གེ་འདི།] 
01:11 [ཁོ་ཚོ་]སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏག་བཏགས་[ས]་པ་མིན་འགྲོ།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ་སེ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་[ལྟ་]སྤྱོད་པ་ད་[ལྟ]་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་[གྱི་]རེད།
01:20 [ཞུ་འུ་]ཞེ་བོ་ཞིག་འདུག་ག[བ] [ལྟ་]འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད། ད་[ལྟ་]ང་ཚོས་ཁས་ལེན་དགོས་རེད་བ། [ལྟ]་བྱས་ཙང་འདི་འདྲས་[འདྲ་]ཡིན་དུས།   
01:27 [ལྟ་]ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ[ར]ལ་གཏུག་ཡོང་གི་རེད།
01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་ལ་བསླབ་ཡ[་ལྟ]ད་ཁ་ཐུག་དེ་[ཏེ་]གཞན་ལ་གནོད་པ་བྱས་ན།
01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་[བྱེད་]བྱས་ནས། འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག[ས་]པའི་ཐོག་ནས། ད་[ཏ་]དེ་འཚེ་བ་སྡོམ་པ་བཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོད་རེད་དེ། [ཏེ་]ཡིན་ནས་ ་
01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནི་རང་དང་རང་འདྲ་བར་[ཏ]ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན། [བལྟས་ནས།] དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ[་ཏ]ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་ག
02:00 ཏ་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།
02:06 [འདི་]ཁྱེད་རང་ལ་གནོད་ཀི་[ཀྱི་]རེད་ཟེར་ཡག་གཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས། དེའི་རྒྱུ་ལྡོག་ཡག་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་ག 
02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ཨིའི་ཨིའི་ག་རེ་[རེད་]ཟེར་བ་[གོ་]རེད། བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་[པ]་བ་ཡིན་དུས་ཙ་ནས། 
02:19 དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གེས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།[འདི་ནས་ཏག་ཏག་ཕབ་མི་འདུག ]
02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་[འདི་]དེ་དང་འབྲེལ་ནས་སླེབ[ས]་ཡོང་གི་འདུག་བ། ཐར་པ་མེད་ན། 
02:36[ ཨ་]ཨེ་ནི་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ། སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་སེ་གས་[གེས]་བསམ་ཡག[ས་]མི་འདུག་ག ད[་ལྟ་]གང་[འདྲ་]དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས། གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས[་གེས་]མི་འདུག་ག
02:45  [ཏ་]ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་[ཡས་ཀྱི་]ཟག་པ་དེ་འབྲལ་[བྲལ་]རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།
02:52  [ཨ་]ཨེ་ནི་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་[ཏ]ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག་གིས།
03:00 ཁོ་གཅིག[་དེས་]དེ་ལས་ཐར་ཐབས་གཅིག་[ཤིག]་མཐོང་གིན་མཐོང་གིན་ལ། [ཏ་]ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ[ར་]ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་[དེས་ཀྱི་]དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག[ས་]སེ་འགྲོ་བསྡད་ཡ་དེ། [དེས་ཡ་འདི།]
03:09[ཏ་]ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡག་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་[ར་]ཁྱད་ཅིག་[ཞིག་]འདུག་ག [བ།] ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས། [ས་ཀྱི་]
03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག[་ཞུ་འོ་ཅིག་]ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་[དེས]་པ་གཅིག་[ཞིག་]མཐོང་ཡོང་དུས། སྙིང་རྗེ་འདི། 
03:24 རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག ཨིའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་[ཞིག་]མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་[གྱི་]མནར་བ་དེ[་ཏ་]ད་གང་དྲག་ཟེར་གཅིག[ཟོ་རོ་ཅིག] ཨེ་ནི་ས་སོར་འུ་འདྲ་གཅིག་ཐུག 
03:34 འུ་འདྲ་ཞིག་ཐུག།   [ཏ་]ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནི་དབུགས་རིང་བཏང་བྱས་[སྡོད་]བསྡད་རྒྱུ་རེད་མ་གཏོགས། [ལྟོག་བྱེད་ཡས་གེ་གེས་] གཞན་ག་གས་མི་འདུག་ག  [ཏ་]ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད[་བ་རེད་]བ།

༢༠༢༣་༠༤་༤ ཉིན།

2023-04-04 09:03 UTC, Tenzindharten requested changes
03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་[རྒྱུ་ཡོད་པ་]མཐོང་གྱིས་རྒྱ་ཆེན་པོ[་བྱས]་འདུག་སེ་[ས་]མཐོང་བྱས་བྱུང་པ་ཡིན་ན། སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་
03:46  འདུག་ག [བྱས་ཙང་]སེ་[འདྲི]དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་[ཀྱི་]སྙིང་རྗེ་དེས་དེ་ག་རེ་ཟེར་བ། [གོ་རེད་] ཕ་གིའི་[གེར]་ཨིའི་ད་ལྟ་[བ་]བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་[དེ་ཤོད་]བཤད་ཡོང་གི་འདུག་ག [བ། ]
03:54 ཐར་པ་འདི་འདྲའི་[འདྲེས་]སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་[ཟེར་]བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་བསྡད་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ། [དེས་པ་དེས་ལ་ཡ་]
04:03 སྙིང་རྗེ་སྐྱེ་ཡ[ར་]མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་[འདི་]དེ་འདྲས་[འདྲེས་]ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་[ཏ་]འདྲ་གི་[ཡི་]རེད་དེ། ཡིན་ནས་ཨིའི་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་དེ། སངས་རྒྱས་པའི་[འདི་]
04:13 [སངས་རྒྱས་པའི་]འཚེ་་་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་སེ་ཏོག་སེ་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།
04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ། ལྟ་བ་འདི་ད་ཨོ། [ཏ]་གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། [ཨ་ནི་]
04:29 ཨེ་ནི་ཨིའི་ག་རེ་ཟེར་ག། [གར་ཟ་]བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་[ཏ་པས་སྡོམ]་ཆེན་པོ་རེད།
04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་ཨིའི་གང་ཟག་རང་རྐྱ་[སྐྱ]་བ། ད་ལྟ་ད་[རེད་བ་ཏ་]བདག་རང་རྐྱ[སྐྱ]་བ་། 
[འདི་གཉིས་བར་དུ་ཡག་པོ་མཐུན་ཐུག་མི་འདུག་བསྐྱར་དུ་ཡག་པོ་གནང་དགོས་འདུག ]
04:47 བདག་རང་རྐྱ་[སྐྱ]་བ་གྲུབ་པ་འདི་འདྲས་[འདྲེས]་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།
04:54 བདག་ལྟའི་[བའི་]ཞེན་ཡུལ་དེ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན[་དང་]མ་ཐུབ་ནས། འགོག་པ་ལ་བརྩོན་བསྡད་མཁན་དེ་[འདི་]ནང་པ། འོ་[འདི་]དེ་གསུང་ཡིན་[ཡོད་]པ་རེད།
05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་སེ། འདི་[འདྲེས་]འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ། 
05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནི་གཞན་སྡེ་ཟེར་གྱིས་ནས་[ཞེས་]གསུངས་པ་མིན་འགྲོ། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌སེ། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ཞིང་། [འདིའི་གོང་འོག་གཉིས་བར་ཏོག་ཙམ་ཏག་ཏག་ཅིག་མི་འདུག བསྐྱར་ཞིབ་གནང་། ]
05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་[བཟློག]་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 
05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 
05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི[ས་]བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།
[འདིའི་གོང་འོག་གཉིས་ནས་ཀྱང་ཏོག་ཙམ་ཏག་ཏག་མཐུན་མི་འདུག. བསྐྱར་ཞིབ་གནང་རོགས། ]
05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི[ཡས་ཀྱི་།] ཨིའི་ཕལ་ཆེར་འདི་[ཏ་]ད་དཔེར་ན་ཕྱིས་ཀྱི་[་ཡི་]ཕྱི་ཟེར་གོ་མ་རེད་བས། 
05:41 དེ་སྔ་ང་ཚོ་བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང་[ཡེས་ཡེ་ཤུ་དང༌]། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་མི་འདུག] [ཡས]་ཕལ་ཆེར་རེད། [དེའི་བར་བསྐྱར་ཞིབ་གནང་དགོས། ]
05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་[ཡས་ཞིག་]བཤད་ཀི་[ཆགས་ཀྱི་]འདུག་ག. [བ་།] [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་གི་མི་འདུག ]
05:53[ བྱས་ཙང་ཏ]ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ། དག་ཞིང[་དུ་]ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།

༢༠༢༣་༠༤་༤ དགོང་དྲོ།

2023-04-05 06:24 UTC, Topchen2023 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft Himalaya";
	panose-1:1 1 1 0 1 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.timestamp
	{mso-style-name:timestamp;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲེས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་04:13 སངས་རྒྱས་པའི་  འཚེ་་་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 04:29 ཨེ་ནི་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་སྐྱ་བར་རེད་བ་ཏ་བདག་རང་སྐྱ་བ་།04:47 བདག་རང་རྐྱ་་བ་གྲུབ་པའི་འདི་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡདམཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་འདི་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨ་ནི་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་བཟློག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག05:53 ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ་།༢༠༢༣་༠༤་༤ དགོང་དྲོ།  Sent from Mail for Windows From: TenzindhartenSent: 04 April 2023 14:33To: MonlamAI/STT001Cc: Topchen2023; AuthorSubject: Re: [MonlamAI/STT001] STT001-08 (PR ***@***.*** requested changes on this pull request.03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་[རྒྱུ་ཡོད་པ་]མཐོང་གྱིས་རྒྱ་ཆེན་པོ[་བྱས]་འདུག་སེ་[ས་]མཐོང་བྱས་བྱུང་པ་ཡིན་ན། སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་03:46 འདུག་ག [བྱས་ཙང་]སེ་[འདྲི]དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་[ཀྱི་]སྙིང་རྗེ་དེས་དེ་ག་རེ་ཟེར་བ། [གོ་རེད་] ཕ་གིའི་[གེར]་ཨིའི་ད་ལྟ་[བ་]བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་[དེ་ཤོད་]བཤད་ཡོང་གི་འདུག་ག [བ། ]03:54 ཐར་པ་འདི་འདྲའི་[འདྲེས་]སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་[ཟེར་]བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་བསྡད་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ། [དེས་པ་དེས་ལ་ཡ་]04:03 སྙིང་རྗེ་སྐྱེ་ཡ[ར་]མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་[འདི་]དེ་འདྲས་[འདྲེས་]ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་[ཏ་]འདྲ་གི་[ཡི་]རེད་དེ། ཡིན་ནས་ཨིའི་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་དེ། སངས་རྒྱས་པའི་[འདི་]04:13 [སངས་རྒྱས་པའི་]འཚེ་་་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་སེ་ཏོག་སེ་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ། ལྟ་བ་འདི་ད་ཨོ། [ཏ]་གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། [ཨ་ནི་]04:29 ཨེ་ནི་ཨིའི་ག་རེ་ཟེར་ག། [གར་ཟ་]བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་[ཏ་པས་སྡོམ]་ཆེན་པོ་རེད།04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་ཨིའི་གང་ཟག་རང་རྐྱ་[སྐྱ]་བ། ད་ལྟ་ད་[རེད་བ་ཏ་]བདག་རང་རྐྱ[སྐྱ]་བ་།[འདི་གཉིས་བར་དུ་ཡག་པོ་མཐུན་ཐུག་མི་འདུག་བསྐྱར་དུ་ཡག་པོ་གནང་དགོས་འདུག ]04:47 བདག་རང་རྐྱ་[སྐྱ]་བ་གྲུབ་པ་འདི་འདྲས་[འདྲེས]་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།04:54 བདག་ལྟའི་[བའི་]ཞེན་ཡུལ་དེ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན[་དང་]མ་ཐུབ་ནས། འགོག་པ་ལ་བརྩོན་བསྡད་མཁན་དེ་[འདི་]ནང་པ། འོ་[འདི་]དེ་གསུང་ཡིན་[ཡོད་]པ་རེད།05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་སེ། འདི་[འདྲེས་]འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ།05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནི་གཞན་སྡེ་ཟེར་གྱིས་ནས་[ཞེས་]གསུངས་པ་མིན་འགྲོ། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌སེ། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ཞིང་། [འདིའི་གོང་འོག་གཉིས་བར་ཏོག་ཙམ་ཏག་ཏག་ཅིག་མི་འདུག བསྐྱར་ཞིབ་གནང་། ]05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་[བཟློག]་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌།05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌།05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི[ས་]བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།[འདིའི་གོང་འོག་གཉིས་ནས་ཀྱང་ཏོག་ཙམ་ཏག་ཏག་མཐུན་མི་འདུག. བསྐྱར་ཞིབ་གནང་རོགས། ]05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི[ཡས་ཀྱི་།] ཨིའི་ཕལ་ཆེར་འདི་[ཏ་]ད་དཔེར་ན་ཕྱིས་ཀྱི་[་ཡི་]ཕྱི་ཟེར་གོ་མ་རེད་བས།05:41 དེ་སྔ་ང་ཚོ་བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང་[ཡེས་ཡེ་ཤུ་དང༌]། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་མི་འདུག] [ཡས]་ཕལ་ཆེར་རེད། [དེའི་བར་བསྐྱར་ཞིབ་གནང་དགོས། ]05:50 བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་[ཡས་ཞིག་]བཤད་ཀི་[ཆགས་ཀྱི་]འདུག་ག. [བ་།] [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་གི་མི་འདུག ]05:53[ བྱས་ཙང་ཏ]ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ། དག་ཞིང[་དུ་]ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།༢༠༢༣་༠༤་༤ དགོང་དྲོ།—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2023-04-05 06:25 UTC, Topchen2023 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft Himalaya";
	panose-1:1 1 1 0 1 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.timestamp
	{mso-style-name:timestamp;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད། 01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ། 01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ་།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་།01:20 ཞེ་བོ་ཞིག་འདུག་ག ད་འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་འདི་འདྲས་ཡིན་དུས་།   01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡ་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་རྩ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་པ་ཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོདརེད་དེ་ཡིན་ནས་ 01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨ་ནི་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན།01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་བ།02:00 ཏ་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་བ། 02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།   བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནི་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག་སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 02:36ཨེ་ནི་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་བ་ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡས་གས་མི་འདུག་ག02:45  ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།02:52  ཨེ་ནི་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡ་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 03:24 རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག03:34 ཨེ་ནི་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནི་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས།  གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།  Sent from Mail for Windows From: TenzindhartenSent: 04 April 2023 11:43To: MonlamAI/STT001Cc: Topchen2023; AuthorSubject: Re: [MonlamAI/STT001] STT001-08 (PR ***@***.*** requested changes on this pull request.00:48 འོ་[འདི]དེ་འདྲས་[འདྲ]་ཡིན་དུས་ད་[ཏ]་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། ད་སེམས་ཅན་ལ་འཚེ་བ་[མི་བྱེད་པ་ཙམ་དེ་]00:57 མི་བྱེད་པ་ཙམ་དེ། [འདི་]གཅེར་བུ་བ་[པར་]ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་[པར་]རེད།01:02 མུ་སྟེགས་རྒྱལ་བ་པ། ཨིའི་ཨིའི་མཧཱ་ཝིར་རྒྱལ་བ་པ། ཁོང་གི་ད་རྗེས་འབྲངས། བྱས་མུ་སྟེགས་གཅེར་བུ་བ་[པ་]རྒྱལ་བ་པ་ཟེར་མཁན་དེ[འདི་]གའི་དེ། [གེ་འདི།]01:11 [ཁོ་ཚོ་]སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏག་བཏགས་[ས]་པ་མིན་འགྲོ། སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ་སེ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་[ལྟ་]སྤྱོད་པ་ད་[ལྟ]་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་[གྱི་]རེད།01:20 [ཞུ་འུ་]ཞེ་བོ་ཞིག་འདུག་ག[བ] [ལྟ་]འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད། ད་[ལྟ་]ང་ཚོས་ཁས་ལེན་དགོས་རེད་བ། [ལྟ]་བྱས་ཙང་འདི་འདྲས་[འདྲ་]ཡིན་དུས།01:27 [ལྟ་]ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ[ར]ལ་གཏུག་ཡོང་གི་རེད།01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་ལ་བསླབ་ཡ[་ལྟ]ད་ཁ་ཐུག་དེ་[ཏེ་]གཞན་ལ་གནོད་པ་བྱས་ན།01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་[བྱེད་]བྱས་ནས། འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག[ས་]པའི་ཐོག་ནས། ད་[ཏ་]དེ་འཚེ་བ་སྡོམ་པ་བཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོད་རེད་དེ། [ཏེ་]ཡིན་ནས་ ་01:45 རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནི་རང་དང་རང་འདྲ་བར་[ཏ]ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན། [བལྟས་ནས།] དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ[་ཏ]ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་ག02:00 ཏ་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།02:06 [འདི་]ཁྱེད་རང་ལ་གནོད་ཀི་[ཀྱི་]རེད་ཟེར་ཡག་གཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས། དེའི་རྒྱུ་ལྡོག་ཡག་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་ག02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ཨིའི་ཨིའི་ག་རེ་[རེད་]ཟེར་བ་[གོ་]རེད། བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་[པ]་བ་ཡིན་དུས་ཙ་ནས།02:19 དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད། སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གེས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།[འདི་ནས་ཏག་ཏག་ཕབ་མི་འདུག ]02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་[འདི་]དེ་དང་འབྲེལ་ནས་སླེབ[ས]་ཡོང་གི་འདུག་བ། ཐར་པ་མེད་ན།02:36[ ཨ་]ཨེ་ནི་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ། སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་སེ་གས་[གེས]་བསམ་ཡག[ས་]མི་འདུག་ག ད[་ལྟ་]གང་[འདྲ་]དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས། གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས[་གེས་]མི་འདུག་ག02:45 [ཏ་]ད་ཡིན་ནས་། ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་[ཡས་ཀྱི་]ཟག་པ་དེ་འབྲལ་[བྲལ་]རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།02:52 [ཨ་]ཨེ་ནི་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་[ཏ]ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག་གིས།03:00 ཁོ་གཅིག[་དེས་]དེ་ལས་ཐར་ཐབས་གཅིག་[ཤིག]་མཐོང་གིན་མཐོང་གིན་ལ། [ཏ་]ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ[ར་]ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་[དེས་ཀྱི་]དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག[ས་]སེ་འགྲོ་བསྡད་ཡ་དེ། [དེས་ཡ་འདི།]03:09[ཏ་]ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡག་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་[ར་]ཁྱད་ཅིག་[ཞིག་]འདུག་ག [བ།] ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས། [ས་ཀྱི་]03:15 སྡུག་བསྔལ་ཞེ་བོ་གཅིག[་ཞུ་འོ་ཅིག་]ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་[དེས]་པ་གཅིག་[ཞིག་]མཐོང་ཡོང་དུས། སྙིང་རྗེ་འདི།03:24 རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག ཨིའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་[ཞིག་]མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་[གྱི་]མནར་བ་དེ[་ཏ་]ད་གང་དྲག་ཟེར་གཅིག[ཟོ་རོ་ཅིག] ཨེ་ནི་ས་སོར་འུ་འདྲ་གཅིག་ཐུག03:34 འུ་འདྲ་ཞིག་ཐུག། [ཏ་]ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནི་དབུགས་རིང་བཏང་བྱས་[སྡོད་]བསྡད་རྒྱུ་རེད་མ་གཏོགས། [ལྟོག་བྱེད་ཡས་གེ་གེས་] གཞན་ག་གས་མི་འདུག་ག [ཏ་]ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད[་བ་རེད་]བ།༢༠༢༣་༠༤་༤ ཉིན།—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2023-04-05 06:25 UTC, Topchen2023 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft Himalaya";
	panose-1:1 1 1 0 1 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.timestamp
	{mso-style-name:timestamp;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->00:00 ད་ཨོ་དི་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་་ཀྱི་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་བ།00:04 ཐར་པ་དེ་ཕྱི་ལོག་ཀྱི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་ཟོ་འདྲ་གཅིག་མ་ཡིན་པ།00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གེའི་དེ་མེད་པ་ཆགས་ཀྱིས།00:16 དེའི་རྕ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་གཉེན་པོ་བྱས་ནས། 00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕ་འགགས་སོང་ན།་  ཨ་ནི་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 00:35 སྡུག་བསྔལ་དེ་ཉེས་པར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ་།   ཐར་པ་ཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 00:36 ཨེ་ནི་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོདརེད་དེ། 00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག༢༠༢༣་༠༤་༤  Sent from Mail for Windows From: TenzindhartenSent: 04 April 2023 10:23To: MonlamAI/STT001Cc: Topchen2023; AuthorSubject: Re: [MonlamAI/STT001] STT001-08 (PR ***@***.*** requested changes on this pull request.༡. 00:00 ད་ཨོ་[འདི་]དེ་འདྲའི་[ཀྱི་]རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས། ཐར་པ་ཟེར་[ཡས་]ཡག་ཀྱི་སྐད་ཆ་དེ་སླེབ[ས་]ཡོང་གི་འདུག་བ།༢. 00:04 ཐར་པ་དེ་ཕྱི་ལོག[ས]་ཀྱི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། [གཅིག་དག་ཞིང་བཟོ་འདྲ་གཅིག་མ་ཡིན་པ། བསྐྱར་ཟློས་རེད་བཞག ]༣. 00:07 གཅིག་དག་ཞིང་བཟོ་འདྲ་གཅིག་མ་ཡིན་པ། ཐར་པ་ཟེར་ཡག་དེ་[འདི་]ནང་སེམས་རྒྱུད་ཀྱི་[ལྟ]ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཨིའི་ཟག་པའི་སྐྱོན་[འདི]དེ་གའི་དེ་མེད་པ་ཆགས་ཀྱིས།[བྱེད་]༤. 00:16 [འདི་]དེའི་རྩ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་ཏུ་འཛིན་པ་མེད་པ། བདག བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་ཨེ་ནི་གཉེན་པོ་བྱས་ནས།༥. 00:23 [ད་ལྟ་]བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕར་འགགས་སོང་ན། [ཨ]ཨེ་ནི་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད།༦. 00:35 སྡུག་བསྔལ་འདེ་ཉེ་བར་ཞི་བ་རེད་། སྡུག་བསྔལ་ལས་ཐར་བ་རེད་ཟེར་ཡ་། ཐར་པ་ཅིག་བཤད་དེ་འདྲའི་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། [འདིའི་གསུང་ཕབ་གནང་ཡ་དེ་ཏག་ཏག་བསྡད་མི་འདུག བསྐྱར་ཞིབ་གནང་དགོས། ]༧. 00:36 ཨེ་ནི་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་[ཞིག་]ཆགས་ཡོང་གི་འདུག་ག འཛམ་བུ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་[པའི་]་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོད་རེད་དེ།[ཏེ་། ]༨. 00:43 ཡིན་ནས་[འདིའི་]དེའི་ནང་ནས་བདག་མེད་པ་ཟེར་མཁན་[་ཞེས་པ་]དེ་གསུང་མཁན་[འདི་]དེ། སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་[ཀྱང]་མི་འདུག་ག [བ་།]༢༠༢༣་༠༤་༤—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 

2023-04-05 08:20 UTC, Tenzindharten requested changes
03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་[རྒྱུ་ཡོད་པ་]མཐོང་གྱིས་རྒྱ་ཆེན་པོ[་བྱས]་འདུག་སེ་[ས་]མཐོང་བྱས་བྱུང་པ་ཡིན་ན། སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་
03:46  འདུག་ག [བྱས་ཙང་]སེ་[འདྲི]དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་[ཀྱི་]སྙིང་རྗེ་དེས་དེ་ག་རེ་ཟེར་བ། [གོ་རེད་] ཕ་གིའི་[གེར]་ཨིའི་ད་ལྟ་[བ་]བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་[དེ་ཤོད་]བཤད་ཡོང་གི་འདུག་ག [བ། ]
03:54 ཐར་པ་འདི་འདྲའི་[འདྲེས་]སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་[ཟེར་]བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་བསྡད་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ། [དེས་པ་དེས་ལ་ཡ་]
04:03 སྙིང་རྗེ་སྐྱེ་ཡ[ར་]མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་[འདི་]དེ་འདྲས་[འདྲེས་]ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་[ཏ་]འདྲ་གི་[ཡི་]རེད་དེ། ཡིན་ནས་ཨིའི་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་དེ། སངས་རྒྱས་པའི་[འདི་]
04:13 [སངས་རྒྱས་པའི་]འཚེ་་་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་སེ་ཏོག་སེ་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།
04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ། ལྟ་བ་འདི་ད་ཨོ། [ཏ]་གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། [ཨ་ནི་]
04:29 ཨེ་ནི་ཨིའི་ག་རེ་ཟེར་ག། [གར་ཟ་]བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་[ཏ་པས་སྡོམ]་ཆེན་པོ་རེད།
04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་ཨིའི་གང་ཟག་རང་རྐྱ་[སྐྱ]་བ། ད་ལྟ་ད་[རེད་བ་ཏ་]བདག་རང་རྐྱ[སྐྱ]་བ་། 
[འདི་གཉིས་བར་དུ་ཡག་པོ་མཐུན་ཐུག་མི་འདུག་བསྐྱར་དུ་ཡག་པོ་གནང་དགོས་འདུག ]
04:47 བདག་རང་རྐྱ་[སྐྱ]་བ་གྲུབ་པ་འདི་འདྲས་[འདྲེས]་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།
04:54 བདག་ལྟའི་[བའི་]ཞེན་ཡུལ་དེ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན[་དང་]མ་ཐུབ་ནས། འགོག་པ་ལ་བརྩོན་བསྡད་མཁན་དེ་[འདི་]ནང་པ། འོ་[འདི་]དེ་གསུང་ཡིན་[ཡོད་]པ་རེད།
05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་སེ། འདི་[འདྲེས་]འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ། 
05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནི་གཞན་སྡེ་ཟེར་གྱིས་ནས་[ཞེས་]གསུངས་པ་མིན་འགྲོ། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌སེ། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ཞིང་། [འདིའི་གོང་འོག་གཉིས་བར་ཏོག་ཙམ་ཏག་ཏག་ཅིག་མི་འདུག བསྐྱར་ཞིབ་གནང་། ]
05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་[བཟློག]་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 
05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 
05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི[ས་]བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།
[འདིའི་གོང་འོག་གཉིས་ནས་ཀྱང་ཏོག་ཙམ་ཏག་ཏག་མཐུན་མི་འདུག. བསྐྱར་ཞིབ་གནང་རོགས། ]
05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི[ཡས་ཀྱི་།] ཨིའི་ཕལ་ཆེར་འདི་[ཏ་]ད་དཔེར་ན་ཕྱིས་ཀྱི་[་ཡི་]ཕྱི་ཟེར་གོ་མ་རེད་བས། 
05:41 དེ་སྔ་ང་ཚོ་བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང་[ཡེས་ཡེ་ཤུ་དང༌]། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་མི་འདུག] [ཡས]་ཕལ་ཆེར་རེད། [དེའི་བར་བསྐྱར་ཞིབ་གནང་དགོས། ]
05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་[ཡས་ཞིག་]བཤད་ཀི་[ཆགས་ཀྱི་]འདུག་ག. [བ་།] [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་གི་མི་འདུག ]
05:53[ བྱས་ཙང་ཏ]ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ། དག་ཞིང[་དུ་]ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།

༢༠༢༣་༠༤་༤ དགོང་དྲོ།

2023-04-05 08:21 UTC, Tenzindharten commented
> 03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་[རྒྱུ་ཡོད་པ་]མཐོང་གྱིས་རྒྱ་ཆེན་པོ[་བྱས]་འདུག་སེ་[ས་]མཐོང་བྱས་བྱུང་པ་ཡིན་ན། སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་ 03:46 འདུག་ག [བྱས་ཙང་]སེ་[འདྲི]དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་[ཀྱི་]སྙིང་རྗེ་དེས་དེ་ག་རེ་ཟེར་བ། [གོ་རེད་] ཕ་གིའི་[གེར]་ཨིའི་ད་ལྟ་[བ་]བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་[དེ་ཤོད་]བཤད་ཡོང་གི་འདུག་ག [བ། ] 03:54 ཐར་པ་འདི་འདྲའི་[འདྲེས་]སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་[ཟེར་]བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་བསྡད་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ། [དེས་པ་དེས་ལ་ཡ་] 04:03 སྙིང་རྗེ་སྐྱེ་ཡ[ར་]མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་[འདི་]དེ་འདྲས་[འདྲེས་]ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་[ཏ་]འདྲ་གི་[ཡི་]རེད་དེ། ཡིན་ནས་ཨིའི་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་དེ། སངས་རྒྱས་པའི་[འདི་] 04:13 [སངས་རྒྱས་པའི་]འཚེ་་་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་སེ་ཏོག་སེ་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌། 04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ། ལྟ་བ་འདི་ད་ཨོ། [ཏ]་གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། [ཨ་ནི་] 04:29 ཨེ་ནི་ཨིའི་ག་རེ་ཟེར་ག། [གར་ཟ་]བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་[ཏ་པས་སྡོམ]་ཆེན་པོ་རེད། 04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་ཨིའི་གང་ཟག་རང་རྐྱ་[སྐྱ]་བ། ད་ལྟ་ད་[རེད་བ་ཏ་]བདག་རང་རྐྱ[སྐྱ]་བ་། [འདི་གཉིས་བར་དུ་ཡག་པོ་མཐུན་ཐུག་མི་འདུག་བསྐྱར་དུ་ཡག་པོ་གནང་དགོས་འདུག ] 04:47 བདག་རང་རྐྱ་[སྐྱ]་བ་གྲུབ་པ་འདི་འདྲས་[འདྲེས]་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ། 04:54 བདག་ལྟའི་[བའི་]ཞེན་ཡུལ་དེ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན[་དང་]མ་ཐུབ་ནས། འགོག་པ་ལ་བརྩོན་བསྡད་མཁན་དེ་[འདི་]ནང་པ། འོ་[འདི་]དེ་གསུང་ཡིན་[ཡོད་]པ་རེད། 05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་སེ། འདི་[འདྲེས་]འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ། 05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནི་གཞན་སྡེ་ཟེར་གྱིས་ནས་[ཞེས་]གསུངས་པ་མིན་འགྲོ། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌སེ། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ཞིང་། [འདིའི་གོང་འོག་གཉིས་བར་ཏོག་ཙམ་ཏག་ཏག་ཅིག་མི་འདུག བསྐྱར་ཞིབ་གནང་། ] 05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་[བཟློག]་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི[ས་]བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ། [འདིའི་གོང་འོག་གཉིས་ནས་ཀྱང་ཏོག་ཙམ་ཏག་ཏག་མཐུན་མི་འདུག. བསྐྱར་ཞིབ་གནང་རོགས། ] 05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི[ཡས་ཀྱི་།] ཨིའི་ཕལ་ཆེར་འདི་[ཏ་]ད་དཔེར་ན་ཕྱིས་ཀྱི་[་ཡི་]ཕྱི་ཟེར་གོ་མ་རེད་བས། 05:41 དེ་སྔ་ང་ཚོ་བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང་[ཡེས་ཡེ་ཤུ་དང༌]། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་མི་འདུག] [ཡས]་ཕལ་ཆེར་རེད། [དེའི་བར་བསྐྱར་ཞིབ་གནང་དགོས། ] 05:50 བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་[ཡས་ཞིག་]བཤད་ཀི་[ཆགས་ཀྱི་]འདུག་ག. [བ་།] [དབྱིན་ཡིག་ཏུ་བྲིས་ན་འགྲིག་གི་མི་འདུག ] 05:53[ བྱས་ཙང་ཏ]ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ། དག་ཞིང[་དུ་]ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།
> 
> ༢༠༢༣་༠༤་༤ དགོང་དྲོ།

2023-04-05 08:22 UTC, Tenzindharten requested changes
05:58 ཡང་ན་གཅིག་[ཅིག་]ངན་སོང་ལ་འགྲོ་མཁན་འདྲ་བོ་གཅིག་གི་[ཅིག་]ཡོད་རེད་བ།  soul ཟེར་ཡ་གཅིག [དབྱིན་ཡིག་དེ་བྲིས་ན་ལྷན་དུ་སྒྲ་གདངས་ལྟར་དུ་བོད་ཡིག་ཏུ་འབྲི་རོགས་གནང་། ]
06:02  ཁོ་ཚེ་འདི་ནས་འཕོས་ནས་ཁོ་ཚེ་ཕྱི་མ[ར་]ལ་འགྲོ་བསྡད་མཁན་ཞིག་འདུག་བ། [ཏ་]ད་ང་ཚོ་ཨིའི་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ན་བཞིན་[བྱེད་]བྱས་ནས་ཁོ་སྐྱེ་བ་གསར་པ་[ཞིག་]གཅིག་ད་[ཏ]་ལེན་གི་[གྱི་]ཡོད་མ་རེད་དེ།
06:09 [ཏེ་]ཡིན་ནས་གང་ལྟར་ཨིའི་མཐའ་མ་ཨེ་ནི་གཅིག་དག་ཞིང་ལ་འགྲོ་མཁན་དང༌། heaven ལ་འགྲོ་མཁན་དང། ཡང་ན་hellལ་འགྲོ་མཁན་[ཞིག]་གཅིག་ཡོད་རེད་བ་ད།[ཏ།] [དབྱིན་ཡིག་དེ་དག་དང་ལྷན་དུ་བོད་ཡིག་འབྲི་དགོས།]
06:17 [ཏ་]ད་[དེ་]འདི་ཨིའི་ཨིའི་ཕུང་པོ་འདི་དང་འབྲེལ་བ་ཡིན་ན། ཕུང་པོ་འདི་འགགས་ཚར་དུས་ཁོ་ཡོང་ཡག་ཡོད་མ་རེད་བ།[པ་།] 
06:23 བྱས་ཙང་[འདི་འདྲེས་]དེ་འདྲས་ཡིན་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་ཅིག་ཁས་ལེན་གི་འདུག་བ།   soul ༼རྣམ་ཤེས།༽ཟེར་[ཡས]་ཡག་[ཞིག་ཤོད་ཀྱི་]བཤད་ཀི་འདུག་བ་།
06:28 བྱས་ཙང་སྔ[ར་]མོ་མུ་སྟེགས་པ་ཚོས་རྟག་གཅིག་རང་དབང་བའི་བདག་སེ། [ཏ་]ད་་ད་ལྟ་མུ་སྟེགས་པ་ཚོས་མུ་སྟེགས་པ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་[ཚོས་འདྲས་]ཚོའི་གྲས་ཀྱིས་
06:37 ཨེ་ནི་ཨིའི་འོ་རེད་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་[འདི་]དེ་གའི་དེ་གིས་ཚེ་སྔ་མ་ནས་འདིར་འོང་མཁན། འདི་ནས་ཕྱི་མར་འགྲོ་མཁན་གཅིག་[ཞིག་]ཡོད་རེད་སེ། 
06:45 [བྱས་ཙང་]སེ་[འདི་འདྲེས་]དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས[་འདིའི་]ད་གིའི་སྟེང་ནས་ང་བཞག་བ་ཡིན་ན། ཨེ་ནི་ལུས་འདི་བཞག་ཚར་དུས་ཙ་ནས་ལུས་འདི་སྔ་མ་ནས[་འོང་]ཡོང་བ་མ་རེད་བ། 
06:54 ལུས་འདི་ཕྱི་མ[ར་]ལ་འགྲོ་ཡི་ཡོད་མ་རེད་བ། སེ་དེ་འདྲས་[འདི་འདྲེས་]ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་འདིར་ལ་ལྟོས་པ་མེད་པའི་བསྡད་མཁན་གྱི་[གི]་བདག་རང་རྐྱ་བ་གཅིག་[ཞིག་]དགོས་ཀི་[ཀྱི་]འདུག་ཟེར་གྱིས་ནས། [བྱས་།]
07:02 འོ་ད་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གཅིག་[ཤོད་ཀྱི་]བཤད་ཡོད་རེད། དེ་འདྲས་ཀི་[འདྲེས་ཀྱི་]བདག་དེ་[འདི་ཨ་]ཨེ་ནི་ཕ་གིའི་ག་རེ་ཟེར་[ག་]བ་རེད། ཨིའི་འགྱུར་བ་མེད་[དས་]བསྡད་མཁན་གྱི་[གི་]རྟག་པ། [འདིའི་མཚམས་འདི་དང་འོག་གཉིས་ཏོག་ཙམ་བསྐྱར་ཟློས་སོང་འདུག་པས་བསྐྱར་འབེབ་གནང་དགོས།]
07:11 ཨེ་ནི་གཅིག་པུ། རང་དབང་བ། ཁོ་ཕུང་པོ་ལ་ལྟོས་པ་མེད་[དས་]བསྡད་མཁན། ཕུང་པོ་ལ་ལྟོས་མེད་རང་དབང[་གིས]གི་གནས་བསྡད་མཁན་གཅིག་[ཞིག་]ཨོ་ཙེ་གཅིག་བཤད་ཀི་[ཨོས་ཤོད་ཀྱི་]འདུག་བ། འདི་ཡང་
07:20[ འདིའི་བར་སྒྲ་དེ་གོང་དང་བསྐྱར་ཟློས་རེད་བཞག བསྐྱར་དུ་གཟབ་ཉན་གནང་སྟེ་ཡིག་འབེབ་གནང་དགོས། ]བྱས་ཙང་དེང་སང་གི་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ག་རེ་[རེད་ཟེར་བ་[གོ་]རེད་ཕ་གིའི་[གིར་]ཆོས་ལུགས་ལྟ་གྲུབ་ཡོད་[དས]་བསྡད་མཁན་ཕལ་མོ་ཆེ་ཕལ་མོ་ཆེ་ལབ་ཆོག་གི་མེད་འགྲོ།
07:29 ངས་ཡང་རྦད་དེ་ཡང་ཚོད་ཐིག་གི་མི་འདུག་བ། གང་ལྟར་ཕལ་མོ་ཆེ[ས་]ད་ལྟ་རྟག་གཅིག་རང་དབང་བའི་བདག་དེ་འདོད་ཀི་[ཀྱི་]ཡོད་རེད།
07:38 བྱས་ཙང་བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས་ཟེར་ཡ་འདི། ད་འདས་པའི་ལོ་
07:45 [ད་འདས་པའི་]སྟོང་ཕྲག་གསུམ་རྗེས་ནས་དུས་ད་ལྟ་བར་དུ་[འདི་གར་]ད་ག་རང་བསྡད་བསྡད་པའི་བཟོ་འདྲ་བོ་ཞིག་འདུག་བ།
07:53  འདས་པའི་ལོ་ཉིས་སྟོང་ལྔ་བརྒྱ་ནས་ད་ལྟ་བར་དུ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱི་ཆོས་བྱུང་བ་ནས་ད་ལྟ་བར་དུ་[ཙིས་]བརྩིས་པ་[ཀྱི་]ཡིན་ན།

08:02  [ད་]ཕྱི་རོལ་པའི་གྲུབ་མཐའི་སྨྲ་བའི་མཚན་ཉིད་ཅིག་[ཞིག་]བཞག་ནས་ད་དེ་ནས་རྣམ་གཞག་མདོར་བསྡུས་ཏེ་བཤད་པ། རང་སྡེའི་གྲུབ་མཐའི་རྣམ་གཞག་ཅུང་ཟད་ཕྱེ་སྟེ་བཤད་པའོ།[ འདིའི་འོག་གཉིས་ཀར་ཡི་གེ་གསུང་གཉིས་མཐུན་གྱིན་མི་འདུག་པས། བསྐྱར་འབེབ་གནང་རོགས།]
08:04  ཕྱི་རོལ་པའི་གྲུབ་མཐའ་སྨྲ་བའི་དབྱེ་ན་། ཨེ་ནི་འདིའི་ད་ལྟ་གོ་རིམ་འདི།

08:13  ཨིའི་ཨིའི་བསྡུས་ན། ཁྱབ་འཇུག་པ། དབང་ཕྱུག་པ། རྒྱལ་བ་པ། སེ་སེ་སེར་སྐྱ་པ། ཕུར་བུ་བ་བྱས་ནས་ལྔ་བཤད།
08:21ཡང་ན། རྩ་བའི་སྡེ་དྲུག་ཏུ་ཡང་བཤད་དེ། ཨིའི་བྱས་ནས་ད་གང་ལྟར། ཕུར་བུ་བའམ་རྒྱང་འཕེན་པ་ཟེར་[ཡས]ཡག་འདི་མུ་སྟེགས་ཆད་པར་སྨྲ་བ་ཟེར་ཡག་[ཡས་]འདི་ཡིན་པ་རེད། [འདིའི་གོང་འོག་གཉིས་ནང་ཡི་གེ་དང་གསུང་དངོས་སུ་མཐུན་གྱིན་མི་འདུག་པས་བསྐྱར་འབེབ་གནང་དགོས།]
08:31གཞན་བདག་དེ་གའི་དེ་[ཡིན་དུས]་རྟག་པར་སྨྲ་བ་ཟེར་[ཡས་]ཡག་འདི་ཆགས་བསྡད་ཀྱི་ཡོད་རེད།

08:38 [ད་འདི་ད་ལྟ་དཀོན་མཆོག] གསུང་དང་མི་མཐུན་པ། ]་འཇིགས་མེད་དབང་པོའི་གྲུབ་མཐའི་ནང་ལོག་ལ་ཡ། སྔོན་ལ་རྟག་པར་སྨྲ་བ་ཨིའི་མུ་སྟེགས་རྟག་སྨྲ་འདི་གའི་དེ་སྔོན་ལ་གསུངས་འདུག་སྟེ། [ལྟས་།] 
08:44[སྔོན་ལ་ང་ཚོས་འདི་ལབ་ན་ཡག་བ་མེད་འགྲོ་བསམ་གི་འདུག་] མུ་སྟེགས་ཆད་པར་སྨྲ་བ་རྒྱང་འཕེན་པ་འདི་སྔོན་ལ་བཤད་ན།


08:48 འདིའི་གཤམ་དེ་འདུག་བ། ཨིའི་འདི་གཅེར་བུ་བ་བཤད་ཚར་བའི་གཞུག་གུ་དེར་འདུག [པས་ཞུ་གུར་དེ་འདུག་] 
08:58 རྒྱལ་བ་དམ་པས་ཁ་བ་རྒྱབ་པས་མེ་ཏོག་ཞེས་སོགས་ཀྱི་ལུང་འདི[་གྲང་]དྲངས་ནས་བཅས་འབྱུང་བས། རྒྱང་འཕེན་པ་ནི་ཟེར་ཡག[ཡས་]རྙེད་སོང་བས། 
09:07ད་རྒྱང་འཕེན་པ་[འགིགས་]རྙེད་སོང་བ་སྔོན་ལ་ཁོ་ཡ་འདུག་སེ་གོ་རིམ་[གཙུག་]འཛུགས་ས་བརྩིས་པ་ཡིན་ན་རེད་བ།   ཁོ་རྩིག་པ་དང་མ་སོང་ནས་[ཟུང་ནས་]འདུག་སེ་ཡར་བསླངས་པ་ཡིན་ན། 


༢༠༢༣་༠༤་༥ ཉིན། ཁྱེད་རང་གིས་གསུང་ཕབ་གནང་བ་འདིའི་ནང་གསུང་དང་མི་མཐུན་པའི་ཡི་གེ་དང་། ཡང་གོང་འོག་བསྐྱར་ཟློས་ཤོར་བ་དང་། གོང་འོག་འཁྲུགས་པ་དེ་འདྲ་མང་པོ་འདུག་པས་ངེས་པར་བསྐྱར་ཞིབ་གནང་རོགས་ཞུ།།

2023-04-05 09:28 UTC, Tenzindharten requested changes
09:17 སྔོན་ལ་ཆད་སྨྲ་བ་འདི་[དེ་]བཤད།[ རྒྱང་འཕེན་པ་བཤད་ན།] ད་འདིས་ཆོས་རྩ་བ་ནས་ཁས་ལེན་ཁོ་མ་རེད་བ། ད་དེ་[འདི་]ནས་ཡ། [ཨ་]ཨེ་ནི་ཡང་གཅིག་ལས་འབྲས་དང༌ཅིག སྐྱེ་བ་སྔ་ཕྱི་ཟེར་ཡག་[ཡོང་དུས་]ཁས་ལེན་ཅིག་དང། 
09:27 ཐར་པ་བཅས་ཁས་ལེན་འདི་འདྲའི་ཡང་་འདུག་སེ་འདུག་སེ་[འདུགས་འདུགས་འདུགས་]བྱས་ནས་འགྲོ་བསྡད་ཡི་འདུག་བ། ད་སྔོན་ལ་ དཔེར་ན་དེང་སང་འདྲ་བོ་ཡིན་པ་ཡིན་ན་ཕལ་ཆེར་རྒྱ་ཆེ་ཤོས་དེ་རྒྱང་འཕེན་པ་བརྩི་དགོས་བྱེད་ཀི་[ཀྱི་]རེད་ད།[ རྒྱང་འཕེན་པ་]

09:37[དེ་འདྲེས་]ད་དེ་འདྲས་ཡིན་དུས[་སྔེན་]སྔོན་ལ་རྒྱང་འཕེན་པ་དེ་སྔོན་ལ་བཤད་ན། རྒྱང་འཕེན་པ་ནི། སྐྱེ་བ་སྔ་མ་ནས་འདིར་འོང་བ་མེད་དེ། སྐྱེ་བ་སྔ་མ་ཞེས་པ་ནི་སུས་ཀྱང་མ་མཐོང་བའི་ཕྱིར། 
09:47ལུས་གློ་བུར་བ་ལས་སེམས་གློ་བུར་བ་[དུ]་གྲུབ་པ་ཡིན་ཏེ་མར་མེ་གློ་བུར་དུ་གྲུབ་པ་ལས་འོད་གློ་བུར་བ་[དུ་]གྲུབ་པ་བཞིན་ནོ། 
09:55ད་འདིས་སྐྱེ་བ་སྔ་མ་མེད་པ[ར་འདི]དེ་སྒྲུབ། ད་སྐྱེ་བ་ཕྱི་མ[ར་]མེད་པ[ར]་འདི།   ད་སྐྱེ་བ་སྔ་མ་མེད་ན་སྐྱེ་བ་ཕྱི་མ་ནི་ད་ག[ར་]རང་རེད། 
10:00ད་སྐྱེ་བ་ཕྱི་མ[ར]་འགྲོ་བ[ར]་སྐྱེ་བ་འདི[ས་]ནས་ཕྱི་མར་འགྲོ་བ་ཡང་མེད་དེ། ལུས་སེམས་རྫས་གཅིག་པས་ལུས་འཇིག་པ་ན་བློ་ཡང་འཇིག་པའི་ཕྱིར་རོ།
10:08  དཔེར་ན་རྡོ་འཇིག་པ་ན་རྡོ་ཡི་[དེའི]་རི་མོ་འཇིག་པ་བཞིན་ནོ། 
10:10 འོ་ད་འདི་གིས[་རེད།]
10:30 [སྔོན་གྱི་རྒྱང་འཕེན་པ་འོ་འདྲི་འདྲེས་ཀྱི་ཅིག་] འོ་དེ་འདྲས་ཀིས་སྐྱེ་བ་སྔ་ཕྱི་ཡོད་མ་རེད་སེ་ཐག་བཅད་ནས[་ཤོད་]ཨིའི་བཤད་བསྡད་[སྡད་]མཁན་གཅིག་བྱེད།
10:39  ད་དེང་སང་བརྩིས་པ་ཡིན་ན། ད་ཨིའི་སྐྱེ་བ་སྔ་ཕྱི་མེད་པར་ཐག་བཅད་པ་གང་ཡིན་ནས་མིན་ནས།
10:49  ད་སྐྱེ་བ་སྔ་ཕྱི་ཐེ་ཚོམ་[གང་]སྒང་ལ་བཞག་བྱས་[བྱེད་]ད་འདི་མང་ཤོས་རེད་བ་ད། 
10:54 དཔེར་ན་ད་རིང་ཁེ་སང་[ཁེས་ས་]དཔེར་ན་ཚན་རིག་པས་བཤད་པ་ཡིན་ན། 
10:59 མ་གཞི་[ཞིར]་སྤྱིར་ད་ལྟ[་ཡང]་ཚན་རིག་པ་འདི་དྲང་པོ་ཞེ་བོ[་ཞུ་འོ་]ཅིག་རེད། 
11:02ངའི་མཐོང་ཚུལ་[བྱེད]་བྱས་པ་ཡིན་ན། ང་རྒྱུས་ཡོད་པ་ད། [ངས་རྒྱུས་ཡོད་པ་དང།]  ངས་རྒྱུས་ཡོད་པར་གཞིར་བཞག་ནས་ངའི་མཐོང་ཚུལ་འདྲ་བོ་བཤད་པ་ཡིན་ན། [ཡིག་ཕྲེང་འདིའི་ནང་གསལ་བོ་ཞིག་ཡིག་འབེབ་གནང་ཐུབ་མི་འདུག་པས་བསྐྱར་དུ་གནང་རོགས། ]

11:12 ཕལ་ཆེར་ཚན་རིག་པས་སྒྲུབ་ཕྱོགས་དེ་[སུ་]གཙོ་བོར་[ཤོད་]བཤད་ཀི་[ཀྱི་]ཡོད་རེད། རེད་བ། ཁོ་ཡོད་པས་ཕྱོགས་དེ་འདི་སོ་སོའི་མིག་གིས་མཐོང༌། 
11:21 [པས་]ཕ་གི་[ཚད་གཞལ་ཕ་གིར་]ཆ་ཚང་གཅིག་ཕ་གིའི་བྱེད[་བྱས་]ཐུབ་ཡག་[ཡས་]ཅིག་ 
11:28 [ཨའདི་ཡས་མི་གཅིག་གིས་བརྟག་དཔྱད་བྱས་ནས་]ཨ་ནི་ཁོ་ཅིག་[ཤེས་པ་]རྙེད་བཞག་པ་འདི་[ཤེས་པ]་ད་[ལྟར་]ཐབས་ཤེས་གཅིག་པ་གཅིག་[ཞིག་བསྟེན་]བརྟེན་པ་ཡིན་ན། 
11:34 སུ་ཡིན་ནས་ད་ག་རང་[ཤེས་]བཤད་ཐུབ་མཁན་གཅིག་ད་འདི་ཡོད་རེད་སེ། ཨེ་ནི་ཐག་གཅད་ཀི་[གཅོད་ཀྱི]་རེད་བ་ད།
11:38  ད་དེ་ལས་སྒེར་[འདི་]དེ་གའི་དེ་[གས་འདི]་ཐེ་ཚོམ་རེད་ཟེར་ད། མེད་པ[ར་]ཐག་གཅོད་གཅད་ཀི་[ཀྱི་]་མ་རེད། [མེད།]
11:43 ཚན་རིག་པ་དྲང་པོ་[འདི]་རེད་ད། ཚན་རིག་པ་རང་ད་[འདི་]ཡིན་ན་ད་བློ་གཟུ་བོར་གནས་པ་རེད་བཞག
11:47 ད་ལྟ་མི་ཤེས་པའི་ཆ[་འདི]་དེ་གའི་དེ་[གས་འདི་]  open questionབྱས་ནས།  གང་ཡིན་ནས་[ཡང]་ཡོང་སྲིད་པ་རེད།  རེད་བ།
11:53 སོ་སོས་རེད། ཡོད་རེད་ཟེར་གྱིས་ནས་ཁས་མ་བླངས་པ་[ལེན་པ་]བྱས། [བྱེད། ]ཡོད་མ་རེད་ཟེར་[མེད་ཅེས]་ཐག་[མི]་མ་བཅད་བྱས། [གཅོད་པ་བྱས། ]ཁོ་རང་ཅི་ཡང་ཡིན་ཆོག་པ་གཅིག [ཞིག]


12:04 འདི་ཚན་རིག་པའི་ཁྱད་ཆོས་རེད་ད། ཚན་རིག་པ་དངོས་གནས་དྲང་གནས་ཚན་རིག་པ་[འདི]་དེ་གའི་དེ་[གས་འདིའི་དག་]བློ་གཟུ་བོར་གནས་པ།
12:10 [ཁོ་རང་ཕེས་དཔྱད་]ཕ་གིའི་[གེར་]ར་འཕྲོད་པ་བྱུང་སོང་ན་ཁས་དེ་བླངས། [ལེན།] དེ་ཕན་ཆད་འདི་ད་ལྟ་ཐེ་ཚོམ་དབང་དུ་བཞག [བྱེད་པ།]
12:14 [བྱེད་ཙང་]སེ་[འདི་འདྲེས་]དེ་འདྲས་ཡིན་དུས་ཡང་ཡོད་མེད་ཐག་བཅད་ནས་གཅིག་ཡང་ཚད་བཟུང་འདྲ་བོ་གཅིག་[ཞིག་]བྱེད་ཀིན་[ཀྱི་]མེད་པའི་བཟོ་[་ཟོ་]འདྲ་བོ་ཞིག
12:21[ འདིའི་བར་སྒྲ་སྟོང་པ་སླེབས་བཞག བསྐྱར་ཞིབ་གནང་རོགས། ]བྱས་ཙང་གང་ལྟར་ད་རིང[་ཁེས་ས་]ཁེ་སང་གཅིག་སྐྱེ་བ་སྔ་ཕྱི་ཐེ་ཚོམ་ངང་ལ་བསྡད་བསྡད་པ་ཞིག་ད་མང་ཤོས་ཆགས་བསྡད་ཡོད་རེད།
12:28 ད་ཨེ་ནི་[མི་]གུང་ཁྲན་བཟོ་འདྲ་བོ[་ཞིག་ནས་]བཤད་པ་ཡིན་ན། ཆོས་ཟེར་མཁན་འདི་དུག་རེད་ཟེར་ནས་[པས་]དཔེ་ཆེད་མངགས་རང་བྱས་ཞེ་བོ་[ཞུ་འོ་ཤོད་]བཤད་ཡོང་དུས།
12:40 སྐྱེ་བ་སྔ་ཕྱི་ཟེར་ཡ[་འདི]་དེ་ཆོས་ནས་བཤད་པ་རེད་སེ།[ཅེས།] ད་ཆོས་དུག་ལ་བརྩིས། ཆོས་ལ་སྡུག་ཅག་འདྲ་བོ་གཅིག་བརྩི་ཡོང་དུས་ཙ་ནས།
12:45 ཨེ་ནི་སྐྱེ་བ་སྔ་ཕྱི་[ཞེས]་ཟེར་ཡག་[པ་]དེ་ཡང་ཆོས་ནས་བཤད་ཀིན་[པ་]རེད་ཟེར་གྱིས་ནས།[ཅེས། ]ད་ཁོ་ཆོས་ནས་བཤད་པ་རྒྱུ་མཚན་དུ་བྱེད་ཀྱིས། ཨེ་ནི་[འདི]དེ་ཡོད་མ་རེད་སེ་ལབ་པ[་འདི་འདྲེས་]འདི་འདྲའི་ད་ཡོང་སྲིད་ཀྱི་རེད་བ་ད།
12:51རེད་བ་བྱས་ཙང་ག ཨིའི་སེ་དེ་འདྲས་ཡིན་དུས་[འདི་འདྲེས]ཨིའི་འདི་གའི་དེ་[གྲངས་]གནས་ཚུལ་ཁ་ཁ་རེད། [མ་ལྟོ་]མ་གཏོགས་ཚན་རིག་པ་རང་གི་ཐོག་ནས་བཤད་པ་ཡིན་ན། ཁོ་ཐེ་ཚོམ་རེད། [འདི་དང་འོག་ལ་བསྐྱར་ཟློས་འདུག]
13:00 སྔོན་མ་ང་ད་ལྟ་ངས་ནམ་རྒྱུན་འདི་[ཤོད་]བཤད་བསྡད་ཀིན་[ཀྱི་]ཡོད། ཚན་རིག་པས་བརྟག་དཔྱད་བྱས་ནས་རྙེད་པ་གཅིག་ར་འཕྲོད་པ་གཅིག. [ཞིག་། ]

13:10 འདི་ཡས་་གང་ཟག་གཅིག་གིས་རྙེད་པ་ཙམ་མ་ཡིན་པར། ད་ལྟ་ད་གིས་བཤད་མ་ཐག་པ་ན་བཞིན་གྱི་གང་ཟག་གཅིག་གིས་བརྟག་དཔྱད་བྱས་ནས་རྙེད་པའི་དོན་དེ་དེས་ཀྱི། ཡིག་ཕྲེང་གོང་འོག་འདི་གཉིས་ག་ཏག་ཏག་ཅིག་ཡིག་འབེབ་གནང་མི་འདུག བསྐྱར་དུ་གཟིགས། 
13:20 བརྟག་དཔྱད་བྱེད་ལུགས་དེ་དང་ཐུན་པ་སུས་བྱས་པ་ཡིན་ནས་ཡང་ཁོ་གྲུབ་དོན་གཅིག་པ་བབ་ཡོང་མཁན་ཞིག་འདུག་ན།


13:28 ད་འདི་ཡོད་པ[ར་]ཐག་གཅད་ཀི་[གཅོད་ཀྱི་]ཡོད་རེད། [བྱས་ཙང]་སེ་[འདི་འདྲེས་]དེ་འདྲས་ཡིན་དུས་ཙ་ནས། གལ་ཏེ་ཚན་རིག་པས་བརྟག་དཔྱད་བྱས་ནས། ཨིའི་སྐྱེ་བ་སྔ་ཕྱི་མེད་པ་གཅིག་ད་ཚད་མས་ངེས་པ་རྙེད་པ་[ཞིག]་གཅིག་ཡོང་གི་འདུག་ན། ནང་པས་དེ་ཁས་ལེན་གི་རེད་སེ། [གྱི་རེད།]


༢༠༢༣་༠༤་༥ ཕྱི་དྲོ་ཡོངས་སུ་བལྟས་ཟིན་མོད། ཡིན་ནའང་གསུང་དང་ཡི་གེ་མང་པོ་ཏག་ཏག་མཐུན་གིན་མི་འདུག ཕར་བསྐུར་བ་རྣམས་ཚུར་མཉམ་དུ་རྡོག་རྡོག་ཅིག་ལ་བསྐུར་རོགས།

2023-04-06 03:31 UTC, Tenzindharten requested changes
00:00 ད་ཨོ་[དི་]དེ་འདྲའི་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་[ཀྱི་]སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་ག།
00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་[ཀྱི]་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་བཟོ་འདྲ་གཅིག་མ་ཡིན་པ།
00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གའི་དེ་མེད་པ་ཆགས་བྱས།
00:16 དེའི་རྩ་བར་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་ཨེ་ནི་གཉེན་པོ་བྱས་ནས། 
00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕར་འགགས་སོང་ན།་  [ཨ]་ཨེ་ནི་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 
00:35 སྡུག་བསྔལ་དེ་ཉེས་པར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ་།   ཐར་པ་གཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 
00:36 ཨེ་ནི་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོད་རེད་དེ། 
00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག

00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 
00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད། 
01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ། 
01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ་།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་།
01:20 ཞེ་བོ་ཞིག་འདུག་ག འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་འདི་འདྲས་ཡིན་དུས་།   
01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་[ཡ་]ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་[རྩ་]ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུགས་ཡོང་གི་རེད།
01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡག་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།
01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་པ་བཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོད་རེད་དེ་ཡིན་ནས་ 
01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་[ཨ་]ཨེ་ནི་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་གཅིག་ལ་བརྟེན།
01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་ག།
02:00 ད་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་ཙ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།
02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་བ། 
02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།   བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནི་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་
02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡག་གི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་ཀའི་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།
02:28 གང་ལྟར་ལྟ་བ་བཀར་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག. སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 
02:36ཨེ་ནི་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་བ་ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག
02:45  ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།
02:52  ཨེ་ནི་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག
03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།
03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡག་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་
03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 
03:24 རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག
03:34 ཨེ་ནི་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནི་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས།  གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།  
03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་འབྲལ་ཡག་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 
03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་[འདྲེས་]ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བ་བཀར་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 
03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།
04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་
04:13 སངས་རྒྱས་པའི་འཚེ་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་ཙེ་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།
04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 
04:29 ཨེ་ནི་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།
04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་[སྐྱ]་བར་རེད་བ་[ཏ་]བདག་རང་སྐྱ་བ་། [རང་རྐྱ་ཞེས་པ་ འདི་བྲིས་ཡོད་རེད། ཁྱེད་རང་གིས་ཡག་པོ་བཅོས་མི་འདུག ]
04:47 བདག་རང་རྐྱ་བ་གྲུབ་པའི་འདི་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།
04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ནས་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡད་མཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།
05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ[་འདི་]དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་
05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨ་ནི་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།
05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་[བཟློག་]ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 
05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 
05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།
05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།
05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།
05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག
05:53 ད་ང་རང་ང་རང་ཚོ་མི་ཤི་བའི་[པའི་]རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།

༢༠༢༣། ༠༤་༦ ཞོགས་པར་བལྟས་ཟིན་བསྐྱར་དུ་བསྐུར་ཡོད།  ངས་སྔོན་དུ་བཅོས་པ་རྣམས་དང་བསྡུར་ཏེ་ཡག་པོ་ཞིག་ལྟ་དགོས། ད་དུང་དཔེར་ན། ཨེ་ནི་ཞེས་འབྲི་དགོས་སར་རང་གིས་རང་འཇགས་ཨ་ནེ་ཞེས་བཞག་འདུག་ལ། ཡག་ཞེས་འབྲི་དགོས་སར་ཡང་། [ཡ་དང་ཡས་]རང་འཇགས་བཞག་འདུག་པ་མ་ཟད། ཡག་གི་ཞེས་འབྲི་དགོས་སར་ཡང་[ཡག་ཀྱི་དང་གྱི་]རང་འཇགས་བྲིས་འདུག་པས། བསྐྱར་དུ་ཡག་པོ་ལྟ་དགོས། གང་ལྟར་གཟབ་ནན་གྱིས་ཡག་པོ་གཅིག་ལྟ་རོགས། ཚུར་སྐུར་དུས་མཉམ་གཅིག་ཏུ་ཤོག་ཁུག་གཅིག་ནང་ཡོད་པ་སྐུར་རོགས། རང་གིས་ཚུར་སྐུར་དུས་ཚེས་གྲངས་ཡི་གེའི་མཐའ་རུ་ཕྲིས་ཤོག

2023-04-06 17:18 UTC, Topchen2023 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft Himalaya";
	panose-1:1 1 1 0 1 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.timestamp
	{mso-style-name:timestamp;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->00:00 ད་ཨོ་དེ་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་བ།00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་ཟོ་འདྲ་གཅིག་མ་ཡིན་པ།00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གེའི་དེ་མེད་པ་ཆགས་ཀྱིས།00:16 དེའི་རྕ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་གཉེན་པོ་བྱས་ནས། 00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕ་འགགས་སོང་ན།  ཨེ་ནས་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 00:35 སྡུག་བསྔལ་དེ་ཉེས་པར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ།  ཐར་པ་ཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 00:36 ཨེ་ནས་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོདརེད་དེ། 00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག༢༠༢༣་༠༤་༤00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད། 01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ། 01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ་།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་།01:20 ཞེ་བོ་ཞིག་འདུག་ག ད་འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་འདི་འདྲས་ཡིན་དུས་།   01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་པ་ཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོདརེད་དེ་ཡིན་ནས་ 01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནས་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན།01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་བ།02:00 ཏ་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་བ། 02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།   བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནས་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག་སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 02:36ཨེ་ནས་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་བ་ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག02:45  ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།02:52  ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡ་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 03:24 སྙིང་རྗེ་དེ་རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག03:34 ཨེ་ནས་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནས་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས།  གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།༢༠༢༣་༠༤་༤03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་04:13 སངས་རྒྱས་པའི་  འཚེ་་་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 04:29 ཨེ་ནས་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་བར་རེད་བ་བདག་རང་རྐྱ་བ་།04:47 བདག་རང་རྐྱ་བ་གྲུབ་པའི་དེ་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡདམཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནས་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག05:53 ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ་།༢༠༢༣་༠༤་༤ དགོང་དྲོ།  Sent from Mail for Windows From: TenzindhartenSent: 06 April 2023 09:01To: MonlamAI/STT001Cc: Topchen2023; AuthorSubject: Re: [MonlamAI/STT001] STT001-08 (PR ***@***.*** requested changes on this pull request.00:00 ད་ཨོ་[དི་]དེ་འདྲའི་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་[ཀྱི་]སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་ག།00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་[ཀྱི]་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་བཟོ་འདྲ་གཅིག་མ་ཡིན་པ།00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གའི་དེ་མེད་པ་ཆགས་བྱས།00:16 དེའི་རྩ་བར་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་ཨེ་ནི་གཉེན་པོ་བྱས་ནས།00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕར་འགགས་སོང་ན།་ [ཨ]་ཨེ་ནི་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད།00:35 སྡུག་བསྔལ་དེ་ཉེས་པར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ་། ཐར་པ་གཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ།00:36 ཨེ་ནི་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོད་རེད་དེ།00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་།00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ། གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད།01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ།01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ་། སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་།01:20 ཞེ་བོ་ཞིག་འདུག་ག འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་འདི་འདྲས་ཡིན་དུས་།01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་[ཡ་]ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་[རྩ་]ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུ [...]

2023-04-06 18:40 UTC, Topchen2023 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft Himalaya";
	panose-1:1 1 1 0 1 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.timestamp
	{mso-style-name:timestamp;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->00:00 ད་ཨོ་དེ་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་བ།00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་ཟོ་འདྲ་གཅིག་མ་ཡིན་པ།00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གེའི་དེ་མེད་པ་ཆགས་ཀྱིས།00:16 དེའི་རྕ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་གཉེན་པོ་བྱས་ནས། 00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕ་འགགས་སོང་ན།  ཨེ་ནས་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 00:35 སྡུག་བསྔལ་དེ་ཉེས་པར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ།  ཐར་པ་ཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 00:36 ཨེ་ནས་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོདརེད་དེ། 00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག༢༠༢༣་༠༤་༤00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད། 01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ། 01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ་།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་།01:20 ཞེ་བོ་ཞིག་འདུག་ག ད་འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་འདི་འདྲས་ཡིན་དུས་།   01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་པ་ཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོདརེད་དེ་ཡིན་ནས་ 01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནས་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན།01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་བ།02:00 ཏ་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་བ། 02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།   བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནས་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག་སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 02:36ཨེ་ནས་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་བ་ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག02:45  ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།02:52  ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡ་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 03:24 སྙིང་རྗེ་དེ་རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག03:34 ཨེ་ནས་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནས་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས།  གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།༢༠༢༣་༠༤་༤03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་04:13 སངས་རྒྱས་པའི་  འཚེ་་་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 04:29 ཨེ་ནས་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་བར་རེད་བ་བདག་རང་རྐྱ་བ་།04:47 བདག་རང་རྐྱ་བ་གྲུབ་པའི་དེ་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡདམཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནས་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག05:53 ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ་།༢༠༢༣་༠༤་༤ དགོང་དྲོ།05:58 ཡང་ན་གཅིག་ངན་སོང་ལ་འགྲོ་མཁན་འདྲ་བོ་གཅིག་ཡོད་རེད་བ་།  ༼རྣམ་ཤེས།༽soul ཟེར་ཡ་གཅིག06:02  ཁོ་ཚེ་འདི་ནས་འཕོས་ནས་ཁོ་ཚེ་ཕྱི་མ་ལ་འགྲོ་སྡདམཁན་ཞིག་འདུག་བ་། ད་ང་ཚོ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ན་བཞིན་བྱས་ནས་ཁོ་སྐྱེ་བ་གསར་པ་གཅིག་ད་ལེན་གི་ཡོད་མ་རེད།06:09 ཡིན་ནས་གང་ལྟར་མཐའ་མ་དག་ཞིང་ལ་འགྲོ་མཁན་དང༌།  ལྷ་ཡུལ་ heaven ལ་འགྲོ་མཁན་དང། ཡང་ན་དམྱལ་བ་hellལ་འགྲོ་མཁན་གཅིག་ཡོད་རེད་བ་ད།06:17 ད་འདི་ཨིའེ་ཨིའི་ཕུང་པོ་འདི་དང་འབྲེལ་བ་ཡིན་ན། ཕུང་པོ་འདི་འགགས་ཚར་དུས་ཁོ་ཡོང་ཡ་ཡོད་མ་རེད་བ། 06:23 བྱས་ཙང་དེ་འདྲས་ཡིན་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་ཅིག་ཁས་ལེན་གི་འདུག་བ་  soul ༼རྣམ་ཤེས།༽ཟེར་ཡག་བཤད་ཀི་འདུག་བ་།06:28 བྱས་ཙང་སྔ་མོ་མུ་སྟེགས་པ་ཚོས་རྟག་གཅིག་རང་དབང་བའི་བདག་། ད་ད་ལྟ་མུ་སྟེགས་པ་ཚོས་མུ་སྟེགས་པ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཚོའི་གྲས་ཀྱིས་06:37 ཨེ་ནས་ཨིའི་འོ་རེད་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཡི་ཚེ་སྔ་མ་ནས་འདིར་འོང་མཁན་། འདི་ནས་ཕྱི་མར་འགྲོ་མཁན་གཅིག་ཡོད་རེད་སེ། 06:45 སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་ད་གིའི་སྟེང་ནས་ང་བཞག་བ་ཡིན་ན། ཨེ་ནས་ལུས་འདི་བཞག་ཚར་དུས་ཙ་ནས་ལུས་འདི་སྔ་མ་ནས་ཡོང་བ་མ་རེད་བ། 06:54 ལུས་འདི་ཕྱི་མ་ལ་འགྲོ་ཡི་ཡོད་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་འདིར་ལ་ལྟོས་པ་མེད་པའི་སྡད་མཁན་གྱི་བདག་རང་རྐྱ་བ་གཅིག་དགོས་ཀི་འདུག་ཟེར་གྱིས་ནས།07:02 ད་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གཅིག་བཤད་ཀྱི་ཡོད་རེད། དེ་འདྲས་ཀི་བདག་དེ་ཨེ་ནས་ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།ཨིའི་འགྱུར་བ་མེད་བསྡད་མཁན་གྱི་རྟག་པ། 07:11 ཨེ་ནས་གཅིག་པུ། རང་དབང་བ། ཕུང་པོ་ལ་ལྟོས་མེད་བསྡད་མཁན།  ཕུང་པོ་ལ་ལྟོས་མེད་རང་དབང་གི་གནས་པ་དས་མཁན་གཅིག་ཨོ་ཙེ་བཤད་ཀི་འདུག་བ་། འདི་ཡང་07:20 བྱས་ཙང་དེང་སང་གི་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ག་རེད་ཟེར་གོ་རེད་ཕ་གིར་ཆོས་ལུགས་ལྟ་གྲུབ་ཡོད་དས་མཁན་ཕལ་མོ་ཆེས་ལབ་ཆོག་གི་མེདའགྲོ།07:29 དེ་ལ་ཡ་ཚོ་ཐིག་གི་མི་འདུག་བ།  གང་ལྟར་ཕལ་མོ་ཆེ་ད་ལྟ་རྟག་གཅིག་རང་དབང་བའི་བདག་དེ་འདོད་ཀི་ཡོད་རེད།07:38 བྱས་ཙང་བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས་ཟེར་ཡ་འདི། ད་འདས་པའི་ལོ།07:45 སྟ [...]

2023-04-07 07:04 UTC, Tenzindharten requested changes
00:00 ད་ཨོ་དེ་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་ག 
00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་ཟོ་འདྲ་གཅིག་མ་ཡིན་པ།
00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གའི་དེ་མེད་པ་ཆགས་ཀྱིས།
00:16 དེའི་རྩ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་ཨེ་ནས་གཉེན་པོ་བྱས་ནས། 
00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕར་འགགས་སོང་ན།  ཨེ་ནས་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 
00:35 སྡུག་བསྔལ་དེ་ཉེ་བར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ།  ཐར་པ་ཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 00:36 ཨེ་ནས་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོད་རེད་དེ། 00:43ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག ག00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 
00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད།
 01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ།
 01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ། སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་
།01:20 ཞེ་བོ་ཞིག་འདུག་ག ད་འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་།   
01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།
01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།
01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་ཡག་བཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོད་རེད་དེ་ཡིན་ནས་ 
01:45 རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནས་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་གཅིག་ལ་བརྟེན་ནས།
01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་ག
02:00 ད་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།
02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡགཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་ག
02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།  བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནས་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།
02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག་སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 
02:36ཨེ་ནས་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་ག ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག
02:45  ད་ཡིན་ནས།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།
02:52 ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅིག་དྲག་བསམ་པ་གཅིག
03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།
03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡ་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་
03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 
03:24 སྙིང་རྗེ་དེ་རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག
03:34 ཨེ་ནས་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནས་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས། གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།
03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 
03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 
03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།
04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་04:13 སངས་རྒྱས་པའི་  འཚེ་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།
04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 
04:29 ཨེ་ནས་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།
04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་བར་རེད་བ་བདག་རང་རྐྱ་བ་།
04:47 བདག་རང་རྐྱ་བ་གྲུབ་པའི་དེ་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།
04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡདམཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནས་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 
05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 
05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།
05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།
05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།
05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག
05:53 ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།དགོང་དྲོ།
05:58 ཡང་ན་གཅིག་ངན་སོང་ལ་འགྲོ་མཁན་འདྲ་བོ་གཅིག་ཡོད་རེད་བ་།  ༼རྣམ་ཤེས།༽soul ཟེར་ཡ་གཅིག
06:02  ཁོ་ཚེ་འདི་ནས་འཕོས་ནས་ཁོ་ཚེ་ཕྱི་མ་ལ་འགྲོ་སྡདམཁན་ཞིག་འདུག་བ་། ད་ང་ཚོ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ན་བཞིན་བྱས་ནས་ཁོ་སྐྱེ་བ་གསར་པ་གཅིག་ད་ལེན་གི་ཡོད་མ་རེད།
06:09 ཡིན་ནས་གང་ལྟར་མཐའ་མ་དག་ཞིང་ལ་འགྲོ་མཁན་དང༌།  ལྷ་ཡུལ་ heaven ལ་འགྲོ་མཁན་དང། ཡང་ན་དམྱལ་བ་hellལ་འགྲོ་མཁན་གཅིག་ཡོད་རེད་བ་ད།06:17 ད་འདི་ཨིའེ་ཨིའི་ཕུང་པོ་འདི་དང་འབྲེལ་བ་ཡིན་ན། ཕུང་པོ་འདི་འགགས་ཚར་དུས་ཁོ་ཡོང་ཡ་ཡོད་མ་རེད་བ། 
06:23 བྱས་ཙང་དེ་འདྲས་ཡིན་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་ཅིག་ཁས་ལེན་གི་འདུག་བ་soul ༼རྣམ་ཤེས།༽ཟེར་ཡག་བཤད་ཀི་འདུག་བ་།06:28 བྱས་ཙང་སྔ་མོ་མུ་སྟེགས་པ་ཚོས་རྟག་གཅིག་རང་དབང་བའི་བདག་། ད་ད་ལྟ་མུ་སྟེགས་པ་ཚོས་མུ་སྟེགས་པ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཚོའི་གྲས་ཀྱིས་06:37 ཨེ་ནས་ཨིའི་འོ་རེད་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཡི་ཚེ་སྔ་མ་ནས་འདིར་འོང་མཁན་། འདི་ནས་ཕྱི་མར་འགྲོ་མཁན་གཅིག་ཡོད་རེད་སེ། 
06:45 སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་ད་གིའི་སྟེང་ནས་ང་བཞག་བ་ཡིན་ན། ཨེ་ནས་ལུས་འདི་བཞག་ཚར་དུས་ཙ་ནས་ལུས་འདི་སྔ་མ་ནས་ཡོང་བ་མ་རེད་བ། 
06:54 ལུས་འདི་ཕྱི་མ་ལ་འགྲོ་ཡི་ཡོད་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་འདིར་ལ་ལྟོས་པ་མེད་པའི་སྡད་མཁན་གྱི་བདག་རང་རྐྱ་བ་གཅིག་དགོས་ཀི་འདུག་ཟེར་གྱིས་ནས།
07:02 ད་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གཅིག་བཤད་ཀྱི་ཡོད་རེད། དེ་འདྲས་ཀི་བདག་དེ་ཨེ་ནས་ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།ཨིའི་འགྱུར་བ་མེད་བསྡད་མཁན་གྱི་རྟག་པ། 
07:11 ཨེ་ནས་གཅིག་པུ། རང་དབང་བ། ཕུང་པོ་ལ་ལྟོས་མེད་བསྡད་མཁན།  ཕུང་པོ་ལ་ལྟོས་མེད་རང་དབང་གི་གནས་པ་དས་མཁན་གཅིག་ཨོ་ཙེ་བཤད་ཀི་འདུག་བ་། འདི་ཡང་
07:20 བྱས་ཙང་དེང་སང་གི་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ག་རེད་ཟེར་གོ་རེད་ཕ་གིར་ཆོས་ལུགས་ལྟ་གྲུབ་ཡོད་དས་མཁན་ཕལ་མོ་ཆེས་ལབ་ཆོག་གི་མེདའགྲོ།
07:29 དེ་ལ་ཡ་ཚོ་ཐིག་གི་མི་འདུག་བ། གང་ལྟར་ཕལ་མོ་ཆེ་ད་ལྟ་རྟག་གཅིག་རང་དབང་བའི་བདག་དེ་འདོད་ཀི་ཡོད་རེད།
07:38 བྱས་ཙང་བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས་ཟེར་ཡ་འདི། ད་འདས་པའི་ལོ།
07:45 སྟོང་ཕྲག་གསུམ་སེ་རྗེས་ནས་དུས་ད་ལྟ་བར་དུ་ད་ག་རང་བསྡད་བསྡད་པའི་བཟོ་འདྲ་བོ་ཞིག་འདུག་ག
07:53 འདས་པའི་ལོ་ཉིས་སྟོང་ལྔ་བརྒྱ་ནས་ད་ལྟ་བར་དུ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱི་ཆོས་བྱུང་བ་ནས་ད་ལྟ་བར་དུ་བརྩིས་པ་ཡིན་ན།
08:02  ཕྱི་རོལ་པའི་གྲུབ་མཐའི་སྨྲ་བའི་མཚན་ཉིད་ཅིག་བཞག་ནས་ད་དེ་ནས་རྣམ་གཞག་མདོར་བསྡུས་ཏེ་བཤད་པ། རང་སྡེའི་གྲུབ་མཐའི་རྣམ་གཞག་ཅུང་ཟད་ཕྱེ་སྟེ་བཤད་པའོ།
08:04  ཕྱི་རོལ་པའི་གྲུབ་མཐའ་སྨྲ་བ་ལ་དབྱེ་ན་། ཨེ་ནས་འདིའི་ད་ལྟ་གོ་རིམ་འདི།
08:13  ཨིའི་ཨིའི་བསྡུས་ན། ཁྱབ་འཇུག་པ། དབང་ཕྱུག་པ། རྒྱལ་བ་པ། སེ་སེ་སེར་སྐྱ་པ། ཕུར་བུ་བ་བྱས་ནས་ལྔ་བཤད།
08:21 ཡང་ན། རྩ་བའི་སྡེ་དྲུག་ཏུ་ཡང་བཤད་དེ། ཨིའི་བྱས་ནས་ད་གང་ལྟར། ཕུར་བུ་བའམ་རྒྱང་འཕེན་པ་ཟེར་ཡག་འདི་མུ་སྟེགས་ཆད་པར་སྨྲ་བ་ཟེར་ཡག་འདི་ཡིན་པ་རེད།
08:31གཞན་དག་ [...]

2023-04-07 09:28 UTC, Topchen2023 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft Himalaya";
	panose-1:1 1 1 0 1 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:#954F72;
	text-decoration:underline;}
span.timestamp
	{mso-style-name:timestamp;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->00:00 ད་ཨོ་དེ་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་བ།00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་ཟོ་འདྲ་གཅིག་མ་ཡིན་པ།00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གེའི་དེ་མེད་པ་ཆགས་ཀྱིས།00:16 དེའི་རྕ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་གཉེན་པོ་བྱས་ནས། 00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕ་འགགས་སོང་ན།  ཨེ་ནས་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 00:35 སྡུག་བསྔལ་དེ་ཉེས་པར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ།  ཐར་པ་ཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 00:36 ཨེ་ནས་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོདརེད་དེ། 00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག༢༠༢༣་༠༤་༤00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད། 01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ། 01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ་།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་།01:20 ཞེ་བོ་ཞིག་འདུག་ག ད་འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་འདི་འདྲས་ཡིན་དུས་།   01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་པ་ཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོདརེད་དེ་ཡིན་ནས་ 01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནས་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན།01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་བ།02:00 ཏ་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་བ། 02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།   བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནས་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག་སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 02:36ཨེ་ནས་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་བ་ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག02:45  ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།02:52  ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡ་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 03:24 སྙིང་རྗེ་དེ་རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག03:34 ཨེ་ནས་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནས་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས།  གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།༢༠༢༣་༠༤་༤03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་04:13 སངས་རྒྱས་པའི་  འཚེ་་་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 04:29 ཨེ་ནས་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་བར་རེད་བ་བདག་རང་རྐྱ་བ་།04:47 བདག་རང་རྐྱ་བ་གྲུབ་པའི་དེ་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡདམཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནས་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག05:53 ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ་།༢༠༢༣་༠༤་༤ དགོང་དྲོ།05:58 ཡང་ན་གཅིག་ངན་སོང་ལ་འགྲོ་མཁན་འདྲ་བོ་གཅིག་ཡོད་རེད་བ་།  ༼རྣམ་ཤེས།༽soul ཟེར་ཡ་གཅིག06:02  ཁོ་ཚེ་འདི་ནས་འཕོས་ནས་ཁོ་ཚེ་ཕྱི་མ་ལ་འགྲོ་སྡདམཁན་ཞིག་འདུག་བ་། ད་ང་ཚོ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ན་བཞིན་བྱས་ནས་ཁོ་སྐྱེ་བ་གསར་པ་གཅིག་ད་ལེན་གི་ཡོད་མ་རེད།06:09 ཡིན་ནས་གང་ལྟར་མཐའ་མ་དག་ཞིང་ལ་འགྲོ་མཁན་དང༌།  ལྷ་ཡུལ་ heaven ལ་འགྲོ་མཁན་དང། ཡང་ན་དམྱལ་བ་hellལ་འགྲོ་མཁན་གཅིག་ཡོད་རེད་བ་ད།06:17 ད་འདི་ཨིའེ་ཨིའི་ཕུང་པོ་འདི་དང་འབྲེལ་བ་ཡིན་ན། ཕུང་པོ་འདི་འགགས་ཚར་དུས་ཁོ་ཡོང་ཡ་ཡོད་མ་རེད་བ། 06:23 བྱས་ཙང་དེ་འདྲས་ཡིན་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་ཅིག་ཁས་ལེན་གི་འདུག་བ་  soul ༼རྣམ་ཤེས།༽ཟེར་ཡག་བཤད་ཀི་འདུག་བ་།06:28 བྱས་ཙང་སྔ་མོ་མུ་སྟེགས་པ་ཚོས་རྟག་གཅིག་རང་དབང་བའི་བདག་། ད་ད་ལྟ་མུ་སྟེགས་པ་ཚོས་མུ་སྟེགས་པ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཚོའི་གྲས་ཀྱིས་06:37 ཨེ་ནས་ཨིའི་འོ་རེད་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཡི་ཚེ་སྔ་མ་ནས་འདིར་འོང་མཁན་། འདི་ནས་ཕྱི་མར་འགྲོ་མཁན་གཅིག་ཡོད་རེད་སེ། 06:45 སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་ད་གིའི་སྟེང་ནས་ང་བཞག་བ་ཡིན་ན། ཨེ་ནས་ལུས་འདི་བཞག་ཚར་དུས་ཙ་ནས་ལུས་འདི་སྔ་མ་ནས་ཡོང་བ་མ་རེད་བ། 06:54 ལུས་འདི་ཕྱི་མ་ལ་འགྲོ་ཡི་ཡོད་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་འདིར་ལ་ལྟོས་པ་མེད་པའི་སྡད་མཁན་གྱི་བདག་རང་རྐྱ་བ་གཅིག་དགོས་ཀི་འདུག་ཟེར་གྱིས་ནས།07:02 ད་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གཅིག་བཤད་ཀྱི་ཡོད་རེད། དེ་འདྲས་ཀི་བདག་དེ་ཨེ་ནས་ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།ཨིའི་འགྱུར་བ་མེད་བསྡད་མཁན་གྱི་རྟག་པ། 07:11 ཨེ་ནས་གཅིག་པུ། རང་དབང་བ། ཕུང་པོ་ལ་ལྟོས་མེད་བསྡད་མཁན།  ཕུང་པོ་ལ་ལྟོས་མེད་རང་དབང་གི་གནས་པ་དས་མཁན་གཅིག་ཨོ་ཙེ་བཤད་ཀི་འདུག་བ་། འདི་ཡང་07:20 བྱས་ཙང་དེང་སང་གི་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ག་རེད་ཟེར་གོ་རེད་ཕ་གིར་ཆོས་ལུགས་ལྟ་གྲུབ་ཡོད་དས་མཁན་ཕལ་མོ་ཆེས་ལབ་ཆོག་གི་མེདའགྲོ།07:29 དེ་ལ་ཡ་ཚོ་ཐིག་གི་མི་འདུག་བ།  གང་ལྟར་ཕལ་མོ་ཆེ་ད་ལྟ་རྟག་གཅིག་རང་དབང་བའི་བ [...]

2023-04-07 18:24 UTC, Topchen2023 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Microsoft Himalaya";
	panose-1:1 1 1 0 1 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
span.timestamp
	{mso-style-name:timestamp;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->༢༠༢༣་༠༤་༧ ཉིན།00:00 ད་ཨོ་དེ་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་བ།00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་ཟོ་འདྲ་གཅིག་མ་ཡིན་པ།00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཟག་པའི་སྐྱོན་དེ་གེའི་དེ་མེད་པ་ཆགས་ཀྱིས།00:16 དེའི་རྕ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་གཉེན་པོ་བྱས་ནས། 00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕ་འགགས་སོང་ན།  ཨེ་ནས་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 00:35 སྡུག་བསྔལ་དེ་ཉེས་པར་ཞི་བར་རེད་། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ།  ཐར་པ་ཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 00:36 ཨེ་ནས་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོདརེད་དེ། 00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག༢༠༢༣་༠༤་༤00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད། 01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ། 01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ་།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད་།01:20 ཞེ་བོ་ཞིག་འདུག་ག ད་འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་འདི་འདྲས་ཡིན་དུས་།   01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་པ་ཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོདརེད་དེ་ཡིན་ནས་ 01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནས་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན།01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་བ།02:00 ཏ་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་བ། 02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།   བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནས་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡ་གྱི་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་གས་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།02:28 གང་ལྟར་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག་སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 02:36ཨེ་ནས་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་བ་ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག02:45  ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།02:52  ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡ་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 03:24 སྙིང་རྗེ་དེ་རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག03:34 ཨེ་ནས་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནས་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས།  གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།༢༠༢༣་༠༤་༤03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་04:13 སངས་རྒྱས་པའི་  འཚེ་་་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 04:29 ཨེ་ནས་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་བར་རེད་བ་བདག་རང་རྐྱ་བ་།04:47 བདག་རང་རྐྱ་བ་གྲུབ་པའི་དེ་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་སྒྲུབ་མཁན་དེ་ཕྱི་པ།04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡདམཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནས་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་ད། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།05:50  བྱས་ནས་ soul ༼རྣམ་ཤེས།༽ ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག05:53 ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ་།༢༠༢༣་༠༤་༤ དགོང་དྲོ།05:58 ཡང་ན་གཅིག་ངན་སོང་ལ་འགྲོ་མཁན་འདྲ་བོ་གཅིག་ཡོད་རེད་བ་།  ༼རྣམ་ཤེས།༽soul ཟེར་ཡ་གཅིག06:02  ཁོ་ཚེ་འདི་ནས་འཕོས་ནས་ཁོ་ཚེ་ཕྱི་མ་ལ་འགྲོ་སྡདམཁན་ཞིག་འདུག་བ་། ད་ང་ཚོ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ན་བཞིན་བྱས་ནས་ཁོ་སྐྱེ་བ་གསར་པ་གཅིག་ད་ལེན་གི་ཡོད་མ་རེད།06:09 ཡིན་ནས་གང་ལྟར་མཐའ་མ་དག་ཞིང་ལ་འགྲོ་མཁན་དང༌།  ལྷ་ཡུལ་ heaven ལ་འགྲོ་མཁན་དང། ཡང་ན་དམྱལ་བ་hellལ་འགྲོ་མཁན་གཅིག་ཡོད་རེད་བ་ད།06:17 ད་འདི་ཨིའེ་ཨིའི་ཕུང་པོ་འདི་དང་འབྲེལ་བ་ཡིན་ན། ཕུང་པོ་འདི་འགགས་ཚར་དུས་ཁོ་ཡོང་ཡ་ཡོད་མ་རེད་བ། 06:23 བྱས་ཙང་དེ་འདྲས་ཡིན་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་ཅིག་ཁས་ལེན་གི་འདུག་བ་  soul ༼རྣམ་ཤེས།༽ཟེར་ཡག་བཤད་ཀི་འདུག་བ་།06:28 བྱས་ཙང་སྔ་མོ་མུ་སྟེགས་པ་ཚོས་རྟག་གཅིག་རང་དབང་བའི་བདག་། ད་ད་ལྟ་མུ་སྟེགས་པ་ཚོས་མུ་སྟེགས་པ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཚོའི་གྲས་ཀྱིས་06:37 ཨེ་ནས་ཨིའི་འོ་རེད་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཡི་ཚེ་སྔ་མ་ནས་འདིར་འོང་མཁན་། འདི་ནས་ཕྱི་མར་འགྲོ་མཁན་གཅིག་ཡོད་རེད་སེ། 06:45 སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་ད་གིའི་སྟེང་ནས་ང་བཞག་བ་ཡིན་ན། ཨེ་ནས་ལུས་འདི་བཞག་ཚར་དུས་ཙ་ནས་ལུས་འདི་སྔ་མ་ནས་ཡོང་བ་མ་རེད་བ། 06:54 ལུས་འདི་ཕྱི་མ་ལ་འགྲོ་ཡི་ཡོད་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་འདིར་ལ་ལྟོས་པ་མེད་པའི་སྡད་མཁན་གྱི་བདག་རང་རྐྱ་བ་གཅིག་དགོས་ཀི་འདུག་ཟེར་གྱིས་ནས།07:02 ད་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གཅིག་བཤད་ཀྱི་ཡོད་རེད། དེ་འདྲས་ཀི་བདག་དེ་ཨེ་ནས་ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།ཨིའི་འགྱུར་བ་མེད་བསྡད་མཁན་གྱི་རྟག་པ། 07:11 ཨེ་ནས་གཅིག་པུ། རང་དབང་བ། ཕུང་པོ་ལ་ལྟོས་མེད་བསྡད་མཁན།  ཕུང་པོ་ལ་ལྟོས་མེད་རང་དབང་གི་གནས་པ་དས་མཁན་གཅིག་ཨོ་ཙེ་བཤད་ཀི་འདུག་བ་། འདི་ཡང་07:20 བྱས་ཙང་དེང་སང་གི་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ག་རེད་ཟེར་གོ་རེད་ཕ་གིར་ཆོས་ལུགས་ལྟ་གྲུབ་ཡོད་དས་མཁན་ཕལ་མོ་ཆེས་ལབ་ཆོག་གི་མེདའགྲོ།07:29 དེ་ལ་ཡ་ཚོ་ཐིག་གི་མི་འདུག་བ།  གང་ལྟར་ཕལ་མོ་ཆེ་ད་ལྟ་རྟག་གཅིག་རང་དབང་བའི་བདག་དེ་འདོད་ཀི་ཡོད་རེད།07:38 བྱས་ཙང་བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས་ཟེར་ཡ་འདི། ད་འདས་པའི་ལོ།07:45 སྟོང་ཕྲག་གསུམ་རྗེས་ནས་དུས་ད་ལྟ་བར་དུ་ད་ག་རང་བསྡད་བསྡད་པའི་ཟོ་འདྲ་བོ་ཞིག་འདུག་བ།07 [...]

2023-04-08 04:25 UTC, Tenzindharten requested changes
00:00 ད་ཨོ་དེ་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་ག།

00:04 ཐར་པ་དེ་ཕྱི་ལོག་གི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་ཟོ་འདྲ་གཅིག་མ་ཡིན་པ།

00:07 ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཨིའི་ཟག་པའི་སྐྱོན་དེ་གའི་དེ་མེད་པ་ཆགས་ཀྱིས།

00:16 དེའི་རྩ་བ་བདག་ཏུ་འཛིན་པ་རེད། བདག་འཛིན་པ་མེད་པ། བདག  བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་ཨེ་ནས་གཉེན་པོ་བྱས་ནས། 

00:23 ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕ་འགགས་སོང་ན།  ཨེ་ནས་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད། 

00:35 སྡུག་བསྔལ་དེ་ཉེ་བར་ཞི་བར་རེད། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡ།  ཐར་པ་གཅིག་བཤད་དེ་དོན་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ། 

00:36 ཨེ་ནས་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོད་རེད་དེ། 

00:43 ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཞེས་པ་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག

00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་། 

00:57 ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ།  གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད། 

01:02 མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ། 
01:11 སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ།  སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད།

01:20 ཞེ་བོ་ཞིག་འདུག་ག འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་།   
01:27 ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།
01:33 མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།

01:39 དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་ཡག་བཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོད་རེད་དེ་ཡིན་ནས་ 

01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནས་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན།

01:55 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་བ།

02:00 ད་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་པ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁོས་འདི་སྡིག་པའི་ལས་རེད།
02:06 ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་ག། 

02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད།   བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནས་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་

02:19ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀྱི་ཡོད་རེད།  སྙིང་རྗེ་ཡོང་ཡག་གི་་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་ཀའི་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།

02:28 གང་ལྟར་ལྟ་བ་བཀར་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག་སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན། 

02:36ཨེ་ནས་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ།  སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་མི་འདུག་བ་ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག

02:45  ད་ཡིན་ནས་།  ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།
02:52  ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་སྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག

03:00 ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡ་དེ།

03:09ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡ་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཞིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་

03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད་སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས། 

03:24 སྙིང་རྗེ་དེ་རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག

03:34 ཨེ་ནས་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག  ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནས་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས།  གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།

03:39 རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན། 

03:46 སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ།  ཕ་གིའི་ཨིའི་ད་ལྟ་བཀའ་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག 

03:54 ཐར་པ་འདི་འདྲའི་སྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།

04:03 སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡ་འདི་

04:13 སངས་རྒྱས་པའི་འཚེ་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་ཙམ་མི་འདྲ་བ་ཡོད་ས་རེད། བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།
04:20 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ།   ལྟ་བ་འདི་ད་ཨོ།  གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ། 
04:29 ཨེ་ནས་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་བསྡོམས་ཆེན་པོ་རེད།
04:37 བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་བ་རེད་བ། བདག་རང་རྐྱ་བ།

04:47 བདག་རང་རྐྱ་བ་གྲུབ་པའི་དེ་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་ཨེ་ནས་སྒྲུབ་མཁན་དེ་ཕྱི་པ།

04:54 བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡད་མཁན་དེ་ནང་པ།  འོ་དེ་གསུང་ཡིན་པ་རེད།

05:04 བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་

05:14 ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནས་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ་། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།

05:20 གཞན་སྡེ་རྣམས་ནི་དེ་ལས་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌། 

05:26 བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌། 

05:29 ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།

05:31 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱི་ཟེར་གོ་མ་རེད་པས།  དེ་སྔ་ང་ཚོ་།

05:41 བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་དང། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།

05:50  བྱས་ནས་ soul (རྣམ་ཤེས།)ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག ག 

05:53 བྱས་གཙང་ག ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ།  དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།

05:58 ཡང་ན་གཅིག་ངན་སོང་ལ་འགྲོ་མཁན་འདྲ་བོ་གཅིག་ཡོད་རེད་བ་།  ༼རྣམ་ཤེས།༽soul ཟེར་ཡ་གཅིག

06:02  ཁོ་ཚེ་འདི་ནས་འཕོས་ནས་ཁོ་ཚེ་ཕྱི་མ་ལ་འགྲོ་བསྡད་མཁན་ཞིག་འདུག་བ། ད་ང་ཚོ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ན་བཞིན་བྱས་ནས་ཁོ་སྐྱེ་བ་གསར་པ་གཅིག་ད་ལེན་གི་ཡོད་མ་རེད།

06:09 ཡིན་ནས་གང་ལྟར་མཐའ་མ་དག་ཞིང་ལ་འགྲོ་མཁན་དང༌།  ལྷ་ཡུལ་ heaven ལ་འགྲོ་མཁན་དང། ཡང་ན་དམྱལ་བ་hellལ་འགྲོ་མཁན་གཅིག་ཡོད་རེད་བ་ད།

06:17 ད་འདི་ཨིའེ་ཨིའི་ཕུང་པོ་འདི་དང་འབྲེལ་བ་ཡིན་ན། ཕུང་པོ་འདི་འགགས་ཚར་དུས་ཁོ་ཡོང་ཡ་ཡོད་མ་རེད་བ། 

06:23 བྱས་ཙང་དེ་འདྲས་ཡིན་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་ཅིག་ཁས་ལེན་གི་འདུག་བ་  soul ༼རྣམ་ཤེས།༽ཟེར་ཡག་བཤད་ཀི་འདུག་ག།

06:28 བྱས་ཙང་སྔ་མོ་མུ་སྟེགས་པ་ཚོས་རྟག་གཅིག་རང་དབང་བའི་བདག་། ད་ད་ལྟ་མུ་སྟེགས་པ་ཚོས་མུ་སྟེགས་པ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཚོའི་གྲས་ཀྱིས་

06:37 ཨེ་ནས་ཨིའི་འོ་རེད་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཡི་ཚེ་སྔ་མ་ནས་འདིར་འོང་མཁན་། འདི་ནས་ཕྱི་མར་འགྲོ་མཁན་གཅིག་ཡོད་རེད་སེ། 

06:45 སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་ད་གིའི་སྟེང་ནས་ང་བཞག་བ་ཡིན་ན། ཨེ་ནས་ལུས་འདི་བཞག་ཚར་དུས་ཙ་ནས་ལུས་འདི་སྔ་མ་ནས་ཡོང་བ་མ་རེད་བ། 

06:54 ལུས་འདི་ཕྱི་མ་ལ་འགྲོ་ཡི་ཡོད་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་འདིར་ལ་ལྟོས་པ་མེད་པའི་སྡད་མཁན་གྱི་བདག་རང་རྐྱ་བ་གཅིག་དགོས་ཀི་འདུག་ཟེར་གྱིས་ནས།

07:02 ད་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གཅིག་བཤད་ཀྱི་ཡོད་རེད། དེ་འདྲའི་ཀི་བདག་དེ་ཨེ་ནས་ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།ཨིའི་འགྱུར་བ་མེད་བསྡད་མཁན་གྱི་རྟག་པ། 

07:11 ཨེ་ནས་གཅིག་པུ། རང་དབང་བ། ཕུང་པོ་ལ་ལྟོས་པ་མེད་བསྡད་མཁན།  ཕུང་པོ་ལ་ལྟོས་མེད་རང་དབང་གི་གནས་བསྡད་མཁན་གཅིག་ཨོ་ཙེ་བཤད་ཀི་འདུག་ག
 འདི་ཡང་

07:20 བྱས་ཙང་དེང་སང་གི་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ག་རེད་ཟེར་གོ་རེད་ཕ་གིར་ཆོས་ལུགས་ལྟ་གྲུབ་ཡོད་དས་མཁན་ཕལ་མོ་ཆེས་ལབ་ཆོག་གི་མེདའགྲོ།

07:29 དེ་ལ་ཡ་ཚོ་ཐིག་གི་མི་འདུག་བ།  གང་ལྟར་ཕལ་མོ་ཆེ་ད་ལྟ་རྟག་གཅིག་རང་དབང་བའི་བདག་དེ་འདོད་ཀི་ཡོད་རེད།

07:38 བྱས་ཙང་བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས་ཟེར་ཡ་འདི། ད་འདས་པའི་ལོ།

07:45 སྟོང་ཕྲག་གསུམ་རྗེས་ནས་དུས་ད་ལྟ་བར་དུ་ད་ག་རང་བསྡད་བསྡད་པའི་ཟོ་འདྲ་བོ་ཞིག་འདུག་བ།

07:53འདས་པའི་ལོ་ཉིས་སྟོང་ལྔ་བརྒྱ་ནས་ད་ལྟ་བར་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱི་ཆོས་བྱུང་བ་ནས་ད་ལྟ་བར་དུ་བཙིས་པ་ཡིན་ན།
08:02  ཕྱི་རོལ་པའི་གྲུབ་མཐའི་སྨྲ་བའི་མཚན་ཉིད་ཅིག་བཞག་ནས་ད་དེ་ནས་རྣམ་གཞག་མདོར་བསྡུས་ཏེ་བཤད་པ། རང་སྡེའི་གྲུབ་མཐའི་རྣམ་གཞག་ཅུང་ཟད་ཕྱེ་སྟེ་བཤད་པའོ།

08:04ཕྱི་རོལ་པའི་གྲུབ་མཐའ་སྨྲ་བ་ལ་དབྱེ་ན་། ཨེ་ནས་འདིའི་ད་ལྟ་གོ་རིམ་འདི།

08:13  ཨིའི་ཨིའི་བསྡུས་ན། ཁྱབ་འཇུག་པ། དབང་ཕྱུག་པ། རྒྱལ་བ་པ། སེ་སེ་སེར་སྐྱ་པ། ཕུར་བུ་བ་བྱས་ནས་ལྔ་བཤད།

08:21ཡང་ན། རྩ་བའི་སྡེ་དྲུག་ཏུ་ཡང་བཤད་དེ། ཨིའི་བྱས་ནས་ད་གང་ལྟར། ཕུར་བ [...]

2023-04-14 17:25 UTC, Tenzindharten requested changes
00:00 ད་ཨོ་དེ་འདྲ་རྣམ་གཞག་ཅིག་བཤད་ཡོང་དུས་ཙ་ནས་ཐར་པ་ཟེར་ཡག་གི་སྐད་ཆ་དེ་སླེབ་ཡོང་གི་འདུག་ག།
00:04  ཐར་པ་དེ་ཕྱི་ལོག་གི་གྲོང་ཁྱེར་ལྟ་བུ་གཅིག་དང༌། གཅིག་དག་ཞིང་བཟོ་འདྲ་གཅིག་མ་ཡིན་པ།
00:09  ཐར་པ་ཟེར་ཡག་དེ་ནང་སེམས་རྒྱུད་ཀྱི་ད་སྡུག་བསྔལ་བར་བྱེད་མཁན་གྱི་ཨིའི་ཟག་པའི་སྐྱོན་དེ་གའི་དེ་མེད་པ་ཆགས་ཀྱིས།
 དེའི་རྩ་བ་བདག་ཏུ་འཛིན་པ་རེད། 
00:17 བདག་འཛིན་པ་མེད་པ། བདག བདག་མེད་པའི་དོན་ཤེས་པའི་བློ་དེས་ཨེ་ནས་གཉེན་པོ་བྱས་ནས།
00:22  ད་ལྟ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕར་འགགས་སོང་ན། ཨེ་ནས་བློ་དེའི་དབང་གིས་བྱུང་བའི་སྡུག་བསྔལ་དེ་འགགས་འགྲོ་ཡི་རེད།
00:29  སྡུག་བསྔལ་དེ་ཉེ་བར་ཞི་བར་རེད། སྡུག་བསྔལ་ནས་ཐར་བ་རེད་ཟེར་ཡག ཐར་པ་གཅིག་བཤད་དེ་འདྲས་འདྲ་བས་ཆོས་ཚུལ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ།
00:35 ཨེ་ནས་སྟོན་པ་འདྲ་འདྲ་ནང་ནས་མི་འདྲ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག འཛམ་བུ་གླིང་འདིའི་སྒང་གི་སྟོན་པ་ཕེའི་བརྒྱ་ཕྲག་སྟོང་ཕྲག་ཡོད་རེད་དེ།
00:43  ཡིན་ནས་དེའི་ནང་ནས་བདག་མེད་པ་ཟེར་མཁན་དེ་གསུང་མཁན་དེ་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཉག་ཅིག་མ་གཏོགས་གཞན་སུ་གཅིག་མི་འདུག་ག
00:48 འོ་དེ་འདྲས་ཡིན་དུས་ད་ཨིའི་སྟོན་པ་སྐྱོན་ཀུན་ཟད་ཅིང་ཡོན་ཏན་རྫོགས་པ་དང་།
00:54  ད་སེམས་ཅན་ལ་འཚེ་བ་མི་བྱེད་པ་ཙམ་དེ། གཅེར་བུ་བ་ཆ་བཞག་ན། ཧ་ལམ་ང་ཚོ་ནང་པ་ལས་ལྷག་རེད།
01:00  མུ་སྟེགས་རྒྱལ་བ་པ། མཧཱ་ཝིར་རྒྱལ་བ་པ་ཁོང་གི་རྗེས་འབྲངས་བྱས་མུ་སྟེགས་གཅེར་བུ་བ་རྒྱལ་བ་པ་ཟེར་མཁན་དེ་གའི་དེ།
01:10  སྤྱོད་པའི་ཆ་ནས་གཅེར་བུ་པ་བཏགས་པ་མིན་འགྲོ། སྟོན་པའི་ཆ་ནས་རྒྱལ་བ་པ། ཧ་ལམ་འཚེ་བ་མེད་པའི་ད་སྤྱོད་པ་ད་ང་ཚོ་ནང་པ་ལས་ལྷག་གི་རེད།

01:20 ཞེ་བོ་ཞིག་འདུག་ག འདི་དངོས་ཡོད་གནས་ཚུལ་རེད་བ་ད་ང་ཚོས་ཁས་ལེན་རེད་བ་། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་།
01:25  ཨིའི་ད་ཡིན་ནས་འཚེ་བ་མི་བྱེད་ཡག་གི་རྒྱུ་མཚན་བཤད་ཡོང་དུས་ཙ་ནས། སངས་རྒྱས་པས་རྩ་བ་རྩ་བ་སྙིང་རྗེ་གཏུག་ཡོང་གི་རེད།
01:34  མ་གཞི་མི་དགེ་བཅུ་སྤོང་གི་ཚུལ་ཁྲིམས་བསླབ་ཡ་ད་ཁ་ཐུག་དེ་གཞན་ལ་གནོད་པ་བྱས་ན།
01:39  དེའི་འབྲས་བུ་སྡུག་བསྔལ་ཡོང་གི་རེད་བྱས་ནས་འབྲས་བུ་སྡུག་བསྔལ་ལ་འཇིག་པའི་ཐོག་ནས་ད་དེ་འཚེ་བ་སྡོམ་ཡག་བཟོ་འདྲ་ཞིག་ཆགས་ཆགས་ཡོད་རེད་དེ་ཡིན་ནས་

01:45  རྩ་བ་རྩ་བ་འདི་སངས་རྒྱས་ཀྱི་བསྟན་པ་སྙིང་རྗེའི་རྩ་བ་ཅན་ཡིན་གསུངས་ཏེ། གཞན་ཨེ་ནས་རང་དང་རང་འདྲ་བར་ད་གཅེས་ཤིང་ཕངས་པ་ཅིག་ལ་བརྟེན་ནས།
01:54 དེ་ལ་གནོད་པ་བྱས་ན་ཡོང་གི་མ་རེད་ཟེར་ཡ་ད་རྩ་བ་དེར་ཐུག་ཡོང་གི་འདུག་ག
01:58  ད་ཡིན་ནས་མར་བསྟན་ཡོང་དུས་རྩ་ནས་ལས་དང་པོ་བ་ཚོ་ལ་ཡ་ཁྱེད་རང་གཞན་ལ་གནོད་པ་བྱས་ན། ཁྱོད་འདི་ཨེ་ནས་སྡིག་པའི་ལས་རེད།
02:06  ཁྱེད་རང་ལ་གནོད་ཀི་རེད་ཟེར་ཡག་ཅིག་གིས་འབྲས་བུ་ངན་པ་བསྟན་པའི་སྒོ་ནས་དེའི་རྒྱུ་ལྡོག་ཡ་ཅིག་ཐབས་ཤེས་ཤིག་གསུང་གི་འདུག་ག
02:14 རྩ་བ་གཏུག་ས་འདྲ་བོ་ཁོ་ཕལ་ཆེར་ག་རེ་ཟེར་བ་རེད། བཅོམ་ལྡན་འདས་ཀྱི་བསྟན་པ་འདི་ཨེ་ནས་སྙིང་རྗེའི་རྩ་བ་ཅན་གསུངས་བ་ཡིན་དུས་རྩ་ནས་
02:22 ད་དེ་འདྲའི་ཐོག་ནས་ཡོང་བསྡད་ཀི་ཡོད་རེད། སྙིང་རྗེ་ཡོང་ཡག་གི་་རྒྱུ་མཚན་འདི་ད་རང་ཞོགས་ཀའི་བཀའ་མོལ་འབྱུང་བ་ནང་བཞིན་རེད།
02:28  གང་ལྟར་ལྟ་བ་བཀར་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་ཟེར་ཡག་དེ་དང་འབྲེལ་ནས་སླེབ་ཡོང་གི་འདུག སླེབ་ཡོང་གི་འདུག་ག ཐར་པ་མེད་ན།
02:35 ཨེ་ནས་ཨིའི་ཟག་བཅས་ཀྱི་སྡུག་བསྔལ་གྱིས་མནར་བ་ལ། སྙིང་རྗེ་ཞེ་དྲག་ཞེ་དྲག་གས་བསམ་ཡག་སེ་མི་འདུག་ག ད་གང་དྲག་བསམ་པ་འདྲ་ཞིག་རེད་མ་གཏོགས།གཞན་ཞེ་དྲག་བསམ་བློ་གཏོང་ཡག་གས་མི་འདུག་ག
02:45  ད་ཡིན་ནས། ཁོ་ཟག་པའི་རྒྱུས་བྱུང་སྡུག་བསྔལ་གཉིས། ཟེར་ཡག་གི་ཟག་པ་དེ་འབྲལ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་ན།
02:52 ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་ཐབས་ཡོད་བཞིན་དུ། སྡུག་བསྔལ་དེའི་གཞན་དབང་དུ་གྱུར་བསྡད་པ་དེ་ལ་ད་གང་དྲག་ཅི་དྲག་བསམ་པ་གཅིག
02:58  ཁོ་གཅིག་དེ་ལས་ཐར་ཐབས་གཅིག་མཐོང་གིན་མཐོང་གིན་ལ། ད་དེ་ལས་ཐར་བའི་ཐབས་ལ་མི་བརྩོན་པ་ད་དུང་སྡུག་བསྔལ་མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་ཡི་གཞན་དབང་ལ་ཡ་འདུག་འགྲོ་བསྡད་ཡག་དེ།
03:09 ད་གང་དྲག་བསམ་པ་འདྲ་བོ་ཞིག་བློ་ལ་ཡར་ཤར་ཡག་ཅིག་ཡོང་གི་རེད་བ། བྱས་ཙང་སྙིང་རྗེ་ཁྱད་ཅིག་འདུག་ག ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་སྙིང་རྗེ་དེ་ཡིས་
03:15  སྡུག་བསྔལ་ཞེ་བོ་གཅིག་ཡོད་རེད། སྡུག་བསྔལ་འདི་ལ་མི་བཟོད་པ་ཞིག་ཡོད་རེད། མི་བཟོད་པའི་སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་བསྡད་པ་གཅིག་མཐོང་ཡོང་དུས།
03:24  སྙིང་རྗེ་དེ་རྣམ་དཔྱོད་ལྡན་པའི་སྙིང་རྗེ་རེད་འདུག་ག སྡུག་བསྔལ་དེ་སེལ་ཐབས་ཡོད་པ་གཅིག་མ་མཐོང་ན། སྡུག་བསྔལ་གྱིས་མནར་བ་དེ་ད་གང་དྲག་ཟེར་གཅིག
03:31  ཨེ་ནས་སོ་སོར་འུ་འདྲ་ཞིག་ཐུག ད་འུ་འདྲ་ཞིག་ཐུག་བྱས་ཨེ་ནས་དབུགས་རིང་བཏང་བྱས་བསྡད་རྒྱུ་རེད་མ་གཏོགས། གཞན་ག་གས་མི་འདུག་ག ད་འདི་ལྐུག་པའི་སྙིང་རྗེ་རེད་བ།
03:39  རེད་བ། རླབས་ཆེན་པོའི་སྙིང་རྗེ་འདི། དེ་བྲལ་ཡ་ཡོད་པ་གཅིག་མཐོང་གྱིས་རྒྱ་ཆེན་པོ་བྱས་འདུག་སེ་མཐོང་བྱས་བྱུང་པ་ཡིན་ན།
03:46  སྙིང་རྗེ་གཞན་དང་མི་འདྲ་བ་ཞིག་འདུག་ག སེ་དེ་འདྲས་ཡིན་དུས། སངས་རྒྱས་ཀི་སྙིང་རྗེ་དེས་དེ་ག་རེད་ཟེར་བ། ཕ་གིའི་ཨིའི་ད་ལྟ་བཀར་བཏགས་ཀྱི་ཕྱག་བཞི་བསྟན་ཡོང་དུས་ཙ་ནས་ཐར་པ་བཤད་ཡོང་གི་འདུག་ག
03:55 ཐར་པ་འདི་འདྲའི་གཅིག་བསྒྲུབ་རུང་ཡིན་པ་ཞིག་མཐོང་ཡོང་དུས་ཙ་ནས། ཨིའི་ཐར་པ་ཐོབ་པ་ལ་གེགས་བྱེད་མཁན་གྱི་ཉོན་མོངས་པའི་སྒྲིབ་པས་མནར་བསྡད་ནས་དེའི་དབང་གིས་སྡུག་བསྔལ་མྱངས་བསྡད་པ་དེ་གའི་དེ་ལ་ཡ།
04:02  སྙིང་རྗེ་སྐྱེ་ཡ་མི་འདྲ་བ་ཞིག་ཡོང་ས་རེད་བ། བྱས་ཙང་དེ་འདྲས་ཡིན་དུས་འཚེ་བ་མེད་པ་ཙམ་དུ་འདྲ་གི་རེད་དེ། ཡིན་ནས་འཚེ་བ་མེད་པ་དྲངས་ཡོང་ཡག་འདི།
04:12  སངས་རྒྱས་པའི་འཚེ་མེད་འཚེ་མེད་ཀྱི་ལྟ་བ་ཡོང་སྟངས་ཏོག་ཙམ་མི་འདྲ་བ་ཡོད་ས་རེད། ཨིའི་བསྟན་པ་སེམས་ཅན་ལ་འཚེ་བ་མེད་པ་དང༌།
04:19  ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པ་སེ། ཨིའི་ལྟ་བ་འདི་ད་ཨོ། གྲུབ་མཐའ་ཆེན་མོ་ནང་ལོག་ལ་ཡ།
04:29  ཨེ་ནས་ཨིའི་ག་རེ་ཟེར་ག བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས། ཟེར་ཡ་འདི་དཔེ་སྡོམ་ཆེན་པོ་རེད།
04:37  བདག་ཏུ་ལྟ་བའི་ཞེན་ཡུལ་གང་ཟག་རང་རྐྱ་བ་རེད་བ། བདག་རང་རྐྱ་བ།
04:46  བདག་རང་རྐྱ་བ་གྲུབ་པའི་དེ་འདྲས་འདྲ་བའི་ཞེན་ཡུལ་དེ་ཨེ་ནས་སྒྲུབ་མཁན་དེ་ཕྱི་པ།
04:54  བདག་ལྟའི་ཞེན་ཡུལ་འགོག་མཁན་འདི། ད་སྔོན་ལ་འགོག་ཐུབ་ན་མ་ཐུབ་ནས།འགོག་པ་ལ་བརྩོན་བསྡད་མཁན་དེ་ནང་པ། འོ་དེ་གསུང་ཡིན་པ་རེད།
05:03  བྱས་ཙང་། ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ལྟ་བ་དང་ལྡན་པ་དེ་འདྲས་འདྲ་བའི་ལྟ་བ་འདོད་པ་འདི་སངས་རྒྱས་པ་
05:14  ལྟ་བ་དེ་མི་འདོད་མཁན་དེ་ཨེ་ནས་གཞན་སྡེ་དེ་གསུངས་པ་མིན་འགྲོ། ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌། རང་སྡེ་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང་།
05:20  གཞན་སྡེ་རྣམས་ནི་དེ་ལས་ལྡོག་སྟེ་སྟོན་པ་སྐྱོན་དང་བཅས་ཤིང་ཡོན་ཏན་མ་རྫོགས་པ་དང༌།
05:26  བསྟན་པ་སེམས་ཅན་ལ་གནོད་ཅིང་འཚེ་བ་དང༌།
05:29  ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱིས་བདག་ཏུ་གྲུབ་པར་ཁས་ལེན་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་པའི་ཕྱིར་རོ།
05:33 ད་རྟག་གཅིག་རང་དབང་ཟེར་ཡག་གི ཨིའི་ཕལ་ཆེར་འདི་ད་དཔེར་ན་ཕྱིས་ཀྱི་ཕྱིས་ཟེར་གོ་མ་རེད་པས། དེ་སྔ་ང་ཚོ་།
05:42  བོད་དང་རྒྱ་གར་ལ་ཡ་མ་དར་བའི་ཡེ་ཤུ་དང༌། ཁ་ཆེ་དང། ཕལ་ཆེར་འཇིའུའི་judaism ཕལ་ཆེར་རེད།
05:49 བྱས་ནས་ soul (རྣམ་ཤེས།)ཟེར་ཡག་ཅིག་བཤད་ཀི་འདུག་ག
05:52  བྱས་ཙང་ག ད་ང་རང་ང་རང་ཚོ་མི་ཤི་པའི་རྗེས་ལ་ཡ། དག་ཞིང་ལ་འགྲོ་མཁན་ལྷ་ཡུལ་ལ་འགྲོ་མཁན་འདྲ་བོ།
05:57  ཡང་ན་གཅིག་ངན་སོང་ལ་འགྲོ་མཁན་འདྲ་བོ་གཅིག་གི་ཡོད་རེད་བ་། ༼རྣམ་ཤེས།༽soul ཟེར་ཡ་གཅིག
06:02  ཁོ་ཚེ་འདི་ནས་འཕོས་ནས་ཁོ་ཚེ་ཕྱི་མ་ལ་འགྲོ་བསྡད་མཁན་ཞིག་འདུག་བ། ད་ང་ཚོ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ན་བཞིན་བྱས་ནས་ཁོ་སྐྱེ་བ་གསར་པ་གཅིག་ད་ལེན་གི་ཡོད་མ་རེད།
06:09  ཡིན་ནས་གང་ལྟར་མཐའ་མ་དག་ཞིང་ལ་འགྲོ་མཁན་དང༌། ལྷ་ཡུལ་ heaven ལ་འགྲོ་མཁན་དང། ཡང་ན་དམྱལ་བ་hellལ་འགྲོ་མཁན་གཅིག་ཡོད་རེད་བ་ད།
06:18  ད་འདི་ཨིའེ་ཨིའི་ཕུང་པོ་འདི་དང་འབྲེལ་བ་ཡིན་ན། ཕུང་པོ་འདི་འགགས་ཚར་དུས་ཁོ་ཡོང་ཡག་ཡོད་མ་རེད་བ།
 06:24 བྱས་ཙང་དེ་འདྲས་ཡིན་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་ཅིག་ཁས་ལེན་གི་འདུག་བ་ soul ༼རྣམ་ཤེས།༽ཟེར་ཡག་བཤད་ཀི་འདུག་ག།
06:29  བྱས་ཙང་སྔ་མོ་མུ་སྟེགས་པ་ཚོས་རྟག་གཅིག་རང་དབང་བའི་བདག་སེ། ད་ད་ལྟ་མུ་སྟེགས་པ་ཚོས་མུ་སྟེགས་པ་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཚོའི་གྲས་ཀྱིས་
06:37 ཨེ་ནས་ཨིའི་འོ་རེད་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་དེ་ཡི་ཚེ་སྔ་མ་ནས་འདིར་འོང་མཁན། འདི་ནས་ཕྱི་མར་འགྲོ་མཁན་གཅིག་ཡོད་རེད་སེ།
06:46  སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་ད་གིའི་སྟེང་ནས་ང་བཞག་བ་ཡིན་ན། ཨེ་ནས་ལུས་འདི་བཞག་ཚར་དུས་ཙ་ནས་ལུས་འདི་སྔ་མ་ནས་ཡོང་བ་མ་རེད་བ།

06:54  ལུས་འདི་ཕྱི་མ་ལ་འགྲོ་ཡི་ཡོད་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ལུས་འདིར་ལ་ལྟོས་པ་མེད་པའི་བསྡད་མཁན་གྱི་བདག་རང་རྐྱ་བ་གཅིག་དགོས་ཀི་འདུག་ཟེར་གྱིས་ནས།
07:04  ད་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གཅིག་བཤད་ཀྱི་ཡོད་རེད། དེ་འདྲའི་ཀི་བདག་དེ་ཨེ་ནས་ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།  ཨིའི་འགྱུར་བ་མེད་བསྡད་མཁན་གྱི་རྟག་པ།
07:14  ཨེ་ནས་གཅིག་པུ། རང་དབང་བ། ཕུང་པོ་ལ་ལྟོས་པ་མེད་བསྡད་མཁན། ཕུང་པོ་ལ་ལྟོས་མེད་རང་དབང་གི་གནས་བསྡད་མཁན་གཅིག་ཨོ་ཙེ་བཤད་ཀི་འདུག་ག 
07:24  བྱས་ཙང་དེང་སང་གི་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ག་རེ་ཟེར་བ་རེད། ཕ་གིའི་་ཆོས་ལུགས་ལྟ་གྲུབ་ཡོད་བསྡད་མཁན་ཕལ་མོ་ཆེས་ལབ་ཆོག་གི་མེད་འགྲོ།
 07:34 ད་ངས་ཡང་རྦད་དེ་ཚོད་ཐིག་གི་མི་འདུག་ག  གང་ལྟར་ཕལ་མོ་ཆེ་ད་ལྟ་རྟག་གཅིག་རང་དབང་བའི་བདག་དེ་འདོད་ཀི་ཡོད་རེད།
07:38  བྱས་ཙང་བདག་ལྟའི་ཞེན་ཡུལ་སྒྲུབ་འགོག་ཕྱི་ནང་གཉིས་ཟེར་ཡག་འདི། ད་འདས་པའི་ལོ།
07:45  སྟོང་ཕྲག་གསུམ་རྗེས་ནས་དུས་ད་ལྟ་བར་དུ་ད་ག་རང་བསྡད་བསྡད་པའི་བཟོ་འདྲ་བོ་ཞིག་འདུག་བ།
07:49 འདས་པའི་ལོ་ཉིས་སྟོང་ལྔ་བརྒྱ་ནས་ད་ལྟ་བར་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱི་ཆོས་བྱུང་བ་ནས་ད་ལྟ་བར་དུ་བརྩིས་པ་ཡིན་ན།
 07:58 ཕྱི་རོལ་པའི་གྲུབ་མཐའི་སྨྲ་བའི་མཚན་ཉིད་ཅིག་བཞག་ནས་ད་དེ་ནས།
08:07 ཕྱི་རོལ་པའི་གྲུབ་མཐའ་སྨྲ་བ་ལ་དབྱེ་ན་། ཨེ་ནས་འདིའི་ད་ལྟ་གོ་རིམ་འདི།
08:13  ཨིའི་ཨིའི་བསྡུས་ན། ཁྱབ་འཇུག་པ། དབང་ཕྱུག་པ། རྒྱལ་བ་པ། སེ་སེ་སེར་སྐྱ་པ། ཕུར་བུ་བ་བྱས་ནས་ལྔ་བཤད།
08:20 ཡང་ན། རྩ་བའི་སྡེ་དྲུག་ཏུ་ཡང་བཤད་དེ། ཨིའི་བྱས་ནས་ད་གང་ལྟར། ཕུར་བུ་བའམ་རྒྱང་འཕེན་པ་ཟེར་ཡག་འདི་མུ་སྟེགས་ཆད་པར་སྨྲ་བ་ཟེར་ཡག་འད [...]

2023-04-18 05:12 UTC, merged