Hello Feiying
MonlamAI/STT001 pull request #2
Opened 2023-01-09 17:53 UTC by choephel-tashi

This is the MP3 format number three from STT001 which only  contained 3:28 minutes. Done by Choephel at 23:21 on 9 Jan 2023

2023-01-10 12:28 UTC, ngawangtrinley requested changes
Please rename your file to `stt001-12.otr`

2023-04-26 14:25 UTC, choephel-tashi commented
00:00རྒྱུ་མཚན་བསམ་བློ་བཏང་ནས་ཡོང་ཡ་གཅིག་བཤད་བ་རེད་མ་གཏོགས། སངས་རྒྱས་པའི་ཆོས་དེ་དད་པ་བྱས་ནས་ཡོང་ཡ་གཅིག་བཤད་ཡོད་མ་རེད།

00:06 རེད་བ། སེ་དེ་འདྲས་ཡིན་དུས་ཤེས་རབ་དེ་ཞེ་བོ་གཅིག་གལ་ཆེན་པོར་བཤད་པ་རེད།

00:12 པེར་ན་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀིས་ཨེ་ནས་དད་པ་གཅིག་པོ་ཐོག་ནས་འགྲིག གི་ཡོད་ན། ཆོས་འཁོར་དང་པོ་གསུང་དུས་ཙ་ནས་མི་ལ་ཡར་ང་དད་པ་བྱེད།

00:19ཨེ་ནས་ཁྱེད་རང་ཚོ་བདེ་སྐྱིད་ཡོང་གི་རེད་བྱས་ནས་གསུང་གོས་ཡག་གཅིག་རེད་དེ། དེ་གསུང་མི་འདུག་ག

00:25 དེའི་ཚེ་དེའི་དུས་རྒྱ་གར་ལ་ཡོད་བསྡད་པའི་ད་ཆོས་བརྒྱུད་མང་པོ་གཅིག་གིས་དཀོན་མཆོག་ལ་དད་པ་བྱས་ན། ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་གི་རེད་ཟེར་ཡག་གཅིག་ཡོད་པ་ཙ་ནས།

00:33བཅོམ་ལྡན་འདས་ཀྱིས་དེ་རྒྱུ་མཚན་མེད་པ་གཅིག་ལ་གཟིགས་ནས། དེ་རྒྱུ་མཚན་དང་མི་ལྡན་པ་གཅིག་ལ་གཟིགས་ནས།

00:39 སངས་རྒྱས་ཀྱིས་ཁོ་རང་གི་ཉམས་མྱོང་གི་སྟེང་ནས། ད་ཀུན་མཁྱེན་ཡེ་ཤེས་ཀྱི་ག་རེ་ཟེར་དགོས་རེད་སྟོབས་ལས་

00:46 ཨེ་ནས་གང་ལྟར་སྡུག་བསྔལ་ཟེར་ཡག་དེ་ཁོང་རྒྱུ་ལས་བྱུང་བ་གཅིག་ཡིན་པ་གཅིག་གཟིགས་བྱས།

00:51བྱས་ཙང་ག་དེ་འདྲས་་ཡིིན་དུས་རྒྱུ་རྒྱུ་དེ་འགོག་ཐབས་གཅིག་མ་བྱས་པར་སྐྱབས་སུ་མཆི་ཞེས་ལབ་བཞག་པས་ཡོང་གི་ཡོད་མ་རེད།

01:00དཔེར་ན་ང་རང་ཚོས། འོ་རེད་ད་ཁྱར་པར་གས་མི་འདུག།སེ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙ། ད་གང་ལྟར་རྒྱུ་འགོག་ཐབས་བྱེད་དགོས་ཀི་ཡོད་རེད། རྒྱུ་འགོག་ཐབས་བྱེད་ཡག་དེ་ག་འདྲས་གཅིག་རེད་ཟེར་ལབ་ན། སྤྱིར་བཏང་།

01:10 ཨིའི་དཔེར་ཆ་བཞག་ན་སྲོག་གཅད་རྒྱུ་ཡོད་མ་རེད་ཟེར། ག་རེ་རེད་ཟེར་ལབ་ན་སངས་རྒྱས་ཀྱིས་གསུངས་བ་རེད་ཟེར་ལབ་ན།

01:18 དེ་ཨེ་ནས་སླ་བོ་ཞེ་བོ་གཅིག་ཆགས་བ་རེད་བ།  ད་དེ་ལ་ཡར་རྒྱུ་མཚན་ལ་བསམ་བློ་གཏོང་དགོས་ཀྱི་ཡོད་རེད།

01:25 རེད་ད་ཨེ་ནས་རྒྱུ་དང་འབྲས་བུ་ཟེར་བསྡད་ཡག་ག་རེ་ག་རེ་ཡིན་པ། ད་ག་ན་བཞིན་གྱི་གཞན་ཨིའི་སྲོག་གཅོད་ཡུལ་དུ། སྲོག་གཅོད་ཡུལ་དེའི་ངོས་ནས་བཤད་པ་ཡིན་ན་ཡང་།

01:34 རང་དང་རང་འདྲ་བ་སྡུག་བསྔལ་མི་འདོད་པ་དང་བདེ་བ་འདོད་པ་རེད། ང་གཉིས་ཐོབ་ཐང་གཅིག་པ་རེད། རེད་དང་གཉིས་ཀ་འཆི་བ་ལ་མི་འདོད་པ་རེད།

01:42 དེ་འདྲས་ཡིན་དུས་ཕ་རོལ་པོའི་སྲོག་བཅད་ན་འགྲིག་གི་མ་རེད་བསམས་ནས་ད་འདུག་སེ་རྒྱུ་མཚན་ཤ་སྟག་བསམ་བློ་བཏང་ནས་འགྲོ་ཡག་རེད་མ་གཏོགས།

01:48 བཅོམ་ལྡན་འདས་ཀྱི་བཀའ་རེད་ཅེས་ནས་བཀའ་བརྗིད་པོ་ཞིག་ལ་བརྩིས་ནས་ཡོང་ཡག་མིན་པ་ཡིན་པ་རེད།

བཅོམ་ལྡན་འདས་ལ་དད་པ་ཁོ་ནས་འགྲིག་གི་ཡོད་ན།

01:56 ང་རང་ཚོ་དཔེར་ན་བོད་སྐད་ནང་ལ་བསྒྱུར་བཞག་པའི་བཀའ་འགྱུར་པོ་ཏི་བརྒྱ་ཟེར་ཡག་དེ་དགོས་ཡག་ཡོད་མ་རེད། བཅོམ་ལྡན་འདས་ཀྱིས་ཆོས་འཁོར་དང་པོ་གསུང་པའི་ཁ་ཐུག་ལ་ཡ་བདེན་པ་བཞི་གསུང་དགོས་ཡག་མེད་པ་རེད།

02:04བདེན་པ་བཞི་གསུངས་པའི་རྗེས་ལ་ཡར་རྟེན་འབྲེལ་ལུགས་འབྱུང་དང་ལུགས་ལྡོག་གི་རྣམ་གཞག་གསུངས་དགོས་ཡག་མེད་པ་རེད།

02:10ཨེ་ནས་ད་ག་ན་བཞིན་ཐེག་ཆེན་གྱི་དབང་དུ་བྱས་པ་ན། ཨེ་ནས་ཤེར་ཕྱིན་གྱི་མདོ་སྡེ་དེ་གས་དེ་དེ་འདྲའི་ཕེའི་རེད་དང་ཨེ་ནས་་ཕུང་ཁམས་སྐྱེད་མཆེད་ཀྱི།

02:18 ཆོས་མང་པོ་གཅིག་ལ་ཡ་ཨེ་ནས་འགྲེལ་རྐང་བརྒྱ་རྩ་ལ་སོགས་པ་དེ་འདྲ་མང་པོ་གཅིག་ཡོང་དགོས་ཡག་མེད་པ་རེད། དེ་གའི་ས་ལམ་གྱི་རྣམ་གཞག་མང་པོ་གཅིག་ཡོང་དགོས་ཡག་དང༌།

02:26གཞིའི་རྣམ་གཞག་གཏན་ལ་ཕབ་པ་ཞེ་བོ་གཅིག་གསུངས་བསྡད་ཡག་དེ་ཨིའི་རྒྱུ་མཚན་[ལ་]བསམ་བློ་་བཏང་ནས། རྒྱུ་མཚན་མཐོང་བའི་སྒོ་ནས་སེམས་ལ་འགྱུར་བ་འགྲོ་དགོས་ཀྱི་ཡོད་རེད་མ་གཏོགས།

02:35 རྒྱུ་མཚན་མ་མཐོང་བར་སྐྱབས་སུ་མཆི་ཟེར་བསྡད་ཡག་གཅིག་གིས་སེམས་ལ་བསྒྱུར་བཅོས་ཐེབས་ཡག་ཞེ་དྲག་ཁག་པོ་རེད། རེད་བ། དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས།

02:44ད་འོ་ཆོས་རབ་ཏུ་རྣམ་འབྱེད་ཀྱི་ཤེས་རབ་ཟེར་ཡག་དེ་ཞེ་བོ་གཅིག་གལ་[འགངས་]ཆེན་པོར་བཤད་པ་རེད། མདོར་ན་སངས་རྒྱས་ཀྱི་ཆོས་ཀྱིས་དད་པ་བཤད་ཡོད་རེད།

02:52དད་པ་བཤད་ཡོད་རེད་དེ། སངས་རྒྱས་པའི་ཆོས་ནས་བཤད་བཞག་པའི་དད་པ་དེ་ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་དད་པ་གཅིག་ལ་བཤད་ཀིན་ཡོད་རེད་མ་གཏོགས།

02:59ཤེས་རབ་ཀྱི་གྲོགས་མེད་བསྡད་མཁན་གྱིས་སྐྱབས་སུ་མཆི་ཟེར་བསྡད་ཡག་གི་དད་པ་རྐྱང་རྐྱང་གཅིག་གིས་ཨིའི་ད་དེ་གླེན་པ་གཏི་ཐུག་གི་བྱེད་སྟངས་རེད་མ་གཏོགས།

03:07 དེ་དངོས་ནས་རྨོངས་དད་བཟོ་འདྲ་ཆགས་ཀི་ཡོད་རེད། དེས་འགྲིག་གི་ཡོད་མ་རེད། སེ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ད་ག་རེད་ཟེར་དགོས་རེད་ཕ་གི་ཨིའི་རྒྱུ་མཚན་ལ་བསམ་བློ་བཏང་ནས།

03:17 སེམས་ལ་བསྒྱུར་བཅོས་གཏོང་དགོས་པ་ཡིན་དུས་ཙ་ནས། རྒྱུ་མཚན་དེ་གས་དེ་སྔོན་ལ་བསམ་བློ་གཏོང་ཡག་གི་ག་རེ་ཟེར་དགོས་རེད། གཞི་འདྲ་བོ་དེ་གས་དེ་གཅིག་ཤེས་དགོས་པ་རེད།

03:24 སེ་དེ་འདྲས་ཡིན་ཡིིན་དུས་ཙ་ནས་སངས་རྒྱས་པའི་ཆོས་ཀྱི་ནང་ལོག་ལ་ཡ་གཞིའི་གནས་ཚུལ་ཟེར་ཡག་གཅིག་བཤད་ཡོང་དེ་ཞེ་བོ་གཅིག་གི་གལ་གནད་ཆེན་པོ་བཤད་ཀྱི་འདུག་བ།

03:33 དེ་ཡང་ད་ལྟ་དེ་རྩ་བ་ཤེས། ག་རེ་ཟེར་བ་་ཨ་དེ། ཨིའི་ཨིའི།

03:40 དེ་ཡང་ད་ལྟ་སྤྱོད་འཇུག།[ཨ་ལྟ་]ད་ལྟ་ཤེས་རབ་ལེའུ་ནང་ལས་དོན་ད་ལྟ་གསུངས་ཀིན་ཡོད་རེད་ལ་ད་ལྟ་དེ་

03:46 ཨིའི་ག་རེ་ཟེར་དེ་གང་ཡིན་ན་གཅིག་ཟེར་ཡག་མེད་ན་དེ། ཨིའི།

03:53 ཡན་ལག་འདི་དག་ཐམས་ཅད་ནི། ། ཐུབ་པས་ཤེས་རབ་དོན་དུ་གསུངས་ཟེར། ད་ངས་དེའི་གཤམ་དེ། འོ་ད་དེ་འདྲ་གཅིག་ཡིན་པ་འདྲ།

04:00ཨ་རྩ་བ་ཤེས་རབ་ནས། སངས་རྒྱས་རྣམས་ཀྱིས་ཆོས་བསྟན་པ།།  ཟེར་ནས་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱིས་ཆོས་གསུངས་ཡག་དེ་གས་དེ་ཚང་མ་ལོག་གཞི་བདེན་པ་གཉིས་ལ་བརྟེན་ནས་གསུངས་བཞག་པ་རེད་བྱས་ནས།

04:10ད་གསུངས་བསྡད་དེ་གིས་དངོས་ཡོད་གནས་ཚུལ་ག་རེ་ཡོད་པ་དེ་གས་དེ་སྔོན་ལ་ཤེས་པར་བྱས།

04:16 དངོས་ཡོད་གནས་ཚུལ་དེ་གས་དེ་ཤེས་པའི་ཐོག་ནས། ད་དབྱིན་ཇིའི་སྐད་ཆའི་ནང་ངས་དེ་བཤད་བསྡད་ཀྱི་ཡོད common sense ཟེར་ཡག་དེ common sense

04:22 རང་གིས་ཤེས་ཀྱི་རེད་བ། ད་[ཡོད་]སྤྱིར་བཏང་ང་ཚོའི་[ར་]བསམ་བློ་གཅིག་འདུག་བ། common sense common sense བེད་སྤྱོད་བྱས་ནས་སངས་རྒྱས་བྱེད་ཡག་གཅིག་རེད་མ་གཏོགས།

04:31 common sense མ་འདྲེས་པར་བྱེད་ཀྱིས་ཨེ་ནས་[ནི]་དད་པའི་ཐོག་ནས་འགྲོ་ཡག་གཅིག་རྩ་བ་ཉིད་ནས་མིན་པ་ཡིན་པ་རེད།

04:36 བྱས་ཙང་ག་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ད་ཡུལ་གྱི་གནས་ལུགས་གཏན་ལ་ཕབ་ནས། ཡུལ་གྱི་རྣམ་གཞག་ག་འདྲའི་གཅིག་ཡིན་པ་དེ་གས་དེ་ཤེས་པའི་ཐོག་ནས།

04:45ད་དེའི་ནང་གི་གཙོ་བོ་གཙོ་བོ་དེ་བདེ་བ་དང་སྡུག་བསྔལ་ཟེར་ཡག་དེ་རེད། བདེ་བ་དང་སྡུག་བསྔལ་ཟེར་ཡག་དེ་རྒྱུ་གང་ལ། བདེ་བ་དང་སྡུག་བསྔལ་ངོ་བོ་[མི་འདྲ་]མི་འདྲ་བ་ག་འདྲས་ག་འདྲས་ཡོད་རེད།

04:54 ཨིའི་དེ་དང་དེའི་ཨིའི་བདེ་སྡུག་མི་འདྲ་བ་མང་པོ་ཡོད་པ་དེ་གས་དེ། ད་ངས་གཙོ་བོ་ད་གིན་ཞུ་ཡག་དེ། གཙོ་བོ་ལུས་ཚོར་ལ་བརྟེན་པའི་བདེ་སྡུག།

05:02གཙོ་བོ་སེམས་ཚོར་ལ་བརྟེན་པའི་བདེ་སྡུག ད་སེམས་ཚོད་ཟེར་དགོས་རེད་བས་ཡིད་བློ་ལ་བརྟེན་པའི་བདེ་སྡུག།དེ་གས་དེ་ཡིས་འཕྲལ་གྱི་དངོས་རྒྱུ་ག་རེ་ག་རེ་བྱེད་ཀྱི་ཡོད་པ།

05:11 དངོས་ཀྱི་རྒྱུ་དང་རྐྱེན་ག་རེ་ག་རེ་བྱེད་ཀྱི་ཡོད་པ་བརྒྱུད་ནས་ཕུགས་ནས་རྒྱུ་དང་རྐྱེན་གང་གང་གིས་བྱེད་ཀྱི་ཡོད་པ་དེ་གས་དེ་ད་རྩད་གཅོད་བྱེད་ཡག་དེ་གལ་ཆེན་པོ་ཞེ་བོ་གཅིག་ཆགས་འདུག་བ།

05:19 སེ་དེ་འདྲ་ཡིན་དུས་ཙ་ནས་སངས་རྒྱས་པའི་ཆོས་ཀྱི་ནང་ལོག་ལ་ཡ་ལས་ཀྱི་རྣམ་གཞག་དེ་མང་པོ་ཞེ་བོ་གཅིག་གསུང་གི་ཡོད་རེད་བ།

05:25ཨིའི་ད་ག་ནང་བཞིན་གཙོ་བོ་གཙོ་བོ་ཨེ་ནས་ཉོན་མོངས་པའི་གང་ལྟར་ཀུན་ཉོན་ཟེར་ཡག་དེ་གལ་ཆེ་ཤོས་ཤིག་ཆགས་ཡོད་དུས་ཙ་ནས།

05:33 ཉོན་མོངས་པ་གཏན་ལ་ཕབ་ཡག་དོན་དག་ལ་ཉོན་མོངས་པ་དང་དེའི་གཉེན་པོ་གཏན་ལ་ཕབ་ཡག་དོན་དག་ལ་ཨིའི་ཤེས་པའི་རྣམ་གཞག་དེ་མང་པོ་ཞེ་བོ་གཅིག་ཐོན་ཡོང་གི་འདུག་བ།

05:41རེད་བ། དེ་འདྲས་ཡིན་པ[ས་]ཡིིན་དུས་ཙ[ང་]ནས་ད་གང་ལྟར་གཞི་བདེན་པ་གཉིས་དེ་ལ་བརྟེན་་པའི།

05:48 ཨེ་ནས་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི་བདེན་པ་བཞི། ད་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི་ཀུན་ནས་ཉོན་མོངས་ཕྱོགས་དང༌། རྣམ་བྱང་ཕྱོགས་ཀྱི་

05:56 རྒྱུ་འབྲས་ཚན་པ་གཉིས་གཏན་ལ་ཕབ་ཡག་གི་བདེན་པ་བཞི་གསུངས་བསྡད་ཡག ད་དེ་ཕར་ཏོག་ཙམ་ཞིབ་ཚགས་སུ་བཏང་ནས། རྟེན་འབྲེལ་ཡན་ལག་བཅུ་གཉིས་ལུགས་འབྱུང་ལུགས་ལྡོག་གི་སྒོ་ནས།

06:04ཨེ་ནས་བདེན་པ་བཞི་པོ་དེ་མར་འགྲེལ་བཤད་རྒྱག་ཡོང་ཡག། ད་དེའི་གཞི་རྩ་ཕར་ཕར་གཏུག་ཡོང་དུས་ཙ[ང]་ནས་ཆོས་རྣམས་རང་བཞིན་གྱིས་གྲུབ་པ་མེད་པར།

06:11རྟེན་འབྲེལ་ལྟོས་གྲུབ་ཙམ་ཟེར་ཡག་སྐད་ཆ་དེའི་སྒང་ནས་ཨེ་ནས་[ནི་]ཨིའི་ནང་པའི་གཞུང་དེ་བཤད་ཡོང་གི་ཡོད་རེད།

06:17སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཨིའི་་ཀླུ་སྒྲུབ་ལ་སོགས་པ་དེ་གས་དེ་གིས་ད་བཀའ་འགྱུར་གྱི་འགྲེལ་པ་སྐྱོན་ཡོང་དུས་ཙ་ས་ནས།

06:25 ད་བསྟན་འགྱུར་ང་ཚོ་བོད་སྐད་ནང་ལ་བསྒྱུར་བཞག་པའི་ཉིས་བརྒྱ་ལྷག་ཙམ་གྱི་ཉིས་བརྒྱ་ཉི་ཤུ་རྩ་གྲངས་ད་ཡོད་བསྡད་པ་དེ་གས་དེ་ད་གང་ལྟར་དངོས་པོའི་གནས་ཚུལ་གཏན་ལ་ཕབ་ཡག།

06:34 མ་གཞི་ལམ་གྱི་རྣམ་གཞག་མང་པོ་བཤད་ཀིན་ཡོད་རེད། འབྲས་བུའི་རྣམ་གཞག་མང་པོ་གཅིག་བཤད་ཀྱི་ཡོད་རེད་དེ། ཡིན་ནས་འབྲས་བུའི་རྣམ་གཞག་དེ་དང་དེ་ལྟ་བུ་ཡོང་བ་ལ་མིང་ཁོ་རང་འབྲས་བུ་སེ་ལབ་པ་ཡིན་དུས།

06:42 རྒྱུ་གཅིག་ལ་བརྟེན་ནས་བྱུང་བསྡད་པ་གཅིག་ཡིན་པ་དེ་གསལ་པོ་ཞེ་དྲག་རེད་བ། བྱས་ཙང་ག་དེའི་དངོས་ཀྱི་རྒྱུ་འདྲ་བོ་དེ་ལམ་དེ་ཡིས་བཤད་ཡོད་རེད།

06:50འོ་ད་ལམ་དེ་གས་དེ་ཡོང་ཡག་གི་གཞི་རྩའི་རྒྱུ་འདྲ་བོ་དེ་གཞིའི་རྣམ་གཞག་གིས་བཤད་ཡོང་གི་ཡོད་རེད་བ།

06:56 ཨིའི་གཞི་ལ་ཡར་ཁམས་བདེ་གཤེགས་སྙིང་པོ་ཟེར་ཡག་གཅིག་དང༌། གཞི་ལ་སེམས་འོད་གསལ་བ་གཅིག་སེམས་འོད་གསལ་བ་གཅིག་དང༌།

07:02 ཨིའི་རྟེན་འབྲེལ་རྟོག་བཏགས་ཙམ་གཅིག་གིས་གཞིའི་གནས་ཚུལ་ཞིག་མེད་ན། འགྱུར་བ་འགྲོ་ཤེས་ཀྱི་མ་རེད་བ།

07:07 འགྱུར་བ་འགྲོ་ཡག་མེད་ན་འགྱུར་བ་གཏོང་ཡག་གི་ལམ་ཡོང་མ་རེད་བ༌། འགྱུར་བ་གཏོང་ཡག་དང་འགྱུར་བ་བཏང་ནས་འགྱུར་བ་ཐེབས་པའི་གནས་སྐབས་ཀྱི[ས་]གནས་སྐབས་མི་འདྲ་བ་ཡོང་ཤེས་ཀྱི་མ་རེད་བ།

07:16 གཞི་དེ་འགྱུར་བ་འགྲོ་ཡག་མེད་ན། སེ་དེ་མེད་ན་འགྱུར་བ་མཐར་ཐུག་པའི་གནས་སྐབས་ཀྱི་འབྲས་བུའི་གནས་སྐབས་ཡོང་ཤེས་ཀྱི་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་དུས་མིང་ཁོ་རང་།

07:25 གཞི། ལམ། འབྲས་བུ་ཟེར་གྱིས་ནས་བཤད་བསྡད་ཡག་དེ་གིས་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་ཟེར་ཡག་དེའི་སྒང་ནས་འགྲེལ་བཤད་དེ་སླེབས་ཡོང་གི་འདུག་བ། རྒྱུ་འབྲས་རྒྱུ་འབྲས་རྟེན་འབྱུང་གི་འབྲེལ་བ་དེ་བཤད་ཡོང་གི་འདུག་བ།

07:34 རྒྱུ་འབྲས་རྟེན་འབྱུང་གི་འབྲེལ་བ་འཐད་ཡག་ཁོ་རང་ལྟོས་གྲུབ་ཀྱི་ད་རྟེན་འབྲེལ་དེའི་ཐོག་ནས་ཨེ་ནས་རྒྱུ་འབྲས་རྟེན་འབྱུང་གི་འབྲེལ་དེ་འཐད་པ་གཅིག་བཤད་ཐུབ་ཡག་འདུག་བ།

07:42ས [...]

2023-04-27 03:40 UTC, Tenzindharten requested changes
00:00རྒྱུ་མཚན་བསམ་བློ་བཏང་ནས་ཡོང་ཡ་གཅིག་བཤད་བ་རེད་མ་གཏོགས། སངས་རྒྱས་པའི་ཆོས་དེ་དད་པ་བྱས་ནས་ཡོང་ཡ་གཅིག་བཤད་ཡོད་མ་རེད།

00:06 རེད་བ། སེ་དེ་འདྲས་ཡིན་དུས་ཨིའི་ཤེས་རབ་དེ་ཞེ་བོ་གཅིག་གལ་ཆེན་པོར་བཤད་པ་རེད།

00:12 དཔེར་ན་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀིས་ཨེ་ནས་དད་པ་གཅིག་པོ་ཐོག་ནས་འགྲིག་གི་ཡོད་ན། ཆོས་འཁོར་དང་པོ་གསུང་དུས་ཙ་ནས་མི་ལ་ཡ་ང་དད་པ་བྱེད།

00:19ཨེ་ནས་ཁྱེད་རང་ཚོ་བདེ་སྐྱིད་ཡོང་གི་རེད་ཟེར་བྱས་ནས་གསུང་དགོས་ཡག་གཅིག་རེད་དེ། དེ་གསུང་མི་འདུག་ག

00:25 དེའི་ཚེ་དེའི་དུས་རྒྱ་གར་ལ་ཡོད་བསྡད་པའི་ད་ཆོས་བརྒྱུད་མང་པོ་གཅིག་གིས་དཀོན་མཆོག་ལ་དད་པ་བྱས་ན། ཨེ་ནས་སྡུག་བསྔལ་ལས་ཐར་གི་རེད་ཟེར་ཡག་གཅིག་ཡོད་པ་ཡིན་དུས་ཙ་ནས།

00:33བཅོམ་ལྡན་འདས་ཀྱིས་དེ་རྒྱུ་མཚན་མེད་པ་གཅིག་ལ་གཟིགས་ནས། དེ་རྒྱུ་མཚན་དང་མི་ལྡན་པ་གཅིག་ལ་གཟིགས་ནས།

00:39 སངས་རྒྱས་ཀྱིས་ཨིའི་ཁོ་རང་གི་ཉམས་མྱོང་གི་སྟེང་ནས། ད་ཀུན་མཁྱེན་ཡེ་ཤེས་ཀྱི་ག་རེ་ཟེར་དགོས་རེད་སྟོབས་ལས་

00:46 ཨེ་ནས་གང་ལྟར་སྡུག་བསྔལ་ཟེར་ཡག་དེ་ཁོང་རྒྱུ་ལས་བྱུང་བ་གཅིག་ཡིན་པ་གཅིག་གཟིགས་བྱས།

00:51བྱས་ཙང་ག དེ་འདྲས་་ཡིིན་དུས་རྒྱུ་རྒྱུ་དེ་འགོག་ཐབས་གཅིག་མ་བྱས་པ་སྐྱབས་སུ་མཆི་ཟེར་ནས་ལབ་བཞག་པས་ཡོང་གི་ཡོད་མ་རེད།

01:00དཔེར་ན་ང་རང་ཚོ། འོ་རེད། ད་ཁྱར་པར་གས་མི་འདུག།སེ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙ། ད་གང་ལྟར་རྒྱུ་འགོག་ཐབས་བྱེད་དགོས་ཀི་ཡོད་རེད། རྒྱུ་འགོག་ཐབས་བྱེད་ཡག་དེ་ག་འདྲས་གཅིག་རེད་ཟེར་ལབ་ན། སྤྱིར་བཏང་།

01:10 ཨིའི་དཔེར་ཆ་བཞག་ན་སྲོག་གཅད་རྒྱུ་ཡོད་མ་རེད་ཟེར། ག་རེ་རེད་ཟེར་ལབ་ན་སངས་རྒྱས་ཀྱིས་གསུངས་བ་རེད་ཟེར་ལབ་ན།

01:18 དེ་ཨེ་ནས་སླ་བོ་ཞེ་བོ་གཅིག་ཆགས་བ་རེད་བ། ད་དེ་ལ་ཡ་རྒྱུ་མཚན་ལ་བསམ་བློ་གཏོང་དགོས་ཀྱི་ཡོད་རེད།

01:25 རེད་ད། ཨེ་ནས་རྒྱུ་དང་འབྲས་བུ་ཟེར་བསྡད་ཡག་ག་རེ་ག་རེ་ཡིན་པ། ད་ག་ནང་བཞིན་གྱི་གཞན་ཨིའི་སྲོག་གཅོད་ཡུལ་དུ། སྲོག་གཅོད་ཡུལ་དེའི་ངོས་ནས་བཤད་པ་ཡིན་ན་ཡང་།

01:34 རང་དང་རང་འདྲ་བ་སྡུག་བསྔལ་མི་འདོད་པ་དང་བདེ་བ་འདོད་པ་རེད། ང་གཉིས་ཐོབ་ཐང་གཅིག་པ་རེད། རེད་ད། གཉིས་ཀ་འཆི་བ་ལ་མི་འདོད་པ་རེད།

01:42 དེ་འདྲས་ཡིན་དུས་ཕ་རོལ་པོའི་སྲོག་བཅད་ན་འགྲིག་གི་མ་རེད་བསམས་ནས། ད་འདུག་སེ་རྒྱུ་མཚན་ཤ་སྟག་བསམ་བློ་བཏང་ནས་འགྲོ་ཡག་རེད་མ་གཏོགས།

01:48 བཅོམ་ལྡན་འདས་ཀྱི་བཀའ་རེད་ཅེས་ནས་བཀའ་བརྗིད་པོ་ཞིག་ལ་བརྩིས་ནས་ཡོང་ཡག་མིན་པ་ཡིན་པ་རེད། བཅོམ་ལྡན་འདས་ལ་དད་པ་ཁོ་ནས་འགྲིག་གི་ཡོད་ན།

01:56 ང་རང་ཚོ་དཔེར་ན་བོད་སྐད་ནང་ལ་བསྒྱུར་བཞག་པའི་བཀའ་འགྱུར་པོ་ཏི་བརྒྱ་ཟེར་ཡག་དེ་དགོས་ཡག་ཡོད་མ་རེད། བཅོམ་ལྡན་འདས་ཀྱིས་ཆོས་འཁོར་དང་པོ་གསུང་པའི་ཁ་ཐུག་ལ་ཡ་བདེན་པ་བཞི་གསུང་དགོས་ཡག་མེད་པ་རེད།

02:04བདེན་པ་བཞི་གསུངས་པའི་རྗེས་ལ་ཡ་རྟེན་འབྲེལ་ལུགས་འབྱུང་དང་ལུགས་ལྡོག་གི་རྣམ་གཞག་གསུངས་དགོས་ཡག་མེད་པ་རེད།

02:10ཨེ་ནས་ད་ག་ནང་བཞིན་ཐེག་ཆེན་གྱི་དབང་དུ་བྱས་པ་ན། ཨེ་ནས་ཤེར་ཕྱིན་གྱི་མདོ་སྡེ་དེ་གས་དེ། དེ་འདྲས་ཀི་ཕེའི་རེད་ད། ཨེ་ནས་་ཕུང་ཁམས་སྐྱེད་མཆེད་ཀྱི།

02:18 ཆོས་མང་པོ་གཅིག་ལ་ཡ་ཨེ་ནས་འགྲེལ་རྐང་བརྒྱ་རྩ་ལ་སོགས་པ་དེ་འདྲ་མང་པོ་གཅིག་ཡོང་དགོས་ཡག་མེད་པ་རེད། དེ་གས་དེ་ས་ལམ་གྱི་རྣམ་གཞག་མང་པོ་གཅིག་ཡོང་དགོས་ཡག་དང༌།

02:26གཞིའི་རྣམ་གཞག་གཏན་ལ་ཕབ་པ་ཞེ་བོ་གཅིག་གསུངས་བསྡད་ཡག་དེ། ཨིའི་རྒྱུ་མཚན་བསམ་བློ་་བཏང་ནས། རྒྱུ་མཚན་མཐོང་བའི་སྒོ་ནས་སེམས་ལ་འགྱུར་བ་འགྲོ་དགོས་ཀྱི་ཡོད་རེད་མ་གཏོགས།

02:35 རྒྱུ་མཚན་མ་མཐོང་བར་སྐྱབས་སུ་མཆི་ཟེར་བསྡད་ཡག་གཅིག་གིས་སེམས་ལ་བསྒྱུར་བཅོས་ཐེབས་ཡག་ཞེ་དྲག་ཁག་པོ་རེད། རེད་བ། དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས།

02:44ད་འོ་ཆོས་རབ་ཏུ་རྣམ་འབྱེད་ཀྱི་ཤེས་རབ་ཟེར་ཡག་དེ་ཞེ་བོ་གཅིག་གལ་ཆེན་པོར་བཤད་པ་རེད། མདོར་ན་སངས་རྒྱས་ཀྱི་ཆོས་ཀྱིས་དད་པ་བཤད་ཡོད་རེད།

02:52དད་པ་བཤད་ཡོད་རེད་དེ། སངས་རྒྱས་པའི་ཆོས་ནས་བཤད་བཞག་པའི་དད་པ་དེ་ཤེས་རབ་ཀྱི་གྲོགས་དང་བཅས་པའི་དད་པ་གཅིག་ལ་བཤད་ཀིན་ཡོད་རེད་མ་གཏོགས།

02:59ཤེས་རབ་ཀྱི་གྲོགས་མེད་བསྡད་མཁན་གྱིས་སྐྱབས་སུ་མཆི་ཟེར་བསྡད་ཡག་གི་དད་པ་རྐྱང་རྐྱང་གཅིག་གིས་ཨེ་ནས་ད་དེ་གླེན་པ་གཏི་ཐུག་གི་བྱེད་སྟངས་རེད་མ་གཏོགས།

03:07 དེ་དངོས་ནས་རྨོངས་དད་བཟོ་འདྲ་ཆགས་ཀི་ཡོད་རེད། དེ་འགྲིག་གི་ཡོད་མ་རེད། སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ད་ག་རེ་ཟེར་དགོས་རེད། ཕ་གིའི་ཨིའི་རྒྱུ་མཚན་ལ་བསམ་བློ་བཏང་ནས།

03:17 སེམས་ལ་བསྒྱུར་བཅོས་གཏོང་དགོས་པ་ཡིན་དུས་ཙ་ནས། རྒྱུ་མཚན་དེ་གས་དེ་སྔོན་ལ་བསམ་བློ་གཏོང་ཡག་གི་ག་རེ་ཟེར་དགོས་རེད། གཞི་འདྲ་བོ་དེ་གས་དེ་གཅིག་ཤེས་དགོས་པ་རེད།

03:24 སེ་དེ་འདྲས་ཡིན་ཡིིན་དུས་ཙ་ནས་སངས་རྒྱས་པའི་ཆོས་ཀྱི་ནང་ལོག་ལ་ཡ་གཞིའི་གནས་ཚུལ་ཟེར་ཡག་གཅིག་བཤད་ཡོང་དེ་ཞེ་བོ་གཅིག་གི་གལ་གནད་ཆེན་པོ་བཤད་ཀྱི་འདུག་བ།

03:33 དེ་ཡང་ད་ལྟ་དེ་རྩ་བ་ཤེས། ག་རེ་ཟེར་བ་དེ། ཨིའི་ཨིའི།

03:40 དེ་ཡང་ད་ལྟ་སྤྱོད་འཇུག།ད་ལྟ་ཤེས་རབ་ལེའུ་ནང་ལས་དོན་ད་ལྟ་གསུང་ཀིན་ཡོད་རེད་ལ་ད་ལྟ་དེ། 

03:46 ཨིའི་ག་རེ་ཟེར་བ་དེ་གང་ཡིན་ན་གཅིག་ཟེར་ཡག་མིན་པས་དེ། ཨིའི།

03:53 ཡན་ལག་འདི་དག་ཐམས་ཅད་ནི། ། ཐུབ་པས་ཤེས་རབ་དོན་དུ་གསུངས་ཟེར། ད་ངས་དེའི་གཤམ་དེ། འོ་ད་དེ་འདྲ་གཅིག་ཡིན་པ་འདྲ།

04:00ཨ་རྩ་བ་ཤེས་རབ་ནས། སངས་རྒྱས་རྣམས་ཀྱིས་ཆོས་བསྟན་པ།། ཟེར་ནས་སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱིས་ཆོས་གསུངས་ཡག་དེ་གས་དེ་ཚང་མ་ལོག་གཞི་བདེན་པ་གཉིས་ལ་བརྟེན་ནས་གསུངས་བཞག་པ་རེད་བྱས་ནས།

04:10ད་གསུངས་བསྡད་དེ་གིས་དངོས་ཡོད་གནས་ཚུལ་ག་རེ་ཡོད་པ་དེ་གས་དེ་སྔོན་ལ་ཤེས་པར་བྱས།

04:16 དངོས་ཡོད་གནས་ཚུལ་དེ་གས་དེ་ཤེས་པའི་ཐོག་ནས། ད་དབྱིན་ཇིའི་སྐད་ཆའི་ནང་ངས་དེ་བཤད་བསྡད་ཀྱི་ཡོད common sense ཟེར་ཡག་དེ common sense

04:22 རང་གིས་ཤེས་ཀྱི་རེད་བ། ད་སྤྱིར་བཏང་ང་ཚོའི་བསམ་བློ་གཅིག་འདུག་བ། common sense common sense བེད་སྤྱོད་བྱས་ནས་སངས་རྒྱས་བྱེད་ཡག་གཅིག་རེད་མ་གཏོགས།

04:31 common sense མ་འདྲེས་པར་བྱེད་ཀྱིས་ཨེ་ནས་དད་པའི་ཐོག་ནས་འགྲོ་ཡག་གཅིག་རྩ་བ་ཉིད་ནས་མིན་པ་ཡིན་པ་རེད།

04:36 བྱས་ཙང་ག དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ད་ཡུལ་གྱི་གནས་ལུགས་གཏན་ལ་ཕབ་ནས། ཡུལ་གྱི་རྣམ་གཞག་ག་འདྲས་གཅིག་ཡིན་པ་དེ་གས་དེ་ཤེས་པའི་ཐོག་ནས།

04:45ད་དེའི་ནང་གི་གཙོ་བོ་གཙོ་བོ་དེ་བདེ་བ་དང་སྡུག་བསྔལ་ཟེར་ཡག་དེ་རེད། བདེ་བ་དང་སྡུག་བསྔལ་ཟེར་ཡག་དེ་རྒྱུ་གང་ལ། བདེ་བ་དང་སྡུག་བསྔལ་ངོ་བོ་མི་འདྲ་བ་ག་འདྲས་ག་འདྲས་ཡོད་རེད།

04:54 ཨིའི་དེ་དང་དེའི་ཨིའི་བདེ་སྡུག་མི་འདྲ་བ་མང་པོ་ཡོད་པ་དེ་གས་དེ། ད་ངས་གཙོ་བོ་ད་གིན་ཞུ་ཡག་དེ། གཙོ་བོ་ལུས་ཚོར་ལ་བརྟེན་པའི་བདེ་སྡུག།

05:02གཙོ་བོ་སེམས་ཚོར་ལ་བརྟེན་པའི་བདེ་སྡུག ད་སེམས་ཚོར་ཟེར་དགོས་རེད་བས། ཡིད་བློ་ལ་བརྟེན་པའི་བདེ་སྡུག།དེ་གས་དེ་ཡི་འཕྲལ་གྱི་དངོས་རྒྱུ་ག་རེ་ག་རེ་བྱེད་ཀྱི་ཡོད་པ།

05:11 དངོས་ཀྱི་རྒྱུ་དང་རྐྱེན་ག་རེ་ག་རེ་བྱེད་ཀྱི་ཡོད་པ་བརྒྱུད་ནས་ཕུགས་ནས་རྒྱུ་དང་རྐྱེན་གང་གང་གིས་བྱེད་ཀྱི་ཡོད་པ་དེ་གས་དེ་ད་རྩད་གཅོད་བྱེད་ཡག་དེ་གལ་ཆེན་པོ་ཞེ་བོ་གཅིག་ཆགས་འདུག་བ།

05:19 སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས་སངས་རྒྱས་པའི་ཆོས་ཀྱི་ནང་ལོག་ལ་ཡ་ལས་ཀྱི་རྣམ་གཞག་དེ་མང་པོ་ཞེ་བོ་གཅིག་གསུང་གི་ཡོད་རེད་བ།

05:25ཨིའི་ད་ག་ནང་བཞིན་གཙོ་བོ་གཙོ་བོ་ཨེ་ནས་ཉོན་མོངས་པའི་གང་ལྟར་ཀུན་ཉོན་ཟེར་ཡག་དེ་གལ་ཆེ་ཤོས་ཤིག་ཆགས་ཡོད་དུས་ཙ་ནས།

05:33 ཉོན་མོངས་པ་གཏན་ལ་ཕབ་ཡག་དོན་དག་ལ་ཉོན་མོངས་པ་དང་དེའི་གཉེན་པོ་གཏན་ལ་ཕབ་ཡག་དོན་དག་ལ་ཨིའི་ཤེས་པའི་རྣམ་གཞག་དེ་མང་པོ་ཞེ་བོ་གཅིག་ཐོན་ཡོང་གི་འདུག་བ།

05:41རེད་བ། དེ་འདྲས་ཡིན་པ་ཡིིན་དུས་ཙ་ནས་ད་གང་ལྟར་གཞི་བདེན་པ་གཉིས་དེ་ལ་བརྟེན་པའི།

05:48 ཨེ་ནས་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི་བདེན་པ་བཞི། ད་ག་རེ་ཟེར་དགོས་རེད། ཕ་གིའི་ཀུན་ནས་ཉོན་མོངས་ཕྱོགས་དང༌། རྣམ་བྱང་ཕྱོགས་ཀྱི་

05:56 རྒྱུ་འབྲས་ཚན་པ་གཉིས་གཏན་ལ་ཕབ་ཡག་གི་བདེན་པ་བཞི་གསུང་བསྡད་ཡག ད་དེ་ཕར་ཏོག་ཙམ་ཞིབ་ཚགས་སུ་བཏང་ནས། རྟེན་འབྲེལ་ཡན་ལག་བཅུ་གཉིས་ལུགས་འབྱུང་ལུགས་ལྡོག་གི་སྒོ་ནས།

06:04ཨེ་ནས་བདེན་པ་བཞི་པོ་དེ་མར་འགྲེལ་བཤད་རྒྱག་ཡོང་ཡག། ད་དེའི་གཞི་རྩ་ཕར་ཕར་གཏུག་ཡོང་དུས་ཙ་ནས་ཆོས་རྣམས་རང་བཞིན་གྱིས་གྲུབ་པ་མེད་པར།

06:11རྟེན་འབྲེལ་ལྟོས་གྲུབ་ཙམ་ཟེར་ཡག་སྐད་ཆ་དེའི་སྒང་ནས་ཨེ་ནས་ཨིའི་ནང་པའི་གཞུང་དེ་བཤད་ཡོང་གི་ཡོད་རེད།

06:17སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཨིའི་ཀླུ་སྒྲུབ་ལ་སོགས་པ་དེ་གས་དེ་གིས་ད་བཀའ་འགྱུར་གྱི་འགྲེལ་པ་སྐྱོན་ཡོང་དུས་ཙ་ས་ནས།

06:25 ད་བསྟན་འགྱུར་ང་ཚོ་བོད་སྐད་ནང་ལ་བསྒྱུར་བཞག་པའི་ཉིས་བརྒྱ་ལྷག་ཙམ་གྱི་ཉིས་བརྒྱ་ཉི་ཤུ་རྩ་གྲངས་ད་ཡོད་བསྡད་པ་དེ་གས་དེ་ད་གང་ལྟར་དངོས་པོའི་གནས་ཚུལ་གཏན་ལ་ཕབ་ཡག།

06:34 མ་གཞི་ལམ་གྱི་རྣམ་གཞག་མང་པོ་བཤད་ཀིན་ཡོད་རེད། འབྲས་བུའི་རྣམ་གཞག་མང་པོ་གཅིག་བཤད་ཀྱི་ཡོད་རེད་དེ། ཡིན་ནས་འབྲས་བུའི་རྣམ་གཞག་དེ་དང་དེ་ལྟ་བུ་ཡོང་བ་ལ་མིང་ཁོ་རང་འབྲས་བུ་སེ་ལབ་པ་ཡིན་དུས།

06:42 རྒྱུ་གཅིག་ལ་བརྟེན་ནས་བྱུང་བསྡད་པ་གཅིག་ཡིན་པ་དེ་གསལ་པོ་ཞེ་དྲག་རེད་བ། བྱས་ཙང་ག དེའི་དངོས་ཀྱི་རྒྱུ་འདྲ་བོ་དེ་ལམ་དེ་ཡིས་བཤད་ཡོད་རེད།

06:50འོ་ད་ལམ་དེ་གས་དེ་ཡོང་ཡག་གི་གཞི་རྩའི་རྒྱུ་འདྲ་བོ་དེ་གཞིའི་རྣམ་གཞག་གིས་བཤད་ཡོང་གི་ཡོད་རེད་བ།

06:56 ཨིའི་གཞི་ལ་ཡ་ཁམས་བདེ་གཤེགས་སྙིང་པོ་ཟེར་ཡག་གཅིག་དང༌། གཞི་ལ་སེམས་འོད་གསལ་བ་གཅིག་སེམས་འོད་གསལ་བ་གཅིག་དང༌།

07:02 ཨིའི་རྟེན་འབྲེལ་རྟོག་བཏགས་ཙམ་གཅིག་གིས་གཞིའི་གནས་ཚུལ་ཞིག་མེད་ན། འགྱུར་བ་འགྲོ་ཤེས་ཀྱི་མ་རེད་བ།

07:07 འགྱུར་བ་འགྲོ་ཡག་མེད་ན་འགྱུར་བ་གཏོང་ཡག་གི་ལམ་ཡོང་མ་རེད་བ། འགྱུར་བ་གཏོང་ཡག་དང་འགྱུར་བ་བཏང་ནས་འགྱུར་བ་ཐེབས་པའི་གནས་སྐབས་ཀྱི་གནས་སྐབས་མི་འདྲ་བ་ཡོང་ཤེས་ཀྱི་མ་རེད་བ།

07:16 གཞི་དེ་འགྱུར་བ་འགྲོ་ཡག་མེད་ན། སེ་དེ་མེད་ན་འགྱུར་བ་མཐར་ཐུག་པའི་གནས་སྐབས་ཀྱི་འབྲས་བུའི་གནས་སྐབས་ཡོང་ཤེས་ཀྱི་མ་རེད་བ། སེ་དེ་འདྲས་ཡིན་དུས་མིང་ཁོ་རང་།

07:25 གཞི། ལམ། འབྲས་བུ་ཟེར་གྱིས་ནས་བཤད་བསྡད་ཡག་དེ་གིས་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང་བ་ཟེར་ཡག་དེའི་སྒང་ནས་འགྲེལ་བཤད་དེ་སླེབས་ཡོང་གི་འདུག་བ། རྒྱུ་འབྲས་རྒྱུ་འབྲས་རྟེན་འབྱུང་གི་འབྲེལ་བ་དེ་བཤད་ཡོང་གི་འདུག་བ།

07:34 རྒྱུ་འབྲས་རྟེན་འབྱུང་གི་འབྲེལ་བ་འཐད་ཡག་ཁོ་རང་ལྟོས་གྲུབ་ཀྱི་ད་རྟེན་འབྲེལ་དེའི་ཐོག་ནས་ཨེ་ནས་རྒྱུ་འབྲས་རྟེན་འབྱུང་གི་འབྲེལ་དེ་འཐད་པ་གཅིག་བཤད་ཐུབ་ཡག་འདུག་བ།

07:42སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས་ སངས་རྒ [...]

2023-04-29 02:38 UTC, Tenzindharten requested changes
00:00 ད་སྔོན་[་སྡོན་]ལ་དེ་[གཅིག་བཞུགས་]ཞུས་ན་མགོན་པོ་ཀླུ་སྒྲུབ་ཀི་དབུ་མ་རིགས་ཚོགས་དྲུག་ནང་ལོག་ལ་ཡ།

00:09 ཞིབ་མོ[འི་]རྣམ་འཐག་ཟེར་ཡག་གཅིག་འདུག་ག [བ།] ཞིབ་ཞིབ། ད་ག་རེ་ཟེར་བས་ད། དཔེ་ཞིབ་ཕྲ་བྱས་ནས་པར་འཐག་པ།

00:17རྟོག་གེའི་ཚིག་དོན་བཅུ་དྲུག་མུ་སྟེགས་པའི་གཞུང་གི་རྟོག་གེའི་ཚིག་དོན་བཅུ་དྲུག ཕར་ཞིབ་པར་བརླགས་པའམ་འཐག་པར་བྱེད་པ་ཞིབ་མོ་རྣམ་འཐག་ཟེར། 

00:26 [ཞིབ་མོ་རྣམ་འཐ] བྱས། ཀླུ་སྒྲུབ་ཀི་[སྐྲུབ་]དེ་བྱས། ཨེ[ནས་ནི་]བཞི་བརྒྱ་པའི་ཨརྱཱ་དེ་ཝས།



00:34མཛད་བཞག་པའི་བཞི་བརྒྱ་པའི་ནང་ལ་ཡ། ཨེ་ནས་[ནི་]ཨིའི་རྩ་བ་ཤེས་རབ་ཀི་[ཀྱི་]ཞལ་ཞེན་དགོངས་[སྐོང་]གི་ཚོད་དེ་ལ་ཡ།

00:42 ཨེ་ནས་[ནི་]ཨིའི་མི་རྟག་པ། སྡུག་བསྔལ་བ་དང༌།

00:50  ཨེ་ནས་[ནི་]བྱང་ཆུབ་སེམས་བསྐྱེད་ཀྱི་སྐོར་དེ་ཚོའི་[ཚོ་]གྲས་དེ་མར་གསུངས། དེ་ནས་[ནི་]མུ་སྟེགས་པའི་འདོད་པ་ཨིའི་དགའ་རབ་[འགའ་རོ་]བཀག་ཡོད་རེད། མུ་སྟེགས་པའི་འདོད་པ་ཁ་ཤས་ཤིག་[འགའ་ཞིག་]བཀག་ཡོད་རེད།

00:58 དེ་ནས་[ནི་]ལེགས་ལྡན་འབྱེད་ཀྱི་དབུ་མ་སྙིང་པོ། དབུ་མ་སྙིང་པོ་དང༌། དེའི་རང་འགྲེལ།

01:07 རྟོག་གེ་འབར་བའི་ནང་ལོག་ལ་ད་མུ་སྟེགས་པའི་འདོད་པ། ལུགས་མང་པོ་མར་བཀོད་འདུག་ག [ཞིག་]མུ་སྟེགས་པའི་ལུགས་ཞིབ་ཕྲ་མར་བཀོད་ནས་དེ་གས་དེ་མར་དགག་པ་བསྐྱོན་[སྐྱོན་]ཡོད ། རྟོག་གེ་སྡེ་ལྔ་[དེ་ནང་]ཕལ་ཆེར་ཡོད་རེད།

01:16 འདོད་པ་དེ་མར་བཀོད།[་ནས] དེ་དེས་ཨེ་ནས་དེ་གས་དེ་[འགོག་]དགག་གིན་དགག་གིན་བྱས་[ནས་]གསུངས་ནས་རྒྱས་པོ་[ཞིབ་འདྲ་]ཞེ་དྲག་འདུག།ཨེ་ནས་གཞན་ཡང་ད་པཎ་གྲུབ་བཅུ་བདུན་གི་[གྱི་]གཞུང་[གི་]ནང་ལོག་ལ་ཡ[ར]་མུ་སྟེགས་པའི་གཞུང་ཐོར་བུ་ཐོར་བུ[ར]་བྱས་ནས། [བཀག་དགག་བཞག་པ་མང་པོ་ཡོང་གི་ཡོད་རེད། ནས། བསྐྱར་ཟློས་རེད་བཞག ]

01:25དགག་བཞག་པ་མང་པོ་ཡོང་གི་ཡོད་རེད། [ནས།མཛད་པ་མང་པོ་ཞིག་ཡོང་གི་ཡོད།]ད་བོད་ལ་ཨེ་ནས་[ནི་]བོད་ཀྱི་མཁས་པ་ཚོས་རྒྱ་གཞུང་ནང་ལོག་ལ་ཡ་མུ་སྟེགས་པའི་[འདོད་པ་དང་།] 

01:34འདོད་པ་དང་འདོད་པ་འགོག་ཡ་[ཡས་]དེ་འདྲས་ཀི་ཐོར་བུ་ཐོར་བུ[ར་]གསུངས་བཞག་པ[འི་]དེ་གས་[ཚོ]་ཚུར་སྡོམ་བརྒྱབས་ནས་[རྒྱགˌཏེ་དེ་གས་དེ་ཚུར་སྡོམ་བརྒྱབས་ནས་ད་བོད་ལ་གྲུབ་མཐའ་ཟེར་ཡག་ཅིག་[ཞེས་པ་ཞིག་]མཛད་འདུག་ག

01:43 ངས་[མཇལ་]མཐོང་པའི་[བའི་གྲུབ་མཐའ་ནི་]ནང་ཆ་བཞག་ན། ཨིའི་ག་རེ་རེད་དགོ། དབུས་པ་བློ་གསལ། བོད་སྔ་རབས་[ཀྱི་]པའི་ཁོངས་རེད། དབུས་པ་བློ་གསལ་གྱི་གྲུབ་མཐའ[འི]་རྩ་བ་གཅིག་འདུག།

01:52 [བུས་]དབུས་པ་བློ་གསལ་གྱི་གྲུབ་མཐའ་གཅིག་འདུག། གྲུབ་མཐའ་རྩ་[བ་]འགྲེལ་གཅིག [འདུག།]རྩ་བ་གཅིག དེའི་རང་འགྲེལ་གཅིག  ངས་གཅིག་མཐོང་།

02:00  དེ་ནས་[ནི་]ཀུན་མཁྱེན་ཀློང་ཆེན་རབ་འབྱམས་པའི་གྲུབ་མཐའ་མཛོད། ཨིའི་དེ་ནས་[ནི་]ད་དགེ་ལུགས་པའི་ཁོངས་ནས་ཐམས་ཅད་མཁྱེན་པ་

02:09 དགེ་འདུན་རྒྱ་མཚོ་དང་། དེ་འདྲའི་གྲུབ་མཐའ་བསྡུས་པ་དེ་འདྲའི་[འདྲའང་]ཡོད་རེད། ད་རྒྱས་ཤོས་དེ་ཀུན་མཁྱེན་བླ་མ་འཇམ་དབྱངས་བཞད་པའི་[པས་མཛད་པའི་]

02:17 གྲུབ་མཐའ་[འི་]རྩ་བ། ད་གྲུབ་མཐའ་ཆེན་མོ། རྩ་བ་དང་། དེའི་རང་འགྲེལ། ཨེ་ནས་དེ་ནས་[ནི་]ལྕང་སྐྱ་རིན་པོ་ཆེ་ཡི་[ཡིས་]

02:25 ཨེ་ནས་གྲུབ་མཐའ། དེ་ཨེ་ནས་རྒྱས་བསྡུས་འཚམས་ཡག་པོ་ཞེ་བོ་[ཞིག་པོ་]གཅིག་འདུག།གྲུབ་མཐའ་[ཐུབ་བསྟན་]ལྷུན་པོའི་མཛེས་རྒྱན། དེ་ནས་[ནི་]ཨེ་ནས་ཨ་ད་[ལྡ་]འདིར་ལབ་བསྡད་ཡ་ད། 

02:35 ཀུན་མཁྱེན་བླ་མ་སྐུ་ཕྲེང་གཉིས་པ། ཨིའི་འཇིགས་མེད་དབང་པོས་མཛད་བཞག་པའི་ད་ཨ་འོ་གྲུབ་མཐའ་རིན་ཆེན་ཕྲེང་བ། [ད་དེ་བསྡུས་ཤོས་གཅིག་ཞིག་]རེད།]

02:44ད་དེ་བསྡུས་ཤོས་[ཤོག་ཞིག་]གཅིག་རེད། [མདོར་]བསྡུས་བསྡུས་གཅིག་[ཞིག་]ཡག་པོ་འདུག་བ།

02:52ད་མིན། དེ་ཡོད་རེད་ཨ་ད་[བ་]མཁན་ཆེན་ཞི་བ་འཚོ[ས་]བོད་ལ་ཕེབས་མཁན་གྱི་དཔལ་ནཱ་ལེདྲནའི་མཁས་པ་བོད་ལ་ཕེབས་མཁན། མཁན་ཆེན་ཞི་བ་འཚོའི་[ས་མཛད་པའི་]

03:00 ཚད་ཆེན་[ནམ་]ཨིའི་ཚད་མའི་དེ་[གཉིས་]ཁོ་ན་ཉིད་བསྡུས་པ་ཡིན་ན། ཚད་མེད་དེ་ཉིད་ཟེར་ན་རེེད། འོ་ད་མཁྲགས་[མཁྲེགས་]པོ་ཞེ་བོ་གཅིག་[ཞིག་]འདུག[པས]

03:08 རོབ་ཙམ་[ཞིག་]མཇལ་ཡིན། ད་དེ་ཤེས་ཡ[ས]་ལ་ཁག་པོ་ཞེ་བོ་གཅིག་རེད་བཞག།དེའི་འགྲེལ་པ་སློབ་དཔོན་ཀརྨ་ལ་ཤི[འ་]ལས་མཛད་བཞག་པའི་འགྲེལ་པ་པོད་གཉིས་འདུག་བ།

03:17 བྱས་[ཅང་]ཨ་ལྟ་[ད་ལྡ་]བར་དུ་སྨོན་ལམ་བརྒྱབ་རྒྱུ་[བརྒྱབས་ནས་]བཞག་རྒྱུ་རེད། ཨང་ལྟ་[ད་ལྡ་]ཀློག་ཡག་[རྒྱུ་]མ་བྱུང་། ཧེ་ཧེ་ཧེ། མང་མཐའ་ཆོད་ནས་[མཁྲེགས་]མཁྲགས་པོ་ཞིག་བོ་གཅིག་འདུག ཧེ་ཧེ་ཧེ་ཧེ། ཡ་ད་ག[ར་]བཞག་བཞག་མེད་འགྲོ།

03:28 



༢༠༢༣་༠༤་༢༩ ཉིན་ཞོགས་པ་བཅོས། ཆད་ལྷག་ཅན་མང་པོ་འདུག ཚང་མ་ཁ་གསབ་དང་བཅོས་ཡོད། གུག་རྟགས་དེ་ཚོ་གསུབ་དུས་གཟབ་གཟབ་བྱེད་མ་གཏོགས། གསུབ་ནོར་ཤོར་ཡོང་།

2023-04-29 03:51 UTC, choephel-tashi commented
00:00 ད་སྔོན་ལ་དེ་ཞུས་ན་མགོན་པོ་ཀླུ་སྒྲུབ་ཀི་དབུ་མ་རིགས་ཚོགས་དྲུག་ནང་ལོག་ལ་ཡ།

00:09 ཞིབ་མོ་རྣམ་འཐག་ཟེར་ཡག་གཅིག་འདུག་ག  ཞིབ་ཞིབ། ད་ག་རེ་ཟེར་བས་ད། དཔེ་ཞིབ་ཕྲ་བྱས་ནས་པར་འཐག་པ།

00:17རྟོག་གེའི་ཚིག་དོན་བཅུ་དྲུག་མུ་སྟེགས་པའི་གཞུང་གི་རྟོག་གེའི་ཚིག་དོན་བཅུ་དྲུག ཕར་ཞིབ་པར་བརླགས་པའམ་འཐག་པར་བྱེད་པ་ཞིབ་མོ་རྣམ་འཐག་ཟེར།

00:26  བྱས། ཀླུ་སྒྲུབ་ཀི་དེ་བྱས། ཨེ་ནས་བཞི་བརྒྱ་པའི་ཨརྱཱ་དེ་ཝས།

00:34མཛད་བཞག་པའི་བཞི་བརྒྱ་པའི་ནང་ལ་ཡ། ཨེ་ནས་ཨིའི་རྩ་བ་ཤེས་རབ་ཀི་ཞལ་ཞེན་དགོངས་གི་ཚོད་དེ་ལ་ཡ།

00:42 ཨེ་ནས་ཨིའི་མི་རྟག་པ། སྡུག་བསྔལ་བ་དང༌།

00:50 ཨེ་ནས་བྱང་ཆུབ་སེམས་བསྐྱེད་ཀྱི་སྐོར་དེ་ཚོའི་གྲས་དེ་མར་གསུངས། དེ་ནས་མུ་སྟེགས་པའི་འདོད་པ་ཨིའི་དགའ་རབ་བཀག་ཡོད་རེད། མུ་སྟེགས་པའི་འདོད་པ་ཁ་ཤས་ཤིག་བཀག་ཡོད་རེད།

00:58 དེ་ནས་ལེགས་ལྡན་འབྱེད་ཀྱི་དབུ་མ་སྙིང་པོ། དབུ་མ་སྙིང་པོ་དང༌། དེའི་རང་འགྲེལ།

01:07 རྟོག་གེ་འབར་བའི་ནང་ལོག་ལ་ད་མུ་སྟེགས་པའི་འདོད་པ། ལུགས་མང་པོ་མར་བཀོད་འདུག་ག་མུ་སྟེགས་པའི་ལུགས་ཞིབ་ཕྲ་མར་བཀོད་ནས་དེ་གས་དེ་མར་དགག་པ་བསྐྱོན་ཡོད ། རྟོག་གེ་སྡེ་ལྔ་ཕལ་ཆེར་ཡོད་རེད།

01:16 འདོད་པ་དེ་མར་བཀོད་དེ་དེས་ཨེ་ནས་དེ་གས་དེ་དགག་གིན་དགག་གིན་བྱས་གསུངས་ནས་རྒྱས་པོ་ཞེ་དྲག་འདུག།ཨེ་ནས་གཞན་ཡང་ད་པཎ་གྲུབ་བཅུ་བདུན་གི་གཞུང་ནང་ལོག་ལ་ཡ་མུ་སྟེགས་པའི་གཞུང་ཐོར་བུ་ཐོར་བུ་བྱས་ནས། 

01:25དགག་བཞག་པ་མང་པོ་ཡོང་གི་ཡོད་རེད།ད་བོད་ལ་ཨེ་ནས་བོད་ཀྱི་མཁས་པ་ཚོས་རྒྱ་གཞུང་ནང་ལོག་ལ་ཡ་མུ་སྟེགས་པའི

01:34འདོད་པ་དང་འདོད་པ་འགོག་ཡ་དེ་འདྲས་ཀི་ཐོར་བུ་ཐོར་བུ་གསུངས་བཞག་པ་དེ་གས་ཚུར་སྡོམ་བརྒྱབས་ནས་མཛད་འདུག་ག

01:43 ངས་མཐོང་པའི་ནང་ཆ་བཞག་ན། ཨིའི་ག་རེ་རེད་དགོ། དབུས་པ་བློ་གསལ། བོད་སྔ་རབས་པའི་ཁོངས་རེད། དབུས་པ་བློ་གསལ་གྱི་གྲུབ་མཐའ་རྩ་བ་གཅིག་འདུག།

01:52 དབུས་པ་བློ་གསལ་གྱི་གྲུབ་མཐའ་གཅིག་འདུག། གྲུབ་མཐའ་རྩ་འགྲེལ་གཅིག་རྩ་བ་གཅིག དེའི་རང་འགྲེལ་གཅིག ངས་གཅིག་མཐོང་།

02:00 དེ་ནས་ཀུན་མཁྱེན་ཀློང་ཆེན་རབ་འབྱམས་པའི་གྲུབ་མཐའ་མཛོད། ཨིའི་དེ་ནས་ད་དགེ་ལུགས་པའི་ཁོངས་ནས་ཐམས་ཅད་མཁྱེན་པ་

02:09 དགེ་འདུན་རྒྱ་མཚོ་དང་། དེ་འདྲའི་གྲུབ་མཐའ་བསྡུས་པ་དེ་འདྲའི་ཡོད་རེད། ད་རྒྱས་ཤོས་དེ་ཀུན་མཁྱེན་བླ་མ་འཇམ་དབྱངས་བཞད་པའི་

02:17 གྲུབ་མཐའ་རྩ་བ། ད་གྲུབ་མཐའ་ཆེན་མོ། རྩ་བ་དང་། དེའི་རང་འགྲེལ། ཨེ་ནས་དེ་ནས་ལྕང་སྐྱ་རིན་པོ་ཆེ་ཡི

02:25 ཨེ་ནས་གྲུབ་མཐའ། དེ་ཨེ་ནས་རྒྱས་བསྡུས་འཚམས་ཡག་པོ་ཞེ་བོ་གཅིག་འདུག།གྲུབ་མཐའ་ལྷུན་པོའི་མཛེས་རྒྱན། དེ་ནས་ཨེ་ནས་ཨ་ད་འདིར་ལབ་བསྡད་ཡ་ད།

02:35 ཀུན་མཁྱེན་བླ་མ་སྐུ་ཕྲེང་གཉིས་པ། ཨིའི་འཇིགས་མེད་དབང་པོས་མཛད་བཞག་པའི་ད་ཨ་འོ་གྲུབ་མཐའ་རིན་ཆེན་ཕྲེང་བ།རེད།

02:44ད་དེ་བསྡུས་ཤོས་གཅིག་རེད། བསྡུས་བསྡུས་གཅིག་ཡག་པོ་འདུག་བ།

02:52ད་མིན། དེ་ཡོད་རེད་ཨ་ད་མཁན་ཆེན་ཞི་བ་འཚོ་བོད་ལ་ཕེབས་མཁན་གྱི་དཔལ་ནཱ་ལེདྲནའི་མཁས་པ་བོད་ལ་ཕེབས་མཁན། མཁན་ཆེན་ཞི་བ་འཚོའི

03:00 ཚད་ཆེན་ཨིའི་ཚད་མའི་དེ་ཁོ་ན་ཉིད་བསྡུས་པ་ཡིན་ན། ཚད་མེད་དེ་ཉིད་ཟེར་ན་རེེད། འོ་ད་མཁྲགས་པོ་ཞེ་བོ་གཅིག

03:08 རོབ་ཙམ་མཇལ་ཡིན། ད་དེ་ཤེས་ཡ་ལ་ཁག་པོ་ཞེ་བོ་གཅིག་རེད་བཞག།དེའི་འགྲེལ་པ་སློབ་དཔོན་ཀརྨ་ལ་ཤི་ལས་མཛད་བཞག་པའི་འགྲེལ་པ་པོད་གཉིས་འདུག་བ།

03:17 བྱས་ཨ་ལྟ་བར་དུ་སྨོན་ལམ་བརྒྱབ་རྒྱུ་བཞག་རྒྱུ་རེད། ཨང་ལྟ་ཀློག་ཡག་མ་བྱུང་། ཧེ་ཧེ་ཧེ། མང་མཐའ་ཆོད་ནས་མཁྲགས་པོ་ཞིག་བོ་གཅིག་འདུག ཧེ་ཧེ་ཧེ་ཧེ། ཡ་ད་ག་བཞག་བཞག་མེད་འགྲོ།

03:28

2023-04-29 04:19 UTC, Tenzindharten requested changes
00:00 ད་སྔན་ལ་ཨིའི་དེ་ཞུས་ན། མགོན་པོ་ཀླུ་སྒྲུབ་ཀི་དབུ་མ་རིགས་ཚོགས་དྲུག་ནང་ལོག་ལ་ཡ།

00:09 ཞིབ་མོ་རྣམ་འཐག་ཟེར་ཡག་གཅིག་འདུག་ག ཞིབ་མོ་རྣམ་འཐག  ཞིབ་ཞིབ། ད་ག་རེ་ཟེར་བས་ད། དཔེ་ཞིབ་ཕྲ་བྱས་ནས་ཕར་འཐག་པ་ཟེར་ད།

00:17རྟོག་གེའི་ཚིག་དོན་བཅུ་དྲུག་མུ་སྟེགས་པའི་གཞུང་གི་རྟོག་གེའི་ཚིག་དོན་བཅུ་དྲུག ཕར་ཞིབ་པར། ཕར་བརླགས་པའམ་འཐག་པར་བྱེད་པ་ཞིབ་མོ་རྣམ་འཐག་ཟེར།

00:26 བྱས། ཀླུ་སྒྲུབ་ཀི་དེ་བྱས། ཨེ་ནས་བཞི་བརྒྱ་པའི་ཨརྱཱ་དེ་ཝས།

00:34 མཛད་བཞག་པའི་བཞི་བརྒྱ་པའི་ནང་ལ་ཡ། ཨེ་ནས་ཨིའི་རྩ་བ་ཤེས་རབ་ཀི་བཞེས་དགོངས་ཀི་ཚོད་འདྲ་བོ་དེ་ལ་ཡ།

00:42 ཨེ་ནས་ཨིའི་མི་རྟག་པ། སྡུག་བསྔལ་བ་དང༌།

00:50 ཨེ་ནས་ག་རེ་ཞུ་རྒྱུ་དགོས་རེད། ཕ་གིའི་བྱང་ཆུབ་སེམས་སྐྱེད་ཀྱི་སྐོར་དེ་ཚོའི་གྲས་དེ་མར་གསུངས། དེ་ནས་མུ་སྟེགས་པའི་འདོད་པ་ཨིའི་དགའ་རབ་བཀག་ཡོད་རེད། མུ་སྟེགས་པའི་འདོད་པ་ཁ་ཤས་ཤིག་བཀག་ཡོད་རེད།

00:58 དེ་ནས་ལེགས་ལྡན་འབྱེད་ཀྱི་ལེགས་ལྡན་འབྱེད་ཀྱི་དབུ་མ་སྙིང་པོ། དབུ་མ་སྙིང་པོ་དང༌། དེའི་རང་འགྲེལ།

01:07 རྟོག་གེ་འབར་བའི་ནང་ལོག་ལ་ད་མུ་སྟེགས་པའི་འདོད་པ། ལུགས་མང་པོ་མར་བཀོད་འདུག་ག མུ་སྟེགས་པའི་ལུགས་ཞིབ་ཕྲ་མར་བཀོད་ནས་དེ་གས་དེ་མར་དགག་པ་བསྐྱོན་ཡོད་རེད། རྟོག་གེ་སྡེ་ལྔ་ཕལ་ཆེར་ཡོད་རེད། དེ་ཡིན་ཙང་། ཚང་མ་ལོག་གི་

01:16 འདོད་པ་དེ་མར་བཀོད། ཨེ་ནས་དེ་གས་དེ་མར་དགག་གིན་དགག་གིན་བྱས་གསུངས་ནས་རྒྱས་པོ་ཞེ་དྲག་འདུག ཨེ་ནས་གཞན་ཡང་ད་པཎ་གྲུབ་བཅུ་བདུན་གི་གཞུང་ནང་ལོག་ལ་ཡ་མུ་སྟེགས་པའི་གཞུང་ཐོར་བུ་ཐོར་བུ་བྱས་ནས།

01:25དགག་བཞག་པ་མང་པོ་ཡོང་གི་ཡོད་རེད། ད་བོད་ལ་ཨེ་ནས་བོད་ཀྱི་མཁས་པ་ཚོས་རྒྱ་གཞུང་ནང་ལོག་ལ་ཡ་མུ་སྟེགས་པའི 

01:34འདོད་པ་དང་འདོད་པ་འགོག་ཡ་དེ་འདྲས་ཀི་ཐོར་བུ་ཐོར་བུ་གསུངས་བཞག་པ་དེ་གས་དེ་ཚུར་སྡོམ་བརྒྱབས་ནས།་དེ་གས་དེ་ཚུར་སྡོམ་བརྒྱབས་ནས་བོད་ལ་གྲུབ་མཐའ་ཟེར་ཡག་ཅིག་མཛད་འདུག་ག

01:43 ངས་མཐོང་པའི་ནང་ཆ་བཞག་ན། ཨིའི་ག་རེ་རེད་དགོ། དབུས་པ་བློ་གསལ། བོད་སྔ་རབས་པའི་ཁོངས་རེད། 

01:52 དབུས་པ་བློ་གསལ་གྱི་གྲུབ་མཐའ་གཅིག་འདུག། གྲུབ་མཐའ་རྩ་འགྲེལ་གཅིག རྩ་བ་གཅིག དེའི་རང་འགྲེལ་གཅིག ངས་གཅིག་མཐོང་།

02:00 ད་དེ་ནས་ཨེ་ནས་ཀུན་མཁྱེན་ཀློང་ཆེན་རབ་འབྱམས་པའི་གྲུབ་མཐའ་མཛོད། ཨིའི་དེ་ནས་ད་དགེ་ལུགས་པའི་ཁོངས་ནས། ཨེ་ནས་ཐམས་ཅད་མཁྱེན་པ་

02:09 དགེ་འདུན་རྒྱ་མཚོ་དང་། དེ་འདྲའི་གྲུབ་མཐའ་བསྡུས་པ་དེ་འདྲའི་ཡོད་རེད། ད་རྒྱས་ཤོས་དེ་ཀུན་མཁྱེན་བླ་མ་འཇམ་དབྱངས་བཞད་པའི་

02:17 གྲུབ་མཐའ་རྩ་འགྲེལ། གྲུབ་མཐའ་རྩ་བ། ད་གྲུབ་མཐའ་ཆེན་མོ། རྩ་བ་དང་། དེའི་རང་འགྲེལ། ཨེ་ནས་དེ་ནས་ལྕང་སྐྱ་རིན་པོ་ཆེ་ཡི

02:25 ཨེ་ནས་གྲུབ་མཐའ། དེ་ཨེ་ནས་རྒྱས་བསྡུས་འཚམས་ཡག་པོ་ཞེ་བོ་གཅིག་འདུག གྲུབ་མཐའ་ལྷུན་པོའི་མཛེས་རྒྱན། དེ་ནས་ཨེ་ནས་ཨ་ལྟ་་འདིར་ལབ་བསྡད་ཡ་ད།

02:35 ཀུན་མཁྱེན་བླ་མ་སྐུ་ཕྲེང་གཉིས་པ། ཨིའི་འཇིགས་མེད་དབང་པོས་མཛད་བཞག་པའི་ད་ཨ་འོ་གྲུབ་མཐའ་རིན་ཆེན་ཕྲེང་བ་རེད།

02:44ད་དེ་བསྡུས་ཤོས་གཅིག་རེད། བསྡུས་བསྡུས་གཅིག་ཡག་པོ་འདུག་བ། ད་དེ་ནས་མར་ཨེ་ནས་ཞུ་ཡ་ཡིན་ད། 

02:52ད་མིན། དེ་ཡོད་རེད་ཨ་ད་མཁན་ཆེན་ཞི་བ་འཚོ་བོད་ལ་ཕེབས་མཁན་གྱི་དཔལ་ནཱ་ལེདྲནའི་མཁས་པ་བོད་ལ་ཕེབས་མཁན། མཁན་ཆེན་ཞི་བ་འཚོའི

03:00 ཚད་ཆེན་ཨིའི་ཚད་མའི་དེ་ཁོ་ན་ཉིད་བསྡུས་པ་ཡིན་ན། ཚད་མེད་དེ་ཉིད་ཟེར་ན་རེེད། འོ་ད་མཁྲགས་པོ་ཞེ་བོ་གཅིག་འདུག 

03:08 རོབ་ཙམ་མཇལ་ཡིན། ད་དེ་ཤེས་ཡ་ལ་ཁག་པོ་ཞེ་བོ་གཅིག་རེད་བཞག དེའི་འགྲེལ་པ་སློབ་དཔོན་ཀརྨ་ལ་ཤི་ལས་མཛད་བཞག་པའི་འགྲེལ་པ་པོད་གཉིས་འདུག་བ།

03:17 བྱས་ཨ་ལྟ་བར་དུ་སྨོན་ལམ་བརྒྱབ་རྒྱུ་བཞག་བཞག་རྒྱུ་རེད། ཨ་ལྟ་ཀློག་ཡག་མ་བྱུང་། ཧེ་ཧེ་ཧེ། མང་མཐའ་ཆོད་ནས་མཁྲགས་པོ་ཞེ་བོ་གཅིག་འདུག ཧེ་ཧེ་ཧེ་ཧེ། ཡ་ད་ག་བཞག་བཞག་རྒྱུ་མིན་འགྲོ།

03:28

༢༠༢༣་༠༤་༢༩ བསྐྱར་དུ་བལྟས་ཟིན། ད་འགྲིག་འདུག

2023-04-29 15:28 UTC, Tenzindharten requested changes
00:00[ ད་ག་རེ་ཟེར་དགོས་]ད་ཁ་རྩང་ཨ་ལྟ་ཨེ་ཆད་པར་སྨྲ་བ་ཨེ་ནས་[ནི་]རྒྱང་འཕེན་པའི་ཨེ་སྔར་གྱི།

00:08རྒྱང་འཕེན་པའི་འདོད་ཚུལ་གཅིག །ཨེ་ནས་[ནི་]སྐྱེ་བ་སྔ་མ་ཡོད་པའི་ད་སྒྲུབ་བྱེད་[ཀྱི་]རྩ་བ་འདྲ་བོ་ད།

00:17 ཤེས་པའི་རྒྱུན་གི་[གྱི་]སྒང་ནས་བསམ་མནོ་གཏང་གིན་[བློ་གཏོང་གི་]ཡོད་རེད། སེ་ད་ཤེས་པ་དེ་ལུས་ལ་བརྟེན་ནས་བྱུང་བ་རེད་ཟེར་དུས་[ཙམ]་ཙ་ནས།

00:24 ཨེ་ནས་[ནི་]ལུས་དེ་འགག[ས་]པ་དང་ཤེས་པ་དེ་འགག[ས་]འགྲོ་ཡ[ས་]གཅིག།སྔར་གྱི་ད་ལོ་སྟོང་ཕྲག་གོང་གི་[རྒྱ་གར་བའི་]རྒྱང་འཕེན་པས་རྒྱ་གར་ལ་དེ་བཤད་ཀིན་ཡོད་རེད། [ལྟར་ཤོད་ཀྱི་ཡོད་རེད།]

00:32 ཨེ་[དེང་]ད་རིང་ཁ་སང་ད་འཛམ་བུ་གླིང་འདིའི་[སྟེང]་སྒང[་ནས་]་ལས་ད་ཨེ། ད་ཤུགས་ཀྱིས་ད་ཤེས་པ་ཟེར་ཡ[ས་]དེ།

00:40  དེ་ཀླད་པ་ཁོ་ན་ལས་སྐྱེས་པ་ཡིན་ན། ཨེ་ནས་[ནི་]ཀླད་པ། [ས་འགགས་པའི་སྐབས་དུས་]ཀླད་པ་ཀླད་པའི་བྱ་བ་འགག[ས་འགྲོ་དུས། ཀླད་པ་འགག་དུས་ཀླད་པའི་བྱ་བ་འགག་འགྲོ་གི་རེད། 

00:48ཨ་[ད་]དེ་འདྲས་གཅིག་རེད་བ་[འོ་]ད། ཨ་དེ་བཤད་བསྡད་ཀིན་[གི་]ཡོད་རེད། ཨ་ཁ་སང་ལབ་པ་ན་བཞིན་རེད། ཨེ་ཚན་རིག་པ་དེ་ཨེ་ཁོང་ཚོ་བློའི་[ཆོས་དག་]རྣམ་དཔྱོད་དང༌། གཅིག་

00:58  བློའི་གནས་སྟངས་འདྲ་བོ་དེ་བློ་དངོས་གནས་དྲང་གནས་གཟུ་བོར་གནས་པ་ཞེ་དྲག་རེད་བཞག།ཡང་ཚན་རིག་པ་འགའ་ཤས། ད་མ་གཞི་[མར་ཞིག་]ཞོར་འཕྲོས་འདྲ་བོ་གཅིག་རེད།

01:07ལོ་གཅིག་ཕལ་ཆར་ཕྱི་ལོ་ ༡༩༧༣ ལོ་ལ་ཡིན་པ་ཡོད།༡༩༧༩ལ་ཡིན་པ་ཡོད།

01:15  ཨུ་རུ་སུ་ལ་ཡ་ཕ་གིའི་[ཕར་གར་]སླེབས་དུས། ངས་ཚན་རིག་པ་ཁ་ཤས་གཅིག་ཐུག་པ་རེད། ཚན་རིག་པ་དེ་འདྲའི་མཉམ་གོ་བསྡུར་བྱེད་ཡག་འདྲ་བོ་གཅིག  བྱས་ཨེ་ནས་[ནི]་ཤེས་པའི་སྐོར་ལ་སྐད་ཆ་བྱུང་བ་རེད།

01:24 ཨེ་ནས་སྒོ་ལྔའི་ཤེས་པ་དང༌། དེ་ནས་[ནི་]ངས་ཡིད་བློ། ཡིད་ཀྱི་བློ། ཡིད་བློ་ཟེར་འདུག་སེ་[ཞེས་]ལབ་པ་ད་ག[དང་། ]ཨེ་ནས་[ནི་]ཚན་རིག་པ་དེ་ཡིས།

01:33 ཡིད་བློ[་ཞེས་]ཟེར་དུས་[དང་]Soul ཟེར་ཡག་[བ]་གོ་བ་འདྲ་བསྡད་འདུག་བ། [ཝ།] དབྱིན་ཇིའི་[ཇའི་]སྐད་ནང་ལ་ད་ཡེ་ཤུའི་ཆོས་པས་Soul་ཟེར་ཡག་ཡས་ཟེར་གིན་ཡོད་རེད་བ། [་ཝ།]

01:43  [དེར་]དེ་གོ་བ་འདྲ་[འགྲོ་]འདུག་བ། [ཝ།] ཡིད་བློ་ཟེར་ལབ་པ་ད་ག་རང་། [བ་དང་] ཨེ་དེ་ཆོས་པའི་སྐད་ཆ་རེད་ཟེར། ཆོས་པའི་སྐད་ཆ་རེད་ཟེར། བྱས་ཙང་ད་དེ།

01:52 ཚན་རིག་པ་དེ་ཚོའི་བཟོ་འདྲ་བའི་གྲས་དེ་ཡང་གནས་ཚུལ་ཁ་ཁ་[ཐ་དད་]རེད། དང་པོ་ནས་ཨེ་ཆོས་ཡོད་མ་རེད་[མེད་]ཟེར་ཡག་[ཡས་]གཅིག ད་ག་[ན]ནང་བཞིན་རྒྱ་མིའི་ཚན་རིག་པ་རིགས་གཅིག་དེས། [གིས་]

02:00 ཆོས་ཡོད་མ་རེད་ཟེར་ནས་སྔོན་ལ་ཐག་བཅད། གུང་ཁྲན་རིང་ལུགས་ཡང་དག་པ་རེད་ཟེར་ནས་སྔོན་ལ་ཐག་བཅད། ཨེ་ནས་[ནི་]གཞི་ནས་ཚན་རིག་ནས་རྒྱབ་བསྐྱོར་བཙལ་བསྡད་ཡག་[ཚོལ་ཡས་]དེ་བློ་གཟུ་བོར་གནས་པ་ཆགས་ཀི་ཡོད་མ་རེད།

02:10 དེ་བཞིན་དུ་ང་རང་ཚོ་ནང་པ་གཅིག་གིས།྄ ཨེ་ནས་[ནི་]ད་ཨེ་ཡང་དག་པ་དང་ཡང་མ་དག་པ་ཟེར་[ཞེས་]ནང་པའི་གཞུང་ནས་བཤད་པ་དེ། 

༢༠༢༣་༠༤་༢༩ མཚན་མོར་བཅོས། འདིའི་ཕྱེད་ཀ་སང་ཉིན་བསྐུར་ཡོང་།

2023-04-30 04:28 UTC, Tenzindharten requested changes
02:19 སྔོན་ལ་[ཕར]ཕ་གིའི་[ཁར་]འབེན་འདྲ་བོ་དེའི་བཙུགས་བྱས། དེ་བཙུགས་ཚར་བའི་རྗེས་ལ་ཨེ་ནས་[ནི་]རིགས་པ་བཀོད་ནས་དེ་ཡང་དག་ཡིན་པར་[བསྒྲུབ་]བསྒྲུབས་ན་བློ་ཕྱོགས་སུ་

02:28 ལྷུང་བ་ཆགས་ཚར་བ་རེད། སེ་[སོ་]དེ་[འདྲ་]འདྲས་ཡིན་དུས། གཟུར་གནས་བློ་ལྡན་དོན་གཉེར་བ།ཟེར་བྱས་ནས་ [འི་ཞེས་]བཤད་བསྡད་བ་དེ།

02:37 རྒྱ་ཆ་བརྒྱ་ཐམ་པ་བློ་གཟུ་བོར་གནས་པ་གཅིག་དགོས་ཀི་ཡོད་རེད། འདི་བླང་བྱ་རེད། འདི་དོར་བྱ་རེད། འདི་ཡང་དག་པ་རེད། འདི་ཡང་མ་དག་པ་རེད་ཟེར་བྱས་ནས་[ཅེས]་སྔོན་ལ་ཐག་བཅད།

02:45  དེ་ནས་སྒྲུབ་བྱེད་བཀོད་ན་བློ་ཕྱོགས་སུ་ལྷུང་བ་ཆགས་སོང་བ། [ཨ།]ཁོ[ང་]དང་པོ་ནས་དམིགས་ཡུལ་གཅིག་གཏན་[བརྟན་]འཁེལ་ཚར་བ་རེད།[ འདི་]དེ་འདྲའི་གཅིག་[ཞིག་སྒྲུབ་]བསྒྲུབ་ཀི་[ཀྱི་]ཡིན། 

02:53 [འདི་]དེ་འདྲའི་གཅིག་དགོས་ཀིན་ཡོད་ཟེར་[་ཞིག་དགོས་ཞེས་]ལབ་ནས། ཨེ་ནས་དེ་བསྒྲུབ་ཡག་གི་སྒྲུབ་བྱེད་[སྒྲུབ་ཡས་]ཨེ་ནས་རྒྱུ་མཚན་གྱི་སྒང་ལ་བཙལ་ཁ[ར་]ཕྱིན་པ་ཡིན་པ་ན། དེ་ཕལ་ཆེར་མ་འགྲིག[ས་]པ་རེད། [སོ་]སེ་[ད་འདྲ་]དེ་འདྲས་ཡིན་དུས།


03:02 བློ་གཟུ་བོར་གནས་པ[ར]་བྱེད་ཀྱིས་གང་ཡང་ཡིན་ཆོག་གི་རེད་ཟེར་བྱས་[ཅེས་]ནས། [དེ་]ད་ག་རང་[གའི་]སྒང་ལ་བཞག[་སྟེ།] ཨེ་ནས་[ནི་]དེ་ནས་བཙལ།

03:10དེ་ནས་ཁོ་ག་རེ་ཟེར་བ་རེད། བདེན་དོན་དེ་གཅིག་ཤེས་སོང་ན། དངོས་ཡོད་གནས་ཚུལ་དེ་ཤེས་སོང་ན། ད་དངོས་ཡོད་གནས་ཚུལ། ད་དངོས་ཡོད་གནས་ཚུལ་དེ། ཨེ་ནས[་ཕན་དང]

03:19ཕན་དང་གནོད་པ་ག་རེ་ཆགས་འདུག་བ། དེ་ཡང་བློ་གཞན་ཞིག[་གིས་]བལྟ་རྒྱུ་མ་གཏོགས། [ཕར་ག་]ཕ་གིའི་བདེན་དོན་ག་རེ་ཡིན་པ་མཚོན་མཁན་བློ་དེ་གས། [པས་བློ་དེ་གར་]

03:27  འགོ་[འཛུགས་]བཙུགས་པའི་ཁ་ཐུག་[སྐབས་]དུས་ནས། ཨེ་ཡིན་དང་མིན། ལེགས་དང་ཉེས་ཀྱི་ཐིག་ཕལ་ཆེར་རྒྱག་ཡག་[ཡས་]ཡོད་ས་མ་རེད། དེ་[བརྒྱབ་]བརྒྱབས་ན། 

03:37 བློ་གཟུ་བོར་གནས་པ་ཆགས་ཀི་[གི་]ཡོད་མ་རེད། གཟུར་གནས་ཟེར་ཡ་དེ་ཆགས་ཀི་ཡོད་མ་རེད། གཟུར་གནས། ད་དེ་འདྲས་[འདྲ་]ཡིན་དུས། ང་རང་ཚོ[འི་]དཔེ་ཆའི་ནང་ལ་ཡིན་ནས།

03:45 དེ་གལ་ཆེན་པོ[ར་]ཞེ་བོར་གསུང་གི་འདུག་བ། གཟུར་གནས་བློ་ལྡན་དོན་གཉེར་བ་ཟེར། ཨེ་རྗེ་རིན་ཆེན་པོ་ཡིས་གང་དག་ཕྱོགས་འཛིན་མུན་པས་མ་བསྒྲིབས་ཤིང༌། །


03:54 ལེགས་ཉེས་འབྱེད་པའི་བློ་ཡི་མཐུ་ལྡན་པ། །ཟེར་[ཞེས་]བྱས་ནས་གསུངས་པ་ནང་[ན་]བཞིན་རེད། ཕྱོགས་འཛིན་གྱིས་[གྱི་]མུན་པས་མ་བསྒྲིབས་པ་ཟེར་དུས་ཙ་ནས། [སྒྲིབ་པ་སོང་ཙམ་ནས།] ཁོ་བློ་ཕྱོགས་སུ་ལྷུང་།

04:02  འདི་ཡིན་དགོས་ཀི་[ཀྱི་]རེད། འདི་མིན་ན་ཨ། བསམ་པ་འདྲ་བོ་[ར་]གཅིག་གི་བསམ་བློ་བཏང་ན། འགྲིག་གི་མི་འདུག་བ། [མི་འགྲིགས་ཨ།] བྱས་ཙང་། ང་ཚོ་[འདི་ཆན་]འདི་ཚན་རིག་པ་མཉམ་དུ་ཚོགས་འདུ་ད།

04:10 འཚོགས་བསྡད་ཡག་[ཡས་]མང་པོ་ཡོང་གིན་ཡོད་རེད། ཚོགས་[འཚོངས་]དུས་ཙ[མ་]ནས། ནང་པའི་ལྟ་བ་འདི་རེད་ཟེར་[ཅེས་]ངས་རྩ་བ་ཉིད་ནས་བཤད་ཀིན་[ཤོད་ཀྱི་]མེད། ནང་པས།

04:19 ནང་པ་ཡང་དག་པ[ར་]ཡིན་པ[ར་]འདྲ་བོ་གཅིག་ཆེད་མངགས་སྒྲུབ་ཀིན་བསྡད་ན་[ཀྱིན་བསྡང་]ན་ནོར་འཁྲུལ་རེད་འདུག་བ། [ཨ།] ནང་པའི་བཤད་སྟངས་འདི་འདྲའི་རེད་ཟེར། [ཅེས་]ཚུར་སྐད་ཆ་དྲིས་པ་ཡིན་ན། ནང་པའི་བཤད་སྟངས་[ཞེས་]འདི་འདྲའི་གཅིག་ཡོད་རེད་བྱས།

04:28 ཨེ་སྐྱེ་བ་སྔ་ཕྱི་ཕར་[སྐོར་ལ་སླེབས་]འགྲོ་དུས་ཙ[མ་]ཙ་ནས། དེ་ནང་པའི་[ནི་]ནང་པ་དང་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ཚོའི་[ཆོ་ཡི་]བྱུས་ཏོག་རེད་མ་གཏོགས། ཁྱེད་རང་ཚོའི་[ཆོ་ཡི་]ཇུས་ཏོག་མ་རེད་ཟེར་[ཅེས་]ལབ་བསྡད་ཀི་[ཀྱི་]ཡོད། བྱས་ཙང་།

04:38 ཁོ་གནད་འགག་འདུག་ག བྱས་ཙང་། ཨང་ལྟ་[ད་]དེ་རྒྱ་མིའི་ཡང་གཅིག་ཚན་རིག་པ་[འགའ]་དེ་འདྲའི་ཁོ་[ཁོས་]དང་པོ་ནས། གུང་ཁྲན་རིང་ལུགས་ཟེར་དེ་ཡང་དག་པ་ཡིན་པ་གཅིག་[ཏུ་]སྒྲུབ་སྙིང་འདོད་བྱས། [ཁོས་]ཁོ་བཤད་བསྡད་དུས།

2023 /04/30 ཕྱེད་ཀ་ཞིག་ཚར་སོང་། ལྷག་མ་རྗེས་སུ་བསྐུར་ཡོང་།།

2023-04-30 05:23 UTC, choephel-tashi commented
00:00ད་ཁ་རྩང་ཨ་ལྟ་ཨེ་ཆད་པར་སྨྲ་བ་ཨེ་ནས་རྒྱང་འཕེན་པའི་ཨེ་སྔར་གྱི།

00:08རྒྱང་འཕེན་པའི་འདོད་ཚུལ་གཅིག །ཨེ་ནས་སྐྱེ་བ་སྔ་མ་ཡོད་པའི་ད་སྒྲུབ་བྱེད་རྩ་བ་འདྲ་བོ་ད།

00:17 ཤེས་པའི་རྒྱུན་གི་སྒང་ནས་བསམ་མནོ་གཏང་གིན་ཡོད་རེད། སེ་ད་ཤེས་པ་དེ་ལུས་ལ་བརྟེན་ནས་བྱུང་བ་རེད་ཟེར་དུས་ཙ་ནས།

00:24 ཨེ་ནས་ལུས་དེ་འགག་པ་དང་ཤེས་པ་དེ་འགག་འགྲོ་ཡ་གཅིག།སྔར་གྱི་ད་ལོ་སྟོང་ཕྲག་གོང་གི་རྒྱང་འཕེན་པས་རྒྱ་གར་ལ་དེ་བཤད་ཀིན་ཡོད་རེད

00:32 ཨེ་ད་རིང་ཁ་སང་ད་འཛམ་བུ་གླིང་འདིའི་སྒང་ལས་ད་ཨེ། ད་ཤུགས་ཀྱིས་ད་ཤེས་པ་ཟེར་ཡ་དེ།

00:40 དེ་ཀླད་པ་ཁོ་ན་ལས་སྐྱེས་པ་ཡིན་ན། ཨེ་ནས་ཀླད་པ། ཀླད་པ་ཀླད་པའི་བྱ་བ་འགག་འགྲོ་དུས། ཀླད་པ་འགག་དུས་ཀླད་པའི་བྱ་བ་འགག་འགྲོ་གི་རེད།

00:48ཨ་དེ་འདྲས་གཅིག་རེད་བ་ད། ཨ་དེ་བཤད་བསྡད་ཀིན་ཡོད་རེད། ཨ་ཁ་སང་ལབ་པ་ན་བཞིན་རེད། ཨེ་ཚན་རིག་པ་དེ་ཨེ་ཁོང་ཚོ་བློའི་རྣམ་དཔྱོད་དང༌། གཅིག་

00:58 བློའི་གནས་སྟངས་འདྲ་བོ་དེ་བློ་དངོས་གནས་དྲང་གནས་གཟུ་བོར་གནས་པ་ཞེ་དྲག་རེད་བཞག།ཡང་ཚན་རིག་པ་འགའ་ཤས། ད་མ་གཞི་ཞོར་འཕྲོས་འདྲ་བོ་གཅིག་རེད།

01:07ལོ་གཅིག་ཕལ་ཆར་ཕྱི་ལོ་ ༡༩༧༣ ལོ་ལ་ཡིན་པ་ཡོད།༡༩༧༩ལ་ཡིན་པ་ཡོད།

01:15 ཨུ་རུ་སུ་ལ་ཡ་ཕ་གིའི་སླེབས་དུས། ངས་ཚན་རིག་པ་ཁ་ཤས་གཅིག་ཐུག་པ་རེད། ཚན་རིག་པ་དེ་འདྲའི་མཉམ་གོ་བསྡུར་བྱེད་ཡག་འདྲ་བོ་གཅིག བྱས་ཨེ་ནས་ཤེས་པའི་སྐོར་ལ་སྐད་ཆ་བྱུང་བ་རེད།

01:24 ཨེ་ནས་སྒོ་ལྔའི་ཤེས་པ་དང༌། དེ་ནས་ངས་ཡིད་བློ། ཡིད་ཀྱི་བློ། ཡིད་བློ་ཟེར་འདུག་སེ་ལབ་པ་ད་ག་ཨེ་ནས་ཚན་རིག་པ་དེ་ཡིས།

01:33 ཡིད་བློ་ཟེར་དུས་Soul ཟེར་ཡག་་གོ་བ་འདྲ་བསྡད་འདུག་བ། དབྱིན་ཇིའི་སྐད་ནང་ལ་ད་ཡེ་ཤུའི་ཆོས་པས་Soul་ཟེར་ཡག་ཡས་ཟེར་གིན་ཡོད་རེད་བ། 

01:43 དེ་གོ་བ་འདྲ་འདུག་བ། ཡིད་བློ་ཟེར་ལབ་པ་ད་ག་རང་།  ཨེ་དེ་ཆོས་པའི་སྐད་ཆ་རེད་ཟེར། ཆོས་པའི་སྐད་ཆ་རེད་ཟེར། བྱས་ཙང་ད་དེ།

01:52 ཚན་རིག་པ་དེ་ཚོའི་བཟོ་འདྲ་བའི་གྲས་དེ་ཡང་གནས་ཚུལ་ཁ་ཁ་རེད། དང་པོ་ནས་ཨེ་ཆོས་ཡོད་མ་རེད་ཟེར་ཡག་གཅིག ད་ག་ནང་བཞིན་རྒྱ་མིའི་ཚན་རིག་པ་རིགས་གཅིག་དེས། 

02:00 ཆོས་ཡོད་མ་རེད་ཟེར་ནས་སྔོན་ལ་ཐག་བཅད། གུང་ཁྲན་རིང་ལུགས་ཡང་དག་པ་རེད་ཟེར་ནས་སྔོན་ལ་ཐག་བཅད། ཨེ་ནས་གཞི་ནས་ཚན་རིག་ནས་རྒྱབ་བསྐྱོར་བཙལ་བསྡད་ཡག་དེ་བློ་གཟུ་བོར་གནས་པ་ཆགས་ཀི་ཡོད་མ་རེད།

02:10 དེ་བཞིན་དུ་ང་རང་ཚོ་ནང་པ་གཅིག་གིས།྄ ཨེ་ནས་ད་ཨེ་ཡང་དག་པ་དང་ཡང་མ་དག་པ་ཟེར་ནང་པའི་གཞུང་ནས་བཤད་པ་དེ།
02:19 སྔོན་ལ་ཕ་གིའི་འབེན་འདྲ་བོ་དེའི་བཙུགས་བྱས། དེ་བཙུགས་ཚར་བའི་རྗེས་ལ་ཨེ་ནས་རིགས་པ་བཀོད་ནས་དེ་ཡང་དག་ཡིན་པར་བསྒྲུབས་ན་བློ་ཕྱོགས་སུ་

02:28 ལྷུང་བ་ཆགས་ཚར་བ་རེད། སེ་དེ་འདྲས་ཡིན་དུས། གཟུར་གནས་བློ་ལྡན་དོན་གཉེར་བ།ཟེར་བྱས་ནས་བཤད་བསྡད་བ་དེ།

02:37 རྒྱ་ཆ་བརྒྱ་ཐམ་པ་བློ་གཟུ་བོར་གནས་པ་གཅིག་དགོས་ཀི་ཡོད་རེད། འདི་བླང་བྱ་རེད། འདི་དོར་བྱ་རེད། འདི་ཡང་དག་པ་རེད། འདི་ཡང་མ་དག་པ་རེད་ཟེར་བྱས་ནས་་སྔོན་ལ་ཐག་བཅད།

02:45 དེ་ནས་སྒྲུབ་བྱེད་བཀོད་ན་བློ་ཕྱོགས་སུ་ལྷུང་བ་ཆགས་སོང་བ། ཁོ་དང་པོ་ནས་དམིགས་ཡུལ་གཅིག་གཏན་འཁེལ་ཚར་བ་རེད། དེ་འདྲའི་གཅིག་བསྒྲུབ་ཀི་ཡིན།

02:53 དེ་འདྲའི་གཅིག་དགོས་ཀིན་ཡོད་ཟེར་ལབ་ནས། ཨེ་ནས་དེ་བསྒྲུབ་ཡག་གི་སྒྲུབ་བྱེད་ཨེ་ནས་རྒྱུ་མཚན་གྱི་སྒང་ལ་བཙལ་ཁ་ཕྱིན་པ་ཡིན་པ་ན། དེ་ཕལ་ཆེར་མ་འགྲིག་པ་རེད། སེ་དེ་འདྲས་ཡིན་དུས།

03:02 བློ་གཟུ་བོར་གནས་པ་བྱེད་ཀྱིས་གང་ཡང་ཡིན་ཆོག་གི་རེད་ཟེར་བྱས་ནས། ད་ག་རང་སྒང་ལ་བཞག་ཨེ་ནས་དེ་ནས་བཙལ།

03:10དེ་ནས་ཁོ་ག་རེ་ཟེར་བ་རེད། བདེན་དོན་དེ་གཅིག་ཤེས་སོང་ན། དངོས་ཡོད་གནས་ཚུལ་དེ་ཤེས་སོང་ན། ད་དངོས་ཡོད་གནས་ཚུལ། ད་དངོས་ཡོད་གནས་ཚུལ་དེ། ཨེ་ནས

03:19ཕན་དང་གནོད་པ་ག་རེ་ཆགས་འདུག་བ། དེ་ཡང་བློ་གཞན་ཞིག་བལྟ་རྒྱུ་མ་གཏོགས། ཕ་གིའི་བདེན་དོན་ག་རེ་ཡིན་པ་མཚོན་མཁན་བློ་དེ་གས། 

03:27 འགོ་བཙུགས་པའི་ཁ་ཐུག་དུས་ནས། ཨེ་ཡིན་དང་མིན། ལེགས་དང་ཉེས་ཀྱི་ཐིག་ཕལ་ཆེར་རྒྱག་ཡག་ཡོད་ས་མ་རེད། དེ་བརྒྱབས་ན།

03:37 བློ་གཟུ་བོར་གནས་པ་ཆགས་ཀི་ཡོད་མ་རེད། གཟུར་གནས་ཟེར་ཡ་དེ་ཆགས་ཀི་ཡོད་མ་རེད། གཟུར་གནས། ད་དེ་འདྲས་ཡིན་དུས། ང་རང་ཚོ་དཔེ་ཆའི་ནང་ལ་ཡིན་ནས།

03:45 དེ་གལ་ཆེན་པོ་ཞེ་བོར་གསུང་གི་འདུག་བ། གཟུར་གནས་བློ་ལྡན་དོན་གཉེར་བ་ཟེར། ཨེ་རྗེ་རིན་ཆེན་པོ་ཡིས་གང་དག་ཕྱོགས་འཛིན་མུན་པས་མ་བསྒྲིབས་ཤིང༌། །

03:54 ལེགས་ཉེས་འབྱེད་པའི་བློ་ཡི་མཐུ་ལྡན་པ། །ཟེར་བྱས་ནས་གསུངས་པ་ནང་བཞིན་རེད། ཕྱོགས་འཛིན་གྱིས་མུན་པས་མ་བསྒྲིབས་པ་ཟེར་དུས་ཙ་ནས། ཁོ་བློ་ཕྱོགས་སུ་ལྷུང་།

04:02 འདི་ཡིན་དགོས་ཀི་རེད། འདི་མིན་ན་ཨ། བསམ་པ་འདྲ་བོ་གཅིག་གི་བསམ་བློ་བཏང་ན། འགྲིག་གི་མི་འདུག་བ།  བྱས་ཙང་། ང་ཚོ་འདི་ཚན་རིག་པ་མཉམ་དུ་ཚོགས་འདུ་ད།

04:10 འཚོགས་བསྡད་ཡག་མང་པོ་ཡོང་གིན་ཡོད་རེད། ཚོགས་དུས་ཙ་ནས། ནང་པའི་ལྟ་བ་འདི་རེད་ཟེར་ངས་རྩ་བ་ཉིད་ནས་བཤད་ཀིན་མེད། ནང་པས།

04:19 ནང་པ་ཡང་དག་པ་ཡིན་པ་འདྲ་བོ་གཅིག་ཆེད་མངགས་སྒྲུབ་ཀིན་བསྡད་ན་ནོར་འཁྲུལ་རེད་འདུག་བ།  ནང་པའི་བཤད་སྟངས་འདི་འདྲའི་རེད་ཟེར། ཚུར་སྐད་ཆ་དྲིས་པ་ཡིན་ན། ནང་པའི་བཤད་སྟངས་འདི་འདྲའི་གཅིག་ཡོད་རེད་བྱས།

04:28 ཨེ་སྐྱེ་བ་སྔ་ཕྱི་ཕར་འགྲོ་དུས་ཙ་ནས། དེ་ནང་པའི་ནང་པ་དང་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ཚོའི་བྱུས་ཏོག་རེད་མ་གཏོགས། ཁྱེད་རང་ཚོའི་ཇུས་ཏོག་མ་རེད་ཟེར་ལབ་བསྡད་ཀི་ཡོད། བྱས་ཙང་།

04:38 ཁོ་གནད་འགག་འདུག་ག བྱས་ཙང་། ཨང་ལྟ་དེ་རྒྱ་མིའི་ཡང་གཅིག་ཚན་རིག་པ་དེ་འདྲའི་ཁོ་དང་པོ་ནས། གུང་ཁྲན་རིང་ལུགས་ཟེར་དེ་ཡང་དག་པ་ཡིན་པ་གཅིག་སྒྲུབ་སྙིང་འདོད་བྱས། ཁོ་བཤད་བསྡད་དུས།
Done at 10:53 at 30th April.

2023-05-01 08:21 UTC, Tenzindharten requested changes
00:00 ད་ཁ་རྩང་ཨང་ལྟ་ད་ཨེ་ཆད་པར་སྨྲ་བ་ཨེ་ནས་རྒྱང་འཕེན་པའི་ཨེ་སྔར་གྱི།

00:0 རྒྱང་འཕེན་པའི་འདོད་ཚུལ་གཅིག ཨེ་ནས་སྐྱེ་བ་སྔ་མ་ཡོད་པའི་ད་སྒྲུབ་བྱེད་རྩ་བ་འདྲ་བོ་དེ་ད།

00:17 ཤེས་པའི་རྒྱུན་གི་སྒང་ནས་བསམ་མནོ་གཏང་གིན་ཡོད་རེད། སེ་ད་ཤེས་པ་དེ་ལུས་ལ་བརྟེན་ནས་བྱུང་པ་རེད་ཟེར་དུས་ཙ་ནས།

00:24 ཨེ་ནས་ལུས་དེ་འགག་པ་དང་ཤེས་པ་དེ་འགག་འགྲོ་ཡ་གཅིག།སྔར་གྱི་ད་ལོ་སྟོང་ཕྲག་གོང་གི་རྒྱང་འཕེན་པས་རྒྱ་གར་ལ་དེ་བཤད་ཀིན་ཡོད་རེད།

00:32 ཨེ་ད་རིང་ཁ་སང་ད་འཛམ་བུ་གླིང་འདིའི་སྒང་ལས་ད་ཨེ། ད་ཤུགས་ཀྱིས་ད་ཤེས་པ་ཟེར་ཡ་དེ།

00:40 དེ་ཀླད་པ་ཁོ་ན་ལས་སྐྱེས་པ་ཡིན་ན། ཨེ་ནས་ཀླད་པ། ཀླད་པ་ཀླད་པའི་བྱ་བ་འགག་འགྲོ་དུས། ཀླད་པ་འགག་དུས་ཀླད་པའི་བྱ་བ་འགག་འགྲོ་གི་རེད།

00:48ཨ་དེ་འདྲས་གཅིག་རེད་བ་ད། ཨ་དེ་བཤད་བསྡད་ཀིན་ཡོད་རེད། ཨ་ཁ་སང་ལབ་པ་ན་བཞིན་རེད། ཨེ་ཚན་རིག་པ་དེ་ཨེ་ཁོང་ཚོ་བློའི་རྣམ་དཔྱོད་དང༌། གཅིག་

00:58 བློའི་གནས་སྟངས་འདྲ་བོ་དེ་བློ་དངོས་གནས་དྲང་གནས་གཟུ་བོར་གནས་པ་ཞེ་དྲག་རེད་བཞག།ཡང་ཚན་རིག་པ་འགའ་ཤས། ད་མ་གཞི་ཞོར་འཕྲོས་འདྲ་བོ་གཅིག་རེད།

01:07ལོ་གཅིག་ཕལ་ཆར་ཕྱི་ལོ་ ༡༩༧༣ ལོ་ལ་ཡིན་པ་ཡོད། ༡༩༧༩ལ་ཡིན་པ་ཡོད།

01:15 ཨུ་རུ་སུ་ལ་ཡ་ཕ་གིའི་སླེབས་དུས། ངས་ཚན་རིག་པ་ཁ་ཤས་གཅིག་ཐུག་པ་རེད། ཚན་རིག་པ་དེ་འདྲའི་མཉམ་གོ་བསྡུར་བྱེད་ཡག་འདྲ་བོ་གཅིག བྱས་ཨེ་ནས་ཤེས་པའི་སྐོར་ལ་སྐད་ཆ་བྱུང་བ་རེད།

01:24 ཨེ་ནས་སྒོ་ལྔའི་ཤེས་པ་དང༌། དེ་ནས་ངས་ཡིད་བློ། ཡིད་ཀྱི་བློ། ཡིད་བློ་ཟེར་འདུག་སེ་ལབ་པ་ད་ག་ཨེ་ནས་ཚན་རིག་པ་དེ་ཡིས།

01:33 ཡིད་བློ་ཟེར་དུས་Soul ཟེར་ཡག་་གོ་བ་འདྲ་བསྡད་འདུག་བ། དབྱིན་ཇིའི་སྐད་ནང་ལ་ད་ཡེ་ཤུའི་ཆོས་པས་Soul་ཟེར་ཡག་ཅིག་ཟེར་གིན་ཡོད་རེད་བ།

01:43 དེ་གོ་བ་འདྲ་འདུག་བ། ཡིད་བློ་ཟེར་ལབ་པ་ད་ག་རང་། ཨེ་དེ་ཆོས་པའི་སྐད་ཆ་རེད་ཟེར། ཆོས་པའི་སྐད་ཆ་རེད་ཟེར། བྱས་ཙང་ད་དེ།

01:52 ཚན་རིག་པ་དེ་ཚོའི་བཟོ་འདྲ་བོའི་གྲས་དེ་ཡང་གནས་ཚུལ་ཁ་ཁ་རེད། དང་པོ་ནས་ཨེ་ཆོས་ཡོད་མ་རེད་ཟེར་ཡག་གཅིག ད་ག་ནང་བཞིན་རྒྱ་མིའི་ཚན་རིག་པ་རིགས་གཅིག་དེས།

02:00 ཆོས་ཡོད་མ་རེད་ཟེར་ནས་སྔོན་ལ་ཐག་བཅད། གུང་ཁྲན་རིང་ལུགས་ཡང་དག་པ་རེད་ཟེར་ནས་སྔོན་ལ་ཐག་བཅད། ཨེ་ནས་གཞི་ནས་ཚན་རིག་ནས་རྒྱབ་བསྐྱོར་བཙལ་བསྡད་ཡག་དེ་བློ་གཟུ་བོར་གནས་པ་ཆགས་ཀི་ཡོད་མ་རེད།

02:10 དེ་བཞིན་དུ་ང་རང་ཚོ་ནང་པ་གཅིག་གིས། ཨེ་ནས་ད་ཨེ་ཡང་དག་པ་དང་ཡང་མ་དག་པ་ཟེར་ནང་པའི་གཞུང་ནས་བཤད་པ་དེ།
02:19 སྔོན་ལ་ཕ་གིའི་འབེན་འདྲ་བོ་དེ་བཙུགས་བྱས། དེ་བཙུགས་ཚར་བའི་རྗེས་ལ་ཨེ་ནས་རིགས་པ་བཀོད་ནས་དེ་ཡང་དག་ཡིན་པར་བསྒྲུབས་ན་བློ་ཕྱོགས་སུ་

02:28 ལྷུང་བ་ཆགས་ཚར་བ་རེད། སེ་དེ་འདྲས་ཡིན་དུས། གཟུར་གནས་བློ་ལྡན་དོན་གཉེར་བ།ཟེར་བྱས་ནས་བཤད་བསྡད་བ་དེ།

02:37 རྒྱ་ཆ་བརྒྱ་ཐམ་པ་བློ་གཟུ་བོར་གནས་པ་གཅིག་དགོས་ཀི་ཡོད་རེད། འདི་བླང་བྱ་རེད། འདི་དོར་བྱ་རེད། འདི་ཡང་དག་པ་རེད། འདི་ཡང་མ་དག་པ་རེད་ཟེར་བྱས་ནས་་སྔོན་ལ་ཐག་བཅད།

02:45 དེ་ནས་སྒྲུབ་བྱེད་བཀོད་ན་བློ་ཕྱོགས་སུ་ལྷུང་བ་ཆགས་སོང་བ། ཁོ་དང་པོ་ནས་དམིགས་ཡུལ་གཅིག་གཏན་འཁེལ་ཚར་བ་རེད། དེ་འདྲའི་གཅིག་བསྒྲུབ་ཀི་ཡིན།

02:53 དེ་འདྲའི་གཅིག་དགོས་ཀིན་ཡོད་ཟེར་ལབ་ནས། ཨེ་ནས་དེ་བསྒྲུབ་ཡག་གི་སྒྲུབ་བྱེད་ཨེ་ནས་རྒྱུ་མཚན་གྱི་སྒང་ལ་བཙལ་ཁ་ཕྱིན་པ་ཡིན་པ་ན། དེ་ཕལ་ཆེར་མ་འགྲིག་པ་རེད། སེ་དེ་འདྲས་ཡིན་དུས།

03:02 བློ་གཟུ་བོར་གནས་པ་བྱེད་ཀྱིས་གང་ཡང་ཡིན་ཆོག་གི་རེད་ཟེར་བྱས་ནས། ད་ག་རང་སྒང་ལ་བཞག་ཨེ་ནས་དེ་ནས་བཙལ།

03:10དེ་ནས་ཁོ་ག་རེ་ཟེར་བ་རེད། བདེན་དོན་དེ་གཅིག་ཤེས་སོང་ན། དངོས་ཡོད་གནས་ཚུལ་དེ་ཤེས་སོང་ན། ད་དངོས་ཡོད་གནས་ཚུལ། ད་དངོས་ཡོད་གནས་ཚུལ་དེ། ཨེ་ནས།

03:19ཕན་དང་གནོད་པ་ག་རེ་ཆགས་འདུག་བ། དེ་ཡང་བློ་གཞན་ཞིག་བལྟ་རྒྱུ་མ་གཏོགས། ཕ་གིའི་བདེན་དོན་ག་རེ་ཡིན་པ་མཚོན་མཁན་བློ་དེ་གས།

03:27 འགོ་བཙུགས་པའི་ཁ་ཐུག་དུས་ནས། ཨེ་ཡིན་དང་མིན། ལེགས་དང་ཉེས་ཀྱི་ཐིག་ཕལ་ཆེར་རྒྱག་ཡག་ཡོད་ས་མ་རེད། དེ་བརྒྱབས་ན།

03:37 བློ་གཟུ་བོར་གནས་པ་ཆགས་ཀི་ཡོད་མ་རེད། གཟུར་གནས་ཟེར་ཡ་དེ་ཆགས་ཀི་ཡོད་མ་རེད། གཟུར་གནས། ད་དེ་འདྲས་ཡིན་དུས། ང་རང་ཚོ་དཔེ་ཆའི་ནང་ལ་ཡིན་ནས།

03:45 དེ་གལ་ཆེན་པོ་ཞེ་བོར་གསུང་གི་འདུག་བ། གཟུར་གནས་བློ་ལྡན་དོན་གཉེར་བ་ཟེར། ཨེ་རྗེ་རིན་ཆེན་པོ་ཡིས་གང་དག་ཕྱོགས་འཛིན་མུན་པས་མ་བསྒྲིབས་ཤིང༌། །

03:54 ལེགས་ཉེས་འབྱེད་པའི་བློ་ཡི་མཐུ་ལྡན་པ། །ཟེར་བྱས་ནས་གསུངས་པ་ནང་བཞིན་རེད། ཕྱོགས་འཛིན་གྱིས་མུན་པས་མ་བསྒྲིབས་པ་ཟེར་དུས་ཙ་ནས། ཁོ་བློ་ཕྱོགས་སུ་ལྷུང་།

04:02 འདི་ཡིན་དགོས་ཀི་རེད། འདི་མིན་ན་ཨ། བསམ་པ་འདྲ་བོ་གཅིག་གི་བསམ་བློ་བཏང་ན། འགྲིག་གི་མི་འདུག་བ། བྱས་ཙང་། ང་ཚོ་འདི་ཚན་རིག་པ་མཉམ་དུ་ཚོགས་འདུ་ད།

04:10 འཚོགས་བསྡད་ཡག་མང་པོ་ཡོང་གིན་ཡོད་རེད། ཚོགས་དུས་ཙ་ནས། ནང་པའི་ལྟ་བ་འདི་རེད་ཟེར་ངས་རྩ་བ་ཉིད་ནས་བཤད་ཀིན་མེད། ནང་པས།

04:19 ནང་པ་ཡང་དག་པ་ཡིན་པ་འདྲ་བོ་གཅིག་ཆེད་མངགས་སྒྲུབ་ཀིན་བསྡད་ན་ནོར་འཁྲུལ་རེད་འདུག་བ། ནང་པའི་བཤད་སྟངས་འདི་འདྲའི་རེད་ཟེར། ཚུར་སྐད་ཆ་དྲིས་པ་ཡིན་ན། ནང་པའི་བཤད་སྟངས་འདི་འདྲའི་གཅིག་ཡོད་རེད་བྱས།

04:28 ཨེ་སྐྱེ་བ་སྔ་ཕྱི་ཕར་འགྲོ་དུས་ཙ་ནས། དེ་ནང་པའི་ནང་པ་དང་སྐྱེ་བ་སྔ་ཕྱི་འདོད་མཁན་ཚོའི་བྱུས་ཏོག་རེད་མ་གཏོགས། ཁྱེད་རང་ཚོའི་ཇུས་ཏོག་མ་རེད་ཟེར་ལབ་བསྡད་ཀི་ཡོད། བྱས་ཙང་།

04:38 ཁོ་གནད་འགག་འདུག་ག བྱས་ཙང་། ཨང་ལྟ་དེ་རྒྱ་མིའི་ཡང་གཅིག་ཚན་རིག་པ་དེ་འདྲའི་ཁོ་དང་པོ་ནས། གུང་ཁྲན་རིང་ལུགས་ཟེར་དེ་ཡང་དག་པ་ཡིན་པ་གཅིག་སྒྲུབ་སྙིང་འདོད་བྱས། ཁོ་བཤད་བསྡད་དུས།








Done at 10:53 at 30th April.







༢༠༢༣།༠༥།༡ འགྲིག་འདུག ད་བཅོས་དགོས་མི་འདུག

2023-05-02 09:00 UTC, Tenzindharten requested changes
04:48 ཚན་རིག་པ་རང་ཆགས་ཀི་[ཀྱིས་]ཡོད་མ་རེད། བློ་གཟུ་བོར་གནས་པ་དེ་ཆགས་ཡོད་མ་རེད། ཡང་དེ་མི་ལ་ཡང་བཤད་པ་གཅིག་པོ་མིན་ད།[ དང་]ང་རང་ཚོའི་ངོས་ནས་[ལ་]ཆ་བཞག་ནས་ང་ཚོའི་འདི་ཡང་དག་པ་ཡིན་ཟེར་བྱས་ནས་[ཞེས་]སྔོན་ལ།

04:58ཐག་བཅད་ནས། ཨེ་ནས་[ནི་]ཚན་རིག་ནས་གཅིག་རིག[ས་]པ་གཅིག་[ཞིག་]ཨེ་རན་མི་རན་གཅིག་བལྟས་པ་[བ་]ཡིན་ནས་[ན་]ནོར་འཁྲུལ་རེད། ཚན་རིག་ཙམ་དུ་ཟད་པའི་སྤྱིར་བཏང་ད་རིག[ས་]པའི་སྒྲུབ་བྱེད་གཅིག་བཀོད་ནས། 

05:07 གཅིག་གཅིག་[གིས་]ད་མཐུན་ཕྱོགས་ལ་མཐོང་ཙམ་དང༌། མི་མཐུན་ཕྱོགས་ལ་མ་མཐོང་ཙམ་གྱིས་རྒྱུ་མཚན་འདྲ་བོ་གཅིག་[ཞིག་]བཀོད་བྱས་ནས་གཅིག་ཨེ་ཡོང་མི་ཡོང་ཞིག་བལྟས་པ་ཡིན་ན། ད་དེ།

05:16 ཁོ[ས་]བློ་གཟུ་བོར་གནས་པའི་ཐོག་ནས་དཔྱད་པ་བྱེད་སྟངས་དེ་ཆགས་ཀྱི་ཡོད་མ་རེད། དཔྱད་པ་[ང་དཔག་]བྱེད་སྟངས་[སྟགས་]དེ་ཆགས་ཀྱི་མི་འདུག་ཨ། ད་འཕྲོས་བཤད་འདྲ་བོ་གཅིག་རེད། འཕྲོས་བཤད།

05:26 ཞོར་ལ་ཡ[ར་]ད་འཕྲོས་བཤད་བཟོ་འདྲ་[བཟོ]་གཅིག། ཨེ་ཚན་རིག་པ་དང་འབྲེལ་བ་བྱེད་[ཡས་ཀྱི་]ཡག་གི་རྒྱུ་མཚན་ག་རེ་[རེད]་ཟེར་[ཞེས་]ལབ་པ་ཡིན་ན།

05:35 ད་ང་ཨང་ལྟ་[ད་ལྟ་]ཚན་རིག་པ་ལ་ཡ་[དང་]འབྲེལ་བ་བྱས་ནས་ལོ་ཧ་ལམ་ད། ཨེ་[བཅུ]་བཅོ་ལྔ། ད་ཉི་ཤུ་མ་ཟིན་ཙམ་འགྲོ་བསྡད་ཀིན་[ཀྱི]་ཡོད་རེད།

05:43  བྱས་ཙང་ཁ།  ད་མགོ་སྟོད་ཐོག་མར་དེ་ཚན་རིག་པ་ལ་ཡ[ར་ངས]་འབྲེལ་བ་བྱེད་ཡག་གཅིག་ཨེ་[བྱ་ཡས་་]བསམ་བློ་བཏང་པའི་ཁ་ཐུག་ལ་ཡ། །བསམ་བློ་འཁོར་བའི་[པའི་]ཁ[ར་]ཐུག་ལ།

05:53  ངའི་ངོ་ཤེས་པ་གཅིག་ཡོད། ཨེ་ཨ་རིའི་མི་གཅིག།མོ་རང་ད་རང་ནང་པ་ཡིན་པར་རེད། 

06:02 ཁོ[ང་]རང་ནང་པ་ཡིན་པ་རེད། བྱས་ནས་[ན་]ངས་ཚན་རིག་པ་དང་འབྲེལ་བྱེད་ཡག་དེ་[ཡས་]ཉེན་ཁ་ལྗིད་པོ་[ཆེན་པོ་]རེད་ཟེར། 

06:11 ཚན་རིག་ཟེར་བསྡད་དེ་ཨེ་དབྱིན་ཇིའི་ཚིག་ནང་ལོག་ལ་ཡ་Killer of religious ཆོས་གསོད་མཁན་དེ་རེད་ཟེར། ཚན་རིག་ཟེར་ཡག་དེ། 

06:20 ཚན་རིག་པ་དང་འབྲེལ་བ་བྱེད་ཡག་དེ་[ཡས་]ཉེན་ཁ་རེད་ཟེར་ཨ། ངས་བསམ་བློ་ཞིག་བཏང་པས། ཨེ་ནས། [བས་ན།] ཚན་རིག་གིས་ག་རེ་བྱེད་ཀི་ཡོད་རེད།

06:29 བདེན་པ་བཙལ་གིན་[གྱི་]ཡོད་རེད་ད། འོ་ད་འཚོལ་སའི་ཡུན་[ལ་]རང་ད། ཁོང་རང་ཚད་ཅན་གཅིག་རེད། གཙོ་བོ་

06:38  གཟུགས་ཅན། དེའི་ནང་ནས་མངོན་གྱུར་བ། མཐོང་བ་མངོན་གྱུར་བ། དེའི་ནང་ནས་[ཀྱང་]གཙོ་བོ་གཟུགས་ཅན་གྱི་ཆོས།

06:46 ཚད་[རྒྱག་]བརྒྱབ་[ཚར]་ས་བསྡད་ཡོད་པ། ཨེ་གཅིག་ཕ་གིའི་རྩིས་རྒྱག་ཡག་[ཡས་]ཡོད་བསྡད་པ། [ད་འདྲ་]དེ་འདྲའི་གཅིག་[གི་]ནང་ལོག་ལ། 

06:54 ཨང་ལྟ་science་ད་[ནང་དུ་]འགྲོ་བསྡད་ཡོད་རེད། དེ field ཁོ་རང་ limited་རེད། [སོ་]སེ་དེ་འདྲས་[འདྲ་]ཡིན་དུས།

07:04 [སོ་]སེ་འོ་ད་[ལྟ་]ནང་པའི་གཞུང་ནས་དཔེར་ན་བཤད་པ་ཡིན་ན། ཨེ་ནང་པའི་གཞུང་ནང་ལོག་ལ་ཡ།  འོ་ད་མ་གཞི་གཞུག་གུ་གཞུག་གུར་[དེའི་ཞོར་ན་]ཐོན་ཡོང་གི་རེད། གཞུག་གུར་ལབ་ཀི་ཡིན། [གཞོར་ལ།]

07:13 རེད་དེ་ཡིན་ནས་[ན་]གང་ལྟར་ཁོ[ང་]རང་གཅིག་བཙལ་བྱའི་གཞི་འདྲ་བོ་ཁོ[ང་]ཚད་ངེས་ཅན་གཅིག་རེད་དེ།

07:22 ཡིན་ནས་[ན་]གཞི་དེའི་ནང་ལོག་ལ་བདེན་པ་འཚོལ་གྱི་ཡོད་རེད་ད། [དང།] སེ་[སོ་]དེ་འདྲས་[འདྲ་]ཡིན་དུས་ཙ[ང་]ནས། སངས་རྒྱས་པའི་ཆོས་ཀྱིས་བདེན་པ་འཚོལ་ཡག་ཅིག་[ཡས་]བཤད་ཀྱི་ཡོད་རེད།

07:30 དཔེར་འདྲ་བོ་ཆ་བཞག་ན་རེད་ད། དཔེར་འདྲ་བོ་ཆ་བཞག་ན། ཨེ་བདེན་པ་འཚོལ་[ཡས་]ཡག་གཅིག་བཤད་ཀྱི་ཡོད་པ་[ཀྱི་ཙང་]ཡིན་དུས་ཙ་ནས་བདེན་པ་འཚོལ་སྟངས་དེ་ལ་ཡ་[དེར་ཡས་]རིགས་པའི་སྒོ་འདྲ་བོ་དེ་བཞི་གསུང་གི་འདུག་ཨ། 

07:40ཆོས་ཉིད་ཀྱི་རིགས་པ་ཟེར་[ཞེས་]གཅིག་བཤད། རེད་བ། དེ་ནས་[ནི་]བྱ་བ་བྱེད་[བྱས་]པའི་རིགས་པ་ཟེར།[ཞེས།] དེ་ནས་[ནི་]ལྟོས་པའི་རིགས་པ། [ཐད་པའི་[ས་སྒྲུབ་པའི་རིགས་པ་]

07:50བཅས་ནི། [ད་གར་]ད་དེ་གས་དེ་ག་རེ་རེད་ཟེར་[ཅེས་]ལབ་ན། སྔོན་ལ་གཞི་ལ་གཅིག་གང་ལྟར་རང་བཞིན་ལྷན་སྐྱེས་ཀྱི།[ས།]དཔེར་ན་གཅིག་ང་རང་ཚོ་ལ་ཡ། 

07:59ཨེ་ང་ཟེར་ཡག་[ཡས་]གཅིག་ཡོད་བསྡད་མཁན།  དེ་ངའོ་སྙམ་པའི་བློ་གཅིག་ཡོད་བསྡད་པ། ཨེ་དེ་ལ་ཡ[ར་དེབ་]བདེ་སྡུག་གི་ཚོར་བ་གཅིག་ཡོད་བསྡད་པ།

08:09  དེ་དང་འབྲེལ་ནས་བདེ་སྡུག་གི་ཚོར་བ་གཅིག་ཡོད་བསྡད་པ། དེ་ཆོས་ཉིད་རེད། དེ་ལས་ཀྱིས་བྱུང་བ་ཡང་མ་རེད། ཨེ་ག་གས་[གེ་]མ་རེད། ཁོ[ང་]རང་ད་ཆོས་ཉིད་རེད།

08:17 ད་ག[ར་ན]ནང་བཞིན་གི་[ན་]ཕྱི་ལ་གཟུགས་ཅན་ཟེར་ཡག་[ཡས]་གཅིག་ཡོད་བསྡད་པ། ཨེ་ཕྱི་དང་ནང་གི་ཆོས་གང་དང་གང་ཡིན་ནས། འབྲས་བུ་རྒྱུ་ལ་རག་ལས་པ།

08:25 ཆོས་ཉིད་རེད། ཨེ་ནས་ད་ག[ར་ན་]ནང་བཞིན་ཁོ[ང་རང་། ཨེ་ཆོས་རང་རང་གི་ཁོ[ང་]རང་བྱེད་[བྱ་]ལས་འདྲ་བོ། དཔེར་ན་[གི་བྱེད་ལས་] མེ་ཚ་བ།

08:34 ཆུ་[བ]རླན་པ་ཟེར་ཡག་[ཡས་]དེ་ཚོའི་གྲས་དེ། [ནི་]ཁོ[ང་]རང་ཆོས་ཉིད་ལ་བརྩི་ཡི་ཡོད། ཆོས་ཉིད་ཀྱི་རིགས་པ་ཟེར་[ཞེས་]གཅིག་བྱས། ད་དེ་ཁོ[ང་]རང་བཞིན་ལྷན་སྐྱེས་ཀྱི[ས་]ཁོ[ང་]རང་དངོས་པོ་དངོས་པོ་སོ་སོའི་

08:43གནས་སྟངས་གང་[ཞིག]་ཡིན་པ་དེ་གཅིག་ཤེས་དགོས་ཀི་ཡོད་རེད། ད་དེ་ནས་[ནི་]ཨེ་ནས་[ནི་]ཨེ་ག་རེ་ཟེར་[གང་ཟེ་]དགོས་རེད་ཕ་གིའི། [ཕར་གར།]

08:52 ཨེ་བྱ་བ་བྱེད་[བྱས་]པའི་རིགས་པ་ཟེར་ལབ་ན། དངོས་པོ་སོ་སོ་སོའི་བྱེད་ལས་ག་རེ་ག་རེ་ཡོད་[ཡོང་]མེད།

09:01 ཕལ་ཆེར་ང་ཚོ[ས]།དཔེར་ན chemistry དེ་ཚོའི་འདིའི་ནང་སླེབས་ཀི་[ཀྱི་]མེད་འགྲོ་[ན་]བསམ་གྱིན། ཁོ[ས་]རྫས་རྫས་སོ་སོ་སོའི་ནུས་པ་ག་རེ་ཡོད་པ། 

09:09 རྫས་ཕན་ཚུན་བསྡེབས་ཡོང་དུས་ཙ་ནས་[གི་]ཙ[ང་]ནས། ནུས་པའི་ངོ་བོ་ག་འདྲས་སེ་[ཟེར་་]འགྱུར་གྱི་ཡོད་པ། སེ་[སོ་]རྫས་ཕན་ཚུན[ལ་]བསྡེབས་ཡོང་དུས་ཡང་རྫས་གསར་པ་ཞིག་ཐོན་ཡོང་གི་འདུག་བ། རེད་བ།

09:18 དེ་འདྲའི་གཅིག་གིས་ཁོ[ང་]རང་ད་དངོས་པོའི་རང་བཞིན་ཁོ[ང]་རང་ཨེ་ནས་ཕན་ཚུན་ལྟོས་ནས། 



༢༠༢༣་༠༥་༢ བཅོས་ཡོད། ཕྱེད་ཀ་རྗེས་ནས་བསྐུར་ཡོང་།

2023-05-02 10:24 UTC, choephel-tashi commented
04:48 ཚན་རིག་པ་རང་ཆགས་ཀི་ཡོད་མ་རེད། བློ་གཟུ་བོར་གནས་པ་དེ་ཆགས་ཡོད་མ་རེད། ཡང་དེ་མི་ལ་ཡང་བཤད་པ་གཅིག་པོ་མིན་ད། ང་རང་ཚོའི་ངོས་ནས་ཆ་བཞག་ནས་ང་ཚོའི་འདི་ཡང་དག་པ་ཡིན་ཟེར་བྱས་ནས་སྔོན་ལ།

04:58ཐག་བཅད་ནས། ཨེ་ནས་ཚན་རིག་ནས་གཅིག་རིག་པ་གཅིག་ཨེ་རན་མི་རན་གཅིག་བལྟས་པ་ཡིན་ནས་ནོར་འཁྲུལ་རེད། ཚན་རིག་ཙམ་དུ་ཟད་པའི་སྤྱིར་བཏང་ད་རིག་པའི་སྒྲུབ་བྱེད་གཅིག་བཀོད་ནས།

05:07 གཅིག་གཅིག་ད་མཐུན་ཕྱོགས་ལ་མཐོང་ཙམ་དང༌། མི་མཐུན་ཕྱོགས་ལ་མ་མཐོང་ཙམ་གྱིས་རྒྱུ་མཚན་འདྲ་བོ་གཅིག་བཀོད་བྱས་ནས་གཅིག་ཨེ་ཡོང་མི་ཡོང་ཞིག་བལྟས་པ་ཡིན་ན། ད་དེ།

05:16 ཁོ་བློ་གཟུ་བོར་གནས་པའི་ཐོག་ནས་དཔྱད་པ་བྱེད་སྟངས་དེ་ཆགས་ཀྱི་ཡོད་མ་རེད། དཔྱད་པ་བྱེད་སྟངས་དེ་ཆགས་ཀྱི་མི་འདུག་ཨ། ད་འཕྲོས་བཤད་འདྲ་བོ་གཅིག་རེད། འཕྲོས་བཤད།

05:26 ཞོར་ལ་ཡ་ད་འཕྲོས་བཤད་བཟོ་འདྲ་་གཅིག། ཨེ་ཚན་རིག་པ་དང་འབྲེལ་བ་བྱེད་ཡག་གི་རྒྱུ་མཚན་ག་རེ་ཟེར་ལབ་པ་ཡིན་ན།

05:35 ད་ང་ཨང་ལྟ་ཚན་རིག་པ་ལ་ཡ་འབྲེལ་བ་བྱས་ནས་ལོ་ཧ་ལམ་ད། ཨེ་བཅོ་ལྔ། ད་ཉི་ཤུ་མ་ཟིན་ཙམ་འགྲོ་བསྡད་ཀིན་ཡོད་རེད།

05:43 བྱས་ཙང་ཁ། ད་མགོ་སྟོད་ཐོག་མར་དེ་ཚན་རིག་པ་ལ་ཡ་འབྲེལ་བ་བྱེད་ཡག་གཅིག་ཨེ་བསམ་བློ་བཏང་པའི་ཁ་ཐུག་ལ་ཡ། །བསམ་བློ་འཁོར་བའི་ཁ་ཐུག་ལ།

05:53 ངའི་ངོ་ཤེས་པ་གཅིག་ཡོད། ཨེ་ཨ་རིའི་མི་གཅིག།མོ་རང་ད་རང་ནང་པ་ཡིན་པར་རེད།

06:02 ཁོ་རང་ནང་པ་ཡིན་པ་རེད། བྱས་ནས་ངས་ཚན་རིག་པ་དང་འབྲེལ་བྱེད་ཡག་དེ་ཉེན་ཁ་ལྗིད་པོ་རེད་ཟེར།

06:11 ཚན་རིག་ཟེར་བསྡད་དེ་ཨེ་དབྱིན་ཇིའི་ཚིག་ནང་ལོག་ལ་ཡ་Killer of religious ཆོས་གསོད་མཁན་དེ་རེད་ཟེར། ཚན་རིག་ཟེར་ཡག་དེ།

06:20 ཚན་རིག་པ་དང་འབྲེལ་བ་བྱེད་ཡག་དེ་ཉེན་ཁ་རེད་ཟེར་ཨ། ངས་བསམ་བློ་ཞིག་བཏང་པས། ཨེ་ནས།  ཚན་རིག་གིས་ག་རེ་བྱེད་ཀི་ཡོད་རེད།

06:29 བདེན་པ་བཙལ་གིན་ཡོད་རེད་ད། འོ་ད་འཚོལ་སའི་ཡུན་རང་ད། ཁོང་རང་ཚད་ཅན་གཅིག་རེད། གཙོ་བོ་

06:38 གཟུགས་ཅན། དེའི་ནང་ནས་མངོན་གྱུར་བ། མཐོང་བ་མངོན་གྱུར་བ། དེའི་ནང་ནས་གཙོ་བོ་གཟུགས་ཅན་གྱི་ཆོས།

06:46 ཚད་བརྒྱབ་ས་བསྡད་ཡོད་པ། ཨེ་གཅིག་ཕ་གིའི་རྩིས་རྒྱག་ཡག་ཡོད་བསྡད་པ། དེ་འདྲའི་གཅིག་ནང་ལོག་ལ།

06:54 ཨང་ལྟ་science་ད་འགྲོ་བསྡད་ཡོད་རེད། དེ field ཁོ་རང་ limited་རེད། སེ་དེ་འདྲས་ཡིན་དུས།

07:04 སེ་འོ་ད་ནང་པའི་གཞུང་ནས་དཔེར་ན་བཤད་པ་ཡིན་ན། ཨེ་ནང་པའི་གཞུང་ནང་ལོག་ལ་ཡ། འོ་ད་མ་གཞི་གཞུག་གུ་གཞུག་གུར་ཐོན་ཡོང་གི་རེད། གཞུག་གུར་ལབ་ཀི་ཡིན། 

07:13 རེད་དེ་ཡིན་ནས་གང་ལྟར་ཁོ་རང་གཅིག་བཙལ་བྱའི་གཞི་འདྲ་བོ་ཁོ་ཚད་ངེས་ཅན་གཅིག་རེད་དེ།

07:22 ཡིན་ནས་གཞི་དེའི་ནང་ལོག་ལ་བདེན་པ་འཚོལ་གྱི་ཡོད་རེད་ད།  སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས། སངས་རྒྱས་པའི་ཆོས་ཀྱིས་བདེན་པ་འཚོལ་ཡག་ཅིག་བཤད་ཀྱི་ཡོད་རེད།

07:30 དཔེར་འདྲ་བོ་ཆ་བཞག་ན་རེད་ད། དཔེར་འདྲ་བོ་ཆ་བཞག་ན། ཨེ་བདེན་པ་འཚོལ་ཡག་གཅིག་བཤད་ཀྱི་ཡོད་པ་ཡིན་དུས་ཙ་ནས་བདེན་པ་འཚོལ་སྟངས་དེ་ལ་ཡ་རིགས་པའི་སྒོ་འདྲ་བོ་དེ་བཞི་གསུང་གི་འདུག་ཨ།

07:40ཆོས་ཉིད་ཀྱི་རིགས་པ་ཟེར་གཅིག་བཤད། རེད་བ། དེ་ནས་བྱ་བ་བྱེད་པའི་རིགས་པ་ཟེར། དེ་ནས་ལྟོས་པའི་རིགས་པ། [ཐད་པའི་[ས་སྒྲུབ་པའི་རིགས་པ་]

07:50བཅས་ནི། ད་དེ་གས་དེ་ག་རེ་རེད་ཟེར་ལབ་ན། སྔོན་ལ་གཞི་ལ་གཅིག་གང་ལྟར་རང་བཞིན་ལྷན་སྐྱེས་ཀྱི། དཔེར་ན་གཅིག་ང་རང་ཚོ་ལ་ཡ།

07:59ཨེ་ང་ཟེར་ཡག་གཅིག་ཡོད་བསྡད་མཁན། དེ་ངའོ་སྙམ་པའི་བློ་གཅིག་ཡོད་བསྡད་པ། ཨེ་དེ་ལ་ཡ་བདེ་སྡུག་གི་ཚོར་བ་གཅིག་ཡོད་བསྡད་པ།

08:09 དེ་དང་འབྲེལ་ནས་བདེ་སྡུག་གི་ཚོར་བ་གཅིག་ཡོད་བསྡད་པ། དེ་ཆོས་ཉིད་རེད། དེ་ལས་ཀྱིས་བྱུང་བ་ཡང་མ་རེད། ཨེ་ག་གས་མ་རེད། ཁོ་རང་ད་ཆོས་ཉིད་རེད།

08:17 ད་ག་ནང་བཞིན་གི་ཕྱི་ལ་གཟུགས་ཅན་ཟེར་ཡག་གཅིག་ཡོད་བསྡད་པ། ཨེ་ཕྱི་དང་ནང་གི་ཆོས་གང་དང་གང་ཡིན་ནས། འབྲས་བུ་རྒྱུ་ལ་རག་ལས་པ།

08:25 ཆོས་ཉིད་རེད། ཨེ་ནས་ད་ག་ནང་བཞིན་ཁོ་རང་། ཨེ་ཆོས་རང་རང་གི་ཁོ་རང་བྱེད་ལས་འདྲ་བོ། དཔེར་ན་མེ་ཚ་བ།

08:34 ཆུ་རླན་པ་ཟེར་ཡག་དེ་ཚོའི་གྲས་དེ། ཁོ་རང་ཆོས་ཉིད་ལ་བརྩི་ཡི་ཡོད། ཆོས་ཉིད་ཀྱི་རིགས་པ་ཟེར་གཅིག་བྱས། ད་དེ་ཁོ་རང་བཞིན་ལྷན་སྐྱེས་ཀྱི་ཁོ་རང་དངོས་པོ་དངོས་པོ་སོ་སོའི་

08:43གནས་སྟངས་གང་ཡིན་པ་དེ་གཅིག་ཤེས་དགོས་ཀི་ཡོད་རེད། ད་དེ་ནས་ཨེ་ནས་ཨེ་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི། 

08:52 ཨེ་བྱ་བ་བྱེད་པའི་རིགས་པ་ཟེར་ལབ་ན། དངོས་པོ་སོ་སོ་སོའི་བྱེད་ལས་ག་རེ་ག་རེ་ཡོད་མེད།

09:01 ཕལ་ཆེར་ང་ཚོ་དཔེར་ན chemistry དེ་ཚོའི་འདིའི་ནང་སླེབས་ཀི་མེད་འགྲོ་བསམ་གྱིན། ཁོ་རྫས་རྫས་སོ་སོ་སོའི་ནུས་པ་ག་རེ་ཡོད་པ།

09:09 རྫས་ཕན་ཚུན་བསྡེབས་ཡོང་དུས་ཙ་ནས་ཙ་ནས། ནུས་པའི་ངོ་བོ་ག་འདྲས་སེ་འགྱུར་གྱི་ཡོད་པ། སེ་རྫས་ཕན་ཚུན་བསྡེབས་ཡོང་དུས་ཡང་རྫས་གསར་པ་ཞིག་ཐོན་ཡོང་གི་འདུག་བ། རེད་བ།

09:18 དེ་འདྲའི་གཅིག་གིས་ཁོ་རང་ད་དངོས་པོའི་རང་བཞིན་ཁོ་རང་ཨེ་ནས་ཕན་ཚུན་ལྟོས་ནས།


Done at 15:53 on Second May

2023-05-03 03:40 UTC, Tenzindharten requested changes
09:28 ཕན་ཚུན་འབྲེལ་ནས་ཁོ[ང་]ཡོད་བསྡད་པ་[གཅིང]་ཡིན་དུས་ཙ་ནས། [མ་ན། ཕན་ཚུན་ལྟོས་པའི་སྒོ་ནས་ཨེ་ནས་[ནི་]ངོ་བོར་ལ་འགྱུར་བ་འགྲོ་བསྡད་གཅིག་ཡོང་བསྡད་ཡག་འདུག་ཨ།

09:37ཆུ་དང། དཔེར་ན། ག་རེ་ཟེར་དགོས་རེད། དཔེར་ན། དཔེར་ན། དཔེར་ན། མེ་དང་ཆུ་འཐབ་ནས་ཡང་ཁོ[ང་]རང་ག་རེ་ཟེར་དགོས་རེད། ཕ་གིའི་རྣམ་པ་འདྲ་བོ་གསར་པ་གཅིག་ཡོང་བསྡད་ཡག་འདྲ་བོར།

09:47 དཔེར་ན་རྫས་མི་འདྲ་བ་གཉིས་བསྡུས་ནས་ཡང་གཅིག་རྣམ་པ་མི་འདྲ་གསར་པ་ཡོང་བསྡད་ཡག་ཡོང་གི་རེད་བ། ད་དེ་ལྟར་ཨེ་ཕན་ཚུན་བསྡུས་ནས་ཡིན་ནས་[ན་]འདྲ། ཁེར་རྐྱང་ཡིན་ནས་[ན་]འདྲ།

09:56 ཨེ་དངོས་པོ་གཅིག་གིས་རང་རང་གི[ས་]འབྲས་བུ་གསར་པ་སྐྱེས་ཡག་[ཡས་]གཅིག་ཡོང་བསྡད་ཀི་འདུག་ཨ། དེ་ལྟོས་པའི་རིགས་པ་ཟེར་[ཞེས་]ལབ་ཡིན་པ་[ཡོང་གི་]རེད། འབྲས་བུ་དེ་རྒྱུ་ལ་ལྟོས་པ་རེད་ཟེར།

10:05  འབྲས་བུ་དེ་རྒྱུ་ལ་ལྟོས་པ[ས]། ད་འདི་གས་འདི་[གར་]ཁོ[ང་རང་ལོག་ཁ[ར་]རེད།NATURE ལོག་ཁ་བཟོ་འདྲ་བོ་[སོར་]འདུག་བ།NATURE ལོག་ཁ[ར་དེ་དེ་]འདི་ཁས་བླངས་ནས།NATURE་

10:14 དེའི་ཐོག་ནས་རང་བཞིན་ལྷན་སྐྱེས་ཀྱི་ཁྲིམས་བཟོ་འདྲ་བོ་[སོར]་ད་འགྲོ་སྟངས་འདྲ་བོ་གཅིག།ད་དེ་གཞི་ལ་བཞག་པའི་ཐོག་ལ་ཨེ་ནས་འཐད་སྒྲུབ་ཟེར་ཡག་[ཡས་]དེ། ད་འཐད་[ར་]སྒྲུབ་ཟེར་ཡག་[ཡས་]དེ་ཨོ།

10:23དེ་ཡིན་ཙང་། དེ་ཡིན་དགོས་རེད། དེ་ཡིན་[བྱས་]ཙང་དེ་ཡིན་དགོས་རེད། ད་ང་ཚོ་སྡུག་བསྔལ་མི་འདོད་པ་དང༌། བདེ་བ་འདོད་པ་རང་བཞིན་ལྷན་སྐྱེས་རེད་བ་ད། བྱས་ཙང་དེ་འདྲས་[འདྲ་]ཡིན་ཙ་ནས། [འདུག་ཙང་ནས།]

10:30 ཨོ། ད་ང་ཚོ་[ས་་]བདེ་བ་ཡོང་ཡག་གི་[ཡས་ཀྱི། བདེ་བ་ཡོང་ཡས་]རྐྱེན། རྒྱུ་རྐྱེན་འདི་འདྲའི་གཅིག་དགོས་ཀི་[ཀྱི]་འདུག། དེའི་རྐྱེན་དེ་ལ་རག་ལས་ཡོད་རེད། དེའི་རྐྱེན་དེའི་དབང་གིས་ཡོང་གིན་ཡོད་རེད།

10:39   དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ[ང་]ནས་ང་ཚོས་རྒྱུ་རྐྱེན་འདི་སྒྲུབ་དགོས་འདུག་བྱས་ནས། [དེ་འདྲ་]ཨེ་ནས་སླེབས་ཀི་[ཀྱི་]འདུག་བ། ད་འཐད་པར་[ས་]སྒྲུབ་པའི་རིགས་པ། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་ཀྱི་རེད། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་རེད། དེ་ང་ཚོ[ར་]ལ་དགོས་ཀྱི་འདུག དེ་ང་ཚོ[ར་]ལ་དགོས་ཀྱི་མི་འདུག

10:49  དེ་འདྲས་ཡིན་པ་ཡིན་དུས། ཨེ་མ་དགོས་ཡག་དེ་[ཡས་]མེད་བ་ཡོང་ཡག་[ཡས་]དོན་དག་ལ་ཁོ[ང་]ཕན་ཚུན་ལྟོས་པའི་ཨེ་ཕྱོགས་དེ་གས་དེ་[དག་]ལ་བསམ་བློ་གཏང་ཡག་[ཡས་]གཅིག།

10:56 ཨེ་ད་ག་ནང་[ར་ན]་བཞིན་གྱི་ཕ་གིའི་ཨེ་[ཕར་གར།]ག་རེ་[རེད་]ཟེར་བ་དགོས། ད་བྱ་བ་བྱེད་པ[འི་བ་]ཟེར་ན་ཁོ[ང་]རང་གཅིག་གིས་གཅིག་གིས་ད་ནུས་པ་མི་འདྲ་བ་ཡོད་པ་དེ་གས་དེ་[དག་]ཤེས་ཡག་[ཡས་]གཅིག་དང་།

11:06 ཨེ་ནས་[ནི་]དེའི་རྒྱུ་འབྲས་ཀྱི་འགྲོ་སྟངས་དེ་ཤེས་པའི་ཐོག་ནས། ཨེ་ནས་[ནི་]ང་ཚོ[ར]་ལ་ཡ་ཕན་པའི་དངོས་པོ་དང་དུ་བླངས། མི་འདོད་པའི་དངོས་པོ་དེ་ཨེ་ནས་ཉུང་དུ་བཏང་།

11:16ཕར་འཕྲི། འཕྲི་ཡག་[ཡས་]ཤེས་ཀྱི་རེད་བ། ཉུང་དུ་གཏང་ཡག[ཡས།]ད་དེ་འདྲའི་བྱེད་ཡག་[ཡས་]རེད་འདུག་བ།[སོ་]སེ་ད་ཆོས་ཟེར་ཡས་འདི་སྒང་ནས། སངས་རྒྱས་པའི་ཆོས།



11:25 ད་དེའི་སྒང་ནས་བཤད་བསྡད་ཀི་རེད་བ། བཅོམ་ལྡན་འདས་ཁོ[ང་]རང་ཡང་རིགས་པ་བཞིའི་འགྲོ་སྟངས་འདིའི་ཐོག་ནས་བཅོམ་འདས་ཁོ[ང་]རང་གིས་ཨེ་ནས།[ནི]

11:34 ཁོ[ང་]རང་གི་བསམ་བློའི་ནང་ལ་ཡ་[ལོག་ཡར་]ད་འགྱུར་བ་གཏོང་ཡག་[ཡས]་གཅིག། གསལ་རིག་གི་ཤེས་པ་གཅིག་ཡོད་པ་བྱས། གསལ་རིག་གི་ཤེས་པ་ལ་འགལ་ཟླ་མང་པོ་ཡོད་པ་བྱས།

11:44 མི་མཐུན་པ་མང་པོ་ཡོད་པ་བྱས། མི་མཐུན་པ་དེའི་ནང་ལོག་ལ་འགལ་ཟླ་མང་པོ་ཡོད་པ་བྱས། སེ་ཕྱི་དངོས་པོ་ལ་ཡ[ར་]འགལ་ཟླ་ཡོད་ཙང་འགྱུར་བ་འགྲོ་གི་རེད་བ། འགལ་ཟླ་མེད་ན་འགྱུར་བ་འགྲོ་གི་མ་རེད་བ། [་མེད་བ།]

11:52 [སོ་]སེ་དེ་འདྲས་ཡིན་པས། དེ་ནང་བཞིན་[ནང་]ཤེས་པ་ལ་[ར་]ཆ་བཞག་ནས། འགལ་ཟླ་ཡོད་ཙང་ཤེས་པ་འགྱུར་བ་འགྲོ་གི་ཡོད་པ་མ་གཏོགས། 

12:01 འགལ་ཟླ་མེད་ན་ཤེས་པ[ར་]འགྱུར་བ་འགྲོ་ཡག་[ཡས་]མི་འདུག་ཨ། ཨེ་ཤེས་པའི་ནང་འགལ་ཟླ་ག[ང]་འདྲས་རེད་ཟེར་ལབ་ན་ཤེས་པའི་ཕྱི་ལོག་གི་གཟུགས་ཅན་ཆོས་ཀྱི་འགལ་ཟླ་དེ་ཁོ[ང་]རང་།

12:10  ནུས་པ་དེ་འདྲའི་མང་པོ་ཞིག[་གི་]ཐོག་ནས་བཤད་ཐུབ་ཀྱི་རེད། དེ་འདྲའི་ཐོག་ནས་ཡོང་གི་རེད། དཔེར་ན། ཚ་གྲང་[གཉིས་]འགལ་ཟླ་རེད། ཚ་གྲང་[གཉིས་]འགལ་ཟླ་དེ་ཁོ[ང་]རྒྱུན་གྱི་འགལ་བ་རེད། རྒྱུན་གཅིག་ཏུ་གནས་མི་ཐུབ་པ་[ས་]གཅིག།

12:19 འགལ་བ་ཡིན་པ་རེད། སྣང་བ་དང་མུན་པ[འི་]འགལ་བ་རེད། ཁོ[ང་]རང་དུས་གཅིག་ཏུ་གནས་མི་ཐུབ་ཡག་གཅིག་གིས་[པའི་]འགལ་བ་སླེབས་ཡོང་གི་འདུག་བ། ད།

12:28 ནང་ཤེས་པ་ལ་ཡ[ར་]ཁོ[ང་]རང་གཟུགས་ཅན་གྱི་ཆོས་ནང་བཞིན་བྱས་ནས་འགལ་བ་བརྩི་ས་ཡོད་མ་རེད་དེ། ཡིན་ནས་ཁོ[ང་]རང་འཛིན་སྟངས་འགལ་བ་ཆགས་ཀི་འདུག་བ། གཅིག་གིས་དཔེར་ན་ཡག་པོ་རེད་ཟེར་འཛིན་བསྡད་ཡག་[ཡས་]བློ་དེ་དང༌།

12:38 དེ་སྡུག་པོ་རེད་ཟེར་ཡག་[ཡས་་]འཛིན་བསྡད་པའི་[ཡས་]བློ་གཉིས་པོ་དེ་འཛིན་སྟངས་འགལ་བ་རེད་བ། ཡུན་[ལ་]དམིགས་པ་གཅིག་ལ་དམིགས་ནས་དུས་གཅིག་ལ་འདི་ཡག་པོ་རེད། འདི་སྡུག་ཅག་རེད་ཟེར་བསྡད་ཡག་[ས་]གཉིས་པོ་དེ་འགལ་བ་རེད་འདུག་བ།

12:48 ད་ཚུར་བསམ་བློ་གཏོང་ཡོང་དུས་ཙམ་ནས། ཉམ་ཐག་པའི་སེམས་ཅན་ལ་དམིགས་ནས་དེ་དང་སྙིང་རྗེ་བསམ་པའི་བརྩེ་བ་དེ་དང༌།

12:58  སེམས་ཅན་དེ་ལ་དམིགས་ནས་དེ་སྡུག་བ་གཅིག་བྱུང་ན་བསམ་པའི་སྡང་བའི་སེམས་གཉིས་པོ་དེ་འཛིན་སྟངས་འགལ་བ་རེད་འདུག་ག། བྱས་ཙང་དངོས་པོ་ལ་ཡ། [དདོས་པོ་ཡར།]

13:07 གཞི་གཞི་གཞི་གཞི་ག་རེ་ཟེར་བ་རེད། གཞི་དངོས་པོའི་གནས་ཚུལ་ཁོ[ང་]རང་ལ་ཡ་[ཡར་]ནང་ཤེས་པ་ལ་འགལ་ཟླ་མང་པོ་འདུག་བ། འགལ་ཟླ་ཡོད་པ་ཡིན་དུས་ཙ[ང་]ནས། དཔེར་ན།

13:16  ཕྱིའི་འགལ་ཟླ། དཔེར་ན། ཚ་བའི་རེག་པ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན་གྲང་བའི་རེག་པ་ཉུང་དུ་ཉུང་དུ་འགྲོ་བསྡད་ཡག སྣང་བ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན་མུན་པ་ཤུགས་ཆུང་དུ་་ཆུང་དུ་འགྲོ་བསྡད་ཡས།

13:24  སྣང་བ་ཇེ་ཉུང་དུ་ཕྱིན་པའི་ཚོད་ཀྱིས་[ཚུལ་གྱིས་]མུན་པ་ཤུགས་ཆེ་རུ་ཆེ་རུ་འགྲོ་བསྡད་ཡག[ས། ]དེ་ནང་[ན་]བཞིན་བྱས་ནས་[ན་]ནང་ཤེས་པ་ལ་འགལ་བ་ཡིན་བསྡད་མཁན་[ཡས་]བློ་གཉིས། ཨེ་དམིགས་པ།

13:33 སེམས་ཅན་ལ་དམིགས་ནས་སྡང་བའི་སེམས་དེ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན། དེ་ལ་དམིགས་པའི་བྱམས་པའི་སེམས་དེ་ཤུགས་ཡོང་ཐུབ་ཡག་[ཡས]་མེད་བསྡད་མཁན།

13:42 སེམས་ཅན་དེ་ལ་དམིགས་ནས་བྱམས་པའི་བློ་ཤུགས་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན། དེ་ལ་དམིགས་ནས་ཁོང་ཁྲོའི་བློ་ཡོང་མི་ཐུབ་པ་ཡག་[པ་]ཁོ[ང་]ཆགས་འདུག་བ། བྱས་ཙང་ཁ་[ང་]ད་དངོས་ཡོད་གནས་ཚུལ་གྱིས།

13:51ཁོང་གང་ལྟར་འགལ་བ་ཡོད་བསྡད་མཁན་གི་འགྱུར་བ་ད་ཆོས་ཉིད་ཀྱི་རིགས་པ། ལྟོས་པའི་རིགས་པ། བྱ་བ་བྱས་པའི་རིགས་པ་དེ་དག་གི

14:00 འོག་ནས་འཐད་སྒྲུབ་ཀི་[ཀྱི་]རིགས་པ། ད་བདེ་བ་འདོད་པ་དང༌། སྡུག་བསྔལ་མི་འདོད་པ་དེ་གཞི་ལ་བཞག།ད་བདེ་བ་འདོད་པ་དང༌། སྡུག་བསྔལ་མི་འདོད་པ་རང་གིས་ངང་ལ་ཡོད་རེད། འགྲེལ་བཤད་ག་གས་[་གང་ཡང་]བརྒྱབ་དགོས་ཡག་ཡོད་མ་རེད། [མི་དགོས་ཡས་ཡོད་མ་རེད།]

14:09དེ་གཞི་ལ་བཞག་པའི་ཐོག་ལ་[ནས་]ད་བདེ་སྡུག་ལ་འབྲེལ་བ་ཡོད་བསྡད་[ས་]མཁན་ཕྱི་ལོག་གི་དངོས་པོ་ཡིན་ནས་[ན་]འདྲ། ནང་གི་ཤེས་པ་ཡིན་ནས་[ན་]འདྲ།

14:17གཉིས་ཀ[ར་]ལོག་ནང་ལ་བདེ་སྐྱིད་ཡོང་ཡག་གི་[ཡས་]མཐུན་རྐྱེན་དེ་བསྒྲུབ་ཡག་[ཡས་]གཅིག་དང་། བདེ་སྐྱིད་ལ་གནོད་མཁན་གྱི་སྡུག་བསྔལ་སྟེར་མཁན་གྱི་འགལ་རྐྱེན་དེ་གས་དེ། [དག།]

14:26 ཉུང་དུ་གཏང་ཡག་[ཡས་]ད་དེ་འོས་པ་དང༌། ཐོབ་ཐང་ཡོད་པ་རེད་བ་ང་ཚོར་ལ་ཡ། སོ་སེ་དེ་འདྲས་ཡིིན་དུས་བཅོམ་ལྡན་འདས་ཁོ[ང་]རང་ཨེ་རིགས་པ་བཞིའི་སྒོ་ནས་འདུག་སེ་[སོར]ད་དགོངས་པ་བཞེས་ནས།

14:35 ཨེ་ནས་[ནི་]བསམ་མནོ་བསམ་བློར་འགྱུར་བ་ག་ལས་ག་ལས་[ལེ་ག་ལེར་]ཐེབས་བྱས་འདུག་སེ་[ཟེར་]བྱས་ནས། སྐྱོན་ཀུན་ཟད་ཡོན་ཏན་ཀུན་ལྡན་ཟེར་ཡག[ཡས།] ད་དེ་ཡང་གཤམ་ལ་མར་ཐོན་ཡོང་གི་རེད། ད་དྲི་མ་ཟད་ཐུབ་ཡག་[ཡས་]ཡོད་དང་མེད་ཟེར་བསྡད་དེ་[དག་]དཔེར་རྙོག་དྲ་ཚ་པོ་རེད་བ།

14:45  ཆགས་སྡང་ཆུང་དུ་འགྲོ་ཡག་[ཡས་]ང་རང་ཚོའི་མྱོང་བས་ཤེས་ཐུབ་འདུག། ང་ཚོའི་ཐ་མལ་པའི་མྱོང་བ་དེ་འདྲའི་གཅིག་[གི]་འོག་ནས་ཤེས་ཐུབ་ཡག་[ཡས་]རེད། ཡིན་ནས་ཆགས་སྡང་གཏན་དུ་ཟད་ཐུབ་དང་མི་ཐུབ་ཟེར་མཁན་དེ་ད་བསམ་བློ་ཞེ་བོ་གཅིག་བཏང་ན་མ་གཏོགས།

14:55  ལམ་སངས་[སེང་]ཤེས་ཐུབ་ཡག་[ཡས་]ཁག་པོ་འདུག་བ། [སོ་]སེ་ད་གང་ལྟར་ཡང་སྙིང་སངས་རྒྱས་བཅོམ་ལྡན་འདས་རང་ཉིད་[ཀྱང་]ག་ལས་ག་ལས་[ལེ་ག་ལེར་]་ལ་ཡ[ར]་ཨེ་ནས་[ནི]་ཁོ[ང་]སྐྱོན་དེ་གས་དེ་[གིན་]ཉུང་དུ་ཉུང་དུ་ཕྱིིན།

15:04  ཡོན་ཏན་དེ་གས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་གྱིས་[བྱས་]འདུག་སེ་[ཟེར་]བྱས་ནས།ཨེ་ནས་[ནི་]གང་ལྟར་སྤངས་རྟོགས་མཐར་ཕྱིན་པ་གཅིག་ཆགས་ཡག་[ཡས་]རེད་མ་གཏོགས། [གང་གེར་]ག་གས་མ་བྱས་པར་དང་པོ་ནས་བྱུང་བསྡད་པ་གཅིག་གཅིག་[ཡང་]ཡོད་མ་རེད་བ། ད་དེ་སངས་རྒྱས་པའི་འགྲོ་སྟངས་རེད་གདའ།

15:14  སངས་རྒྱས་པའི་ཞུ་སྟངས་དེ། ད་འཇིག་རྟེན་བཀོད་པ་པོ་འདོད་མཁན་གྱི་དཀོན་མཆོག་ཟེར་ལབ་ཡིན་ན་གནས་ཚུལ་ཁ་ཁ[ར]་རེད། ཡེ་གདོད་མ་ནས་ཨེ་ནས་ཨེ་སངས་རྒྱས་ཟེར་ཡག་གཅིག་ཡོད་བསྡད་པ།  དཀོན་མཆོག་ཟེར་ཡག[ཡས་]གཅིག་ཡོད་བསྡད་པ་བཤད་བྱས།

15:24  དེས་ཨེ་ནས་འཇིག་རྟེན་བཀོད་པ་རེད་ཟེར་གྱིས་[ཅེསཤོད་ཀྱི་]བཤད་ཀི་ཡོད་རེད་བ། སངས་རྒྱས་པས་ད་དེ་མ་རེད་བ། སོ་སེ་དེ་འདྲས་[འདྲ་]ཡིན་དུས་ཨང་ལྟ་[ད་]ངས་བཤད་དགོོས་ཡག་དེ། [ཡས།་]དེ་འདྲས་[འདྲ་]ཡིན་དུས།



15:33  སངས་རྒྱས་པའི་ཆོས་ཀྱིས་བརྟག་དཔྱད་བཏང་ནས། ཨེ་ནས་[ནི]་ཡིན་ལུགས་ཇི་ལྟ་ཇི་སྙེད་ཀྱི་དོན་གང་ཡིན་ནས་ཡིན་ལུགས་གཏན་ལ་ཕབ་ཡག་[ཡས་]གཅིག་ཆགས་བསྡད་འདུག་ཟེར།

15:43  ཨེ་ཚན་རིག་པས་ཁོ[ང་]ཡིན་ལུགས་གཏན་ལ་ཕབ་ཀྱི་ཡོད་རེད། [སོ་]སེ་དེ་ཡིན་དུས་[ཁོང་]འགལ་བ་གལ་མི་འདུག་བ། བྱས་ཙང་། འོ།

15:52 ཨེ་དེ་ཡིན་དུས་ད་ཡིན་གཅིག་མིན་གཅིག་ཚན་རིག་པ་ལ་འབྲེལ་བ་བྱས་ན། ཨེ་ནས་[ནི་]འགལ་བ་ག་གས་[གེར་]མི་འདུག་བསམས་ནས་འདུག་སེ་[ཟེར་]ད་འབྲེལ་[བྲེལ་]བ་བྱས་པ་རེད།

16:00ཡང་མཚམས་མཚམས་ཁ་ཤས་ཚན་རིག་པ་དེ་འདྲས། [འདྲ།] ཚན་རིག་པ་ཟེར་ནས་མི་འདུག།ཁ་ཤས་ཀྱིས་སྐད་ཆ་དྲིས་ཀིན། [འདྲི་གི།]ཨེ་ནས་[ནི་]ངས་ག་རེ་ཟེར་[ཟེད་]ད་ནང་པས་ཚན་རིག་ལ་ཡ། 

16:09 དོ་སྣང་བྱེད་ཡག་[ཡས་]དེ་ག་རེ་རེད་ཟེར། ཁ་ཤས་ཡ་མཚར་མཚར་[མཚན་མཚན་]བྱེད་ཀྱིན་འདུག་བ།  [མདོག་བྱས་ཀྱི་འདུག་བ།]ཨེ་ནས། [ནི།] ཨེ་ནང་པས་ Reality

16:19 བདེན་པ་དེ། དངོས་ཡོད་གནས་ཚུལ་ག་རེ་ཡོད་པ་དེ་ང་ཚོས་བཙལ་གྱི་ཡོད་རེད་ཟེར། ཚན་རིག་པས་དངོས་ཡོད་གནས་ཚུལ་བཙལ་གྱི་ཡོད་རེད་ཟེར། ད་བདེན་པ་འཚོལ་བ།

16:28 Reality དེ་ང་ཚོས་འཚོལ་གྱི་ཡོད་པ་རེད་ཟེར། བྱས་ཙང་ག [ང་]Reality འཚོལ་མཁན་གཅིག་པ་རེད་ཟེར། ཚན་རིག་དང་ནང་པ་གཉིས་ཆ་ལོག་[ཀ་ལོར་]Reality་འཚ [...]

2023-05-03 06:59 UTC, choephel-tashi commented
09:28 ཕན་ཚུན་འབྲེལ་ནས་ཁོ་ཡོད་བསྡད་པ་ཡིན་དུས་ཙ་ནས། ཕན་ཚུན་ལྟོས་པའི་སྒོ་ནས་ཨེ་ནས་ངོ་བོར་ལ་འགྱུར་བ་འགྲོ་བསྡད་གཅིག་ཡོང་བསྡད་ཡག་འདུག་ཨ།

09:37ཆུ་དང། དཔེར་ན། ག་རེ་ཟེར་དགོས་རེད། དཔེར་ན། དཔེར་ན། དཔེར་ན། མེ་དང་ཆུ་འཐབ་ནས་ཡང་ཁོ་རང་ག་རེ་ཟེར་དགོས་རེད། ཕ་གིའི་རྣམ་པ་འདྲ་བོ་གསར་པ་གཅིག་ཡོང་བསྡད་ཡག་འདྲ་བོར།

09:47 དཔེར་ན་རྫས་མི་འདྲ་བ་གཉིས་བསྡུས་ནས་ཡང་གཅིག་རྣམ་པ་མི་འདྲ་གསར་པ་ཡོང་བསྡད་ཡག་ཡོང་གི་རེད་བ། ད་དེ་ལྟར་ཨེ་ཕན་ཚུན་བསྡུས་ནས་ཡིན་ནས་འདྲ། ཁེར་རྐྱང་ཡིན་ནས་འདྲ།

09:56 ཨེ་དངོས་པོ་གཅིག་གིས་རང་རང་གི་འབྲས་བུ་གསར་པ་སྐྱེས་ཡག་གཅིག་ཡོང་བསྡད་ཀི་འདུག་ཨ། དེ་ལྟོས་པའི་རིགས་པ་ཟེར་ལབ་ཡིན་པ་རེད། འབྲས་བུ་དེ་རྒྱུ་ལ་ལྟོས་པ་རེད་ཟེར།

10:05 འབྲས་བུ་དེ་རྒྱུ་ལ་ལྟོས་པ་། ་འདི་གས་འདི་ཁོ་རང་ལོག་ཁ་རེད།NATURE ལོག་ཁ་བཟོ་འདྲ་བོ་འདུག་བ།NATURE ལོག་ཁ་འདི་ཁས་བླངས་ནས།NATURE་

10:14 དེའི་ཐོག་ནས་རང་བཞིན་ལྷན་སྐྱེས་ཀྱི་ཁྲིམས་བཟོ་འདྲ་བོ་ད་འགྲོ་སྟངས་འདྲ་བོ་གཅིག།ད་དེ་གཞི་ལ་བཞག་པའི་ཐོག་ལ་ཨེ་ནས་འཐད་སྒྲུབ་ཟེར་ཡག་དེ། ད་འཐད་སྒྲུབ་ཟེར་ཡག་དེ་ཨོ།

10:23དེ་ཡིན་ཙང་། དེ་ཡིན་དགོས་རེད། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་རེད། ད་ང་ཚོ་སྡུག་བསྔལ་མི་འདོད་པ་དང༌། བདེ་བ་འདོད་པ་རང་བཞིན་ལྷན་སྐྱེས་རེད་བ་ད། བྱས་ཙང་དེ་འདྲས་ཡིན་ཙ་ནས། 

10:30 ཨོ། ད་ང་ཚོ་བདེ་བ་ཡོང་ཡག་གི་རྐྱེན། རྒྱུ་རྐྱེན་འདི་འདྲའི་གཅིག་དགོས་ཀི་འདུག། དེའི་རྐྱེན་དེ་ལ་རག་ལས་ཡོད་རེད། དེའི་རྐྱེན་དེའི་དབང་གིས་ཡོང་གིན་ཡོད་རེད།

10:39 དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ང་ཚོས་རྒྱུ་རྐྱེན་འདི་སྒྲུབ་དགོས་འདུག་བྱས་ནས། ཨེ་ནས་སླེབས་ཀི་འདུག་བ། ད་འཐད་པར་སྒྲུབ་པའི་རིགས་པ། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་ཀྱི་རེད། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་རེད། དེ་ང་ཚོ་ལ་དགོས་ཀྱི་འདུག དེ་ང་ཚོ་ལ་དགོས་ཀྱི་མི་འདུག

10:49 དེ་འདྲས་ཡིན་པ་ཡིན་དུས། ཨེ་མ་དགོས་ཡག་དེ་མེད་བ་ཡོང་ཡག་དོན་དག་ལ་ཁོ་ཕན་ཚུན་ལྟོས་པའི་ཨེ་ཕྱོགས་དེ་གས་དེ་ལ་བསམ་བློ་གཏང་ཡག་གཅིག།

10:56 ཨེ་ད་ག་ནང་་བཞིན་གྱི་ཕ་གིའི་ཨེ་ག་རེ་ཟེར་བ་དགོས། ད་བྱ་བ་བྱེད་པ་ཟེར་ན་ཁོ་རང་གཅིག་གིས་གཅིག་གིས་ད་ནུས་པ་མི་འདྲ་བ་ཡོད་པ་དེ་གས་དེ་ཤེས་ཡག་གཅིག་དང་།

11:06 ཨེ་ནས་དེའི་རྒྱུ་འབྲས་ཀྱི་འགྲོ་སྟངས་དེ་ཤེས་པའི་ཐོག་ནས། ཨེ་ནས་ང་ཚོ་ལ་ཡ་ཕན་པའི་དངོས་པོ་དང་དུ་བླངས། མི་འདོད་པའི་དངོས་པོ་དེ་ཨེ་ནས་ཉུང་དུ་བཏང་།

11:16ཕར་འཕྲི། འཕྲི་ཡག་ཤེས་ཀྱི་རེད་བ། ཉུང་དུ་གཏང་ཡག་ད་དེ་འདྲའི་བྱེད་ཡག་རེད་འདུག་བ།སེ་ད་ཆོས་ཟེར་ཡས་འདི་སྒང་ནས། སངས་རྒྱས་པའི་ཆོས།

11:25 ད་དེའི་སྒང་ནས་བཤད་བསྡད་ཀི་རེད་བ། བཅོམ་ལྡན་འདས་ཁོ་རང་ཡང་རིགས་པ་བཞིའི་འགྲོ་སྟངས་འདིའི་ཐོག་ནས་བཅོམ་འདས་ཁོ་རང་གིས་ཨེ་ནས།

11:34 ཁོ་རང་གི་བསམ་བློའི་ནང་ལ་ཡ་ད་འགྱུར་བ་གཏོང་ཡག་གཅིག། གསལ་རིག་གི་ཤེས་པ་གཅིག་ཡོད་པ་བྱས། གསལ་རིག་གི་ཤེས་པ་ལ་འགལ་ཟླ་མང་པོ་ཡོད་པ་བྱས།

11:44 མི་མཐུན་པ་མང་པོ་ཡོད་པ་བྱས། མི་མཐུན་པ་དེའི་ནང་ལོག་ལ་འགལ་ཟླ་མང་པོ་ཡོད་པ་བྱས། སེ་ཕྱི་དངོས་པོ་ལ་ཡ་འགལ་ཟླ་ཡོད་ཙང་འགྱུར་བ་འགྲོ་གི་རེད་བ། འགལ་ཟླ་མེད་ན་འགྱུར་བ་འགྲོ་གི་མ་རེད་བ། 

11:52 སེ་དེ་འདྲས་ཡིན་པས། དེ་ནང་བཞིན་ཤེས་པ་ལ་ཆ་བཞག་ནས། འགལ་ཟླ་ཡོད་ཙང་ཤེས་པ་འགྱུར་བ་འགྲོ་གི་ཡོད་པ་མ་གཏོགས།

12:01 འགལ་ཟླ་མེད་ན་ཤེས་པ་འགྱུར་བ་འགྲོ་ཡག་མི་འདུག་ཨ། ཨེ་ཤེས་པའི་ནང་འགལ་ཟླ་ག་འདྲས་རེད་ཟེར་ལབ་ན་ཤེས་པའི་ཕྱི་ལོག་གི་གཟུགས་ཅན་ཆོས་ཀྱི་འགལ་ཟླ་དེ་ཁོ་རང་།

12:10 ནུས་པ་དེ་འདྲའི་མང་པོ་ཞིག་ཐོག་ནས་བཤད་ཐུབ་ཀྱི་རེད། དེ་འདྲའི་ཐོག་ནས་ཡོང་གི་རེད། དཔེར་ན། ཚ་གྲང་འགལ་ཟླ་རེད། ཚ་གྲང་འགལ་ཟླ་དེ་ཁོ་རྒྱུན་གྱི་འགལ་བ་རེད། རྒྱུན་གཅིག་ཏུ་གནས་མི་ཐུབ་པ་གཅིག།

12:19 འགལ་བ་ཡིན་པ་རེད། སྣང་བ་དང་མུན་པ་འགལ་བ་རེད། ཁོ་རང་དུས་གཅིག་ཏུ་གནས་མི་ཐུབ་ཡག་གཅིག་གིས་འགལ་བ་སླེབས་ཡོང་གི་འདུག་བ། ད།

12:28 ནང་ཤེས་པ་ལ་ཡ་ཁོ་རང་གཟུགས་ཅན་གྱི་ཆོས་ནང་བཞིན་བྱས་ནས་འགལ་བ་བརྩི་ས་ཡོད་མ་རེད་དེ། ཡིན་ནས་ཁོ་རང་འཛིན་སྟངས་འགལ་བ་ཆགས་ཀི་འདུག་བ། གཅིག་གིས་དཔེར་ན་ཡག་པོ་རེད་ཟེར་འཛིན་བསྡད་ཡག་བློ་དེ་དང༌།

12:38 དེ་སྡུག་པོ་རེད་ཟེར་ཡག་འཛིན་བསྡད་པའི་བློ་གཉིས་པོ་དེ་འཛིན་སྟངས་འགལ་བ་རེད་བ། ཡུན་དམིགས་པ་གཅིག་ལ་དམིགས་ནས་དུས་གཅིག་ལ་འདི་ཡག་པོ་རེད། འདི་སྡུག་ཅག་རེད་ཟེར་བསྡད་ཡག་གཉིས་པོ་དེ་འགལ་བ་རེད་འདུག་བ།

12:48 ད་ཚུར་བསམ་བློ་གཏོང་ཡོང་དུས་ཙམ་ནས། ཉམ་ཐག་པའི་སེམས་ཅན་ལ་དམིགས་ནས་དེ་དང་སྙིང་རྗེ་བསམ་པའི་བརྩེ་བ་དེ་དང༌།

12:58 སེམས་ཅན་དེ་ལ་དམིགས་ནས་དེ་སྡུག་བ་གཅིག་བྱུང་ན་བསམ་པའི་སྡང་བའི་སེམས་གཉིས་པོ་དེ་འཛིན་སྟངས་འགལ་བ་རེད་འདུག་ག། བྱས་ཙང་དངོས་པོ་ལ་ཡ། 

13:07 གཞི་གཞི་གཞི་གཞི་ག་རེ་ཟེར་བ་རེད། གཞི་དངོས་པོའི་གནས་ཚུལ་ཁོ་རང་ལ་ཡ་ནང་ཤེས་པ་ལ་འགལ་ཟླ་མང་པོ་འདུག་བ། འགལ་ཟླ་ཡོད་པ་ཡིན་དུས་ཙ་ནས། དཔེར་ན།

13:16 ཕྱིའི་འགལ་ཟླ། དཔེར་ན། ཚ་བའི་རེག་པ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན་གྲང་བའི་རེག་པ་ཉུང་དུ་ཉུང་དུ་འགྲོ་བསྡད་ཡག སྣང་བ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན་མུན་པ་ཤུགས་ཆུང་དུ་་ཆུང་དུ་འགྲོ་བསྡད་ཡས།

13:24 སྣང་བ་ཇེ་ཉུང་དུ་ཕྱིན་པའི་ཚོད་ཀྱིས་མུན་པ་ཤུགས་ཆེ་རུ་ཆེ་རུ་འགྲོ་བསྡད་ཡག་དེ་ནང་བཞིན་བྱས་ནས་ནང་ཤེས་པ་ལ་འགལ་བ་ཡིན་བསྡད་མཁན་བློ་གཉིས། ཨེ་དམིགས་པ།

13:33 སེམས་ཅན་ལ་དམིགས་ནས་སྡང་བའི་སེམས་དེ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན། དེ་ལ་དམིགས་པའི་བྱམས་པའི་སེམས་དེ་ཤུགས་ཡོང་ཐུབ་ཡག་་མེད་བསྡད་མཁན།

13:42 སེམས་ཅན་དེ་ལ་དམིགས་ནས་བྱམས་པའི་བློ་ཤུགས་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན། དེ་ལ་དམིགས་ནས་ཁོང་ཁྲོའི་བློ་ཡོང་མི་ཐུབ་པ་ཡག་ཁོ་ཆགས་འདུག་བ། བྱས་ཙང་ཁ་ད་དངོས་ཡོད་གནས་ཚུལ་གྱིས།

13:51ཁོང་གང་ལྟར་འགལ་བ་ཡོད་བསྡད་མཁན་གི་འགྱུར་བ་ད་ཆོས་ཉིད་ཀྱི་རིགས་པ། ལྟོས་པའི་རིགས་པ། བྱ་བ་བྱས་པའི་རིགས་པ་དེ་དག་གི

14:00 འོག་ནས་འཐད་སྒྲུབ་ཀི་རིགས་པ། ད་བདེ་བ་འདོད་པ་དང༌། སྡུག་བསྔལ་མི་འདོད་པ་དེ་གཞི་ལ་བཞག།ད་བདེ་བ་འདོད་པ་དང༌། སྡུག་བསྔལ་མི་འདོད་པ་རང་གིས་ངང་ལ་ཡོད་རེད། འགྲེལ་བཤད་ག་གས་བརྒྱབ་དགོས་ཡག་ཡོད་མ་རེད། 

14:09དེ་གཞི་ལ་བཞག་པའི་ཐོག་ལ་ད་བདེ་སྡུག་ལ་འབྲེལ་བ་ཡོད་བསྡད་མཁན་ཕྱི་ལོག་གི་དངོས་པོ་ཡིན་ནས་འདྲ། ནང་གི་ཤེས་པ་ཡིན་ནས་འདྲ།

14:17གཉིས་ཀ་ལོག་ནང་ལ་བདེ་སྐྱིད་ཡོང་ཡག་གི་མཐུན་རྐྱེན་དེ་བསྒྲུབ་ཡག་གཅིག་དང་། བདེ་སྐྱིད་ལ་གནོད་མཁན་གྱི་སྡུག་བསྔལ་སྟེར་མཁན་གྱི་འགལ་རྐྱེན་དེ་གས་དེ། 

14:26 ཉུང་དུ་གཏང་ཡག་ད་དེ་འོས་པ་དང༌། ཐོབ་ཐང་ཡོད་པ་རེད་བ་ང་ཚོར་ལ་ཡ། སོ་སེ་དེ་འདྲས་ཡིིན་དུས་བཅོམ་ལྡན་འདས་ཁོ་རང་ཨེ་རིགས་པ་བཞིའི་སྒོ་ནས་འདུག་སེ་ད་དགོངས་པ་བཞེས་ནས།

14:35 ཨེ་ནས་བསམ་མནོ་བསམ་བློར་འགྱུར་བ་ག་ལས་ག་ལས་ཐེབས་བྱས་འདུག་སེ་བྱས་ནས། སྐྱོན་ཀུན་ཟད་ཡོན་ཏན་ཀུན་ལྡན་ཟེར་ཡག་ད་དེ་ཡང་གཤམ་ལ་མར་ཐོན་ཡོང་གི་རེད། ད་དྲི་མ་ཟད་ཐུབ་ཡག་ཡོད་དང་མེད་ཟེར་བསྡད་དེ་དཔེར་རྙོག་དྲ་ཚ་པོ་རེད་བ།

14:45 ཆགས་སྡང་ཆུང་དུ་འགྲོ་ཡག་ང་རང་ཚོའི་མྱོང་བས་ཤེས་ཐུབ་འདུག། ང་ཚོའི་ཐ་མལ་པའི་མྱོང་བ་དེ་འདྲའི་གཅིག་་འོག་ནས་ཤེས་ཐུབ་ཡག་རེད། ཡིན་ནས་ཆགས་སྡང་གཏན་དུ་ཟད་ཐུབ་དང་མི་ཐུབ་ཟེར་མཁན་དེ་ད་བསམ་བློ་ཞེ་བོ་གཅིག་བཏང་ན་མ་གཏོགས།

14:55 ལམ་སངས་ཤེས་ཐུབ་ཡག་ཁག་པོ་འདུག་བ། སེ་ད་གང་ལྟར་ཡང་སྙིང་སངས་རྒྱས་བཅོམ་ལྡན་འདས་རང་ཉིད་ག་ལས་ག་ལས་་ལ་ཡ་ཨེ་ནས་ཁོ་སྐྱོན་དེ་གས་དེ་ཉུང་དུ་ཉུང་དུ་ཕྱིིན།

15:04 ཡོན་ཏན་དེ་གས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་གྱིས་འདུག་སེ་བྱས་ནས།ཨེ་ནས་གང་ལྟར་སྤངས་རྟོགས་མཐར་ཕྱིན་པ་གཅིག་ཆགས་ཡག་རེད་མ་གཏོགས། ག་གས་མ་བྱས་པར་དང་པོ་ནས་བྱུང་བསྡད་པ་གཅིག་གཅིག་ཡོད་མ་རེད་བ། ད་དེ་སངས་རྒྱས་པའི་འགྲོ་སྟངས་རེད་གདའ།

15:14 སངས་རྒྱས་པའི་ཞུ་སྟངས་དེ། ད་འཇིག་རྟེན་བཀོད་པ་པོ་འདོད་མཁན་གྱི་དཀོན་མཆོག་ཟེར་ལབ་ཡིན་ན་གནས་ཚུལ་ཁ་ཁ་རེད། ཡེ་གདོད་མ་ནས་ཨེ་ནས་ཨེ་སངས་རྒྱས་ཟེར་ཡག་གཅིག་ཡོད་བསྡད་པ། དཀོན་མཆོག་ཟེར་ཡག་གཅིག་ཡོད་བསྡད་པ་བཤད་བྱས།

15:24 དེས་ཨེ་ནས་འཇིག་རྟེན་བཀོད་པ་རེད་ཟེར་གྱིས་བཤད་ཀི་ཡོད་རེད་བ། སངས་རྒྱས་པས་ད་དེ་མ་རེད་བ། སོ་སེ་དེ་འདྲས་ཡིན་དུས་ཨང་ལྟ་ངས་བཤད་དགོོས་ཡག་དེ། དེ་འདྲས་ཡིན་དུས།

15:33 སངས་རྒྱས་པའི་ཆོས་ཀྱིས་བརྟག་དཔྱད་བཏང་ནས། ཨེ་ནས་་ཡིན་ལུགས་ཇི་ལྟ་ཇི་སྙེད་ཀྱི་དོན་གང་ཡིན་ནས་ཡིན་ལུགས་གཏན་ལ་ཕབ་ཡག་གཅིག་ཆགས་བསྡད་འདུག་ཟེར།

15:43 ཨེ་ཚན་རིག་པས་ཁོ་ཡིན་ལུགས་གཏན་ལ་ཕབ་ཀྱི་ཡོད་རེད། སེ་དེ་ཡིན་དུས་འགལ་བ་གལ་མི་འདུག་བ། བྱས་ཙང་། འོ།

15:52 ཨེ་དེ་ཡིན་དུས་ད་ཡིན་གཅིག་མིན་གཅིག་ཚན་རིག་པ་ལ་འབྲེལ་བ་བྱས་ན། ཨེ་ནས་འགལ་བ་ག་གས་མི་འདུག་བསམས་ནས་འདུག་སེ་ད་འབྲེལ་བ་བྱས་པ་རེད།

16:00ཡང་མཚམས་མཚམས་ཁ་ཤས་ཚན་རིག་པ་དེ་འདྲས།  ཚན་རིག་པ་ཟེར་ནས་མི་འདུག།ཁ་ཤས་ཀྱིས་སྐད་ཆ་དྲིས་ཀིན། ཨེ་ནས་ངས་ག་རེ་ཟེར་ད་ནང་པས་ཚན་རིག་ལ་ཡ།

16:09 དོ་སྣང་བྱེད་ཡག་དེ་ག་རེ་རེད་ཟེར། ཁ་ཤས་ཡ་མཚར་མཚར་བྱེད་ཀྱིན་འདུག་བ། ཨེ་ནས།  ཨེ་ནང་པས་ Reality

16:19 བདེན་པ་དེ། དངོས་ཡོད་གནས་ཚུལ་ག་རེ་ཡོད་པ་དེ་ང་ཚོས་བཙལ་གྱི་ཡོད་རེད་ཟེར། ཚན་རིག་པས་དངོས་ཡོད་གནས་ཚུལ་བཙལ་གྱི་ཡོད་རེད་ཟེར། ད་བདེན་པ་འཚོལ་བ།

16:28 Reality དེ་ང་ཚོས་འཚོལ་གྱི་ཡོད་པ་རེད་ཟེར། བྱས་ཙང་ག Reality འཚོལ་མཁན་གཅིག་པ་རེད་ཟེར། ཚན་རིག་དང་ནང་པ་གཉིས་ཆ་ལོག་Reality་འཚོལ་མཁན་གཅིག་པ་རེད། 

16:38 དེ་འདྲས་ཡིན་དུས་དེ་འགལ་བ་མི་འདུག་ཟེར་བྱས་ནས་འབྲེལ་བ་བྱེད་དགོས་ཀི་ཟེར། དེ་འདྲས་ཡིན་དུས་ང་ཚོས་དེ་དོ་སྣང་ཡོང་གི་ཡོད་ཟེར་བྱས་ནས།

16:43འོ་དེ་འདྲ་བཤད་ཀྱི་ཡོད། བྱས་ཙང་འགྲོ་སྟངས་དེ་འདྲའི་རེད། འགལ་བ་གལ་མི་འདུག་བ།

16:50

 Done at 12:18 3th of May

2023-05-03 07:25 UTC, Tenzindharten requested changes
00:00ད་ངས་ནམ་རྒྱུན་འོ་དེ་བཤད་བསྡད་[ས་ཀྱི་]ཀིན་ཡོད། ཨེ་ནས་[ནི་ཧེ་་]ཨེ་སངས་རྒྱས་པའི་གཞུང་ནས་ད་གཞི་ལམ་འབྲས་གསུམ་ཞེས་བཤད་ཀིན་[ཀྱི་]ཡོད་པ་[པས་]ཡིན་དུས།

00:08 ཨེ་[ནི]ནས་ད་ལྟ་གཅིག་ཚན་རིག་པ་དང་འབྲེལ་བ་ཡོང་བསྡད་དེ། ཨེ་[འེ་]ལམ་དང་འབྲས་བུའི་གནས་ཚུལ་གྱི་ཨེ་ཐོག་ནས། 

00:18ད་ཨེ་ཚན་རིག་པ་དང་འབྲེལ་བ་བྱེད་[ཡོང་]ཡག་བྱེད་དོན་ཡོད་མ་རེད་ལ་ཨེ་[འེ་]ཡོང་གི་ཡོད་མ་རེད། ད་མིན་ལམ་གྱི་དམིགས་པ་ཕྲ་བའི་མི་རྟག་པ་བཟོ་འདྲ་བོ་[སོགས་]དེ་འདྲའི་དེ་འདྲའི། 

00:27ད་[ཨན]ཨང་ལྟ་ཡང་གཅིག་སླེབས་ཡོང་གི་ཡོད་རེད། ད་དེ་ཁོ[ང་]གཞིའི་གནས་ཚུལ་ཆགས་ཀྱི་རེད་བ་ད་དེའི། [ཡང་།] བྱས་ཙང་ག ད་གཞིའི་[ཡི་]རྣམ་གཞག

00:36[དེ་]དེའི་ཐོག་ནས་ཚན་རིག་པ་ལ་འབྲེལ་བ་ཡོང་བསྡད་ཡག་[ས།] གཞིའི་རྣམ་གཞག་དེ་ལ་ཡང་།[འང༌།] ཨེ་ནས་[ནི་]མཐོང་བ་མངོན་གྱུར། ཅུང་ཟད་ལྐོག་གྱུར།

00:45ག་རེ་ཟེར་ཨེ་ནས་[ནི་]ཤིན་ཏུ་ལྐོག་གྱུར་བཅས་ཡོད་པའི་ནང་ནས་གཙོ་བོ་གཙོ་བོ་མཐོང་བ་མངོན་གྱུར་དང༌། ཨེ་ནས་[ནི་]ཕྲ་བའི་མི་རྟག་པ་ལ་སོགས་པའི་ཅུང་ཟད་ལྐོག་གྱུར་[དེ་]དེ་གས་དེ།

00:54གཞི་རྩ་དེ་གས་དེ་[ག་གི་]ནང་ལོག་ནས་ཚན་རིག་པ་དང་འབྲེལ་བ་ཡོང་བསྡད་ཡག་[ཡས་]དེ་རེད། བྱས། ད་དེ་ལ་དང་པོ་ལ་གཉིས། 

01:03ཡུལ་གྱི་འདོད་ཚུལ་དང་ཡུལ་ཅན་གྱི་འདོད་ཚུལ། སྤྱིར་ཨེ་ནས་[ནི་]གཞི་ཡི་གནས་ཚུལ་དབྱེ་བ་ཕྱེ་ལུགས་ད་འདྲ་མི་འདྲ་[མིན]་ཡོང་གི་རེད་དེ། ཡིན་ནས་[ན་]ད་ཨང་ལྟ། [ཨན་ད་དེ།]

 01:12 ཡུལ་དང་ཡུལ་ཅན་ཟེར་བྱས་ནས་[ཞེས་]དབྱེ་བ་ཕྱེ་བ་དེ་གིས་ཁོ[ང་]གནད་འགག་ཅིག་འདུག་བ། ད་ལམ་བཤད་ཡག་[ཡས་]དེ་གས་དེ་[ག་]གཙོ་བོ་ཡུལ་ཅན་སྒང་ནས་ད་ལམ་བཤད་དགོས་རེད་བ།

01:19 ཨེ་ཡུལ་ཅན་དང་ད་འབྲས་བུ་མཐར་ཐུག་དེ་ཡུལ་ཅན་གྱི་སྟེང་གི་ཨེ་ནས་[ནི་]འགྱུར་བ་བཏང་བྱས། ད་དེ་ལ་བརྟེན་ཁོ[ང་]ད་ཡ་ག་རེ་ཟེར་དགོས་རེད། ལམ་དང་འབྲས་བུའི་གནས་ཚུལ་དེ། [གས་དེ།་ག།]

01:29གཙོ་བོ་དེའི་ཐོག་ནས་བཤད་དགོས་ཡག་ཅིག་[ཡས་]ཡིན་པ་ཡིན་དུས། ཕལ་ཆེར་ཡུལ་དང་ཡུལ་ཅན་ཞེས་དབྱེ་བ་དེ་འདྲས་བསམ་བློ་གཏོང་ཡག་[ཡས་]མིན་འགྲོ། ད་ཡུལ་གྱི་འདོད་ཚུལ་ལ་ལུགས་འདིས་ཤེས་བྱ་ཐམས་ཅད་གཞི་ལྔར་ཨེ་

01:38 འདུས་པར་འདོད་དེ། སྣང་བ་གཟུགས་ཀྱི་གཞི། གཙོ་བོ་སེམས་ཀྱི་གཞི། འཁོར་སེམས་འབྱུང་གི་གཞི། བདེན་པ་མ་ཡིན་པའི་འདུ་བྱེད་ཀྱི་གཞི། འདུས་མ་བྱས་ཀྱི་གཞི་རྣམས་སོ།།

01:46གཞི་ལྔ་པོ་དེ་དག་ཀྱང་དངོས་པོར་འདོད་དེ། ད་ཨེ་གང་ལྟར་ག་རེ་ཟེར་དགོས་རེད། ཡོད་པ་ཞིག་ཡིན་ཕྱིན་ཆད་ལ་ཡ། [ར།]

01:55ཁོ[ང་རད་]བྱས་རང་གཅིག་ད་དོན་བྱེད་པའམ་རང་རང་གིས་གཅིག་དོན་བྱེད་པ་འདྲ་བོ། གཅིག་དོན་བྱེད་ནུས་པ་འདྲ་བོ།དེ་འདྲའི་རང་བཞིན་རྗེན་པ་གཅིག་ད་ཁོ[ང་]ཡོད་དགོས་ཡག་ཡིན་དུས་ཙ[ང་]ནས།

02:04 དོན་བྱེད་པ། དོན་བྱེད་ནུས་པ་དངོས་པོའི་མཚན་ཉིད་བྱས་ནས་ད་དངོས་པོ། ཡོད་པ། ཤེས་བྱ། ཨེ་འོ་ད་འགྲིག་བཞག [དེ་རེད་བཞག་]དངོས་པོ་རྣམས་དོན་གཅིག།

02:14 འདུས་མ་བྱས་ཀྱི་ཆོས་རྣམས་རྟག་པའི་དངོས་པོ་དང༌། དེ་ཕལ་ཆེར་ཨེ་ཨེ་ད་རྒྱུན་གྱི་རྟག།ད་རྒྱུན་གྱི་ཟེར་དགོས་རེད་བས།ད་གང་ལྟར་

02:22 རྟག་ཏུ་གནས་མཁན་གྱི་རྟག་པ་གཅིག་ལ་གོ་དགོས་ཀི་[ཡས་ཡོད་ཡས་]མིན་འགྲོ། ཨེ་བྱས་ནས་འདུ་མ་བྱེད་ཀྱི་ཆོས་རྣམས་རྟག་པའི་དངོས་པོ་དང་གཟུགས་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་ནི་མི་རྟག་པའི་དངོས་པོ་འདོད།



༢༠༢༣་༠༥་༣ ཉིན་བཅོས་ཡོད། 



༢༡ དེ་རེད། ཕྱེད་ཀ་རྗེས་སུ་བསྐུར་ཡོང་།་

2023-05-03 15:04 UTC, Tenzindharten requested changes
09:28 ཕན་ཚུན་འབྲེལ་ནས་ཁོ་ཡོད་བསྡད་པ་ཡིན་དུས་ཙ་ནས། ཕན་ཚུན་ལྟོས་པའི་སྒོ་ནས་ཨེ་ནས་ངོ་བོ་ལ་འགྱུར་བ་འགྲོ་བསྡད་གཅིག་ཡོང་བསྡད་ཡག་འདུག་ཨ།

09:37ཆུ་དང། དཔེར་ན། ག་རེ་ཟེར་དགོས་རེད། དཔེར་ན། དཔེར་ན། དཔེར་ན། མེ་དང་ཆུ་འཐབ་ནས་ཡང་ཁོ་རང་ག་རེ་ཟེར་དགོས་རེད། ཕ་གིའི་རྣམ་པ་འདྲ་བོ་གསར་པ་གཅིག་ཡོང་བསྡད་ཡག་འདྲ་བོ།

09:47 དཔེར་ན་རྫས་མི་འདྲ་བ་གཉིས་བསྡུས་ནས་ཡང་གཅིག་རྣམ་པ་མི་འདྲ་གསར་པ་ཡོང་བསྡད་ཡག་ཡོང་གི་རེད་བ། ད་དེ་ལྟར་ཨེ་ཕན་ཚུན་བསྡུས་ནས་ཡིན་ནས་འདྲ། ཁེར་རྐྱང་ཡིན་ནས་འདྲ།

09:56 ཨེ་དངོས་པོ་གཅིག་གིས་རང་རང་གི་འབྲས་བུ་གསར་པ་སྐྱེས་ཡག་གཅིག་ཡོང་བསྡད་ཀི་འདུག་ཨ། དེ་ལྟོས་པའི་རིགས་པ་ཟེར་ལབ་ཡིན་པ་རེད། འབྲས་བུ་དེ་རྒྱུ་ལ་ལྟོས་པ་རེད་ཟེར།

10:05 འབྲས་བུ་དེ་རྒྱུ་ལ་ལྟོས་པ་། ་འདི་གས་འདི་ཁོ་རང་ལོག་ཁ་རེད།NATURE ལོག་ཁ་བཟོ་འདྲ་བོ་འདུག་བ།NATURE ལོག་ཁ་འདི་ཁས་བླངས་ནས།NATURE་

10:14 དེའི་ཐོག་ནས་རང་བཞིན་ལྷན་སྐྱེས་ཀྱི་ཁྲིམས་བཟོ་འདྲ་བོ་ད་འགྲོ་སྟངས་འདྲ་བོ་གཅིག།ད་དེ་གཞི་ལ་བཞག་པའི་ཐོག་ལ་ཨེ་ནས་འཐད་སྒྲུབ་ཟེར་ཡག་དེ། ད་འཐད་སྒྲུབ་ཟེར་ཡག་དེ་ཨོ།

10:23དེ་ཡིན་ཙང་། དེ་ཡིན་དགོས་རེད། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་རེད། ད་ང་ཚོ་སྡུག་བསྔལ་མི་འདོད་པ་དང༌། བདེ་བ་འདོད་པ་རང་བཞིན་ལྷན་སྐྱེས་རེད་བ་ད། བྱས་ཙང་དེ་འདྲས་ཡིན་ཙ་ནས།

10:30 ཨོ། ད་ང་ཚོ་བདེ་བ་ཡོང་ཡག་གི་རྐྱེན། རྒྱུ་རྐྱེན་འདི་འདྲའི་གཅིག་དགོས་ཀི་འདུག། དེའི་རྐྱེན་དེ་ལ་རག་ལས་ཡོད་རེད། དེའི་རྐྱེན་དེའི་དབང་གིས་ཡོང་གིན་ཡོད་རེད།

10:39 དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ང་ཚོས་རྒྱུ་རྐྱེན་འདི་སྒྲུབ་དགོས་ཀི་འདུག་བྱས་ནས། ཨེ་ནས་སླེབས་ཀི་འདུག་བ། ད་འཐད་པར་སྒྲུབ་པའི་རིགས་པ། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་ཀྱི་རེད། དེ་ཡིན་ཙང་དེ་ཡིན་དགོས་རེད། དེ་ང་ཚོ་ལ་དགོས་ཀྱི་འདུག དེ་ང་ཚོ་ལ་དགོས་ཀྱི་མི་འདུག

10:49 དེ་འདྲས་ཡིན་པ་ཡིན་དུས། ཨེ་མ་དགོས་ཡག་དེ་མེད་བ་ཡོང་ཡག་དོན་དག་ལ་ཁོ་ཕན་ཚུན་ལྟོས་པའི་ཨེ་ཕྱོགས་དེ་གས་དེ་ལ་བསམ་བློ་གཏང་ཡག་གཅིག།

10:56 ཨེ་ད་ག་ནང་་བཞིན་གྱི་ཕ་གིའི་ཨེ་ག་རེ་ཟེར་བ་དགོས། ད་བྱ་བ་བྱེད་པ་ཟེར་ན་ཁོ་རང་གཅིག་གིས་གཅིག་གིས་ད་ནུས་པ་མི་འདྲ་བ་ཡོད་པ་དེ་གས་དེ་ཤེས་ཡག་གཅིག་དང་།

11:06 ཨེ་ནས་དེའི་རྒྱུ་འབྲས་ཀྱི་འགྲོ་སྟངས་དེ་ཤེས་པའི་ཐོག་ནས། ཨེ་ནས་ང་ཚོ་ལ་ཡ་ཕན་པའི་དངོས་པོ་དང་དུ་བླངས། མི་འདོད་པའི་དངོས་པོ་དེ་ཨེ་ནས་ཉུང་དུ་བཏང་།

11:16ཕར་འཕྲི། འཕྲི་ཡག་ཤེས་ཀྱི་རེད་བ། ཉུང་དུ་གཏང་ཡག་ད་དེ་འདྲའི་བྱེད་ཡག་རེད་འདུག་བ།སེ་ད་ཆོས་ཟེར་ཡས་འདི་སྒང་ནས། སངས་རྒྱས་པའི་ཆོས།

11:25 ད་དེའི་སྒང་ནས་བཤད་བསྡད་ཀི་རེད་བ། བཅོམ་ལྡན་འདས་ཁོ་རང་ཡང་རིགས་པ་བཞིའི་འགྲོ་སྟངས་འདིའི་ཐོག་ནས་བཅོམ་འདས་ཁོ་རང་གིས་ཨེ་ནས།

11:34 ཁོ་རང་གི་བསམ་བློའི་ནང་ལ་ཡ་ད་འགྱུར་བ་གཏོང་ཡག་གཅིག། གསལ་རིག་གི་ཤེས་པ་གཅིག་ཡོད་པ་བྱས། གསལ་རིག་གི་ཤེས་པ་ལ་འགལ་ཟླ་མང་པོ་ཡོད་པ་བྱས།

11:44 མི་མཐུན་པ་མང་པོ་ཡོད་པ་བྱས། མི་མཐུན་པ་དེའི་ནང་ལོག་ལ་འགལ་ཟླ་མང་པོ་ཡོད་པ་བྱས། སེ་ཕྱི་དངོས་པོ་ལ་ཡ་འགལ་ཟླ་ཡོད་ཙང་འགྱུར་བ་འགྲོ་གི་རེད་བ། འགལ་ཟླ་མེད་ན་འགྱུར་བ་འགྲོ་གི་མ་རེད་བ།

11:52 སེ་དེ་འདྲས་ཡིན་པས། དེ་ནང་བཞིན་ཤེས་པ་ལ་ཆ་བཞག་ནས། འགལ་ཟླ་ཡོད་ཙང་ཤེས་པ་འགྱུར་བ་འགྲོ་གི་ཡོད་པ་མ་གཏོགས།

12:01 འགལ་ཟླ་མེད་ན་ཤེས་པ་འགྱུར་བ་འགྲོ་ཡག་མི་འདུག་ཨ། ཨེ་ཤེས་པའི་ནང་འགལ་ཟླ་ག་འདྲས་རེད་ཟེར་ལབ་ན་ཤེས་པའི་ཕྱི་ལོག་གི་གཟུགས་ཅན་ཆོས་ཀྱི་འགལ་ཟླ་དེ་ཁོ་རང་།

12:10 ནུས་པ་དེ་འདྲའི་མང་པོ་ཞིག་ཐོག་ནས་བཤད་ཐུབ་ཀྱི་རེད། དེ་འདྲའི་ཐོག་ནས་ཡོང་གི་རེད། དཔེར་ན། ཚ་གྲང་འགལ་ཟླ་རེད། ཚ་གྲང་འགལ་ཟླ་དེ་ཁོ་རྒྱུན་གྱི་འགལ་བ་རེད། རྒྱུན་གཅིག་ཏུ་གནས་མི་ཐུབ་པ་གཅིག།

12:19 འགལ་བ་ཡིན་པ་རེད། སྣང་བ་དང་མུན་པ་འགལ་བ་རེད། ཁོ་རང་དུས་གཅིག་ཏུ་གནས་མི་ཐུབ་ཡག་གཅིག་གིས་འགལ་བ་སླེབས་ཡོང་གི་འདུག་བ། ད།

12:28 ནང་ཤེས་པ་ལ་ཡ་ཁོ་གཟུགས་ཅན་གྱི་ཆོས་ནང་བཞིན་བྱས་ནས་འགལ་བ་བརྩི་ས་ཡོད་མ་རེད་དེ། ཡིན་ནས་ཁོ་རང་འཛིན་སྟངས་འགལ་བ་ཆགས་ཀི་འདུག་བ། གཅིག་གིས་དཔེར་ན་ཡག་པོ་རེད་ཟེར་འཛིན་བསྡད་ཡག་བློ་དེ་དང༌།

12:38 དེ་སྡུག་པོ་རེད་ཟེར་ཡག་འཛིན་བསྡད་པའི་བློ་གཉིས་པོ་དེ་འཛིན་སྟངས་འགལ་བ་རེད་བ། ཡུན་དམིགས་པ་གཅིག་ལ་དམིགས་ནས་དུས་གཅིག་ལ་འདི་ཡག་པོ་རེད། འདི་སྡུག་ཅག་རེད་ཟེར་བསྡད་ཡག་གཉིས་པོ་དེ་འགལ་བ་རེད་འདུག་བ།

12:48 ད་ཚུར་བསམ་བློ་གཏོང་ཡོང་དུས་ཙམ་ནས། ཉམ་ཐག་པའི་སེམས་ཅན་ལ་དམིགས་ནས་དེ་དང་སྙིང་རྗེ་བསམ་པའི་བརྩེ་བ་དེ་དང༌།

12:58 སེམས་ཅན་དེ་ལ་དམིགས་ནས་དེ་སྡུག་བ་གཅིག་བྱུང་ན་བསམ་པའི་སྡང་བའི་སེམས་གཉིས་པོ་དེ་འཛིན་སྟངས་འགལ་བ་རེད་འདུག་ག། བྱས་ཙང་དངོས་པོ་ལ་ཡ།

13:07 གཞི་གཞི་གཞི་གཞི་ག་རེ་ཟེར་བ་རེད། གཞི་དངོས་པོའི་གནས་ཚུལ་ཁོ་རང་ལ་ཡ་ནང་ཤེས་པ་ལ་འགལ་ཟླ་མང་པོ་འདུག་བ། འགལ་ཟླ་ཡོད་པ་ཡིན་དུས་ཙ་ནས། དཔེར་ན།

13:16 ཕྱིའི་འགལ་ཟླ། དཔེར་ན། ཚ་བའི་རེག་པ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན་གྲང་བའི་རེག་པ་ཉུང་དུ་ཉུང་དུ་འགྲོ་བསྡད་ཡག སྣང་བ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན་མུན་པ་ཤུགས་ཆུང་དུ་ཆུང་དུ་འགྲོ་བསྡད་ཡག

13:24 སྣང་བ་ཇེ་ཉུང་དུ་ཕྱིན་པའི་ཚོད་ཀྱིས་མུན་པ་ཤུགས་ཆེ་རུ་ཆེ་རུ་འགྲོ་བསྡད་ཡག་དེ་ནང་བཞིན་བྱས་ནས་ནང་ཤེས་པ་ལ་འགལ་བ་ཡིན་བསྡད་མཁན་བློ་གཉིས། ཨེ་དམིགས་པ།

13:33 སེམས་ཅན་ལ་དམིགས་ནས་སྡང་བའི་སེམས་དེ་ཤུགས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན། དེ་ལ་དམིགས་པའི་བྱམས་པའི་སེམས་དེ་ཤུགས་ཡོང་ཐུབ་ཡག་་མེད་བསྡད་མཁན།

13:42 སེམས་ཅན་དེ་ལ་དམིགས་ནས་བྱམས་པའི་བློ་ཤུགས་ཆེ་རུ་ཕྱིན་པ་ཡིན་ན། དེ་ལ་དམིགས་ནས་ཁོང་ཁྲོའི་བློ་ཡོང་མི་ཐུབ་པ་ཡག་ཁོ་ཆགས་འདུག་བ། བྱས་ཙང་ཁ་ད་དངོས་ཡོད་གནས་ཚུལ་གྱིས།

13:51ཁོ་གང་ལྟར་འགལ་བ་ཡོད་བསྡད་མཁན་གི་འགྱུར་བ་ད་ཆོས་ཉིད་ཀྱི་རིགས་པ། ལྟོས་པའི་རིགས་པ། བྱ་བ་བྱས་པའི་རིགས་པ་དེ་དག་གི

14:00 འོག་ནས་འཐད་སྒྲུབ་ཀི་རིགས་པ། ད་བདེ་བ་འདོད་པ་དང༌། སྡུག་བསྔལ་མི་འདོད་པ་དེ་གཞི་ལ་བཞག།ད་བདེ་བ་འདོད་པ་དང༌། སྡུག་བསྔལ་མི་འདོད་པ་རང་གིས་ངང་ལ་ཡོད་རེད། འགྲེལ་བཤད་ག་གས་བརྒྱབ་དགོས་ཡག་ཡོད་མ་རེད།

14:09དེ་གཞི་ལ་བཞག་པའི་ཐོག་ལ་ད་བདེ་སྡུག་ལ་འབྲེལ་བ་ཡོད་བསྡད་མཁན་ཕྱི་ལོག་གི་དངོས་པོ་ཡིན་ནས་འདྲ། ནང་གི་ཤེས་པ་ཡིན་ནས་འདྲ།

14:17 གཉིས་ཀ་ལོག་ནང་ལ་བདེ་སྐྱིད་ཡོང་ཡག་གི་མཐུན་རྐྱེན་དེ་བསྒྲུབ་ཡག་གཅིག་དང་། བདེ་སྐྱིད་ལ་གནོད་མཁན་གྱི་སྡུག་བསྔལ་སྟེར་མཁན་གྱི་འགལ་རྐྱེན་དེ་གས་དེ།

14:26 ཉུང་དུ་གཏང་ཡག་ད་དེ་འོས་པ་དང༌། ཐོབ་ཐང་ཡོད་པ་རེད་བ་ང་ཚོར་ལ་ཡ། སོ་སེ་དེ་འདྲས་ཡིིན་དུས་བཅོམ་ལྡན་འདས་ཁོ་རང་ཨེ་རིགས་པ་བཞིའི་སྒོ་ནས་འདུག་སེ་ད་དགོངས་པ་བཞེས་ནས།

14:35 ཨེ་ནས་བསམ་མནོ་བསམ་བློར་འགྱུར་བ་ག་ལས་ག་ལས་ཐེབས་བྱས་འདུག་སེ་བྱས་ནས། སྐྱོན་ཀུན་ཟད་ཡོན་ཏན་ཀུན་ལྡན་ཟེར་ཡག་ད་དེ་ཡང་གཤམ་ལ་མར་ཐོན་ཡོང་གི་རེད། ད་དྲི་མ་ཟད་ཐུབ་ཡག་ཡོད་དང་མེད་ཟེར་བསྡད་དེ་དཔེར་རྙོག་དྲ་ཚ་པོ་རེད་བ།

14:45 ཆགས་སྡང་ཆུང་དུ་འགྲོ་ཡག་ང་རང་ཚོའི་མྱོང་བས་ཤེས་ཐུབ་འདུག། ང་ཚོའི་ཐ་མལ་པའི་མྱོང་བ་དེ་འདྲའི་གཅིག་འོག་ནས་ཤེས་ཐུབ་ཡག་རེད། ཡིན་ནས་ཆགས་སྡང་གཏན་དུ་ཟད་ཐུབ་དང་མི་ཐུབ་ཟེར་མཁན་དེ་ད་བསམ་བློ་ཞེ་བོ་གཅིག་བཏང་ན་མ་གཏོགས།

14:55 ལམ་སངས་ཤེས་ཐུབ་ཡག་ཁག་པོ་འདུག་བ། སེ་ད་གང་ལྟར་ཡང་སྙིང་སངས་རྒྱས་བཅོམ་ལྡན་འདས་རང་ཉིད་ག་ལས་ག་ལས་་ལ་ཡ་ཨེ་ནས་ཁོ་སྐྱོན་དེ་གས་དེ་ཉུང་དུ་ཉུང་དུ་ཕྱིིན།

15:04 ཡོན་ཏན་དེ་གས་ཆེ་རུ་ཆེ་རུ་ཕྱིན་གྱིས་འདུག་སེ་བྱས་ནས།ཨེ་ནས་གང་ལྟར་སྤངས་རྟོགས་མཐར་ཕྱིན་པ་གཅིག་ཆགས་ཡག་རེད་མ་གཏོགས། ག་གས་མ་བྱས་པར་དང་པོ་ནས་བྱུང་བསྡད་པ་གཅིག་གཅིག་ཡོད་མ་རེད་བ། ད་དེ་སངས་རྒྱས་པའི་འགྲོ་སྟངས་རེད་གདའ།

15:14 སངས་རྒྱས་པའི་ཞུ་སྟངས་དེ། ད་འཇིག་རྟེན་བཀོད་པ་པོ་འདོད་མཁན་གྱི་དཀོན་མཆོག་ཟེར་ལབ་ཡིན་ན་གནས་ཚུལ་ཁ་ཁ་རེད། ཡེ་གདོད་མ་ནས་ཨེ་ནས་ཨེ་སངས་རྒྱས་ཟེར་ཡག་གཅིག་ཡོད་བསྡད་པ། དཀོན་མཆོག་ཟེར་ཡག་གཅིག་ཡོད་བསྡད་པ་བཤད་བྱས།

15:24 དེས་ཨེ་ནས་འཇིག་རྟེན་བཀོད་པ་རེད་ཟེར་གྱིས་བཤད་ཀི་ཡོད་རེད་བ། སངས་རྒྱས་པས་ད་དེ་མ་རེད་བ། སོ་སེ་དེ་འདྲས་ཡིན་དུས་ཨང་ལྟ་ངས་བཤད་དགོོས་ཡག་དེ། དེ་འདྲས་ཡིན་དུས།

15:33 སངས་རྒྱས་པའི་ཆོས་ཀྱིས་བརྟག་དཔྱད་བཏང་ནས། ཨེ་ནས་ཡིན་ལུགས་ཇི་ལྟ་ཇི་སྙེད་ཀྱི་དོན་གང་ཡིན་ནས་ཡིན་ལུགས་གཏན་ལ་ཕབ་ཡག་གཅིག་ཆགས་བསྡད་འདུག་ཟེར།

15:43 ཨེ་ཚན་རིག་པས་ཡིན་ལུགས་གཏན་ལ་ཕབ་ཀྱི་ཡོད་རེད། སེ་དེ་ཡིན་དུས་འགལ་བ་གལ་མི་འདུག་བ། བྱས་ཙང་། འོ།

15:52 ཨེ་དེ་ཡིན་དུས་ད་ཡིན་གཅིག་མིན་གཅིག་ཚན་རིག་པ་ལ་འབྲེལ་བ་བྱས་ན། ཨེ་ནས་འགལ་བ་ག་གས་མི་འདུག་བསམས་ནས་འདུག་སེ་ད་འབྲེལ་བ་བྱས་པ་རེད།

16:00ཡང་མཚམས་མཚམས་ཁ་ཤས་ཚན་རིག་པ་དེ་འདྲས། ཚན་རིག་པ་ཟེར་ནས་མི་འདུག།ཁ་ཤས་ཀྱིས་སྐད་ཆ་དྲིས་ཀིན། ཨེ་ནས་ངས་ག་རེ་ཟེར་ད་ནང་པས་ཚན་རིག་ལ་ཡ།

16:09 དོ་སྣང་བྱེད་ཡག་དེ་ག་རེ་རེད་ཟེར། ཁ་ཤས་ཡ་མཚར་མཚར་བྱེད་ཀྱིན་འདུག་བ། ཨེ་ནས། ཨེ་ནང་པས་ Reality

16:19 བདེན་པ་དེ། དངོས་ཡོད་གནས་ཚུལ་ག་རེ་ཡོད་པ་དེ་ང་ཚོས་བཙལ་གྱི་ཡོད་རེད་ཟེར། ཚན་རིག་པས་དངོས་ཡོད་གནས་ཚུལ་བཙལ་གྱི་ཡོད་རེད་ཟེར། ད་བདེན་པ་འཚོལ་བ།

16:28 Reality དེ་ང་ཚོས་འཚོལ་གྱི་ཡོད་པ་རེད་ཟེར། བྱས་ཙང་ག Reality འཚོལ་མཁན་གཅིག་པ་རེད་ཟེར། ཚན་རིག་དང་ནང་པ་གཉིས་ཆ་ལོག་Reality་འཚོལ་མཁན་གཅིག་པ་རེད།

16:38 དེ་འདྲས་ཡིན་དུས་དེ་འགལ་བ་མི་འདུག་ཟེར་བྱས་ནས་འབྲེལ་བ་བྱེད་དགོས་ཀི་ཟེར། དེ་འདྲས་ཡིན་དུས་ང་ཚོས་དེ་དོ་སྣང་ཡོང་གི་ཡོད་ཟེར་བྱས་ནས།

16:43འོ་དེ་འདྲ་བཤད་ཀྱི་ཡོད། བྱས་ཙང་། འགྲོ་སྟངས་དེ་འདྲའི་རེད། འགལ་བ་གལ་མི་འདུག་བ།

16:50

Done at 12:18 3th of May


༢༠༢༣་༠༥་༣ ད་རྦད་དེ་འགྲིག་གདའ། ཚང་མ་བསྒྲིགས་ནས་ཐད་ཀར་ཁོང་ཚོར་གཏོང་རོགས།

2023-05-04 11:17 UTC, Tenzindharten requested changes
02:32 དངོས་པོ་ལ་རྫས་གྲུབ་ཀྱིས་ཁྱབ་ཀྱང་། རྫས་ཡོད་ཀྱིས་མ་ཁྱབ་སྟེ། དོན་དམ་བདེན་པ་དང༌། རྫས་ཡོད་དོན་གཅིག [སོ་]སེ་ད་རྫས་གྲུབ་དང་རྫས་ཡོད། གྲུབ་པ་དང་།

02:40 ཡོད་པ་གཉིས་པོ་འདི་སྤྱིར་བཏང་ད་ཚིག་དེ། ཨེ་ཁོ[ང]་གཅིག་པ་འདྲ་བོ་ཆགས་ཀྱི་ཡོད་རེད་དེ། ཡིན་ནས་[ན་]ད་[ཨན་]ཨང་ལྟ་[ད་]དེ་རྫས་ཟེར་ཡག་[ས་]ཚིག་དེ་དང་འབྲེལ་ནས་ཡོང་དུས་ཙ[ང]་ནས་ཁོ[ང་]གོ་བ་མི་འདྲ་གཅིག། གོ་བ་ལྷག་པོ་གཅིག།

02:50 ད་ཕ་གིའི་[ཕར་གི་]ག་རེ་ཟེར་དགོས་རེད། ཨེ་ད་ག་རེ[་རེད་]ཟེར་དགོས་རེད། གོ་བ་[འདྲ་བ་]གཅིག། མི་འདྲ་བ་གཅིག། ཨེ་ནས་[ནི]་ཁོ[ང་]ད་ག་རེ་ཟེར་དགོས་རེད། གཏན་འབེབས་ཟེར་དགོས་རེད་བས།

02:59གོ་བ་མི་འདྲ་གཅིག་སྤྲད་ཡག་[ཡས་]གཅིག་དགོངས་པ་བཞེས་ནས་རྫས་གྲུབ་དང་རྫས་ཡོད་ལ་ཁྱད་པར་ཕྱེ། ཨེ་དོན་དམ་བདེན་པ་དང་། དོན་དམ་བདེན་པ་དང་རྫས་ཡོད་དོན་གཅིག 

03:09 ཀུན་རྫོབ་བདེན་པ་དང༌། བཏགས་ཡོད་དོན་གཅིག་ཏུ་འདོད་པའི་ཕྱིར།  བཏགས་ཡོད་དེ་རྫས་གྲུབ་རེད་དེ་རྫས་ཡོད་མ་རེད་གསུངས་བ་རེད། ད

03:18ཨེ་དེ་ལ་དབྱེ་ན[་ཡོད་པས]་བདེན་པ་གཉིས་སུ་དབྱེ་བ་དང༌། ཟག་བཅས་ཟག་མེད་གཉིས་སུ་དབྱེ་བ་དང༌། འཕྲོས་དོན་གཞན་བསྟན་པའོ།། དང་པོ་ནི་[ནས་]ད་འོ་བདེན་གཉིས་བཤད་བསྡད་ཡག་[ཡས་]དེ།

03:27 ཕྱི་པ་ཚོས་[ཀྱང་]བདེན་གཉིས་བཤད་ཀྱི་ཡོད་རེད་ལ། ད་ནང་པའི་གྲུབ་མཐའ་ཡོངས་རྫོགས་ལོག་གིས་[ཀྱིས་]བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་དེ་གསུང་གི་ཡོད། ད་བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་གསུང་ཡག་[ཡས་]དེ་སྣང་ཚུལ་དང་གནས་ཚུལ་གྱི་ཐོག་ནས།

03:35 ཕལ་ཆེར་ཕྲན་བུ་ཕྲན་[མི་]འདྲ་བཤད་ཆོག་གི་མེད་འགྲོ་བསམ་གྱིན། [ས།སེ་་་པོ།]ད་དེ་ལ་[ཅ་ལག་]བཅོམ་པའམ་[འང་]བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ན། རང་འཛིན་གྱི་བློ་འདོར་དུ་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ། 

03:45 ཀུན་རྫོབ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི། རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུའོ་ཟེར། ཨེ། 

03:50 གང་ལ་བཅོམ་དང་བློ་ཡིས་གཞན། །བསལ་ན་དེ་བློ་མི་འཇུག་པ། ། བུམ་ཆུ་བཞིན་དུ་ཀུན་རྫོབ་ཏུ། ། ཡོད་དེ། [དོན་དམ་ཡོད་གཞན་ནོ། ། ]གསུངས་བསྡད་ཡག ད་མངོན་པ་མཛོད་ནང་གསུང་བསྡད་ཡག་དེ་ཡིན་པ་རེད། 

 [དངོས་པའི་མཛོད་ནང་ལོག་གསུངས་བསྡད་དེ་ཡིན་པ་རེད།]

03:59ཚད་གཞི་རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུ་ཡིན་ཏེ་ཟེར། རྫ་བུམ་ཐོ་བས་བཅོམ་པ་ན་རྫ་བུམ་དུ་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར་དང༌། 

04:05ཨེ་ཕྲེང་བ་ཟེར་ལབ་དུས། ཕྲེང་རྡོག་མང་པོ་ཚུར་ག་རེ་ཟེར་དགོས། ད་ཕྲེང་ཐག་ལ་ཕྲེང་ཐག་ལ་རྒྱུས་[བརྒྱུད་]བྱས་ཨེ་ནས་དེ་འདྲས་གཅིག་ལ་ཡ། ད་ཕྲེང་བ་ཟེར་ཐ་སྙད་ཆགས་པ་ཐ་སྙད་ཆགས་པ་ཡིན་དུས་ཙ[ང]་ནས། 

04:15 དེ་ཨེ་རྡོག་པོ་སོ་སོ[ར་]ནས་བསལ་བ་ན་ཕྲེང་བར་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར། ཡང༌བཅོམ་པའམ་བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ལ།

04:22 བསལ་བ་ན་རང་འཛིན་གྱི་བློ་འདོར་དུ་མི་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ། དོན་དམ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི་རྡུལ་ཕྲན་ཕྱོགས་ཀྱི་ཆ་མེད་དང༌། ཤེས་པ་སྐད་ཅིག་ཆ་མེད་དང༌འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ལྟ་བུ་ཡིན་ཏེ།

04:32 ད་མཛོད་ཀྱི་ལུགས་དེ་གསུངས། རྗེས་ནས་ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌། ཨེ་ཤེས་པ་སྐད་ཅིག་ཆ་མེད། 

04:41ཨེ་ཆ་བཞག་པ་ཡིན་ན། ད་དེ་ཨེ་ནས་[ནི་]དེ་ནས་ཕར་ཁོ[ང་]བསལ་ཡག་[ཡས་]མེད་བསྡད་པ་རེད། ད་ཁོ[ང་]ཆ་ཕྲ་ཤོས་ཆགས།

04:48 བྱས་ཙང་ག དེ་ནས་ཕར་བསལ་བ་ཡིན་ན། ཨེ་ནས་ཁོ[ང]་རང་འཛིན་གྱི་བློ་ཁོ[ང་]རང་འཛིན་གྱི་བློ་ཟེར་དགོས་རེད་བས།ད་གང་ལྟར་ཤེས་པ་དང་ཁོ་ཨེ་ནས། [ང་།]

04:58རྫས་ཀྱི་རང་བཞིན་ཁོ[ང་]དེ་བརླག་འགྲོ་མཁན་[ངང་]གཅིག[ང་]ཆགས་འདུག་བ། ད་ཁོ[ང་]ཇི་སྲིད་གནས་གནས་བར་དུ་ཨེ་ནས་[ནི་]ག[ང]་དུས་ཡིན་ནས། དེ་གཟུགས་དེ་ཕྲ་ཤོས་དེ་རེད་བསམ་པ[འི]་གཅིག་རང་འཛིན་གྱི་བློ་[དེ་མི་]དོར་གི་[འདོར་ཀྱི་]མི་འདུག་བ།

05:07འོ་ད་བུམ་པ་ལྟ་བུ་རགས་པ་གཅིག་ཡིན་དུས་ཙ[ང་]ནས་ཁོ[ང་]ཕར་བཅོམ་པའམ་བློས་བསལ་ན་ཨེ་ནས་[ནི]་ཨེ་རང་འཛིན་གྱི་བློ་དོར་གྱི་ཡོད་རེད།

05:15ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌ཤེས་པ་སྐད་ཅིག་ཆ་མེད་ཟེར་ཡག་དེ་གས་དེ་[ཡས་་དེ་དེ་ག་དེ་]ཨེ་རང་འཛིན་གྱི་བློ་དེ་[མི་]དོར་གི་[ཀྱི་]མི་འདུག་ཟེར། དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ[ང]་ནས་དེ་དམ་བདེན་པ་རེད་ཅེས་དེ་འདྲའི་བཤད་ཡོང་གི་རེད། [པ་རེད།]

༢༠༢༣་༠༥་༤ འདིའི་བར་ཚར་ཡོད།  ཚུར་སྐུར་དུས་མཉམ་དུ་བཏང་ན་འགྲིག་གི་རེད་བ།

2023-05-07 03:25 UTC, Tenzindharten requested changes
02:32 དངོས་པོ་ལ་རྫས་གྲུབ་ཀྱིས་ཁྱབ་ཀྱང་། རྫས་ཡོད་ཀྱིས་མ་ཁྱབ་སྟེ། དོན་དམ་བདེན་པ་དང༌། རྫས་ཡོད་དོན་གཅིག [སོ་]སེ་ད་རྫས་གྲུབ་དང་རྫས་ཡོད། གྲུབ་པ་དང་།

02:40 ཡོད་པ་གཉིས་པོ་འདི་སྤྱིར་བཏང་ད་ཚིག་དེ། ཨེ་ཁོ[ང]་གཅིག་པ་འདྲ་བོ་ཆགས་ཀྱི་ཡོད་རེད་དེ། ཡིན་ནས་[ན་]ད་[ཨན་]ཨང་ལྟ་[ད་]དེ་རྫས་ཟེར་ཡག་[ས་]ཚིག་དེ་དང་འབྲེལ་ནས་ཡོང་དུས་ཙ[ང]་ནས་ཁོ[ང་]གོ་བ་མི་འདྲ་གཅིག། གོ་བ་ལྷག་པོ་གཅིག།

02:50 ད་ཕ་གིའི་[ཕར་གི་]ག་རེ་ཟེར་དགོས་རེད། ཨེ་ད་ག་རེ[་རེད་]ཟེར་དགོས་རེད། གོ་བ་[འདྲ་བ་]གཅིག། མི་འདྲ་བ་གཅིག། ཨེ་ནས་[ནི]་ཁོ[ང་]ད་ག་རེ་ཟེར་དགོས་རེད། གཏན་འབེབས་ཟེར་དགོས་རེད་བས།

02:59གོ་བ་མི་འདྲ་གཅིག་སྤྲད་ཡག་[ཡས་]གཅིག་དགོངས་པ་བཞེས་ནས་རྫས་གྲུབ་དང་རྫས་ཡོད་ལ་ཁྱད་པར་ཕྱེ། ཨེ་དོན་དམ་བདེན་པ་དང་། དོན་དམ་བདེན་པ་དང་རྫས་ཡོད་དོན་གཅིག 

03:09 ཀུན་རྫོབ་བདེན་པ་དང༌། བཏགས་ཡོད་དོན་གཅིག་ཏུ་འདོད་པའི་ཕྱིར།  བཏགས་ཡོད་དེ་རྫས་གྲུབ་རེད་དེ་རྫས་ཡོད་མ་རེད་གསུངས་བ་རེད། ད

03:18ཨེ་དེ་ལ་དབྱེ་ན[་ཡོད་པས]་བདེན་པ་གཉིས་སུ་དབྱེ་བ་དང༌། ཟག་བཅས་ཟག་མེད་གཉིས་སུ་དབྱེ་བ་དང༌། འཕྲོས་དོན་གཞན་བསྟན་པའོ།། དང་པོ་ནི་[ནས་]ད་འོ་བདེན་གཉིས་བཤད་བསྡད་ཡག་[ཡས་]དེ།

03:27 ཕྱི་པ་ཚོས་[ཀྱང་]བདེན་གཉིས་བཤད་ཀྱི་ཡོད་རེད་ལ། ད་ནང་པའི་གྲུབ་མཐའ་ཡོངས་རྫོགས་ལོག་གིས་[ཀྱིས་]བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་དེ་གསུང་གི་ཡོད། ད་བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་གསུང་ཡག་[ཡས་]དེ་སྣང་ཚུལ་དང་གནས་ཚུལ་གྱི་ཐོག་ནས།

03:35 ཕལ་ཆེར་ཕྲན་བུ་ཕྲན་[མི་]འདྲ་བཤད་ཆོག་གི་མེད་འགྲོ་བསམ་གྱིན། [ས།སེ་་་པོ།]ད་དེ་ལ་[ཅ་ལག་]བཅོམ་པའམ་[འང་]བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ན། རང་འཛིན་གྱི་བློ་འདོར་དུ་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ། 

03:45 ཀུན་རྫོབ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི། རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུའོ་ཟེར། ཨེ། 

03:50 གང་ལ་བཅོམ་དང་བློ་ཡིས་གཞན། །བསལ་ན་དེ་བློ་མི་འཇུག་པ། ། བུམ་ཆུ་བཞིན་དུ་ཀུན་རྫོབ་ཏུ། ། ཡོད་དེ། [དོན་དམ་ཡོད་གཞན་ནོ། ། ]གསུངས་བསྡད་ཡག ད་མངོན་པ་མཛོད་ནང་གསུང་བསྡད་ཡག་དེ་ཡིན་པ་རེད། 

 [དངོས་པའི་མཛོད་ནང་ལོག་གསུངས་བསྡད་དེ་ཡིན་པ་རེད།]

03:59ཚད་གཞི་རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུ་ཡིན་ཏེ་ཟེར། རྫ་བུམ་ཐོ་བས་བཅོམ་པ་ན་རྫ་བུམ་དུ་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར་དང༌། 

04:05ཨེ་ཕྲེང་བ་ཟེར་ལབ་དུས། ཕྲེང་རྡོག་མང་པོ་ཚུར་ག་རེ་ཟེར་དགོས། ད་ཕྲེང་ཐག་ལ་ཕྲེང་ཐག་ལ་རྒྱུས་[བརྒྱུད་]བྱས་ཨེ་ནས་དེ་འདྲས་གཅིག་ལ་ཡ། ད་ཕྲེང་བ་ཟེར་ཐ་སྙད་ཆགས་པ་ཐ་སྙད་ཆགས་པ་ཡིན་དུས་ཙ[ང]་ནས། 

04:15 དེ་ཨེ་རྡོག་པོ་སོ་སོ[ར་]ནས་བསལ་བ་ན་ཕྲེང་བར་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར། ཡང༌བཅོམ་པའམ་བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ལ།

04:22 བསལ་བ་ན་རང་འཛིན་གྱི་བློ་འདོར་དུ་མི་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ། དོན་དམ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི་རྡུལ་ཕྲན་ཕྱོགས་ཀྱི་ཆ་མེད་དང༌། ཤེས་པ་སྐད་ཅིག་ཆ་མེད་དང༌འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ལྟ་བུ་ཡིན་ཏེ།

04:32 ད་མཛོད་ཀྱི་ལུགས་དེ་གསུངས། རྗེས་ནས་ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌། ཨེ་ཤེས་པ་སྐད་ཅིག་ཆ་མེད། 

04:41ཨེ་ཆ་བཞག་པ་ཡིན་ན། ད་དེ་ཨེ་ནས་[ནི་]དེ་ནས་ཕར་ཁོ[ང་]བསལ་ཡག་[ཡས་]མེད་བསྡད་པ་རེད། ད་ཁོ[ང་]ཆ་ཕྲ་ཤོས་ཆགས།

04:48 བྱས་ཙང་ག དེ་ནས་ཕར་བསལ་བ་ཡིན་ན། ཨེ་ནས་ཁོ[ང]་རང་འཛིན་གྱི་བློ་ཁོ[ང་]རང་འཛིན་གྱི་བློ་ཟེར་དགོས་རེད་བས།ད་གང་ལྟར་ཤེས་པ་དང་ཁོ་ཨེ་ནས། [ང་།]

04:58རྫས་ཀྱི་རང་བཞིན་ཁོ[ང་]དེ་བརླག་འགྲོ་མཁན་[ངང་]གཅིག[ང་]ཆགས་འདུག་བ། ད་ཁོ[ང་]ཇི་སྲིད་གནས་གནས་བར་དུ་ཨེ་ནས་[ནི་]ག[ང]་དུས་ཡིན་ནས། དེ་གཟུགས་དེ་ཕྲ་ཤོས་དེ་རེད་བསམ་པ[འི]་གཅིག་རང་འཛིན་གྱི་བློ་[དེ་མི་]དོར་གི་[འདོར་ཀྱི་]མི་འདུག་བ།

05:07འོ་ད་བུམ་པ་ལྟ་བུ་རགས་པ་གཅིག་ཡིན་དུས་ཙ[ང་]ནས་ཁོ[ང་]ཕར་བཅོམ་པའམ་བློས་བསལ་ན་ཨེ་ནས་[ནི]་ཨེ་རང་འཛིན་གྱི་བློ་དོར་གྱི་ཡོད་རེད།

05:15ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌ཤེས་པ་སྐད་ཅིག་ཆ་མེད་ཟེར་ཡག་དེ་གས་དེ་[ཡས་་དེ་དེ་ག་དེ་]ཨེ་རང་འཛིན་གྱི་བློ་དེ་[མི་]དོར་གི་[ཀྱི་]མི་འདུག་ཟེར། དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ[ང]་ནས་དེ་དམ་བདེན་པ་རེད་ཅེས་དེ་འདྲའི་བཤད་ཡོང་གི་རེད། [པ་རེད།]

05:23ཨེ་དེས་ན་ཀུན་རྫོབ་བདེན་པ་རྣམས་དོན་དམ་དུ་མ་གྲུབ་ཀྱང་བདེན་གྲུབ་ཏུ་འདོད་དེ།

05:30[ཨོན་]ཨེ་ལུགས་འདིས་དངོས་པོ་ལ་བདེན་གྲུབ་ཀྱིས་ཁྱབ་པ་ཁས་ལེན་པའི་ཕྱིར་རོ། གསུངས་བཞག་ད། [འོ་གསུགས་བཞག་ད།]

05:37 ཡ་སྔོན་ལ་འདི་གཟིགས་དང་།[ལབ་གདའ།] འོ་ཡ། ད་དེ་ནས་ཨེ་ཟག་བཅས་ཟག་མེད་གཉིས་སུ་ཕྱེ་བ་ཟེར་ཡག་[ཡས་]ད་དེ། 

05:45དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་སུ་རུང་བའི་ཆོས་ཟག་བཅས་ཀྱི་མཚན་ཉིད། ཨེ་ད་ཕུང་པོ་ལྔ་ལྟ་བུ། 

05:52ཨེ་དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་ཡ། བྱས་དུས་[བས་]ཙ[ང]་ནས། ཟག་བཅས།

05:58དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་སུ་[སོང་ན་]མི་རུང་བའི་ཆོས། ཨེ་དཔེར་ན་ལམ་བདེན། འདུས་མ་བྱས་ལྟ་བུ་ཡིན་ཏེ་གསུངས་བཞག།

06:07 ད་སྤྱིར་ཟག་བཅས་དང་ཟག་མེད་ཟེར་ཡག་[ཡས་]དོན་དག་འཇོག་ཚུལ་མི་འདྲ་མི་འདྲ་ད་[དག་]ཡོང་གི་ཡོད་རེད།

06:12ད་ཨང་ལྟ་འདི[ར་]ཤེས་བྱ་ཚང་མ་ལོག་ཟག་བཅས་ཟག་མེད་གཉིས་སུ་བསྡུ་བའི་དབང་དུ་བྱས་ནས་ཟག་བཅས་ཟག་མེད་གསུང[ས་]ཡོང་དུས་ཙ[ང་]ནས་ཨང་ལྟ་དེ་ཟག་བཅས་ཟག་མེད་དེ་གསུངས་འདུག་བ།

06:20 དེ་བྱས། ད་དེ་ནས་ཟག་བཅས་ལ་སྤང་བྱས་ཁྱབ་སྟེ། ཨེ་ཚོགས་སྦྱོར་གཉིས་ཨེ་ཚོགས་སྦྱོར་གཉིས་སྤང་བྱ་ཡིན་པའི་ཕྱིར།

06:29བྱས་ད་མཐོང་ལམ་ཟག་མེད་ཁོ་ན་ཕལ་ཆེར་ག་རེ་ཟེར། དེ་ལ་ད་སྐད་ཅིག་བཅོ་ལྔ་རྣམས། མ་མཐོང་མཐོང་ཕྱིར་[བས་ཐམས་ཅད་]མཐོང་བའི་ལམ་ཟེར།

06:38བྱས་ནས་སྐད་ཅིག་བཅོ་ལྔ་དེ་གས་དེ་རྐྱང་རྐྱང་[ཀྱང་ཀྱང་]མཐོང་ལམ་བཞག།སྐད་ཅིག་བཅུ་དྲུག་པ་དེ་སྒོམ་ལམ་བཞག་པ་ཡིན་ན། བྱས་ཙང་ག  ད་མཐོང་ལམ་མཉམ་གཞག་ཁོ་ན་བྱས། [འབྲི་]འབྲས་དུས་ཟག་མེད་ཁོ་ན་དང་།

06:48སྒོམ་ལམ་ལ་ཡ། [ཡར།] ཨེ[་ཨོ་]སྒོམ་ལམ་དང་མི་སློབ་ལམ།

06:57གཉིས་པོ་རེ་རེ་ལ་ཟག་བཅས་ཟག་མེད་ཀྱི་ལམ་གཉིས་གཉིས་ཡོད་དོ་ཟེར།

07:02[ཨ་]ཨེ་ཡ་མཉམ་གཞག་ཐུན་གཅིག་ལ་འགྲོ་གི་ཡོད་མ་རེད་བ། མཉམ་གཞག་ཐུན་གཅིག་ལ་འགྲོ་གི་ཡོད་མ་རེད་བ། 



07:12ད་མ་གཞི་འོ[ག་]ཨང་ལྟ་གཞུང་འབྲས་[འགྲེལ་]དེ་ཚོ་བཤད་ཡོང་ཡ་ཡིན་དུས་ཙ[ང་]ནས། ཨེ། 

07:19སྒོམ་ལམ་དང་མི་སློབ་ལམ་ཨེ།

07:28ད་སྒོམ་ལམ་དང་མི་སློབ་ལམ་གཉིས་པོ་དེ་ལ་གང་ལྟར་མཉམ་རྗེས་གཉིས་ཡོང་གི་ཡོད་པ་ཡིན་དུས་[ས་]ཙ[ང་]ནས། ཟག་བཅས་ཟག་མེད་ཀི་[ཀྱི]་ལམ་གཉིས་གཉིས་ཡོད་ཟེར། 

07:35འཕགས་ལམ་ཡིན་ན་ཟག་མེད་ཡིན་པས་ཁྱབ་ཀྱང༌། འཕགས་རྒྱུད་ཀྱི་ལམ་ལ་ཟག་མེད་ཡིན་པས་མ་ཁྱབ་སྟེ། སྒོམ་པས་སྒོམ་ལམ་པའི་རྒྱུད་ཀྱི་ཞི་རགས་རྣམ་ཅན་དུ་གྱུར་པའི་ལམ་དེ་ཟག་བཅས་ཡིན་པའི་ཕྱིར།

07:43 ད་དེ་ནས་འཕྲོས་དོན་གཞན་བསྟན་པ་ལ་དུས་གསུམ་རྫས་སུ་འདོད་དེ། བུམ་པ་བུམ་པའི་ཨེ་འདས་པའི་དུས་སུ་ཡང་ཡོད།

07:49ཨེ་བུམ་པ་བུམ་པའི་མ་འོངས་པའི་དུས་སུ་ཡང་ཡོད་པ[ར་]འདོད་པའི་ཕྱིར། དགག་སྒྲུབ་གཉིས་ཁས་ལེན་ཀྱང༌།

07:57མེད་དགག་[ནི་]ཁས་མི་ལེན་ཨེ། ད་གང་ལྟར་དོན་གྱི་ངོ་བོ་འདྲ་བོ་གཅིག་མེད་ན་མ་བདེ་ཆགས་[བཞག་]ཡོང་དུས་ཙ[ང]་ནས་དགག་བྱ་བཀག་ཙམ་གྱིས

08:05མེད་དགག་ཟེར་ཡ་[ཡས་]དེ་བློ་ལ་བདེ་བོ་ཆགས་ཀྱི་མེད་པ་རེད། [སོ་]སེ་དེ་འདྲ་ཡིན་དུས་མེད་དགག་ཁས་མི་ལེན་ཟེར། ཨེ་དགག་པ་ཡིན་ན་མ་ཡིན་དགག་ཡིན་པས་ཁྱབ་པར་འདོད་པའི་ཕྱིར། 

08:13བྱེ་བྲག་སྨྲ་བ་རྣམས་མདོ་སྡེ་པ་དང་མཐུན་པར་ལས་འབྲས་ཀྱི་འབྲེལ་བའི་རྟེན་དུ་རྣམ་ཤེས་ཀྱི་རྒྱུན་ཁས་ལེན་ཅིང༌། 

08:21ད་ལས་འབྲས་ཨེ་གྲུབ་མཐའ་སྨྲ་བ[འི་]དེ་ཐམས་ཅད་ལོག་གིས་ད་མུ་སྟེགས་པས། འོ་མུ་སྟེགས་པས་བདག་ཁས་[ལེན་]བླངས་[པས་]ཙང་བསམ་[བློ་]གཏོགས་ཙེ་[ཙང་]དྲག་[བ]་མེད་འགྲོ

08:28རྟག་གཅིག་རང་དབང་བའི་བདག་གཅིག་ཁས་བླངས་[ལེན་]ཙང་། ཨེ་ད་སངས་རྒྱས་པས། འོ་ད་ཨེ། ག་རེ་[ཟེར་]ཞུ་དགོས་རེད་ཕ་གིའི། [ཕར་གི]

08:37ལས་[ཀྱི་]ཀི་རྒྱུ་འགགས་ནས། ཨེ་ནས་[ནི་]འབྲས་བུ་སྨིན་པའི་བར་ལ་ཡུན་རིང་པོ་འགོར་བསྡད་ཡག[ཡས།] ཁོ[ང]་ད་ཡོང་གི་རེད་བ་ད།

08:46ཨེ་ཡུན་ཡུན་ཡུན་ངེས་མེད་གཅིག་གི་བྱས་སྐབས་རེ་དཔེ་[པས་]ཡུན་རིང་འགོར་བསྡད་ཡག་ཅིག་ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཙ[ང་]ནས་ད་ལས་འགགས་ནས་ལས་དེ་གིས། [་ཡིས།] ཨེ་ནས། [ནི།]

08:54འབྲས་བུ་འབྱིན་ཡག་གི་[ཡས་]ནུས་པ་འདྲ་བོ་གཅིག་ད། ཡོད་རེད་བ་ད། ད་འོ་དེའི་[དེར་]བསམ་བློ[ས་]ཞེ་བོ་གཅིག་[གཅིང་]བཏང་[ག་]ཡོད་རེད།



09:02སངས་རྒྱས་པའི་གཞུང་གི་ནང་ལོག་ལ། [ཡ།] སངས་རྒྱས་པའི་[པས་]ད་ག་རེ་ཟེར་དགོས་རེད། གཞུང་གི་ཟེར་དགོས་རེད་བས། ད་སངས་རྒྱས་པའི་ཆོས་པ་ཚོའི་ནང་ལོག་ལ་ཡ་[ར]་དེ་བསམ་བློ་ཞེ་དྲག་བཏང་ནས། 

09:09[སོ་]སེ་དེ་འདྲས་[འདྲ་]ཡིན་པ་ཡིན་དུས་ཙ[ང་]ནས་ཁ་ཆེ་བྱེ་བྲག་སྨྲ་བ་རྣམས་མདོ་སྡེ་པ་མཐུན་པ། མདོ་སྡེ་མདོ་སྡེ་པ་དང་མཐུན་པར་ལས་འབྲས་ཀྱི་འབྲེལ་བའི་རྟེན་དུ་ [མདོ།]

09:17རྣམ་ཤེས་ཀྱི་རྒྱུན་ཁས་ལེན་ཅིང༌། ཨེ་ད། ཡིད་ཤེས། [ད་]ཡིད་ཀྱི་ཤེས་པ་ད་རྒྱུན་མ་ཆད་པ[ར་]ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཙ[ང་]ནས།

09:25 དེའི་དེ་རྣམ་ཤེས་[ས་ཀྱི་]ག་རེ་ཟེར་དགོས་རེད། བག་ཆགས་འཇོག་ས་དེ་[ཟེར་]བྱས། བག་ཆགས་[བསྒོ་]བགོ་གཞི་དེ་བྱས། དེ་མ་གཏོགས་པའི་བྱེ་བྲག་སྨྲ་བ་རྣམས།

09:33 ལས་འབྲས་ཀྱི་འབྲེལ་བའི་རྟེན་དུ་ད་བྱེ་བྲག་སྨྲ་བའི་རྟོག་བཏགས་ཡིན་པ་རེད། བྱེ་བྲག་སྨྲ་བ་རང་གིས་ཐོབ་པ་ཟེར་ཡག་[ཞེས་ཡས་]བཤད་ནས།

09:39 ཨེེ་ཨེ་ཨིན། [ཨན་་]

09:46ལྡན་མིན་འདུ་བྱེད་ག་ཚོད་རེད་བས། བཅུ་བཞི་ཡིན་ན་གཅིག་[ནས་]བཤད་པའི་ནང་གི་ད་འོ་ཐོབ་པ་ཟེར་ཡག་[ཞེས་ཡས་ཤོད་ཀྱི་]གཅིག་བཤད་བསྡད་[ཀྱི་]ཡོད་རེད། ཨོ་ད་དེ་གསུང་གི་ཡོད་རེད།

09:52 ཨེེེ་ལས་འབྲས་ཀྱི་འབྲེལ་བའི་རྟེན་དུ་ཐོབ་པ[ར་]དང་། ཡང༌བུ་ལོན་གྱི་[དཔང་]སྤང་བྱ་[རྒྱ་]དང་འདྲ་བའི་ཆུད་མི་ཟ་བ་ཞེས་པའི་ལྡན་མིན་འདུ་བྱེད་དུ་གྱུར་པ་ཞིག་ཁས་ལེན་ལ། 

10:00 ཐལ་འགྱུར་བ་དང༌འདི་གཉིས་ཀའི་ལུགས་ལ་ལུས་ངག་གི་ལས་གཟུགས་ཅན་དུ་འདོད་དོ། 

10:07ལས་ལ་ཨེ་སེམས་བྱུང་སེམས་པ་ཁོ་ན་ཡིན་[མི་]དགོས་མ་རེད་ཟེར། [པར] གཟུགས་ཅན་ཡོད་རེད་ཟེར་བྱས་ནས་[ཅེས་]ད་གསུངས་ཡིན་པ་རེད། འདུས་བྱས་ལ་མི་རྟག་པས་ཁྱབ་ཀྱང༌།

10:15 སྐད་ཅིག་རེ་རེ་ནས་འཇིག་པས་མ་ཁྱབ་སྟེ། འོ་ད་གིན་[གར་]ཞུ་ཡག་[ཡས་]དེ་བྱས། སྐྱེས་ཟིན་པའི་འོག་ཏུ་གནས་པའི་བྱ་བ། མཚན་ཉིད་སྐྱེ་སོགས་བཞི་གསུངས་བསྡད་ཡག[ཡས།] མཚན་ཉིད་སྐྱེ་སོགས་བཞི།





10:23 ཡང་དེ་རེ་རེ་ལའང་སྐྱེ་བའི་སྐྱེ་བ་སོགས་ཡང་བཞི་བཞག་བྱས་ནས་རྙོག་དྲ་ཚ་པོ་ཞིག་འདུག་བ། 

10:28འདུས་བྱས་ལ་མི་རྟག་པས་ཁྱབ་ཀྱང༌། སྐད་ཅིག་རེ་རེ་ནས [...]

2023-05-07 04:11 UTC, choephel-tashi commented
00:00ད་ངས་ནམ་རྒྱུན་འོ་དེ་བཤད་བསྡད་ཀིན་ཡོད། ཨེ་ནས་ཨེ་སངས་རྒྱས་པའི་གཞུང་ནས་ད་གཞི་ལམ་འབྲས་གསུམ་ཞེས་བཤད་ཀིན་ཡོད་པ་ཡིན་དུས།

00:08 ཨེ་ནས་ད་ལྟ་གཅིག་ཚན་རིག་པ་དང་འབྲེལ་བ་ཡོང་བསྡད་དེ། ཨེ་ལམ་དང་འབྲས་བུའི་གནས་ཚུལ་གྱི་ཨེ་ཐོག་ནས།

00:18ད་ཨེ་ཚན་རིག་པ་དང་འབྲེལ་བ་བྱེད་ཡག་བྱེད་དོན་ཡོད་མ་རེད་ལ་ཨེ་ཡོང་གི་ཡོད་མ་རེད། ད་མིན་ལམ་གྱི་དམིགས་པ་ཕྲ་བའི་མི་རྟག་པ་བཟོ་འདྲ་བོ་དེ་འདྲའི་དེ་འདྲའི།

00:27ད་ཨང་ལྟ་ཡང་གཅིག་སླེབས་ཡོང་གི་ཡོད་རེད། ད་དེ་ཁོ་གཞིའི་གནས་ཚུལ་ཆགས་ཀྱི་རེད་བ་ད་དེའི། བྱས་ཙང་ག ད་གཞིའི་རྣམ་གཞག

00:36 དེའི་ཐོག་ནས་ཚན་རིག་པ་ལ་འབྲེལ་བ་ཡོང་བསྡད་ཡག་གཞིའི་རྣམ་གཞག་དེ་ལ་ཡང་། ཨེ་ནས་མཐོང་བ་མངོན་གྱུར། ཅུང་ཟད་ལྐོག་གྱུར།

00:45ག་རེ་ཟེར་ཨེ་ནས་ཤིན་ཏུ་ལྐོག་གྱུར་བཅས་ཡོད་པའི་ནང་ནས་གཙོ་བོ་གཙོ་བོ་མཐོང་བ་མངོན་གྱུར་དང༌། ཨེ་ནས་ཕྲ་བའི་མི་རྟག་པ་ལ་སོགས་པའི་ཅུང་ཟད་ལྐོག་གྱུར་དེ་གས་དེ།

00:54གཞི་རྩ་དེ་གས་དེ་ནང་ལོག་ནས་ཚན་རིག་པ་དང་འབྲེལ་བ་ཡོང་བསྡད་ཡག་དེ་རེད། བྱས། ད་དེ་ལ་དང་པོ་ལ་གཉིས།

01:03ཡུལ་གྱི་འདོད་ཚུལ་དང་ཡུལ་ཅན་གྱི་འདོད་ཚུལ། སྤྱིར་ཨེ་ནས་གཞི་ཡི་གནས་ཚུལ་དབྱེ་བ་ཕྱེ་ལུགས་ད་འདྲ་མི་འདྲ་ཡོང་གི་རེད་དེ། ཡིན་ནས་ད་ཨང་ལྟ། 

01:12 ཡུལ་དང་ཡུལ་ཅན་ཟེར་བྱས་ནས་དབྱེ་བ་ཕྱེ་བ་དེ་གིས་ཁོ་གནད་འགག་ཅིག་འདུག་བ། ད་ལམ་བཤད་ཡག་དེ་གས་དེ་གཙོ་བོ་ཡུལ་ཅན་སྒང་ནས་ད་ལམ་བཤད་དགོས་རེད་བ།

01:19 ཨེ་ཡུལ་ཅན་དང་ད་འབྲས་བུ་མཐར་ཐུག་དེ་ཡུལ་ཅན་གྱི་སྟེང་གི་ཨེ་ནས་འགྱུར་བ་བཏང་བྱས། ད་དེ་ལ་བརྟེན་ཁོ་ད་ཡ་ག་རེ་ཟེར་དགོས་རེད། ལམ་དང་འབྲས་བུའི་གནས་ཚུལ་དེ། 

01:29གཙོ་བོ་དེའི་ཐོག་ནས་བཤད་དགོས་ཡག་ཅིག་ཡིན་པ་ཡིན་དུས། ཕལ་ཆེར་ཡུལ་དང་ཡུལ་ཅན་ཞེས་དབྱེ་བ་དེ་འདྲས་བསམ་བློ་གཏོང་ཡག་མིན་འགྲོ། ད་ཡུལ་གྱི་འདོད་ཚུལ་ལ་ལུགས་འདིས་ཤེས་བྱ་ཐམས་ཅད་གཞི་ལྔར་ཨེ་

01:38 འདུས་པར་འདོད་དེ། སྣང་བ་གཟུགས་ཀྱི་གཞི། གཙོ་བོ་སེམས་ཀྱི་གཞི། འཁོར་སེམས་འབྱུང་གི་གཞི། བདེན་པ་མ་ཡིན་པའི་འདུ་བྱེད་ཀྱི་གཞི། འདུས་མ་བྱས་ཀྱི་གཞི་རྣམས་སོ།།

01:46གཞི་ལྔ་པོ་དེ་དག་ཀྱང་དངོས་པོར་འདོད་དེ། ད་ཨེ་གང་ལྟར་ག་རེ་ཟེར་དགོས་རེད། ཡོད་པ་ཞིག་ཡིན་ཕྱིན་ཆད་ལ་ཡ། 

01:55ཁོ་བྱས་རང་གཅིག་ད་དོན་བྱེད་པའམ་རང་རང་གིས་གཅིག་དོན་བྱེད་པ་འདྲ་བོ། གཅིག་དོན་བྱེད་ནུས་པ་འདྲ་བོ།དེ་འདྲའི་རང་བཞིན་རྗེན་པ་གཅིག་ད་ཁོ་ཡོད་དགོས་ཡག་ཡིན་དུས་ཙ་ནས།

02:04 དོན་བྱེད་པ། དོན་བྱེད་ནུས་པ་དངོས་པོའི་མཚན་ཉིད་བྱས་ནས་ད་དངོས་པོ། ཡོད་པ། ཤེས་བྱ། ཨེ་འོ་ད་འགྲིག་བཞག དངོས་པོ་རྣམས་དོན་གཅིག།

02:14 འདུས་མ་བྱས་ཀྱི་ཆོས་རྣམས་རྟག་པའི་དངོས་པོ་དང༌། དེ་ཕལ་ཆེར་ཨེ་ཨེ་ད་རྒྱུན་གྱི་རྟག།ད་རྒྱུན་གྱི་ཟེར་དགོས་རེད་བས།ད་གང་ལྟར་

02:22 རྟག་ཏུ་གནས་མཁན་གྱི་རྟག་པ་གཅིག་ལ་གོ་དགོས་ཀི་མིན་འགྲོ། ཨེ་བྱས་ནས་འདུ་མ་བྱེད་ཀྱི་ཆོས་རྣམས་རྟག་པའི་དངོས་པོ་དང་གཟུགས་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་ནི་མི་རྟག་པའི་དངོས་པོ་འདོད།

02:32 དངོས་པོ་ལ་རྫས་གྲུབ་ཀྱིས་ཁྱབ་ཀྱང་། རྫས་ཡོད་ཀྱིས་མ་ཁྱབ་སྟེ། དོན་དམ་བདེན་པ་དང༌། རྫས་ཡོད་དོན་གཅིག སེ་ད་རྫས་གྲུབ་དང་རྫས་ཡོད། གྲུབ་པ་དང་།

02:40 ཡོད་པ་གཉིས་པོ་འདི་སྤྱིར་བཏང་ད་ཚིག་དེ། ཨེ་ཁོ་གཅིག་པ་འདྲ་བོ་ཆགས་ཀྱི་ཡོད་རེད་དེ། ཡིན་ནས་ད་ཨང་ལྟ་དེ་རྫས་ཟེར་ཡག་ཚིག་དེ་དང་འབྲེལ་ནས་ཡོང་དུས་ཙ་ནས་ཁོ་གོ་བ་མི་འདྲ་གཅིག། གོ་བ་ལྷག་པོ་གཅིག།

02:50 ད་ཕ་གིའི་ག་རེ་ཟེར་དགོས་རེད། ཨེ་ད་ག་རེ་ཟེར་དགོས་རེད། གོ་བ་གཅིག། མི་འདྲ་བ་གཅིག། ཨེ་ནས་ཁོ་ད་ག་རེ་ཟེར་དགོས་རེད། གཏན་འབེབས་ཟེར་དགོས་རེད་བས།

02:59གོ་བ་མི་འདྲ་གཅིག་སྤྲད་ཡག་གཅིག་དགོངས་པ་བཞེས་ནས་རྫས་གྲུབ་དང་རྫས་ཡོད་ལ་ཁྱད་པར་ཕྱེ། ཨེ་དོན་དམ་བདེན་པ་དང་། དོན་དམ་བདེན་པ་དང་རྫས་ཡོད་དོན་གཅིག

03:09 ཀུན་རྫོབ་བདེན་པ་དང༌། བཏགས་ཡོད་དོན་གཅིག་ཏུ་འདོད་པའི་ཕྱིར། བཏགས་ཡོད་དེ་རྫས་གྲུབ་རེད་དེ་རྫས་ཡོད་མ་རེད་གསུངས་བ་རེད། ད

03:18ཨེ་དེ་ལ་དབྱེ་ན་བདེན་པ་གཉིས་སུ་དབྱེ་བ་དང༌། ཟག་བཅས་ཟག་མེད་གཉིས་སུ་དབྱེ་བ་དང༌། འཕྲོས་དོན་གཞན་བསྟན་པའོ།། དང་པོ་ནི་ད་འོ་བདེན་གཉིས་བཤད་བསྡད་ཡག་དེ།

03:27 ཕྱི་པ་ཚོས་བདེན་གཉིས་བཤད་ཀྱི་ཡོད་རེད་ལ། ད་ནང་པའི་གྲུབ་མཐའ་ཡོངས་རྫོགས་ལོག་གིས་བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་དེ་གསུང་གི་ཡོད། ད་བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་གསུང་ཡག་དེ་སྣང་ཚུལ་དང་གནས་ཚུལ་གྱི་ཐོག་ནས།

03:35 ཕལ་ཆེར་ཕྲན་བུ་ཕྲན་འདྲ་བཤད་ཆོག་གི་མེད་འགྲོ་བསམ་གྱིན། ད་དེ་ལ་བཅོམ་པའམ་བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ན། རང་འཛིན་གྱི་བློ་འདོར་དུ་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ།

03:45 ཀུན་རྫོབ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི། རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུའོ་ཟེར། ཨེ།

03:50 གང་ལ་བཅོམ་དང་བློ་ཡིས་གཞན། །བསལ་ན་དེ་བློ་མི་འཇུག་པ། ། བུམ་ཆུ་བཞིན་དུ་ཀུན་རྫོབ་ཏུ། ། ཡོད་དེ། གསུངས་བསྡད་ཡག ད་མངོན་པ་མཛོད་ནང་གསུང་བསྡད་ཡག་དེ་ཡིན་པ་རེད།

03:59ཚད་གཞི་རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུ་ཡིན་ཏེ་ཟེར། རྫ་བུམ་ཐོ་བས་བཅོམ་པ་ན་རྫ་བུམ་དུ་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར་དང༌།

04:05ཨེ་ཕྲེང་བ་ཟེར་ལབ་དུས། ཕྲེང་རྡོག་མང་པོ་ཚུར་ག་རེ་ཟེར་དགོས། ད་ཕྲེང་ཐག་ལ་ཕྲེང་ཐག་ལ་རྒྱུས་བྱས་ཨེ་ནས་དེ་འདྲས་གཅིག་ལ་ཡ། ད་ཕྲེང་བ་ཟེར་ཐ་སྙད་ཆགས་པ་ཐ་སྙད་ཆགས་པ་ཡིན་དུས་ཙ་ནས།

04:15 དེ་ཨེ་རྡོག་པོ་སོ་སོ་ནས་བསལ་བ་ན་ཕྲེང་བར་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར། ཡང༌བཅོམ་པའམ་བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ལ།

04:22 བསལ་བ་ན་རང་འཛིན་གྱི་བློ་འདོར་དུ་མི་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ། དོན་དམ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི་རྡུལ་ཕྲན་ཕྱོགས་ཀྱི་ཆ་མེད་དང༌། ཤེས་པ་སྐད་ཅིག་ཆ་མེད་དང༌འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ལྟ་བུ་ཡིན་ཏེ།

04:32 ད་མཛོད་ཀྱི་ལུགས་དེ་གསུངས། རྗེས་ནས་ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌། ཨེ་ཤེས་པ་སྐད་ཅིག་ཆ་མེད།

04:41ཨེ་ཆ་བཞག་པ་ཡིན་ན། ད་དེ་ཨེ་ནས་དེ་ནས་ཕར་ཁོ་བསལ་ཡག་མེད་བསྡད་པ་རེད། ད་ཁོ་ཆ་ཕྲ་ཤོས་ཆགས།

04:48 བྱས་ཙང་ག་དེ་ནས་ཕར་བསལ་བ་ཡིན་ན། ཨེ་ནས་ཁོ་རང་འཛིན་གྱི་བློ་ཁོ་རང་འཛིན་གྱི་བློ་ཟེར་དགོས་རེད་བས།ད་གང་ལྟར་ཤེས་པ་དང་ཁོ་ཨེ་ནས། 

04:58རྫས་ཀྱི་རང་བཞིན་ཁོ་དེ་བརླག་འགྲོ་མཁན་གཅིག་ཆགས་འདུག་བ། ད་ཁོ་ཇི་སྲིད་གནས་གནས་བར་དུ་ཨེ་ནས་ག་དུས་ཡིན་ནས། དེ་གཟུགས་དེ་ཕྲ་ཤོས་དེ་རེད་བསམ་པ་གཅིག་རང་འཛིན་གྱི་བློ་དོར་གི་མི་འདུག་བ།

05:07འོ་ད་བུམ་པ་ལྟ་བུ་རགས་པ་གཅིག་ཡིན་དུས་ཙ་ནས་ཁོ་ཕར་བཅོམ་པའམ་བློས་བསལ་ན་ཨེ་ནས་་ཨེ་རང་འཛིན་གྱི་བློ་དོར་གྱི་ཡོད་རེད།

05:15ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌ཤེས་པ་སྐད་ཅིག་ཆ་མེད་ཟེར་ཡག་དེ་གས་དེ་ཨེ་རང་འཛིན་གྱི་བློ་དེ་དོར་གི་མི་འདུག་ཟེར། དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་དེ་དམ་བདེན་པ་རེད་ཅེས་དེ་འདྲའི་བཤད་ཡོང་གི་རེད། 

05:23ཨེ་དེས་ན་ཀུན་རྫོབ་བདེན་པ་རྣམས་དོན་དམ་དུ་མ་གྲུབ་ཀྱང་བདེན་གྲུབ་ཏུ་འདོད་དེ།

05:30ཨེ་ལུགས་འདིས་དངོས་པོ་ལ་བདེན་གྲུབ་ཀྱིས་ཁྱབ་པ་ཁས་ལེན་པའི་ཕྱིར་རོ། གསུངས་བཞག་ད།

05:37 ཡ་སྔོན་ལ་འདི་གཟིགས་དང་།འོ་ཡ། ད་དེ་ནས་ཨེ་ཟག་བཅས་ཟག་མེད་གཉིས་སུ་ཕྱེ་བ་ཟེར་ཡག་ད་དེ།

05:45དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་སུ་རུང་བའི་ཆོས་ཟག་བཅས་ཀྱི་མཚན་ཉིད། ཨེ་ད་ཕུང་པོ་ལྔ་ལྟ་བུ།

05:52ཨེ་དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་ཡ། བྱས་དུས་ཙ་ནས། ཟག་བཅས།

05:58དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་སུ་མི་རུང་བའི་ཆོས། ཨེ་དཔེར་ན་ལམ་བདེན། འདུས་མ་བྱས་ལྟ་བུ་ཡིན་ཏེ་གསུངས་བཞག།

06:07 ད་སྤྱིར་ཟག་བཅས་དང་ཟག་མེད་ཟེར་ཡག་དོན་དག་འཇོག་ཚུལ་མི་འདྲ་མི་འདྲ་ད་ཡོང་གི་ཡོད་རེད།

06:12ད་ཨང་ལྟ་འདི་ཤེས་བྱ་ཚང་མ་ལོག་ཟག་བཅས་ཟག་མེད་གཉིས་སུ་བསྡུ་བའི་དབང་དུ་བྱས་ནས་ཟག་བཅས་ཟག་མེད་གསུང་ཡོང་དུས་ཙ་ནས་ཨང་ལྟ་དེ་ཟག་བཅས་ཟག་མེད་དེ་གསུངས་འདུག་བ།

06:20 དེ་བྱས། ད་དེ་ནས་ཟག་བཅས་ལ་སྤང་བྱས་ཁྱབ་སྟེ། ཨེ་ཚོགས་སྦྱོར་གཉིས་ཨེ་ཚོགས་སྦྱོར་གཉིས་སྤང་བྱ་ཡིན་པའི་ཕྱིར།

06:29བྱས་ད་མཐོང་ལམ་ཟག་མེད་ཁོ་ན་ཕལ་ཆེར་ག་རེ་ཟེར། དེ་ལ་ད་སྐད་ཅིག་བཅོ་ལྔ་རྣམས། མ་མཐོང་མཐོང་ཕྱིར་མཐོང་བའི་ལམ་ཟེར།

06:38བྱས་ནས་སྐད་ཅིག་བཅོ་ལྔ་དེ་གས་དེ་རྐྱང་རྐྱང་མཐོང་ལམ་བཞག།སྐད་ཅིག་བཅུ་དྲུག་པ་དེ་སྒོམ་ལམ་བཞག་པ་ཡིན་ན། བྱས་ཙང་ག ད་མཐོང་ལམ་མཉམ་གཞག་ཁོ་ན་བྱས། འབྲས་དུས་ཟག་མེད་ཁོ་ན་དང་།

06:48སྒོམ་ལམ་ལ་ཡ། ཨེ་སྒོམ་ལམ་དང་མི་སློབ་ལམ།

06:57གཉིས་པོ་རེ་རེ་ལ་ཟག་བཅས་ཟག་མེད་ཀྱི་ལམ་གཉིས་གཉིས་ཡོད་དོ་ཟེར།

07:02 ཨེ་ཡ་མཉམ་གཞག་ཐུན་གཅིག་ལ་འགྲོ་གི་ཡོད་མ་རེད་བ། མཉམ་གཞག་ཐུན་གཅིག་ལ་འགྲོ་གི་ཡོད་མ་རེད་བ།

07:12ད་མ་གཞི་འོ་ཨང་ལྟ་གཞུང་འབྲས་དེ་ཚོ་བཤད་ཡོང་ཡ་ཡིན་དུས་ཙ་ནས། ཨེ།

07:19སྒོམ་ལམ་དང་མི་སློབ་ལམ་ཨེ།

07:28ད་སྒོམ་ལམ་དང་མི་སློབ་ལམ་གཉིས་པོ་དེ་ལ་གང་ལྟར་མཉམ་རྗེས་གཉིས་ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཙ་ནས། ཟག་བཅས་ཟག་མེད་ཀི་ལམ་གཉིས་གཉིས་ཡོད་ཟེར

07:35འཕགས་ལམ་ཡིན་ན་ཟག་མེད་ཡིན་པས་ཁྱབ་ཀྱང༌། འཕགས་རྒྱུད་ཀྱི་ལམ་ལ་ཟག་མེད་ཡིན་པས་མ་ཁྱབ་སྟེ། སྒོམ་པས་སྒོམ་ལམ་པའི་རྒྱུད་ཀྱི་ཞི་རགས་རྣམ་ཅན་དུ་གྱུར་པའི་ལམ་དེ་ཟག་བཅས་ཡིན་པའི་ཕྱིར།

07:43 ད་དེ་ནས་འཕྲོས་དོན་གཞན་བསྟན་པ་ལ་དུས་གསུམ་རྫས་སུ་འདོད་དེ། བུམ་པ་བུམ་པའི་ཨེ་འདས་པའི་དུས་སུ་ཡང་ཡོད།

07:49ཨེ་བུམ་པ་བུམ་པའི་མ་འོངས་པའི་དུས་སུ་ཡང་ཡོད་པ་འདོད་པའི་ཕྱིར། དགག་སྒྲུབ་གཉིས་ཁས་ལེན་ཀྱང༌།

07:57མེད་དགག་ཁས་མི་ལེན་ཨེ། ད་གང་ལྟར་དོན་གྱི་ངོ་བོ་འདྲ་བོ་གཅིག་མེད་ན་མ་བདེ་ཆགས་ཡོང་དུས་ཙ་ནས་དགག་བྱ་བཀག་ཙམ་གྱིས

08:05མེད་དགག་ཟེར་ཡ་དེ་བློ་ལ་བདེ་བོ་ཆགས་ཀྱི་མེད་པ་རེད། སེ་དེ་འདྲ་ཡིན་དུས་མེད་དགག་ཁས་མི་ལེན་ཟེར། ཨེ་དགག་པ་ཡིན་ན་མ་ཡིན་དགག་ཡིན་པས་ཁྱབ་པར་འདོད་པའི་ཕྱིར།

08:13བྱེ་བྲག་སྨྲ་བ་རྣམས་མདོ་སྡེ་པ་དང་མཐུན་པར་ལས་འབྲས་ཀྱི་འབྲེལ་བའི་རྟེན་དུ་རྣམ་ཤེས་ཀྱི་རྒྱུན་ཁས་ལེན་ཅིང༌།

08:21ད་ལས་འབྲས་ཨེ་གྲུབ་མཐའ་སྨྲ་བ་དེ་ཐམས་ཅད་ལོག་གིས་ད་མུ་སྟེགས་པས། འོ་མུ་སྟེགས་པས་བདག་ཁས་བླངས་ཙང་བསམ་གཏོགས་ཙེ་དྲག་མེད་འགྲོ

08:28རྟག་གཅིག་རང་དབང་བའི་བདག་གཅིག་ཁས་བླངས་ཙང་། ཨེ་ད་སངས་རྒྱས་པས། འོ་ད་ཨེ། ག་རེ་ཞུ་དགོས་རེད་ཕ་གིའི།

08:37ལས་ཀི་རྒྱུ་འགགས་ནས། ཨེ་ནས་འབྲས་བུ་སྨིན་པའི་བར་ལ་ཡུན་རིང་པོ་འགོར་བསྡད་ཡག་ཁོ་ད་ཡོང་གི་རེད་བ་ད།

08:46ཨེ་ཡུན་ཡུན་ཡུན་ངེས་མེད་གཅིག་གི་བྱས་སྐབས་རེ་དཔེ་ཡུན་རིང་འགོར་བསྡད་ཡག་ཅིག་ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཙ་ནས་ད་ལས་འགགས་ནས་ལས་དེ་གིས། ཨེ་ནས། 

08:54འབྲས་བུ་འབྱིན་ཡག་གི་ནུས་པ་འདྲ་བོ་གཅིག་ད། ཡོད་རེད་བ་ད། ད་འོ་དེའི་བསམ་བློ་ཞེ་བོ་ག [...]

2023-05-07 05:09 UTC, Tenzindharten requested changes
00:00ད་ངས་ནམ་རྒྱུན་འོ་དེ་བཤད་བསྡད་ཀིན་ཡོད། ཨེ་ནས་ཨེ་སངས་རྒྱས་པའི་གཞུང་ནས་ད་གཞི་ལམ་འབྲས་གསུམ་ཞེས་བཤད་ཀིན་ཡོད་པ་ཡིན་དུས།

00:08 ཨེ་ནས་ད་ལྟ་གཅིག་ཚན་རིག་པ་དང་འབྲེལ་བ་ཡོང་བསྡད་ཡག་དེ། ཨེ་ལམ་དང་འབྲས་བུའི་གནས་ཚུལ་གྱི་ཨེ་ཐོག་ནས།

00:18ད་ཨེ་ཚན་རིག་པ་དང་འབྲེལ་བ་བྱེད་ཡག་བྱེད་དོན་ཡོད་མ་རེད་ལ་ཨེ་ཡོང་གི་ཡོད་མ་རེད། ད་ལམ་གྱི་དམིགས་པ་ཕྲ་བའི་མི་རྟག་པ་བཟོ་འདྲ་བོ་དེ་འདྲའི་དེ་འདྲའི།

00:27ད་ཨང་ལྟ་ཡང་གཅིག་སླེབས་ཡོང་གི་ཡོད་རེད། ད་དེ་ཁོ་གཞིའི་གནས་ཚུལ་ཆགས་ཀྱི་རེད་བ་ད་དེའི། བྱས་ཙང་ག ད་གཞིའི་རྣམ་གཞག

00:36 དེའི་ཐོག་ནས་ཚན་རིག་པ་ལ་འབྲེལ་བ་ཡོང་བསྡད་ཡག གཞིའི་རྣམ་གཞག་དེ་ལ་ཡང་། ཨེ་ནས་མཐོང་བ་མངོན་གྱུར། ཅུང་ཟད་ལྐོག་གྱུར།

00:45ག་རེ་ཟེར་ཨེ་ནས་ཤིན་ཏུ་ལྐོག་གྱུར་བཅས་ཡོད་པའི་ནང་ནས་གཙོ་བོ་གཙོ་བོ་མཐོང་བ་མངོན་གྱུར་དང༌། ཨེ་ནས་ཕྲ་བའི་མི་རྟག་པ་ལ་སོགས་པའི་ཅུང་ཟད་ལྐོག་གྱུར་དེ་གས་དེ།

00:54གཞི་རྩ་དེ་གས་དེ་ནང་ལོག་ནས་ཚན་རིག་པ་དང་འབྲེལ་བ་ཡོང་བསྡད་ཡག་དེ་རེད། བྱས། ད་དེ་ལ་དང་པོ་ལ་གཉིས།

01:03ཡུལ་གྱི་འདོད་ཚུལ་དང་ཡུལ་ཅན་གྱི་འདོད་ཚུལ། སྤྱིར་ཨེ་ནས་གཞི་ཡི་གནས་ཚུལ་དབྱེ་བ་ཕྱེ་ལུགས་ད་འདྲ་མི་འདྲ་ཡོང་གི་རེད་དེ། ཡིན་ནས་ད་ཨང་ལྟ།

01:12 ཡུལ་དང་ཡུལ་ཅན་ཟེར་བྱས་ནས་དབྱེ་བ་ཕྱེ་བ་དེ་གིས་ཁོ་གནད་འགག་ཅིག་འདུག་བ། ད་ལམ་བཤད་ཡག་དེ་གས་དེ་གཙོ་བོ་ཡུལ་ཅན་སྒང་ནས་ད་ལམ་བཤད་དགོས་རེད་བ།

01:19 ཨེ་ཡུལ་ཅན་དང་ད་འབྲས་བུ་མཐར་ཐུག་དེ་ཡུལ་ཅན་གྱི་སྟེང་གི་ཨེ་ནས་འགྱུར་བ་བཏང་བྱས། ད་དེ་ལ་བརྟེན་ནས་ཁོ་ད་ཡ་ག་རེ་ཟེར་དགོས་རེད། ལམ་དང་འབྲས་བུའི་གནས་ཚུལ་དེ།

01:29གཙོ་བོ་དེའི་ཐོག་ནས་བཤད་དགོས་ཡག་ཅིག་ཡིན་པ་ཡིན་དུས། ཕལ་ཆེར་ཡུལ་དང་ཡུལ་ཅན་ཞེས་དབྱེ་བ་དེ་འདྲའི་བསམ་བློ་གཏོང་ཡག་མིན་འགྲོ། ད་ཡུལ་གྱི་འདོད་ཚུལ་ལ་ལུགས་འདིས་ཤེས་བྱ་ཐམས་ཅད་གཞི་ལྔར་ཨེ་

01:38 འདུས་པར་འདོད་དེ། སྣང་བ་གཟུགས་ཀྱི་གཞི། གཙོ་བོ་སེམས་ཀྱི་གཞི། འཁོར་སེམས་འབྱུང་གི་གཞི། བདེན་པ་མ་ཡིན་པའི་འདུ་བྱེད་ཀྱི་གཞི། འདུས་མ་བྱས་ཀྱི་གཞི་རྣམས་སོ།།

01:46གཞི་ལྔ་པོ་དེ་དག་ཀྱང་དངོས་པོར་འདོད་དེ། ད་ཨེ་གང་ལྟར་ག་རེ་ཟེར་དགོས་རེད། ཡོད་པ་ཞིག་ཡིན་ཕྱིན་ཆད་ལ་ཡ།

01:55ཁོ་བྱས་རང་གཅིག་ད་དོན་བྱེད་པའམ་རང་རང་གིས་གཅིག་དོན་བྱེད་པ་འདྲ་བོ། གཅིག་དོན་བྱེད་ནུས་པ་འདྲ་བོ།དེ་འདྲའི་རང་བཞིན་རྗེན་པ་གཅིག་ད་ཁོ་ཡོད་དགོས་ཡག་ཡིན་དུས་ཙ་ནས།

02:04 དོན་བྱེད་པ། དོན་བྱེད་ནུས་པ་དངོས་པོའི་མཚན་ཉིད་བྱས་ནས་ད་དངོས་པོ། ཡོད་པ། ཤེས་བྱ། ཨེ་འོ་ད་འགྲིག་བཞག དངོས་པོ་རྣམས་དོན་གཅིག།

02:14 འདུས་མ་བྱས་ཀྱི་ཆོས་རྣམས་རྟག་པའི་དངོས་པོ་དང༌། དེ་ཕལ་ཆེར་ཨེ་ཨེ་ད་རྒྱུན་གྱི་རྟག།ད་རྒྱུན་གྱི་ཟེར་དགོས་རེད་བས།ད་གང་ལྟར་

02:22 རྟག་ཏུ་གནས་མཁན་གྱི་རྟག་པ་གཅིག་ལ་གོ་དགོས་ཀི་མིན་འགྲོ། ཨེ་བྱས་ནས་འདུས་མ་བྱས་ཀྱི་ཆོས་རྣམས་རྟག་པའི་དངོས་པོ་དང་གཟུགས་ཤེས་ལྡན་མིན་འདུ་བྱེད་གསུམ་ནི་མི་རྟག་པའི་དངོས་པོ་འདོད།

02:32 དངོས་པོ་ལ་རྫས་གྲུབ་ཀྱིས་ཁྱབ་ཀྱང་། རྫས་ཡོད་ཀྱིས་མ་ཁྱབ་སྟེ། དོན་དམ་བདེན་པ་དང༌། རྫས་ཡོད་དོན་གཅིག སེ་ད་རྫས་གྲུབ་དང་རྫས་ཡོད། གྲུབ་པ་དང་།

02:40 ཡོད་པ་གཉིས་པོ་འདི་སྤྱིར་བཏང་ད་ཚིག་དེ། ཨེ་ཁོ་གཅིག་པ་འདྲ་བོ་ཆགས་ཀྱི་ཡོད་རེད་དེ། ཡིན་ནས་ད་ཨང་ལྟ་དེ་རྫས་ཟེར་ཡག་ཚིག་དེ་དང་འབྲེལ་ནས་ཡོང་དུས་ཙ་ནས་ཁོ་གོ་བ་མི་འདྲ་གཅིག། གོ་བ་ལྷག་པོ་གཅིག།

02:50 ད་ཕ་གིའི་ག་རེ་ཟེར་དགོས་རེད། ཨེ་ད་ག་རེ་ཟེར་དགོས་རེད། གོ་བ་གཅིག། མི་འདྲ་བ་གཅིག། ཨེ་ནས་ཁོ་ད་ག་རེ་ཟེར་དགོས་རེད། གཏན་འབེབས་ཟེར་དགོས་རེད་བས།

02:59གོ་བ་མི་འདྲ་གཅིག་སྤྲད་ཡག་གཅིག་དགོངས་པ་བཞེས་ནས་རྫས་གྲུབ་དང་རྫས་ཡོད་ལ་ཁྱད་པར་ཕྱེ། ཨེ་དོན་དམ་བདེན་པ་དང་། དོན་དམ་བདེན་པ་དང་རྫས་ཡོད་དོན་གཅིག

03:09 ཀུན་རྫོབ་བདེན་པ་དང༌། བཏགས་ཡོད་དོན་གཅིག་ཏུ་འདོད་པའི་ཕྱིར། བཏགས་ཡོད་དེ་རྫས་གྲུབ་རེད་དེ་རྫས་ཡོད་མ་རེད་གསུངས་བ་རེད། ད

03:18ཨེ་དེ་ལ་དབྱེ་ན་བདེན་པ་གཉིས་སུ་དབྱེ་བ་དང༌། ཟག་བཅས་ཟག་མེད་གཉིས་སུ་དབྱེ་བ་དང༌། འཕྲོས་དོན་གཞན་བསྟན་པའོ།། དང་པོ་ནི་ད་འོ་བདེན་གཉིས་བཤད་བསྡད་ཡག་དེ།

03:27 ཕྱི་པ་ཚོས་བདེན་གཉིས་བཤད་ཀྱི་ཡོད་རེད་ལ། ད་ནང་པའི་གྲུབ་མཐའ་ཡོངས་རྫོགས་ལོག་གིས་བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་དེ་གསུང་གི་ཡོད། ད་བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་གསུང་ཡག་དེ་སྣང་ཚུལ་དང་གནས་ཚུལ་གྱི་ཐོག་ནས།

03:35 ཕལ་ཆེར་ཕྲན་བུ་ཕྲན་འདྲ་བཤད་ཆོག་གི་མེད་འགྲོ་བསམ་གྱིན། ད་དེ་ལ་བཅོམ་པའམ་བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ན། རང་འཛིན་གྱི་བློ་འདོར་དུ་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ།

03:45 ཀུན་རྫོབ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི། རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུའོ་ཟེར། ཨེ།

03:50 གང་ལ་བཅོམ་དང་བློ་ཡིས་གཞན། །བསལ་ན་དེ་བློ་མི་འཇུག་པ། ། བུམ་ཆུ་བཞིན་དུ་ཀུན་རྫོབ་ཏུ། ། ཡོད་དེ། གསུངས་བསྡད་ཡག ད་མངོན་པ་མཛོད་ནང་གསུང་བསྡད་ཡག་དེ་ཡིན་པ་རེད།

03:59ཚད་གཞི་རྫ་བུམ་དང་ཕྲེང་བ་ལྟ་བུ་ཡིན་ཏེ་ཟེར། རྫ་བུམ་ཐོ་བས་བཅོམ་པ་ན་རྫ་བུམ་དུ་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར་དང༌།

04:05ཨེ་ཕྲེང་བ་ཟེར་ལབ་དུས། ཕྲེང་རྡོག་མང་པོ་ཚུར་ག་རེ་ཟེར་དགོས། ད་ཕྲེང་ཐག་ལ་ཕྲེང་ཐག་ལ་རྒྱུས་བྱས་ཨེ་ནས་དེ་འདྲས་གཅིག་ལ་ཡ། ད་ཕྲེང་བ་ཟེར་ཐ་སྙད་ཆགས་པ་ཐ་སྙད་ཆགས་པ་ཡིན་དུས་ཙ་ནས།

04:15 དེ་ཨེ་རྡོག་པོ་སོ་སོ་ནས་བསལ་བ་ན་ཕྲེང་བར་འཛིན་པའི་བློ་འདོར་བའི་ཕྱིར། ཡང༌བཅོམ་པའམ་བློས་ཆ་ཤས་སོ་སོར་བསལ་བ་ལ།

04:22 བསལ་བ་ན་རང་འཛིན་གྱི་བློ་འདོར་དུ་མི་རུང་བའི་ཆོས་སུ་དམིགས་པ་དེ། དོན་དམ་བདེན་པའི་མཚན་ཉིད། མཚན་གཞི་ནི་རྡུལ་ཕྲན་ཕྱོགས་ཀྱི་ཆ་མེད་དང༌། ཤེས་པ་སྐད་ཅིག་ཆ་མེད་དང༌འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ལྟ་བུ་ཡིན་ཏེ།

04:32 ད་མཛོད་ཀྱི་ལུགས་དེ་གསུངས། རྗེས་ནས་ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌། ཨེ་ཤེས་པ་སྐད་ཅིག་ཆ་མེད།

04:41ཨེ་ཆ་བཞག་པ་ཡིན་ན། ད་དེ་ཨེ་ནས་དེ་ནས་ཕར་ཁོ་བསལ་ཡག་མེད་བསྡད་པ་རེད། ད་ཁོ་ཆ་ཕྲ་ཤོས་ཆགས།

04:48 བྱས་ཙང་ག་དེ་ནས་ཕར་བསལ་བ་ཡིན་ན། ཨེ་ནས་ཁོ་རང་འཛིན་གྱི་བློ་ཁོ་རང་འཛིན་གྱི་བློ་ཟེར་དགོས་རེད་བས།ད་གང་ལྟར་ཤེས་པ་དང་ཁོ་ཨེ་ནས།

04:58རྫས་ཀྱི་རང་བཞིན་ཁོ་དེ་བརླག་འགྲོ་མཁན་གཅིག་ཆགས་འདུག་བ། ད་ཁོ་ཇི་སྲིད་གནས་གནས་བར་དུ་ཨེ་ནས་ག་དུས་ཡིན་ནས། དེ་གཟུགས་དེ་ཕྲ་ཤོས་དེ་རེད་བསམ་པ་གཅིག་རང་འཛིན་གྱི་བློ་དོར་གི་མི་འདུག་བ།

05:07འོ་ད་བུམ་པ་ལྟ་བུ་རགས་པ་གཅིག་ཡིན་དུས་ཙ་ནས་ཁོ་ཕར་བཅོམ་པའམ་བློས་བསལ་ན་ཨེ་ནས་་ཨེ་རང་འཛིན་གྱི་བློ་དོར་གི་ཡོད་རེད།

05:15ད་རྡུལ་ཕྲན་ཆ་མེད་དང༌ཤེས་པ་སྐད་ཅིག་ཆ་མེད་ཟེར་ཡག་དེ་གས་དེ་ཨེ་རང་འཛིན་གྱི་བློ་དེ་དོར་གི་མི་འདུག་ཟེར། དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་དེ་དམ་བདེན་པ་རེད་ཅེས་དེ་འདྲའི་བཤད་ཡོང་གི་ཡོད་རེད།

05:23ཨེ་དེས་ན་ཀུན་རྫོབ་བདེན་པ་རྣམས་དོན་དམ་དུ་མ་གྲུབ་ཀྱང་བདེན་གྲུབ་ཏུ་འདོད་དེ།

05:30ཨེ་ལུགས་འདིས་དངོས་པོ་ལ་བདེན་གྲུབ་ཀྱིས་ཁྱབ་པ་ཁས་ལེན་པའི་ཕྱིར་རོ། གསུངས་བཞག་ད།

05:37 ཡ་སྔོན་ལ་འདི་གཟིགས་དང་།འོ་ཡ། ད་དེ་ནས་ཨེ་ཟག་བཅས་ཟག་མེད་གཉིས་སུ་ཕྱེ་བ་ཟེར་ཡག་ད་དེ།

05:45དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་སུ་རུང་བའི་ཆོས་ཟག་བཅས་ཀྱི་མཚན་ཉིད། ཨེ་ད་ཕུང་པོ་ལྔ་ལྟ་བུ།

05:52ཨེ་དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་ཡ། བྱས་དུས་ཙ་ནས། ཟག་བཅས།

05:58དམིགས་པ་དང་མཚུངས་ལྡན་གང་རུང་གི་སྒོ་ནས་ཟག་པ་རྒྱས་སུ་མི་རུང་བའི་ཆོས། ཨེ་དཔེར་ན་ལམ་བདེན། འདུས་མ་བྱས་ལྟ་བུ་ཡིན་ཏེ་གསུངས་བཞག།

06:07 ད་སྤྱིར་ཟག་བཅས་དང་ཟག་མེད་ཟེར་ཡག་དོན་དག་འཇོག་སྟངས་མི་འདྲ་མི་འདྲ་ད་ཡོང་གི་ཡོད་རེད།

06:12ད་ཨང་ལྟ་འདི་ཤེས་བྱ་ཚང་མ་ལོག་ཟག་བཅས་ཟག་མེད་གཉིས་སུ་བསྡུ་བའི་དབང་དུ་བྱས་ནས་ཟག་བཅས་ཟག་མེད་གསུང་ཡོང་དུས་ཙ་ནས་ཨང་ལྟ་དེ་ཟག་བཅས་ཟག་མེད་དེ་གསུངས་འདུག་བ།

06:20 དེ་བྱས། ད་དེ་ནས་ཟག་བཅས་ལ་སྤང་བྱས་ཁྱབ་སྟེ། ཨེ་ཚོགས་སྦྱོར་གཉིས་ཨེ་ཚོགས་སྦྱོར་གཉིས་སྤང་བྱ་ཡིན་པའི་ཕྱིར།

06:29བྱས་ད་མཐོང་ལམ་ཟག་མེད་ཁོ་ན་ཕལ་ཆེར་ག་རེ་ཟེར། དེ་ལ་ད་སྐད་ཅིག་བཅོ་ལྔ་རྣམས། མ་མཐོང་མཐོང་ཕྱིར་མཐོང་བའི་ལམ་ཟེར།

06:38བྱས་ནས་སྐད་ཅིག་བཅོ་ལྔ་དེ་གས་དེ་རྐྱང་རྐྱང་མཐོང་ལམ་བཞག།སྐད་ཅིག་བཅུ་དྲུག་པ་དེ་སྒོམ་ལམ་བཞག་པ་ཡིན་ན། བྱས་ཙང་ག ད་མཐོང་ལམ་མཉམ་གཞག་ཁོ་ན་བྱས། འབྲས་དུས་ཟག་མེད་ཁོ་ན་དང་།

06:48སྒོམ་ལམ་ལ་ཡ། ཨེ་སྒོམ་ལམ་དང་མི་སློབ་ལམ།

06:57གཉིས་པོ་རེ་རེ་ལ་ཟག་བཅས་ཟག་མེད་ཀྱི་ལམ་གཉིས་གཉིས་ཡོད་དོ་ཟེར།

07:02 ཨེ་ཡ་མཉམ་གཞག་ཐུན་གཅིག་ལ་འགྲོ་གི་ཡོད་མ་རེད་བ། མཉམ་གཞག་ཐུན་གཅིག་ལ་འགྲོ་གི་ཡོད་མ་རེད་བ།

07:12ད་མ་གཞི་འོ་ཨང་ལྟ་གཞུང་འབྲས་དེ་ཚོ་བཤད་ཡོང་ཡ་ཡིན་དུས་ཙ་ནས། ཨེ།

07:19སྒོམ་ལམ་དང་མི་སློབ་ལམ་ཨེ།

07:28ད་སྒོམ་ལམ་དང་མི་སློབ་ལམ་གཉིས་པོ་དེ་ལ་གང་ལྟར་མཉམ་རྗེས་གཉིས་ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཙ་ནས། ཟག་བཅས་ཟག་མེད་ཀི་ལམ་གཉིས་གཉིས་ཡོད་ཟེར

07:35འཕགས་ལམ་ཡིན་ན་ཟག་མེད་ཡིན་པས་ཁྱབ་ཀྱང༌། འཕགས་རྒྱུད་ཀྱི་ལམ་ལ་ཟག་མེད་ཡིན་པས་མ་ཁྱབ་སྟེ། སྒོམ་པས་སྒོམ་ལམ་པའི་རྒྱུད་ཀྱི་ཞི་རགས་རྣམ་ཅན་དུ་གྱུར་པའི་ལམ་དེ་ཟག་བཅས་ཡིན་པའི་ཕྱིར།

07:43 ད་དེ་ནས་འཕྲོས་དོན་གཞན་བསྟན་པ་ལ་དུས་གསུམ་རྫས་སུ་འདོད་དེ། བུམ་པ་བུམ་པའི་ཨེ་འདས་པའི་དུས་སུ་ཡང་ཡོད།

07:49ཨེ་བུམ་པ་བུམ་པའི་མ་འོངས་པའི་དུས་སུ་ཡང་ཡོད་པ་འདོད་པའི་ཕྱིར། དགག་སྒྲུབ་གཉིས་ཁས་ལེན་ཀྱང༌།

07:57མེད་དགག་ཁས་མི་ལེན་ཨེ། ད་གང་ལྟར་དོན་གྱི་ངོ་བོ་འདྲ་བོ་གཅིག་མེད་ན་མ་བདེ་ཆགས་ཡོང་དུས་ཙ་ནས་དགག་བྱ་བཀག་ཙམ་གྱིས

08:05མེད་དགག་ཟེར་ཡ་དེ་བློ་ལ་བདེ་བོ་ཆགས་ཀྱི་མེད་པ་རེད། སེ་དེ་འདྲས་ཡིན་དུས་མེད་དགག་ཁས་མི་ལེན་ཟེར། ཨེ་དགག་པ་ཡིན་ན་མ་ཡིན་དགག་ཡིན་པས་ཁྱབ་པར་འདོད་པའི་ཕྱིར།

08:13 བྱེ་བྲག་སྨྲ་བ་རྣམས་མདོ་སྡེ་པ་དང་མཐུན་པར་ལས་འབྲས་ཀྱི་འབྲེལ་བའི་རྟེན་དུ་རྣམ་ཤེས་ཀྱི་རྒྱུན་ཁས་ལེན་ཅིང༌།

08:21ད་ལས་འབྲས་ཨེ་གྲུབ་མཐའ་སྨྲ་བ་དེ་ཐམས་ཅད་ལོག་གིས་ད་མུ་སྟེགས་པས། འོ་མུ་སྟེགས་པས་བདག་ཁས་བླངས་ཙང་བསམ་གཏོགས་ཙེ་དྲག་མེད་འགྲོ

08:28རྟག་གཅིག་རང་དབང་བའི་བདག་གཅིག་ཁས་བླངས་ཙང་། ཨེ་ད་སངས་རྒྱས་པས། འོ་ད་ཨེ། ག་རེ་ཞུ་དགོས་རེད་ཕ་གིའི།

08:37ལས་ཀི་རྒྱུ་འགགས་ནས། ཨེ་ནས་འབྲས་བུ་སྨིན་པའི་བར་ལ་ཡུན་རིང་པོ་འགོར་བསྡད་ཡག་ཁོ་ད་ཡོང་གི་རེད་བ་ད།

08:46ཨེ་ཡུན་ཡུན་ཡུན་ངེས་མེད་གཅིག་གི་བྱས་སྐབས་རེ་དཔེ་ཡུན་རིང་འགོར་བསྡད་ཡག་ཅིག་ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཙ་ནས་ད་ལས་འགགས་ནས་ལས་དེ་གིས། ཨེ་ནས།

08:54འབྲས་བུ་འབྱིན་ཡག་གི་ནུས་པ་འདྲ་བོ་གཅིག་ད། ཡོད་རེད་བ་ད། ད་འོ་དེའི་བསམ་བློ་ཞེ་བ [...]

2023-05-15 09:17 UTC, Tenzindharten requested changes
00:00 ག་འོ་གཞི་རེེད། བ་འོ་བཞི་རེད། ག་འོ་གཞི་རེད་ཨེ་རྣམ་འབྱོར་གཞིའི་སྒོ་ནས་ད་གང་ཡིན་ན་རྣམ་འབྱོར་གཞིའི་སྒོ་ནས། 
00:09 ད་རྣམ་འབྱོར་སྤྱོད་པར་ཟེར་བསྡད་དེ་ལ་ཨང་ལྟ་གཞིའི་འདོད་པ་གཅིག་གིས་ཨང་ལྟ་རྣམ་འབྱོར་གྱི་ས་གཞི་ཟེར་ནས་བཤད་བསྡད་ཡག
00:17 དེ་འདྲས་བཤད་དགོས་ཡོད་ན་གང་ཡིན་ན་མི་ཤེས། ཨེ་ད་མི་ཤེས་ཟེར་ན་ཡག་ཤོས་རེད།
00:24 ཨེ་ཌཌི་ནོཝ(I don not know )ཟེར་ལབ་ནས་ཡག་ཤོས་རེད། ཧེ་ཧེ་ཧེ་ཧེ
00:29 ད་བཞི་པ་འདོད་ཚུལ་ལ་ཨེ་གཞི་ལམ་འབྲས་བུ་གསུམ་ལས། དང་པོ་ལ་ཡུལ་ཡུལ་ཅན་གཉིས། 
00:36 དང་པོ་ནི། ཤེས་བྱ་ཐམས་ཅད་མཚན་ཉིད་གསུམ་དུ་འདུས་པར་འདོད་དེ་ཟེར། འདུས་བྱས་ཐམས་ཅད་གཞན་དབང༌དང་། ཆོས་ཆོས་ཉིད་ཐམས་ཅད་ཡོངས་གྲུབ་དང་། དེ་ལས་གཞན་པ་རྣམས་ཀུན་བཏགས་སུ་འདོད་པའི་ཕྱིར་ཟེར།
00:46 ཨེ་ད་གྲུབ་མཐའ་སྨྲ་བ་འདི་བཞི་ཀ་ལོག་གིས།
00:55 ཨེ་ནས་ག་རེ་ཟེར་དགོས་རེད། ཨེ་ཐ་སྙད་པའི་ཕྱོགས་ཀྱི་རྣམ་གཞག་ཨེ་འདོད་ཚུལ་མི་འདྲ་བ་ཡོང་གི་རེད།
01:03 ཡིན་ནས་གཙོ་བོ་གཙོ་བོ་དེ་ཨེ་ནས་བདག་མེད་པ་ཟེར་ཡག་དེ་གིས་ད་དོན་དག་དེ་ཨེ་ནས་ད་ཕར་གོ་བ་
01:12 ལེན་སྟངས་ཕྲ་རགས་ཡོད་པའི་ཐོག་ནས་ད་གྲུབ་མཐའ་བཞི་པོ་དེ་ཐོན་ཡོང་གི་ཡོད་ས་རེད།
01:17 ་་་་་་་་་་་་་
01:20 བྱས་ནས་ད་སྔར་ལ་ལས་དང་པོ་བ་ཨེ་་བློ་གཅིག་རྒྱ་ཆེན་པོ་མིན་མཁན་གཅིག་གིས།
01:30 ཨེ་ང་རང་ཚོའི་རང་རྒྱུད་ཀྱི་ཆགས་སྡང་གི་བློ་ཨེ་ནས་ཤུགས་ཆུང་དུ་གཏོང་ཡག་གི་ཐབས་ཤེས་ག་རེ་བྱེད་དགོས་རེད་ཟེར་ནས་ལབ་པ་ཡིན་ན།
01:36 ང་རང་ཚོའི་ད་ཆགས་སྡང་གི་མཚོན་པས། དཔེར་ན་ཆགས་སྡང་གཉིས་གཙོ་བོར་གྱུར་པའི་གཅིག་ཉོན་མོངས་པའི་བློ་དེ་ཚོ་སྐྱེས་ཡོང་དུས་ཙང་ནས།
 01:44 ཨེ་དཔེར་ན་ང་ཚོ་ཆགས་ཡུལ་ཡིད་དུ་འོང་བ་ཨེ་ཡུལ་ཡིད་དུ་འོང་བ་ལ་ཆགས་པ་སྐྱེས།
 01:53 ཡུལ་ཡིད་དུ་མི་འོང་བ་ལ་སྡང་བ་སྐྱེས། བྱས་ཙང་། ད་དེ་དཔེར་ན་སྤྱིར་བཏང་འདྲ་བཤད་པ་ན།
01:59 ཁོང་ལ་ཁོང་ལ་ཡིད་ཡིད་དུ་འོང་བ་སྣང་གིནཟེར་བྱས་ནས་ང་ཚོར་ཆགས་པ་སྐྱེས་ཀྱི་ཡོད་མ་རེད་བ། མི་གཞན་དག་གཅིག་ལ་མི་གཞན་དག་གཅིག་ལ་ཡིད་དུ་མི་འོང་བ་སྣང་གིན་འདུག་ཟེར་ནས་ང་ཚོར་སྡང་བ་སྐྱེས་ཀི་མ་རེད་བ།
02:08 ང་ལ་ཡིད་དུ་འོང་བ་སྣང་གིན་འདུག། ང་ལ་ཡིད་དུ་མི་འོང་བ་སྣང་གིན་འདུག་བྱས་ནས་
02:12 ཡིད་དུ་འོང་བ་སྣང་ས་དང་མི་སྣང་ས་དེ་ཨེ་བདག་རེད་བ། ད་སེ་ཁྱད་པར་ཞེ་བོ་གཅིག་འདུག་བ། བྱས་ཙང་ད་བདག་དང་འབྲེལ་ནས་ང་ཟེར་ཡག་དེ་དང་འབྲེལ་ནས། 
02:22 ཨེ་ནས་ཡིད་དུ་འོང་བ་དང་ཡིད་དུ་མི་འོང་བ་བཞག་དགོས་ཀྱི་འདུག་བ། 
02:26 བྱས་ཙང་ག་ད་ཡིད་དུ་འོང་བ་ལ་ཆགས་པ། ཡིད་དུ་མི་འོང་བ་ལ་སྡང་བ་དེ་
02:33 ཇི་ཙམ་གྱིས་ང་ཟེར་ཡག་གི་ཨེ་འཛིན་པ་འདྲ་བོ་ཨ་འཐས་ཀྱི་འཛིན་པ་འདྲ་བོ་ག་ཚད་ཤུགས་ཆེ་བ་ཡོད་ན།
02:40 དེའི་ཚོད་ཀྱིས་ཨེ་ཆགས་པ་དང་སྡང་བ་དེ་ཤུགས་ཆེ་བ་ཕལ་ཆེར་ཡོང་ས་རེད། 
02:47 དཔེར་ན་ང་ཡི་དཔེར་ན་ང་ཡི་གཉེན། ཨེ་ང་ཡི་དགྲ་ཟེར་ནས་ཤུགས་ཆེན་པོ་ཞེ་བོ་གཅིག་ཡོང་བསྡད་ཡག་གཅིག།
02:55 ད་ཇི་ཙམ་གྱིས་ངར་འཛིན་པས། ང་ཟེར་ལབ་དུས་དཔེ་ནད་འདྲ་བོ་ཁྱོན་ནས་མ་བཅངས་མཁན་དཔེ་ང་ཟེར་ནས་ཤུགས་ཆེན་པོ་དེ་རང་མེད་པ་གཅིག་གིས།
03:03 ཏོག་ཙེ་གཅིག་ཤུགས་ཆུང་དུ་ཕྱིན་པ་ཡིན་ན། ཨེ་ནས་སྤྱིར་ང་ཡི་གཉེན་དང༌། ང་ཡི་དགྲ་ཡོད་ཡོང་གི་རེད་དེ།
03:09 ཡིན་ནས་ང་ཡི་དགྲ་དང་གཉེན་ཡིན་པ་རྒྱུ་མཚན་དུ་བྱས་ཏེ་དཔེ་ཆགས་སྡང་ཤུགས་དྲག་པོ་སྐྱེས་ཡག་དེ་ཕལ་ཆེར་ཤུགས་ཆུང་བ་ཡོད་ས་རེད།
03:16 ་་་་་་་་་་་་་་་་་་་་་།
03:22 ནམ་རྒྱུན་ཨང་ལྟ་ངས་འདི་འདྲའི་དཔེ་བཤད་བསྡད་ཡོད་དཔེ་འདི་འདྲའི་བཤད་བསྡད་ཀྱི་ཡོད། དཔེ་འདྲ་བོ་ཆ་བཞག་ན་དཔེ་ན་དཔེ་ན་ཅ་ལག་གཅིག་དཔེ་ན་ཆུ་ཚོད་འདྲ་བོ་གཅིག།
03:29 ཨེ་ནས་ཚོང་ཁང་ལ་འདུག་སེ་ཡོད་པའི་ཁ་ཐུག་ལ་ཨེ་ནས་ང་ཡིར་མ་འཛིན་པའི་གོང་ལ་ང་ཡི་ཆུ་ཚོད་བྱས་ནས།
03:37 སོ་སོས་ཉོས་ནས་བདག་གིར་འཛིན་པ་མ་སྐྱེས་གོང་ལ་ཡ་ཡུལ་དེ་ཡིད་དུ་འོང་བ་ལ།
03:43 ཨེ་བཟང་པོའི་ཆ་འདྲ་བོ་གཅིག་ལ་དམིགས་ནས་དེ་ཡག་པོ་འདུག་ག བསམ་པ་གཅིག་ད་ཡོང་གི་རེད། ཡིན་ནས་དེ་རང་གིས་ཉོས་ཚར་བའི་རྗེས་ལ་ང་ཡི་ཆུ་ཚོད་ཟེར་ཡག་ཅིག 
03:53 ཨེ་ཆགས་ཚར་དུས་ད་གིན་ཕ་གིའི་ཁྲོམ་ས་ཁྲོམ་ས་ཡོད་ཚོང་ཁང་ནང་ལ་ཡོད་བསྡད་པའི་གནས་སྐབས་ལས་ཡིད་དུ་འོང་བའི་ཆ་འདྲ་བོ་དེ་ཤུགས་ཆེ་རུ་ཕྱིན་བྱས། 
04:02 ཨེ་ནས་ང་ཡིར་འཛིན་པ་ང་ཡི་འཛིན་པ་ཡིན་ཙང་བདག་གིར་བཟུང་བས་ཡིན་དུས་ཙང་ནས་ཁོས་ཡུལ་དེ་ལ་ཆགས་པའི་བློ་དེ་ཤུགས་ཆེ་རུ་འགྲོ་བསྡད་ཀྱི་འདུག་ག
04:11 སེ་དེ་འདྲས་ཡིན་པས་ཡིན་དུས་ཙ་ནས་སྔོན་ལ་ཆགས་སྡང་གི་བློ་རགས་པ་དེ་ཨེ་སེལ་ཡག་གི་རིམ་པ་དང་པོ་འདྲ་བོ་དེ་ང་ཟེར་བྱས་ནས།
04:19 ཨེ་གཅིག་དཔེར་གཙིགས་སུ་བྱེད་ཡག་གི་དཔེ་ང་རང་མཚན་པ།
04:25 ཨེ་གཅིག་ང་ཨ་འཐས་འདྲ་བོ་ཤར་བསྡད་དེའི་བློ་ཤུགས་ཆུང་དུ་ད་གཏོང་ཡག་གི་ཐབས་ཤེས་གཅིག 
04:32 ཨེ་བྱེད་ཡག་གསུངས་བ་ཡིན་པ་རེད། དེ་ག་རེ་ཟེར་ལབ་ན་ཁ་སེང་ལབ་བ་ཁ་སང་ཁ་ཉིན་ང་ཚོ་སྐད་ཆ་བྱུང་བ་ནང་བཞིན་རེད། ང་ཡི་ལུས། ང་ཡི་སེམས།
04:40 དཔེར་ན་ང་ཡི་ཁང་ཁྱིམ། ང་ཡི་གཉེན་ཉེ་དུ། ང་ཡི་སྤྱི་བོ། ང་ཡི་སྙིང་ག་ཟེར་ཡ་ལབ་ཡོང་དུས་ཙ་ནས དེ་ཐམས་ཅད
04:48 གང་གི་ཡིན་རྒྱུའི་ང་ཟེར་བྱས་ནས་ཚུགས་ཐུབ་བ་གཅིག་ལ་བློ་ལ་ཤར་ཡོང་གི་འདུག་ག ད་དེ་ཇི་ལྟར
04:57ཤར་བ་ནང་བཞིན་གཅིག་ཡོད་མ་རེད་ཟེར་བྱས་ནས་ལབ་དུས་ཙ་ནས། ཨེ་ང་ཟེར་ཡ་ཁོ་ཚུགས་ཐུབ་པའི་བློ་དེ་ག་ཚོད་ཤུགས་ཆུང་དུ་ཕྱིན་པའི་ཚོད་ཀྱིས།
05:05 ང་ཡི་གཉེན་དང༌། ང་ཡི་དགྲ། ཨེ་གཅིག་ང་ཡི་ལོངས་སྤྱོད་ཟེར་བསྡད་ཡ་དེ། འཛིན་ཆགས་འདྲ་བོ་ཁོ་ཏོག་ཙེ་ཤུགས་ཆུང་དུ་འགྲོ་གི་ཡོད་ས་རེད། 
05:13 ཇི་ཙམ་གྱིས་འཛིན་ཆགས་འདྲ་བོ་ཁོང་ཤུགས་ཆུང་དུ་ཕྱིན་པ་ཡིན་ན། དེ་ལ་འགལ་རྐྱེན་ཟོ་མཁན་གྱི་མི་མཐུན་ཕྱོགས་ལ་སྡང་བ་དེ་ཤུགས་ཆུང་དུ་འགྲོ་ཡི་རེད།
05:21 དེ་རྣམ་འགྲེལ་ནང་གསུངས་བ་ནང་བཞིན་བདག་ཡོད་ན་ནི་གཞན་དུ་ཤེས། །བདག་གཞན་ཆ་ལས་འཛིན་དང་སྡང༌།། གསུངས་བ་ནང་བཞིན། ག་ཚད་ཇི་ཙམ་གྱིས་ཆགས་པའི་བློ་ཤུགས་ཆེ་བ་ཡོད་པ་དེའི་ཚོད་ཀྱིས
05:30 ཁོ་སྡང་བའི་བློ་སྐྱེས་ཡོང་ཡག་གཅིག་ཕལ་ཆེར་ཡིན་ས་རེད། ག་གས་མ་བྱས་གོང་ནས་སྡང་བ་སྐྱེས་ཀི་མ་རེད་བ། རེད་བ། སུ་ལའང་ཁྲོས་བསྡད་ཡ་གཅིག་མ་རེད་བ། 
05:37རང་ལ་གཅིག་སྔོན་ལ་རང་ལ་ཆགས་པ་གཅིག་ཡོད་ནས་རང་ངམ་རང་ཡི་གཉེན་ཉེ་དུ་དེ་ལ་ཆགས་པ་གཅིག་ཡོད་ནས། དེའི་དབང་ལས་དེ་ལ་ཨེ་ནས་འགལ་རྐྱེན་འཕྲད་ཡོང་དུས། 
05:46 སྡང་བ་དེ་སླེབ་ཡོང་གི་འདུག་ག བྱས་ཙང། ཨོ་དེ་འདྲས་ཡིན་དུས་ཆགས་སྡང་གི་བློ་ཤུགས་ཆུང་དུ་གཏོང་ཡག་གི་རིམ་པ་དང་པོ་འདྲ་བོ་དེ་ང་ཟེར་ཡག་གི་བློ
05:56བློ་ཤུགས་དྲག་པོ་དེ་ཤུགས་ཆུང་དུ་གཏོང་བ་གཅིག དེ་ལ་ཡ་ཨེ་ནས་རྟག་གཅིག་རང་དབང་བའི་བདག་ཡོད་མ་རེད་ཟེར་ཡག་དང་གཅིག 
06:02 དེ་ཙམ་དུ་མ་ཟད་པས་ཕུང་ཕུང་པོའི་ཕྱི་ནས་ཕུང་པོ་ལས་དོན་གཞན་པའི་རྟག་གཅིག་རང་དབང་བའི་བདག་ཡོད་མ་རེད། ད་ག་ནང་བཞིན་གི་ཨེ་ཕུང་པོའི་ནང་ནས་
06:11 ཕུང་པོ་ལ་བརྟེན་པ་གང་ཞིག་གཅིག་ལ་ཡིན་ནའང་ཕུང་པོ་ལ་དབང་སྒྱུར་མཁན་གྱི་རྗེ་བོ་ལྟ་བུའི་ང་རང་རྐྱ་བ་གཅིག་ཡོད་མ་རེད་ཟེར་བྱས་ནས།
06:20 ཁོ་ཨེ་ཕར་བསམ་བློ་བཏང་དཔེ་ངེས་པ་དྲངས། ཨེ་ནས་གོམས་འདྲིས་བསྟན་པ་ཡིན་ན་ང་ཟེར་ཡག་གི་བློ་དེ་ཤུགས་ཆུང་དུ་འགྲོ་བསྡད་ཡོད་རེད།
06:29 ད་དེ་ནས་རིམ་པ་གཉིས་པ་དེ་སླེབ་དུས། ཨེ་ད་ང་ལ་ཡིད་དུ་འོང་བ་སྣང་གིན་འདུག ང་ལ་ཡིད་དུ་མི་འོང་བ་སྣང་གིན་འདུག་ཅེས་ནས
06:39 ཟེར་བསྡད་ཡག་གི་སྣང་སའི་སྔོན་ལ་ང་དེ་ཨེ་གང་ཟག་གི་བདག་མེད་སྒོམ་པའི་སྟེང་ནས་ཁོ་ཤུགས་ཆུང་དུ་བཏང་བ་ཙམ་དུ་མ་ཟད། 
06:47 གང་སྣང་རྒྱུའི་གཅིག་ཨེ་ནས་ཡིད་དུ་འོང་བ་དང༌། ཡིད་དུ་མི་འོང་བ་ཆོས་དེ་དང་དེ་ལས་བདག་མེད་པ་ཞིག་བསམ་བློ་བཏང་ན།
06:55 ཤུགས་ཆེ་རུ་འགྲོ་བསྡད་འདུག་ག ད་ཆོས་ཀྱི་བདག་མེད་གསུངས་ཡག་དེ་འདྲའི་དེ་ཡིན་པ་རེད། ཨོ་ད་ཕུང་སོགས་ཀྱིས་བསྡུས་པའི་ཆོས་དེ་གས་དེ
07:03 ང་ཨེ་ནས་ད་ག་རེ་ཟེར་དགོས་རེད་ཐད་ཀ་ཐད་ཀར་གསུང་སྟངས་ཀིས་དཔེར་ན་ང་ཇི་ལྟར་སྣང་བ་ནང་བཞིན་བདེན་པར་མེད་པ།
07:11 ད་ངས་ཡང་དབུ་མ་པའི་བཤད་ཡག་གི་བདེན་པར་མེད་པ་ཟེར་ཀིན་མེད་མདའ། ཨེ་ཁོ་རང་ཁོ་སྐབས་ཐོབ་ཀྱི་ཡང་ཁོང་རང་དཔེར་ན་བསམ་བློ་གཅིག་བཏང་པ་ཡིན་ན། 
07:18 ང་ཟེར་ནས་ཚུགས་ཐུབ་བདེན་པ་འདྲ་བོ་དེ་མེད་པ་གཅིག་མཐོང་བ་ཙམ་དུ་མ་ཟད་པས། ང་དེས་ལོངས་སྤྱད་བྱའི་ཆོས་དེ་ཚུགས་ཐུབ་ཨ་འཐས་བདེན་པ་ཡོད་མ་རེད་ཟེར་ཡག་གཅིག
07:27 ད་དེ་བསྒྲུབ་ཡ་ལ་སྒྲུབ་བྱེད་གཅིག་དེ་ཨེ་ནས་ཕྱི་རོལ་དོན་དུ་གྲུབ་པ་ཡོད་མ་ཟེར།
07:33 རེད་བ་དེ་ཐམས་ཅད་ལོག་ཨེ་ནས་ག་རེ་ཟེར་བ་རེད། ཕ་གིའི་ཡུལ་དེ་དང་དེའི་ཕུང་སོགས་ཀྱི་ཆོས་དེ་དང་དེ་གཉིས་འཇལ་བྱེད་ཀི་
07:42 བློ་ཁོང་རང་གི་སྟེང་ནས་བག་ཆགས་སད་པ་ཙམ་མ་གཏོགས་ཨེ་ཨེ་བློ་དེ་ལ་སྣང་རྒྱུའི་དངོས་པོ་རང་མཚན་པ
07:52 ཨེ་འདིའོ་ཟེར་བྱས་ནས་འདི་དང་འདི་ཟེར་བྱས་ནས་ཕྱི་རོལ་ནས་ཁོང་རང་ཚུགས་ཐུབ་པ་གཅིག་གྲུབ་བསྡད་པ་གཅིག་ཡོད་མ་རེད་ཟེར་ནས་ལབ་པ་ཡིན་ན།
08:00 ཧ་ལམ་ཧ་ལམ་ད་རྨི་ལམ་གྱི་སྣང་བ་འདྲ་བོ་རེད་ཟེར་ནས་ལབ་པ་ཡིན་ན་དཔེར་ན་ང་རང་ཚོའི་བློ་ཕལ་པ་གཅིག་ཡིན་པ་ཡིན་ནས་རྨི་ལམ་གྱི་སྣང་བ་ལ་ཆགས་སྡང་སྐྱེས་ན། 
08:09 ཁོ་གཉིད་སད་པའི་གནས་སྐབས་ཨེ་ནས་ཆོ་ག་རེ་ཡོད་རེད་ཟེར། དེ་ང་རང་ཤེས་པ་ལ་ཡ་སྣང་བསྡད་པ་ཙམ་རེད་ཟེར་ཡག་མ་གཏོགས་ཡོང་གི་མ་རེད་བ།
08:15 ཕྱི་རོལ་གི་དགྲ་དང་གཉེན་ཟེར་ནས་མཛུབ་ཀུ་འཛུགས་ས་གཅིག་ཡོད་བསྡད་པ་དེ་ལ་ཡ་ཆགས་སྡང་ཤུགས་ཆེ་བ་སྐྱེས་བསྡད་ཡག་གཅིག་འདུག་ག ད་ང་ཚོའི་མཛུབ་ཀུ་འཛུགས་སའི་ཆགས་སྡང་སྐྱེས་སའི་ཡུལ་དེ་གས་དེ། 
08:25 རང་གི་ཨེ་ག་རེ་ཟེར་དགོས་རེད། ཨེ་རང་གི་བློ་ཡི་སྟེང་ནས་ཨེ་ནས་བག་ཆགས་སད་པ་ཙམ་རེད་ཟེར། རང་གི་སེམས་ཀྱི་སྣང་ཆ་ཙམ་རེད་ཟེར་ནས་ལབ་པ་ཡིན་ན། 
08:35 ཨེ་ཕྱི་རོལ་ཨེ་ནས་ཕྱི་རོལ་ཕྱི་རོལ་ནས་ཚུགས་ཐུབ་ཏུ་གྲུབ་བསྡད་མཁན་བདེན་པ་བ་གཅིག་ཡོད་པར་ཞེན་ནས་ཆགས་སྡང་། 
08:43 སྐྱེ་བསྡད་ཡག་དེ་ཉུང་དུ་འགྲོ་ས་རེད། ད་ཨོ་འདུག་སེ་བྱས་ནས། ཨེ་ནས་སེམས་ཙམ་པའི་གཞུང་གི་སྐབས་ནས།
08:50 ཨེ་ད་ཆོས་ཀྱི་བདག་མེད་གསུངས་ཡག་དེ་ཡིན་པ་རེད། ཕུང་སོགས་ཀྱི་ད་ཆོས་ཨེ་ནས་དེའི་ནང་ཚན་ད་ཕུང་སོགས་ཆོས་དེ་གས་དེ་ཨེ་ནས་སྣང་བ་ནང་བཞིན་གྲུབ་པ་གཅིག་ཡོད་མ་རེད་ཟེར་ཡག་གཅིག་གི
09:00 ད་སྣང་བ་ནང་བཞིན་ཟེར་དགོས་རེད་བས། ད་སྣང་བ་ནང་བཞིན་ག་བ་སྦྱར་ནས་སྦྱར་ཆོག་གི་འདུག་ག བྱས་ནས་ཨོ་དེ་འདྲས་ཀི་སྟེང་ནས་ཆོས་ཀྱི་བདག་མེད་ཅེས་གསུངས་བསྡད་ཡག་དེ་ཡིན་པ་རེད། ཁོ་ཐབས་མཁས་པ་རེད་འདུག་ག། སེ་དེ་འདྲས་ཡིན་དུས་གང་ཟག་གི་བདག་མེད་དང༌། ཆོས་ཀྱི་བདག་མེད་ཟེར་ནས་གཉིས་བཤད།
09:10 ཨེ་ཆགས་སྡང་སྐྱེ་མཁན་གི་ང་ཨེ་ཆགས་སྡང་སྐྱེ་སའི་ཡུལ་དེ་གཉིས་ཀ་ལོག ཨེ་ནས་རང་ག་རེ་ཟེར་དགོས་རེད་རང་དབང་བ། 
09:19 བདེན་པ་བ་ཡོད་མ་རེད་ཟེར་ཡག་ག [...]

2023-05-20 10:51 UTC, closed without merging