ten norbu
MonlamAI/STT001 pull request #5
Opened 2023-01-17 16:36 UTC by Tennorbu132

this is mp3-10
done in one week and it contain 8:42 mins

2023-03-22 09:55 UTC, Tsering86 requested changes
གུག་རྟགས་<>འདི་ནོར་བ་ཡིན།   གུག་རྟགས་( ) འདི་བཟོ་བཅོས་བརྒྱབ་ཟིན་པ་ཡིན།
<00:00 ཏ་ཁོ་བློ་སྐད་ཅིག་སྔ་མ་དེ་ལོག་ཤེས་རེད་བ་ཐ་> (དཱ་ཁོ་བློ་སྐད་ཅིག་སྔ་མ་དེ་ལོག་ཤེས་རེད་བ། ཁོ)

2023-03-23 08:06 UTC, Tsering86 reviewed
<་བློ་སྐད་ཅིག་་ཕྱི་མ་དེ་བློ་ཡང་དག་པ་ཆག་སྡོད་ཡོད་ར་་>
(བློ་སྐད་ཅིག་ཕྱི་མ་དེ་བློ་ཡང་དག་པ་ཆགས་སྡོད་ཡོད་རེད་བ)

2023-03-23 08:15 UTC, Tsering86 reviewed
<་བློ་སྐད་ཅིག་་ཕྱི་མ་དེ་བློ་ཡང་དག་པ་ཆག་སྡོད་ཡོད་ར་་>
(བློ་སྐད་ཅིག་ཕྱི་མ་དེ་བློ་ཡང་དག་པ་ཆགས་སྡོད་ཡོད་རེད་བ)

2023-03-23 08:30 UTC, Tsering86 requested changes
<བློ་སྐད་ཅིག་་ཕྱི་མ་དེ་བློ་ཡང་དག་པ་ཆག་སྡོད་ཡོད་ར་་་>
(བློ་སྐད་ཅིག་ཕྱི་མ་དེ་བློ་ཡང་དག་པ་ཆགས་སྡོད་ཡོད་རེད་བ)
<མེ་དམར་ལམ་པ་མཐོང་སྡད་ངན་གྱི་དེ་ཡི་དྲངས་པའི་ཡིད་བློ་འདི་ཁ་ཀྱང་ཀྱང་ཅིག་མ་ཏོག་>
(མེ་དམར་ལམ་མེར་མཐོང་མཁན་དེ་ཡིས་དྲངས་པའི་ཡིད་དེ་ག་་རྐྱང་རྐྱང་ཅིག་མ་གཏོགས་ཚད་མ་ཚད་མིན་གྱི་དབྱེ་བ་དེ་ཕལ་ཆེར་ཕྱེས་ཡ་ཁག་པོ་རེད་ཤག)

2023-06-26 05:44 UTC, geshecelon requested changes
26 June, 2023 stt001-15
00:00 དྲང་སྲོང་སེར་སྐྱའི་རྗེས་སུ་འབྲངས་པ་འདི་༼དེ་༽༑ ཤེས་བྱ་ཉི་ཤུ་རྩ་ལྔར་གྲངས་ངེས་པར་འདོད་ལ། དེ་ཡང་བདག་དང༌། གཙོ་བོ་དང༌། ཆེན་པོ་དང༌། ང་རྒྱལ་དང༌། དེ་ཙམ་ལྔ་དང༌། དབང་པོ་བཅུ་གཅིག་དང༌། འབྱུང་བ་ལྔ་སྟེ་ཉི་ཤུ་རྩ་ལྔ་།
 00:15 །དེ་ཙམ་ལྔ་ནི། གཟུགས་སྒྲ་དྲི་རོ་རེག་ ཐ་དེ་དམིགས་བསལ་ཞུས་ཡ་མིན་འདུག་ཨ་ད་བློ༼ཀློག་བཅས་གལ་དགོས་ཀྱི་ཨ་ཡོད༽་་་་་་་། །ད་དབང་པོ་བཅུ་གཅིག་བྱས་ དེ་ནས་དབང་པོ་བཅུ་གཅིག་ནི། འོ་རེད་དབང་པོ་བཅུ་གཅིག་
 00:30 ད་དེ་ནས་ བློའི་དབང་པོ་ལྔ་ ལུས་ཀྱི་དབང་པོ་ལྔ་ ཡིད་ཀྱི་དབང་པོ་བྱས་ །བློའི་དབང་པོ་ལྔ་ནི། མིག་རྣ་སོགས་བྱས་༼ཚགས་དུང་མི་དགོས༽།
 00:39 ལུས་ཀྱི་དབང་པོ་ལྔ་ནི། ངག་ ལག་པ་ རྐང་པ་ རྐུབ་ འདོམས་བྱས་༼ཚགས་དུང་མི་དགོས༽། །འབྱུང་བ་ལྔ་ནི། ས་ཆུ་མེ་རླུང་ནམ་མཁའ་༼ཚགས་དུང་མི་དགོས༽།
 00:51 །ད་ནམ་མཁའ་ཕལ་ཆེར་བུ་ག་ནམ་མཁའ་ཞེས་པ་དེ་བཞག་གི་མེད་འགྲོ། འབྱུང་བ་ལྔ་ ཡང་ན་གོ་བརྗེས་པ་༼ཙམ་༽ཟེར་པ་༼ཟེར་པ་འདི་མེད་པ་ལྟ་བུ་མཐོང་།༽བསམ་བློ་གཏོང་གི་ཡོད་ན་། 
 01:13 གཞན་རྣམས་ཀུན་རྫོབ་བདེན་པར་འདོད་དོ། ༼འེ།༽།བྱས་ཙང་ བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་ནི་མུ་སྟེགས་གྲངས་ཅན་པས་ཤོདཡོང་་ཀྱི་འདུག་ཨ་། 
01:37 འབྲས་བུ་ཡིན་ལ་རྒྱུ་མ་ཡིན་པ། རྒྱུ་འབྲས་གཉིས་ཀ་མ་ཡིན་པའི་མུ་དང་བཞི་ཡོད་དེ། དང་པོ་ནི། སྤྱི་གཙོ་བོ་དང༌། སྤྱི་གཙོ་བོ་དེ་ཐམས་ཅད་ཏ་སྤྲུལ་མཁན་༼ཚགས་དུང་མི་དགོས༽།

02:19 ཨ་ནི་འབྲས་བུ་ཡིན་པའི་༼ཡིན་ལ་༽རྒྱུ་མ་ཡིན་པ་། ལྷག་མ་བཅུ་དྲུག། རྒྱུ་འབྲས་གཉིས་ཀ་མ་ཡིན་པ་མུ་བཞི་། བྱས་ཙང་ཀ་རྣམ་འགྱུར་གྱི་གཙོ་བོ་སྤྲོད་པ་བྱས་
02:30 གཙོ་བོ་གར་ཟེར་གོ་ད་། སྤྱུད་༼སྤྲུལ་༽པ་སྤྱུད་༼སྤྲུལ་༽པར་བྱས་། སྐྱེས་བུ་འདི་་གཙོ་བོའི་སྤྲུལ་པ་མོད་མི་བྱས་པར་ཐ་མངོས་ནས་ཡོད་པ་ཡིན་ན་། 
02:40 ཏ་གང་ལྟར་ རང་བཞིན་ གཙོ་བོ་ གཙོ་བོའི་རང་བཞིན་འདྲ་པོ་དེ་མཐོང་བྱས་། བྱས་ཡོང་དུས་ཨ་ནི་རིམ་པས་གི་ཅིག་སྤྲོས་པ་དེ་གས་དེ་ཕ་ནུབ་འགྲོ་ཡ་ཅིག་གི། ཨ་ནི་དེ་ཤེས་༼བཤད་༽པ་ཡིན་གི་མ་རེད་
02:55 ཨཨཨཨ་སྐྱེས་བུ་    དེ་ཡང་མངོན་ཙུག་ནམ་མཁའ་ཀུན་ནས་ཙག་ཡ་ཏ་དེ་བྱས་ དེ་ཡང་རྩ་བའི་རང་བཞིན་དང༌། སྤྱི་དང༌། གཙོ་བོ་རྣམས་དོན་གཅིག་ཡིན་ཞིང་ཁྱད་ཆོས་བཅོ་དྲུག་དང་ལྡན་པའི་ཤེས་བྱ་ཞིག་ལ་༼ཚགས་དུང་མི་དགོས༽།  ཁྱད་ཆོས་དྲུག་དང་ལྡན་པའི་ཤེས་བྱ་ཞིག་ལ་འདོད་༼ཚགས་དུང་མི་དགོས༽། 
03:10 །ཏ་ཁྱད་ཆོས་དྲུག་འདི་འགྲེལ་བ་བརྒྱད་ཟེར་ན་མེད་གར་ཟ་ འ་གྲུབ་མཐའ་རྒྱས་པ་དེ་ཚོས་ནང་ཡོད་ཀྱི་རེད༌༼ཚགས་དུང་མི་དགོས༽། སྐྱེས་བུ་དང༌། བདག་དང༌། ཤེས་པ་དང༌། རིག་པ་རྣམས་དོན་གཅིག་།  

03:31 གང་གི་ཚེ་སྐྱེས་བུ་དེས་ཡུལ་ལ་ལོངས་སྤྱོད་པའི་འདོད་པ་སྐྱེས་པ་ན། རྩ་བའི་རང་བཞིན་གྱིས་སྒྲ་ལ་སོགས་པའི་རྣམ་འགྱུར་རྣམས་སྤྲུལ་པར་བྱེད་དོ། །ཏ་གཙོ་བོའི་ངང་ལས་དེ་དག་༼དེ་གས་འདི་༽ཤར་ཡོང་ཡ་ཅིག་༼ཚགས་དུང་མི་དགོས༽། 
03:41 ཏ་གཙོ་བོས་ཅིག་ ཅིག་སྤྲུལ་༼སྤྲུལ་༽འདོད་ཅིག་ཡོང་བ་ཡིན་ན་ ག་འདྲ་ཡིན་ན་དེ་ རྩ་བའི་རང་བཞིན་གི་དྲ་ལ་སོགས་པའི་རྣམ་འགྱུར་རྣམས་སྤྲུལ་པར་བྱེད་དོ་

04:01 ཏ་དེ་བ་བཤད་ཡ་༼སེ་གལ་༽མིན་འདུག་ ཀློག་མ་དགོས་པ་བྱས་ཏ་༼འ་འ་འ།༽ང་རྒྱལ་ལ་དབྱེ་ན། རྣམ་པར་འགྱུར་བ་ཅན་གྱི་ང་རྒྱལ་དང༌། སྙིང་སྟོབས་ཅན་གྱི་ང་རྒྱལ་དང༌། མུན་པ་ཅན་གྱི་ང་རྒྱལ་ ཏ་བྱས་ན་གལ་མིན་འདུག་དབང་པོ་བཅུ་གཅིག་།

04:24 རང་བཞིན་གཙོ་བོ་དེ་དང༌། སྐྱེས་བུ་གཉིས་པོ་དེ་གཅིག་ཏུ་འཁྲུལ་ཏེ་ཟེར་བ་ཡིན་ན་༼ཟེར་དགོས་ཀྱི་ཡོད་ན།༽། རྣམ་འགྱུར་རྣམས་རྩ་བའི་རང་བཞིན་གྱིས་སྤྲུལ་པའི་ཚུལ་མ་ཤེས་པའི་དབང་གིས་འཁོར་བར་འཁོར་བ་འདོད་དོ། 

04:52 ཏ་འདི་ཞི་གནས་སྒྲུབ་ཡ་ནང་པ་དང་གཅིག་པ་ཡིན་གྱི་རེད།  བསམ་བསྟན་༼བསམ་གཏན་༽ལ་སྟེན་༼བརྟེན་༽ནས་ཨ་་་ཨ་ནི་མངོས་ཤེས་༼མངོན་ཤེས་༽དེ་འགྲུབ་ 
05:02 ཨ་དེ་ལས་མངོས་ཤེས་༼མངོན་ཤེས་༽ཀྱི་གཙོ་བོ་ལ་བསྟས་པ་ན་གཙོ་བོ་དེ་གཞན་གྱི་བུད་མེད་ལྟར་ངོ་ཚ་བས་སྐྱེངས་ཏེ་རྣམ་འགྱུར་རྣམས་ཉེ་བར་བསྡུས་ཏེ། རང་བཞིན་ཡན་གར་བར་གནས་ཤིང༌། 
 
05:21 །ཨམ་ཡ་ཏ་ ཏ་དེ་གི་གོང་མ་དེ་དང་འདི་གཉིས་ཅ་ལོགས་ཀྱི་སྐྱེ་བ་སྔ་ཕྱི་འདོད་བསྡས་ངན་༼བསྡད་མཁན་༽ ལས་འདོད་བསྡས་༼བསྡད་༽པ་། 
05:33 ལས་རྒྱུ་འབྲས་ཀྱང་བཤད་འདོད་པ་ཞིག་འདུག་པ༼ཟེར་དགོས་ཀྱི་ཡོད་ན།༽། ཨ་ནི་དེ་ནས་ གཉིས་ཀར་༼གཉིས་ཀ་ལོགས་ཀྱི་ཕལ་ཆེར། གཉིས་ཀ་ཟེར་དགོས་ཡོད་ན་༽་ཟེར་ལགོས་ཡོད་ན་ ཕལ་ཆེར་ཐར་པ་ཐོབ་པ་ཅིག་༼ཡེ་༽ཤོད་ཀྱི་འདུག་བ་
05:45 བྱས་ནས་ཏ་ དེ་འདྲ་ཅིག་མ་རེད་ ཞེས་་འདོད་དོ་ ད་དེ་གི་གཉིས་ཆ་ལོག་སྐྱེས་བ་སྔ་ཕྱི་འདོད་བསྡས་ངན་ཆགས་གི་ཡོད་རེད་  
05:56 ཏ་དེ་ནས་དཔྱོད་པ་བ་ནི་ རྒྱལ་དཔོག་པའི་རྗེས་སུ་འབྲངས་པ་སྟེ། རེག་བྱེད་ལ་གང་སྣང་བ་ནི་རང་བྱུང་ཡིན་ཏེ། ༼འེ་༽དེ་ནི་དེ་ཁོ་༼ན་༽ཉིད་
06:07 ཡིན་ནོ་ཞེས་སྒྲོ་བཏགས་ནས་མཆོད་སྦྱིན་ལ་སོགས་པ་འབའ་ཞིག་གིས་མཐོ་རིས་ཀྱི་གོ་འཕང་ཐོབ་པར་འདོད་ལ་དེ་ནི་ངན་སོང་ལས་གྲོལ་བའི་ཐར་པ་ཙམ་དུ་ཁས་ལེན་ནོ། ༼ཤད་གཉིས་དགོས་༽ ༼དེ་ནི་ངན་སོང་ལས་གྲོལ་བའི་ཐར་པ་ཙམ་དུ་ཁས་ལེན་ནོ། །༽
06:21 ཅིག་ཏ་ལྷ་ཡི་ཕུན་ཚོགས་ཅིག་ཐར་པ་བྱེད་དགོས་ཡོད་ན་ དེ་ནི་ངན་སོང་ལས་གྲོལ་བའི་ཐར་པ་ཙམ་དུ་ཁས་ལེན་ནོ།༼ཤད་གཉིས་དགོས་༽བ་ཤིག་༼འབའ་ཞིག་༽གི་ཆོས་སྦྱིན་བ་ཤིག་༼འབའ་ཞིག་༽གི་མཐུ་རིགས་གི་གོ་འཕང་ཐོབ་པ་འདོད་ལ། དེ་ནི་ངན་སོང་ལས་གྲོལ་བའི་ཐར་པ་ཙམ་དུ་ཁས་ལེན་ནོ། ༼ཤད་གཉིས་དགོས་༽
06:35 འོན་ཀྱང་སྡུག་བསྔལ་ཉེ་བར་ཞི་བའི་ཐར་པ་ནི་མེད་དེ། ཨ་ལེ་མུ་སྟེགས་དཔྱོད་པ་བས། དྲི་མ་སེམས་ཀྱི་རང་བཞིན་གྱི་ཞུགས་པ་རེད། དེ་འདྲ་ཡིན་དུ་06:47༼ག་རེ་ཟེར་དགོས་རེད། ག་རེ་ཟེར་དགོས་རེད་༽སེམས་མ་གསོད་༼ཟད་༽བར་དུ་དྲི་མ་གསོད་༼ཟད་༽ཡ་ཡོད་མ་རེད་ཟེར་ཡ་ཅིག། དྲི་མ་སེམས་ཀྱི་རང་བཞིན་ལ་ཞུགས་པའི་ཕྱིར་དང་ཐམས་ཅད་མཁན་པ་ཡང་མེད་དེ། ཤེས་བྱ་མཐའ་ཡས་པའི་ཕྱིར་རུ། དེ་བས་ན་བདེན་པའི་ངག་ཀྱང་མེད་དེ་༼དོ་༽ཞེས་སྨྲའོ།༼ཤད་གཉིས་དགོས་༽
I will do the rest of the others later on. Kindly listen carefully and fix them properly. There could be many other things to do.

2023-06-26 11:49 UTC, geshecelon requested changes
07:10 ཏ་གྲངས་ཅན་ལྷ་མེད་པ་བྱས་ནས་ཨ་ནི་གཙོ་བོའི་རྣམ་གཞག་ནས་བྱས་རྗེས་གྲུབ་མཐའི་རྐང་འཛིན་མཁན་ངན་༼དེང་སང་ཡོད་ཡིན་ན་མེད་ཡིན་ན་༽ཡོད་ན་མེད་ན་ཤེས་ཡང་མི་ཤེས།
07:56 ཨ་ནི་དཔེ་ཆའི་བསྔོག་ས་དེ་ནང་པའི་གཞུང་ཅིག་ཏ་བྱས་ ནང་པའི་གཞུང་ནས་མུ་སྟེགས་པའི་འདོད་པ་བཀོད་ཡོང་དུས་ཙ་ནས། ཕར་དགག་པ་རྒྱབ་ཡ་གཙོ་བོར་ར་ཅིག་ོ༼ར་བོ་་ཅིག་༽གསུངས་བཞག་པ་མ་གཏོགས་
08:05 དེ་པའི་ལུགས་ཆ་ཚང་བ་ཅིག་ཕལ་ཆེར་གསུངས་ཡོད་ཀྱི་མ་རེད་བསམ་གྱིས། གསུངས་ཨ་ཡོད་བསམ་གྱི། བྱས་ཙང་ཏ་རང་ལུགས་ མུ་སྟེགས་པའི་གཞུང་དེ་ཚོས་རང་ལུགས་རང་བྱས་དུ་ཟིམ་ངན་༼ཟིམ་མཁན་༽ཚོར་གཏུགས་ནས།
 
08:36 ཡང་མུ་སྟེགས་པའི་མུ་སྟེགས་རྟོག་གེ་བསྟེན་ངན་༼རྟོག་གེ་སྡེ་ལྔ་༽ཟོར་འདྲ་བོ་རང་རང་སོ་སོར་ལུགས་མ་འདྲེས་བྱས་ནས་འཛིན་མཁན་དེ་འདྲ་ག་འདྲ་ཡིན་ན། ཏ་མང་ཆེས་ཡི་ཅིག་ཚངས་པ་ལ་གསོལ་་སྡོད་ཡ་ཟོར་འདྲ་བོ། ཅིག་དབང་ཕྱུག་གསོལ་སྡོད་ཡ་འདྲ་བོ་མང་ཆེས་དེ་འདྲ་ཟོར་རོ་འདྲ་བོ་སྡོད་བསྡད་ཀྱི་འདུག་ཨ། ཞིབ་ཚགས་པོ་ཅིག་ཡོད་མེད་མ་ཤེས།  ཏ་དེ་འདྲ་ཅིག་རེད་བཞག།༼ཤད་མི་དགོས།༽
08:53  ཏ་དེ་ནས་ཏ་གཅེར་བུ་བ། ཏ་གཅེར་བུ་བ་སོ་སོ་རང་རྐང་རོ་ཟིམ་ནས་སྡོད་ཀྱི་འདུག་ཨ་རྒྱ་གར་ནང་ལ་ཡ། ཨ་གཅེར་བུ་བ་ནི་རྒྱལ་བ་དམ་པའི་རྗེས་སུ་འབྲངས་བ་ཏེ། ཤེས་བྱ་ཐམས་ཅད་དོན་འགུར་འདུས་པ་འདོད་དེ། སྲོག།༼ཤད་མི་དགོས།༽ ཟག་པ་༼ཚགས་དུང་མི་དགོས༽། སྡོམ་པ་༼ཚགས་དུང་མི་དགོས༽། ངེས་པར་༼ངེས་པར་༽རྒ་བ་ཡིན་ན། 
09:19 ཏ་ངེས་པར་རྒ་བ། འཆིང་་༼ཚགས་དུང་གཉིས་མི་དགོས༽བ་། ལས་དང། སྡིག་པ་དང་། བསོད་ནམས་དང་། ཐར་པ་རྣམས་ཁོ་ དེ་དག་དེ་ལ་སྲོག་ནི་བདག་ཡིན་ལ་སྐྱེས་བུ་རྣམས་ནི་ལུས་ཀྱི་ཚད་ཇི་ལྟར་བ་བཞིན་དུ་ཡོད་པ་ངོ་བོ་རྟག་ལ་ཏ་སྐྱེས་བུ་ངམ་གང་ཟག་ཟེར་ཡ་འདི་ཏ་ལུས་པོ་ཆེས་ཆུང་ག་རེད་ཡོད་ནས་དེ་ལ་ཀུན་ཏུ་ཁྱབ་བསྡད་ཉན་ཅིག་གི་སྐྱེས་བུ་དེ་འདྲ་ཅིག་ཡོད་རེད་ཟེར་ཡ་ཅིག།༼ཤད་མི་དགོས།༽ 
09:40 ཕྱི་རྟགས་བཞིན་དུ་ཡོད་པ་ངོ་བོ་རྟགས་ལ་གནས་སྐབས་མི་རྟག་པའི་རང་བཞིན་ཅན་ཡིན་ནོ། ༼ཤད་གཉིས་དགོས།༽ཟག་པ་ནི་ཏ་དེ་ལ་ལབ་ཡས་ག་མིན་འདུག་༼ཚགས་དུང་མི་དགོས༽ ཟག་པ་བྱས་༼ཤད་དགོས།༽  སྡོམ་པ་བྱས། སྡོམ་པ་ད་ལྟ་གཅེར་བུ་པའི་ཨ་ཅིག་ཏ་རབ་བྱུང་ཕོ་མོ་དེ་ཚོས་འདྲེན་ཧ་ལས་པའི་བསླབ་ཁྲིམས་སྲུང་གི་འདུག་བ་༼ཚགས་དུང་མི་དགོས༽། 
10:00 ཨ་ནི་དཀའ་ཐུབ་ཞེ་བོ་སྤྱད་ཡ་ཅིག། ཏ་དེ་ངེ་པར་རྒ་བ་ཟེར་ཡ་འདི་སྐོམ་མི་འཐུང་གང་འདྲ་ཡིན་ན་མི་ཤེས་ཏེ། གང་ལྟར་༼འེ་༽ལུས་གདུང་བ་ལ་སོགས་པ། ༼འེ་༽ཏ་ལྟ་དུས་དེ་ཡང་༼དཀའ་ཐུབ་བསྟན་ཡ་༽ཤུགས་ཆེན་པོ་ཞེས་བོ་ཡོད་ས་རེེད། སྐྲ་སྦལ་བ་དེའི་ཡོད་ས་རེད། 
10:22 ལར་ནས་ད་ལྟ་མུ་སྟེགས་པའི་ཅིག་ཚངས་སྤྱོད་༼ཚངས་སྤྱོད། ཚངས་སྤྱོད་༽དེ་ཚོས་འདྲེན་༼དེ་ཚོ་གྲས་༽འདི་འདོད་ཆུང་ཆོག་ཤེས། ཏ་མིན་དངུལ་ཁང་ནང་ལ་དངུལ་མང་པོ་འདྲ་མེད་འགྲོ་ཁ་ཤས་ག་འདྲ་ཡིན་མ་ཤེས་ཏ། མ་གཏོགས་གཞན་ཉིན་རེ་ཉིན་རེ་ཅིག་ཟས་གོས་རྒྱུ་ནོར་ལོངས་སྤྱོད་དེ་ཚོས་འདྲེན་དེ་གས་འདི་དངོས་ནས་རང་ཆོག་ཤེས་ཧ་ལས་པ་རེད་བཞག།༼ཤད་མི་དགོས།༽
10:47 ད་ལྟ་མེ་གས་མདྷ་ར་སེ་འཁྲིས་དེ་གར་ཟ་ཅིག་པོན་ཌ་སྤྱ་རི་རེད་བས། ཏ་མེ་གར་མདྷ་ར་སེ་མེ་གས་ད་ལྟ་དེ་ཅིག་ཡོད་རེད་ ག་ཟེར་བོ་བླ་ཆེན་ཅིག་ཡག་པོ་ཞེས་༼ཞེད་༽པོ་འདུག། ༼ཤད་མི་དགོས་༽
11:05 ང་འདི་ངོས་ཤེས་ཏ་ཧ་ལས་པ་རེད་ བྱས་ཙང་ཁོས་ཀྱི་བློ་རྒྱུས་དང་ཞོ་གོར་ཁྲིམས་ཐོག་ལ་རྙོག་གྲ་བྱུང་སོང་མ་གཏོགས་དེ་ཁོ་རང་ཕྱ་རྫོད་དེ་གི་རྙོག་གྲ་འདྲ་བོ་ཅིག་བྱུང། ཨ་ནི་འདི་ཅིག་ཅིག་བྱས་བྱུང་པར་ཏ་ཁོ་གང་ལྟར། དངུལ་གྱི་ཐོག་ནས་རྙོག་གྲ་ཅིག་བྱང་པར་རེད། ཞེས་༼ཞེད་༽བོ་ཡག་པོ་རེད་བཞག་དངོས་གནས་ཅིག་པས་འཕགས་པའི་རིགས་བཞི་ལ་གནས་པ་ནང་བཞིན་རེད་བཞག་ཡག་པོ་ཞེས་༼ཞེད་༽པོ་འདུག།༼ཤད་མི་དགོས།༽
11:28 བྱས་ནས་རྒ་བ་ཟེར་ཡ་དེ་ད་ག་རང་བྱེད་ ངེས་པར་རྒ་བ་ནི་ སྐོམ་མི་འཐུང་བ་དེ་ཤེས་མི་སོང་ཏེ་ ལུས་གདུང་བོ་ལ་སོགས་པའི་སྐ་ཐུག་༼དཀའ་ཐུབ་༽གི་གོ་ནས་སྔོན་བསགས་པའི་རྒྱ་གར་ཆུ་མ་འཐུང་ཅིག་ཏ་ཙ་ཨ་ཡོད། ཆུ་ག་དུས་ཡིན་ནས་འཐུང་སྡོད་ཀྱི་མ་གཏོགས་དེར་བརྟེན་སྐོམ་མི་འཐུང་ག་དུས་ཡིན་ན་མ་ིཤེས། ཏ་ཁོ་རང་དམིགས་བསལ་གྱི་སྨྱུང་གནས་དེ་བྱེད་པའི་སྐབས་སུ་ལ་མིན་འགྲོ། 
11:46 ཨ་ལུས་གདུང་བ་སོགས་པའི་དཀའ་ཐུབ་ཀྱི་སྒོ་ནས་སྔོན་བསགས་པའི་ལས་རྣམས་ཟད་བར་བྱེད་པའོ།༼ཤད་གཉིས་དགོས།༽ འཆིང་བ་ནི། ཨ་ནི་ག་མིན་འདུག་ ལོག་ལྟ། སྡིག་པ། ཆོས་མིན། བསོད་ནམས། ཐར་པ། ལུས་གཅེར་བོ་དང་ངག་མི་སྨྲ་བ་དང་མེ་ལྔ་བརྟེན་པ་དེ་རང་མཐོང་མ་སོང་། 
12:04 མེ་ལྔ་བརྟེན་པ་༼ཚགས་དུང་མི་དགོས།༽། ཏ་རྗོན་ཤིང་སེམས་ལྡན་ཟེར་ཡ་འདི་སྒྲུབ་ཡ་འདི་མཚན་མོ་༼མཚན་མོ་༽ལོ་མ་འཁུམ་ནས་ཉལ་ཕྱིར་ཟེར་ཡ་ཅིག་རྒྱུ་མཚན་དེ་འདྲ་ཡི་འུ་ཐུག་པོ་ཅིག་རྒྱུ་མཚན་བཀོད་ཀྱི་མིན་འདུག་ཨ་༼ཚགས་དུང་མི་དགོས།༽། འདུ་ཤེས་མི་འདྲ་བ་བཅོ་བརྒྱད་ནས་བཤད་ཡོང་གི་ཡིན་༼ཚགས་དུང་མི་དགོས།༽། འདུ་ཤེས་མི་འདྲ་བ་བཅོ་བརྒྱད་ནས་བཤད་ནས་༼ཤིང་ལ་སོགས་པ་༽ཨ་ནི་ལྗོན་ཤིང་ལ་སོགས་པ་འདུག་པའི་ཁོ་འདུ་ཤེས་ཤིག་ཡོད་རེད་ཟེར་ནས་རྣམ་གྲངས་མང་པོ་ཞེས་པོ་བཤད་ཡ་འདུག།༼ཤད་མི་དགོས།༽
12:26 ད་ཉིང་དང་ཞེ་ཉིང་ནང་བཞིནཅིག་ང་ཚོས་ཕ་ཁེར་ལྦཱ་རཱ་ཎ་སིའར་གཅེར་བུ་བར་དང་དེ་འདྲ་མུ་སྟེགས་ག་རོ་ཞིག་ང་ཚོས་ཆུ་ཚོད་ཁ་ཤས་ཅིག་རུག་རུག་བྱས་སྡད་པ་རེད་། གཞན་དང་མ་འདྲ་བ་བཤད་ཡ་འདུག།༼ཤད་མི་དགོས།༽ ཡག་པོ་ཞེས་༼ཞེད་༽པ་ོབཤད་ཡ་འདུག།༼ཤད་མི་དགོས།༽ བྱས་ཙང་ང་ཚོས་དེ་ཉམས་ཞིབ་བྱེད་ཡ་གལ་ཆེན་པོ་རེད་བཞག།༼ཤད་མི་དགོས།༽ 
12:42 ༼འེ་༽ཏ་དེ་ཞུ་གུ་དེ་འོ་ཏ་༼འེས་༽ཐར་པ་ནི་གཅེར་བུ་པ་དང་ངག་མི་སྨྲ་བ་དང་མེ་ལྔ་བརྟེན་བ་༼ལ་༽སོགས་པའི་དཀའ་ཐུབ་ཀྱི་སྤྱོད་པ་བརྟེན་ནས་སྔར་བྱས་ཀྱི་ལས་ཐམས་ཅད་ཟད་ཅིང་། ལས་གསར་ཏུ་མ་བསགས་པའས་༼པས་༽འཇིག་རྟེན་ཐམས་ཅད་ཀྱི་སྟེང་ན་འདུག་པའི་གནས་༼ཚགས་དུང་མི་དགོས༽། ཏ་ཁོང་ཚོ་སྐད་ཆ་རང་མ་བྱུང་། ཏ་འཇིག་རྟེན་བཀོད་པ་པོ་ཕལ་ཆེར་མི་འགྲིགས་༼མི་འདོད་པའི་༽ཟོར་འདྲ་བོ་འདུག།༼ཤད་མི་དགོས།༽ ལས་ཀྱི་དབང་ཀྱི་འཇིག་རྟེན་འཁོར་བསྡད་པ་རོ་འཁོར་ཡ་ཡིན་པས་ཟོར་འདྲ་བོ་ཅིག།༼ཤད་མི་དགོས།༽ 
ཤད། དག་ཆ། དེ་བཞིན་སྐུ་མདུན་གྱི་ཞལ་ནས་ འེས། ཨ། ཏོག་སེ། ཞེད་པོ། འདི་ཚོ་མང་པོ་ཞིག་ནོར་འདུག རྗེས་མ་འདི་རིགས་དོ་སྣང་ཆེན་པོ་བྱེད་དགོས་པ་མཐོང་། 
Kindly pay attention on ཤད། དག་ཆ། also His Holiness’s words such as འེས། ཨ། ཏོག་སེ། ཞེད་པོ།. There are many other things. If you make such an error again and again then it takes both of our time. 

Do listen all once again. It will help you to make it more nicer.

2023-07-02 16:05 UTC, geshecelon requested changes
Date: 02 July 2023

00:00 ཏ་༼ད་༽ཁོ་བློ་སྐད་ཅིག་སྔ་མ་དེ་ལོག་ཤེས་རེད་བ་ཐ་་༼ཚགས་དུང་གཉིས་མི་དགོས།༽བློ་སྐད་ཅིག་་༼ཚགས་དུང་གཉིས་མི་དགོས།༽ཕྱི་མ་དེ་བློ་ཡང་དག་པ་ཆག་སྡོད་ཡོད་ར་་་༼ཚགས་དུང་གསུམ་མི་དགོས།༽ཡིན་ནས་འདི་ཀླད་རྩ་རང་གི་སྒང་ནས་ཕལ་ཆེར།


00:09 འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་ཁག་པོ་རེད། མེ་དམར་ལམ་པ་མཐོང་སྡད་ངན་༼བསྡད་མཁན་༽གྱི་དེ་ཡི་དྲངས་པའི་ཡིད་བློ་འདི་ཁ་༼འདི་ག་༽ཀྱང་ཀྱང་ཅིག་མ་ཏོག



00:16 ཚད་མ་དང་ཚད་མིན་གྱི་དབྱེ་བ་དེ་ཕལ་ཆེར་ཕྱེ་ཐུབ་ཡ་ཁག་པོ་རེད་ཤག བྱས་ཙང་དེ་འདྲ་ཡིན་དུ་རྩ་ནས་ཀླད་རྩ་ཀྱང་ཀྱང་སྟེང་ནས་བློའི་རྣམ་གཞག་ཆ་ཚང་ཞིག་འགྲེལ་བཤད་ད་ལྟ་རྒྱབ་ཐུབ་ཀྱི་མིན་འདུག་ཡ༼མི་འདུག་ག༽།




00:38 ཤེས་པ་ཀྱང་ཀྱང་སྒང་ལ་ལས་ཀ་བསྐུར་ནས་ལུས་པོའི་འགུལ་བསྐྱོད་མེད་པ་བྱས་ ༼འ་༽ལུས་པོའི་སྦྱོང་བརྡར་མིན་པར་བྱས་ ཤེས་པ་ཀྱང་ཀྱང་སྒང་ལ་ལས་ཀ་༼སྐུལ་བའི་རྐྱེན་ལས་ཀ་༽བསྐུལ་ནས་




00:49 དེས་རྐྱེན་པས་ཀླད་རྩ་ལ་འགྱུར་བ་འགྲོ་ཡི་འདུག་བ༼ག༽། བྱས་ཙང་ཁ་དེ་དུས་འགྱུར་བ་གཏོང་མཁན་གྱི་ཀླད་པ་དེ་དང་




00:58 འགྱུར་བ་གཏོང་བྱེད་ཀྱི་ཤེས་པ་གཉིས་པོ་དེ་ཁ་ཁག་ཡོད་པའི་ཟོ་འདྲ་༼ར་བོ་༽བུ་ཆག་རོག་༼འགྲོ་༽ཆག་རོག་༼འགྲོ་༽བྱས་ཀྱི་འདུག་པ་ མ་གཞི་ཤེས་པ་ཁོ་ཀླད་རྩ་ལ་རྟེན་ནས་ཡོང་གི་ཡོད་རེད།


01:08 ཡིན་ནས་ཡང་ཤེས་པ་དེ་ལ་སྦྱོང་བརྡར་བྱས་པའི་རྐྱེན་གྱིས་ཀླད་རྩ་ལ་ཕར་འགུལ་བསྐྱོད་ཐེབས་ཡ་ཅིག་ཡོང་ཀྱི་འདུག༼ག༽ བྱས་ཙང་ཁོ་གཉིས་བརྟེན་དང་རྟེན་པ་བྱས་ནས་འགྲེལ་བ་ཡོད་པ།



01:33 དེ་ནས་འོ་ཐ་ ད་ལྟ་འཇར་མན་འདི་ལབ་སྡོད་ཡ་སྐད་ཆ་འཕྲོ་དེ་ཡིན་ འཇར་མན་གྱི་ཀླད་རྩའི་མཁས་པ་(neurologist)༼ནི་རོ་ལོ་ཇིས་ཌི་༽ཞིག་རེད་




01:42 ཐ་གཅིག

02:02 བྱས་ཙང་དེ་ཡང་༼ཁོ་༽ཡུལ་བྱེ་བྲག་པ་དེའི་རིག་པའི་ནུས་པ་འདྲ་པོ་དེ་སྐྱོན་ཤོར་སའི་ཀླད་པ་ཁོ་ནར་ངེས་པ་རེད་མི་འདུག་ཅིང༌༼ག༽།









02:31 བྱས་ཙང་ཁ་དེ་ཀླད་རྩའི་དབུས་དེ་ལ་ཡ་ཅིག་བཀའ་གཏོང་ངན་བཟོར་འདྲ་པོ་ མི་རང་གི་འདི་ཟེར་གྱི་ (self)༼སེལ་ཕི་༽བདག་ཟེར་ཡ་འདི་




02:42 འདི་མིན་འདུག་ control or judge མིན་འདུག central commander ཟེར་ངན་འདྲ་པོ་ཅིག་མིན་འདུག་འོ་དེ་བཤད་ཡོང་གི་༼ཚགས་དུང་མི་དགོས།༽


03:04 ཀླད་པ་ཡོངས་རྫོགས་ལོག་གཅིག་ལ་ལྟོ་༼ལྟོས་༽ནས་ཕན་ཚུན་གཅིག་གི་གཅིག་ལ་བརྟེན་པའི་ཐོག་ནས་ཀླད་པའི་བྱ་བ་དེ་བྱེད་ཡོང་༼གི་༽ཀྱི་རེད་༼རེད་ཟེར་བ་མིན་འདུག༽དེ་ཤོད་ཀྱི་འདུག


03:33 ཏ་༼ཤེས་པ་༽ང་ཚོ་ནང་པའི་གཞུང་ནས་ཤེས་པ་ལ་ ལྷག་པར་སྔགས་ཀྱི་གཞུང་དང་འབྲེལ་ནས་བཤད་ཡིན་ན། ཤེས་པ་ལ་ཕྲ་རགས་མང་པོ་ཞིག་འདུག་ག

03:42 བྱས་ཙང་རགས་པའི་ཤེས་པ་དེ་དཔེར་ན་ང་རང་ཚོས་ནང་པའི་གཞུང་གི་ནང་ལོག་ནས་དབང་པོའི་ཤེས་པ་ཟེར་ཡ་འདི་དབང་པོ་ལ་བརྟེན་པས་ཤེས་པ་ཡིན་དུས་ཙ་ན། དབང་པོའི་ཤེས་པ་ཞེས་མིང་བཏགས་༼གི་༽ཡོད། ཁོ་དབང་པོ་འགགས་སོ་ན་དབང་པོར་སྐྱོན་ཤོར་ན། ཤེས་པ་ཁོ་འགགས་འགྲོ་ཡི་རེད་

03:53 ཁོ་དབང་པོ་དེ་ལ་རྟེན་ནས་ཡོང་བ་ཅིག་ཡིན་པ་ཁོ་བདག་རྐྱེན་དབང་པོ་བྱས་ནས་ཡོང་བ་དེ་ུ༼དེ་མེད་པ་བཟོ་དགོས་འདུག༽གསལ་པོ་རེད།

03:59 ཐ་ཡིད་བློ་ཡིད་དབང་ལ་བརྟེན་པ་ཞེས་ཤོད་སྡོད་ཀྱི་ཡོད་རེད། ཐ་འདི་ཡིད་བློའི་ནང་དུ་ཕྲ་རགས་མང་པོ་ཅིག་ཡོང་སྡོད་ཉན་༼བསྡད་མཁན་༽ཅིག།༼ཤད་མི་དགོས།༽
04:16 ཐ་ཇི་ཙམ་ཕྲ་རུ་ཕྲ་རུ་ཕྱིན་པའི་ཚོད་ཀྱིས་ཁོ་ཏོག་༼ཏོག་སེ་༽(autonomy)འདྲ་བོ་ཅིག་ཕལ་ཆེར་རང་སྐྱོང་འདྲ་བོ་ཅིག་ཆགས་ཡོང་ངན་། མཐར་ལ་གཏུགས་ཡོང་དུས་ཙ་ནས་ཨེ་ནས་ཕལ་ཆེར་རང་མཚན་པ་ཞིག་ཕལ་ཆེར་ཆགས་ཀྱི་ཡོད་རེད།

04:27 དེ་འདྲ་ཡིན་དུས་ཙ་ནས་ སྔ་མ་ནས་སྐྱེ་བ་སྔ་ཕྱི་མེད་པའི་སྒྲུབ་བྱེད་མཐར་ཐུག་ཤེས་པ་ཀླད་རྩ་ལ་བརྟེན་ནས་ཡོང་བ་རེད་ཅེས་ལབ་སྡོད་ཡ་དེ་ ད་ལྟ་ཐག་ཆོད་པ་ཅིག་བཤད་ཐུབ་ཡ་ཁག་པོ་རེད་བཞག

04:42 ཏ་ཡང་ཕྱོགས་གཞན་ཅིག་ནས་སྐྱེ་བ་སྔ་མ་དྲན་ངན་དེ་འདྲ་ཡོང་སྡོད་ཀྱི་འདུག་བ་༼ག༽ གསལ་པོ་ཞེས་བོ་༼ཞེད་པོ་༽ཅིག་ཡོང་གི་འདུག་བ།༼ག༽



04:51 ཏ་ཡིན་ནས་དེ་༼འེས་༽གར་ཟེར་གོ་༼ག་རེ་ཟེར་དགོས་༽རེད། ཡོད་དམ་མེད་ཅེས་ཐག་བཅད་ན།

05:17 ཏ་ཉེ་ཆར་རང་ཡང་རྒྱ་གར་གཅིག་གིས་གཞི་པོ་ཅིག་ར་འཕྲོད་པོ་ཅིག་ ཨ་ཏ་ཕལ་ཆེར་ལོ་ཉི་ཤུ་སུམ་ཅུ་གོང་ལ་རེད་ ཕལ་ཆེར་ལོ་ཉི་ཤུ་ཏ་སུམ་ཅུ་གོང་ལ་མིན་འགྲོ་ བྱས་ནས་ཡང་རྒྱ་གར་བའི་བུ་མོ་གཉིས་ གཉིས་ཅ་ལོག་ངས་ཐུག་༼སོང་།༽ཆུང་ཆུང་རེད།

05:37 སྐྱེ་བ་སྔ་མ་གསལ་པོ་ཞེས་པོ་དྲན་ནས་སྐྱེ་བ་སྔ་མ་དྲན་ཡ་ཞེས་པོ་ཞིག་གསལ་པོ་ཆགས་བྱས། སྐྱེ་བ་སྔོན་མའི་ཕ་མ་གཉིས་པོ་ལྷག་སྡོད་འདུག་བ་༼ག༽ བྱས་ཙང་སྐྱེ་བ་སྔོན་མའི་ཕ་མ་གཉིས་པོ་དེ་ཡིས་ད་ལྟ་ཕྲུ་གུ་གཉིས་པོ་ཁོ་རང་གཉིས་ཀྱི་ཕྲུ་གུ་ཡིན་པར་ངོས་འཛིན་བྱེད་བྱས།

05:50 ཏ་ཕྲུ་གུ་གཅིག་ལ་ཕ་མ་བཞི་ ཚེ་འདིའི་ཕ་མ་གཉིས་དང། ཚེ་སྔོན་མའི་ཕ་མ་གཅིག ཕ་མ་བཞི་འདུག་དེ་རྒྱ་གར་ས་ཆ་ kanpur ༼ཀཎ་པུར་༽ཟེར་ཡ་དེ་ལ་ཐུག་༼ཚགས་དུང་མི་དགོས།༽

06:30 ཨ་ནི་པ་བ་དེ་གྲོངས་ཁར་ལྷག་མོ་དེ་ཕྲུ་གུ་དེས་ལྟ་ལྷ་གང་འདྲ་ཕེབས་དགོས་རེད་ལབ་པ་རེད། ཨ་ནི་༼ཨ་ནས་༽རྐང་པའི་གཏིང་ཁ་དེ་དུག་ རྐང་པའི་རྩེ་བཙུགས་བྱས་བསྡད་ན། གང་འཚམས་ནས་འདར་སིག་རྒྱག་གི་རེད།༼ཧེ་ཧེ་ཧེ་༽



06:44 ཨ་ནི་ག་བོ་སྤོས་དཀར་མང་པོ་བདུག་ན་ཨ་སྟོང་བརྒྱབ་ཀྱི་རེད། ༼ཧེ་ཧེ་༽ཨ་ནི་ཐུག་ཁོ་ག་རོ་སྐྱོ་བྱས་ ཨ་ནི་ག་བྱུང་མ་བྱུང་ག་རོ་བཤད་བཞག་ན་ཁ་ཤས་ཁ་ཤས་ཐིག་འགྲོ་ཡི་རེད།༼ཧེ་ཧེ་༽



06:55 བྱས་ཙང་འོ་དེ་ཟོར་འདྲ་བོ་༼ཟོ་ར་བོ་༽བྱེད་བྱས་ཨ་ནི་༼ཨེ་ནས་༽ཁ་ཤས་ཁ་ཤས་ལྟ་ཁོ་ཅིག་ཡང་ཐིག་པ་ཡོང་སྲིད་གི་ར་ཏ་ཁོ། ཏ་ཡིན་ནས་ཧ་ལས་པའི་ར་འཕྲོད་པོ་ཅིག་ཏ་ང་ཚོང་བོད་པའི་ཕྱུ་གུ་ཅིག་ཡོད་རེད་ བོད་པའི་ཕྱུ་གུ་ཅིག



07:07 ཁོ་བོད་ནས་ད་ལྟ་ཐུབ་བསྟན་ཚེ་རིང་ལགས་ཀྱི་༼ཐུབ་བསྟན་ཚེ་རིང་ལགས་ཀྱི་༽ཡང་སྲིད་ཡིན་ཟེར་ཉན་༼མཁན་༽འདི་ཧ་ལས་པའི་ར་འཕྲོད་པོ་ཞིག་འདུག



07:16 བྱས་ཙང་དེ་འདྲ་ཁོ་སྐྱེ་བ་སྔ་ཕྱི་དྲན་མཁན་ཅིག་ཡོང་གི་ཡོད་རེད་བ། ཨ་ད་ལན་ཉེ་ཆར་བལ་ཡུལ་ལ་ཡ་ཕྲུ་གུ་ཞིག་འདུག་བ། ཕྲུ་གུ་༼པུ་གུ་༽དེས་ཟླ་བ་གསུམ་ལྷག་ཙམ་ཅིག་ལྟོ་ཆས་ཁྱོད་ནས་མ་བཟས་པར་བསྡད་འདུག་པ།



07:26 ཁོས་སྒོམ་འདྲ་པོ་༼ར་བོ་༽རྒྱབ་པ་༼རྒྱབ་ཀྱིན་༽ཡིན་ན་༼ཡོད་ན་༽གཅིག་བྱེད་བྱས། བྱས་ཙང་ཏ་དེ་ཚན་རིག་གཅིག་པུའི་ཐོག་ནས་འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་མིན་འདུག་ཁ།༼ག༽



07:34 ཏ་ཁོ་གང་ལྟར་ནང་སེམས་ཀྱི་སྔོན་གོམས་པའི་ཏིང་ངེ་འཛིན་གྱིས་༼ར་བོ་ཅིག་གིས་༽ཡོང་གི་ཡོད་པ་ཡིན་འགྲོ།༼ཤད་མི་དགོས།༽ ཡང་ན་དངོས་གནས་རང་ཡང་ཅིག་༼འེས་༽སངས་རྒྱས་པའི་གཞུང་ནས་གསུངས་པ་ནང་བཞིན་༼འོ་དེ་འདྲེས་ཀྱི་ཕ་གེ་༽ཅིག་གི་ཡོན་ཏན་ཞིག་ཐོབ་ནས་ཡོང་གི་ཡོད་པ་ཡིན་འགྲོ།༼ཤད་མི་དགོས།༽



07:50 ཡང་ན་ཅིག ༼ག་རེ་ཟེར་དགོས་རེད་༽ཏིང་ངེ་འཛིན་དེ་འདྲ་༼འདྲེས་༽གི ཕྱི་ནང་ཐུན་མོང་བའི་ཏིང་ངེ་འཛིན་དེ་འདྲ་གྱི་ཐོག་ནས་ཡོང་གི་ཡོད་བ་ཡིན་འགྲོ།

08:11 གཟུགས་པོ་ནི་རྒྱག་པ་ཞེས་འདྲ་འདུག ངས་དཔར་ཅིག་མཐོང་སོང་བལ་ཡུལ་ཚགས་པར་ནང་ཐོན་འདུག་ཁ། བྱས་ཙང་འོ་དེ་འདྲ་འདྲ་པོ་རེད། ཏ་དེ་ཚོས་གྲལ་ལ་འགྲེལ་བཤད་ཞིག་རྒྱབ་༼རྒྱབ་༽དགོས་ཀྱི་འདུག་ཨ། ཚན་རིག་ཀྱང་ཀྱང་ཐོག་ནས་འགྲེལ་བཤད་རྒྱབ་ཐུབ་རྒྱུ་ཁག་པོ་རེད།



08:20 ཏ་ཁོ་ གཅིག་བྱུང་ནི་བྱུང་བ་རེད། ཨ་ནི་ཏ་དེ་དམིགས་བསལ་རེད། ཨ་ནི་ལབ་ཡ་ཡོད་༼ཡོང་གི་༽མ་རེད་བ་ ཏ་ཁོ་འགྲེལ་བཤད་ཅིག་དགོས་པ་རེད། དེ་འདྲ་ཡིན་དུས་ཙ་ནས་ཏ་དེ་འདྲ་ཡི་རྒྱུ་མཚན་གཅིག



08:31 ཏ་དེ་ནས་འཇིག་རྟེན་ཆག་ཡ་འདི་ ཏ་དེ་རིང་ད་ག་༼དེ་རིང་ད་ག་༽བཞག་གོ་མེད་འགྲོ་ དེ་རིང་ད་ག་བཞག་ནས་སྔོན་ལ་དེ་ལབ་ཏ།

Kindly listen to the audio carefully when you change the error. So many things are missing.

2023-07-12 04:27 UTC, geshecelon requested changes
STT001-10
Date: 12 July 2023

00:00 ད་ཁོ་བློ་སྐད་ཅིག་སྔ་མ་དེ་ལོག་ཤེས་རེད་བ་ཐ་བློ་སྐད་ཅིག་ཕྱི་མ་དེ་༼འེས་༽བློ་ཡང་དག་པ་ཆག་སྡོད་ཡོད་ར་ཡིན་ནས་འདི་ཀླད་རྩ་རང་གི་སྒང་ནས་ཕལ་ཆེར།


00:09 འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་ཁག་པོ་རེད། མེ་དམར་ལམ་པ་མཐོང་བསྡད་མཁན་གྱི་དེ་ཡི་དྲངས་པའི་ཡིད་བློ་འདི་ག་ཀྱང་ཀྱང་ཅིག་མ་ཏོག༼མ་གཏོགས།༽




00:28 གཅིག་བྱས། གཉིས་པ་འདི་ཨེ་ནི་སྒོམ་རྒྱབ་ནས་ད་ཅིག་ཤེས་པ་ཀྱང་ཀྱང་སྒང་ལ་ལས་ཀ་བསྐུར་ནས་༼བསྐུལ་ནས་༽




00:38 ཤེས་པ་ཀྱང་ཀྱང་སྒང་ལ་ལས་ཀ་བསྐུར་ནས་༼བསྐུལ་ནས་༽ལུས་པོའི་འགུལ་བསྐྱོད་མེད་པ་བྱས་འ་༼འེས་ད་༽ལུས་པོའི་སྦྱོང་བརྡར་མིན་པར་བྱས་ ཤེས་པ་ཀྱང་ཀྱང་སྒང་ལ་ལས་ཀ་སྐུལ་བའི་རྐྱེན་ལས་ཀ་བསྐུལ་ནས



00:58 འགྱུར་བ་གཏོང་བྱེད་ཀྱི་ཤེས་པ་གཉིས་པོ་དེ་ཁ་ཁག་ཡོད་པའི་ཟོ་འདྲ་ར་བོ་ཆག་འགྲོ་ཆག་འགྲོ་བྱས་ཀྱི་འདུག་པ་ མ་གཞི་ཤེས་པ་ཁོ་ཀླད་རྩ་ལ་རྟེན་ནས་༼བརྟེན་༽ཡོང་གི་ཡོད་རེད།

ཀླད་རྩ་ལ་རྟེན་༼བརྟེན་༽ནས་ཡོང་གི་ཡོད་རེད་ཏེ།


01:33 དེ་ནས་འོ་ཐ་ ༼ཨ་ལྟ་༽ད་ལྟ་འཇར་མན་འདི་ལབ་སྡོད་ཡ་སྐད་ཆ་འཕྲོ་དེ་ཡིན་ འཇར་མན་གྱི་ཀླད་རྩའི་མཁས་པ་ནི་འོ་རོ་ཇིས་ཌི་རེད་



02:11 ཨ་ནི་༼ཨེ་ནས་༽ད་ལྟ་འཇར་མན་སྤོ་ལགས་དེའི་ལབ་ཡ་ལ། མ་གཞི་ཡུལ་བྱེ་བྲག་པ་སོ་སོར་རིག་ཡ་འི་ཀླད་པའི་ཀླད་རྩའི་ཀླད་པའི་རྡུལ་ཕྲ་རབ་སོ་སོར་ཡོད་རེད་ཏེ།


02:42 འདི་མིན་འདུག་ ཁོན་ཋི་རོལ་ཨོར་ judge མིན་འདུག central commander ཟེར་ངན་འདྲ་པོ་ཅིག་མིན་འདུག་འོ་དེ་བཤད་ཡོང་གི


03:13 བྱས་ཙང་དེ་འདྲ་ཡིན་དུས་ཙ་ནས་ ད་ལྟ་སྤྱི་སྤོམ་རགས་པ་ཞིག་ཤོད་ཡོང་དུས་ཨ་ཤེས་པ་དེ་ཀླད་པ་ལ་བརྟེན་ནས་ཡོང་བ་རེད་ཅེས་ལབ་ཡ་ཅིག་འདུག་བ།༼ག༽




03:20 ཏ་ཞིབ་ཚགས་པོའི་ག་ལ་ཕར་ཕྱིན་པ་ཡིན་ན། ད་ལྟ་ལན་རྒྱབ་ཡ་ཁག་པོ་ཞེས་འདྲ་རེད། བྱས་ཙང་དེ་འདྲ་༼འདྲེས་༽ཡིན་དུས་ཀླད་པའི་འགྲེལ་བཤད་ཀྱང་ཀྱང་ཐོག་ནས་ཤེས་པ་མེད་པར་སྒྲུབ་ཐུབ་ཡ་ཁག་པོ་རེད་ཤག


03:42 བྱས་ཙང་རགས་པའི་ཤེས་པ་དེ་དཔེར་ན་ང་རང་ཚོས་ནང་པའི་གཞུང་གི་ནང་ལོག་ནས་དབང་པོའི་ཤེས་པ་ཟེར་ཡ་འདི་དབང་པོ་ལ་བརྟེན་པས་ཤེས་པ་ཡིན་དུས་ཙ་ན། དབང་པོའི་ཤེས་པ་ཞེས་མིང་བཏགས་གི་ཡོད། ཁོ་དབང་པོ་འགགས་སོ་ན་དབང་པོར་སྐྱོན་ཤོར་ན། ཤེས་པ་ཁོ་འགགས་འགྲོ་ཡི་༼གི་༽རེད་

03:59 ཐ་ཡིད་བློ་ཡིད་དབང་ལ་བརྟེན་པ་ཞེས་ཤོད་སྡོད་༼བཤད་བསྡད་༽ཀྱི་ཡོད་རེད། ཐ་འདི་ཡིད་བློའི་ནང་དུ་ཕྲ་རགས་མང་པོ་ཅིག་ཡོང་སྡོད་མཁན་༼བསྡད་མཁན་༽ཅིག


04:08 བྱས་ཙང་ག ཇི་ཙམ་རགས་པ་དེ་གས་འདི་ལུས་འདིའི་དབང་པོ་ལ་བརྟེན་མཁན་༼བརྟེན་བསྡད་མཁན་༽ཅིག་དང༌།



04:16 ཐ་ཇི་ཙམ་ཕྲ་རུ་ཕྲ་རུ་ཕྱིན་པའི་ཚོད་ཀྱིས་ཁོ་ཏོག་སེ་(autonomy)འདྲ་བོ་ཅིག་ཕལ་ཆེར་རང་སྐྱོང་འདྲ་བོ་ཅིག་ཆགས་ཡོང་ངན༼ངེ་༽། མཐར་ལ་གཏུགས་ཡོང་དུས་ཙ་ནས་ཨེ་ནས་ཕལ་ཆེར་རང་མཚན་པ་ཞིག་ཕལ་ཆེར་ཆགས་ཀྱི་ཡོད་རེད།



04:27 དེ་འདྲ་༼འདྲེས་༽ཡིན་དུས་ཙ་ནས་ ༼འེས། འེས།༽༼ག་རེ་ཟེ་དགོས་རེད་༽སྔ་མ་ནས་སྐྱེ་བ་སྔ་ཕྱི་མེད་པའི་སྒྲུབ་བྱེད་མཐར་ཐུག་ཤེས་པ་ཀླད་རྩ་ལ་བརྟེན་ནས་ཡོང་བ་རེད་ཅེས་ལབ་སྡོད་ཡ་༼བསྡད་ཡ་༽དེ་ ད་ལྟ་ཐག་ཆོད་པ་ཅིག་བཤད་ཐུབ་ཡ་ཁག་པོ་རེད་བཞག



04:42 ༼འེམ།༽ཏ་༼ད་༽ཡང་ཕྱོགས་གཞན་ཅིག་ནས་སྐྱེ་བ་སྔ་མ་དྲན་ངན་༼དྲན་མཁན་༽དེ་འདྲ་ཡོང་སྡོད་ཀྱི་འདུག་ག གསལ་པོ་ཞེད་པོ་ཅིག་ཡོང་གི་འདུག་ག



04:51 ཏ་༼ད་༽ཡིན་ནས་དེ་འེ་ག་རེ་ཟེར་དགོས་རེད། ཡོད་དམ་མེད་ཅེས་ཐག་བཅད་ན།


05:01 ཁོ་མང་ཁ་ཉུང་ཉུང་གི་སྐད་ཆ་མ་རེད་བར་ཡོད་དང་མེད་ཟེར་ཡ་འདི་ཐག་གཅོད་ཡ་འདི་ ཁོ་༼འེས་༽གཅིག་ཡོད་ན་ཡོད་པ་རེད།



05:08 བྱས་ཙང་ཁ་ཏ་སྐྱེས་བ་སྔ་ཕྱི་སྐྱེ་བ་སྔ་མ་ཟེར་ཡ་དེ་༼འེས་༽དྲན་བསྡད་ཉན་༼དྲན་བསྡད་མཁན་༽ཅིག་གི་ཉུང་ཤས་ཅིག་གི་ཏ་ཁོ་ར་འཕྲོད་པོ་ཅིག་ཡོང་བསྡད་ཀྱི་འདུག་བ་





05:50 ཏ་ཕྲུ་གུ་གཅིག་ལ་ཕ་མ་བཞི་ ཚེ་འདིའི་ཕ་མ་གཉིས་དང། ཚེ་སྔོན་མའི་ཕ་མ་གཅིག ཕ་མ་བཞི་འདུག་༼འདི་ཀཎ་པུར་ལ་ཐུག་སོང་། ཀཎ་པུར་ཟེར་ས་དེར་༽དེ་རྒྱ་གར་ས་ཆ་ཀཎ་པུར་ཟེར་ཡ་དེ་ལ་ཐུག



06:00 ཨ་ནི་པ་ཏྲི་ཡ་ལའི་འཁྲིས་ནས་ཡང་རྒྱ་གར་བུ་མོ་ཅིག་སྐྱེ་བ་སྔོན་མ་གསལ་པོ་ཞེས་པོ་དྲན་ཉན་༼དྲན་མཁན་༽ཅིག ད་ལན་ཉེ་ཆར་ཡང་སྐྱེ་བ་སྔོན་མ་གསལ་པོ་ཞེས་པོ་དྲན་མཁན་ཞིག་འདུག



06:09 ༼སེ་༽དེ་དང་དེ་འདྲ་བ་ དེ་འདྲ་ཉམས་ཞིབ་བྱེད་མཁན་དེ་འདྲ་༼འདྲེས་༽གྱིས་༼ཀྱི་༽སྐྱེ་བ་སྔོན་མ་གསལ་པོ་ཞེས་པོ་༼ཞེད་པོ་༽དྲན་ནས་ར་འཕྲོད་པོ་ཡོད་དོ་པ་དེ་འདྲ་ག་རོས་བཤད་ཡ་ཡོད་རེད། ཏ་༼ད་༽འདི་འགྲེལ་བཤད་ཅིག་དགོས་རེད་པ།



06:20 ཏ་༼ད་༽འདི་ལྟེས་དབང་གི་༼གིས་༽གཅིག་༼སེ་༽གཅིག་༼སེ་༽ར་འཕྲོད་པ་ཡོང་སྲིད་གི་ར་ཐ་ སྔ་མ་ལྷ་ཕེབས་ཉན་༼ཕེབས་མཁན་༽ཅིག་གི་ ཨ་ནི་ལྷ་ཕེབས་ཉན་༼ཕེབས་མཁན་༽ཅིག་༼གཅིག་༽གི་ཕྲུ་གུ་༼པུ་གུ་༽གཅིག་ཡོད་རེད།



06:30 ཨ་ནི་པ་བ་༼པ་ཕ་༽དེ་གྲོངས་ཁར་ལྷག་མོ་དེ་ཕྲུ་གུ་༼པུ་གུ་༽དེས་ལྟ་ལྷ་གང་འདྲ་༼སེ་༽ཕེབས་དགོས་རེད་ལབ་པ་རེད། ཨ་ནས་རྐང་པའི་གཏིང་ཁ་དེ་དུག་༼འདུག༽ རྐང་པའི་རྩེ་བཙུགས་བྱས་བསྡད་ན། གང་འཚམས་ནས་འདར་སིག་རྒྱག་གི་རེད། ཧེ་ཧེ་ཧེ་



06:55 བྱས་ཙང་འོ་དེ་ཟོར་ར་བོ་བྱེད་བྱས་ ཨེ་ནས་ཁ་ཤས་ཁ་ཤས་ལྟ་ཁོ་ཅིག་ཡང་ཐིག་པ་ཡོང་སྲིད་གི་ར་ཏ་ཁོ། ཏ་ཡིན་ནས་ཧ་ལས་པའི་ར་འཕྲོད་པོ་ཅིག་ཏ་༼ད་༽ང་ཚོང་བོད་པའི་ཕྱུ་གུ་ཅིག་ཡོད་རེད་ བོད་པའི་ཕྱུ་གུ་ཅིག



07:07 ཁོ་བོད་ནས་ད་ལྟ་༼ཨ་ལྟ་༽ཐུབ་བསྟན་ཚེ་རིང་ལགས་ཀྱི་ཡང་སྲིད་ཡིན་ཟེར་མཁན་འདི་ཧ་ལས་པའི་ར་འཕྲོད་པོ་ཞིག་འདུག



07:16 བྱས་ཙང་དེ་འདྲ་ཁོ་སྐྱེ་བ་སྔ་ཕྱི་དྲན་མཁན་ཅིག་ཡོང་གི་ཡོད་རེད་བ། ཨ་ད་ལན་ཉེ་ཆར་བལ་ཡུལ་ལ་ཡ་པུ་གུ་ཞིག་འདུག་བ། ཕྲུ་གུ་༼པུ་གུ་༽དེས་ཟླ་བ་གསུམ་ལྷག་ཙམ་ཅིག་ལྟོ་ཆས་ཁྱོད་ནས་མ་བཟས་པར་བསྡད་འདུག་པ།



07:26 ཁོས་སྒོམ་ར་པོ་རྒྱབ་ཀྱིན་ཡོད་ན་གཅིག་བྱེད་བྱས། བྱས་ཙང་ཏ་དེ་ཚན་རིག་གཅིག་པུའི་༼གཅིག་གོ་གི་༽ཐོག་ནས་འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་མིན་འདུག་ག



07:34 ཏ་༼ད་༽ཁོ་གང་ལྟར་ནང་སེམས་ཀྱི་སྔོན་གོམས་པའི་ཏིང་ངེ་འཛིན་ར་བོ་ཅིག་གིས་ཡོང་གི་ཡོད་པ་ཡིན་འགྲོ ཡང་ན་དངོས་གནས་རང་ཡང་ཅིག་འེས་སངས་རྒྱས་པའི་གཞུང་ནས་གསུངས་པ་ནང་བཞིན་འོ་དེ་འདྲེས་ཀྱི་ཕ་གེ་ཅིག་གི་ཡོན་ཏན་ཞིག་ཐོབ་ནས་ཡོང་གི་ཡོད་པ་ཡིན་འགྲོ



07:50 ཡང་ན་ཅིག ༼འེས་༽ག་རེ་ཟེར་དགོས་རེད་༼འེས་༽ཏིང་ངེ་འཛིན་དེ་འདྲེས་གི ཕྱི་ནང་ཐུན་མོང་བའི་ཏིང་ངེ་འཛིན་དེ་འདྲ་༼འདྲེས་༽གྱི་ཐོག་ནས་ཡོང་གི་ཡོད་བ་ཡིན་འགྲོ



08:00 ཏ་༼ད་༽སྔ་མོའི་བག་ཆགས་ཞེས་པོ་ཞིག་སད་ནས་ཡོང་སྲིད་ཀྱི་ར་ཐ༼རེད་པ༽། བྱས་ཙང་ཁོ་རགས་པའི་ཟས་ལ་བརྟེན་མི་དགོས་པར་ཏིང་ངེ་འཛིན་ཁོ་རས་འཚོ་དེ་ཡ་དེ་འདྲ་ཅིག་ཡོང་གི་ཡོད་བ་ཡིན་ན། གང་ལྟར་ཟླ་བ་གསུམ་ལྷག་ཙམ་ཅིག



08:11 གཟུགས་པོ་ནི་རྒྱག་པ་ཞེས་འདྲ་༼ཞེ་དྲགས་༽འདུག ངས་དཔར་ཅིག་མཐོང་སོང་བལ་ཡུལ་ཚགས་པར་ནང་ཐོན་འདུག་ཁ། བྱས་ཙང་འོ་དེ་འདྲ་འདྲ་པོ་རེད། ཏ་དེ་ཚོས་གྲལ་ལ་འགྲེལ་བཤད་ཞིག་རྒྱབ་༼རྒྱབ་༽དགོས་ཀྱི་འདུག་ཨ། ཚན་རིག་ཀྱང་ཀྱང་ཐོག་ནས་འགྲེལ་བཤད་རྒྱབ་ཐུབ་རྒྱུ་༼ཐུབ་ཡ་༽ཁག་པོ་རེད།



08:20 ཏ་༼ད་༽ཁོ་ གཅིག་བྱུང་ནི་བྱུང་བ་རེད། ཨ་ནི་༼ཨེ་ནས་༽ཏ་༼ད་༽དེ་དམིགས་བསལ་རེད། ཨ་ནི་༼ཨེ་ནས་༽ལབ་ཡ་ཡོང་གི་མ་རེད་བ་ ཏ་ཁོ་འགྲེལ་བཤད་ཅིག་དགོས་པ་རེད། དེ་འདྲ་ཡིན་དུས་ཙ་ནས་ཏ་༼ད་༽དེ་འདྲ་ཡི་རྒྱུ་མཚན་གཅིག



08:31 ཏ་༼ད་༽དེ་ནས་འཇིག་རྟེན་ཆག་ཡ་༼ཆགས་ཡ་༽འདི་ ཏ་༼ད་༽དེ་རིང་ད་ག་བཞག་གོ་མེད་འགྲོ་ དེ་རིང་ད་ག་བཞག་ནས་སྔོན་ལ་དེ་ལབ་ཏ༼ད་༽།

2023-07-12 10:52 UTC, geshecelon requested changes
STT001-15
Date: 12 July 2023
00:00 དྲང་སྲོང་སེར་སྐྱའི་རྗེས་སུ་འབྲངས་པ་དེ་༑ ཤེས་བྱ་ཉི་ཤུ་རྩ་ལྔར་གྲངས་ངེས་པར་འདོད་ལ། དེ་ཡང་བདག་དང༌། གཙོ་བོ་དང༌། ཆེན་པོ་དང༌། ང་རྒྱལ་དང༌། དེ་ཙམ་ལྔ་དང༌། དབང་པོ་བཅུ་གཅིག་དང༌། འབྱུང་བ་ལྔ་སྟེ་ཉི་ཤུ་རྩ་ལྔ་།


00:15 །དེ་ཙམ་ལྔ་ནི། གཟུགས་སྒྲ་དྲི་རོ་རེག་ ཐ་དེ་དམིགས་བསལ་ཞུས་ཡ་མིན་འདུག་ཨ་ད་ཀློག་བཅས་གལ་དགོས་ཀྱི་ཨ་ཡོད། །ད་དབང་པོ་བཅུ་གཅིག་བྱས་ དེ་ནས་དབང་པོ་བཅུ་གཅིག་ནི། འོ་རེད་དབང་པོ་བཅུ་གཅིག



00:30 ད་དེ་ནས་ བློའི་དབང་པོ་ལྔ་ ལུས་ཀྱི་དབང་པོ་ལྔ་ ཡིད་ཀྱི་དབང་པོ་བྱས་ ༼ད་དེ་ནས་བློའི་དབང་པོ་ལྔ་། ལུས་ཀྱི་དབང་པོ་ལྔ་། ཡིད་ཀྱི་དབང་པོ་བྱས།༽ །བློའི་དབང་པོ་ལྔ་ནི། མིག་རྣ་སོགས་བྱས།



00:39 ལུས་ཀྱི་དབང་པོ་ལྔ་ནི། ངག་ ལག་པ་ རྐང་པ་ རྐུབ་༼ ངག ལག་པ། རྐང་པ། རྐུབ།༽ འདོམས་བྱས། །༼ཤད་དེ་མི་དགོས།༽འབྱུང་བ་ལྔ་ནི། ས་ཆུ་མེ་རླུང་ནམ་མཁའ།



00:51 །༼ཤད་དེ་མི་དགོས།༽ད་ནམ་མཁའ་ཕལ་ཆེར་བུ་ག་ནམ་མཁའ་ཞེས་པ་དེ་བཞག་གི་མེད་འགྲོ འབྱུང་བ་ལྔ་༼འབྱུང་བ་ལྔ་།༽ ཡང་ན་གོ་བརྗེས་པ་ཙམ་བསམ་བློ་གཏོང་གི་ཡོད་ན།

01:00 སྟོང་ཆ་འདྲ་བོ་བསམ་བློ་གཏོང་གི་ཡོད་ན། དེ་དག་ལས་སྐྱེས་བུ་ནི་ཤེས་པ་དང། བདག་ཤེས་རིག་སྐྱེས་བུ་ཟེར་འདས་ཡ་འདི་ དེ་དག་ལས་སྐྱེས་བུ་ནི་ཤེས་པ་དང། ལྷག་མ་ཉེར་བཞི་འདུས་བསགས་ཡིན་པས་བེམ་པོར་འདོད་༑ གཙོ་བོ་དང༌། སྐྱེས་བུ་ནི་དོན་དམ་བདེན་པ་དང༌།



01:13 གཞན་རྣམས་ཀུན་རྫོབ་བདེན་པར་འདོད་དོ། ༼ཤད་གཉིས་དགོས།༽འེ། །བྱས་ཙང་ བདེན་པ་གཉིས་ཀྱི་རྣམ་གཞག་ནི་༼ནི་དེ་མི་འདུག༽མུ་སྟེགས་གྲངས་ཅན་པས་ཤོདཡོང་་༼བཤད་ཡོང་གི་༽ཀྱི་འདུག་ཨ་༼ཚགས་དུང་མི་དགོས།༽།



01:26 དེར་དུས་ཏ་རྒྱ་གར་གྱི་གྲུབ་མཐའ་ཚོར་ཡོངས་གྲགས་ཅིག་ཡིན་པ། དེ་ལ་ཡང་རྒྱུ་ཡིན་ལ་འབྲས་བུ་མ་ཡིན་པ། ཏ་

ཤེས་བྱ་ཉི་ཤུ་རྩ་ལྔའི་ནང་ལོག་ལ་ཡ། རྒྱུ་ཡིན་ལ་འབྲས་བུ་མ་ཡིན་པ། རྒྱུ་འབྲས་གཉིས་ཀ་ཡིན་པ།



01:37 འབྲས་བུ་ཡིན་ལ་རྒྱུ་མ་ཡིན་པ། རྒྱུ་འབྲས་གཉིས་ཀ་མ་ཡིན་པའི་མུ་དང་བཞི་ཡོད་དེ། དང་པོ་ནི། སྤྱི་གཙོ་བོ་དང།༼དང་།༽ སྤྱི་གཙོ་བོ་དེ་ཐམས་ཅད་ཏ་༼ད་༽སྤྲུལ་མཁན།



01:48 བྱས་ཙང་ཏ་ད་གི་ཟེར་བསྡད་ཡ་དེ་རྟག་པའི་རྒྱུ་ཟེར་བསྡད་ཡ་དེ་སྤྱི་གཙོ་བོ་འདི་རྟག་པ་བྱས། ཨ་ནི་འཇིག་རྟེན་བཀོད་པ་པོ་བྱས་ནས་ཅིག་བློ་ཅན་གྱི་༼ར་བོ་༽དཀོན་མཆོག་ཟོར་འདྲ་བོ་༼ར་བོ་༽ཅིག་མ་བརྩིས་པར་བྱས། ཁོ་རང་རང་བཞིན་མཐར་ཐུག་འདྲ་པོ་ཅིག།༼ག་ཡི་རྗེས་ལ་ཤད་མི་དགོས།༽



02:01 ལྟ་བ་འདི་རྟག་པ་བྱས་ སྤྱི་གཙོ་བོ་ཏ་༼ད་༽གཤམ་ལ་ཡ་ཕལ་ཆེར་ཡོད་ཀྱི་རེད་ གཙོ་བོ་བྱས་ ཏ་༼ད་༽འདི་རྒྱུ་བྱས་ འབྲས་བུ་མ་ཡིན་པ་



02:11 ཨ་ནི་དེ་ནས་རྒྱུ་འབྲས་གཉིས་ཀ་ཡིན་པ་ནི། བློ་དང།༼དང་།༽  ང་རྒྱལ་དང།༼དང་།༽  དེ་ཙམ་ལྔ་སྟེ་བདུན་དང།༼དང་།༽ 



02:19 ཨ་ནི་༼ཨ་ནི་དེ་མིན་འདུག༽༼ད་༽འབྲས་བུ་ཡིན་ལ་རྒྱུ་མ་ཡིན་པ། ལྷག་མ་བཅུ་དྲུག རྒྱུ་འབྲས་གཉིས་ཀ་མ་ཡིན་པ་མུ་བཞི། བྱས་ཙང་ཀ་རྣམ་འགྱུར་གྱི་༼འདི་གས་འདི་༽གཙོ་བོ་སྤྲོད་པ་བྱས་༼བྱས།༽



02:30 གཙོ་བོ་གར་ཟེར་གོ་ད། སྤྱུལ་པ་སྤྱུལ་པར་བྱས། སྐྱེས་བུ་འདི་་༼འེས་༽གཙོ་བོའི་སྤྲུལ་པ་མོད་མི་བྱས་༼མིན་པར་བྱས་༽པར་ཐ་མངོས་ནས་༼ཁ་ོརང་དང་པོ་ནས་༽ཡོད་པ་ཡིན་ན།



02:40 ཏ་༼ད་༽གང་ལྟར་ རང་བཞིན་ གཙོ་བོ་ གཙོ་བོའི་རང་བཞིན་འདྲ་པོ་༼ར་བོ་༽དེ་མཐོང་བྱས། བྱས་ཡོང་དུས་ཨ་ནི་༼ཨེ་ནས་༽རིམ་པས་གི་ཅིག་སྤྲོས་པ་དེ་གས་དེ་ཕ་ནུབ་འགྲོ་ཡ་ཅིག་གི ཨ་ནི་༼ཨ་ནི་དེ་མི་འདུག༽དེ་བཤད་པ་ཡིན་གི་མ་རེད་༼བཤད་པ་ཡིན་པ་རེད།༽



02:55 ཨཨཨཨ་༼འེས།༽སྐྱེས་བུ་ དེ་ཡང་མངོན་ཙུག་ནམ་མཁའ་ཀུན་ནས་ཙག་ཡ་ཏ་དེ་བྱས་༼དེ་ཡང་དབང་ཕྱུག་ནག་པོའི་རྒྱུད་ལས་རྩ་བའི་རང་བཞིིན།༽ དེ་ཡང་རྩ་བའི་རང་བཞིན་དང༌། སྤྱི་དང༌། གཙོ་བོ་རྣམས་དོན་གཅིག་ཡིན་ཞིང་ཁྱད་ཆོས་བཅོ་དྲུག་དང་ལྡན་པའི་ཤེས་བྱ་ཞིག་ལ། ཁྱད་ཆོས་དྲུག་དང་ལྡན་པའི་༼ཁྱད་ཆོས་དྲུག་དང་ལྡན་པའི་༽ཤེས་བྱ་ཞིག་ལ་འདོད།



03:10 །ཏ་༼ད་༽ཁྱད་ཆོས་དྲུག་འདི་༼ཕ་གེ་༽འགྲེལ་བ་བརྒྱད་ཟེར་ན་༼ཟེར་དུ་ཙ་ནས་༽མེད་གར་ཟ་ འ་གྲུབ་མཐའ་རྒྱས་པ་དེ་ཚོས་ནང་༼ཡོད་པ་༽ཡོད་ཀྱི་རེད། སྐྱེས་བུ་དང༌། བདག་དང༌། ཤེས་པ་དང༌། རིག་པ་རྣམས་དོན་གཅིག་།



03:21 བྱས་ཙང་བདག་ཤེས་རིག་གི་སྐྱེས་བུ་ལབ་དུ་ཚང་མ་ལོག་གསལ་བཞག་ བདག་༼བདག༽ ཤེས་༼ཤེས།༽ རིག་༼རིག༽ སྐྱེས་བུ་དོན་གཅིག་མིང་གི་རྣམ་གྲངས་སོགས་༼སོ།།༽།ལྷག་མ་ཉེར་གསུམ་གྱི་སྐྱེ་ཚུལ་ནི།

2023-07-17 12:04 UTC, geshecelon requested changes
STT001-10
17 July, 2023

00:09 འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་ཁག་པོ་རེད། མེ་དམར་ལམ་པ་མཐོང་བསྡད་མཁན་གྱི་དེ་ཡི་དྲངས་པའི་ཡིད་བློ་འདི་ག་ཀྱང་ཀྱང་ཅིག་མ་ཏོག ༼མ་གཏོགས།༽


01:33 དེ་ནས་འོ་ཐ་ ད་ལྟ་འཇར་མན་འདི་ལབ་སྡོད་ཡ་སྐད་ཆ་འཕྲོ་དེ་ཡིན་ འཇར་མན་གྱི་ཀླད་རྩའི་མཁས་པ་ནི་འོ་རོ་ཇིས་ཌི་༼ནི་རོ་ལོ་ཇིས་ཌི་༽རེད་


02:42 འདི་མིན་འདུག་ ཁོན་ཋི་རོལ་ཨོར་ judge༼ཇཱརྗྀ།༽ མིན་འདུག central commander༼སེན་ཋཱལ། ཁམ་མན་ཌྀར།༽ ཟེར་ངན་འདྲ་པོ་ཅིག་མིན་འདུག་འོ་དེ་བཤད་ཡོང་གི


04:16 ཐ་ཇི་ཙམ་ཕྲ་རུ་ཕྲ་རུ་ཕྱིན་པའི་ཚོད་ཀྱིས་ཁོ་ཏོག་སེ་(autonomy)༼ཨཱ་ཋོ་ནོ་མའེ།༽འདྲ་བོ་ཅིག་ཕལ་ཆེར་རང་སྐྱོང་འདྲ་བོ་ཅིག་ཆགས་ཡོང་ངན། མཐར་ལ་གཏུགས་ཡོང་དུས་ཙ་ནས་ཨེ་ནས་ཕལ་ཆེར་རང་མཚན་པ་ཞིག་ཕལ་ཆེར་ཆགས་ཀྱི་ཡོད་རེད།


08:11 གཟུགས་པོ་ནི་རྒྱག་པ་ཞེས་འདྲ་འདུག ངས་དཔར་ཅིག་མཐོང་སོང་བལ་ཡུལ་ཚགས་པར་ནང་ཐོན་འདུག་ཁ། བྱས་ཙང་འོ་དེ་འདྲ་འདྲ་པོ་རེད། ཏ་དེ་ཚོས་གྲལ་ལ་འགྲེལ་བཤད་ཞིག་རྒྱབ་༼རྒྱབ་རྒྱབ་ཟེར་བ་གཉིས་འདུག ངེས་པར་དུ་ཡག་པོ་བྱས་ནས་སྐུ་འདུས་ཀྱི་བཀའ་སློབ་གསན་རོགས།༽དགོས་ཀྱི་འདུག་ཨ། ཚན་རིག་ཀྱང་ཀྱང་ཐོག་ནས་འགྲེལ་བཤད་རྒྱབ་ཐུབ་རྒྱུ་ཁག་པོ་རེད།

2023-07-20 06:30 UTC, geshecelon requested changes
 00:00 ད་ཁོ་བློ་སྐད་ཅིག་སྔ་མ་དེ་ལོག་ཤེས་རེད་བ་ཐ་བློ་སྐད་ཅིག་ཕྱི་མ་དེ་འེས་བློ་ཡང་དག་པ་ཆག་སྡོད་༼ཆགས་བསྡད་༽ཡོད་ར་ཡིན་ནས་འདི་ཀླད་རྩ་རང་གི་སྒང་ནས་ཕལ་ཆེར།
00:09  འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་ཁག་པོ་རེད། མེ་དམར་ལམ་པ་མཐོང་བསྡད་མཁན་གྱི་དེ་ཡི་དྲངས་པའི་ཡིད་བློ་འདི་ག་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽ཅིག་མ་གཏོགས།
00:16 ཚད་མ་དང་ཚད་མིན་གྱི་དབྱེ་བ་དེ་ཕལ་ཆེར་ཕྱེ་ཐུབ་ཡ་ཁག་པོ་རེད་ཤག བྱས་ཙང་དེ་འདྲ་ཡིན་དུ་རྩ་ནས་ཀླད་རྩ་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽སྟེང་ནས་བློའི་རྣམ་གཞག་ཆ་ཚང་ཞིག་འགྲེལ་བཤད་ད་ལྟ་༼ཨ་ལྟ་༽རྒྱབ་ཐུབ་ཀྱི་མི་འདུག་ག
00:28 གཅིག་བྱས། གཉིས་པ་འདི་ཨེ་ནས་འེས་སྒོམ་རྒྱབ་ནས་ད་ཅིག་ཤེས་པ་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽སྒང་ལ་ལས་ཀ་བསྐུལ་ནས་ 
00:38 ཤེས་པ་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽སྒང་ལ་ལས་ཀ་བསྐུལ་ནས་ལུས་པོའི་འགུལ་བསྐྱོད་མེད་པ་བྱས་འེས་ད་ལུས་པོའི་སྦྱོང་བརྡར་མིན་པར་བྱས་ ཤེས་པ་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽སྒང་ལ་ལས་ཀ་སྐུལ་བའི་རྐྱེན་ལས་ཀ་བསྐུལ་ནས་
00:49 དེས་རྐྱེན་པས་ཀླད་རྩ་ལ་འགྱུར་བ་འགྲོ་ཡི་༼འགྲོ་བསྡད་ཀྱི་༽འདུག་ག བྱས་ཙང་ཁ་དེ་དུས་འགྱུར་བ་གཏོང་མཁན་གྱི་ཀླད་པ་དེ་དང་
 00:58 འགྱུར་བ་གཏོང་བྱེད་ཀྱི་ཤེས་པ་གཉིས་པོ་དེ་ཁ་ཁག་༼ཁག་ཁག་༽ཡོད་པའི་ཟོ་འདྲ་ར་བོ་ཆག་འགྲོ་ཆག་འགྲོ་བྱས་ཀྱི་འདུག་པ། མ་གཞི་ཤེས་པ་ཁོ་ཀླད་རྩ་ལ་བརྟེན་ནས་ཡོང་གི་ཡོད་རེད། ཀླད་རྩ་ལ་བརྟེན་ནས་ཡོང་གི་ཡོད་རེད་ཏེ།
01:08 ཡིན་ནས་ཡང་ཤེས་པ་དེ་ལ་སྦྱོང་བརྡར་བྱས་པའི་རྐྱེན་གྱིས་ཀླད་རྩ་ལ་ཕར་འགུལ་བསྐྱོད་ཐེབས་ཡ་ཅིག་ཡོང་ཀྱི་འདུག་ག བྱས་ཙང་ཁོ་གཉིས་བརྟེན་དང་རྟེན་པ་༼རྟེན་དང་བརྟེན་པ་༽བྱས་ནས་འགྲེལ་བ་ཡོད་པ།
01:18 ཡིན་ནས་བརྟེན་པ་ཤེས་པ་དེ་རྟེན་ཀླད་པ་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽རེད་༼སེ་༽ལབ་ཐུབ་ཡ་ཕལ་ཆེར་ཁག་པོ་རེད་ཤག
01:25 ཀླད་པ་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽སྒང་ནས་ཤེས་པའི་རྣམ་གཞག་ཆ་ཚང་འགྲེལ་བཤད་རྒྱབ་དགོས་བྱུང་ན་ཕལ་ཆེར་ཁག་པོ་རེད། བྱས་ཙང་དེ་འདྲ་ཡིན་དུས་

01:42 ཐ་༼ད་༽གཅིག ཡུལ་བྱེ་བྲག་པ་སོ་སོར་འབྱེད་མཁན་༼མཇལ་མཁན་༽གྱི་ཀླད་རྩའི་གནས་བྱེ་བྲག་པ་སོ་སོར་ཡོད་རེད་ཏེ་ཀླད་པའི་རྡུལ་ཕྲ་རབ་སོ་སོར་ལ་གནས་སོ་སོ་ཡོད་རེད་ཏེ་ཡིན་ནས་
01:51 དཔེར་ན་ཀླད་པའི་ཕྱོགས་ལྟ་བུ་གཅིག་ལ་སྐྱོན་ཤོར་ན། ཡང་རིམ་པས་ག་ལེར་ག་ལེར་ཀླད་པའི་ཕྱོགས་གཞན་ཐག་༼གཞན་དག་༽དེ་ནས་ཡང་དེ་གསབ་ཡོང་གི་འདུག 
02:02  བྱས་ཙང་དེ་ཡང་༼འདི་ཡས་༽ཁོ་ཡུལ་བྱེ་བྲག་པ་དེའི་རིག་པའི་ནུས་པ་འདྲ་པོ་དེ་སྐྱོན་ཤོར་སའི་ཀླད་པ་ཁོ་ནར་ངེས་པ་རེད་མི་འདུག་ག 

02:21 ཡིན་ནས་དེའི་བྱ་བ་བྱེད་ཡ་འདི་གས་འདི་ཀླད་པ་ཕན་ཚུན་ཚང་མ་བསྡོམས་ནས་ཕན་ཚུན་བསྡོམས་ནས་སྤྱི་ཐོག་ནས་བྱེད་སྡོད་༼བྱེད་བསྡད་༽ཀྱི་འདུག
02:31 བྱས་ཙང་ཁ་དེ་ཀླད་རྩའི་དབུས་དེ་ལ་ཡ་ཅིག་བཀའ་གཏོང་ངན་༼གཏོང་ངེ་༽བཟོར་འདྲ་པོ། མི་རང་གི་འདི་ཟེར་གྱི་སེལ་ཕི་བདག་ཟེར་ཡ་འདི།
02:42 འདི་མིན་འདུག ཁོན་ཋི་རོལ་ཨོར་ཇཱརྗྀ་མིན་འདུག སེན་ཋཱལ། ཁམ་མན་ཌྀར། ཟེར་ངན་༼ཟེར་ངེ་༽འདྲ་པོ་ཅིག་མིན་འདུག་འོ་དེ་བཤད་ཡོང་གི 
02:51 ཐ་དེ་ཚུར་ནས་བདག་མེད་པ་ཟེར་པ་སྐད་ཆ་དེ་སྒང་ནས་ཅིག་སླེབས་ཡོང་གི་ཡོད་རེད་བ་ ཐ་ཨ་ལྟ་ཁོང་གིས་༼མོས་རང་གིས་༽འགྲེལ་བཤད་རྒྱབ་པ་དེ་ཤེས་པའི་གཙོ་བོ་འདྲ་པོ་ཅིག་གི ཀླད་རྩ་གཙོ་བོ་འདྲ་བོ་ཞིག་གིས་ཀླད་རྩ་གཞན་དག་ཚང་མར་ལོག་ལ་བཀའ་གཏོང་མཁན་དེ་འདྲ་མི་འདུག
03:04 ཀླད་པ་ཡོངས་རྫོགས་ལོག་གཅིག་ལ་ལྟོས་ནས་ཕན་ཚུན་གཅིག་གི་གཅིག་ལ་བརྟེན་པའི་ཐོག་ནས་ཀླད་པའི་བྱ་བ་དེ་བྱེད་ཡོང་གི་དེ་ཤོད་༼བཤད་༽ཀྱི་འདུག
03:13 བྱས་ཙང་དེ་འདྲ་ཡིན་དུས་ཙ་ནས། ད་ཨ་ལྟ་སྤྱི་སྤོམ་རགས་པ་ཞིག་ཤོད་ཡོང་དུས་༼རགས་པ་ར་བོ་བཤད་ཡོང་དུས་༽ཨ་ཤེས་པ་དེ་ཀླད་པ་ལ་བརྟེན་ནས་ཡོང་བ་རེད་ཅེས་ལབ་ཡ་ཅིག་འདུག་ག
03:20 ད་ཞིབ་ཚགས་པོའི་ག་ལ་ཕར་ཕྱིན་པ་ཡིན་ན། ཨ་ལྟ་ལན་རྒྱབ་ཡ་ཁག་པོ་ཞེས་འདྲ་༼ཞེ་དྲགས་༽རེད། བྱས་ཙང་དེ་འདྲེས་ཡིན་དུས་ཀླད་པའི་འགྲེལ་བཤད་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་གི་༽ཐོག་ནས་ཤེས་པ་མེད་པར་སྒྲུབ་ཐུབ་ཡ་ཁག་པོ་རེད་ཤག 
03:33 ད་ཤེས་པ་༼ད་༽ང་ཚོ་ནང་པའི་གཞུང་ནས་ཤེས་པ་ལ་ ལྷག་པར་སྔགས་ཀྱི་གཞུང་དང་འབྲེལ་ནས་བཤད་༼པ་༽ཡིན་ན། ཤེས་པ་ལ་ཕྲ་རགས་མང་པོ་ཞིག་འདུག་ག
03:42 བྱས་ཙང་རགས་པའི་ཤེས་པ་དེ་དཔེར་ན་ང་རང་ཚོས་ནང་པའི་གཞུང་གི་ནང་ལོག་ནས་དབང་པོའི་ཤེས་པ་ཟེར་ཡ་འདི་དབང་པོ་ལ་བརྟེན་པས་ཤེས་པ་ཡིན་དུས་ཙ་ན། དབང་པོའི་ཤེས་པ་ཞེས་མིང་བཏགས་གི་ཡོད། ཁོ་དབང་པོ་འགགས་སོ་༼སོང་༽ན་དབང་པོར་སྐྱོན་ཤོར་ན། ཤེས་པ་ཁོ་འགགས་འགྲོ་གི་རེད།
03:53 ཁོ་དབང་པོ་དེ་ལ་རྟེན་ནས་ཡོང་བ་ཅིག་ཡིན་པ་ཁོ་བདག་རྐྱེན་དབང་པོ་༼པོས་༽བྱས་ནས་ཡོང་བ་དེ་གསལ་པོ་རེད། 

04:08 བྱས་ཙང་ག ཇི་ཙམ་རགས་པ་དེ་གས་འདི་ལུས་འདིའི་དབང་པོ་ལ་བརྟེན་བསྡདམཁན་༼བསྡད་མཁན་༽ཅིག་དང། 

04:27 དེ་འདྲེས་ཡིན་དུས་ཙ་ནས་ འེས་འེས་ག་རེ་ཟེ་དགོས་རེད་སྔ་མ་ནས་སྐྱེ་བ་སྔ་ཕྱི་མེད་པའི་སྒྲུབ་བྱེད་མཐར་ཐུག་ཤེས་པ་ཀླད་རྩ་ལ་བརྟེན་ནས་ཡོང་བ་རེད་ཅེས་ལབ་བསྡད་ཡ་དེ་ ཨ་ལྟ་༼རྦད་༽ཐག་ཆོད་པ་ཅིག་བཤད་ཐུབ་ཡ་ཁག་པོ་རེད་བཞག
04:42 འེམ་ད་ཡང་ཕྱོགས་གཞན་ཅིག་ནས་༼འེས་༽སྐྱེ་བ་སྔ་མ་དྲན་མཁན་དེ་འདྲ་ཡོང་སྡོད་ཀྱི་འདུག་ག གསལ་པོ་ཞེད་པོ་ཅིག་ཡོང་གི་འདུག་ག
04:51 ད་ཡིན་ནས་དེ་འེ་ག་རེ་ཟེར་དགོས་རེད། ཡོད་དམ་མེད་ཅེས་ཐག་བཅད་ན། 

05:17 ད་ཉེ་ཆར་རང་ཡང་རྒྱ་གར་གཅིག་གིས་གཞི་པོ་༼ཞེད་པོ་༽ཅིག་ར་འཕྲོད་པོ་ཅིག  ཨ་ད་༼ཨ་ལྟ་༽ཕལ་ཆེར་ལོ་ཉི་ཤུ་སུམ་ཅུ་གོང་ལ་རེད་ ཕལ་ཆེར་ལོ་ཉི་ཤུ་ཏ་སུམ་ཅུ་གོང་ལ་མིན་འགྲོ་ བྱས་ནས་ཡང་རྒྱ་གར་བའི་བུ་མོ་གཉིས་ གཉིས་ཅ་ལོག་ངས་ཐུག་སོང་ཆུང་ཆུང་རེད།
 05:37 སྐྱེ་བ་སྔ་མ་གསལ་པོ་ཞེས་པོ་༼ཞེད་པོ་༽དྲན་ནས་སྐྱེ་བ་སྔ་མ་དྲན་ཡ་ཞེས་པོ་༼ཞེད་པོ་༽ཞིག་གསལ་པོ་ཆགས་བྱས། སྐྱེ་བ་སྔོན་མའི་ཕ་མ་གཉིས་པོ་ལྷག་སྡོད་འདུག་ག བྱས་ཙང་སྐྱེ་བ་སྔོན་མའི་ཕ་མ་གཉིས་པོ་དེ་ཡིས་ད་ལྟ་ཕྲུ་གུ་༼པུ་གུ་༽གཉིས་པོ་ཁོ་རང་གཉིས་ཀྱི་ཕྲུ་གུ་༼པུ་གུ་༽ཡིན་པར་ངོས་འཛིན་བྱེད་བྱས། 
05:50 ད་ཕྲུ་གུ་༼པུ་གུ་༽གཅིག་ལ་ཕ་མ་བཞི། ཚེ་འདིའི་ཕ་མ་གཉིས་དང། ཚེ་སྔོན་མའི་ཕ་མ་གཅིག ཕ་མ་བཞི་འདུག འདི་ཀཎ་པུར་ལ་ཐུག་སོང། ཀཎ་པུར་ཟེར་ས་དེར་རྒྱ་གར་ས་ཆ་ཀཎ་པུར་ཟེར་ཡ་དེ་ལ་ཐུག
06:00 ཨེ་ནས་པ་ཏྲི་ཡ་ལའི་འཁྲིས་ནས་ཡང་༼ཡང་མིན་འདུག༽༼མ་གིར་༽རྒྱ་གར་བུ་མོ་ཅིག་སྐྱེ་བ་སྔོན་མ་གསལ་པོ་ཞེས་པོ་༼ཞེད་པོ་༽དྲན་མཁན་ཅིག ད་ལན་ཉེ་ཆར་ཡང་སྐྱེ་བ་སྔོན་མ་གསལ་པོ་ཞེས་པོ་༼ཞེད་པོ་༽དྲན་མཁན་ཞིག་འདུག 
06:09 སེ་དེ་དང་དེ་འདྲ་བ། ༼འེས་༽དེ་འདྲ་ཉམས་ཞིབ་བྱེད་མཁན་དེ་འདྲེས་ཀྱི་སྐྱེ་བ་སྔོན་མ་གསལ་པོ་ཞེད་པོ་དྲན་ནས་ར་འཕྲོད་པོ་ཡོད་དོ་པ་༼ཡོད་བསྡད་པ་༽དེ་འདྲ་ག་རོས་༼དགའ་རོ་༽བཤད་ཡ་ཡོད་རེད། ད་འདི་འགྲེལ་བཤད་ཅིག་དགོས་རེད་པ། 
06:20 ད་འདི་ལྟེས་དབང་གི་གཅིག་སེ་གཅིག་སེ་ར་འཕྲོད་པ་ཡོང་སྲིད་གི་ར། སྔ་མ་ལྷ་ཕེབས་མཁན་ཅིག་གི ཨ་ནི་ལྷ་ཕེབས་མཁན་གཅིག་གི་ོ༼གི་༽པུ་གུ་གཅིག་ཡོད་རེད། 
06:30 ཨེ་ནས་པ་ཕ་དེ་གྲོངས་ཁར་ལྷག་མོ་༼ལ་མོ་༽དེ་པུ་གུ་དེས་ལྟ་ལྷ་གང་འདྲ་སེ་ཕེབས་དགོས་རེད་ལབ་པ་རེད། ཨེ་ནས་རྐང་པའི་གཏིང་ཁ་དེ་འདུག རྐང་པའི་རྩེ་བཙུགས་བྱས་བསྡད་ན། གང་འཚམས་ནས་འདར་སིག་རྒྱག་གི་རེད། ཧེ་ཧེ་ཧེ།
06:44 ཨེ་ནས་ག་བོ་སྤོས་དཀར་མང་པོ་བདུག་ན་ཨ་སྟོང་བརྒྱབ་ཀྱི་རེད། ཧེ་ཧེ་ཨ་ནི་༼ཨེ་ནས་༽ཐུག་ཁོ་ག་རོ་སྐྱོ་བྱས༼ཕུ་རོ་བོ་ག་རོ་རྒྱབ་བྱས།༽། ཨེ་ནས་ག་བྱུང་མ་བྱུང་ག་རོ་བཤད་བཞག་ན་ཁ་ཤས་ཁ་ཤས་ཐིག་འགྲོ་ཡི་༼གི་༽རེད། ཧེ་ཧེ།
06:55 བྱས་ཙང་འོ་དེ་ཟོར་ར་བོ་བྱེད་བྱས། ཨེ་ནས་ཁ་ཤས་ཁ་ཤས་ལྟ་ཁོ་ཅིག་ཡང་ཐིག་པ་ཡོང་སྲིད་གི་ར་ཏ་ཁོ། ཏ་ཡིན་ནས་ཧ་ལས་པའི་ར་འཕྲོད་པོ་ཅིག་ད་ང་ཚོང་བོད་པའི་ཕྱུ་གུ་༼པུ་གུ་༽ཅིག་ཡོད་རེད། བོད་པའི་ཕྱུ་གུ་༼པུ་གུ་༽ཅིག 
07:07 ཁོ་བོད་ནས་ཨ་ལྟ་ཐུབ་བསྟན་ཚེ་རིང་ལགས་ཀྱི་༼ཐུབ་བསྟན་ཚེ་རིང་ལགས་ཀྱི་༽ཡང་སྲིད་ཡིན་ཟེར་མཁན་འདི་ཧ་ལས་པའི་ར་འཕྲོད་པོ་ཞིག་འདུག 

07:26 ཁོས་སྒོམ་ར་པོ་རྒྱབ་ཀྱིན་ཡོད་ན་གཅིག་བྱེད་བྱས། བྱས་ཙང་༼བྱང་ཙང་ཁ་༽ད་དེ་༼ད་འདི་༽ཚན་རིག་གཅིག་གོ་གི་ཐོག་ནས་འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་མིན་འདུག་ག 

08:00 ད་སྔ་མོའི་བག་ཆགས་ཞེས་པོ་ཞིག་སད་༼བསལ་༽ནས་ཡོང་སྲིད་ཀྱི་རེད་པ། བྱས་ཙང་ཁོ་རགས་པའི་ཟས་ལ་བརྟེན་མི་དགོས་པར་ཏིང་ངེ་འཛིན་ཁོ་རས་འཚོ་དེ་ཡ་དེ་འདྲ་ཅིག་ཡོང་གི་ཡོད་བ་ཡིན་ན། གང་ལྟར་ཟླ་བ་གསུམ་ལྷག་ཙམ་ཅིག
08:11 གཟུགས་པོ་ནི་རྒྱག་པ་ཞེས་དྲགས་༼ཞེ་དྲགས་༽འདུག ངས་དཔར་ཅིག་མཐོང་སོང་བལ་ཡུལ་ཚགས་པར་ནང་ཐོན་འདུག་ཁ། བྱས་ཙང་འོ་དེ་འདྲ་འདྲ་པོ་རེད། ཏ་དེ་ཚོས་གྲལ་༼དེ་ཚོ་གྲས་༽ལ་འགྲེལ་བཤད་ཞིག་རྒྱབ་རྒྱབ་དགོས་ཀྱི་འདུག་ཨ།  ཚན་རིག་ཀྱང་ཀྱང་༼རྐྱང་རྐྱང་༽ཐོག་ནས་འགྲེལ་བཤད་རྒྱབ་ཐུབ་ཡ་ཁག་པོ་རེད། 

2023-08-10 04:21 UTC, closed without merging