My final file
MonlamAI/STT001 pull request #6
Opened 2023-01-19 12:28 UTC by Tenzindakar

please accept my file and correct it

2023-03-20 07:13 UTC, Tenzindharten requested changes
1་ 00:00 [ཡ་ཡ་] (ཡ་)གྲུབ་མཐའ། (ད་འདིའི་)འགོ་ནས་(མར་)བཤད་(ཡ་ཟིག)(གལ་མི་)འདུག་(ག 

  2་ 00:03(ད་འདིར་)རང་གཞན་གྱི་གྲུབ་མཐའི་རྣམ་གཞག་མདོར་བསྡུས་(ཏེ་བརྗོད་པ་ལ་གཉིས།) [ན་གཉིས།]

 3. 00:11 སྤྱིར་བསྟན་པ་དང༌། བྱེ་བྲག་ཏུ་བཤད་(པ།) [པའོ།།] རྙེད་སོང་བས། ས་བཅད་དེ། འདུག་ག

4. 00:15 བྱས་ཙང་། ད་འདིར། རྗེ་རིན་པོ་[ཆེའི་](ཆེ་ཡི)་(སྔགས་རིམ་ཆེན་མོའི་)

5. 00;22སྔགས་རིམ་ཆེན་མོའི་ནང་ལ་(ཡང་)། (གསུངས་ཡོད་རེད།) འགོ་དེར། (ཨེ་ནི)

6. 00;27 [དེས་]ཨེ་ནི་[འགོ་འཛུགས་ལ་]མུ་སྟེགས་བྱེད་ཡོད་དམ་མེད་ཀྱང་(སླ་ཡི།)

7. 00;35)[སླར་ཡིན་](རང་རང་སོ་སོའི་རྒྱུད་ལ་ཡ་)

8. 00;38 སྔོན་གྱི་ལྟ་བ་ཕྱིན་ཅི་ལོག་[གིས་]དེ་འདྲའི་བག་ཆགས་

 9. 00;42 ང་(རང་)ཚོའི་རྒྱུད་ལ་ཡོད་པ་ཡིན་དུས[་]། (ཨེ་ནི།)ལྟ་བ་འདྲ་(མི་འདྲ་)[མིན་]

 10.  00;47[དེ་དག་](དེ་སྐད་དེ་)ཤེས་པར་བྱས་ནས། (ཨེ་ནི་འཐད་མི་འཐད་ཀྱིས) [ཏག་ཏག་ཡིན་དང་མིན་]

11.  00;50 དཔྱད་པ་[བྱ་རྒྱུ་](བྱེད་ཡ་དེ)་[དེས་ཧ་ཅང་གི་]གལ་ཆེན་པོ(་ཞེ་དྲག་)རེད་ཅེས་གསུངས་འདུག་(ག)[།།]

12.  00;53 (བྱས་ཙང་)[དེས་ན་]རྗེ་རིན་པོ་[ཆེའི]་(ཆེ་)བོད་ལ་ཡོད་དུས(་ཙ་)ནས་

13. 00;56 བོད་ལ་(ཡ་)མུ་སྟེགས་པ་ཡོད་མ་རེད་(བ)། [དེས་ཙང་འབྲལ་བ་གང་ཡང་མེད་](ཨེ་ནི་དམུ་སྟེགས་པ་དང་འབྲེལ་བ་ཟིག་གལ་ཡོད་མ་རེད་བ།)

 14. 01;00ཕྱི་[ལོགས་སུ་]ལོག་(ལ་)ཡོད་པའི་མུ་སྟེགས་པ་(ཚོ་དང་འབྲེལ་བ་ཟིག་གལ་ཡོད་མ་རེད་བ། ང་ཚོ་བོད་ལ་ཡ། [སོག་དང་འབྲེལ་བ་གང་ཡང་མེད།]

15. 01;04 [བྱེས་](བྱས་)ཙང་(ག་)རྗེ་རིན་པོ་ཆེས་[འདི](་དེ་)གསུངས་པ་རེད།

  16.  01;07 (ད་)དེང་སང་ང་[རང་]ཚོ་(ད།)[ཐ་]ལྟ་གྲུབ་འདྲ་[མིན་](མི་འདྲའི་དཀྱིལ་ལ་ཡ་བསྡད་དེ་ཡོད་རེད་བ།)[མིན་ཀྱིས་ལ་ཚོར་བ་སྐྱེལ་ཡོད།]

 17.  01;14 (དེ་ཙམ་དུ་མ་ཟད་པས།)(ད་ང་ཚོ་)[དེས་མཉམ་དུས་]བོད་པའི་ངོས་ནས་བཤད་པ་ཡིན་ན་(རེད་གདའ།)

 18.  01;18 མ་འོངས་[པར་](པ་)ལ་ཡ། ང་ཚོ་(ད་)བོད་[ནང་]ལ་(ཡ་)གཞིས་བྱེས་

19.  01;22 མཉམ་འཛོམས་བྱུང་བའི་རྗེས་ལ་ཡིན་(ན་)ཡང་(། )(ད་)འཛམ་(བུ་)གླིང་འདི་

29.  01;25 གཅིག་[གིས]་(གི)་གཅིག་[ལ](གི)་འབྲེལ་བ(་དེ་ཞེ་དྲག་)ཤུགས་ཆེན་པོ་ཡོ་(ཡོད་)རེད།

21.  01;28 འབྲེལ་བ(།) གཅིག་[གིས]་(གི་)གཅིག་[ལ་](གི་(ཕ་གིའི་)འབྲེལ་བ་(ཐག་ཉེ་བོ་གཅིག་)[མཐའ་ཉེ་པོ་]དགོས་(ཀི་)[སྐྱིས་ཡ་]རེད་

22.  01;32 [སོ་འདི་](སེ་དེ་འདྲས་)[འདྲ་ཞིག་](གཅིག་)ཡིན་དུས་ཙང་(ཙ་)ནས། གང་[བརྟར་](ལྟར)འཛམ(་བུ་)གླིང་གི་ས་ཆ་

 23.  01;36 [གང་དུ་](ག་བ་)བསྡད་ཡོད་ནས་མེད་ནས[་]། གང་[བརྟར་]ལྟར་ལྟ་གྲུབ་འདྲ་[མིན་]མི་(འདྲའི་)དཀྱིལ་ལ་ང་ཚོ་ཡོད་(ཡོད་)པ་རེད་(བ)།

24.  01;40 (ALL WORLD རེད་བ། ད་ག་རེ་ཟེར་བ་རེད།) WORLD ད་ག་རེ་ཟེར་བ་རེད། གླིང་འདྲ་བོ་གཅིག་བཟོ་འདྲ་ཆགས་ཡོང་གི་འདུག་ག) འཛམ་གླིང་ཡོངས་རྫོགས་(ལོག་དེ་)[གླིང་གཅིག་]

25.  01;48 [དུས་]ཆགས་ཡོང་གིས་(གིན)་འདུག་བ། [འཛམ་གླིང་ཡོང་(ཡོངས་རྫོགས་ལོག་དེ་)[འཛོག་བཤད་ཡ་འདི་]

26. 01; 51 བྱས་ཙང་(ག་)འཛམ་གླིང་[ཡོང་](ཡོངས་རྫོགས་ལོག་དེ།)[འཛོག་]གླིང་གཅིག་ཆགས་[ཡིང](་ཡིན་)དུས་[ཙང](་ཙ་)ནས་

27. 01;53 གླིང་གཅིག་ཆགས་(བསྡད་མཁན་)[བདེ་ངེན་]གྱི་གླིང་(དེ)[འདི་]

28.  01;56 (ད་གང་ལྟར། རིག་གཞུང་མི་འདྲ་མི་འདྲ་ཡོད་བསྡད་པ། རིག་གཞུང་། རིག་གཞུང་། )རིག་གཞུང་སྣ་ཚོགས་ཅན།

 29.  02;03 ཆོས་ལུགས་སྣ་ཚོགས་ཅན། གྲུབ་མཐའ་སྣ་ཚོགས་ཅན་(གཅིག་)[ཅིག]་ཆགས་(བསྡད་ཡོད་རེད་བ།)[བདེ་ཡོད་ར།]

30. 02;08 སེ། (དེ་འདྲས་)[དེས་འགྲ་]ཡིན་དུས་[ཙང](་ཙ་)ནས(།)[་]ང་རང་ཚོ་དེ་སྔ་བོད་ལ་ཡ་[ཅིག་]གཅིག 

31.  02;14 ཆོས་བྱེད་མཁན་[ཞིག་](གཅིག་ཡིན་པ་)ཡིན་ན། [ཨ་ནི་](ཨེ་ནི།)

32.  02;17 (གཅིག)[ཅིག་]ལམ་རིམ་འདྲ་འདྲ། ཨེ་ནི་བློ་ལྡོག་རྣམ་བཞི་འདྲ་འདྲ་

33.  02;21 [ཅིག་](གཅིག་)[འདི་](དེ་འདྲའི་)[འགྲ་ཡི་]ཐོག་ནས[་](། )[ཨ་](ཨེ་ནི་མར་)[མ་]་འདུམ་བདེ་པོ་བྱས་ནས(།)[་་]འཁྲིད་ཡ་(ཞིག་)[ཤིག་]་འདུག་(ག)[བ་]

 34. 02;25 [དེ་](དེའི་)དུས་ཚོད་ཡོལ་རེད་(བཞག་)[ཤ]། [བྱེད་ཙང་](བྱས་ཙང་)ཁྱེད་རང་ཚོ་ཀོ་རི་ཡར་ཆ་བཞག་ནས།

 35. 02;30 ( ད་)[ཐ་]དེ་སྔ་ང་(རང་)ཚོས་ད་གཅིག་(ནམ་རྒྱུན་)[ཉི་མ་རྟག་པར་]ཆོས་(ཟེར་)བཤད་(ལབ་)དུས་ཡིན་ཤག་ཤག་(འདྲ་བོ་)བྱས་(ཀྱིས་) [བྱེས་]

 36. 02;37 སངས་རྒྱས་པའི་ཆོས་(ཟེར་ལབ་དུས་གཅིག་)[བཤད་དུས་]ཡིན་ཤག་ཤག་(འདྲ་བོ་)[བྱེས་](བྱེད་བསྡད་ཡ་ད་འདིའི།)་[བདེ་ཡ་ཐ་འདི་]

37.  02;41 ཐོག་ནས་དད་པ་བྱེད་པ་ཡ་དེ་དུས་ཚོད་ཡོལ་(བ་)རེད། (སེ། དེ་འདྲས་)[ཚོ་དེས་འགྲ]་ཡིན་དུས་(ཙ་)[ཙང་]ནས་

38.  02;47[ཐ་](ད་)ཕྱི་ནང་གི་གྲུབ་མཐའ་སྣ་ཚོགས་པ་(དེ་གའི་དེ་)[འདི་རིགས་]ཤེས་དགོས་ཡ་རེད་(བཞག)[ཤ།།]

39.  02;55 [ཐ་](ད་)ཕྱི་ནང་གི་སྣ་ཚོགས་(པའི་)གྲུབ་མཐའ་ཟེར་དུས(་ཙ་)[ཙང་]ནས། 

40.   02;59 དེ་སྔ་རྒྱ་གར་ལ་ཡོད་པའི་འདི་[ཅིག་](གཅིག་)པོ་(ཡིས་འདང་གིན་)[གདངས་ཀྱིས་](་མི་)[མིན་]འདུག་(ག)[བ]

41.  03;03 [ ཐ](ད་)ད་ལྟ་འཛམ་(བུ་)གླིང་འདིའི[་སྟེང་](སྒང་)ལ་ཡོད་པའི་[ཅིག་](གཅིག་)ཡེ་ཤུ། [དེ་བཞིན་]ད་ག་ནང་བཞིན་གྱི་ཁ་ཆེ།

42.  03;08 [དེ་ནཞིན་](ད་ག་ནང་བཞིན་གྱི་)འཇིའུ། 

43.  03;11 (ད་ག་ནང་བཞིན་གྱི་དཔེར་ན) ཛོ་ལ་ཛོ་དིམ། (པར་སིག་གི པར་སིག་གི་ཆོས་ལུགས་གཅིག་འདུག་ག) བྷོམ་སྦེལ་(དེ་བ་ཏོག་ཙམ་ཡོད་རེད།)ཁུལ་དུ་ཡོད་

44.  03;18 [ཐ་] (ད་འོ་)དེ་དང་དེ་འདྲ་བ། ད་དཔེར་ན་ངས་ཤེས་པ་[དི](དེ་ཚོའི)ཚོ་[དྲས་](གྲས་)རེད། [ཐ་]ད་)དེ་དང་དེ་འདྲ་བའི།

45.   03; 24 [ཨ་ནི་](ཨེ་ནི་ག་རེ་ཟེར་བ་རེད། (ཕ་གིའི་)ཆོས་ལུགས་(དེ་ཚོའི་)[འདི་ཚོས་]འགྲོ་སྟངས་(ཀྱང་)ཤེས་དགོས་ཡ་(གཅིག་)[ཅིག་]རེད་(བཞག)[ཤ།།]


གསལ་བཤད་ཞུ་དགོས་པ་འགའ་གཤམ་གསལ།
 
དང་པོ། གསུང་སྒྲ་ཡིག་ཕབ་བྱས་པ་དེ་ཚོའི་ནང་། གོང་ས་མཆོག་གིས་གང་གསུང་ཐམས་ཅད་ཡིག་ཐོག་ལ་བཀོད་ཐུབ་མི་འདུག 
གཉིས་པ། གང་ཡིག་ཐོག་བཀོད་པ་དེ་དག་ཀྱང་དག་ནོར་ཆེ་འདུག་སྙམ།
གསུམ་པ། གོང་ས་མཆོག་གིས་གསུང་མེད་པའི་རང་ཚིག་མང་པོ་འདུག་པ་བཅས་དེ་དག་སླད་མར་ཡིད་གཟབ་དགོས་པར་སྣང་། 
 
བཞི་པ། ངས་ཐོག་མར་བཀའ་སློབ་སྒྲ་དངོས་དང་ཡིད་ཐོག་བཀོད་པ་དེ་དག་དང་བསྡུར་ཏེ། གསུང་པ་ནང་བཞིན་འཁོད་མེད་པ་རྣམས་ཁ་གསབ་བྱེད་དེ་རྟགས་འདི་()བརྒྱབས་ཡོད། ཡང་ཡིག་བཀོད་པའི་རིགས་ལ་དག་ནོར་བཅོས་ཏེ་རྟགས་འདི་()བརྒྱབས་ཡོད་པ་དང་། དག་ནོར་དང་ཚིག་ལྷག  རང་ཚིག་མི་དགོས་པའི་རིགས་རྣམས་རྟགས་འདི་[]བརྒྱབས་ཡོད་པས། རྟགས་ཕྱི་མ་ཅན་རྣམས་མེད་གསུབ་དགོས་པ་ཡིན་པས་ཞབ་གཟིགས་ཡོང་བར་ཞུའོ།། 
 

2023-03-20 07:29 UTC, Tenzindakar commented
Hello ma'am
Can I edit it later because my exam is going on.

On Mon, 20 Mar, 2023, 12:43 pm Tenzindharten, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> 1་ 00:00 [ཡ་ཡ་] (ཡ་)གྲུབ་མཐའ།
> (ད་འདིའི་)འགོ་ནས་(མར་)བཤད་(ཡ་ཟིག)(གལ་མི་)འདུག་(ག
>
>   2་
> 00:03(ད་འདིར་)རང་གཞན་གྱི་གྲུབ་མཐའི་རྣམ་གཞག་མདོར་བསྡུས་(ཏེ་བརྗོད་པ་ལ་གཉིས།)
> [ན་གཉིས།]
>
>  3. 00:11 སྤྱིར་བསྟན་པ་དང༌། བྱེ་བྲག་ཏུ་བཤད་(པ།) [པའོ།།] རྙེད་སོང་བས།
> ས་བཅད་དེ། འདུག་ག
>
>    1.
>
>    00:15 བྱས་ཙང་། ད་འདིར། རྗེ་རིན་པོ་ཆེའི་
>    <http://%E0%BD%86%E0%BD%BA%E0%BC%8B%E0%BD%A1%E0%BD%B2>
>    ་(སྔགས་རིམ་ཆེན་མོའི་)
>    2.
>
>    00;22སྔགས་རིམ་ཆེན་མོའི་ནང་ལ་(ཡང་)། (གསུངས་ཡོད་རེད།) འགོ་དེར། (ཨེ་ནི)
>    3.
>
>    00;27 [དེས་]ཨེ་ནི་[འགོ་འཛུགས་ལ་]མུ་སྟེགས་བྱེད་ཡོད་དམ་མེད་ཀྱང་(སླ་ཡི།)
>    4.
>
>    00;35)སླར་ཡིན་
>    <http://%E0%BD%A2%E0%BD%84%E0%BC%8B%E0%BD%A2%E0%BD%84%E0%BC%8B%E0%BD%A6%E0%BD%BC%E0%BC%8B%E0%BD%A6%E0%BD%BC%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%B4%E0%BD%91%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%A1%E0%BC%8B>
>    5.
>
>    00;38 སྔོན་གྱི་ལྟ་བ་ཕྱིན་ཅི་ལོག་[གིས་]དེ་འདྲའི་བག་ཆགས་
>
>  9. 00;42 ང་(རང་)ཚོའི་རྒྱུད་ལ་ཡོད་པ་ཡིན་དུས[་]།
> (ཨེ་ནི།)ལྟ་བ་འདྲ་(མི་འདྲ་)[མིན་]
>
>  10. 00;47དེ་དག་
> <http://%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%A6%E0%BE%90%E0%BD%91%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BC%8B>ཤེས་པར་བྱས་ནས།
> (ཨེ་ནི་འཐད་མི་འཐད་ཀྱིས) [ཏག་ཏག་ཡིན་དང་མིན་]
>
>    1.
>
>     00;50 དཔྱད་པ་བྱ་རྒྱུ་
>    <http://%E0%BD%96%E0%BE%B1%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%A1%E0%BC%8B%E0%BD%91%E0%BD%BA>
>    ་[དེས་ཧ་ཅང་གི་]གལ་ཆེན་པོ(་ཞེ་དྲག་)རེད་ཅེས་གསུངས་འདུག་(ག)[།།]
>    2.
>
>     00;53 (བྱས་ཙང་)[དེས་ན་]རྗེ་རིན་པོ་[ཆེའི]་(ཆེ་)བོད་ལ་ཡོད་དུས(་ཙ་)ནས་
>    3.
>
>    00;56 བོད་ལ་(ཡ་)མུ་སྟེགས་པ་ཡོད་མ་རེད་(བ)། དེས་ཙང་འབྲལ་བ་གང་ཡང་མེད་
>    <http://%E0%BD%A8%E0%BD%BA%E0%BC%8B%E0%BD%93%E0%BD%B2%E0%BC%8B%E0%BD%91%E0%BD%98%E0%BD%B4%E0%BC%8B%E0%BD%A6%E0%BE%9F%E0%BD%BA%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%94%E0%BC%8B%E0%BD%91%E0%BD%84%E0%BC%8B%E0%BD%A0%E0%BD%96%E0%BE%B2%E0%BD%BA%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BC%8B%E0%BD%9F%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%82%E0%BD%A3%E0%BC%8B%E0%BD%A1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BC%8B%E0%BD%A2%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%96%E0%BC%8D>
>
>  14.
> 01;00ཕྱི་[ལོགས་སུ་]ལོག་(ལ་)ཡོད་པའི་མུ་སྟེགས་པ་(ཚོ་དང་འབྲེལ་བ་ཟིག་གལ་ཡོད་མ་རེད་བ།
> ང་ཚོ་བོད་ལ་ཡ། [སོག་དང་འབྲེལ་བ་གང་ཡང་མེད།]
>
>    1. 01;04 བྱེས་ <http://%E0%BD%96%E0%BE%B1%E0%BD%A6%E0%BC%8B>
>    ཙང་(ག་)རྗེ་རིན་པོ་ཆེས་འདི <http://%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BC%8B>
>    གསུངས་པ་རེད།
>
>   16. 01;07 (ད་)དེང་སང་ང་[རང་]ཚོ་(ད།)[ཐ་]ལྟ་གྲུབ་འདྲ་མིན་
> <http://%E0%BD%98%E0%BD%B2%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BE%B2%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%91%E0%BD%80%E0%BE%B1%E0%BD%B2%E0%BD%A3%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%A1%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%A1%E0%BD%91%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%A1%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%A2%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%96%E0%BC%8D>
> [མིན་ཀྱིས་ལ་ཚོར་བ་སྐྱེལ་ཡོད།]
>
>  17. 01;14
> (དེ་ཙམ་དུ་མ་ཟད་པས།)(ད་ང་ཚོ་)[དེས་མཉམ་དུས་]བོད་པའི་ངོས་ནས་བཤད་པ་ཡིན་ན་(རེད་གདའ།)
>
>  18. 01;18 མ་འོངས་པར་ <http://%E0%BD%94%E0%BC%8B>ལ་ཡ།
> ང་ཚོ་(ད་)བོད་[ནང་]ལ་(ཡ་)གཞིས་བྱེས་
>
>    1.
>
>     01;22 མཉམ་འཛོམས་བྱུང་བའི་རྗེས་ལ་ཡིན་(ན་)ཡང་(། )(ད་)འཛམ་(བུ་)གླིང་འདི་
>    2.
>
>     01;25 གཅིག་[གིས]་(གི)་གཅིག་ལ <http://%E0%BD%82%E0%BD%B2>
>    ་འབྲེལ་བ(་དེ་ཞེ་དྲག་)ཤུགས་ཆེན་པོ་ཡོ་(ཡོད་)རེད།
>    3.
>
>     01;28 འབྲེལ་བ(།)
>    གཅིག་[གིས]་(གི་)གཅིག་[ལ་](གི་(ཕ་གིའི་)འབྲེལ་བ་(ཐག་ཉེ་བོ་གཅིག་)[མཐའ་ཉེ་པོ་]དགོས་(ཀི་)[སྐྱིས་ཡ་]རེད་
>    4.
>
>     01;32 སོ་འདི་
>    <http://%E0%BD%A6%E0%BD%BA%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BE%B2%E0%BD%A6%E0%BC%8B>
>    འདྲ་ཞིག་ <http://%E0%BD%82%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B>
>    ཡིན་དུས་ཙང་(ཙ་)ནས། གང་བརྟར་ <http://%E0%BD%A3%E0%BE%9F%E0%BD%A2>
>    འཛམ(་བུ་)གླིང་གི་ས་ཆ་
>
>  23. 01;36 གང་དུ་ <http://%E0%BD%82%E0%BC%8B%E0%BD%96%E0%BC%8B>
> བསྡད་ཡོད་ནས་མེད་ནས[་]། གང་[བརྟར་]ལྟར་ལྟ་གྲུབ་འདྲ་[མིན་]མི་(འདྲའི་)དཀྱིལ་ལ་ང་ཚོ་ཡོད་(ཡོད་)པ་རེད་(བ)།
>
>    1.
>
>    01;40 (ALL WORLD རེད་བ། ད་ག་རེ་ཟེར་བ་རེད།) WORLD ད་ག་རེ་ཟེར་བ་རེད།
>    གླིང་འདྲ་བོ་གཅིག་བཟོ་འདྲ་ཆགས་ཡོང་གི་འདུག་ག)
>    འཛམ་གླིང་ཡོངས་རྫོགས་(ལོག་དེ་)[གླིང་གཅིག་]
>    2.
>
>     01;48 [དུས་]ཆགས་ཡོང་གིས་(གིན)་འདུག་བ།
>    [འཛམ་གླིང་ཡོང་(ཡོངས་རྫོགས་ལོག་དེ་)[འཛོག་བཤད་ཡ་འདི་]
>    3.
>
>    01; 51 བྱས་ཙང་(ག་)འཛམ་གླིང་ཡོང་
>    <http://%E0%BD%A1%E0%BD%BC%E0%BD%84%E0%BD%A6%E0%BC%8B%E0%BD%A2%E0%BE%AB%E0%BD%BC%E0%BD%82%E0%BD%A6%E0%BC%8B%E0%BD%A3%E0%BD%BC%E0%BD%82%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BC%8D>
>    [འཛོག་]གླིང་གཅིག་ཆགས་ཡིང
>    <http://%E0%BC%8B%E0%BD%A1%E0%BD%B2%E0%BD%93%E0%BC%8B>དུས་ཙང
>    <http://%E0%BC%8B%E0%BD%99%E0%BC%8B>ནས་
>    4.
>
>    01;53 གླིང་གཅིག་ཆགས་(བསྡད་མཁན་)[བདེ་ངེན་]གྱི་གླིང་(དེ)[འདི་]
>    5.
>
>     01;56 (ད་གང་ལྟར། རིག་གཞུང་མི་འདྲ་མི་འདྲ་ཡོད་བསྡད་པ། རིག་གཞུང་།
>    རིག་གཞུང་། )རིག་གཞུང་སྣ་ཚོགས་ཅན།
>
>  29.  02;03
> ཆོས་ལུགས་སྣ་ཚོགས་ཅན། གྲུབ་མཐའ་སྣ་ཚོགས་ཅན་(གཅིག་)[ཅིག]་ཆགས་(བསྡད་ཡོད་རེད་བ།)[བདེ་ཡོད་ར།]
>
>    1.
>
>    02;08 སེ། (དེ་འདྲས་)[དེས་འགྲ་]ཡིན་དུས་ཙང
>    <http://%E0%BC%8B%E0%BD%99%E0%BC%8B>
>    ནས(།)[་]ང་རང་ཚོ་དེ་སྔ་བོད་ལ་ཡ་[ཅིག་]གཅིག
>    2.
>
>     02;14 ཆོས་བྱེད་མཁན་ཞིག་
>    <http://%E0%BD%82%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%A1%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%94%E0%BC%8B>ཡིན་ན།
>    ཨ་ནི་ <http://%E0%BD%A8%E0%BD%BA%E0%BC%8B%E0%BD%93%E0%BD%B2%E0%BC%8D>
>    3.
>
>     02;17 (གཅིག)[ཅིག་]ལམ་རིམ་འདྲ་འདྲ། ཨེ་ནི་བློ་ལྡོག་རྣམ་བཞི་འདྲ་འདྲ་
>    4.
>
>     02;21 ཅིག་ <http://%E0%BD%82%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B>འདི་
>    <http://%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BE%B2%E0%BD%A0%E0%BD%B2%E0%BC%8B>
>    [འགྲ་ཡི་]ཐོག་ནས་ <http://%E0%BC%8D>ཨ་
>    <http://%E0%BD%A8%E0%BD%BA%E0%BC%8B%E0%BD%93%E0%BD%B2%E0%BC%8B%E0%BD%98%E0%BD%A2%E0%BC%8B>
>    [མ་]་འདུམ་བདེ་པོ་བྱས་ནས(།)[་་]འཁྲིད་ཡ་(ཞིག་)[ཤིག་]་འདུག་(ག)[བ་]
>
>  34. 02;25 དེ་ <http://%E0%BD%91%E0%BD%BA%E0%BD%A0%E0%BD%B2%E0%BC%8B>དུས་ཚོད་ཡོལ་རེད་(བཞག་)[ཤ]།
> བྱེད་ཙང་
> <http://%E0%BD%96%E0%BE%B1%E0%BD%A6%E0%BC%8B%E0%BD%99%E0%BD%84%E0%BC%8B>
> ཁྱེད་རང་ཚོ་ཀོ་རི་ཡར་ཆ་བཞག་ནས།
>
>  35. 02;30 (
> ད་)[ཐ་]དེ་སྔ་ང་(རང་)ཚོས་ད་གཅིག་(ནམ་རྒྱུན་)[ཉི་མ་རྟག་པར་]ཆོས་(ཟེར་)བཤད་(ལབ་)དུས་ཡིན་ཤག་ཤག་(འདྲ་བོ་)བྱས་(ཀྱིས་)
> [བྱེས་]
>
>  36. 02;37 སངས་རྒྱས་པའི་ཆོས་(ཟེར་ལབ་དུས་གཅིག་)[བཤད་དུས་]ཡིན་ཤག་ཤག་(འདྲ་བོ་)
> བྱེས་
> <http://%E0%BD%96%E0%BE%B1%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%A1%E0%BD%91%E0%BC%8B%E0%BD%A1%E0%BC%8B%E0%BD%91%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BD%B2%E0%BD%A0%E0%BD%B2%E0%BC%8D>
> ་[བདེ་ཡ་ཐ་འདི་]
>
>    1.
>
>     02;41 ཐོག་ནས་དད་པ་བྱེད་པ་ཡ་དེ་དུས་ཚོད་ཡོལ་(བ་)རེད། (སེ།
>    དེ་འདྲས་)[ཚོ་དེས་འགྲ]་ཡིན་དུས་(ཙ་)[ཙང་]ནས་
>    2.
>
>     02;47ཐ་ <http://%E0%BD%91%E0%BC%8B>
>    ཕྱི་ནང་གི་གྲུབ་མཐའ་སྣ་ཚོགས་པ་(དེ་གའི་དེ་)[འདི་རིགས་]ཤེས་དགོས་ཡ་རེད་(བཞག)[ཤ།།]
>    3.
>
>    02;55 ཐ་ <http://%E0%BD%91%E0%BC%8B>
>    ཕྱི་ནང་གི་སྣ་ཚོགས་(པའི་)གྲུབ་མཐའ་ཟེར་དུས(་ཙ་)[ཙང་]ནས།
>    4.
>
>     02;59 དེ་སྔ་རྒྱ་གར་ལ་ཡོད་པའི་འདི་ཅིག་
>    <http://%E0%BD%82%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B>པོ་(ཡིས་འདང་གིན་)
>    གདངས་ཀྱིས་ <http://%E0%BC%8B%E0%BD%98%E0%BD%B2%E0%BC%8B>
>    [མིན་]འདུག་(ག)[བ]
>    5.
>
>    03;03  ཐ <http://%E0%BD%91%E0%BC%8B>ད་ལྟ་འཛམ་(བུ་)གླིང་འདིའི་སྟེང་
>    <http://%E0%BD%A6%E0%BE%92%E0%BD%84%E0%BC%8B>ལ་ཡོད་པའི་ཅིག་
>    <http://%E0%BD%82%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B>ཡེ་ཤུ།
>    [དེ་བཞིན་]ད་ག་ནང་བཞིན་གྱི་ཁ་ཆེ།
>    6.
>
>    03;08 དེ་ནཞིན་
>    <http://%E0%BD%91%E0%BC%8B%E0%BD%82%E0%BC%8B%E0%BD%93%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BD%9E%E0%BD%B2%E0%BD%93%E0%BC%8B%E0%BD%82%E0%BE%B1%E0%BD%B2%E0%BC%8B>
>    འཇིའུ།
>    7.
>
>    03;11 (ད་ག་ནང་བཞིན་གྱི་དཔེར་ན) ཛོ་ལ་ཛོ་དིམ། (པར་སིག་གི
>    པར་སིག་གི་ཆོས་ལུགས་གཅིག་འདུག་ག) བྷོམ་སྦེལ་(དེ་བ་ཏོག་ཙམ་ཡོད་རེད།)ཁུལ་དུ་ཡོད་
>    8.
>
>    03;18 [ཐ་] (ད་འོ་)དེ་དང་དེ་འདྲ་བ། ད་དཔེར་ན་ངས་ཤེས་པ་དི
>    <http://%E0%BD%91%E0%BD%BA%E0%BC%8B%E0%BD%9A%E0%BD%BC%E0%BD%A0%E0%BD%B2>
>    ཚོ་དྲས་ <http://%E0%BD%82%E0%BE%B2%E0%BD%A6%E0%BC%8B>རེད།
>    [ཐ་]ད་)དེ་དང་དེ་འདྲ་བའི།
>    9.
>
>     03; 24 [ཨ་ནི་](ཨེ་ནི་ག་རེ་ཟེར་བ་རེད།
>    (ཕ་གིའི་)ཆོས་ལུགས་(དེ་ཚོའི་)[འདི་ཚོས་]འགྲོ་སྟངས་(ཀྱང་)ཤེས་དགོས་ཡ་(གཅིག་)[ཅིག་]རེད་(བཞག)[ཤ།།]
>
> གསལ་བཤད [...]

2023-03-21 12:59 UTC, Tenzindharten requested changes
1. 03:31 (ཨེ་ནི། དེ་གའི་དེའི་) [འདིའི་ལྟ་གྲུབ་](ལྟ་བ་)དང་གྲུབ་མཐའ(་དེ་གའི་དེ་)ཤེས་དགོས་ཡ་རེད་(བཞག) [ཤ་]
2. 03:35 དེ་ཙམ་དུ་མ་ཟད་པའི་ཨ་ནེ་[འདིར་སྐད་ཐོག་གསུང་པ་དེ་འབྲི་དགོས་རེད་འདུག]་ནུབ་ཕྱོགས་(པའི་ལྟ་བ།)
3.  03:40 [པའི]་(ལྟ་བ། )[སྟེ།]
4. 03:45 གཅིག་མིའི་བསམ་བློའི་ཐོག་ནས་གཅིག་བསམ་བློ་[གཏང](གཏོང་བསྡད་ཡ་དེ་འདྲའི་)[བདེ་ཡ་དེས་འགྲ་ཡི་]
5. 03:49 ལྟ་གྲུབ་དེ་(འདྲའི་)[འགྲ་]འདུག་(ག)[བ]། (དེ་ཚོའི་གྲས་ག་ཤེས་དགོས་ཡ་རེད་བཞག )[འདི་ཚོ་འབྲས་ཤེས་དགོས་པ་རེད་ཤ།།]
6. 03:53  (དེ་ག་ནང་བཞིན་གྱི་)[འདིའིར་དབར་ཡང་དབྱིན་སྐད་གསུང་པ་དེ་འབྲི་དགོས་འདུག][དེ་བཞིན་]དེང་དུས་ཀྱི་ཚན་རིག་ཤེས་དགོས་ཡ་རེད་(བཞག)[ཤ།།]
7. 03:57  [འདི](་དེ་གའི་དེ་)ཚང(་མ)་[མར]་(གཅིག) (ད) [ཅིག་]ང་(ཚོ་)[ཚོས་]དོ་སྣང་(བགྱིས།)[བྱས་](ད་)དཔྱིས་ཕྱིན་པ་ཤེས་ཡ་(དེ།)(སྔོན་ལ་ཁག་པོ་རེད་དེ།)དེས་ཁག་པོ་རེད་དེ། 
8. 04:03 ཡིན་ནས[་གང་དག་](གང་ལྟར་གཅིག་)གནད་འགག་གནད་འགག་(འདྲ་བོ་དེ་)[འདི]་ཤེས་པ[་འབྱུང་](གཅིག་བྱུང)་ན།
9. 04:07 དེས་ཕན་ཐོགས་ཞེ་དྲག་[ས་]ཡོད་རེད། [དེས་]གལ་ཆེན་པོ་རེད་(བཞག)[ཤ།]
10. 04:11 (འོ་ད་)[ཐ་]ཡང་བསྟན་པ་སྤྱི་(མཚན།)[བཙན།] གང་ཟག་སྒོས[་བཙན་](མཚན་ཟེར་ནས།)[བྱེས་ནས།]
11. 04:16 ཡ་འགྲོ་སྟངས་མི་འདྲ་བ་གཉིས་ཡོང་གི་ཡོད་རེད། བོད་ཀྱི་ད(་ལྟ་)[་ྲམཐའ་གཉན]་(གཉེན)་མགོན་གསུང་རབ་པ། 
12. 04:22 ཁམས་ཀྱི་ད་ལྟ་[ཁམ་གིས་]མགོ་ལོག་(གི་)[ཀྱི་]གཉེན་མགོན་སྤྲུལ་སྐུ[འི་]གསུང་རབ་པ་ཟེར་ཡ་(གཅིག་)འདུག་ག)[བ་]
13. 04:27 (འོ་)ཁོང་གིས་[འདིའདྲ་]་དེ་འདྲའི་གསུང་(བཞག)[ཤ] བསྟན་པ་སྤྱི་མཚན།)[བཙན།] གང་ཟག་སྒོས་མཚན་[བཙན]་ཟེར་ཡ་གཅིག 
14.  04:32 [བྱེ་](ཟེར་ཡ་འདི་གནད་འགག་རེད་བཞག) [ཤ་ཐ་]ད་ད་ལྟ་(གཅིག་)ཕྱི་ནང་གི་གྲུབ་མཐའ་ལ་སོགས་པ། 
15.  04:37 [དེ་དག་ཚང་མ་](དེ་ཚོ་ཚང་མ་ལོག་ཅིག་)[ལོ་ཅིག་]ཤེས་དགོས་ཡ་(གཅིག)་[ཅིག་]གལ་ཆེན་པོ་འདུག་ཟེར་ཡ་དེ། (ང་ཚོ།)  [འདི།]
16.  04:40 བསྟན་པ་སྤྱི་མཚན་)[བཙན་བྱེས་](་བྱས)ནས་བཤད་)[ཤེས]་ཡོང་དུས་ཙ་[ཙང་]ནས་(དེའི་རིགས་)[དེ་དག་]ངེས་པར་དུ་དགོས་ཡ་རེད།
17.  04:44 སློབ་སྦྱོང་[བྱེས་](བྱེད)་དགོས་ཡ་དེ། [འདི་ཨ་ཐ་] འོ་ད་གང་ཟག་སྒོས་(བཙན་](མཚན་)ཟེར་དུས་(ཙ)་[ཙང་]ནས།)[ཐ་](ད་ཡང་)གང་ཟག་རིགས་བྱེ་བྲག་པ། 
18.  04:50 [ཨ་](འེ)བྱེ་བྲག་པ་གཅིག་(གིས་)[གྱིས་](ད་)དེ་འདྲ(འི་)རྣམ་གྲངས་མང་པོ་ཤེས་མི་དགོས།[ཁོ།]
19.  04:54  རྣམ་གྲངས་གཅིག་གི་ཐོག་ནས། (ཨ་ནེ)་སོ་སོ[འི་འདི](ད)་ག་རང་ལ་ཡ་(ཨི་ནེ་ཕ་གིའི་མྱོང་བ།)[པའི་ཀྱི་མྱོང་བ]
20.  04:59 སྟོན་གྱིས་ཡང་)[བྱས་]ཉམས་ལེན་(བྱས་ནས་)[བྱེད་སྟེ]་འགྲོ་(སྡོད་མཁན་)[བདེ་མཁན་]དེ་འདྲ(འི)་ཡོང་གི་རེད་བ། 
21.  05:02[ ཨ]་(འེ)དེའི་དབང་དུ་བྱས་པའི་ཡང་(ག)ཅིག་བསྟན་པའི་རྣམ་གཞག་གཏན་ལ་ཕབ་ནས།
22.  05:07  ཉམས་ལེན་བྱེད་ལུགས་ཀྱི་ཁྲིད་ལུགས་(ག)ཅིག་ཡོད་རེད། [ནི](དེ་)གང་ཟག་སྒོས་མཚན་)[བཙན་]
23.  05:11 [གྱི་]དབང་དུ་བྱས་(བྱེད་)་པའི་ཁྲིད་ལུགས(་དེ་བྱེད།)[ཅིག་བྱིས།] ཐ་(ད་)སངས་རྒྱས་ཀྱི་བསྟན་པ་འཛམ་(བུ་)གླིང་
24.  05:15 འདིའི(་སྒང་)གང་ལ་སྤྱིའི་ཆ་ནས་གཏན་ལ་ཕབ་ཡོང་དུས་(ཙ་ནས།)[ནས།འོ་ཐ] (འོ་ད)་ཕྱི་ནང་གི་གྲུབ་མཐའ་
25.  05:20 (གཅིག་)མཆིས་སོ་ཅོག དེ་(གའི་དེ་)[འདི]་ཤེས་པའི་ཐོག་ནས། ཨ་ནེ་)[ནི་འདི་དེས་]ལ་དེ་གའི་དེ་དང་མགོ་བསྟུན། སྒོ་བསྟུན་པ་ཟེར་དགོས་རེད་བས། 
26.  05:27 ཚང་མ་[ཡོང](་ལོག་དེ་)[ལ]་ཡ་འབྲེལ་ཤེས་པའི་ཐོག་ནས། ཨ་(ནེ་)[ནི་]ཁྲིད་ཡ་དེ་གལ་ཆེན་པོ་ཞེ་དྲག་[དྲགས་]རེད།
27.  05:31 [ཐ་ཕ་](བསྟན་པ་)སྤྱི་མཚན་[བཙན་]དབང་དུ་བྱས་པ་)[དུས་བྱེས་པ་]ཡིན་ན། དཔལ་ནཱ་ལེདྲནའི་མཁས་(པ་)[པས་]ཚོས་སངས་རྒྱས་
28.  05:36 ཀྱི་བསྟན་པ་འཛིན་སྐྱོང་སྤེལ་གསུམ་གནང་(སྟངས་དེ།) [བདང་འདི། ]བསྟན་པ་སྤྱི་(མཚན་)[བཙན་གྱི་]དབང་དུ་བྱས་ནས་ཁྲིད་སྟངས་(དེ་)[འདི་]ཪེད།
29. 05:40  [ཐ་བྱེས]་(ད་བྱས་)ན་འདིར་གཅིག་གཟིགས་ཤོག་ཨ།) (འེ་་་འེ་་་འེ།) འེ་འདིའི་དེ་འདྲའི་གཅིག་འདུག་ག [བརྟ་ན་ཨ་ཨ་འདིར་དེས་འགྲ་ཅིག་འདུག་བ་]
30.  05:46འེ་འེ། [ཨ་རྗེའི་] རྗེ་ཪིན་པོ(་ཆེ་ཡིས་)[ཆེས་ཀྱིས་འདིར་དེས་] (འ་ད་དེ་)ཡང་རྗེ་བཙུན་ཙོང་ཁ་པས། [རྗེས་གཙོ་ཙོན་ཁ་པའི།]
31.   05:50 གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་མི་ལྡན་ན། །ངེས་འབྱུང་བྱང་ཆུབ་སེམས་ལ་གོམས་བྱས་ཀྱང༌། །སྲིད་པའི་རྩ་(བ་གཅོད)[་གཅད་]པར་མི་ནུས་པས། །
32.  05:56 [དེ་](དེའི)་ཕྱིར་རྟེན་འབྲེལ་རྟོགས་པའི་ཐབས་ལ་འབད།། ཟེར་ཡ་ལུང་དེ་དྲངས་གནང་ནས། [ཐ་](ད་གང་ལྟར་)[གང་མཐའ་](ཨ་ནེ་)[ནི]་(ཆོས་རབ་ཏུ་རྣམ་འབྱེད་ཀྱི་ཤེས་རབ་འདི།)[དོན་དམ་གཅིག་ཀྱིས་ཤེས་རབ་འདི།]
33.  06:04 (ཨ་ནེ།) [ཨ་ཐ་](འེ་ད་ག་འདྲའི་གཅིག་ཞུ་དགོས་རེད། །) (དཔེར་ན།)( ད་)གནས་ལུགས་རྟོགས་པའི་(ཤེས་རབ་རེད་བ།) [རབས་ར་]གནས་ལུགས་རྟོགས་པའི་ཤེས་(རབ།)[རབས་]ད་རང་སྐད་ཆ་
34.  06:11 བྱུང་བ་(ནང་བཞིན་གྱིས་)[ཞིང་གྱི]་ཨ་(ནེ་)[ནི་]རྟེན་འབྱུང་གི་(དེ་ཁོ་ན་ཉིད་)[ཀྱིས་]ངེས་པའི་ཤེས་རབ་[འདི་](དེ་)མེད་པ་ལ། 
35.  06:16 ཨ་ནེ)་[ནི]འེ་ཐར་པ་ཐོབ་ཐུབ་ཡ་ཡོད་མ་(རེད།) [རེས]་ ཐར་པ་ཙམ་ཡང་ཐོབ་ཐུབ་ཡ་ཡོད་མ་རེད། [རེས]
36.  06:21 [དེས་འགྲ་](དེ་འདྲས་ཡིན་པ་)ཡིན་དུས་ཙང་ནས། ཨ་ནེ། འེ་གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་འདི་མེད་ཐབས་(མེད་བསྡད་པ་རེད་ཟེར་དེ་གསུང་པ་རེེད། )[མི་འདས་པ་མེད་པ་རེད་འདི་གསུངས།]
37.  06:27 [ཨ་ཐ་ཨ་ཐ་](རེད་བ། ད་འེ་འེ། ད་)གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་འདི།
38.  06:35  ཨ་ནེ་)[ནི་ཨ་]འེ་སྤྱིར་ཨ་ནེ། )[ནི]ག་རེ་ཟེར་བ་རེད། དཔེར་ན། འེ་འེ་[ཨ་](རང་སྡེ་)[སྡེའི]་གྲུབ་མཐའ་སྨྲ་བ་ཚང་མ་ལོག་གིས་)ལོགས་ཀྱིས་ཕལ་ཆེར། 
39.   06:43 གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་ཟེར་ཡ་(གཅིག)[ཅིག]་གསུང་གསུང་གི་རེད༑ བདག་མེད་པའི་ལྟ་བ་ཚང་མ་(ལོག་གིས་)[ལོགས་ལ་]གསུང་གི་ཡོད་རེད།

2023-03-22 10:48 UTC, Tenzindharten requested changes
1.  06:48  ད་(ལྟ་)[ཐ་]བདག་མེད་པ་ཟེར་ཡ་འདི། ག་རེ་ཟེར་རེད། ཕ་གིའི་[དེ]་ཡིན་ལུགས་གཅིག་ཡིན་པ་རེད། [བྱེས](་བྱས་)ཙང་ག་[ཁ་]ཡིན་ལུགས་སམ་གནས་ལུགས་ཤིག་ཆགས་ཀྱི་[ཀྱིས་]ཡོད་རེད།
2. 06:55  དེ་རྟོགས་པའི་ཤེས་(རབ།)[རབས] འེ་གྲུབ་མཐའ་བཞི་(ཀ་ལོག་གིས་)[ཆར་   ལོགས་གྱི་]ད་གསུང་གི་ཡོད་རེད། [ཨ་] འེ་རེད་དེ་[དེས]་(ཡིན་ནས།)[ཐ་]
3.  07:01 སྐབས་འདིར་ཨ་(ནེ)[ནི]་གནས་ལུགས་(ག་འདྲས་གཅིག) (གནས་ལུགས་དེ་)ཁོ་ན་ཉིད་[གྱིས་གང་འདྲ་ཞིག་](ག་འདྲའི་གཅིག་)ལ་ཟེར་(གྱི་)[ཀྱི་]ཡོད་རེད་(ལབ་པ་ཡིན་ན།)[་བཤད་ན།]
3.  07:06  རྟེན་འབྱུང་གི་དེ་ཁོ་ན་ཉིད་ལ[་ཡིན་པ་ལ]་ཟེར་(གྱི་)[ཀྱི་]ཡོད་རེད། [ཨ་དེས་](འེ་དེའི་)རྟེན་འབྱུང་གི་(དེ་ཁོ་ན་ཉིད་ཟེར་བསྡད་ཡ་དེ།) [ཡིན་ཟེར་འདི་ཡི། ]
4. 07:13 རྟེན་འབྱུང(་དེ་)[དེས་]རྟེན་འབྲེལ་ཕྲ་མོ། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱིས་གདགས་གཞི་ལ་བརྟེན་ནས། 
5.  07:20 ཨ་ནེ། རྟོག་པས་བཏགས་ཙམ། རྟོག་པས་བཏགས་པ་ལ་བརྟེན་ནས་གྲུབ་པ། རྟོག་པས་བཏགས་ཙམ་ལ་བརྟེན་ནས་ཡོད་པ་
6. 07:28 དེ་འདྲའི་འདྲ་བའི་[ཡིན་དུས་]ད་རྟེན་འབྱུང་ཕྲ་མོ་[འདི](དེ་)་དགོངས་པ་བཞེས་ནས། དེ་འདྲའི་(འདྲ་བའི)་རྟེན་འབྱུང་ཕྲ་མོ་འདི་ཡིས་)ག་རེ་ཟེར་བ་རེད། ཕ་གིའི་ད་རྟེན་འབྱུང་འདི་
7. 07:36 རྒྱུ་མཚན་ལ་བཀོད་ནས། ཨ་ནེ། ངེས་(ཡག་གི)[་ཀྱིས་]གནས་ལུགས་གཅིག་ཡོད་རེད། [ཐ་](ད་)གནས་ལུགས་[འདི]་(དེ་)གནས་ལུགས་ཕྲ་མོ་(དེ་)[འདི་]ཡིན་པ་རེད།
 8.  07:43 གནས་ལུགས་ཕྲ་ཤོས་དེ[ས་]ཆགས་[བདེ]་བསྡད་ཡོད་རེད།གནས་ལུགས་ཕྲ་ཤོས(་དེ།)[ཐ་དེས](ད་འོ་དེ་འདྲའི་འདྲ་བའི་ཨ་ནེ་ག་རེ་ཟེར་བ་རེད་བ།)ཕ་གིའི་འེ་འེ་གནས་ལུགས་དེ་ཤེས་དགོས་ཀི་རེད་ཟེར་གསུངས། [ས་བཤད་དགོས་ཀྱིས་རེད་གསུངས་]
9.  07:52 [ཐ་]ད་དེ་འདྲའི་[འདིའབྲེ་ཡི་]རྟེན་འབྱུང་ཕྲ་མོ་དེ་[འདི་]ཨ་ནེ་ངེས་པ་ལ་ཡ། ལྟོས་ནས་བཏགས་པའི་
10. 08:01 [སྤྱེ་རེས]སྤྱིར་ཨ་ནེ་ལྟོས་ནས་བཏགས་པའི། ག་རེ་ཟེར་རེད། ཕ་གིའི་ལྟོས་ནས་[བསྒྲུབ་](གྲུབ་)པའི་ཨ་ནེ་ལྟོས་ནས་བཏགས་པའི་
11. 08:08 རྟེན་འབྱུང་[དེས་](དེ་)གཅིག་ངེས་དགོས་ཀྱི[་ཀྱིས]་ཡོད་རེད། [ཨ་] འེ་)བརྟེན་ནས་བཏགས་པའི་རྟེན་འབྱུང་དེ)འདི་ངེས་པ་ལ་ཡ། 
12. 08:14 ཨ་(ནེ)[ནི]་རྒྱུ་འབྲས་རྟེན་འབྱུང་གི་ʼཨ་]རྟེན་འབྲེལ་[འདི](དེ)་ངེས་དགོས་ཀྱི་[ཀྱིས་]ཡོད་རེད། (རེད་བ། ད་)[ཐ་ཨ་དེས་](དེ་འདྲས་ཡིན་དུས་ཙ་ནས།)[ཙང་]
13. 08:23 ནས་[ཐ་](གང་ལྟར་)[སྟ་]རྟེན་འབྲེལ་ཟེར་ཡ་འདི། ཕར་སྔོན་ལ་ཕྲ་མོ་[འདི]་དེ་ཤེས་པ་ལ་ཡ། དེའི་རགས་པ་དེ་ཤེས་དགོས་ཡ།
14.  08:29[འདི]་དེའི་རགས་པ་དེ་ཤེས་དགོས་ཡ། དེའི་དེ་མར[་སླེབ་ཡིང་]སླེབ་ཡོང་དུས་ཕལ་ཆེར་དངོས་པོའི་གནས་ལུགས་དེའི་དེ་ཤེས་དགོས་ཡ། [འདི་དག་ཤེས་དགོས་ཡ།]
15.  08:36 སྤྱིར་བཏང་(གི)་དངོས་པོའི་རང་བཞིན་[འདི་བཤད་]དེ་གའི་དེ་དགོས་ཡ། [ཐ་འདི་](ད་དེ་ཚོ་འབྲེས་སྦྲེལ་ཡོང་གི་ཡོད་རེད་གདའ། ད་དངོས་པོའི)[གྱིས་ཡོད་རེད། ཐ་དངོས་པོ་]
16.  08:43 [སྣས་](གནས)་ལུགས་མར་བཤད་ཡོང་དུས་[ཙང་](ཙ)་ནས། དེང་སང་དཔེར་ན། བཤད་ཚུལ་དེང་བསང་གི་མིང་ཚིག་ནང་བཞིན་བྱས་ནས།
17.  08:48  དངོས་ཁམས་རིག་པ། སེམས་ཁམས་རིག་པ། རྫས་འགྱུར་རིག་པ་ལ་སོགས་པ་དེ་[ཀྱང་]རྐྱང་སླེབ་ཡོང་གི་འདུག་བ། ཟེར། (རྒྱ་ཆེན་པོ་ཞེ་བུ་གཅིག་ཆགས་ཡོང་གི་འདུག་ག)  [ གལ་ཆེན་པོ་ཞེས་པོ་ཆགས་ཡོང་ཀྱི་འདུག་བ།]

2023-03-23 09:47 UTC, Tenzindharten requested changes
1.  08:56 རྟེན་འབྲེལ་ཟེར[་ཡ་](ཡག་གི་)འེ། [འདི་ཨ་ཚིགས་](ཚིག་འདི་ཡི་)[འདིའི་ཀྱི་]བརྗོད་གཞི[འི་]འདི་ནས[་མ](མར་)[དུག་](འདུག་སེ་)ཕྱིན་པ་ཡིན་ན། གང་ལྟར།)[སྟར།]
2.  09:02  འཛམ་(བུ་)གླིང་འདིའི[་གང](་སྒང་)གི་ཤེས་བྱ་ཡོངས་སུ་རྫོགས་པ་[འདི](་དེ།)རྟེན་འབྲེལ་ཟེར་[ཡ]་(ཡག་)གི འེ་ག་རེ་ཟེར་བ་རེད། མིང་ཚིག་[དེའི་](འདིའི་ནང་ནས་
3.  09:08 བསྡུས་ཡོང་གི་འདུག་ག  [བདེས་དུས་་་དེ་གའི་དེ་ཤེས་དགོས་(ཀྱི་)[ཀྱིས་]ཡོད་རེད་བ། (ག་རེ་ཟེར་རེད་ལབ་ན།)[ ཨ་གང་རེད་ལབ་ན།]ཁ་སང་སྐད་ཆ་བྱུང་བ་ནང་བཞིན་རེད། 
4.   09:14(ཁ་སང་རེད་བས། སྐད་ཆ་བྱུང་བ་ནང་བཞིན་རེད།)  འེ་གང་ལྟར་སངས་རྒྱས་པའི་ཆོས་ཟེར་ཡག་འདི། ཨེ་ནི་ཆོས་རབ་ཏུ་རྣམ་འབྱེད་ཀྱི་ཤེས་རབ་
5.  09:21 ཕ་གིའི་ག་རེ་ཟེར་བ་རེད། འེ་ཆ་ཐམས་ཅད་ནས་[ཐ་]ད་དཔྱིས་ཕྱིན་པ[་ཞིག་]བེད་སྤྱོད་བྱས་ནས། 
6.  09:29 དེ་ལ་བརྟེན་ནས་ནང་སེམས་རྒྱུད་འདུལ་ཐབས་བྱེད་ཡ་གཅིག་ཡིན་པ་རེད། སེ་དེ་འདྲས་ཡིན་དུས་[ཙང་](ཙ་)ནས།( དཔེར་ན།)རྗེ་བཙུན་བྱམས་པ་མགོན་པོ་ད་ལྟ་འདིའི་
7.  09:38 རྒྱུད་བླ་མའི་ནང་གསུངས་བ་ནང་བཞིན་[བྱེས]་(བྱས་)ནས། རིག་པའི་གནས་ལྔ་དག་ལ་མཁས་པར་མ་བྱས་ན་གསུངས་(པ་)[བ་]ནང་བཞིན་[མ་](བྱས་ནས།)[བྱེས་ནས་]རིག་པའི་གནས་ལྔ་ཚང་མ་ལོག་ལ་ཤེས་དགོས་རེད་ཟེར་ཡག་ཅིག་གསུང་གི་འདུག་ག  [ལོགས་གི་ཤེས་དགོས་ཀྱིས་རེག་ཞེས་གསུངས་གི་འདུག་བ།]
8.  09:44 (དེའི་)རིག་པའི་གནས་ལྔ་ཟེར་ཡ་དེ། དེའི་ཚེ་དེའི་དུས་རྒྱ་གར་གྱི་[ཡི་ཐ](ད)་ཡོད་[བདེ་](བསྡད་)པའི་རིག་པའི་གནས་ལྔ་[དེས་](དེ་)བཤད་ཀྱི་ཡོད་རེད། [ཐ་](ད་དེའི་)[འདི་]རིག་པའི་གནས་ལྔའི་ནང་གི་བཟོ་ཡི[འི་]རིག་པ་
9.  09:52 (མར་འདུག་སེ་གཏོད། བཀྲལ་ནས་ག་རེ་ཟེར་བ་རེད། རྒྱ་བསྐྱེད་ནས་) [་ལྟས་བསྐྱེད་ནས་རྒྱ་བཀལ་ནས་]ཕྱིན་པ་ཡིན་ན། ད་དེང་སང་གི་[གྱི](ད་རིག་གནས་ཚང་མ་ལོག་དེའི་ནང་ལ་ཕལ་ཆེར་བསླེབ་ས་རེད་བ།)ལོགས་དེའི་ནང་ལ་ཕལ་ཕྱིར་སླེབས་ཚ་བ་ར་།
10.  09:58 [ཐ་དེས་]སེ་དེ་འདྲས་་ཡིན་པ་ཡིན་དུས། ད་འེ་འེ་སངས་རྒྱས་པའི་ཆོས་ཡག་པོ་གཅིག་ཤེས་པ་ལ་ཡ། 
11,  10:06 ཆོས་རབ་ཏུ་རྣམ་འབྱེད་ཀྱི་ཤེས་རབ་ཀྱིས་ད་གང་ལྟར། གང་ལྟར་གཅིག་ཕྱི་དང་ནང་གི་གནས་ཚུལ་ག་རེ་ཡིན་ནས། [ཐ་ཕྱི་ནང་གི་ཐ་གནས་ཚུལ་གང་ཡིན་ནས་]
12.  10:12ཁོ་ཕ་གིའི་འེ་གཅིག་ཤེས་དགོས་ཡག་ཅིག་དང་། [ཕལ་མཁས་ཤེས་དགོས་ཡ་ཅིག་དང།དེས་དེ་འདྲའི་ཀྱིས་] (དེ་འདྲ་ཡི་གནས་ཚུལ་གཞི་ལ་བཞག་པའི་ཐོག་ནས། 
13.  10:19 (ཨེ་ནི་ལྟ་བ་གོང་མ་གོང་མ་དེ་གའི་དེ།) [མོ་གོང་མོ་འདི་] (ཕར་ཟབ་ཏུ་ཟབ་ཏུ་བཏང་ནས་འགྲོ་བསྡད་ཡག་ཅིག་ད་ཆགས་ཀྱི་འདུག་ག )བདེ་ཡ་ཅིག་ཐ་ཆགས་ཀྱི་འདུག་བ།
14.  10:25 འེ་གཅིག་ལབབ་གདའ། འོ་ཡ། 
15.  10:32 [དེ་ན་དེས་རྗེས་སུ་] (དེས་ན་སེ་དེའི་གཞུག་ལ་དེ་གསུངས་བཞག ལྟ་བའི་གོལ་ས་སྤང་པ་དང༌། བདག་མེད་ཕྲ་རགས་ཀྱི་རིམ་པ་ངེས་པར་བྱ་བའི་ཕྱིར། ཟེར་ད།) 
16.  10:40  ལྟ་བའི་གོལ་ས་སྤང་བ་དང་སེ་ལབ་དུས། ད་རྟག་པའི། ལྟ་བའི་གོལ་ས་སྤོང་ཡ་ལ།  ད་རང་སྡེ་ཙམ་དུ་མ་ཟད་པའི། ད་གཞན་སྡེ། [ བའི་ཐ་གཞན་སྡེ་]
17.  10:48 གཞན་སྡེ་ཡི་ད་གནའ་དུས་ཀྱི་གཞན་སྡེ། ད་ལྟའི་གཞན་སྡེ་དེ་ཚོ་ཚང་མ་ལོག་ད་ཤེས་ཐུབ་པ་ཡ་དེ། 
18.  10:54 ཤེས་པ་བྱུང་ན་ཕན་ཐོགས་ཆེན་པོ་ཡོད་བསྡད་པ་གཅིག་རེད་བཞག དེ་ནས་བདག་མེད་ཕྲ་རགས་ཀྱི་རིམ་པ་
19.  11:01 ངེས་པར་བྱ་བའི་ཕྱིར། བདག་མེད་ཕྲ་རགས་ཀྱི་ཁྱད་པར་དེ་གའི་དེ་ཤེས་པ་གཅིག་བྱུང་ན། བདག་མེད་ཕྲ་མོ་ཕྲ་མོའི་ཟབ་གནད་དང༌།
20.  11:08  ཁྱད་ཆོས་དེ་གའི་དེ་ཨེ་ནི་ཁོ་ཤེས་ཐུབ་ཀྱི་རེད། གཞན་བདག་མེད་ཕྲ་མོ་རེད་སེ་ལབ་པ་ཡིན་ནས། ཡིན་པ་དང་བསམ་བསྡད་ཡ་གཅིག་མ་གཏོགས་གཞན་པ་ག་གས་མི་འདུག་ག  [བདེ་ཡ་ཅིག་མ་སྟོག་གང་ཡང་མིན་འདུག་བ།]

2023-03-24 11:44 UTC, Tenzindharten requested changes
11:14 བེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་རང་སྡེ་བདག་མེད་འདོད་མཁན་གྱི་(ད་)གྲུབ་མཐའ་བཞི་པོའི་(དེ་སྐད། [འདའདི་ཀྱིས་་]ཨེ་ནི་བེ། 
11:22 དུས་འདོད་ཚུལ་དེ་གའི་དེ་[འདི་ཀྱི་འདི་]ཤེས་པ་ཡིན་ན། ཨེ་ནི་བདག་མེད་འདོད་མཁན་གཅིག་གྱུར་རེད་དེ། [སྟེ་]ཡིན་ནས།
11:28  བདག་མེད་ཀྱི་གོ་བ་ལེན་སྟངས་[བཏང]་ལ་ཡ། ཨེ་ནི་བེ་ཟབ་ལོད་[ལོས་]ཟེར་ན་མི་འདུག གང་ལྟར་གཅིག ཨེ་ཕ་གིའི་གཏིང་ཟབ་
11:35 (ལོད་འདྲ་བོ་གང་ལྟར་ད་གང་ལྟར་གཅིག རྣམ་དཔྱོད་རླིང་པོའི་ཐོག་ནས་ཕ་གིའི་གནས་ཚུལ་ཕེ་ཕྲ་ཞིང་ཕྲ་བའི་སྒང་ལ་ད་གཅིག་བསམ་བློ་གཏོང་སྟངས་)
11:44 ཀྱི་ཁྱད་པར་ཡོང་བསྡད་ཡག་གཅིག་འདུག་ག ( ད་དེ་གའི་དེ་)[འདི་འདི་]ཤེས་པར་བྱུང་ན་ཕན་ཐོགས་ཞེ་(དྲག་)[དྲགས་]ཡོད་རེད།
11:49 དེ་འདྲས་ཡིན་དུས། བདག་མེད་ཕྲ་རགས་ཀྱི་རིམ་པ་ངེས་པར་ངེས་པར་བྱ་བའི་ཕྱིར་རང་གཞན་གྱི་གྲུབ་མཐའི་རྣམ་གཞག 
11:55 ཨེ་ནི་ཤེས་དགོས་ཀྱིས་རེད།[ ཐ་འདི་འདྲ་]དེ་འདྲས་ཡིན་དུས་[ཙང]་ཙ་ནས། དགོས་པ་དེ་ཡི་སླད་དུ་[སྐུ་]དཀོན་མཆོག་འཇིགས་མེད་དབང་པོས། 
12:02 [ཨ་]ཨེ་ནི་གྲུབ་མཐའི། (ད་དཀོན་མཆོག ག་རེ་ཟེར་བ་ད།)  [འབྲས་ཐ་དེའི] དེ་ཡི་སླད་དུ་[ཐ་]ད་གཅིག་རྒྱལ་པོའི་རྒྱ་བོད་ཀྱིི་[ཕག་པོའི]འཕགས་བོད་ཀྱི་བླ་མ་མང་པོས། 
12:10 [ད་གྲུབ་མཐན་ཀྱིས་]ད་གྲུབ་མཐའི་རྣམ་གཞག་མཛད་ནས་ཡོད་བསྡད་པ་[དེས་]པ་ད་གང་ལྟར་[ཐར་]གཅིག  ལུགས་འདྲ་མི་འདྲ་ཚོའི་འདོད་པ་མར་བཀོད་ནས་ཡོད་བསྡད་པ། དེ་གའི་དེ་ཡི་ཚུར། 
12:17 དོན་བསྡུས་ནས་ད་སྐབས་སུ་བབས་པ་དཀོན་མཆོག་འཇིགས་མེད་དབང་པོ། རང་གིས་[ཀྱིས]་མདོར་བསྡུས་གཅིག་ད་གསུང་གི་ཡིན་གསུང་བ་ཡིན་པ་རེད། 
12:25 བེ་བརྗོད་པ་ལ་[ཅེས་པ་ལ་]གཉིས། སྤྱིར་བསྟན་པ་དང་བྱེ་བྲག་ཏུ་བཤད་པའོ།། དང་པོ་ནི། གྲུབ་མཐའ་ཞེས་པའི་ཐ་སྙད་རང་བཟོ་མ་ཡིན་ཏེ། 
12:30 ད་སངས་རྒྱས་ཀྱི་ལུང་ལས་གསུངས་པའི་ཕྱིར། ད་གནད་འགག་སེ་གལ་མི་འདུག [རེད་ཐ་གནད་དགག་གང་ཡང་མིན་འདུག་ཐ་འདི] ད་དེའི་དོན་དག་འདི་ཨེ་ནི། [ནི་ཨ་]
12:37 [ཐ ]ད་གང་ལྟར་[སྟར་]གྲུབ་མཐའ་ཟེར་དུས་[ཙང]་ཙ་ནས་གཅིག མ་བརྟགས་མ་དཔྱད་པ།  ཁོ་རང་ཉིན་རེ་ཉིན་རེའི་ཁ་ཐུག་ཁ་ཐུག་[ཚོར]འཚོ་བ་འདྲ་བོ་སྐྱེལ་གྱིན་འགྲོ་སྡོད་ཡག་དེ་འདྲ་གཅིག་མ་ཡིན་པ། [སྐལ་བྱེས་འགྲོ་བདེ་ཡ་དེ་འདྲ་མ་ཡིན་པར་]
12:46 གཅིག གཅིག་ཡིན་ལུགས། ག་རེ་ཟེར་བ་རེད་ད། [ད་གང་ཟེར་དགོས་རེད]གང་ལྟར་[སྟར]་ཕྱི་དང་ནང་གི་གནས་ཚུལ་ག་བ་ལ་ཡིན་ནས། ཁོ་གཅིག་བསམ་བློ་བཏང་ནས། 
12:54 ཐ་]ད་ཕལ་ཆེར་འདི་རེད། གཅིག་ཁ་ཐུག་ཁ་ཐུག་ལ་ག་རེ་ཐུག་བཞག་པ་ཁོ་རང་། ད་ཁོ་བེ་ཉི་མ་ཚ་བོ་འདྲ་བྱུང་ན་ཉི་མ་དེར་ག་བསྡད། འཁྱགས་པའིཁ་ཐུག་ལ་ཁོ་མ་དེར་བསྡད།
13:00 ཨེ་ནི། བེ་བེ་ག་རེ་ཟེར་བ་གཅིག། དྲོ་བོ་བྱུང་བའི་ཁ་ཐུག་ལ་ཡ། དཔེར་ན། ག་རེ་ཟེར་བ་རེད། བསིལ་བསིལ་གཅིག་ལ་བསྡད། འདུག་སེ་བྱེད་སྟངས་དེ་དུད་འགྲོ་ཚོས་བྱེད་ཀྱི་རེད་བ་ད། 
༢༠༢༣། ༠༣། ༢༤ ཕྱི་དྲོར་བཅོས། དེའི་འཕྲོས་རྗེས་སུ་བསྐུར་ཆོག

2023-03-25 12:12 UTC, Tenzindharten requested changes
1. 13:08བེ་ད་ཡིན་ནས་ཉི་མ་ཟེར་ཡ་དེ། [འདི]དེ[་གང་]འདྲ་ག་འདྲས་སེ་ཡོང་གི་ཡོད་རེད། ཉི་མ་[འདི་]དེའི་དྲོད་དེ་[གང་འདྲ་]ག་འདྲས་སེ་ཡོང་གི་ཡོད་རེད།
2. 13:15  [ཨ་] ཨེ་ནི་ཉི་མ་འདི་ལོ་ག་ཚོད་སེ་ཕྱིན་ཡོད་རེད། ཧེ་ཧེ། མ་འོངས་པ་ལ་ཉི་མ་[འདི]་དེ་ག་འདྲས་སེ་འགྲོ་ཡི་རེད་ཟེར་ཡ་བཟོ་འདྲ་བོ་འདུག་ག
3.13:22 [ཐ་]ད་[འདི་]དེའི་དུད་འགྲོ་ཚོས་བསམ་བློ་གཏོང་གི་མ་རེད་བ། [ཐ་](ད་ང་ཚོ་མི་དེ་ཚོས་བསམ་བློ་གཏོང་གིན་ཡོད་རེད་བ་ད། ད་དེ་ག་འདྲས་ག་འདྲས་སེ་བྱུང་བ་རེད།) [མིའི་འདི་ཡི་བསམ་བློ་གཏོང་གྱི་ཡོད་རེད་བ་ཐ། ཐ་འདི་གང་འདྲ་སེ་བྱུང་པ་རེད་སེ་]
4.13:26 [ཐ འདེ་འདི་] ད་དེ་ཡར་ཡར་དེད་ཕྱིན་ན། ཨེ་ནི་ཉི་མ་དེ་རུ་ཚད་ཅིག་ཡོད་རེད། [དེས་ལའང་ཚད་གཅིག་ཡོད་རེད་།]
5.13:32  [ཉི་མའི་འདི་] ཉི་དེའི་ཚད་གཅིག་ལོ་འཐེར་འབུམ་ཆུང་བ་ཕལ་ཆེར་ད་འཐེར་འབུམ་ཆུང་བ་ག་རོ་གཅིག་ཡོད་རེད། ད་འཐེར་འབུམ་ཆུང་བ་ལྔ་དྲུག་བདུན་བརྒྱད་ཨེ་འདྲས་བཤད་ཀྱི་མིན་འགྲོ། [མ་ལྟོག་ཆགས་ཀྱི་མི་འགྲོ།]
6.13:39 གང་ལྟར་འཛམ་(བུ་)གླིང་འདི་ཆགས་ནས ཐ་] ད་འཐེར་འབུམ་ག་ཚོད་རེད་གོ ཁོ་[ཐ་]ད་འཐེར་འབུམ་ཆུང་བ་ལྔ[་བཤེས་]བཤད་ཀྱི་ཡོད་རེད༌།
7.13:46  བྱིས་]བྱས་ཙང་ད་ཉི་མ་དེ་ལས། ད་ལྟ་ངས་ད་ལྟ་ཡག་པོ་དྲན་གྱི་མི་འདུག [བྱེས་] བྱས་ནས་འོ་ད་གང་ལྟར་ཉི་མ[་འགོ་]མགོ་འཚོས་[ཚུགས་]ཡ་གཅིག་ཡོད་རེད།
8.  13:54 ཐ་] ད་ད་དུང་ཡ་དྲི་བ་དྲིས་ནས་ག་རེ་བྱས་ནས་ཉི་མ་ཟེར་ཡ་དེ་བྱུང་བ་རེད། འདུག་བ། ཐ་] ད་བསམ་མནོ་[གཏོང་བསམ་མནོ[་བློ]་གཏོང་། འདི་གའི་འདི། 
9. 14:02 ད་སོ་སོས་[སོའི་]ཚོད་དཔག་བྱེད་ཀྱིས་འདུག་སེ་བསམ་བློ་གཏོང་། གཅིག་མིག་མཐོང་ལག་ཟིན་གྱིས་གནས་ཚུལ་དེ་གའི་དེ་གཞི་ལ་བཞག [འདི་འདི་གཞི་ལ་བཞག་།]
10. 14:10ཐ་] [་འདི་] ད་དེ་ཕལ་ཆེར་་[འདིའི་དབར་དབྱིན་སྐད་དེ་བཅུག་དགོས་]་བློ་ལྷན་རྒྱས་ཀྱི་ད། [ཉིས་ཀྱིས་བརྟག།] མ་བརྟག་མ་དཔྱད་པའི་བློ་ལྷན་རྒྱས་ཀྱིས་གཅིག་མཐོང་བསྡད་ཡག ཨེ་ནི་གཅིག [ ཉིས་ཀྱིས་ཅིག་ཀྱི་ཐ་མཐོང་བདེ་ཡ་ཨ་ནི་ཅིག་།]
11.  14:19  (ཉམས་སུ་མྱོང་བསྡད་ཡ།) [བདེ་ཡ་། ]གཅིག་བདེ་སྡུག་གི་གཅིག ད་ཚོར་བ་ཡོང་བསྡད་ཡ་དེ་གའི་དེ། [འདི་ནས་དབྱིན་སྐད་གསུང་པ་དེ་འབྲི་དགོས།] [འདི་འདི་ཨ་]སྤྱིར་བཏང་གི་ཤེས་བྱ་བྱེད།
12.  14:26 དཔེར་ན། ང་ཚོས་རྗེས་དཔག་ལོང་བར་གྱུར་བ། [བརྒྱུད་པའི་]མཐར་དངོས་སུམ་དུ་[ལ་]གཏུག་དགོས་ཟེར་ཡ་དེ་ཕལ་ཆེར་[འདི་ནས་ཀྱང་དབྱིན་སྐད་དེ་བཞིན་རང་འཇགས་འབྲི་དགོས།] [སྤྱི་བཏང་གི་ཤེས་བྱར་གཏུག་དགོས་ཡ་]ཕལ་ཆེར་རེད།
13. 14:32 སྒྲུབ་བྱེད་བཀོད་བཀོད་ནས་བཀོད་པའི་མཐའ་མར་འདྲ་བོ་དེ། ང་རང་ཚོ་[ འདི་ནས་དབྱིན་སྐད་དེ་འབྲི་དགོས་][སྤྱིར་བཏང་གི་ཤེས་བྱའི་གང་ལ་དེས་]དེ་འདྲས་སེ་འདུག་ག [ཐ་འདི་]ད་དེ་སུས་བལྟས་ནས། 
14. 14:39 ཁོ་བསྙོན་དུ་མེད་བསྡད་བ། གཅིག་ཡོད་བསྡད་བ། [བདེ་བ་ཅིག་ཡོད་བདེ་བ་ཐ་] ད་འདི་ལ་སྔོན་ལ་ག་རེ་ཟེར་བ་རེད། བདེན་པའི་གནས་ལུགས་དེ་འདྲས་གཅིག་ལ་ཆ་བཞག་དགོས་རེད་བ།  
15. 14:46 འོ་དེ་ལ་ཆ་བཞག་ནས་ད། གཞི་[དེས་]དེ་ལ་གཏུག་པའི་ཐོག་ནས། ཨེ་ནི་རྣམ་གཞག་མང་པོ་གཅིག ད་སོ་སོས་ཚོད་དཔག་བྱས་ནས་བཤད་བསྡད་ཡ་འདྲ་བོ། [བདེ་ཡ་ཅིག།།]
16.  14:55[དེས་འདྲ་ཡི་]དེ་འདྲས་སྒོ་ནས་ད་སོ་སོས་[སོའི་]ཚོད་དཔག་བྱས་ནས།  ད་འདི་ག་སེ་གཅིག་ཡིན་དགོས་ཀྱི་རེད་བྱས་ནས། [ཚོད་ཅིག་ཡིན་དགོས་ཀྱི་རེད་བྱེས་ནས་ཅིག་]གཅིག་སོ་སོའི་བསམ་བློའི་ནང་ལ་ཡ། 
17.  15:02 ཕལ་ཁའི་] ཕ་གིའི་ག་རེ་ཟེར་བ་རེད། [དགོས་རེད།] གྲུབ་པའམ་གཅིག་གྲུབ་ཚད་འདྲ་བོ་ཅིག་བཞག དེ་བསམ་བྱུང་ཟེར་ཡ་མིན་པ་བྱས། ཧེ།  བསམ་བྱུང་ཟེར་ལབ་ན།
18.  15:11 ཧེ་ཧེ། སྣང་བ་སྐྱིད་པོའི་སྐད་ཆ་འདྲ་རེད། བསམ་བྱུང་མིན་པ་བྱས། དཔྱད་པ་བྱས་ནས་དཔྱད་པ་འདྲ་བོ་རྒྱུ་མཚན་ག་རོ་བསམ་བློ་བཏང་ནས། 
19.  15:18 ཨེ་ཨེ།  དོན་[འབད་]རྦད་དེ་ར་འཕྲོད་པ་འདྲ་བོ་ད་ཡིན་ནས་མི་ནས། གང་ཡིན་པ་མེད་ནས་[སྔས་]སྔོན་ལ་ག་རོ་གཅིག་བསམ་བློ་བཏང་། འདི་འདྲས་གཅིག་ཐོག་ནས། ཨོ་ད་འདི་འདྲས་གཅིག་རེད་བཞག    [ནས་འོ་ཐ་འདི་འདྲ་ཞིག་རེད་ཤ་སེ་
20.  15:25 [ངེས་བྱེས་ན་] ངས་བྱས་ན། ཁོ་དྲང་པོ་རེ་བྱེད་དགོ་བྱུང་ན། དྲང་པོ་རེ་བྱས་ན།  [ཐ་སྔས་]ད་སྔོན་ལ་སྤྱིར་བཏང་གང་ཡིན། དོན་ངོ་མ་གང་ཡིན་ནས་མེད་ནས། ང་རང་བསམ་ཚོད་ལ་འདི་འདྲས་ཤིག་འདུག་བྱས། [ཞིག་འདུག་བྱེས་ནས་
21. 15:32 [ཐ་ཅིག་] ད་གཅིག་ཁོ་རང་མཚམས་འདྲ་བོ་གཅིག་བཞག་ཡོང་དུས། དེ་ལ་ཡ་གྲུབ་པའི་གྲུབ་ཚད་འདྲ་བོ་གཅིག  [སོ་སོའི་]སོ་སོས་དཔྱད་པ་བྱས་ནས། 
22. 15:39 ཁོ་གཅིག  ག་རེ་ཟེར་བ་རེད། [དགོས་ར་ཅིག་ཚད་འདྲ་པོ་ཅིག་]ཚད་འདྲ་བོ་བཞག་ཡོང་གི་ཡོད་རེད་བ། འོ་ད་དེ་འདྲས་འདྲ་བོ་དེ་ལ་གྲུབ་མཐའ་སེ་ལབ། 

༢༠༢༣། ༠༣།༢༥ སྡེ་ཚན་འདི་ཚར།

2023-03-26 05:50 UTC, Tenzindharten requested changes
༡།.  00:00 ཡ་ད{་ཨ་}སངས་རྒྱས་པའི་ད་ཆོས་སྤྱི་དང༌། ལྷག་པར་ཨེ་ནི་ཐེག་པ་ཆེན་པོ། 
༢།.  00:08 དཔལ་ནཱ་ལེན[་འདྲ་]ཏྲ་ནས་ད་བརྒྱུད་པའི་ད་ཆོས་བརྒྱུད་འཛིན་མཁན་[འེས]་འེ་ཁྱེད་རང་ཚོ་ཀོ་རི་ཡ། 
༣།.  00:16ཀོ་རི་ཡའི་ཆོས་གྲོགས་ཚོ་ཡིན་ནས་འདྲ། ང་ཚོ་བོད་པ་ཚོ་ཡིན་ནས་འདྲ། འེ་གང་ལྟར་འེ་ཆོས་བརྒྱུད་[འདིའི་]དེའི་ཐོག་ནས། 
༤།.  00:24 ད་ང་ཚོ་ནམ་རྒྱུན་སྨོན་ལམ་(རྒྱག་བསྡད་ཡག་)[དད་ཡས་འདི]་དེ་ག་རེད་ཟེར་ལབ་ན། སེམས་ཅན་ཐམས་ཅད་ལ་བདེ་བ་
༥།.  00:28 ཐོབ་པ་གཅིག་ཡོང་བར་ཤོག སྡུག་བསྔལ་མཐའ་དག་བྲལ་བར་ཤོག་ཟེར་ཡག[་ཡས་]གཅིག་དང། དེའི་ཆེད་དུ་ཨེ་ནི་རང་ཉིད་
༦།.  00:35 ཀྱིས་རྣམ་མཁྱེན་རྒྱལ་བའི་གོ་འཕང་ཐོབ་པར་ཤོག་བྱས་ནས། སྨོན་ལམ་[རྒྱབས་]རྒྱག་སྡོད་[བསྡད་]ཀྱི་ཡོད་རེད། དེ་ལྟ་བའི་སངས་རྒྱས་ཀྱི་གོ་འཕང་ཐོབ་ཡག་[ཡས་]ཟེར་མཁན་དེ། [འདི]
༧།.  00:42 [ཨ ]ཨེ་ནི་ཤེས་རབ་སྙིང་པོའི་ནང་ལ་ཡ། ཨེ་ནི་འེ་ཇི་སྐད་གསུངས་པ་ནང་བཞིན་ཀྱིས། ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཟེར་ཡག་དེ། 
༨།   00:50 འེ་ཉམས་ཞིབ་གནང་ནས། ཨེ་ནི། དེ་ལ་བརྟེན་ནས་ད་སངས་རྒྱས་དགོས་ཡག་གཅིག་ཡིན་པ་རེད།
༩།.  00:58 འེ་དེ་ཡང་ཨེ་ནི་འདས་པའི་སངས་རྒྱས་རྣམས་ཀྱང༌། ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཉམས་[བཞེས་]ཞིབ་གནང་ནས་སངས་རྒྱས་པ་རེད། [འེས་] འེ་ད་ལྟ་སངས་རྒྱས་བཞིན་པ་ཚོས། 
༡༠།.   01:06 [ཤེས་རབ་ཀྱི]ཆོས་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལམ་ཉམས་[བཞེས་]ཞིབ་གནང་ནས་ད་སངས་རྒྱས་བཞིན་པ་ཡིན་པ་རེད།
 ༡༡།.  01:12 ང་རང་ཚོ་སངས་རྒྱས་ཀྱི་གོ་འཕང་ཐོབ་པར་ཤོག་ཟེར་ནས། སྨོན་ལམ་[རྒྱབ་]རྒྱག་མཁན་ཚོ་ཡིས། མ་འོངས་པ་ལ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལམ་འདི་མཁོ་ན་ལ་བརྟེན་ནས། ཨེ་ནི་སངས་རྒྱས། སངས་རྒྱས་དགོས་ཡག་ཅིག་ཡིན་པ་རེད།
༡༢།.   01:22 འོ་ན་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་གང་འདྲས་སེ་རེད་ལབ་ན། འེ་སྤྱིར་ནས་ཨེ་ནི་འེ་སྟོད་ཉིད་རྟོགས་པའི་ཤེས་རབ། 
༡༣།. 01:29 ད་ལྟ་སྟོང་པ་ཉིད་བརྟེན་བྱུང་གི་དེ་ཁོ་ན་ཡིན་ཟེར་བསྡད་ཡག་གི[་ཀྱི་]ད་སྟོད་ཉིད་ཕྲ་མོ་འེ་རྟོགས་པའི་ཤེས་རབ་ཅིག 
༡༤།.  01:36 དེའི་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་འེ་འེ་ཙམ་མ་ཡིན་པ། ད་གང་ལྟར་ཟིན་བྱེད་ཀྱི་ཐབས་[རྦད་]བྱང་ཆུབ་ཀྱི་སེམས་དང༌།
༡༥།. 01:46  དེས་ཀུན་ནས་བསླངས་པའི་སྦྱིན་སོགས་ཀྱི་ཐབས་ཀྱི་ཨེ་ནི་ཕྱོགས་དེ་གའི་དེ་[འདི]་གྲོགས་དང་བཅས་པ། དེ་འདྲས་དེ་ལ་ནམ་རྒྱུན་ད་ལྟ།
༡༦།  01:55 རྣམ་ཀུན་མཆོག་ལྡན་གྱི་སྟོང་པ་ཉིད་ཟེར་གྱི་ཡོད་རེད། རྣམ་པ་ཀུན་གྱི་མཆོག་དང་ལྡན་པའི་སྟོང་པ་ཉིད་ཟེར་ཡག་འེ། 
༡༧།  02:00 མདོར་ན་[ཨ་]ཨེ་ནི་དེ་འདྲས་ལྟ་བུའི་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་[འདི]་དེ། རྣམ་མཁྱེན་སྒྲུབ་ཟེར་ཡག་ཅིག་[ཡས་ཅིག་]ཆགས་ཀྱི་ཡོད་རེད། 
༡༨།. 02:05 དེ་འདྲས་ཡིན་དུས་རྣམ་མཁྱེན་ཐོབ་པའི་ཐབས་དཔེ་མ་ཚང་བ་མེད་པ་གཅིག་ཆགས་ཡོང་བ་ཡིན་དུས་ཙ་ནས། 

༢༠༢༣།༠༣།༢༦ ཞོགས་པ་ཕྱེད་ཀ་གཅིག་ཚར།

2023-03-26 06:37 UTC, Tenzindharten requested changes
༡།.  00:00 ཡ་ད{་ཨ་}སངས་རྒྱས་པའི་ད་ཆོས་སྤྱི་དང༌། ལྷག་པར་ཨེ་ནི་ཐེག་པ་ཆེན་པོ། 
༢།.  00:08 དཔལ་ནཱ་ལེན[་འདྲ་]ཏྲ་ནས་ད་བརྒྱུད་པའི་ད་ཆོས་བརྒྱུད་འཛིན་མཁན་[འེས]་འེ་ཁྱེད་རང་ཚོ་ཀོ་རི་ཡ། 
༣།.  00:16ཀོ་རི་ཡའི་ཆོས་གྲོགས་ཚོ་ཡིན་ནས་འདྲ། ང་ཚོ་བོད་པ་ཚོ་ཡིན་ནས་འདྲ། འེ་གང་ལྟར་འེ་ཆོས་བརྒྱུད་[འདིའི་]དེའི་ཐོག་ནས། 
༤།.  00:24 ད་ང་ཚོ་ནམ་རྒྱུན་སྨོན་ལམ་(རྒྱག་བསྡད་ཡག་)[དད་ཡས་འདི]་དེ་ག་རེད་ཟེར་ལབ་ན། སེམས་ཅན་ཐམས་ཅད་ལ་བདེ་བ་
༥།.  00:28 ཐོབ་པ་གཅིག་ཡོང་བར་ཤོག སྡུག་བསྔལ་མཐའ་དག་བྲལ་བར་ཤོག་ཟེར་ཡག[་ཡས་]གཅིག་དང། དེའི་ཆེད་དུ་ཨེ་ནི་རང་ཉིད་
༦།.  00:35 ཀྱིས་རྣམ་མཁྱེན་རྒྱལ་བའི་གོ་འཕང་ཐོབ་པར་ཤོག་བྱས་ནས། སྨོན་ལམ་[རྒྱབས་]རྒྱག་སྡོད་[བསྡད་]ཀྱི་ཡོད་རེད། དེ་ལྟ་བའི་སངས་རྒྱས་ཀྱི་གོ་འཕང་ཐོབ་ཡག་[ཡས་]ཟེར་མཁན་དེ། [འདི]
༧།.  00:42 [ཨ ]ཨེ་ནི་ཤེས་རབ་སྙིང་པོའི་ནང་ལ་ཡ། ཨེ་ནི་འེ་ཇི་སྐད་གསུངས་པ་ནང་བཞིན་ཀྱིས། ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཟེར་ཡག་དེ། 
༨།   00:50 འེ་ཉམས་ཞིབ་གནང་ནས། ཨེ་ནི། དེ་ལ་བརྟེན་ནས་ད་སངས་རྒྱས་དགོས་ཡག་གཅིག་ཡིན་པ་རེད།
༩།.  00:58 འེ་དེ་ཡང་ཨེ་ནི་འདས་པའི་སངས་རྒྱས་རྣམས་ཀྱང༌། ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཉམས་[བཞེས་]ཞིབ་གནང་ནས་སངས་རྒྱས་པ་རེད། [འེས་] འེ་ད་ལྟ་སངས་རྒྱས་བཞིན་པ་ཚོས། 
༡༠།.   01:06 [ཤེས་རབ་ཀྱི]ཆོས་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལམ་ཉམས་[བཞེས་]ཞིབ་གནང་ནས་ད་སངས་རྒྱས་བཞིན་པ་ཡིན་པ་རེད།
 ༡༡།.  01:12 ང་རང་ཚོ་སངས་རྒྱས་ཀྱི་གོ་འཕང་ཐོབ་པར་ཤོག་ཟེར་ནས། སྨོན་ལམ་[རྒྱབ་]རྒྱག་མཁན་ཚོ་ཡིས། མ་འོངས་པ་ལ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལམ་འདི་མཁོ་ན་ལ་བརྟེན་ནས། ཨེ་ནི་སངས་རྒྱས། སངས་རྒྱས་དགོས་ཡག་ཅིག་ཡིན་པ་རེད།
༡༢།.   01:22 འོ་ན་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་གང་འདྲས་སེ་རེད་ལབ་ན། འེ་སྤྱིར་ནས་ཨེ་ནི་འེ་སྟོད་ཉིད་རྟོགས་པའི་ཤེས་རབ། 
༡༣།. 01:29 ད་ལྟ་སྟོང་པ་ཉིད་བརྟེན་བྱུང་གི་དེ་ཁོ་ན་ཡིན་ཟེར་བསྡད་ཡག་གི[་ཀྱི་]ད་སྟོད་ཉིད་ཕྲ་མོ་འེ་རྟོགས་པའི་ཤེས་རབ་ཅིག 
༡༤།.  01:36 དེའི་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་འེ་འེ་ཙམ་མ་ཡིན་པ། ད་གང་ལྟར་ཟིན་བྱེད་ཀྱི་ཐབས་[རྦད་]བྱང་ཆུབ་ཀྱི་སེམས་དང༌།
༡༥།. 01:46  དེས་ཀུན་ནས་བསླངས་པའི་སྦྱིན་སོགས་ཀྱི་ཐབས་ཀྱི་ཨེ་ནི་ཕྱོགས་དེ་གའི་དེ་[འདི]་གྲོགས་དང་བཅས་པ། དེ་འདྲས་དེ་ལ་ནམ་རྒྱུན་ད་ལྟ།
༡༦།  01:55 རྣམ་ཀུན་མཆོག་ལྡན་གྱི་སྟོང་པ་ཉིད་ཟེར་གྱི་ཡོད་རེད། རྣམ་པ་ཀུན་གྱི་མཆོག་དང་ལྡན་པའི་སྟོང་པ་ཉིད་ཟེར་ཡག་འེ། 
༡༧།  02:00 མདོར་ན་[ཨ་]ཨེ་ནི་དེ་འདྲས་ལྟ་བུའི་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་[འདི]་དེ། རྣམ་མཁྱེན་སྒྲུབ་ཟེར་ཡག་ཅིག་[ཡས་ཅིག་]ཆགས་ཀྱི་ཡོད་རེད། 
༡༨།. 02:05 དེ་འདྲས་ཡིན་དུས་རྣམ་མཁྱེན་ཐོབ་པའི་ཐབས་དཔེ་མ་ཚང་བ་མེད་པ་གཅིག་ཆགས་ཡོང་བ་ཡིན་དུས་ཙ་ནས། 


02:10 རྣམ་པ་ཀུན་གྱི་མཆོག་དང་ལྡན་པའི་ཨེ་ནི་སྟོང་ཉིད་ཟེར་བྱས་ནས། རྣམ་ཀུན་མཆོག་ལྡན་གྱི་[འབྲས་གྱིས་]སྟོང་པ་ཉིད་ཟེར་བསྡད་ཡག འོ་ད་འདི་འདྲས་དེ། 
02:17 ད[་གང་]ག་རེ་ཟེར་རེད། [དགོས་རེད་] ད་དེ་འདྲས་གཅིག་ལ་ཟེར་གྱི་ཡོད་རེད། ད་ལྟ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཟེར་བསྡད་ཡག་དེ། [་འདི་འོམ།]
02:22 དེ་ལྟར་ད་འེ་རྣམ་པ་ཀུན་གྱི་མཆོག་དང་ལྡན་པའམ། འེ་རྣམ་ཀུན་མཆོག་ལྡན་གྱི་ད་སྟོང་པ་ཉིད་དམ། 
02:30 ད་ཨེ་ནི་ཕ་གིའི་[ཕར་གིས]་བྱང་ཆུབ་ཀྱི་སེམས་ཀྱིས་ཟིན་པའི།
02:37 ད་སྦྱིན་སོགས་ཀྱི་གྲོགས་དང་བཅས་པའི་ད་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་ཁྱད་པར་ཅན། ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་དེ་འདྲས་ཅིག 
02:44 ད་ང་རང་ཚོའི་བརྒྱུད་ལ་སྐྱེ་བ་ལ་ཡ། སྨོན་ལམ་བརྒྱབས་ནས་རྒྱུད་ལ་སྐྱེ་ཡག་མེད་པ་རེད།
02:49  འེ་ཡང[་འདི་]དེ་ག་ནང་བཞིན་གྱི་[ཕར་གིས་]ཕ་གིའི་ད་འེ་དད་པ་བྱས་ནས།
02:54 ཨེ་ནི་སངས་རྒྱས་འེ་སྲས་དང་བཅས་པ་རྣམས་ཀྱི་བྱིན་རླབས་ཀྱི་ཐོག་ནས། ང་ཚོའི་རྒྱུད་ལ་སྐྱེ་ཡག་ཡོད་མ་རེད། [་ཡས་ཡོད་མ་རེད།] 
03:00 རང་རང་སོ་སོས་དམིགས་རྣམ་བསྐྱངས་ནས། ད་དེ་འདྲ་འདྲ་བོའི[དང་འབྲས་པའི]་ཨ་ནི་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཕྱིན་པ་ཟེར་ཡག་དེ་རྒྱུད་ལ་སྐྱེས་དགོས་ཀྱི་ཡོད་རེད།
03:08 དེ་སྐྱེ་ཡག་དེ། འེ་ཁོ་དེ་གའི་དེ་དུས་གཅིག་ལ་སྐྱེ་ཡག་མེད་པ་རེད། [་ཡས་མེད་པ་རེད།]
03:14 འེ་དཔེར་ན། ཕྱིའི་ཨེ་ནི་འེ་དཔེར་ན་མེ་ཏོག་འདྲ་བོ་ཡིན་ནས་རེད། ཤིང་འབྲས་འདྲ་པོ་ཞིག ཤིང་འབྲས་fruitཡིན་ནས་རེད།
03:23 ཁོ་ད་འེ་ལོ་མང་པོ་ཁོ་རིམ་པས་རིམ་པས་རིམ་པས་རིམ་པས་བྱས་ནས་སྔོན་ལ་ས་བོན་གཅིག་བཏབ། 
03:29 ས་བོན་ལས་ཁོ་སྐྱེ་རུང་གི་ནུས་པ་གཅིག་ཡོད་བསྡད་མཁན་གཅིག་བྱས། 
03:34འེ་དེ་འདྲའི་ས་བོན་དེ་ཨེ་ནི་རྐྱེན་མང་པོ་ཚོགས་པའི་སྟེང་ནས། ཨེ་ནི་དུས་ཡུན་ག་ལེར་ག་ལེར་ལ་ཡ། 
03:41 དུས་ཡུན་བསྲིངས་ནས་ཡོང་དུས། ཨེ་ནི་འེ་ཐོག་མར་མྱུ་གུའི་གནས་སྐབས། དེ་ནས་ཡར་ག་ལེ་ག་ལེ་ལ་ཡར་འེ་དཔེར་ན་ཤིང་འབྲས་ཀྱི་སྡོང་པོ་འདྲ་པོ་ཡིན་ནས་འདྲ། 


༢༠༢༣།༠༣།༢༦

2023-03-27 03:52 UTC, Tenzindharten requested changes
༡. 03:49 [མི་] མེ་ཏོག་འདྲ་པོ་ཡིན་ནས། དང་པོ་གཞི་ནས་ཡར་འཚར། དེ་ནས་ཨེ་ནི་མེ་ཏོག དེ་ནས་འབྲས་བུ། 
༢. 03:54 ཁོ་དེ་གའི་དེ་[འདི་གས་འདི་]ཡོང་དགོས་ཀྱི་འདུག་བ། འོ་འདི་ནང་བཞིན་ང་རང་ཚོའི་ནང་སེམས་ཀྱི་ཨེ་ནི་ཡོན་ཏན་ཟེར་ཡག་དེ། དེ་དེ་བཞིན་བྱས་ནས་ཐོག་མར་གཞི་རྩའི་ས་བོན་ཅིག
༣. 04:03 ཨེ་ནི་དགོས་ཀྱི་ཡོད་རེད། ད་ས་བོན་དེ་མེད་ན་ཨེ་ནི་བྱེད་ཐབས་མེད་པ་རེད་(དེ།) [ཏེ།] ང་རང་ཚོའི་རྒྱུད་ལ་ཡ་ཨེ་ནི། 
༤. 04:10འེ་གསལ་རིག་ཟེར་ཡག་གི་ད་ད་ཡུལ་གསལ་ཡག་གི་[ཀྱིསའེས་] འེ་ནུས་པ་རང་ཆས་སུ་ཡོད་བསྡད་པའི་ཤེས་པ་ཟེར་ཡ་གཅིག་འདུག་ག
༥. 04:18  དེ་ཡིས་ཨེ་ནི་ཆོས་རྣམས་ཀྱི་ཡིན་ལུགས་ཤེས་པ་དང༌། མཐར་ཐུག་ཨེ་ནི།
༦་ 04:23 འེ་ཇི་ལྟ་ཇི་ཉིད་ཀྱི་ཆོས་ཀུན་ཤེས་ཐུབ་ཡག་ཅིག་གི་འེ་ཁོ་ནུས་པ་འདྲ་པོ་ཁོ། 
༧. 04:30 གང་ལྟར་གསལ་རིག་དེའི་སྒང་ནས་ཡོད་པ་རེད། ད་ཡུན་རིག་པ་ལ་ཁོ་སྒྲིབ་བྱེད་དང་བྲལ་སོང་ན། 
༨. 04:36 ཁོ་ཡུན་རིག་ཡག་གི་[ཡི་]ནུས་པ་གསར་དུ་བསྒྲུབ་མི་དགོས་པ་ཁོ་རང་ཆས་སུ་ཡོད་པ་ཡིན་པ་རེད།
༩. 04:40 དེ་ག་ནང་བཞིན་གྱི་ཕ་གིའི་ང་རང་ཚོ་བརྩེ་བའི་བསམ་པ་ཟེར་ཡ་དེ།[འདི།] སྲོག་ཆགས་གྲོག་འབུ་ཚུན་ཆད་ལོག་ལ་ཡ་གཅིག་བརྩེ་བའི་བསམ་པ་གཅིག་ཡོད་བསྡད་ཡོད་རེད།
༡༠. 04:49  ཆུང་ཆུང་ཞེ་བོ་གཅིག་རེད། རྒྱ་ཆུང་ཆུང་ཞེ་བོ་གཅིག་རེད་དེ། [་སྟེ]ཡིན་ནས་[དེས་]དེ་འདྲའི་འདྲ་བའི་ད་བརྩེ་བའི་བསམ་པ་ཟེར་མཁན་[ཡས]་ཁོ་ས་བོན་ང་རང་ཚོའི་རྒྱུད་ལ་ཡོད་ཡོད་པ་བྱས། 
༡༡. 04:57 [སོ་]དེ་[དེས]་འདྲས་ཡིན་པ་ཡིན་དུས། [ཡུལ]ཡུན་རིག་གི་[ཡས་ཀྱི་འེས་]ས་བོན་འདྲ་པོ་ནུས་པ་འདྲ་པོ་གཅིག་རང་ཆས་སུ་ཡོད་བསྡད་པ། 
༡༢. 05:04 ད་ག་ནང་བཞིན་གྱི་[ཀྱིའེས་]འེ་ཕལ་ཆེར་དེ་ལབ་ཆོག་གི་མིན་འགྲོ། ངའོ་སྙམ་པའི་བློ་གཅིག་ཡོད་ཕྱིན་ཆད་ལ་ཡ།
༡༣.  05:09 བརྩེ་བ་ཟེར་ཡ་གཅིག་འདིའི་སྒང་དེར་ཕལ་ཆེར་ཡོད་རེད། སེ་[དེས]དེ་འདྲས་ཡིན་དུས་ས་བོན་ཡོད་ཡོད་པ་བྱས།
༡༤. 05:15  ད་ག་རེ་བྱེད་དགོས་རེད་ཟེར་ལབ་ན། འེ་གཅིག་ཡུན་རིག་ཡག་གི་ནུས་པ་རང་ཆས་སུ་ཡོད་བསྡད་པ་དེའི་སྟེང་ལ་ཡ།
༡༥.  05:22  ད་ཡུན་གྱི་གནས་ལུགས་ག་འདྲའི་ཡིན་པ་དེ། ཨེ་ནི་ཕར་ཤེས་པར་བྱས་ནས། འོ་དེ་གའི་དེ་ཞིབ་འཇུག་བྱེད། རྩད་གཅོད་བྱེད།
༡༦. 05:31  འེ་བསམ་བློ་བཏང་འདུག་སེ་བྱས་ནས། ཨེ་ནི་འེ་ཡུན་གྱི་ག་རེཟེར་བ་རེད། ཕ་གིའི་གནས་ལུགས་རིག་ཡག་གི་བློ་ཁོ། 
༡༧.  05:39 ཨེ་ནི་ཕར་འེ་རྒྱ་འདྲ་བོ་བསྐྱེད་ནས་ཁོ་ཕ་གིའི་ནུས་པ་འདྲ་པོ། ད་རིམ་པས་རིམ་པས་ཆེ་རུ་གཏོང་དགོས་ཡག་དེ་འདྲས་ཡིན༌པ་རེད། 
༡༨.  05:46 ད་ག་ནང་བཞིན་གྱི་སྙིང་རྗེ་བསམ་པ་གཅིག བརྩེ་བའི་བསམ་པ་ཟེར་ཡག་གི་ས་བོན་འདྲ་པོ་ཆུང་ཆུང་གཅིག་ཡོད་བསྡད་པ་དེ་ལ་ཡ། ཨེ་ནི་དེ་དང་དུ་བླངས། 

༢༠༢༣་༠༣་༢༧ ཞོགས་པ་བཅོས།

2023-03-27 06:28 UTC, Tenzindharten requested changes
༡. 05:53  དེ་ལ་ཡོན་ཏན་དུ་ལྟས་ནས། ཨེ་ནི་དེ་གོང་ནས་གོང་དུ་སྤེལ་ཡག 
༢. 05:57  དེའི་འགལ་ཟླ་ཡིན་བསྡད་མཁན་གྱི་ཞེ་སྡང་ལ་སོགས་པ། ཕྲག་དོག་ལ་སོགས་པ། 
༣. 06:03 དེ་ཚོའི་གྲས་དེ་ཇེ་ཉུང་ཇེ་ཉུང་། དེའི་་ཉེས་དམིགས་སུ་བལྟས་ནས་ཇེ་ཉུང་ཇེ་ཉུང་ལ་བཏང་ནས་འདུག་སེ་བྱས་ནས་གོམས་པ་བསྟེན་པ་ཡིན་ན། 
༤. 06:11 རིམ་པས་རིམ་པས་ཀྱི་ཨེ་ནི་ཁོ་བློ་འདི་འདུས་བྱས་སོགས་ལ་མི་གནས་པ་ཡིན་དུས་ཙ་ནས། ཁོ་རིམ་པས་རིམ་པས་ཀྱིས་འགྱུར་བ་ཐེབས་ཐུབ་ཡག་ཅིག  [ཡས་ཅིག།།]
༥. 06:18 ང་རང་ཚོ་དཔེར་ན་འེ་མཐོང་ཆོས་ལ་ཆ་བཞག་ནས། གཅིག་ཚེ་སྟོད་ཀྱི་བསམ་བློ་དེ་ཚེ་སྨད་ལ་མི་འདྲ་བ་གཅིག་ང་ཚོས་མཐོང་ཐུབ་[ཡས་]ཡག་འདུག་ག
༦. 06:25 [ཉིན]་ཉི་མ་གཅིག་གཉིས་ཀྱི་ནང་ལོག་ལ་ད་འགྱུར་བ་ཐེབས་ཡ་འེ་ཁག་པོ་ཞེ་དྲག་རེད། མཐོང་ཡ་[མིན་]མི་འདུག་སྟེ། [ཏེ] ཡིན་ནས་ལོ་དང་ཟླ་བ་མང་པོ་
༧. 06:34 ཕྱིན་པའི་སྐབས། རྗེས་ལ་ཡ་བློ་ལ་འགྱུར་བ་འགྲོ་ཡི་[ཀྱི་]ཡོད་བསྡད་པ་དེ་དངོས་སུ་ད་ཉམས་སུ་མྱོང་ཡག་[ཡས་]འདུག་ག 
༨. 06:40 སེ་དེ་འདྲས་ཡིན་དུས་[ཙམ]་ཙ་ནས། ད་[ཡར་གྱི་]ཡ་གིའི་འེ[་གང་ཟེར་]ག་རེ་ཟེར་བ་རེད། རྣམ་མཁྱེན་ཐོབ་ཡག་གི་[་ཀྱི་]ད་འོ་ཐབས་
༩. 06:48 མདོར་ན། དཔེ་རྣམ་ཀུན་མཆོག་ལྡན་གྱི་སྟོང་པ་ཉིད་ཟེར་ནས་ཟེར་ཡག་འདི་ཁོ་རིམ་པས་རིམ་པས།
༡༠. 06:54 གཞི་རྩ་གཅིག་ཡོད་པ་འདིའི་ཐོག་ནས་ཨེ་ནི་རིམ་པས་རིམ་པས་ཡར་གོམས་བྱས། 
༡༡. 06:59 ཨེ་ནི་གོམས་པ་རབ་ཀྱིས་མཐར་ཕྱིན་པའི་གནས་སྐབས་ལ་ཡ། ཨེ་ནི་རྣམ་མཁྱེན་ཟེར་ཡག་དེ་ཆགས་བ་ཡིན་པ་རེད།
༡༢. 07:04ད་དེ་ལྟ་བུའི་གཅིག་ལམ་ཉམས་སུ་ལེན་ཡག ཨེ་ནི།
༡༣. 07:09 ཁོ་[གང་]ག་རེ་ཟེར་བ་རེད། ཉམས་སུ་ལེན་པ་ལ་ཡ་ཉམས་སུ་ལེན་ལུགས་ཤེས་དགོས་པ་རེད།
༡༤. 07:13  དེ་འདྲའི་འདྲ་བའི་ད་ཉམས་ལེན་གྱིས་སྟོན་པའི་གཞུང་ད་མཆོག་ཏུ་གྱུར་པ་ཞི་བ་ལྷ་ཡི་ད་སྤྱོད་འཇུག་གི་གཞུང་འདི་མཆོག་དུ་གྱུར་པ་གཅིག་ཆགས་བསྡད་ཡོད་རེད།

༢༠༢༣་༠༣་༢༧ གོང་དེའི་ཕྱེད་ཀ་གཅིག

2023-03-27 10:46 UTC, Tenzindharten requested changes
༡  07:20  ད་ཡིས་འེ་བསམ་གཏན་གྱི་ལེའུ་ཡན་ཆད་དེ་གའི་དེ་གས་འེ་རྒྱ་ཆེ་བའི་ལམ་རིམ་གྱི་སྐོར་དེ་གསུང་། 
༢  07:27 ད་ཤེས་རབ་ལེའུ་འདི་ཡིས་ཟབ་མོའི་ལམ་གྱི་རིམ་པ་དེ་གསུང་གི་ཡོད་རེད།
༣  07:31  ད་དེའི་ཡན་ལག་ལ་ཡ་ཨེ་ནི་གྲུབ་མཐའ་མར་འཁྲིད་ཡག་གི་[ཡས་ཀྱི]ད་ཁ་སང་མཚམས་དེ་ཡིན་ད།
༤ 07:36 འེ་ཡ་འདི་ག་རེ་འདྲ་རེད་འདི། རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་[བའི་]བས་གཞལ་ན།
༥ 07:43 རྟག་[དཔྱད་](ཆད་)ཀྱི་མཐའ་གཉིས་ཀར་ལྟུང་ཡང་ཟེར་ཡག་འདི། འདི་[ཨ་]ཨེ་ནི་འེ་དཔེར་ན།
༦ 07:50  རང་རྒྱུད་པ་རྟག་མཐར་ལྷུང་བ་ད་གསལ་བ་བྱེད། རེད་བ།
༧ 07:56དཔེར་ན་རང་རྒྱུད་པ་ཕྱི་དོན་ཞལ་གྱིས་མི་བཞེད་པར་ཆ་བཞག་པ་ཡིན་ན། ཕལ་ཆེར་ཕྱི་དོན་ལ་སྐུར་བ་འདེབས་པའི་ཟོ་རེ་འདྲ་ཞིག་བཤད་པ་ཡིན་ན་བཤད་ཆོག་གི་[ཀྱི་]རེད་བ།
༨ 08:03 ཐ་] ད་ཕྱི་དོན་བཞེད་མཁན་གྱི་རང་རྒྱུད་པ་དེ་ཆད་ལྟ་ཡིན་པའི་སྒྲུབ་བྱེད་ག་རེ་བཤད་དགོས་རེད།
༩ 08:10 ཐ་སྙད། སྣང་ཕྱོགས། རྟེན་འབྱུང་ཕྲ་མོ། ད་འདི་ད་འདོད་ཀྱི་མ་རེད་བ། 
༡༠ 08:17 རྟེན་འབྱུང་ཕྲ་མོ་རྟེན་འབྱུང་ཕྲ་མོ་བཞག་ག་ཕྱིན་པ་ཡིན་ན། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་རྟེན་འབྱུང་བཞག་ག་ཕྱིན་པ་ཡིན་ན། ད་འདི་ཆད་ལྟར་ལྟ་ཡིས་རེད་བ།
༡༡ 08:24 རང་རྒྱུད་པས་རེད་བ།  [འདི་འདྲ་གཅིག་གང་ལ་བཤད་དགོས་རེད། ཤེས་བྱེད་གང་བཤད་དགོས་རེད། དེ་མིན་གང་ཞིག་བཤད་དགོས་རེད་ད།]དེའི་དབར་དེ་དག་གསུང་གསལ་བོ་མི་འདུག གཞན་དུ་འཚོལ་ཞིབ་གནང་ན་ལེགས། 
༡༢ 08:29འོ་རེད་བ། བྱས་ཙང་ག་ཁོས་ཆད་ལྟ་ལྷུང་བ་རེད་སེ། རེད་བས།
༡༣ 08:37  [འེས་] འེ་ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱིས་བཞེད་པའི་ཆ་ནས། མདངས་]རྟག་མཐར་ལྷུང་།
༡༤ 08:43 ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱིས་བཞེད་པ་ཡིན་དུས་ཙ་ནས། ཐ་སྙད་དུ་མིང་རྐྱང་བཏགས་ཡོད་ཙམ་འཇོག་མི་ཐུབ་པ་ཡིན་དུས་ཆད་མཐའ་[ཐབ་]ལྷུང་སེ། འདུག་སེ་རེད་བས།
༡༥ 08:48 འདི་འདྲས་བཞག་འདུག་པས། འེ། རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་བས་གཞལ་ན་རྟག་ཆད་
༡༦ 08:56 གཉིས་ཀྱི་མཐར་མཐའ་གཉིས་ཀར་བཏུང་ཡང་། ད་འདི་བྱས། ད་དེའི་གཤམ་དེ་འེ་དེ་ཡང་གྲུབ་མཐའ་སྨྲ་བ་བཞི་ལ་རྟག་[དཔྱད]ཆད་ཀྱི།
༡༧ 09:02 མཐའ་སྤོང་ཚུལ་མི་འདྲ་བ་རེ་ཡོད་དེ།[་དེས་ཟེར]། བྱེ་བྲག་སྨྲ་བ་རྣམས་འབྲས་བུ་སྐྱེ་བའི་ཚེ་རྒྱུ་འགག་པས་འེ་
༡༨ 09:09 རྟག་མཐའ་སྤོང་ལ། འེ་འེ་ད་འེ།
༡༩ 09:18 རྒྱུའི་མཇུག་ཐོགས་སུ་འབྲས་བུ་འབྱུང་བས་ཆད་པའི་མཐའ་སྤོང་ངོ་ཞེས་ཟེར་རོ།།

༢༠༢༣།༠༣།༢༧ ཕྱི་དྲོ།

2023-03-27 10:47 UTC, Tenzindharten commented
> ༡ 07:20 ད་ཡིས་འེ་བསམ་གཏན་གྱི་ལེའུ་ཡན་ཆད་དེ་གའི་དེ་གས་འེ་རྒྱ་ཆེ་བའི་ལམ་རིམ་གྱི་སྐོར་དེ་གསུང་། ༢ 07:27 ད་ཤེས་རབ་ལེའུ་འདི་ཡིས་ཟབ་མོའི་ལམ་གྱི་རིམ་པ་དེ་གསུང་གི་ཡོད་རེད། 
༣ 07:31 ད་དེའི་ཡན་ལག་ལ་ཡ་ཨེ་ནི་གྲུབ་མཐའ་མར་འཁྲིད་ཡག་གི་[ཡས་ཀྱི]ད་ཁ་སང་མཚམས་དེ་ཡིན་ད། ༤ 07:36 འེ་ཡ་འདི་ག་རེ་འདྲ་རེད་འདི། རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་[བའི་]བས་གཞལ་ན། ༥ 07:43 རྟག་[དཔྱད་](%E0%BD%86%E0%BD%91%E0%BC%8B)ཀྱི་མཐའ་གཉིས་ཀར་ལྟུང་ཡང་ཟེར་ཡག་འདི། འདི་[ཨ་]ཨེ་ནི་འེ་དཔེར་ན། ༦ 07:50 རང་རྒྱུད་པ་རྟག་མཐར་ལྷུང་བ་ད་གསལ་བ་བྱེད། རེད་བ། ༧ 07:56དཔེར་ན་རང་རྒྱུད་པ་ཕྱི་དོན་ཞལ་གྱིས་མི་བཞེད་པར་ཆ་བཞག་པ་ཡིན་ན། ཕལ་ཆེར་ཕྱི་དོན་ལ་སྐུར་བ་འདེབས་པའི་ཟོ་རེ་འདྲ་ཞིག་བཤད་པ་ཡིན་ན་བཤད་ཆོག་གི་[ཀྱི་]རེད་བ། ༨ 08:03 ཐ་] ད་ཕྱི་དོན་བཞེད་མཁན་གྱི་རང་རྒྱུད་པ་དེ་ཆད་ལྟ་ཡིན་པའི་སྒྲུབ་བྱེད་ག་རེ་བཤད་དགོས་རེད། ༩ 08:10 ཐ་སྙད། སྣང་ཕྱོགས། རྟེན་འབྱུང་ཕྲ་མོ། ད་འདི་ད་འདོད་ཀྱི་མ་རེད་བ། ༡༠ 08:17 རྟེན་འབྱུང་ཕྲ་མོ་རྟེན་འབྱུང་ཕྲ་མོ་བཞག་ག་ཕྱིན་པ་ཡིན་ན། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་རྟེན་འབྱུང་བཞག་ག་ཕྱིན་པ་ཡིན་ན། ད་འདི་ཆད་ལྟར་ལྟ་ཡིས་རེད་བ། ༡༡ 08:24 རང་རྒྱུད་པས་རེད་བ། [འདི་འདྲ་གཅིག་གང་ལ་བཤད་དགོས་རེད། ཤེས་བྱེད་གང་བཤད་དགོས་རེད། དེ་མིན་གང་ཞིག་བཤད་དགོས་རེད་ད།]དེའི་དབར་དེ་དག་གསུང་གསལ་བོ་མི་འདུག གཞན་དུ་འཚོལ་ཞིབ་གནང་ན་ལེགས། ༡༢ 08:29འོ་རེད་བ། བྱས་ཙང་ག་ཁོས་ཆད་ལྟ་ལྷུང་བ་རེད་སེ། རེད་བས། ༡༣ 08:37 [འེས་] འེ་ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱིས་བཞེད་པའི་ཆ་ནས། མདངས་]རྟག་མཐར་ལྷུང་། ༡༤ 08:43 ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱིས་བཞེད་པ་ཡིན་དུས་ཙ་ནས། ཐ་སྙད་དུ་མིང་རྐྱང་བཏགས་ཡོད་ཙམ་འཇོག་མི་ཐུབ་པ་ཡིན་དུས་ཆད་མཐའ་[ཐབ་]ལྷུང་སེ། འདུག་སེ་རེད་བས། ༡༥ 08:48 འདི་འདྲས་བཞག་འདུག་པས། འེ། རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་བས་གཞལ་ན་རྟག་ཆད་ ༡༦ 08:56 གཉིས་ཀྱི་མཐར་མཐའ་གཉིས་ཀར་བཏུང་ཡང་། ད་འདི་བྱས། ད་དེའི་གཤམ་དེ་འེ་དེ་ཡང་གྲུབ་མཐའ་སྨྲ་བ་བཞི་ལ་རྟག་[དཔྱད]ཆད་ཀྱི། ༡༧ 09:02 མཐའ་སྤོང་ཚུལ་མི་འདྲ་བ་རེ་ཡོད་དེ།[་དེས་ཟེར]། བྱེ་བྲག་སྨྲ་བ་རྣམས་འབྲས་བུ་སྐྱེ་བའི་ཚེ་རྒྱུ་འགག་པས་འེ་ ༡༨ 09:09 རྟག་མཐའ་སྤོང་ལ། འེ་འེ་ད་འེ། ༡༩ 09:18 རྒྱུའི་མཇུག་ཐོགས་སུ་འབྲས་བུ་འབྱུང་བས་ཆད་པའི་མཐའ་སྤོང་ངོ་ཞེས་ཟེར་རོ།།
> 
> ༢༠༢༣།༠༣།༢༧ ཕྱི་དྲོ།

2023-03-27 10:48 UTC, Tenzindharten commented
> ༡ 07:20 ད་ཡིས་འེ་བསམ་གཏན་གྱི་ལེའུ་ཡན་ཆད་དེ་གའི་དེ་གས་འེ་རྒྱ་ཆེ་བའི་ལམ་རིམ་གྱི་སྐོར་དེ་གསུང་། ༢ 07:27 ད་ཤེས་རབ་ལེའུ་འདི་ཡིས་ཟབ་མོའི་ལམ་གྱི་རིམ་པ་དེ་གསུང་གི་ཡོད་རེད། ༣ 07:31 ད་དེའི་ཡན་ལག་ལ་ཡ་ཨེ་ནི་གྲུབ་མཐའ་མར་འཁྲིད་ཡག་གི་[ཡས་ཀྱི]ད་ཁ་སང་མཚམས་དེ་ཡིན་ད། ༤ 07:36 འེ་ཡ་འདི་ག་རེ་འདྲ་རེད་འདི། རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་[བའི་]བས་གཞལ་ན། ༥ 07:43 རྟག་ཆད་[དཔྱད་](%E0%BD%86%E0%BD%91%E0%BC%8B)ཀྱི་མཐའ་གཉིས་ཀར་ལྟུང་ཡང་ཟེར་ཡག་འདི། འདི་[ཨ་]ཨེ་ནི་འེ་དཔེར་ན། ༦ 07:50 རང་རྒྱུད་པ་རྟག་མཐར་ལྷུང་བ་ད་གསལ་བ་བྱེད། རེད་བ། ༧ 07:56དཔེར་ན་རང་རྒྱུད་པ་ཕྱི་དོན་ཞལ་གྱིས་མི་བཞེད་པར་ཆ་བཞག་པ་ཡིན་ན། ཕལ་ཆེར་ཕྱི་དོན་ལ་སྐུར་བ་འདེབས་པའི་ཟོ་རེ་འདྲ་ཞིག་བཤད་པ་ཡིན་ན་བཤད་ཆོག་གི་[ཀྱི་]རེད་བ། ༨ 08:03 ཐ་] ད་ཕྱི་དོན་བཞེད་མཁན་གྱི་རང་རྒྱུད་པ་དེ་ཆད་ལྟ་ཡིན་པའི་སྒྲུབ་བྱེད་ག་རེ་བཤད་དགོས་རེད། ༩ 08:10 ཐ་སྙད། སྣང་ཕྱོགས། རྟེན་འབྱུང་ཕྲ་མོ། ད་འདི་ད་འདོད་ཀྱི་མ་རེད་བ། ༡༠ 08:17 རྟེན་འབྱུང་ཕྲ་མོ་རྟེན་འབྱུང་ཕྲ་མོ་བཞག་ག་ཕྱིན་པ་ཡིན་ན། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་རྟེན་འབྱུང་བཞག་ག་ཕྱིན་པ་ཡིན་ན། ད་འདི་ཆད་ལྟར་ལྟ་ཡིས་རེད་བ། ༡༡ 08:24 རང་རྒྱུད་པས་རེད་བ། [འདི་འདྲ་གཅིག་གང་ལ་བཤད་དགོས་རེད། ཤེས་བྱེད་གང་བཤད་དགོས་རེད། དེ་མིན་གང་ཞིག་བཤད་དགོས་རེད་ད།]དེའི་དབར་དེ་དག་གསུང་གསལ་བོ་མི་འདུག གཞན་དུ་འཚོལ་ཞིབ་གནང་ན་ལེགས། ༡༢ 08:29འོ་རེད་བ། བྱས་ཙང་ག་ཁོས་ཆད་ལྟ་ལྷུང་བ་རེད་སེ། རེད་བས། ༡༣ 08:37 [འེས་] འེ་ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱིས་བཞེད་པའི་ཆ་ནས། མདངས་]རྟག་མཐར་ལྷུང་། ༡༤ 08:43 ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱིས་བཞེད་པ་ཡིན་དུས་ཙ་ནས། ཐ་སྙད་དུ་མིང་རྐྱང་བཏགས་ཡོད་ཙམ་འཇོག་མི་ཐུབ་པ་ཡིན་དུས་ཆད་མཐའ་[ཐབ་]ལྷུང་སེ། འདུག་སེ་རེད་བས། ༡༥ 08:48 འདི་འདྲས་བཞག་འདུག་པས། འེ། རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་བས་གཞལ་ན་རྟག་ཆད་ ༡༦ 08:56 གཉིས་ཀྱི་མཐར་མཐའ་གཉིས་ཀར་བཏུང་ཡང་། ད་འདི་བྱས། ད་དེའི་གཤམ་དེ་འེ་དེ་ཡང་གྲུབ་མཐའ་སྨྲ་བ་བཞི་ལ་རྟག་[དཔྱད]ཆད་ཀྱི། ༡༧ 09:02 མཐའ་སྤོང་ཚུལ་མི་འདྲ་བ་རེ་ཡོད་དེ།[་དེས་ཟེར]། བྱེ་བྲག་སྨྲ་བ་རྣམས་འབྲས་བུ་སྐྱེ་བའི་ཚེ་རྒྱུ་འགག་པས་འེ་ ༡༨ 09:09 རྟག་མཐའ་སྤོང་ལ། འེ་འེ་ད་འེ། ༡༩ 09:18 རྒྱུའི་མཇུག་ཐོགས་སུ་འབྲས་བུ་འབྱུང་བས་ཆད་པའི་མཐའ་སྤོང་ངོ་ཞེས་ཟེར་རོ།།
> 
> ༢༠༢༣།༠༣།༢༧ ཕྱི་དྲོ།

2023-03-28 16:38 UTC, Tenzindharten requested changes
༡. 09:22[ མདོར་བདེ་བ་དང་]མདོ་སྡེ་པ་དག་འདུས་བྱས་རྣམས། ད་འོ་སྤྱིར་བཏང་[སྟངས་]་འ་ད་རྒྱུན་ལ་ལྟ་ཉེ་ན། [བལྟ་ཉེས]
༢. 09:27 རྒྱུན་ཡོད་རེད་བ་ད། འོ་རྒྱུན་ལ་ལྟ་[ཉེས]་ཉེ་ན[་ཨ་]ཨེ་ནི[་འེས་འེས]་ཨི་ཨི་ག་རེ་ཟེར་བ་རེད། ཕ་གིའི། [དགོས་རེ་ཕལ་གིས།]
༣.  09:34 ཨ་] ཨེ་ནི་སྔ་ཕྱི་གཅིག་འཛིན་གྱི[་འེས་]ཨི་རྟག་པ་[པར་]་ལ་ལྟ་ཡག་[དེ]་འདྲ་ཡོང་ཡོང་གིན་འདུག་ག [སོ་དེས་] སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས།
༤. 09:40 {ཐ་འེས་}ཨི་བྱེ་བྲག་སྨྲ་བས་[ད་ལྟ་]གང་ལྟར་ཨེ་ནི[་འེས]་ཨི་རྒྱུན་ད་ཁོ་རྫས་ཀྱི་རྫས་རྒྱུན་གཅིག་གདའ་ཡོང་གི་ཡོད་ཀྱི་རེད། ཡོང་གིན་རེད་དེ། ཡིན་ནས་ད་ཁོ་རང་ཨི། [འེས།]
༥.  09:49 ཡང་རྒྱུའི་གནས་སྐབས་གཅིག[།།]  འབྲས་བུའི་གནས་སྐབས་གཅིག་ཨོ་ཨི། དཔེར་ན། གྲངས་ཅན་པས།
༦.  09:55 རྒྱུ་འབྲས་རང་བཞིན་གཅིག་པ་[ཤོད]་བཤད་ཡོང་གི་[ཀྱི་]ཡོད་རེད་བ་ད། རྒྱུ་འབྲས་རང་བཞིན་གཅིག་པ། བདག་ཉིད་གཅིག་པ་ཟེར་དགོ་རེད་བས། [བཤད་ཀོ་རེད་]ད་འོ་དེ་ཚོ་[དག་]དང་མི་འདྲ་བ་ཆགས་ཀྱིས། 
༧.  10:03 འབྲས་བུ་སྐྱེས་པའི་ཚེ་[་ཅིག]་རྒྱུ་འགག་པས་[འི་བརྟང་ཐབ་]་རྟག་མཐའ་སྤོང་། རྒྱུ་ཡི་[འཇུག་]མཇུག་ཐོགས་[སྡུས་]སུ་འབྲས་བུ་འབྱུང་བས་ཆད་མཐའ[་ཆ་ཐབ]་སྤོང་།
༨.  10:09 མདོ་སྡེ་པ་དག་འདུས་བྱས་རྣམས་རྒྱུན་མ་ཆད་པར་འཇུག་པས་ཆད་པའི་མཐའ་སྤོང། 
༩.  10:14 སྐད་ཅིག་གིས་འཇིག་པས་རྟག་པའི་མཐའ་ལས་གྲོལ་ཞེས་[ཞིན་]འདོད་དོ།། མ་གཞི་བྱེ་བྲག་སྨྲ་བས་ཨི་ཨི། [འེས།]
༡༠.   10:22 ཨི་ག་རེ་ཟེར་བ་རེད།  [ག་རེ་ཟེར་དགོས་རེད]ཕ་གིའི་[་འེས་འེས་རྦད]ཨི་ཨི་འདུས་བྱས་ཐམས་ཅད།
༡༡. 10:30 མི་རྟག་པ་ཟེར་བྱས་ནས་གསུངས་གསུང་གིན་ཡོད་རེད་དེ། ཡིན་ནས་ཨི་མཚན་ཉིད་སྐྱེ་སོགས་བཞི་ཟེར་ཡ་གཅིག མ་གཞི་[ཤམ་]གཤམ་ལ་ཡོང་ཕལ་ཆེར་[ཕྱིར]་ཡོད་རེད།
༡༢.   10:35 མཚན་ཉིད་སྐྱེ་སོགས་བཞི་ཟེར་ཡག་ཅིག་[ཡས་ཞིག]་གསུངས་ནས། ཨེ་ནི་ཨི་སྐྱེ་བའི་བྱ་བ། གནས་པའི་བྱ་བ།
༡༣.   10:42  [འགག་]དགའ་བའི་[པའི་]བྱ་བ། ཨེ་ནི་ག་རེ་འཇིག་པ་བཅས་གང་ལྟར་། [འེས་འེས།]ཨི་ཨི།
༡༤.  10:48 སྐྱེས་བའི་རྗེས་ལ་གནས་པའི་བྱ་བས་གནས་པར་བྱེད་ཡག [ཡས་]བཤད་ཀྱི་འདུག་ག ཁོ་སྐྱེས་ཙམ་ཉིད་ནས་འཇིག་པའི་བདག་ཉིད་དེ་ཕལ་ཆེར་མི་ཤེསཔ་་ཡིན་པ་རེད།
༡༥. 10:56 བྱས་ཙང་ག ད་མདོ་སྡེ་པས་གསུང་ཡོང་དུས་ཙ་[ཙམ་]ནས་སྐད་ཅིག་གིས་འཇིག་པས་ཟེར་དུས། 
༡༦.   11:01 [འེས་]ཨི་རྒྱུས་[རྒྱུད་]སྐྱེས་ཡག་ཁོ་རང་འཇིག་པའི་བདག་ཉིད་དུ་སྐྱེས་པ་རེད། [དེས་]དེ་འདྲས་ཡིན་དུས་གྲུབ་ཙམ།
༡༧.  11:07 ཉིད་ནས་འཇིག་པའི་བདག་ཉིད་དུ་གྲུབ་པ་རེད་ཟེར་ཡག་གིས་[འདྲ་བོ།]འཇིག་པ་ཕྱིས་འབྱུང་གི་རྒྱུ་ལ་ལྟོས་ཀིས་[གྱི་]ཡོད་མ་རེད་སེ། འདི་གསུང་གིན་[གསུངས་ཀྱི་]ཡོད་པ་ཡིན་དུས།
༡༨.  11:13སྐད་ཅིག་གིས་འཇིག་པས་རྟག་པའི་མཐའ་ལས་གྲོལ་ཞེས་འདོད། སེམས་ཙམ་པ་མ་རྣམས་ཀུན་བཏགས་བདེན་པར་མ་གྲུབ་པས་རྟག་པའི་མཐའ་སྤོང་ལ།
༡༩.   11:20 ད་མཚན་ཉིད་གསུམ་ཕྱེ་ནས། ཨི་ཨི་[འེས་་་འེས་]ཀུན་བཏགས་བདེན་པར་[པ་]མ་[བསྒྲུབ]་གྲུབ་པས་[པའི་]རྟག་པར་ཐ་སྤོང་ལ་
༢༠. 11:29གཞན་དབང་བདེན་པར་གྲུབ་པས་[བསྒྲུབ་པའི་]ཆད་པའི་[ཐ་]་མཐའ་སྤོང་ངོ་ཞེས་སྨྲའོ། དབུ་མ་པ་རྣམས།
༢༡.   11:34 ཆོས་ཐམས་ཅད་ཐ་སྙད་དུ་ཡོད་པས་ཆད་པའི་མཐའ་ལས་གྲོལ་ཞིང༌། དོན་དམ་དུ་མེད་པས་རྟག་པའི་མཐའ་ལས་གྲོལ་[ཞིག་]ཞེས་བཞེད་དོ།
༢༢.   11:41 གྲུབ་མཐའ་གོང་མ་[མོ་]གོང་མ་[མོ་]རྣམས་ཀྱིས་འོག་མ་འོག་མའི་གྲུབ་མཐའ[་ཐུན་]མཐུན་མོང་མ་ཡིན་པ་རྣམས་འགོག་པར་བྱེད་ཀྱང༌།
༢༣.   11:45  འོག་མ་འོག་མའི་ལྟ་བ་གོ་བ་དེ། གོང་མ་གོང་མའི་ལྟ་བ་གོ་བའི་ཐབས་དམ་པར་སྣང་བས། གྲུབ་མཐའ་གོང་མ་ལ་མཆོག་ཏུ་བཟུང་ནས་འོག་མ་ལ་སྡང་བར་མི་བྱའོ།།

༢༠༢༣།༠༣།༢༨ མཚན་མོ་བཅོས།

2023-03-29 04:08 UTC, Tenzindharten requested changes
༡. 11:53 [འེས་]ཨི་ད་ཨེ་འདྲས་གཅིག་རེད་ཤག ད་[དེས]་དེ་ནས།
༢. 12:00 དེས་ན་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་ཁས་ལེན་པའི་གང་ཟག་དེ། ནང་པ་སངས་རྒྱས་པའི་གྲུབ་མཐའ་སྨྲ་བའི་མཚན་ཉིད་དུ་འཇོག 
༣ 12:06ད་ཕྱག་རྒྱ་བཞི་[འདི]དེ། འདུས་བྱས་ཐམས་ཅད་མི་རྟག་པ༑ ཟག་བཅས་ཐམས་ཅད་སྡུག་བསྔལ་བ། [འེས་]ཨི་ཆོས་ཐམས་ཅད་བདག་མེད་པ།
༤. 12:13  ཡང་ན་ཆོས་ཐམས་ཅད་སྟོང་ཞིང་བདག་མེད་པ། 
༥. 12:17 ཆོས་ཐམས་ཅད་སྟོང་ཞིང་བདག་མེད་པ་ཟེར་ནས[་ཡས་]གཉིས་ཕྱེ་བ་ཡིན་ན། ཡང་ན་བདག་དང་[ཏུ་]བདག་གི་བ།[རེད།]
༦. 12:22[འེས་འེས་]ཨི་ཨི་ད་ག་རེ་[རེད་]ཟེར་བ[་དགོས་ར་]ཕ་གིའི་ཨི། [ཕལ་གིས་འེས།]
༧. 12:26 [ཡ་]ཡང་[འེས་]ཨི་བདག་དང་བདག་གི་ག་རེ་[རེད]་ཟེར་བ་རེད་ད། [དགོས་ར་ཐ་འེས་]ད་གང་ལྟར་བདག་ཏུ་ལྟ་བ་དང་།
༨. 12:31 [འེས]་ཨི་བདག་གི་བ་ལྟ་བ་དེ་འདྲའི་[དྲ་]འདྲ་བོ་མེད་པའི་དོན། ཡང་ན་ཨི་[འེས]་ཕུང་པོ་ལས་དོན་གཞན་པའི་བདག་གིས་སྟོང་བ།
༩. 12:38 ཨེ་ནི་རང་རྐྱ་བའི་བདག་མེད་པ། དེ་འདྲའི་བཞག་ཐུབ་ཀི[་སྦྱར་ཐུབ་ཀྱི་]ཡོད་ན། ད་དེ་ནས་མྱ་ངན་ལས་འདས་པ་ཞི་བ་རྣམས་སོ།།
༡༠. 12:45 ད་དེ་གཞུག་གུ་ལ་དོགས་[གཅོད]དཔྱོད། ། གལ་ཏེ་གནས་མ་བུ་བ་བས་གང་ཟག་གི་
༡༡. 12:51 བདག་ཁས། མ་རེད། གལ་ཏེ་[ལྟེ་]གནས་མ་བུ་བས་གང་ཟག་གི་བདག་ཁས་བླངས་པས་སེ། ད་བདག་བརྗོད་དུ་མེད་པ་ཟེར་གིན་ཡོད་རེད།
༡༢. 12:57  ད་བདག་མེད་རང་ག་རེ་ཟེར་བ་རེད། ཕ་གིའི་[ཕལ་གིས་འེས་]ཨི་ཤོད་མ་འཕོད་པ་བྱས་ཀྱིས་བདག་མེད་ཟེར་ཡ་དེ། [འདི]་བློ་ལ་མ་ཤོང་བ་བྱས་ཀྱིས།[ཅས།]
༡༣. 13:04  བདག་ཟེར་ཡག་[ཡས]་འདི་[འེས་]ཨི་ཡང་ཕྱི་རོལ་པས་བཤད་པ་ནང་བཞིན་གིས་[གྱི་]ཕུང་པོ་ལས་དོན་གཞན་དུ་བདག་འདི་ཞེས་མཛུབ་གུ་འཛུགས་ས་ཡང་མེད་བསྡད་པ།
 ༡༤. 13:12 [དེས་]དེ་འདྲས་[འདྲ་]ཡིན་པ་[པའི]ཡིན་དུས་ཙ་[ཙམ་]ནས། ད་ཕུང་པོའི་ཕྱི་དང་ནང་གང་དུ་ཡང་[འང་]བདག་ཟེར་བྱས་ནས། མཛུབ་གུ་[མོ་]འཛུགས་ཡག་[ཡས]་གསལ་པོར་གཅིག་མེད་པ་ཆགས་ཡོང་དུས་ཙ་ནས།
༡༥. 13:17  བརྗོད་དུ་མེད་པའི་བདག་ཟེར་ཡག་ཅིག སེ་ད་ཁོ་སྤྱིར་བཏང་བརྗོད་དུ་མེད་པ་ཟོ་འདྲ་བོ། བརྗོད་དུ་མེད་པ་ཟོ་འདྲ་བོ་ཆགས་ཀི༌འདུག་ག 
༡༦. 13:25  ད་ཁོ་བདག་མཛུབ་གུ་འཛུགས་ས་མེད་དུས་ཙ་ནས། ཁོ་བརྗོད་དུ་མེད་པ་ཟོ་འདྲ་པོ་ཆགས་ཀི་འདུག་སྟེ། ཝ་ད་འདི་བདག་མེད་རང་ད།
༡༧. 13:29 ཨི་ག་རེ་[རེད་]ཞུ་བ་རེད། [དགོས་ར་ཕལ་]ཕ་གིའི་ཨི་[འེས་]བློར་ལ་མ་ཤོང་། ད་དེ་ལ་ལྟོས་ནས་ཨེ་ནི་བརྗོད་དུ་མེད་པ་སེ་ལབ་དུས་ཙ་[ཙམ་]ནས།

༢༠༢༣་༠༣་༢༩

2023-03-29 06:14 UTC, Tenzindharten requested changes
༡. 13:38 ཕུགས་ཀིས[་གིས་]བདག་མེད་པ་རང་མ་རེད། བདག་དེ་བ་ལ་[བདེ་བར་]གཅིག་ཡོད་པའི་བཟོ་འདྲ་པོ་གཅིག ད་དོན་གྱིས་[ཀྱི་]འདི་འདྲས་ཆགས་ཀྱི་ཡོད་རེད་བ་ད།
༢. 13:44 [འདི]དེ་མིན་འགྲོ།[ ཨ་འེས]་ཨི་གནས་མ་བུ་བས་གང་ཟག་ལ་བདག་ཁས་བླངས་པས། ནང་པའི་གྲུབ་མཐའ་སྨྲ་བ་མ་ཡིན་པར་འགྱུར་རོ་ཞེ་ན་
༣. 13:49  སྐྱོན་མེད་དེ། དེས་ཁས་བླངས་པའི་བདག་ནི། རང་རྐྱ་ཐུབ་པའི་རྫས་ཡོད་ཀྱི་བདག་ཡིན་ལ། ཕྱག་རྒྱ་བཞིའི་ནང་གི་བདག་མེད་ནི།
༤. 13:55  རྟག་གཅིག་རང་དབང་ཅན་གྱིས་སྟོང་པའི་བདག་མེད་ལ་བྱེད་ཅིང༌།
༥. 13:59  འོ་འདི་ཡིན་ན་ཨེ་ནི་ཨི་ཆོས་ཐམས་ཅད་བདག་མེད་པ་ཟེར་ཡག་[ཡས་]འདི་རྟག་གཅིག་རང་དབང་བའི་བདག་གིས་སྟོང་བ་དེ་ལ་སྦྱར་གནང་ཤག དེ་ནི་མང་བཀུར་སྡེ་ལྔས་ཀྱང་ཁས་ལེན་པའི་ཕྱིར་རོ། དེ་འདྲས་ཤིག་འདུག 
༦. 14:09 བྱས་ཙང་འོ། རིགས་གཅིག་གིས། ཨེ་ནི་ཨི་གཅིག་པོ་དེ། [འདི]ཝ་ད་བདག་བརྗོད་དུ་མེད་པ་འདོད་མཁན་དེ་གའི་དེ། 
༧. 14:18 ལྟ་བའི་ཆ་ནས་ཨེ་ནི་ནང་པ་མ་རེད་བྱས་ནས་གསུང་མཁན་དེ་འདྲ་ཡོད་པ་རེད། ད་འདི་སྔོན་གྱི་མཁས་པ་ཚོས་ཏོག་ཏོག་ཟེ་གསུང་སྟངས་མི་འདྲ་མི་འདྲ་བ་ཡོང་བསྡད་ཀྱི་འདུག་ག
༨. 14:24 འགྲིག་སོང་ང་། ད་དེ་ནས་གཉིས་པ་བྱེ་བྲག་ཏུ་བཤད་པ་ལ།
༩. 14:32  [ཐ་]ད་བྱེ་བྲག་སྨྲ་བ། མདོ་སྡེ་པ། སེམས་ཙམ་པ། ངོ་བོ་ཉིད་མེད་པར་སྨྲ་བའི་གྲུབ་མཐའ་བཞི་བྱས། ད་མཚན་ཉིད་དབྱེ་བ་ཟེར་ཡག་མི་དགོས་པ་བྱས།
 ༡༠. 14:37 མཚན་ཉིད་དབྱེ་བ་སྒྲ་བཤད་གལ་སེ་མིན་འདུག ད་འདི་ནས་མར། བཞི་བ་འདོད་ཚུལ་ལ། བཞི་ཡི་འདོད་ཚུལ། ལམ་གྱི་འདོད་ཚུལ། འབྲས་བུའི་འདོད་ཚུལ་ 
༡༡. 14:45 ལོ། བཞི་ལམ་འབྲས་གསུམ་བྱས་ནས་ཨི་ཕྱེ་ཡག་[བཤད་ཡས་]འདི་གནད་དགག་ཆེན་པོ ཞེ་པོ་རེད་ཞག
༡༢. 14:52 [འེས་]ཨི་ཁ་སེང་བཞུས་པ་ནང་བཞིན། ད་ཁོ་གཞི་[བཞི]ཡི་གནས་ཚུལ་[འེས་]ཨི་དེས།
༡༣. 14:59 ཨི་དེ་ལ་ཡ་ཨེ་ནི་ཁོ་[སྒྱུར་]འགྱུར་བ་འགྲོ་ཡག་ཡོད་བསྡད་པ་ཞིག་དང་། [སྒྱུར]འགྱུར་བ་གཏོང་ཡག་ཡོད་བསྡད་པ་གཅིག་གི་[ཡི་འེས་] ཨི་གནས་ཚུལ་གཅིག་ཡོད་པ་ཡིན་དུས་[ཙམ་]་ཙ་ནས།
༡༤. 15:07 ཨེ་ནི་[སྒྱུར]འགྱུར་བ་འགྲོ་བཞིན་པའི་[སྣས་]གནས་སྐབས་ཀྱི་སྒྱུར་འགྱུར་བ་གཏོང་ཡག་དང་། [སྒྱུར་བ་]འགྱུར་བ་ཐེབས་པའི་གནས་སྐབས་གྱི་ཨེ་ནི་ལམ་གྱི་འདོད་ཚུལ་དང་། 
༡༥. 15:13 [ད་དེས]་་དེ་ལ་བརྟེན་ནས་འགྱུར་བ་མཐར་ཐུག་པ་ཡོང་བསྡད་ཡག་ཅིག་ཡོང་གིན་ཡོད་པ་ཡིན་དུས་འབྲསས་བུའི་འདོད་ཚུལ་སེ། [་ཙུལ།]
༡༦. 15:19 [དེས]དེ་གནད་འགག་ཆེན་པོ་འདུག་ག ཨི།

༢༠༢༣་༠༣་༢༩ ཉིན། ཧྲིལ་པོ་གཅིག

2023-04-05 17:38 UTC, Tenzindharten requested changes
00:00ཡ་གྲུབ་མཐའ། ད་འདིའི་འགོ་ནས་མར་བཤད་ཡ་ཟིག་གལ་མི་འདུག་ག

00:03 བྱས་ད་འདིར་ཨིའི་རང་གཞན་གྱི་གྲུབ་མཐའི་རྣམ་གཞག་མདོར་བསྡུས་ཏེ་བརྗོད་པ་ལ་གཉིས།།

00:13ཨིའི་སྤྱིར་སྤྱིར་བསྟན་པ་དང༌། བྱེ་བྲག་ཏུ་བཤད་པ། རྙེད་སོང་བས། ས་བཅད་དེ། འདུག་ག

00:17བྱས་ཙང་། ད་འདིར། འོ་རྗེ་རིན་པོ་ཆེ་ཡི་སྔགས་རིམ་ཆེན་མོའི་

00:24སྔགས་རིམ་ཆེན་མོའི་ནང་ལ་ཡང་ འདི་གསུང་ཡོད་རེད། འགོ་དེར། ཨེ་ནི།

00:29 ཨིའི་མུ་སྟེགས་བྱེད་ཡོད་དམ་མེད་ཀྱང་སླ་ཡི་ཟེར།

00:36 ཨིའི་རང་རང་སོ་སོ་རྒྱུད་ལ་ཡར་སྔོན་གྱི་ཨ་ནི་ལྟ་བ་ཕྱིན་ཅི་ལོག་དེ་འདྲའི་བག་ཆགས།།

00:42ང་རང་ཚོའི་རྒྱུད་ལ་ཡོད་པ་ཡིན་དུས། ཨེ་ནི། ཨིའི་ཨིའི་ལྟ་བ་འདྲ་མི་འདྲ།།

00:47དེ་གས་དེ་ཤེས་པར་བྱས་ནས། ཨེ་ནི་འཐད་མི་འཐད་ཀྱིས།།

00:50དཔྱད་པ་བྱ་ཡག་དེ་གལ་ཆེན་པོ་ཞེ་དྲག་རེད་ཅེས་གསུངས་འདུག་ག་

00:53བྱས་ཙང་རྗེ་རིན་པོ་ཆེ་བོད་ལ་ཡོད་དུས་ཙ་ནས།།

00:56བོད་ལ་ཡ་མུ་སྟེགས་པ་ཡོད་མ་རེད་བ།།

00:58 ཨེ་ནི་མུ་སྟེགས་པ་ཚོ་དང་འབྲེལ་བ་ཟིག་གལ་ཡོད་མ་རེད་བ།  ཕྱི་ལོག་ལ་ཡ་ད་ཡོད་པའི་མུ་སྟེགས་ཚོ་དང་ཧེ་འབྲེལ་བ་ཟེ་གལ་ཡོ་མ་རེད་བ། ང་ཚོ་བོད་ལ་ཡ།།
01:04བྱས་ཙང་ག. རྗེ་རིན་པོ་ཆེས་འདི་གསུངས་ཡོད་རེད།།

01:07 ཨིའི་ད་དེང་སང་ང་ཚོ་ད། ཨིའི་ལྟ་གྲུབ་འདྲ་མི་འདྲའི་དཀྱིལ་ལ་ཡ་ང་ཚོ་བསྡད་བསྡད་ཡོད་རེད་བ།།

01:14ཨིའི་དེ་ཙམ་དུ་མ་ཟད་པས་ད་ང་ཚོ་བོད་པའི་ངོས་ནས་བཤད་པ་ཡིན་ན་རེད་གདའ།།

01:19མ་འོངས་པ་ལ་ཡ། ང་ཚོ་ད་བོད་ལ་ཡ་གཅིག་གཞིས་བྱེས།།

01:22མཉམ་འཛོམས་བྱུང་བའི་རྗེས་ལ་ཡིན་ན་ཡང། ད་འཛམ་བུ་གླིང་འདི།།

01:26གཅིག་གི་གཅིག་ལ་འབྲེལ་བ་དེ་ཞེ་དྲག་ཤུགས་ཆེན་པོ་ཡོད་རེད།།

01:28འབྲེལ་བ། གཅིག་གི་གཅིག་གི་ཕ་གིའི་འབྲེལ་བ་ཐག་ཉེ་བོ་གཅིག་དགོས་ཀི་རེད།།

01:32སེ་དེ་འདྲ་ཞིག་ཡིན་དུས་ཙ་ནས། གང་ལྟར་འཛམ་བུ་གླིང་གི་ས་ཆ།།

01:36གང་བར་བསྡད་ཡོད་ནས་མེད་ནས། གང་ལྟར་ལྟ་གྲུབ་འདྲ་མི་འདྲའི་དཀྱིལ་ལ་ང་ཚོ་ཡོད་ཡོད་པ་རེད་བ།།

01:40 ALL WORLD རེད་བ། Globalཁོ་རང་Multiད་ག་རེ་ཟེར་བ་རེད། WORLD ད་ག་རེ་ཟེར་བ་རེད། གླིང་འདྲ་བོ་གཅིག་བཟོ་འདྲ་ཆགས་ཡོང་གི་འདུག་ག འཛམ་གླིང་ཡོངས་རྫོགས་ལོག་དེ་

01:50བྱས་ཙང་ག འཛམ་གླིང་ཡོང་རྫོགས་ལབ་དུས་ཁོ་གླིང་གཅིག་ཆགས་ཡོང་དུས་ཙ་ནས།།

01:53 གླིང་གཅིག་ཆགས་བསྡད་མཁན་གྱི་གླིང་དེmulticulture 

01:57 ད་གང་ལྟར། ཨིའི་རིག་གཞུང་འདྲ་མི་འདྲ་ཡོད་བསྡད་པ། རིག་གཞུང་། རིག་གཞུང་། རིག་གཞུང་སྣ་ཚོགས་ཅན།།

02:03ཆོས་ལུགས་སྣ་ཚོགས་ཅན། གྲུབ་མཐའ་སྣ་ཚོགས་ཅན་གཅིག་ཆགས་བསྡད་ཡོད་རེད་བ།

02:08སེ། དེ་འདྲས་ཡིན་དུས་ཙ་ནས། ཨིའི་ང་རང་ཚོ་དེ་སྔ་བོད་ལ་ཡ་གཅིག

02:14 ཨིའི་ཆོས་བྱེད་མཁན་ཅིག་ཡིན་པ་ཡིན་ན། ཨ་ནི།

02:17གཅིག་ལམ་རིམ་འདྲ་འདྲ། ཨེ་ནི་བློ་ལྡོག་རྣམ་བཞི་འདྲ་འདྲ།།

02:20གཅིག་འདི་དྲའི་ཐོག་ནས་ཨེ་ནི་མར་འདུམ་བདེ་པོ་བྱས་ནས། འཁྲིད་ཡ་ཞིག་འདུག་ག་

02:25དེ་དུས་ཚོད་ཡོལ་བ་རེད་བཞག། བྱས་ཙང་ཁྱེད་རང་ཚོ་ཀོ་རི་ཡར་ཆ་བཞག་ནས།།

02:29ད་དེ་སྔ་ང་རང་ཚོས་ད་གཅིག་ནམ་རྒྱུན་ཆོས་ཟེར་ལབ་དུས་ཡིན་ཤག་ཤག་འདྲ་བོ་བྱས།།

02:37སངས་རྒྱས་པའི་ཆོས་ཟེར་ལབ་དུས་གཅིག་ཡིན་ཤག་ཤག་འདྲ་བོ་བྱེད་བསྡད་ཡག

02:40ད་དེའི་ཐོག་ནས་དད་པ་བྱེད་ཡག་དེ་དུས་ཚོད་ཡོལ་བ་རེད། སེ། དེ་འདྲས་ཡིན་དུས་ཙ་ནས།།

02:47 ད་ཨིའི་ཕྱི་ནང་གི་གྲུབ་མཐའ་ཨིའིསྣ་ཚོགས་པ་དེ་གའི་དེ་ཤེས་དགོས་ཡ་རེད་བཞག་

02:55ད་ཕྱི་ནང་གི་སྣ་ཚོགས་པའི་གྲུབ་མཐའ་ཟེར་དུས་ཙ་ནས།།

02:59དེ་སྔ་རྒྱ་གར་ལ་ཡོད་པའི་འདི་གཅིག་པོ་ཡིས་འདང་གིན་མིན་འདུག་ག་

03:03ད་ད་ལྟ་འཛམ་བུ་གླིང་འདིའི་སྟེང་ལ་ཡོད་པའི་གཅིག་ཡེ་ཤུ། ད་ག་ནང་བཞིན་གྱི་ཁ་ཆེ།

03:08ད་ག་ནང་བཞིན་འཇིའུ། 

03:11ད་ག་ནང་བཞིན་གྱི་དཔེར་ན་ ག་རེ་ཟེར་གོ་རེད་དཔེར་ན་ཛོ་ལ་ཛོ་དིམ། པར་སིག་གི པར་སིག་གི་ཆོས་ལུགས་གཅིག་འདུག་ག་ བྷོམ་སྦེལ་དེ་བ་ཏོག་ཙམ་ཡོད་རེད།

03:18ད་འོ་དེ་དང་དེ་འདྲ་བ། ད་དཔེར་ན་ངས་ཤེས་པ་དེ་ཚོས་དྲས་རེད་ད་དེ་དང་དེ་འདྲ་བའི།།

03:24 ཨེ་ནི་ག་རེ་ཟེར་བ་རེད། ཕ་གིའི་ཨིའི་ཆོས་ལུགས་དེ་ཚོའི་འགྲོ་སྟངས་ཀྱང་ཤེས་དགོས་ཡ་གཅིག་རེད་བཞག་

03:31ཨེ་ནི། དེ་གའི་དེའི་ཨིའི་ལྟ་བ་དང་གྲུབ་མཐའ་དེ་གའི་དེ་ཤེས་དགོས་ཡ་རེད་བཞག་

03:34དེ་ཙམ་དུ་མ་ཟད་པའི་ཨེ་ནི་Western  Philosophyནུབ་ཕྱོགས་པའི་ལྟ་བ།

03:41humanismཟེར་གི་མེད་འགྲོ་གང་ལྟར་གཅིག་མིའི་བསམ་བློའི་ཐོག་ནས་གཅིག་བསམ་བློ་གཏང་བསྡད་ཡས་འདི་འདྲའི།

03:48ལྟ་གྲུབ་དེ་འདྲའི་འདུག་ག་ དེ་ཚོའི་གྲས་ག་ཤེས་དགོས་ཡ་རེད་བཞག་

03:53དེ་ག་ནང་བཞིན་གྱི་modrenscienceཤེས་དགོས་ཡ་རེད་བཞག་

03:57འདི་ཚང་མ་གཅིག་ ད་ ང་ཚོ་དོ་སྣང་བགྱིས།དཔྱིས་ཕྱིན་པ་ཤེས་ཡ་དེ།སྔོན་ལ་ཁག་པོ་རེད་དེ།

04:03ཡིན་ནས་གང་དག་གནད་འགག་གནད་འགག་འདྲ་བོ་དེ་ཤེས་པ་འབྱུང་ན།

04:07དེས་ཕན་ཐོགས་ཞེ་དྲག་ཡོད་རེད། གལ་ཆེན་པོ་རེད་བཞག་

04:09འོ་ད་ཡང་བསྟན་པ་སྤྱི་མཚན།གང་ཟག་སྒོས་བཙན་ཟེར་བྱས་ནས།།

04:15ཡ་འགྲོ་སྟངས་མི་འདྲ་བ་གཉིས་ཡོང་གི་ཡོད་རེད། བོད་ཀྱི་ད་ལྟ་འེས་དེ་གཉེན་མགོན་གསུང་རབ་པ།

04:22འེས་ཁམས་ཀྱི་ད་ལྟ་མགོ་ལོག་གི་གཉེན་མགོན་སྤྲུལ་སྐུ་གསུང་རབ་པ་ཟེར་ཡ་གཅིག་འདུག་ག་

04:26འོ་ཁོང་གིས་དེ་འདྲའི་གསུང་བཞག་བསྟན་པ་སྤྱི་མཚན།འེས་གང་ཟག་སྒོས་མཚན་ཟེར་ཡ་གཅིག

04:32བྱེ་འདི་གནད་འགག་རེད་ཞག་ད་ད་ལྟ་གཅིག་ཕྱི་ནང་གི་གྲུབ་མཐའ་ལ་སོགས་པ།

04:37དེ་དག་ཚང་མ་ཤེས་དགོས་ཡ་གཅིགགལ་ཆེན་པོ་འདུག་ཟེར་ཡ་དེ།

04:40ང་ཚོ།བསྟན་པ་སྤྱི་མཚན་བྱེས་ནས་བཤད་ཡོང་དུས་ཙ་ནས་དེའི་རིགས་ངེས་པར་དུ་དགོས་ཡ་རེད།།

04:43སློབ་སྦྱོང་བྱེས་་དགོས་ཡ་དེ། འོ་ད་གང་ཟག་སྒོས་བཙན་ཟེར་དུས་ཙ་ནས།ད་ཡང་གང་ཟག་རིགས་བྱེ་བྲག་པ།

04:50ཨ་བྱེ་བྲག་པ་གཅིག་གིས་དེ་འདྲའི་རྣམ་གྲངས་མང་པོ་ཤེས་མི་དགོས།

04:55རྣམ་གྲངས་གཅིག་གི་ཐོག་ནས། ཨ་ནེ་སོ་སོའི་འདི་ག་རང་ལ་ཡ་ཨི་ནེ་ཕ་གིའི་མྱོང་བ།སྟོན་ཅས།།

05:00ཡང་ཉམས་ལེན་བྱས་ནས་འགྲོ་སྡོད་མཁན་དེ་འདྲའི་ཡོང་གི་རེད་བ།

05:02ཨིའི་དེའི་དབང་དུ་བྱས་པའི་ཡང་གཅིག་བསྟན་པའི་རྣམ་གཞག་གཏན་ལ་ཕབ་ནས། 

05:07ཉམས་ལེན་བྱེད་ལུགས་ཀྱི་ཁྲིད་ལུགས་གཅིག་ཡོད་རེད།

05:09དེ་གང་ཟག་སྒོས་མཚན་དབང་དུ་བྱས་པའི་ཁྲིད་ལུགས་དེ་བྱེད།

05:12ད་སངས་རྒྱས་ཀྱི་བསྟན་པ་འཛམ་བུ་གླིང་འདིའི་སྒང་གང་ལ་སྤྱིའི་ཆ་ནས་གཏན་ལ་ཕབ་ཡོང་དུས་ཙ་ནས།

05:18འོ་ད་ཕྱི་ནང་གི་གྲུབ་མཐའ་གཅིག་མཆིས་སོ་ཅོག དེ་གའི་དེ་ཤེས་པའི་ཐོག་ནས།

05:23ཨེ་ནི་དེ་གའི་དེ་དང་མགོ་བསྟུན། སྒོ་བསྟུན་པ་ཟེར་དགོས་རེད་བས།

05:26དེ་གས་དེ་ཚང་མ་ཡོང་ཡ་འབྲེལ་ཤེས་པའི་ཐོག་ནས། ཨ་ནེ་ཁྲིད་ཡ་དེ་གལ་ཆེན་པོ་ཞེ་དྲག་རེད།།

05:31བསྟན་པ་སྤྱི་མཚན་དབང་དུ་བྱས་པ་ཡིན་ན། དཔལ་ནཱ་ལེདྲནའི་མཁས་པ་ཚོས་སངས་རྒྱས་ཀྱི་བསྟན་པ།།

05:36འཛིན་སྐྱོང་སྤེལ་གསུམ་གནང་སྟངས་དེ།བསྟན་པ་སྤྱི་མཚན་གི་དབང་དུ་བྱས་ནས་ཁྲིད་སྟངས་དེ་ཪེད།།

05:39ད་བྱས་ན་འདིར་གཅིག་གཟིགས་ཤོག་ཨ། འེ་་་འེ་་་འེ། འེ་འདིའི་དེ་འདྲའི་གཅིག་འདུག་ག

05:46འེ་འེ། རྗེ་ཪིན་པོ་ཆེ་ཡིས་འ་ད་དེ་ཡང་རྗེ་བཙུན་ཙོང་ཁ་པས་སེ།།

05:50གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་མི་ལྡན་ན། །ངེས་འབྱུང་བྱང་ཆུབ་སེམས་ལ་གོམས་བྱས་ཀྱང༌། །སྲིད་པའི་རྩ་བ་གཅོདཔར་མི་ནུས་པས། །

05:56དེ་ཕྱིར་རྟེན་འབྲེལ་རྟོགས་པའི་ཐབས་ལ་འབད།། ཟེར་ཡ་ལུང་དེ་དྲངས་གནང་ནས། ཐ་གང་ལྟར་ཨ་ནི་ཆོས་རབ་ཏུ་རྣམ་འབྱེད་ཀྱི་ཤེས་རབ་འདི།

06:04ཨ་ནེ།འེ་ད་ག་འདྲའི་གཅིག་ཞུ་དགོས་རེད། ། དཔེར་ན། ད་གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་རེད་བ།

06:10གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ།ད་རང་སྐད་ཆ་བྱུང་བ་ནང་བཞིན་གྱིས་།།

06:12ཨེ་ནི་རྟེན་འབྱུང་གི་དེ་ཁོ་ན་ཉིད་ངེས་པའི་ཤེས་རབ་འདི་མེད་པ་ལ།།

06:16ཨ་ནེ་འེ་ཐར་པ་ཐོབ་ཐུབ་ཡ་ཡོད་མ་རེད།ཐར་པ་ཙམ་ཡང་ཐོབ་ཐུབ་ཡ་ཡོད་མ་རེད།།

06:20དེས་འདྲ་ཡིན་པ་ཡིན་དུས་ཙ་ནས། ཨ་ནེ། འེ་གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་འདི་མེད་ཐབས་མེད་བསྡད་པ་རེད་ཟེར་དེ་གསུང་པ་རེད།

06:28རེད་བ། ད་འེ་འེ། ད་གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་འདི།

06:35ཨ་ནེ་འེ་སྤྱིར་ཨ་ནེ།ག་རེ་ཟེར་བ་རེད། དཔེར་ན། འེ་འེ་ཨ་རང་སྡེ་གྲུབ་མཐའ་སྨྲ་བ་ཚང་མ་ལོག་གིས་ཕལ་ཆེར།

06:43གནས་ལུགས་རྟོགས་པའི་ཤེས་རབ་ཟེར་ཡ་གཅིགགསུང་གསུང་གི་རེད༑

06:45བདག་མེད་པའི་ལྟ་བ་ཚང་མ་ལོག་གིས་གསུང་གི་ཡོད་རེད།།

06:47ད་ལྟ་བདག་མེད་པ་ཟེར་ཡ་འདི། ག་རེ་ཟེར་རེད། ཕ་གིའི་ཡིན་ལུགས་གཅིག་ཡིན་པ་རེད།།

06:52བྱསཙང་ག་ཡིན་ལུགས་སམ་གནས་ལུགས་ཤིག་ཆགས་ཀྱི་ཡོད་རེད།

06:55དེ་རྟོགས་པའི་ཤེས་རབ།འེ་གྲུབ་མཐའ་བཞི་ཀ་ལོག་གིས་ད་གསུང་གི་ཡོད་རེད།

06:58འེ་རེད་དེ་ཡིན་ནས།ད་སྐབས་འདིར་ཨ་ནེགནས་ལུགས་ག་འདྲས་གཅིག གནས་ལུགས་དེ་ཁོ་ན་ཉིད་གྱིས་གང་འདྲ་ཞིག་ལ་ཟེར་གྱི་ཡོད་རེད་ལབ་པ་ཡིན་ན།

07:05རྟེན་འབྱུང་གི་དེ་ཁོ་ན་ཉིད་ལ་ཟེར་གྱི་ཡོད་རེད་སེ།

07:09འེས་དེས་རྟེན་འབྱུང་གི་དེ་ཁོ་ན་ཉིད་ཟེར་བསྡད་ཡ་དེ།རྟེན་འབྱུང་དེ་རྟེན་འབྲེལ་ཕྲ་མོ། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱིས་གདགས་གཞི་ལ་བརྟེན་ནས།།

07:20ཨ་ནེ། རྟོག་པས་བཏགས་ཙམ། རྟོག་པས་བཏགས་པ་ལ་བརྟེན་ནས་གྲུབ་པ། རྟོག་པས་བཏགས་ཙམ་ལ་བརྟེན་ནས་ཡོད་པ།།

07:28དེ་འདྲའི་འདྲ་བའི་ད་རྟེན་འབྱུང་ཕྲ་མོ་འདི་དགོངས་པ་བཞེས་ནས། དེ་འདྲའི་འདྲ་བའི་རྟེན་འབྱུང་ཕྲ་མོ་འདི་ཡིས་ག་རེ་ཟེར་བ་རེད། ཕ་གིའི་ད་རྟེན་འབྱུང་འདི།
07:36རྒྱུ་མཚན་ལ་བཀོད་ནས། ཨ་ནེ། ངེས་ཡག་གི་གནས་ལུགས་གཅིག་ཡོད་རེད།།

07:41ད་གནས་ལུགས་དེ་གནས་ལུགས་ཕྲ་མོ་དེ་ཡིན་པ་རེད།།

07:42གནས་ལུགས་ཕྲ་ཤོས་དེ་ཆགས་བསྡད་ཡོད་རེད།གནས་ལུགས་ཕྲ་ཤོས་དེ།ཐ་དེས་ཕ་གིའི་འེ་འེ་གནས་ལུགས་དེ་ཤེས་དགོས་ཀི་རེད་ཟེར་གསུངས།

07:52ད་དེ་འདྲའི་རྟེན་འབྱུང་ཕྲ་མོ་དེ་ཨ་ནེ་ངེས་པ་ལ་ཡ། ལྟོས་ནས་བཏགས་པའི།

08:01སྤྱིར་ཨ་ནེ་ལྟོས་ནས་བཏགས་པའི། ག་རེ་ཟེར་རེད། ཕ་གིའི་ལྟོས་ནས་བསྒྲུབ་པའི་ཨ་ནེ་ལྟོས་ནས་བཏགས་པའི།

08:08རྟེན་འབྱུང་དེས་གཅིག་ངེས་དགོས་ཀྱི་ཡོད་རེད། འེ་བརྟེན་ནས་བཏགས་པའི་རྟེན་འབྱུང་དེའདི་ངེས་པ་ལ་ཡ།

08:14ཨ་ནེརྒྱུ་འབྲས་རྟེན་འབྱུང་གི་འེས་རྟེན་འབྲེལ་འདི་ངེས་དགོས་ཀྱི་ཡོད་རེད། རེད་བ། ད་ཐ་ཨ་དེ་འདྲ་ཡིན་དུས་ཙ་ནས།

08:23ད་གང་ལྟར་རྟེན་འབྲེལ་ཟེར་ཡ་འདི། ཕར་སྔོན་ལ་ཕྲ་མོ་དེ་ཤེས་པ་ལ་ཡ། དེའི་རགས་པ་དེ་ཤེས་དགོས་ཡ།

08:29དེའི་རགས་པ་དེ་ཤེས་དགོས་ཡ། དེའི་དེ་མར་སླེབ་ཡོང་དུས་ཕལ་ཆེར་དངོས་པོའི་གནས་ལུགས་དེའི་དེ་ཤེས་དགོས་ཡ།

08:36སྤྱིར་བཏང་གི་དངོས་པོའི་རང་བཞིན་དེ་གའི་དེ་ཤེས་དགོས་ཡ། ད་དེ་ཚོ་འབྲེས་སྦྲེལ་ཡོང་གི་ཡོདགདའ། ད་དངོས་པོའི

08:43གནས་ལུགས་མར་བཤད་ཡོང་དུས་ཙ་ནས། དེང་སང་དཔེར་ན། བཤད་ཚུ [...]

2023-04-05 17:48 UTC, Tenzindharten commented
༢༠ ཅན་དེ་རང་གིས་ཡག་པོ་བལྟས་ཏེ་གཙང་མ་ཞིག་ང་ལ་སྐུར་རོགས།

2023-04-11 01:42 UTC, Tenzindharten requested changes
00:00ཡ་ད་ཨིའི་སངས་རྒྱས་པའི་ད་ཆོས་སྤྱི་དང༌། ལྷག་པར་ཨེ་ནས་ཨིའི་ཐེག་པ་ཆེན་པོ།



00:08དཔལ་ནཱ་ལེན་ཏྲ་ནས་ད་བརྒྱུད་པའི་ཆོས་བརྒྱུད་འཛིན་མཁན་ཨིའི་ཁྱེད་རང་ཚོ་ཀོ་རི་ཡ།

00:16ཀོ་རི་ཡའི་ཆོས་གྲོགས་ཚོ་ཡིན་ནས་འདྲ། ང་ཚོ་བོད་པ་ཚོ་ཡིན་ནས་འདྲ། འོ་གང་ལྟར་ཨིའི་ཆོས་བརྒྱུད་དེའི་ཐོག་ནས།



00:24ད་ང་ཚོའི་ནམ་རྒྱུན་ནས་སྨོན་ལམ་རྒྱག་བསྡད་ཡག་དེ། ག་རེ་རེད་ཟེར་ལབ་ན། སེམས་ཅན་ཐམས་ཅད་ལ་བདེ་བ།



00:28ཐོབ་པ་གཅིག་ཡོང་བར་ཤོག སྡུག་བསྔལ་མཐའ་དག་བྲལ་བར་ཤོག་ཟེར་ཡག་གཅིག་དང། དེའི་ཆེད་དུ་ཨེ་ནས་རང་ཉིད།



00:35ཀྱིས་རྣམ་མཁྱེན་རྒྱལ་བའི་གོ་འཕང་ཐོབ་པར་ཤོག་བྱས་ནས་སྨོན་ལམ་རྒྱག་བསྡད་ཀི་ཡོད་རེད་། དེ་ལྟ་བུའི་སངས་རྒྱས་ཀྱི་གོ་འཕང་ཐོབ་ཡག་ཟེར་མཁན་དེ།



00:42ཨེ་ནས་ཤེས་རབ་སྙིང་པོའི་ནང་ལ་ཡ། ཨེ་ནས་ཨིའི་ཇི་སྐད་གསུངས་པ་ནང་བཞིན་གྱི།  ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཟེར་ཡག་དེ།



00:50ཨིའི་ཉམས་ཞིབ་གནང་ནང་ནས། ཨེ་ནས། དེ་ལ་བརྟེན་ནས་ད་སངས་རྒྱས་དགོས་ཡག་ཅིག་ཡིན་པ་རེད།



00:57ཨིའི་དེ་ཡང་ཨེ་ནས་འདས་པའི་སངས་རྒྱས་རྣམས་ཀྱང༌། ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཉམས་ཞིབ་གནང་ནས་སངས་རྒྱས་པ་རེད། ཨིའི་ད་ལྟ་སངས་རྒྱས་བཞིན་པ་ཚོས།

01:05ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལམ་ཉམས་ཞིབ་གནང་ནས་ད་སངས་རྒྱས་བཞིན་པ་ཡིན་པ་རེད།



01:12ང་རང་ཚོ་སངས་རྒྱས་གོ་འཕང་ཐོབ་པར་ཤོག་ཟེར་ནས། སྨོན་ལམ་རྒྱག་མཁན་ཚོ་ཡིས། མ་འོངས་པ་ལ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་ལམ་འདི་མཁོ་ན་ལ་བརྟེན་ནས། ཨེ་ནས་སངས་རྒྱས། སངས་རྒྱས་དགོས་ཡག་ཅིག་ཡིན་པ་རེད།



01:22འོ་ན་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ག་འདྲས་སེ་རེད་ལབ་ན། ཨིའི་སྤྱིར་ནས་ཨེ་ནས་ཨིའི་སྟོད་ཉིད་རྟོགས་པའི་ཤེས་རབ།



01:29ད་ལྟ་སྟོང་པ་ཉིད་བརྟེན་བྱུང་གྱི་དེ་ཁོ་ན་ཡིན་ཟེར་བསྡད་ཡག་གི་ད་སྟོད་ཉིད་ཕྲ་མོ་ཨིའི་རྟོགས་པའི་ཤེས་རབ་ཅིག



01:36 དེའི་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་ཨིའི་ཨིའི་ཙམ་མ་ཡིན་པ། ད་གང་ལྟར་ཟིན་བྱེད་ཀྱི་ཐབས་བྱང་ཆུབ་ཀྱི་སེམས་དང༌།



01:46དེས་ཀུན་ནས་བསླངས་པའི་སྦྱིན་སོགས་ཀྱི་ཐབས་ཀྱི་ཨེ་ནས་ཕྱོགས་དེ་གའི་དེ་གྲོགས་དང་བཅས་པ། དེ་འདྲས་དེ་ལ་ནམ་རྒྱུན་ད་ལྟ།



01:55རྣམ་ཀུན་མཆོག་ལྡན་གྱི་སྟོང་པ་ཉིད་ཟེར་གྱི་ཡོད་རེད། རྣམ་པ་ཀུན་གྱི་མཆོག་དང་ལྡན་པའི་སྟོང་པ་ཉིད་ཟེར་ཡག་ཨིའི།



02:00 མདོར་ན་ཨེ་ནས་དེ་འདྲའི་ལྟ་བུའི་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་དེ། རྣམ་མཁྱེན་སྒྲུབ་ཐུབ་ཡག་ཅིག་ཆགས་ཀི་ཡོད་རེད།



02:05དེ་འདྲས་ཡིན་དུས་རྣམ་མཁྱེན་ཐོབ་པའི་ཐབས་དཔེ་མ་ཚང་མེད་པ་གཅིག་ཆགས་ཡོང་བ་ཡིན་དུས་ཙ་ནས།



02:10རྣམ་པ་ཀུན་གྱི་མཆོག་དང་ལྡན་པའི་ཨེ་ནི་སྟོང་ཉིད་ཟེར་བྱས་ནས། རྣམ་ཀུན་གྱི་མཆོག་ལྡན་གྱི་སྟོང་ཉིད་ཟེར་བསྡད་ཡག འོ་ད་འདི་འདྲས་དེ།



02:16ད་ག་རེ་ཟེར་དགོས་རེད། ད་དེ་འདྲའི་གཅིག་ལ་ཟེར་ཀྱི་ཡོད་རེད་ད་ལྟ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་ཟེར་བསྡད་ཡག་འདི།



02:22དེ་ལྟར་ད་ཨིའི་རྣམ་པ་ཀུན་གྱི་མཆོག་དང་ལྡན་པའམ། ཨིའི་རྣམ་ཀུན་མཆོག་ལྡན་གྱི་ད་སྟོང་པ་ཉིད་དམ།



02:30ད་ཨེ་ནས་ཨིའི་ཕ་གིའི་བྱང་ཆུབ་ཀྱི་སེམས་ཀྱིས་ཟིན་པའི།



02:37ད་སྦྱིན་སོགས་ཀི་གྲོགས་དང་བཅས་པའི་ད་སྟོང་ཉིད་རྟོགས་པའི་ཤེས་རབ་ཁྱད་པར་ཅན་ཤེས་རབ་ཀྱི་ཕ་རོལ་དུ་ཕྱིན་པ་དེ་འདྲའི་གཅིག



02:44ད་ང་རང་ཚོའི་རྒྱུད་ལ་སྐྱེས་པ་ལ་ཡ། སྨོན་ལམ་བརྒྱབས་ནས་རྒྱུད་ལ་སྐྱེས་ཡག་མེད་པ་རེད།



02:49ཨིའི་ཡང་འདི་ག་ནང་བཞིན་གྱི་ཕ་གིའི་ད་ཨིའི་དད་པ་བྱས་ནས།



02:54ཨེ་ནས་སངས་རྒྱས་ཨིའི་སྲས་དང་བཅས་པ་རྣམས་ཀྱི་ཨིའི་བྱིན་རླབས་ཀྱི་ཐོག་ནས་ང་ཚོའི་རྒྱུད་ལ་སྐྱེས་ཡག་ཡོད་མ་རེད།



03:01རང་རང་སོ་སོས་དམིགས་རྣམ་བསྐྱངས་ནས། ད་དེ་དང་འབྲེལ་བའི་ཨེ་ནས་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཕྱིན་པ་ཟེར་ཡག་དེ་རྒྱུད་ལ་སྐྱེ་དགོས་ཀྱི་ཡོད་རེད།



03:08དེ་སྐྱེས་ཡག་དེ། འོ་ཁོ་དེ་གའི་དེ་དུས་གཅིག་ལ་སྐྱེ་ཡག་མེད་པ་རེད།



03:14ཨིའི་དཔེར་ན། ཕྱིའི་ཨེ་ནས་ཨིའི་དཔེར་ན་མེ་ཏོག་འདྲ་པོ་ཡིན་ནས་རེད། ཤིང་འབྲས་འདྲ་པོ་ཞིག་ཤིང་འབྲས་རེད་བ་fruitཡིན་ནས་རེད།





ཧཧཧ



03:23ཁོ་ད་ཨིའི་ལོ་མང་པོ་ཁོ་རིམ་པས་རིམ་པས་རིམ་པས་བྱས་ནས་སྔོན་ལ་ས་བོན་གཅིག་བཏབ།



03:30ས་བོན་ལས་ཁོ་སྐྱེ་རུང་གི་ནུས་པ་གཅིག་ཡོད་བསྡད་མཁན་གཅིག་བྱས།



03:34ཨིའི་དེ་འདྲའི་ས་བོན་དེ་ཨེ་ནས་རྐྱེན་མང་པོ་ཚོགས་པའི་སྟེང་ནས། ཨེ་ནས་དུས་ཡུན་ག་ལེར་ག་ལེར་ལ་ཡ།



03:41དུས་ཡུན་བསྲིངས་ནས་ཡོང་དུས། ཨེ་ནས་ཨིའི་ཐོག་མར་མྱུ་གུའི་གནས་སྐབས། དེ་ནས་ཡར་ག་ལེར་ག་ལེར་ཡར་ཨིའི་དཔེར་ན་ཤིང་འབྲས་ཀྱི་སྡོང་པོ་འདྲ་པོ་ཡིན་ནས་འདྲ།

03:49མེ་ཏོག་འདྲ་པོ་ཡིན་ནས།  དང་པོ་གཞི་ནས་ཡར་འཚར། དེ་ནས་ཨེ་ནས་མེ་ཏོག དེ་ནས་འབྲས་བུ



03:53ཁོ་དེ་གའི་དེ་ཡོང་དགོས་ཀྱི་འདུག་བ། འོ་དེ་ནང་བཞིན་ང་རང་ཚོའི་ནང་སེམས་ཀྱི་ཨེ་ནས་ཡོན་ཏན་ཟེར་ཡག་འདི་དེ་དེ་བཞིན་བྱས་ནས་ཐོག་མར་གཞི་རྩའི་ས་བོན་ཅིག



04:03ཨེ་ནས་དགོས་ཀྱི་ཡོད་རེད། ད་ས་བོན་དེ་མེད་ན་ཨེ་ནས་བྱེད་ཐབས་མེད་པ་རེད་དེ། ང་རང་ཚོའི་རྒྱུད་ལ་ཡ་ཨེ་ནས།



04:10ཨིའི་གསལ་རིག་ཟེར་ཡག་གི་ད་ད་ཡུལ་གསལ་ཡག་གི་ཨིའི་ནུས་པ་རང་ཆས་སུ་ཡོད་བསྡད་པའི་ཤེས་པ་ཟེར་ཡག་གཅིག་འདུག་ག



04:18དེ་ཡིས་ཨེ་ནས་ཆོས་རྣམས་ཀྱི་ཡིན་ལུགས་ཤེས་པ་དང༌། མཐར་ཐུག་ཨེ་ནས།



04:24ཨིའི་ཇི་ལྟ་ཇི་ཉིད་ཀྱི་ཆོས་ཀུན་ཤེས་ཐུབ་ཡག་ཅིག་གི་ཨིའི་ཁོ་ནུས་པ་འདྲ་པོ་ཁོ།



04:30གང་ལྟར་གསལ་རིག་དེའི་སྒང་ནས་ཡོད་པ་རེད། ད་ཡུན་རིག་པ་ལ་ཁོ་སྒྲིབ་བྱེད་དང་བྲལ་སོང་ན།



04:37ཁོ་ཡུན་རིག་ཡག་གི་ནུས་པ་གསར་དུ་བསྒྲུབ་མི་དགོས་པ་ཁོ་རང་ཆས་སུ་ཡོད་པ་ཡིན་པ་རེད།



04:40དེ་ག་ནང་བཞིན་གྱི་ཕ་གིའི་ང་རང་ཚོ་བརྩེ་བའི་བསམ་པ་ཟེར་ཡག་དེ། སྲོག་ཆགས་གྲོག་འབུ་ཚུན་ཆད་ལོག་ལ་ཡ་གཅིག་བརྩེ་བའི་བསམ་པ་གཅིག་ཡོད་བསྡད་ཡོད་རེད།

04:49ཆུང་ཆུང་ཞེ་བོ་གཅིག་རེད། རྒྱ་ཆུང་ཆུང་ཞེ་བོ་གཅིག་རེད་དེ། ཡིན་ནས་དེ་འདྲའི་འདྲ་བའི་ད་བརྩེ་བའི་བསམ་པ་ཟེར་མཁན་ཁོ་ས་བོན་ང་རང་ཚོའི་རྒྱུད་ལ་ཡོད་ཡོད་པ་བྱས།

04:57སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས། ཡུན་རིག་ཡག་གི་ཨིའི་ས་བོན་འདྲ་པོ་ནུས་པ་འདྲ་པོ་གཅིག་རང་ཆས་སུ་ཡོད་བསྡད་པ།



05:04ད་ག་ནང་བཞིན་གི་ཨིའི་ཕལ་ཆེར་དེས་ལབ་ཆོག་གི་མིན་འགྲོ། ངའོ་སྙམ་པའི་བློ་གཅིག་ཡོད་ཕྱིན་ཆད་ལ་ཡ། 



05:09བརྩེ་བ་ཟེར་ཡག་གཅིག་འདིའི་སྒང་དེར་ཕལ་ཆེར་ཡོད་རེད། སོ་དེ་འདྲས་ཡིན་དུས་ས་བོན་ཡོད་ཡོད་པ་བྱས།



05:15 ད་ག་རེ་བྱེད་དགོས་རེད་ཟེར་ལབ་ན། ཨིའི་གཅིག་ཡུན་རིག་ཡག་གི་ནུས་པ་རང་ཆས་སུ་ཡོད་བསྡད་པ་དེའི་སྟེང་ལ་ཡ།



05:22ད་ཡུན་གྱི་གནས་ལུགས་ག་འདྲའི་ཡིན་པ་དེ། ཨེ་ནས་ཕར་ཤེས་པར་བྱས་ནས། འོ་དེ་གའི་དེ་རྦད་ཞིབ་འཇུག་བྱེད། རྩད་གཅོད་བྱེད།



05:31 ཨིའི་བསམ་བློ་བཏང་། འདུག་སེ་བྱས་ནས། ཨེ་ནས་འེ་ཡུན་གྱི་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི་གནས་ལུགས་རིག་ཡག་གི་བློ་ཁོ།



05:39ཨེ་ནས་ཕར་ཨིའི་རྒྱ་འདྲ་པོ་བསྐྱེད་ནས་ཁོ་ཕ་གིའི་ནུས་པ་འདྲ་པོ། ད་རིམ་པས་རིམ་པས་ཆེ་རུ་གཏོང་དགོས་ཡག་དེ་འདྲས་ཡིན༌པ་རེད།



05:46ད་ག་ནང་བཞིན་གྱི་སྙིང་རྗེ་བསམ་པ་གཅིག  བརྩེ་བའི་བསམ་པ་ཟེར་ཡག་གི་ས་བོན་འདྲ་པོ་ཆུང་ཆུང་གཅིག་ཡོད་བསྡད་པ་དེ་ལ་ཡ། ཨེ་ནས་དེ་དང་དུ་བླངས།



05:53དེ་ལ་ཡོན་ཏན་དུ་ལྟས་ནས། ཨེ་ནས་དེ་གོང་ནས་གོང་དུ་སྤེལ་ཡག



05:57དེའི་འགལ་ཟླ་ཡིན་བསྡད་མཁན་གྱི་ཞེ་སྡང་ལ་སོགས་པ། ཕྲག་དོག་ལ་སོགས་པ།



06:03དེ་ཚོའི་གྲས་དེ་ཇེ་ཉུང་ཇེ་ཉུང་། དེའི་ཉེས་དམིགས་སུ་བལྟས་ནས་ཇེ་ཉུང་ཇེ་ཉུང་ལ་བཏང་ནས་འདུག་སེ་བྱས་ནས་གོམས་པ་བསྟེན་པ་ཡིན་ན།



06:11རིམ་པས་རིམ་པས་ཀྱི་ཨེ་ནས་ཁོ་བློ་འདི་འདུས་བྱས་སོགས་ལ་མི་གནས་པ་ཡིན་དུས་ཙ་ནས། ཁོ་རིམ་པས་རིམ་པས་ཀྱིས་འགྱུར་བ་ཐེབས་ཐུབ་ཡག་ཅིག



06:18ང་རང་ཚོ་དཔེར་ན་ཨིའི་མཐོང་ཆོས་ལ་ཆ་བཞག་ནས། གཅིག་ཚེ་སྟོད་ཀྱི་བསམ་བློ་དེ་ཚེ་སྨད་ལ་མི་འདྲ་བ་གཅིག་ང་ཚོས་མཐོང་ཐུབ་ཡག་འདུག་ག



06:25ཉི་མ་གཅིག་གཉིས་ཀྱི་ནང་ལོག་ལ་ད་འགྱུར་བ་ཐེབས་ཡ་འེ་ཁག་པོ་ཞེ་དྲག་རེད། མཐོང་ཡ་མི་འདུག་སྟེ། ཡིན་ནས་ལོ་དང་ཟླ་བ་མང་པོ།



06:34ཕྱིན་པའི་སྐབས། རྗེས་ལ་ཡ་བློ་ལ་འགྱུར་བ་འགྲོ་ཡི་ཡོད་བསྡད་པ་དེ་དངོས་སུ་ད་ཉམས་སུ་མྱོང་ཡག་འདུག་ག



06:40སོ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས་ད་ཡ་གིའི་ཨིའི་ག་རེ་ཟེར་བ་རེད།  རྣམ་མཁྱེན་ཐོབ་ཡག་གི་ད་འོ་ཐབས་



06:48 མདོར་ན། དཔེ་རྣམ་ཀུན་མཆོག་ལྡན་གྱི་སྟོང་པ་ཉིད་ཟེར་ནས་ཟེར་ཡག་འདི་ཁོ་རིམ་པས་རིམ་པས།



06:55གཞི་རྩ་གཅིག་ཡོད་པ་འདིའི་ཐོག་ནས་ཨེ་ནས་རིམ་པས་རིམ་པས་ཡར་གོམས་བྱས།



06:58ཨེ་ནས་གོམས་པ་རབ་ཀྱིས་མཐར་ཕྱིན་པའི་གནས་སྐབས་ལ་ཡ། ཨེ་ནས་རྣམ་མཁྱེན་ཟེར་ཡག་དེ་ཆགས་བ་ཡིན་པ་རེད།



07:03ད་དེ་ལྟ་བུའི་གཅིག་ལམ་ཉམས་སུ་ལེན་ཡག ཨེ་ནས།



07:09ཁོ་ག་རེ་ཟེར་བ་རེད། ཉམས་སུ་ལེན་པ་ལ་ཡ་ཉམས་སུ་ལེན་ལུགས་ཤེས་དགོས་པ་རེད།



07:13དེ་འདྲའི་འདྲ་བུའི་ད་ཉམས་ལེན་སྟོན་པའི་གཞུང་ད་མཆོག་ཏུ་གྱུར་པ་ཞི་བ་ལྷའི་ད་སྤྱོད་འཇུག་གི་གཞུང་འདི་མཆོག་དུ་འགྱུར་པ་གཅིག་ཆགས་བསྡད་ཡོད་རེད།

07:20ད་དེའི་ཨིའི་བསམ་གཏན་གྱི་ལེའུ་ཡན་ཆད་དེ་གའི་དེའི་འེ་རྒྱ་ཆེ་བའི་ལམ་རིམ་གྱི་སྐོར་དེ་གསུངས།



07:27ད་ད་ལྟ་ཤེས་རབ་ལེའུ་དེའི་འེ་ཟབ་མོས་ལམ་གྱི་རིམ་པ་དེ་གསུངས་གི་ཡོད་རེད།



07:31ད་དེའི་ཡན་ལག་ལ་ཡ། ཨེ་ནས་གྲུབ་མཐའ་མ་འཁྲིད་ཡས་ཀྱི་ད་ཁ་སང་མཚམས་འདི་ཡིན་ད།



07:36འོ་ཡ་དེ་གང་འདྲ་རེད་དེ་རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་བས་གཞལ་ནས།



07:43རྟག་དཔྱད་ཀྱི་མཐའ་གཉིས་ཀར་ལྟུང་ཡང་ཟེར་ཡག་དེ། དེ་ཨེ་ནས་ཨིའི་དཔེར་ན།



07:50རང་རྒྱུད་པ་རྟག་མཐར་ལྷུང་བ་གསལ་བོར་བྱས། རེད་བ།



07:54ད་དཔེར་ན་རང་རྒྱུད་པ་ཕྱི་དོན་ཞལ་གྱིས་མི་བཞེད་པར་ཆ་བཞག་པ་ཡིན་ན། ཕལ་ཆེར་ཕྱི་དོན་ལ་སྐུར་བ་འདེབས་པ་བཟོ་རེ་འདྲ་གཅིག་བཤད་པ་ཡིན་ན་བཤད་ཆོག་ཀྱི་རེད་བ།

08:03ད་ཕྱི་དོན་བཞེད་མཁན་གྱི་རང་རྒྱུད་པ་དེ་ཆད་ལྟ་ཡིན་པའི་སྒྲུབ་བྱེད་ག་རེ་བཤད་དགོས་རེད།



08:07ཐ་སྙད། སྣང་ཕྱོགས། རྟེན་འབྱུང་ཕྲ་མོ་ད་འདི་ད་འདོད་ཀི་མ་རེད་པ།



08:17ད་རྟེན་འབྱུང་ཕྲ་མོ་རྟེན་འབྱུང་ཕྲ་མོ་བཞག་ཀ་ཕྱིན་པ་ཡིན་ན། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་རྟེན་འབྱུང་བཞག་ཀ་ཕྱིན་པ་ཡིན་ན་ད་འདི་ཆད་མཐའ་ལྟ་ཀི་རེད་བ།

08:24རང་རྒྱུད་པས་རེད་བ་འདི་འདྲ་གཅིག་སྒང་ལ་བཤད་དགོས་རེད་གཞན་ག་རེ་བཤད་དགོས་རེད་དེ་མིན་གང་ཞིག་བཤད་དགོས་རེད་ད།



08:29འོ་རེད་བ་བྱས་ཙང་ཁོ་བྱས་པ་འདྲ་བོ་རེད་རེད་བས།



08:36བྱས་ཙང་ཁ་འེ་ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱིས་བཞེད་པའི་ཆ་ནས། མདངས་ལྟར་ལྷུང།



08:43ད་ཐ་སྙད་དུ་རང་མཚན་ཞལ་གྱི་བཞེད་པའི་ཡིན་དུས་ཙ་ནས་ཐ་སྙད་དུ་མིང་རྐྱང་བཏགས་ཡོ [...]

2023-05-29 11:30 UTC, closed without merging