stt001-02
MonlamAI/STT001 pull request #8
Opened 2023-01-24 09:34 UTC by tsultrim-dolma

complete commit

2023-02-06 12:19 UTC, ngawangtrinley requested changes
1. བར་མཚམས་བཅོད་སྟངས་འགྲིག་མི་འདུག དེ་དང་ལདྲ་པོ་མང་ཙམ་འདུག ཞུ་དག་གཏོང་རོགས།
> 07:18ལུས་པོའི་དཀའ་ངལ་ཟིལ་གྱིས་གནོན་ཐུབ་ཀྱི་འདུག་ག ལུས་པོའི་ཅིག་དཔེར་ན་ཅིག དཔེར་ན་ང་རང་ཚོའི་ཅིག་སོ་སོ་ཆབ་སྲིད་ཀྱི་དམིགས་ཡུལ་འདྲ་བོ།
> 07:18ལུས་པོའི་དཀའ་ངལ་ཟིལ་གྱིས་གནོན་ཐུབ་ཀྱི་འདུག་ག **ལུས་པོའི། ཅིག དཔེར་ན་ཅིག དཔེར་ན་ང་རང་ཚོའི། ཅིག** སོ་སོ་ཆབ་སྲིད་ཀྱི་དམིགས་ཡུལ་འདྲ་བོ།

2023-03-30 05:15 UTC, Tenzindharten requested changes
༡.00:00 ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་གི་སྐད་ཆ་བཤད་ཡོང་དུས་ཙ་ནས། (ཨི་)ཆོས་ལུགས་དང་འབྲེལ་བ་(སླེབ་ཀི་)[སླེབས་ཀྱི་]ཡོད་རེད། [ཁོང་གི་གསུང་སྐད་ཀྱི་འགྲོས་བཞིན་སྒྲ་ལ་འབེབ་དགོས་པ་རེད། སྐབས་རེ་བརྡ་སྤྲོད་དང་མི་མཐུན་པ་དེའང་ཡོད་ངེས།]

༢. 00:09 འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་ཡ། (ད་ཨི། ད་ལོ་ཕ་གིའི་)སྟོང་ཕྲག་ཁ་ཤས་[ཀྱི་]རིང་ལ་ཡ། གང་ལྟར་མིའི་སྤྱི་ཚོགས་ནང་ལོག་ལ་ཆོས་ཟེར་ཡག་(ཅིག་)[ཞིག་]བྱུང་ཡིན་པ་རེད། 

༣.  00:19 (ཨི་)ད་ཆོས་རིགས་ཁ་ཤས་ཨི་ཞེ་དྲག་དེ་སེ་གལ་ཡོད་མ་རེད། (ད་གཅིག)[་ཅིག་གི]་ཨི་ད་ཨི་)ཉི་མ་(གསོལ)[སོལ་]ཡག་གི་བཟོ་འདྲ་བོ། 

༤. 00:27[ ཅིག་](གཅིག་)དེ་བ་(གཅིག་ཨེ་ནི་)[ཅིག་གི་]ཨི་ག་རེ་ཟེར་བ་[དགོས་]རེད། ཕ་གི་(གིའི་)མེ་མེ་མེ་ལ་ཡ་ད་གཅིག[་གི]ད་ག་རེ་ཟེར་བ་[དགོས་]རེད་རྩ་ཆེན་པོ་བརྩི་ཡག[་གི]་བཟོ་འདྲ་བོ།

༥. 00:36 ད་དེ་འདྲའི་མི་འདུག་སྟེ། [ནས་མར་རེད་ཨ་]ཨེ་ནི་གཅིག་[གི]་ད་ལྷ་ཡོད་རེད། ཀླུ་ཡོད་རེད་ཟེར་ཡག་འདྲ་བོ་བཤད་བྱས་དེ་འདྲའི་[ཡི་]ཐོག་ནས། གཅིག་དད་པ་བྱེད་[བྱས་]་བསྡད་ཡག་འདྲ་བོ་གཅིག་ཡོང་བསྡད་ཀི་[ཀྱི་]འདུག་ག

༦. 00:45 ད་དེ་གའི་དེ་[རྒྱས་]ལ་[ནི](་ཁོའི་)ལྟ་གྲུབ་ཟེར་གལ་མི་འདུག་ག གྲུབ་མཐའ་ཟེར་གལ་བཤད་ཡག་མི་གདུག་ག

༧. 00:49ད་ཨི་ད་གྲུབ་མཐའ་ཡོད་བསྡད་པའི་ཆོས་ལུགས་དེ་གའི་[རྒྱས་]དེ། ཕལ་ཆེར་རྒྱ་གར་ནང་ལ་ཆ་བཞག་ན་ཕལ་ཆེར་ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་ཕྱིན་པ་མིན་འགྲོ། 

༨. 00:58 ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་[ཀྱི་]མཚམས་ནས་[ཨ་]ཨེ་ནི་ད་ལྟ་གྲུབ་[ཅེས་བྱས་]བཤད་ནས་དེའི་ཐོག་ནས་ཨི་ད་ཆོས་ཀྱི་ཨི་ག་རེ་ཟེར་བ་[དགོས་]རེད་ཕ་གིའི།

༩.  01:08ད་ཆོས་དད་ཅིག་བཤད་ཡོང་གིན་[གི]་ཡོད་རེད།

༡༠. 01:10ཨི་བྱས་[ནི་]ནས་དེ་འདྲའི[་ཡི་]ད་ལྟ་གྲུབ་ཡོད་བསྡད་མཁན་གྱི་ཕལ་ཆེར་ཆོས་ལུགས་གཙོ་ཆེ་བ་དེ་[རྒྱས]་གའི་དེ།

༡༡.  01:19ད་རྒྱ་གར་ནང་གི་[གྱི་]ཆོས་ལུགས་[ལ་]ཆ་བཞག་[ནའི]་ནས་འདྲ། [ཨ་]ཨེ་ནི་ཨི་རིམ་པས་[པའི་]གཅིག་[ཅིག་]གི་ཨི་ད་དཔེར་ན་འཇིའུ་ལ་ཆ་བཞག་ནས།

༡༢. 01:28འཇིའུ་སྡེ་ཟེའི་[ཆོད་ལུགས་ལ་]ཆ་བཞག་ནས་འདྲ། [ཨ་]ཨེ་ནི་ཡེ་ཤུ་ཡིན་ནས་རེད། ཁ་ཆེ་ཡིན་ནས་རེད། གཅིག་[གི་]ད་ཨ་ག་རེ་ཡོད་རེད་[ཨ་]ཨེ་ནི།

༡༣. 01:38ད་དེ་ལ་སོགས་པའི་གང་ལྟར་དེ་ལ་སོགས་པའི་ད་གཅིག་གྲུབ་མཐའ་ཡོད་བསྡད་མཁན་གྱི་ཆོས་ལུགས་དེ་གའི་[རྒྱས་]དེ་ཚང་མ་ལོག[་གི་]གིས་བསླབ་བྱ་[རྒྱབ་]རྒྱག་ཡག་དེ། [ཨ]ཨེ་ནི་མི་སེམས་པ་བཟང་པོ་བྱེད་དགོས་རེད། བྱམས་པ་དགོས་རེད། 

༡༤.    01:48 བརྩེ་བ་དགོས་རེད་ཟེར་ཡག་དེ་བཟོད་པ་དགོས་རེད། ཆོག་ཤེས་དགོས་རེད། ཨེ་[ཨ་]ནི་རང་རང་གི༌ཕི་གིའི་བསླབ་པ་སྲུང་དགོས་ཀྱིརེད།

༡༥. 01:56རང་རང་གི་ཆོས་ལུགས་ནས་བཤད་ཞག་པའི་བསླབ་པ་སྲུང་དགོས་ཀི་[ཀྱི་]རེད་ཟེར་བྱས་ནས་བཤད་བསྡད་མཁན་གཅིག་ཚང་མ་གཅིག་པ་རེད་འདུག་ག  (སེ)་དེ་འདྲས་[འདྲ་]ཡིན་དུས་ཆོས་ལུགས་ཁག་དེ་གའི་[རྒྱས་]དེ་ཡིས་སྙིང་པོ་ག་རེ་བཤད་[ཀྱི་]ཀི་ཡོད་རེད་ཟེར་ལབ་ན།

༡༦. 02:06མི་ལ་ལྷན་སྐྱེས་[ཀྱི]་ཀི་ཡོད་བསྡད་པ་དང་། ལྷན་སྐྱེས་ཀི་[ཀྱི་]ཡོད་བསྡད་པའི་ཐོག་ལ་མི་ལ་དགོས་མཁོ་ཡོད་བསྡད་པའི་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གལ་ཆེན་པོ་ཡིན་པ་གཅིག་ཆོས་ལུགས་ཚང་མས་བཤད་[ཀྱི]་ཀི་འདུག་ག 

༡༧. 02:15ད་བྱམས་པ་དང་བརྩེ་བ་ཨ་སྒྲུབ་སྟངས་དེ་ལ་[ཨ་]ཨེ་ནི་ཨི་ཐབས་ཤེས་མི་འདྲ་བ་བྱས་ཀྱིས།[ཅས།]

༡༨. 02:25རིགས་གཅིག་གིས་འཇིག་རྟེན་བཀོད་པ་པོ་ཡོད་རེད་ཟེར་བྱས་ནི། འཇིག་རྟེན་བཀོད་པ་པོ་དེ་བརྩེ་བའི་བདག་ཉིད་རེད། མཁྱེན་པའི་བདག་ཉིད་རེད། ཇི་ཙམ། དེ་འདྲས་[འདྲ་]ཡིན་དུས་ཙ་ནས།

༡༩.  02:34འཇིག་རྟེན་བཀོད་པ་ལ་ང་ཚོས་བརྩེ་བ་བྱེད་དགོས་རེད། དད་པ་བྱེད་དགོས་རེད། གུས་པ་བྱེད་དགོས་རེད། ཇི་ཙམ་གྱིས་འཇིག་རྟེན་བཀོད་པ་པོ་ལ་ཡ། དད་པ་དང་བརྩེ་བ་དང་གུས་བྱས་པ་དེའི་ཚོད་ཀྱིས།

༢༠.   02:43རང་ཉིད་ཀིས་[་ཀྱིཨ་]ཨེ་ནི་གཅིག་དད་པ་དང་། གཅིག་བརྩེ་བ་ཟེར་ཡག་དེ་ཚོའི་གྲས། རང་ཉིད་ཀྱིས་ད་ཉམས་ལེན་བྱེད་དགོས་ཡག་ཅིག་དང་།

༢༡. 02:49ཨ་]ཨེ་ནི་འཇིག་རྟེན་བཀོད་པ་པོ་གཅིག་གིས་བཀོད་བཞག་པའི་ང་རང་ཚོ་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་[ཨ་]ཨེ་ནི་གཅིག་བརྩེ་བ་བྱེད་དགོས་རེད་ཟེར་ཡག་ཅིག

༢༢.  02:56དཔེར་ན་ད་ལྟ་འདིའི་[འདི]་མུ་སི་ལིམ་ད་ལྟ་འདི་ཀོ་རན་ནང་ལོག་ལས་[ལའི་]འདི་འདྲ་(འདྲས)་བཤད་ཀིས་[ཀྱི།་དེ་འདྲ་]བཤད་[ཀྱི་]ཀི་ཡོད་པ་རེད།

༢༣.  03:03ངས་ད་ལྟ་ཁ་ཆེ་ངོ་ཤེས་པ་གཅིག་[ཅིག་ལ་]སྐད་ཆ་བྱུང་།  ཁ་ཆེ་བླ་མ་གཅིག་སྐད་ཆ་[འདྲ་བོ་]བྱུང་[ཨ་]ཨེ་ནི་ཀོ་རན་ནང་ལོག་ལ་ཡ་[ཨ་]ཨེ་ནི།

༢༤.  03:10འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པའི་ད་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་ང་ཚོ་བྱམས་བརྩེ་བྱེད་དགོས་རེད་ཟེར་བྱས་ནས་[ནི་]དེ་འདྲ་ཡོད་རེད་སེ།[་ཟ།]

༢༥.  03:20སེ་དེ་འདྲས་[འདྲ་]ཡིན་དུས་ཙ་ནས། སྒྲུབ་བྱེད་འདི་འཇིག་རྟེན་བཀོད་པ[་པོས་]ཡིས་བཀོད་ནས། འཇིག་རྟེན་བཀོད་པ་པོ་ཟེར་ཡག འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པ་རེད་ཟེར་ཡག་དེ། སྒྲུབ་བྱེད་དེ་[འདྲ་]འདྲའི་གཅིག་[ཞིག་འགོད་]བཀོད་ཀི་[ཀྱི་]ཡོདརེད། 

༢༦. 03:29བཀོད་པའི་གྲུབ་དོན་སྙིང་པོ་འདྲ་བོ་དེ། ཨི་བྱམས་པ་དང་བརྩེ་བ་དང་དེ་ཚོ་དགོས་ཀི་རེད་ཟེར་ཡག་ཅིག

༢༧. 03:34ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གཅིག་པོ་ཡིས་[པུས་]འདང་གི་ཡོད་མ་རེད། ང་ཚོ་ད་ག་རེ་བྱས་ནས་ཡང་མི་མཐུན་པ་དང༌། འཁྲུག་པ་[རྒྱབ་]རྒྱག་ཡག་[འདྲ་བོ་]ཡོང་གིན་[གི]་ཡོད་པ་ཡིན་དུས། [ཨ་]ཨེ་ནི་བཟོད་པ་དགོས་རེད།

༢༨. 03:44ཨི་གཅིག་ག་རེ་ཟེར་བ་རེད། [དགོས་རེད་]ཕ་གིའི་[ཨ་]ཨེ་ནི་ཆོག་ཤེས་དགོས་རེད་ཟེར་ཡག་དེ་ཚོའི་གྲས་ཀྱི[་སླབས་]བསླབ་བྱ་དེ་སླེབ་ཡོང་གིན་འདུག་ག སྙིང་པོ་སྙིང་པོ་དེ་བྱམས་བརྩེའི་སྒང་ལ་ཡ་སྐད་ཆ་བཤད་ཀི་ཡོད་རེད་བ་[པ]།



༢༠༢༣་༠༣་༣༠ ཞོགས་པ་བཅོས། 

གསལ་བཤད། () གུག་རྟགས་འདི་ཅན་ནི་ཁ་གསབ་དང་ནོར་བའི་འཚབ་མཚོན་དུ་བཅོས་པ་རྣམས་རེད། [] གུག་རྟགས་འདི་ཅན་ནི་དག་ནོར་རིགས་དང་ཡང་གསུང་གི་སྒྲ་དང་ཏག་ཏག་མཐུན་མེད་པས་གསུབ་དགོས་པའི་རིགས་ཡིན་པས་ཞིབ་གཟིགས་གནང་རོགས་ཞུ། རིམ་གྱིས་ལྟ་བཞིན་བསྐུར་ཡོང་གི་ཡིན། ཁྱེད་རང་གིས་འདི་བསྐྱར་དུ་ང་ལ་ཚུར་སྐུར་སྐབས། མཐའ་མར་ཚེས་གྲངས་བྲིས་ཏེ་བསྐུར་ཡོང་རོགས།

2023-03-30 09:00 UTC, Tenzindharten requested changes
1. 03:52(སེ་)དེ་འདྲས་(འདྲ)་ཡིན་པ་ཡིན་དུས་ཙ་ནས། ད་ལྟ་དུས་རབས་ཉི་ཤུ་[བརྩ་]རྩ་གཅིག་པ་གཅིག་ཚན་རིག་ཡར་རྒྱས་ཧ་ཅང་ད་ཚད་མཐོན་པོ་སླེབས་བསྡད་པ། [ཡོད་པ།]
2. 04:01[ཅིག]་གཅིག་དངོས་པོ་ཡར་རྒྱས་སྤྱིར་བཏང་བཤད་པ་ཡིན་ན། ཧ་ཅང་གི་[གེ་]ད་ཚད་མཐོ་པོ་སླེབས་བསྡད་པའི་དུས་རབས་འདིའི་ནང་ལ་ཡིན་ནས། [ནའི་]འཛམ་གླིང་ཤར་ནུབ་ག་ས་ག་ལ་ཡ་ཆོས་ལ་ཡ་དོ་སྣང་བྱེད་མཁན་གཅིག [ཅིག]
3.  04:12འཛམ་བུ་གླིང་འདིའི་སྒང་གི་མི་མང་བ་དེ་གའི་[རྒྱས་]དེ། ཆོས་ལ་དད་པ[་ཅིག་](ཅང་)[ཨ་]ཡོད་མེད་མི་ཤེས་ཏེ། [ཏས]་ད་གང་ལྟར་ཆོས་ལ་དད་པ་བྱེད་མཁན་འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་མང་པོ་གཅིག་དུས་ད་ལྟ་ཡིན་ནས་[ནའི་]ཡོད་བསྡད་པ་རེད།
4. 04:21དེ་ཁྲལ་དང་ཁྲིམས་ཀྱི་ཐོག་ནས་བཟོས་པ་གས་[གའི]་མ་རེད། རང་བཞིན་གྱིས་མི་ལ་ཡ་ཁོ་ཕན་ཐོགས་གཅིག་ཡོད་བསྡད་པ་གཅིག་དང་། ཁོ་དགོས་མཁོ་ཡོད་བསྡད་པ་[ཅིག་]གཅིག་མཐོང་བ་ཡིན་དུས་ཙ་ནས།
5. 04:29མི་རིགས་གཅིག་གིས་ཆོས་ལ་ཡ་དོ་སྣང་བྱས་བསྡད་ཡག་ཅིག་ཆགས་བསྡད་ཀི་[ཀྱི]་ཡོད་རེད་བ། དེ་[འདྲ་]འདྲས་ཡིན་དུས་ཙ་ནས།
6. 04:34སྙིང་པོ་འདི་དངོས་པོ་ཡར་རྒྱས[་ཀྱི་]ཀྱིས་ལུས་པོ་བདེ་ཐང་བཟོ་ཡི་ཡོད་རེད། ལུས་པོའི་གཅིག་ཕ་གིའི།
7. 04:43ཚོར་བ་བདེ་སྐྱིད་ཡོང་ཡག་གི་གང་ལྟར་ཆ་རྐྱེན་དེ་གའི་དེ་[རྒྱས]དངོས་པོ་ཡར་རྒྱས་ཀྱི་ཐོག་ནས་སྒྲུབ་བསྡད་ཀི་[ཀྱི་]ཡོད་རེད། ངེས་པར་དུ་དགོས་[ཀྱི་]ཀི་ཡོད་རེད། ཨི་[དེ་]ད་ག་ནང་བཞིན་གྱི་
8. 04:52ལུས་པོའི་བདེ་ཐང་གཅིག་པོ་ཡིས་ང་ཚོར་འདང་གི་ཡོད་མ་རེད། ག་རེ་ཟེར་ལབ་ན་ནང་རྣམ་པར་རྟོག་པའི་རྐྱེན་པས་ཡང་དགའ་སྡུག་མང་པོ་ཞིག་ཡོང་གི་ཡོད་རེད། 
9. 05:01དེ་འདྲ་དེ་རྣམ་པར་རྟོག་པ་ཁོ་རང་གི་ཐོག་ནས་ཐབས་ཤེས་ཤིག་བཙལ་ནས།[ཏེ།] 
10. 05:07རྣམ་རྟོག་གི་[ཨ་]ཨེ་ནི་ཐོག་ནས་གཅིག་དགའ་པོ་ཡོང་བསྡད་ཡག རྣམ་རྟོག་གི་ཐོག་ནས་མི་དགེ་བ་ཡོང་བསྡད་ཡག་དེ་ལ། རྣམ་རྟོག་ཁོ་རང་གི་ཐོག་ནས།
11. 05:17དགའ་སྡུག་གི་ག་རེ་ཟེར་བ་རེད། [དགོས་རེད་]ཕ་གིའི་ག་རེ་ཟེར་བ་[དགོས་]རེད། ད་དགའ་སྡུག་གི་རྒྱུ་རྐྱེན་གཅིག་རྣམ་རྟོག་ཁོ་རང་ངོས་ནས་བསྒྲུབ་རྒྱུ་རེད་མ་གཏོགས། [ཏོག ]
12. 05:24ནང་གི་སེམས་ཀི་[ཀྱི་]དགའ་སྡུག་བྱུང་བསྡད་པ་དེ་ལ་ཁབ[་བརྒྱབ་]བརྒྱབས་ནས་ཕན་ཡག་ཅིག་དང་། གཅིག་བཤགས་བཅོས་བྱས་ནས་ཕན་ཡག་འདྲ་བོ་གཅིག་དང་། དངུལ་མང་པོ་ཡོད་ན་དེས་སེལ་ཡག་ཅིག་མི་འདུག་ག
13.  05:33 རེད་བ།[པ།] ཨོ་ཧུ། ཨོ་ཧུ། ལུས་པོའི་དཀའ་སྡུག་སྡུག་བསྔལ་ཟེར་ཡག་དེ་གའི་[རྒྱས་]དེ། དཔེར་ན། འཚོ་བས་ཕོངས་པའི་སྡུག་བསྔལ་གྱིས་མཚོན་པས།[པའི།] གཅིག་ཚ་གྲང་གི་སྡུག་བསྔལ་གྱིས་མཚོན་པས།[པའི།]
14. 05:43 དེ་འདྲས་ཀི་[ཀྱི་]སྡུག་བསྔལ་དེ་གའི་[རྒྱས་]དེ་དངུལ་ཡོད་ན། [ཨ་]ཨེ་ནི་ཁོ་གང་ལྟར་[ཨ་]ཨེ་ནི་སྨན་བཅོས་བྱེད་ཡག་གི་མཚོན་པས། གཅིག་ཟ་བཏུང་ལོངས་སྤྱོད་[ཨ་]ཨེ་ནི་ཕུན་སུམ་ཚོགས་པ། 
15. 05:52ད་ག་ནང་བཞིན་གི་[གྱི་]གནས་ཁང་ཕུན་སུམ་ཚོགས་པ། [འཁོར་]ཁོར་ཡུག་ཕུན་སུམ་ཚོགས་པ། གཉེན་ཉེ་དུ་ཕུན་སུམ་ཚོགས་པ། དེ་འདྲས་གཅིག་གི་ངང་ནས་ལུས་པོའི་བདེ་ཐང་དེ་སྒྲུབ་ཐུབ་ཀི་[ཀྱི་]ཡོད་རེད། 
16. 06:01ལུས་པོའི་བདེ་སྐྱིད་དེ་བསྒྲུབ་ཐུབ་ཀི་[ཀྱི་]ཡོད་རེད། ཨ་ད་ཡིན་ནས་ཨི་ཨི་གཅིག་ཕྱི་ཡི་ད་དངུལ་དང་དངོས་པོ་ལ་བརྟེན་ནས།
17.  06:11སྒྲུབ་ཐུབ་ཡག་ཡོད་བསྡད་པའི་ཆ་རྐྱེན་དེ་གའི་[རྒྱས་]དེ་ཕུན་སུམ་ཚོགས་པོ་ཞིག་ཡོད་པ་ཡིན་ནས་སེམས་འཁྲུག[ས་]བྱས། མ་སྐྱིད་པ་བྱེད་བསྡད་མཁན་མང་པོ་ཡོང་གིན་འདུག་ག
18. 06:20བྱས་ཙང་དེ་འདྲས་ཀི་[ཡི་]ད་སེམས་འཁྲུག་བསྡད་ཡག་གི་མ་སྐྱིད་པ་ཡོང་བསྡད་ཡག་དེ་ཕྱི་དངོས་པོའི་མཐུན་རྐྱེན་མ་འདང་བའི་རྐྱེན་བྱས་ནས་དཀའ་ངལ་བྱུང་བ་མ་རེད།
19. 06:29ནང་བསམ་བློའི[་བློ་]གཏོང་སྟངས་ཀིས་[ཀྱི་]གཅིག་མ་འགྲིགས་ནས་[ཨ]་ཨེ་ནི་སེམས་འཁྲུག[ས་]བསྡད་པ་ཡིན་པ་རེད། སེ་དེ་འདྲས་[འདྲ]་ཡིན་དུས་ནས།
20. 06:36གང་ལྟར་ང་རང་ཚོས་དོན་གཉེར་བྱེད་ཡག་གི་སེལ་རྒྱུའི་སྡུག་བསྔལ་དང༌། བསྒྲུབ་རྒྱུའི་བདེ་སྐྱིད་ལ་ཡ།
21.  06:44གཙོ་བོ་ལུས་ཚོར་ལ་བརྟེན་བསྡད་པའི་ཨེ་ནི་བདེ་སྡུག་ཅིག་དང༌། གཙོ་བོ་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་ཅིག་གཉིས་ཡོད་བསྡད་པ(་དེ)་གསལ་པོ་རེད་འདུག་ག
22. 06:53སེ་དེ་(འདྲས)་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ད་དེ་གཉིས་པོ་དེའི་ནང་ནས་ག་རེ་གལ་ཆེ་ཡི་རེད་ཟེར་ལབ་ན།
23.  07:01ག་གིའི་[རྦད]་སྦེ་འགངས་འདྲ་བོ་ཆེ་གི་[ཡི]་རེད་ཟེར་ལབ་ན། ཕལ་ཆེར་ནང་བསམ་བློའི་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་དེ་ཕལ་ཆེར་འགངས་ཆེ་བ་རེད་བཞག [ཤག ]
24. 07:09དེ་ཡིན་པའི་རྒྱུ་མཚན་ག་རེ་རེད་ཟེར་ལབ་ན། ཨི་ལུས་པོའི་དཀའ་ངལ་མང་པོ་གཅིག་[ཞིག་]སེམས་ཀྱིས[་ཨ་]ཨེ་ནི་ཚེམས་པ་དེ་གིས། [ཡི།]
 
༢༠༢༣་༠༣་༣༠ དགོང་དྲོ། 

2023-03-31 03:50 UTC, Tenzindharten requested changes
༡་ 07:18 ལུས་པོའི་དཀའ་ངལ་ཟིལ་གྱིས་[གནོན་](མནན)་ཐུབ་ཀི་[ཀྱི་]འདུག་ག ལུས་པོའི་གཅིག་དཔེར་ན་གཅིག དཔེར་ན་ང་རང་ཚོའི་གཅིག་སོ་སོ་ཆབ་སྲིད་ཀྱི་དམིགས་ཡུལ་འདྲ་བོ། 

༢. 07:29གཅིག་[གི]ད་ག་ནང་བཞིན་གི་གཅིག་[གི་]སོ་སོའི་ད་གཅིག་ད་གང་ལྟར་དམིག་ཡུལ་འདྲ་བོ་ཡང་ད་ག་ནང་བཞིན་དཔེར་ན་རྩེད་མོའི་གཅིག་ད་འགྲན་བསྡུར་[གྱི་]གི་ཐོག་ནས།

༣. 07:39གཅིག་མིང་བླང་ཡག་གི་བཟོ་འདྲ་བོ་གཅིག་དེ་འདྲས་ཀི་[ཡི]་གང་ལྟར་བསམ་བློའི་ཐོག་ནས་དོན་དུ་གཉེར་བའི་དོན་དག་ཅིག་འགྲུབ་ཡག་གི་དོན་དག་ལ།

༤. 07:49 ལུས་པོས་དཀའ་ལས་ཞེ་བོ་[ཅིག་བརྒྱབ་]རྒྱག་ཐུབ་མཁན་ཡོང་གི་འདུག་ག

༥.  07:52ད་ག་ནང་བཞིན་ང་རང་ཚོས་ཆོས་ཉམས་ལེན་བྱེད་མཁན་ཅིག་གིས་ནང་བསམ་བློའི་ཐོག་ནས་གཅིག་གི་མཐར་པ་དང་ད་མཐར་པ་ཐམས་ཅད་མཁྱེན་པ་ད་[ཏ]་གང་ཤེས་ཏེ་[ལྟས་]ད་སྔོན་ལ་སྤྱིར་བཏང་འདྲ་བོ་བཤད་པ་ཡིན་ན།

༦.  08:02གང་ལྟར་ནང་ཆོས་ཕྱོགས་ཀི་[ཀྱི་]ཐོག་ནས། [ད་]ཡང་སོ་སོའི་དམིགས་ཡུལ་གཅིག་[ཞིག]་བསྒྲུབ་ཡག་ཅིག་བཞག་ནས། དེ་བསྒྲུབ་ཡག་གི་ཆེད་དུ་ལུས་པོའི་དཀའ་ངལ་དང་དུ་ལེན་ནས།

༧.  08:10དང་དུ་ལེན་ནས་དཀའ་ངལ་ཁྱད་དུ་བསད་པ་མང་པོ་ཞིག་ཡོང་གི་འདུག་ག དེ་གའི་[རྒྱས་]དེ་ཁོ་དང་དུ་བླངས་ནས་དཀའ་ངལ་དེ་[ཨ་]ཨེ་ནི་མྱོང་གི་ཡོད་རེད་མ་གཏོགས། [ཏོག]

༨. 08:19མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་བྱུང་བ་མ་རེད་བ།  དེ་[འདྲ་]འདྲས་་ཡིན་དུས་ནང་སེམས་ཀྱིས་ཡིད་ཚིམས་པ་དེས་ལུས་པོ་ལ་བརྟེན་པའི་དཀའ་ངལ་དེ་སྡུག་བསྔལ་དེ་གའི[་རྒྱས]་དེ།

༩. 08:29དང་དུ་[ལེན་]བླང་ཐུབ་ཡག་ཡོང་གི་ཡོད་རེད་བ།[པ།] དེས་སེམས་ལ་མ་སྐྱིད་པ་ཡོང་རྒྱུའི་ཚབ་ལ་སེམས་ལ་ལྷག་པར་དུའང་ཡིད་ཚིམ་པ་ཡོང་ཡག་ཅིག་ཡོང་ཡག་འདུག་ག

༡༠. 08:39ད་དེ་ལས་ལྡོག་ནས་ནང་བསམ་བློ་འཁྲུག་བསྡད་ཡོད་ན་ཕྱི་ཡི་དངོས་པོའི་མཐུན་རྐྱེན་ག་ཚད་ཀི་[ཚོད་ཀྱི་]བཟང་པོ་ཞིག་ཡོད་པ་ཡིན་ནས།

༡༡. 08:47དེས་ནང་སེམས་ཀྱི་མ་སྐྱིད་པ་ཡོད་བསྡད་པ་དེ་ཟིལ་གྱིས་གནོན་ཐུབ་ཀི་[ཀྱི་]མི་འདུག་ག སེ་དེ་འདྲས་[འདྲ་]ཡིན་དུས་ཨི་གཙོ་བོ་ཡིད་བློ་ལ་བརྟེན་པའི་བདེ་སྡུག་དེ།

༡༢.  08:56འགངས་ཆེ་བ་[དེ་]རེད་ཤག་ཕན་ནུས་[གནོད་]ཤུགས་ཆེ་བ་རེད་ཤག ཡང་གཉིས་ནས་དཔེར་ན་གཅིག་ལུས་ཚོར་ལ་བརྟེན་བསྡད་པའི་བདེ་བ་སྡུག་བསྔལ།

༡༣.  09:06བདེ་བ་སྡུག་བསྔལ་དེ་ཨེ་ནི་སྡུག་བསྔལ་སེལ་ཡག་དང༌། བདེ་བ་བསྒྲུབ་ཡག་དེ་དུད་འགྲོ་དང་ཐུན་མོང་བ་རེད་ཤག 

༡༤.  09:13ད་ཡིད་བློ་ལ་བརྟེན་པའི་བདེ་སྡུག་དེ་མ་གཞི་[ཞི་]དུད་འགྲོའི་རིགས་ལས་ཕྲན་བུ་ཕྲན་བུ་ཡོང་གི་ཡོད་ས་རེད་དེ། ཨི་ཡིན་ནས་[ནའི་]གཙོ་བོ་མི་རེད།

༡༥. 09:22མི་ལ་ཡ་ཡིད་བློ་ལ་བརྟེན་པའི་བདེ་སྡུག་དེ་ཤུགས་ཆེ་[བ་]རེད་ཤག དེ་ཡིན་པ་དེ་ཡོང་ཡག་གི་རྒྱུ་མཚན་དེ་མི་ལ་(ཡ་)བསམ་བློ་ཞེ་དྲག་ཤུགས་ཆེ་[བ་]ཡོད་རེད་པ། 

༡༦.  09:31བསམ་བློ་གཏོང་ཡག་གི་ནུས་པ་དེ་མི་ལ་ཞེ་དྲག་ཤུགས་ཆེ་[བ་]རེད། དུད་འགྲོ་ཤུགས་ཆུང་བ་རེད། ད་དེ་ཀླད་པའི་འགྲོ་སྟངས[་ཤིག་]གཅིག་གི་ཐོག་ནས་དེ་ཏན་ཏན་རེད་ཤག། 

༡༧.  09:39ཀླད་པ་གཅིག་བསམ་བློ་གཏོང་ཡག་གི་ཀླད་པ་དེ་མིའི་ཀླད་པ་ཞེ་དྲག[ས་]ཤུགས་ཆེ་མང་བ་ཡོད་རེད།[ལ།] སེ་དེ་འདྲས་[འདྲ་ཡི་]ཐོག་ནས་མི་ལ་བསམ་བློ་གཏོང་ཡག་གི་ནུས་པ་དེ་ཤུགས་ཆེ་བ་ཡོད་པ་ཡིན་དུས་ཙ་ནས་བསམ་བློ་གཏོང་ཡག་གི

༡༨.  09:49 ནུས་པ་ཤུགས་ཆེ་བ་ཡོད་པ་[དེས]་དེའི་རྐྱེན་པའི་[པས]་རེ་དོགས། རྣམ་རྟོག་འདྲ་མི་འདྲ་མང་པོ་བྱུང་ནས་[དེ་]དེའི་རྐྱེན་པས།

༡༩. 09:56[ཨ་]ཨེ་ནི་ཡིད་བློ་ལ་བརྟེན་པའི་དགའ་སྡུག་མང་པོ་ཞིག་ཡོང་བསྡད་ཡག་ཅིག་ཡོང་གི་ཡོད་རེད། དེ་འདྲས་[འདྲ]་ཡིན་པ་ཡིན་དུས་དུད་འགྲོ་དང་མི་བྱས་ན་མི་ལ་ཡ་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི།

༢༠. 10:05བསམ་བློ[ས]་རྐྱེན་པས་[ཨ]་ཨེ་ནི་རེ་དོག་གམ་[དོགས་དང་]རྣམ་རྟོག་མང་པོ་[ཞིག་]གཅིག་གིས[་ཨ་]ཨེ་ནི་སེམས་ལ་ཡ་སྐྱིད་མ་སྐྱིད་ཡོང་བསྡད་ཡག་དེ་མི་ཤུགས་ཆེ་ཤོས་ཆགས་བསྡད་ཡོད་རེད།

༢༡. 10:13སེ་འོ་དེ་འདྲས་[འདྲ་]ཡིན་དུས་གསལ་པོ་ཞེ་དྲག[ས]་འདུག་ག ཕྱི་ལུས་པོ་ལ་བརྟེན་པའི་སྡུག་བསྔལ་སེལ་ཡག་དང་བདེ་བ་བསྒྲུབ་ཡག་ལ་དངོས་པོ་ཡར་རྒྱས་དེ་དགོས་ཀི་[ཀྱི་]ཡོད་རེད།

༢༢. 10:23ནང་ཡིད་བློ་ལ་བརྟེན་པའི་བདེ་སྡུག་དེས་བདེ་སྡུག་དེ་འདྲའི་[འདྲ]་ཞིག་ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཙ་ནས། དེ་ལ་དངུལ་སྤྲད་ནས་བཟོ་ཐུབ་ཡག་ཅིག་ཁོ་མེད་པ།

༢༣. 10:33ཨི་ཕྱིའི་སྨན་བཅོས་རྐྱང་རྐྱང་[གེ]་གི་ཐོག་ནས་བཟོ་ཐུབ་ཡག་མེད་པ་ཡིན་དུས་ཙ་ནས། ནང་བསམ་བློའི་སྦྱོང་བརྡར་གི་[གྱི་]ཐོག་ནས་སྡུག་བསྔལ་ཉུང་དུ་གཏོང་ཡག་ཅིག་དང༌། བདེ་བ་མང་དུ་གཏོང་བསྡད་ཡག་ཅིག་གི་ད་ཐབས་ཤེས་གཅིག་[ཤིག་ཨ་]ཨེ་ནི་བྱེད་འོས་པ་རེད་པ། 

༢༤.  10:43བྱེད་དགོས་ཡག་ཆགས་ཀི་[ཀྱི་]འདུག་ག ཨོ། ཨི་ད་ཆོས་ལུགས་ཁག་གྲུབ་མཐའ་ཡོད་བསྡད་པ་དེ་གའི་[རྒྱས]་དེ་ཡིས།

༢༥. 10:53ད་ཨ་ཕ་གིའི་བསླབ་བྱ་[རྒྱབ་]རྒྱག་ཡག་སྙིང་པོ་འདྲ་བོ་ཁོ་གཅིག་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེའི་[འདི་ཡི་]བསླབ་བྱ་དེ་[རྒྱབ་]རྒྱག་བསྡད་ཀི་[ཀྱི་]ཡོད་རེད། རེད་བ་དེ་འདྲས་[འདྲ་]ཡིན་པ་ཡིན་དུས་ཙ་ནས།

༢༦. 11:02མི་ལ་ཡ་ཕན་ཐོགས་གཅིག་[ཤིག་]ཡོང་གི་ཡོད་རེད་ལ། ཨིའི། རེད། དུས་ད་ལྟ་ཡིན་ནས་[ནའི་]ད་གང་ལྟར་ཆོས་བརྒྱུད་དེ་གའི་[རྒྱས་]དེ། གང་ལྟར་འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་ཁོ་གནས་བསྡད་ཀི་[ཀྱི་]ཡོད་རེད། 

༢༧. 11:11ཆོས་བརྒྱུད་དེ་གའི་[རྒྱས་]དེའི་རྗེས་སུ་འབྲང་མཁན་མི་ས་ཡ་མང་པོ་གཅིག་[ཅིག་]ཡོང་བསྡད་ཀི་[ཀྱི་]ཡོད་རེད།

༢༨.  11:17ཨི་ད་ཡང་སྐབས་རེ་ཨི་ད་ཆོས་བརྒྱུད་སོ་སོ་ལ་ཡ། ཨི་སོ་སོ་ལ་ཡ་ཁོ་རང་གཅིག[་གི]་ཆོས་ལུགས་རང་རང་ནས་ཅིག་གསུངས་བཞག་པའི་བསླབ་བྱ་སྙིང་པོ་དེ་དང༌། ཡང་གཅིག་གི་མར་དུས་རབས་མར་མང་པོ་ཞིག་འདུག་བྱས་སེ་[ཟེ་]འགྲོ་བསྡད་དུས་ཙ་ནས།

༢༩. 11:37དེ་ཡང་[རྗེས་]གཅིག་[ལ]་ལམ་དང་ལུགས་སྲོལ་འདྲ་བོ་མར་ཆགས་བསྡད་ཡག་ཅིག་གི་དེ་ཆ་གཉིས་འདུག་ག

༣༠. 11:42ལུགས་སྲོལ་གྱི་ཆ་གཅིག ཆོས་ལུགས་ཀི་[ཀྱི་]ད་བྱེད་སྒོ་འདྲ་བོ། ཆོས་ལུགས་ཀྱི་ལུགས་སྲོལ་འདྲ་བོ་ཆ་གཅིག ཨི་ཆོས་ལུགས་དེ་ནས་བཤད་བཞག་པའི།

༣༡. 11:51བསླབ་བྱ་སྙིང་པོ་འདི་ཨི་ཆ་གཅིག་བྱས་ནས་[ནི]་དེ་ང་ཚོས་ད་དབྱེ་བ་ཕྱེ་ཡག་དེ་གལ་ཆེན་པོ་[ཞིག་]ཞེ་དྲག་རེད་བཞག[ཤག] (ད་ཆོས་ལུགས་ཨི་སྙིང་པོ་དེ། ད་ལྟ་ངས་ལབ་པ་ནང་བཞིན་གིན། )

2023-03-31 08:01 UTC, Tenzindharten requested changes
༡.  11:58ད་ཆོས་ལུགས་སྙིང་པོ་འདི་ད་ལྟ་ངས་ལབ་པ་ནང་བཞིན་གྱི་བྱམས་བརྩེ་ཟེར་བསྡད་ཡག་དེ་བཤད་བསྡད་[ཀྱི་]ཀི་ཡོད་རེད།
༢.  12:04བྱམས་བརྩེ་དེ་དང་འབྲེལ་བའི་[བྱས་]བཟོད་བསྲན་[ཟན]་ཆོག་ཤེས་ཟེར་ཡག་[ཅིག་]དེ་བཤད་བསྡད་ཀི་[ཀྱི་]ཡོད་རེད། ཨིའི་[དེ་]དེའི་སྒྲུབ་བྱེད་ལ་ཡ་ད་འཇིག་རྟེན་བཀོད་པ་པོ་འདོད་མཁན། འཇིག་རྟེན་བཀོད་པ་པོ་མི་འདོད་མཁན་དེ་འདྲའི་[་ཡི་]ད་ལྟ་གྲུབ་མི་འདྲ་གཅིག་བཤད་བསྡད[་ཀྱི]་ཀི་ཡོད་རེད།
༣. 12:14 རེད་བ་ད་ཆོས་ལུགས་དེ་[རྒྱས]གའི་དེ་གཅིག་ལོ་སྟོང་ཕྲག་ཕྱིན་བསྡད་པ་ཤ་སྟག་ཆགས་བསྡད་དུས་ཙ་ནས། ཆོས་ལུགས་གང་དང་གང་[ལ]་ཡིན་ནའང༌། ཨི།  
༤. 12:23ཆོས་ལུགས་དེ་ཡོད་སའི་ལུང་པ་[འདིའི་]དེའི་[ཨ་]ཨེ་ནི་གོམས་སྲོལ་དེ་འདྲའི་དང་ཁོ་འབྲེལ་བ་གཅིག་ཆགས་བསྡད་ཀྱི་འདུག་ག དེ་འདྲས་གཅིག་ཆགས་པའི་ཆགས་པ་དང་།
༥. 12:32ཡང་ཆོས་ལུགས་དེ་དང་དེ་ནས་གཅིག་[གི་]ཡང་ལམ་དང་ལུགས་སྲོལ་འདྲ་བོ་ཅིག་མར་ཆགས་བསྡད་མཁན་གཅིག ད་ཁོ་གཉིས་ཡོད་པ་ཡིན་དུས་ཙ་ནས། ད་ང་ཚོ་ག་རེ་གལ་ཆེན་པོ་འདུག་ཟེར་ལབ་[པཡིན]་ན།
༦. 12:41སྙིང་པོ་དེ་ག་རེ་རེད་འདུག དེ་བསམ་བློ་[གཏང]་གཏོང་ཡག་དེ་དཔེ་གལ་ཆེན་པོ་རེད་ཤག ད་འོ་ན་སྔོན་ལ་དེ་ལབ་དགོས་མེད་འགྲོ་སྔོན་ལ་ཆོས་ལུགས་གང་དང་གང་ལ་ཡིན་ན་ཡང༌། 
༧.  12:51ལྟ་གྲུབ་ཀྱི་ཆ་གཅིག་དང༌། བསླབ་བྱ་དེའི་ཆ་གཅིག་ཤེས་སོང་ང་། ད་ལྟ་གྲུབ་འདྲ་[མིན]་མི་འདྲ་མང་པོ་ཞེ་བུ་[དྲག་]གཅིག་ཡོང་བསྡད་ཀྱི་ཡོད་རེད། 
༨. 12:59ཡིན་ནས་[ནའི་]ལྟ་གྲུབ་འདྲ་[མིན]་མི་འདྲ་དེ་གའི་[་རྒྱས་]དེ་གིའི་[ཡི་]དགོས་དོན་གྲུབ་དོན་འདྲ་བོ་དེ་ག་རེ་རེད་འདུག་ག ད་དེ་བསམ་མནོ་[བློ་གཏང]བཏང་ན། ཨ་ནི།
༩. 13:08བྱམས་སྙིང་རྗེ་རྩལ་དུ་[བཏོན་]གཏོང་མཁན་གཅིག་པ་ཆགས་བསྡད་དུས་ཙ་ནས། གཞི་རྩ་དེའི་ཆ་ནས་ཆོས་ལུགས་ཚང་མ་ལོག[ས]་མཐུན་པོ་བྱེད་ཐུབ་ཡག་གི་རྒྱུ་མཚན་གཅིག་ཡོད་བསྡད་པ་ཆགས་བསྡད་ཡོད་རེད།
༡༠.  13:18ད་[ཨ་]ཨེ་ནི་ལྟ་གྲུབ་འདྲ་མི་[་མིན]་འདྲ་དེ་[རྒྱས་]གའི་དེ་ཡོད་རེད། ལྟ་གྲུབ་རྦད་དེ་གཅིག་གིས་འདོད་པ་གཅིག་[ཅིག་གི་]གིས་མི་འདོད་པ་ཞེ་[བོ་]བུ་གཅིག་གིས་ད་ཧེ་བག་ཆེན་པོ་ཡོད་རེད། དེ་དགོས་མཁོ་ཡོད་[པ་]རེད། 
༡༡. 13:27མིའི་ཁམས་དང་མོས་པ་མི་འདྲ་བ། དུས་རབས་མི་འདྲ་བ[་དང༌]། དུས་རབས་མི་འདྲ་བ། ས་གནས་མི་འདྲ་བ། ཁམས་དང་མོས་པ་མི་འདྲ་བ་དེ་འདྲའི་གཅིག[་ཅིག་]ལ་ཡ་ཁོ་བཤད་ཡོང་དུས་ཙ་ནས། 
༡༢.  13:37[ཨ]་ཨེ་ནི་ཁམས་དང་མོས་པ་མི་འདྲ་བའི་རྐྱེན་གྱིས་གང་ལྟར་ལྟ་གྲུབ་མི་འདྲ་བ་གཅིག་དགོས་ཀི་[ཀྱི་]ཡོད་རེད། དཔེར་ན། སངས་རྒྱས་པའི་ཆོས་པ་རང་གི་ནང་དུ་ཆ་བཞག་ནས། [ནའི།] 
༡༣. 13:46ཁམས་དང་མོས་པ་མི་འདྲ་བ་ཡོད་པ་ཡིན་དུས་ཙ་ནས། [ཨ་]ཨེ་ནི་ཐེག་པ་མི་འདྲ་བ། [ཨ་]ཨེ་ནི་ལྟ་གྲུབ་མི་འདྲ་བ་ཡོང་བསྡད་ཀྱི་ཡོ་རེད་པ། 
༡༤. 13:52སེ་དེ་འདྲས་[འདྲ་]ཡིན་པ་ཡིན་དུས་ཨི་ལྟ་གྲུབ་མི་འདྲ་བ་ཡོད་པ་དེ་གའི་[རྒྱས་]དེ།[་ཡི་]དེ་ལ་བརྩི་ཡག་གལ་མི་འདུག དེའི་ལྟ་གྲུབ་མི་འདྲ་བ་དེ་[རྒྱས་]གའི་དེ་ཡིས། 

༢༠༢༣་༠༣་༣༡ ཉིན།

2023-03-31 09:09 UTC, Tenzindharten requested changes
14:02གང་ལྟར་ཕ་[གི་]གིའི་གཏན་ལ་ཕབ་ཡག་དང་། དེ་གའི་[རྒྱས་]དེ་ཡི་[གྲུབ་]བསྒྲུབ་ཡག་གི་[འདྲ་དང་]ད་གཅིག་གི་གྲུབ་དོན་འདྲ་བོ་ཁོ་གཙོ་བོ་ག་རེ་རེད་ཟེར་ལབ་ན། བྱམས་སྙིང་རྗེ་ཟེར་བསྡད་ཡག་དང་ད་དེའི་སྒང་ལ།
14:10ཁོ་གཅིག་པ་བབ[ས་ཀྱི]ཀི་་ཡོད་པ་ཡིན་དུས་ཚང་མ་ལོག[ས་]མཐུན་པོ་བྱེད་ཡག་གི་ཆ་རྐྱེན་ཞིག་འདུག་ག དེ་ནས་ཆོས་ལུགས་གང་དང་གང་ཡིན་ནས།[ནའི།] ད་གིན་ལབ་པ་ནང་བཞིན་གྱི་ཆོས་ལུགས་ཀྱི་སྙིང་པོ་གཅིག་དང༌། 
14:20ལམ་དང་ལུགས་སྲོལ་གྱི་ཆ་འདྲ་བོ་གཅིག་གཉིས་ཡོད་པ་དེའི་ནང་ནས་ད་ང་ཚོ་ག་རེ་གལ། ག་རེ་གལ་ཆེན་པོ་བརྩི་ཡིས་[རོད་]རེད་ཟེར་ལབ་པ་ཡིན་ན། སྙིང་པོ་དེ་བརྩི་[རྩེ]་ཡག་དེ་གལ་ཆེན་པོ་རེད་ཤག ད་ཧིན་དྷུ་ཡིན་ནས་[ནའི་]འདྲ། 
14:30འོ་ད་ཕལ་ཆེར་གཅིག་གི་ཡེ་ཤུ་ཡིན་ནས་[ནའི་]འདྲ། ནང་པ་ཡིན་ནས་[ནའི]་འདྲ། འོ་ན་མང་པོ་[ཅིག་[གཅིག་གིས་སྤྱི་ཚོགས་ནང་ལོག་ལ་སྙིང་པོ་དེ་བརླགས། 
14:39ལམ་དང་ལུགས་སྲོལ་དེ་འཇགས། དེ་འདྲའི་ད་ང་ཚོ་མང་པོ་གཅིག་[ཅིག་]ཡོང་བསྡད་ཀི་[ཀྱི་]འདུག་ག སེ་ངས་ནམ་རྒྱུན་ད་ལྟ་ངས་རྒྱ་གར་བ་ངོ་ཤེས་དེ་འདྲ་ལ་བཤད་བསྡད་ཀྱི་ཡོད་ལ། གང་ལྟར་ད་ང་རང་ཚོ་ཆོས་པ་ཚང་མ་ལོག[ས་]ངས་འདི་བཤད་བསྡད་ཀྱི་ཡོད། 

2023/03/31/

2023-03-31 10:49 UTC, Tenzindharten requested changes
༡. 14:48ད་ང་ཚོ་ཆོས་ཁས་བླངས་དང་མ་བླང་ཟེར་ཡག་དེ་སོ་སོ[འི]རང་དབང་རེད། ཆོས་མ་བྱས་ནས[་གྲིགས་]འགྲིག་གི[ཀྱི]་རེད། དེ་སོ་སོའི་རང་དབང་རེད། ཆོས་མེད་ན་སྐྱིད་པ་འདུག་ན་དེ་ཆོས་མ་བྱས་ན་འགྲིག[ས་]པ་རེད།
༢. 14:57ཁྱད་གས་གས་[རྒྱབ]་ཡག་མི་འདུག་ག ཡིན་ན་ཡང་ཆོས་གཅིག་[ཤིག་]ཁས་བླངས་ཕྱིན་ཆད་ལ་དེ་སོ་སོ་བསམ་པ་རྣམ་དག་གིས་
༣. 15:05གཅིག་དོ་གལ་འདྲ་པོ་གཅིག་[ཅིག]་བརྩིས་བྱས། ཡིད་གཟབ་འདྲ་བོ་[ཅིག་]བྱེད་ཡག་དེ་གལ་ཆེན་པོ་རེད་ཤག་སེ།  རེད་མ་གཏོགས་ཨེ་ནི་[ཏོག་]ང་ཆོས་ལུགས་དེ་དང་དེའི་རྗེས་འབྲང་ཡིན་ཟེར་སེ།[ཡག]
༤. 15:15མིང་ཙམ་ཞིག་མ་གཏོགསས[་ཏོག] ངོ་ཐོག་ཆོས་ཀྱི་བསླབ་བྱ་ག་རེ་ག་རེ་ཡོད་པ་དེ་དོ་སྣང་ཡང་མ་བྱས་པ་བྱས། བསླབ་བྱ་དེ་ཉིན་རེ་ཉིན་རེའི་མི་ཚེའི་ནང་ལོག་ལ་ཡ།
༥  15:23བསླབ་བྱ་དེ་ཁྱེར་ཤེས་པ་གཅིག་[ཅིག]་མེད་པ་བྱས། འཁྱེར[་ཁྱེར་]ཡག་ལ་བསླབ་བྱ་དེ་ཉིན་རེ་ཉིན་རེའི་ཚོ་བའི་ནང་ལོག་ལ་ཡ་བསླབ་བྱ་དེ་ལག་ལེན་བཀལ་ཡག་གི་དོ་སྣང་གལ་མེད་པ་བྱས།
༦. 15:32[ཨ་]ཨེ་ནི་ཆོས་ཟེར་ལབ་དུས་ད་ག་སེ་གཅིག་ལུགས་སྲོལ་གྱི་བཟོ་འདྲ་བོ་གཅིག ཨེ་ནི་ཆོས་བྱེད་[བྱས་]ཟེར་ལབ་དུས་ཡང་ལམ་དང་ལུགས་སྲོལ་ནང་བཞིན་བྱས་ནས། [ནི།] དཔེར་ན་གཅིག་[ཡི་]ཡེ་ཤུའི་ཆོས་པ་འདྲ་བོ་ཞིག་ཡིན་པ་ཡིན་ན།
༧. 15:42[ཨ་]ཨེ་ནི་དུས་དུས་ལ་[སུ་ཨ་]ཨེ་ནི་ག་རེ་ཟེར་བ་[དགོས་]རེད། དཔེར་ན་གཟའ་ཉི་མའི་[ཅིག་]གཅིག་ལྷ་ཁང་ནང་ལ་སྨོན་ལམ་འདྲ་བོ་གཅིག་བརྒྱབས། [ཨ་]ཨི་ཨེ་ནི་དཔེར་ན་ང་རང་ཚོ་ནང་པ་ཆ་བཞག་ནས།
༨. 15:52གཅིག་དུས་དུས་ལ་སོ་སོ་ལྷ་ཁང་ནང་ལོག་ལ་ཡ་འདོན་པ་འདྲ་བོ་གཅིག་བཏོན། སྨོན་ལམ་འདྲ་བོ་གཅིག་བརྒྱབས་དེ་ཁྱུག་ཙེ[་ཅིག]་རིང་ལ་སྨོན་ལམ་འདྲ་བོ་གཅིག་[ཅིག]བརྒྱབས[་བརྒྱབ]་མིག་སྤུ་[ཟིང་ཟིང་]ཟིམ་ཟིམ་བྱས་བསྡད། [ཨ་]ཨེ་ནི་ཕྱི་ལོག[ས]་ལ་མར་སླེབས་ཚར་དུས་ག་གིས[་གའི]་མེད་པ་བྱས།
༩. 16:00འོ་ད་དེ་འདྲས་གཅིག་[འདྲ་ཅིག]་ང་ཚོ་ཆོས་ལུགས་མང་པོའི་ནང་ལ་འདུག་ག བྱས་ཙང་ང་ཚོས་ཆོས་དད་པ་བྱེད། དད་པ་བྱེད་ཀིན་[ཀྱི་]ཡོད་རེད་དེ་ཡིན་ནས་[ནའི]་ལམ་དང་ལུགས་སྲོལ་དེའི་སྒང་ལ་འདུག་[ཟེ]་སེ་ཕྱིན་པའི་བཟོ་འདྲ་བོ་གཅིག་མ་གཏོགས། [ཅིག་མ་ཏོག]
༡༠. 16:10[ཨ་]ཨེ་ནི་ཁོ་ངོ་ཐོག་ལ་བསླབ་བྱ་[གང]ག་འདྲའི་གཅིག་[ཅིག]་ཡིན་པ་དེ་དང༌། ངོ་ཐོག་གི་[ཀྱི་]བསླབ་བྱ་དེ་ཤེས་པའི་ཐོག་ནས་ཉིན་རེ་ཉིན་རེའི་འཚོ་བའི་ནང་ལོག་ལ་ཡ་ལག་ལེན་བཀལ་ཡག་དེ་དོ་སྣང་ཞེ་དྲག་མེད་བསྡད་མཁན་གཅིག་ཡོང་བསྡད་ཀྱི་འདུག་ག
༡༡. 16:20དེ་ནོར་འཁྲུལ་རེད།


༢༠༢༣།༠༣།༣༡ ཤོག་ཁུག་གཅིག་གི་མཇུག་རྫོགས་པ།

2023-04-02 06:37 UTC, Tenzindharten requested changes
00:00ད་དེ་འདྲ་ཡིན་དུས་ཙ་ནས། [ཨ] ཨེ་ནི་ཨི་ཀླུ་སྒྲུབ་ཡབ་སྲས་ལ་སོགས་པ། འོ་ད་དེ་གའི་[རྒྱས་]དེ་གི ཨིའི་དཔེར་ན་ད་ཀླུ་སྒྲུབ་ཀྱིས
00:09གང་གི་[གིས་]ཐུགས་བརྩེས་ཉེར་བཟུང་ནས། །
ལྟ་བ་ཐམས་ཅད་སྤང་[སྤངས་]པའི་ཕྱིར། །
དམ་པའི་ཆོས་ནི་སྟོན་མཛད་པ། །
གཽ་ཏམ་དེ་ལ་ཕྱག་འཚལ་ལོ། །
[བྱས་ནི་]ཞེས་གསུངས་ཡག་དེ་དང༌། ཨེ་ནི་རྩ་བ་ཤེས་རབ་ཀྱི་དབུ་དེ་ལ་ཡ།
00:18གང་གིས་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང༌། །འགག་པ་མེད་པ་སྐྱེ་མེད་པ། །
ཆད་པ་མེད་པ་རྟག་མེད་པ། །འོང་བ་མེད་པ་འགྲོ་མེད་པ། །
ཐ་དད་དོན་མིན་དོན་གཅིག་མིན། །སྤྲོས་པ་ཉེར་ཞི་ཞི་བསྟན་པ། །
རྫོགས་པའི་སངས་རྒྱས་སྨྲ་རྣམས་ཀྱི། །དམ་པ་དེ་ལ་ཕྱག་འཚལ་ལོ། །ཟེར་བྱས་ནས།[་ནི།]
00:27ཨི་དེ་འདྲའི་བསྟོད་ཕྱག་མཛད་སའི་ཡུལ་དེ་ད་བསམ་གྱིས་མི་ཁྱབ་པ་གཅིག་ཡིན་པ་གཅིག་[ཞིག[ཨ་]ཨེ་ནི་ཚོད་དཔག་བྱེད་ཐུབ་ཡག་ཅིག་འདུག་ག
00:33ཨོ་ད་དེ་ད་[ཏ་]ཁྱད་མཚར་གཅིག་ཡོད་ས་རེད། མི་འདྲ་བ་གཅིག་[ཞིག་]ཡོད་ས་རེད་བསམ་པ་དྲན་ཡག་ཅིག་[ཞིག་]འདུག་ག
00:37དེ་འདྲས་[འདྲ]་ཡིན་དུས་ཙ་ནས་[ཨ་]་ཨི་ཨེ་ནི། ཨི་ཨི་དེ་འདྲས་[འདྲ་]ཡིན་དུས་ལོ་ཉིས་སྟོང་ལྔ་བརྒྱའི་གོང་དུ་བྱུང་བཞག་པའི་སངས་རྒྱས་བཅོམ་ལྡན་འདས་དེ།
00:47མི་ཕལ་པ་གཅིག་ད་[ཅིག་ཏ་]མིན་པ་གཅིག་མི་རང་དགའ་བ་མིན་བསྡད་པ་གཅིག་[ཞིག་]ད་ཚོད་དཔག་བྱེད་ཐུབ་ཡག་རེད། དེ་ཙམ་དུ་མ་ཟད་པའི་[པར་ཨ་]ཨེ་ནི།
00:57ཉན་ཐོས་སྡེ་པའི་གཞུང་ནས་བཅོམ་ལྡན་འདས་[ཨ་]ཨེ་ནི་རྒྱ་གར་ལ་[དུ་]འཁྲུངས་དུས་ཙ་ནས། [ཨ་]ཨེ་ནི་ད་ཚེ་འདི་ལ་གསར་དུ་སངས་རྒྱས་མཁན་གྱི་བྱང་ཆུབ་སེམས་དཔའ་སེམས་ཅན་གཅིག་[ཞིག་]བྱས། ད་དེས་ཨེ་ནི་རྡོ་རྗེ་གདན་གྱི་གནས་ལ་ཡ་[ཨ་]ཨེ་ནི།
01:16སྔོན་ལ་ཐོག་མར་ད་ག་རེ་ཟེར་བ་[དགོས]་རེད་ཕ་གིའི་ལོ་དྲུག་དཀའ་སྤྱད་དེ་ཚོ་མཛད། མཐར་[ཨ་]ཨེ་ནི་རྡོ་རྗེ་གདན་གྱི་གནས་ལ་མངོན་པར་རྫོགས་པ་སངས་རྒྱས་པའི་མཛད་པ་མཛད་ཡག་དེ།
01:25འོད་རེ་ད་དེ་ནས་སངས་རྒྱས་པའི་མཛད་པ་མཛད་ནས་དེ་ནས་ད་གཅིག་ག་ཚད་རེད་ལོ་བཞི་བཅུ་[ཅུ་]་ཞེ་གྲངས་གཅིག ཨེ་ནི་སེ་ད་སེ་སངས་རྒྱས་གནང་བྱས།
01:35ད་སེམས་ཅན་ལས་ཡོངས་སུ་འདས་ནས་སངས་རྒྱས་ཆགས་ནས་[ཏེ་]ལོ་བཞི་བཅུ་ཞེ་གྲངས་ཤིག་བཞུགས། དེ་ནས་[ཨ་]ཨེ་ནི་སངས་རྒྱས་ཚར་བའི་དེ་ནས་
01:44ག་རེ་ཟ་རྩྭ་མཆོག་གྲོང་ལ་ཡ་[ཨ་]ཨེ་ནི་མྱ་ངན་ལས་འདས་པའི་རྗེས་ལ། ཨེ[་ཨ་]ནི་བདུད་བཞི་ཁར་བཅོམ[ན་]ནི། འཆི་བདག་གི་བདུད་བཅོམ། ཕུང་པོའི་བདུད[་ཀྱང]་བཅོམ་ནས།[ནི།]
01:52ད་དེ་ནས་ཕུང་པོ་ལྷག་མ་མེད་པ[ར་ཨ་]ཨེ་ནི་མྱང་ངན་ལས་འདས་པ་རེད་ཟེར། དེ་ནས་[ཨ་]ཨེ་ནི་མར་མེ་ཤི་བ་ནང་བཞིན་རིག་པ་རྒྱུན་ཆད་པ་རེད་ཟེར་བྱས་ནས་[ནི་]ད་བཤད་བསྡད་ཡག་ཅིག་ཡོད་རེད་པ།
02:01ད་འདི་ཨེ་ནི་རྒྱུ་མཚན་མི་ལྡན་པ་ཞིག་ཆགས་ཀི་[ཀྱི་]ཡོད་རེད། འདིའི་བཤད་པ་བཤད་པ་ག་རེ་ཟེར་བཤད་སྟངས་འདི།
02:10ད་གཏི་ཐུག་ཆགས་པ་རེད། བསམ་བློ་ཞིག་བཏང་པ་ཡིན་ན། བསྐལ་ཆེན་གྲངས་མེད་གསུམ་གྱི་བར་ལ་ཡ་ཚོགས་བསགས་ནས། རྒྱུ་རླབས་ཆེན་པོ་དེ་འདྲའི[་ཞིག་]གཅིག་གིས།
02:20འབྲས་བུ་དེ་ལོ་བཞི་བཅུ་ཞེ་གྲངས་[ཤིག་]གཅིག་གི་ཨེ་ནི་མངོན་པར་རྫོགས་པའི་སངས་རྒྱས་ནས་ལོ་བཞི་བཅུ་ཞེ་གྲངས་[ཤིག་]གཅིག་གི་ད་སེམས་ཅན་གྱི་དོན་མཛད་ཡག་མ་གཏོགས་[ཏོག་]བྱུང་མེད་ན། རྒྱུ་འབྲས་གོ་འཛོལ་རེད་འདུག་ག
02:30རྒྱུ་[འདི་]ད་ག་རང་[འདྲ་]བོ་གཅིག་ལ་བསླབས་ནས། བྱང་ཆུབ་ཀྱི་སེམས[་ཀྱི་ˌཀྱིས་ཀུན་ནས་བསླངས་ཏེ། ཨེ་ནི་ཕྱིན་དྲུག་ལ་ཡ་བསླབ་ཡག་དེ་ག་རང་བོ་[འདྲ་བོ་]གཅིག་[ཅིག་]གི་སྐུ་ངལ་སྐྱོན་ནས་མཐའ་མ་ལོ་བཞི་བཅུ་ཞེ་གྲངས་གཅིག་[ཤིག]་མ་གཏོགས་[ཏོག་ཨ]ཨེ་ནི་དེའི་འབྲས་བུ།
02:40མེད་པ་ཞིག་ཡིན་ན་དེ་ནི་ཐབས་སྐྱོ་པོ་རེད་པ། རྒྱུ་འབྲས་འཆོལ་ཡོང་གི་འདུག་ག དཔེར་ན། ང་རང་ཚོའི་འཇིག་རྟེན་གྱི་བྱ་བ་ཞིག་ཡིན་པ་ཡིན་ནས་[ནའི།] དཀའ་ལས་ཞེ་བོ་[བརྒྱབ་]བརྒྱབས་ནས་བསྒྲུབས་བཞག་པའི་འབྲས་བུ་དེ།
02:49དེ་ལ་དཔག་པ་གཅིག་གིས་དཀའ་ལས[་བརྒྱབ་]བརྒྱབས་ནས་[བརྒྱབ་]རྒྱག་རིན་ཆོག་པའི་འབྲས་བུ་ཞིག་དགོས་ཀྱི་རེད་མ་གཏོགས[ཏོག]་དེ་མེད་ན་[ཨ་]ཨེ་ནི་ག་རེ་ཟེར་བ[་དགོས་]རེད་དཀའ་ལས་ཆེ་ལ་དོན་གོ་ཆུང་བ་ཆགས་ཡོང་གི་[གེ་]རེད་པ།
02:58སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས་དེ་ཡང་[མི]་མ་བདེ་བ་གཅིག་[ཞིག་]ཆགས། གཉིས་ནས་[ཨ]ཨེ་ནི་ཨི་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི། འོ[་སྒྲིག་]འགྲིག་ཤག
03:09ཨི་གཉིས་ནས་[ཐ]་ད་ཐེག་པ་ཆེ་ཆུང་སྔགས་དང་བཅས་པ་དེ་[རྒྱས་]གའི་དེ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ་ཨི་སྐུ་ཚེ་གཅིག་ལ་ཡ་ད་ག་རེ་ཟེར་བ་[དགོས་]རེད།
03:19སྐུ་ཚེ་གཅིག་གི་རིང་[དེ་]ད་ག་རང་ལ་སྐུ་ཚེ་གཅིག་ད་ལོ་བརྒྱད་བཅུ། བརྒྱད་བཅུ་ཙམ་བཞུགས་བཞག་པའི་དུས་ཡུན་དེ་ག་རང་གི་ནང་ལོག་ལ་ཡ་ལམ་ཡོངས་སུ་རྫོགས་པ་དེ་གའི་[རྒྱས་]དེ་[ཨ]ཨེ་ནི།
03:28ཐུགས་ལ་ཡ་ཤར་ནས་གཅིག་གསུངས་པ་རེད་ཟེར་ལབ་དགོས་བྱུང་ནས་[ནའི]་དཔེ་ཁག་པོ་རེད། ལྷག་པར་དུ་ཡང་ཨེ་ནི་ཕུང་པོ་ལྷག་མ་སངས་ཕུང་པོ་ལྷག་མ་མེད་པར་མྱ[ང་]ངན་ལས་འདས་ནས་[འབད་]ཕེ་གིའི་ད་དེ་ཡི་རིག་པའི་རྒྱུན་ཆད་པ་ཡིན་ན།

༢༠༢༣།༠༤།༢ ལ།

2023-04-02 14:20 UTC, tsultrim-dolma commented
00:00ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་གི་སྐད་ཆ་བཤད་ཡོང་དུས་ཙ་ནས།
ཨི་ཆོས་ལུགས་དང་འབྲེལ་བ་སླེབ་ཀི་ཡོད་རེད།

00:07 འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་ཡ། ད་ཨི། ད་ལོ་ཕ་གིའི་སྟོང་ཕྲག་ཁ་ཤས་ཀྱི་རིང་ལ་ཡ།
གང་ལྟར་མིའི་སྤྱི་ཚོགས་ནང་ལོག་ལ་ཆོས་ཟེར་ཡག་ཅིག་བྱུང་ཡིན་པ་རེད།

00:19 ཨི་ད་ཆོས་རིགས་ཁ་ཤས་ཨི་ཞེ་དྲག་དེ་སེ་གལ་ཡོད་མ་རེད།
ད་གཅིག་ཨི་ད་ཨི་ཉི་མ་གསོལ་ཡག་གི་བཟོ་འདྲ་བོ།

00:27 ཅིག་དེ་བ་གཅིག་ཨེ་ནི་ཨི་ག་རེ་ཟེར་བ་རེད།
ཕ་གི་གིའི་མེ་མེ་མེ་ལ་ཡ་ད་གཅིག་ད་ག་རེ་ཟེར་བ་རེད་རྩ་ཆེན་པོ་བརྩི་ཡག་བཟོ་འདྲ་བོ།

00:36 ད་དེ་འདྲའི་མི་འདུག་སྟེ། ཨེ་ནི་གཅིག་ད་ལྷ་ཡོད་རེད།
ཀླུ་ཡོད་རེད་ཟེར་ཡག་འདྲ་བོ་བཤད་བྱས་དེ་འདྲའི་ཐོག་ནས།
གཅིག་དད་པ་བྱེད་བསྡད་ཡག་འདྲ་བོ་གཅིག་ཡོང་བསྡད་ཀི་འདུག་ག

00:45ད་དེ་གའི་དེ་ལ་ནིལྟ་གྲུབ་ཟེར་གལ་མི་འདུག་ག
གྲུབ་མཐའ་ཟེར་གལ་བཤད་ཡག་མི་གདུག་ག

00:49ད་ཨི་ད་གྲུབ་མཐའ་ཡོད་བསྡད་པའི་ཆོས་ལུགས་དེ་གའི་དེ།
ཕལ་ཆེར་རྒྱ་གར་ནང་ལ་ཆ་བཞག་ན་ཕལ་ཆེར་ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་ཕྱིན་པ་མིན་འགྲོ།

00:58
ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་མཚམས་ནས་ཨེ་ནི་ད་ལྟ་གྲུབ་བཤད་ནས་དེའི་ཐོག་ནས་ཨི་ད་ཆོས་ཀྱི་ཨི་ག་རེ་ཟེར་བ་རེད་ཕ་གིའི།

01:08ད་ཆོས་དད་ཅིག་བཤད་ཡོང་གིན་ཡོད་རེད།

01:10
ཨི་བྱས་ནས་དེ་འདྲའི་ད་ལྟ་གྲུབ་ཡོད་བསྡད་མཁན་གྱི་ཕལ་ཆེར་ཆོས་ལུགས་གཙོ་ཆེ་བ་དེ་གའི་དེ།

01:19ད་རྒྱ་གར་ནང་གི་ཆོས་ལུགས་ཆ་བཞག་ནས་འདྲ།
ཨེ་ནི་ཨི་རིམ་པས་གཅིག་གི་ཨི་ད་དཔེར་ན་འཇིའུ་ལ་ཆ་བཞག་ནས།

01:28འཇིའུ་སྡེ་ཟེའི་ཆ་བཞག་ནས་འདྲ། ཨེ་ནི་ཡེ་ཤུ་ཡིན་ནས་རེད། ཁ་ཆེ་ཡིན་ནས་རེད།
གཅིག་ད་ཨ་ག་རེ་ཡོད་རེད་ཨེ་ནི།

01:38ད་དེ་ལ་སོགས་པའི་གང་ལྟར་དེ་ལ་སོགས་པའི་ད་གཅིག་གྲུབ་མཐའ་ཡོད་བསྡད་མཁན་གྱི་ཆོས་ལུགས་དེ་གའི་དེ་ཚང་མ་ལོག་གིས་བསླབ་བྱ་རྒྱག་ཡག་དེ།
ནི་མི་སེམས་པ་བཟང་པོ་བྱེད་དགོས་རེད། བྱམས་པ་དགོས་རེད།

01:48བརྩེ་བ་དགོས་རེད་ཟེར་ཡག་དེ་བཟོད་པ་དགོས་རེད། ཆོག་ཤེས་དགོས་རེད།
ཨེ་ནི་རང་རང་གི༌ཕི་གིའི་བསླབ་པ་སྲུང་དགོས་ཀྱི་རེད།

01:56རང་རང་གི་ཆོས་ལུགས་ནས་བཤད་ཞག་པའི་བསླབ་པ་སྲུང་དགོས་ཀི་རེད་ཟེར་བྱས་ནས་བཤད་བསྡད་མཁན་གཅིག་ཚང་མ་གཅིག་པ་རེད་འདུག་ག
དེ་འདྲས་ཡིན་དུས་ཆོས་ལུགས་ཁག་དེ་གའི་དེ་ཡིས་སྙིང་པོ་ག་རེ་བཤད་ཀི་ཡོད་རེད་ཟེར་ལབ་ན།

02:06མི་ལ་ལྷན་སྐྱེས་ཀི་ཡོད་བསྡད་པ་དང་།
ལྷན་སྐྱེས་ཀི་ཡོད་བསྡད་པའི་ཐོག་ལ་མི་ལ་དགོས་མཁོ་ཡོད་བསྡད་པའི་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གལ་ཆེན་པོ་ཡིན་པ་གཅིག་ཆོས་ལུགས་ཚང་མས་བཤད་ཀི་འདུག་ག

02:15
ད་བྱམས་པ་དང་བརྩེ་བ་ཨ་སྒྲུབ་སྟངས་དེ་ལ་ཨེ་ནི་ཨི་ཐབས་ཤེས་མི་འདྲ་བ་བྱས་ཀྱིས།

02:24རིགས་གཅིག་གིས་འཇིག་རྟེན་བཀོད་པ་པོ་ཡོད་རེད་ཟེར་བྱས་ནི།
འཇིག་རྟེན་བཀོད་པ་པོ་དེ་བརྩེ་བའི་བདག་ཉིད་རེད། མཁྱེན་པའི་བདག་ཉིད་རེད། ཇི་ཙམ།
དེ་འདྲས་ཡིན་དུས་ཙ་ནས།

02:34འཇིག་རྟེན་བཀོད་པ་ལ་ང་ཚོས་བརྩེ་བ་བྱེད་དགོས་རེད། དད་པ་བྱེད་དགོས་རེད།
གུས་པ་བྱེད་དགོས་རེད། ཇི་ཙམ་གྱིས་འཇིག་རྟེན་བཀོད་པ་པོ་ལ་ཡ།
དད་པ་དང་བརྩེ་བ་དང་གུས་བྱས་པ་དེའི་ཚོད་ཀྱིས།

02:43རང་ཉིད་ཀིས་ཨེ་ནི་གཅིག་དད་པ་དང་། གཅིག་བརྩེ་བ་ཟེར་ཡག་དེ་ཚོའི་གྲས།
རང་ཉིད་ཀྱིས་ད་ཉམས་ལེན་བྱེད་དགོས་ཡག་ཅིག་དང་།

02:49
ཨེ་ནི་འཇིག་རྟེན་བཀོད་པ་པོ་གཅིག་གིས་བཀོད་བཞག་པའི་ང་རང་ཚོ་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་ཨེ་ནི་གཅིག་བརྩེ་བ་བྱེད་དགོས་རེད་ཟེར་ཡག་ཅིག

02:56
དཔེར་ན་ད་ལྟ་འདིའི་མུ་སི་ལིམ་ད་ལྟ་འདི་ཀོ་རན་ནང་ལོག་ལས་འདི་འདྲ་འདྲས་བཤད་ཀིས་བཤད་ཀི་ཡོད་པ་རེད།

03:03ངས་ད་ལྟ་ཁ་ཆེ་ངོ་ཤེས་པ་གཅིག་སྐད་ཆ་བྱུང་།
ཁ་ཆེ་བླ་མ་གཅིག་སྐད་ཆ་བྱུང་ཨེ་ནི་ཀོ་རན་ནང་ལོག་ལ་ཡ་ཨེ་ནི།

03:10
འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པའི་ད་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་ང་ཚོ་བྱམས་བརྩེ་བྱེད་དགོས་རེད་ཟེར་བྱས་ནས་དེ་འདྲ་ཡོད་རེད་སེ།

03:20སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས། སྒྲུབ་བྱེད་འདི་འཇིག་རྟེན་བཀོད་པ་ཡིས་བཀོད་ནས།
འཇིག་རྟེན་བཀོད་པ་པོ་ཟེར་ཡག འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པ་རེད་ཟེར་ཡག་དེ།
སྒྲུབ་བྱེད་དེ་འདྲའི་གཅིག་བཀོད་ཀི་ཡོདརེད།

03:29བཀོད་པའི་གྲུབ་དོན་སྙིང་པོ་འདྲ་བོ་དེ།
ཨི་བྱམས་པ་དང་བརྩེ་བ་དང་དེ་ཚོ་དགོས་ཀི་རེད་ཟེར་ཡག་ཅིག

03:34ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གཅིག་པོ་ཡིས་འདང་གི་ཡོད་མ་རེད།
ང་ཚོ་ད་ག་རེ་བྱས་ནས་ཡང་མི་མཐུན་པ་དང༌།
འཁྲུག་པ་རྒྱག་ཡག་ཡོང་གིན་་ཡོད་པ་ཡིན་དུས། ཨེ་ནི་བཟོད་པ་དགོས་རེད།

03:44ཨི་གཅིག་ག་རེ་ཟེར་བ་རེད།
ཕ་གིའི་ཨེ་ནི་ཆོག་ཤེས་དགོས་རེད་ཟེར་ཡག་དེ་ཚོའི་གྲས་ཀྱི་བསླབ་བྱ་དེ་སླེབ་ཡོང་གིན་འདུག་ག
སྙིང་པོ་སྙིང་པོ་དེ་བྱམས་བརྩེའི་སྒང་ལ་ཡ་སྐད་ཆ་བཤད་ཀི་ཡོད་རེད་བ། 03:52
སེ་དེ་འདྲས་འདྲ་ཡིན་པ་ཡིན་དུས་ཙ་ནས།
ད་ལྟ་དུས་རབས་ཉི་ཤུ་རྩ་གཅིག་པ་གཅིག་ཚན་རིག་ཡར་རྒྱས་ཧ་ཅང་ད་ཚད་མཐོན་པོ་སླེབས་བསྡད་པ།

04:01གཅིག་དངོས་པོ་ཡར་རྒྱས་སྤྱིར་བཏང་བཤད་པ་ཡིན་ན།
ཧ་ཅང་གི་ད་ཚད་མཐོ་པོ་སླེབས་བསྡད་པའི་དུས་རབས་འདིའི་ནང་ལ་ཡིན་ནས།
འཛམ་གླིང་ཤར་ནུབ་ག་ས་ག་ལ་ཡ་ཆོས་ལ་ཡ་དོ་སྣང་བྱེད་མཁན་གཅིག

04:12འཛམ་བུ་གླིང་འདིའི་སྒང་གི་མི་མང་བ་དེ་གའི་དེ།
ཆོས་ལ་དད་པ་ཅིག་ཡོད་མེད་མི་ཤེས་ཏེ།
ད་གང་ལྟར་ཆོས་ལ་དད་པ་བྱེད་མཁན་འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་མང་པོ་གཅིག་དུས་ད་ལྟ་ཡིན་ནས་ཡོད་བསྡད་པ་རེད།

04:21དེ་ཁྲལ་དང་ཁྲིམས་ཀྱི་ཐོག་ནས་བཟོས་པ་གས་མ་རེད།
རང་བཞིན་གྱིས་མི་ལ་ཡ་ཁོ་ཕན་ཐོགས་གཅིག་ཡོད་བསྡད་པ་གཅིག་དང་།
ཁོ་དགོས་མཁོ་ཡོད་བསྡད་པ་་གཅིག་མཐོང་བ་ཡིན་དུས་ཙ་ནས།

04:29མི་རིགས་གཅིག་གིས་ཆོས་ལ་ཡ་དོ་སྣང་བྱས་བསྡད་ཡག་ཅིག་ཆགས་བསྡད་ཀི་་ཡོད་རེད་བ།
དེ་འདྲས་ཡིན་དུས་ཙ་ནས།

04:34སྙིང་པོ་འདི་དངོས་པོ་ཡར་རྒྱས་ཀྱིས་ལུས་པོ་བདེ་ཐང་བཟོ་ཡི་ཡོད་རེད།
ལུས་པོའི་གཅིག་ཕ་གིའི།

04:43ཚོར་བ་བདེ་སྐྱིད་ཡོང་ཡག་གི་གང་ལྟར་ཆ་རྐྱེན་དེ་གའི་དེ་དངོས་པོ་ཡར་རྒྱས་ཀྱི་ཐོག་ནས་སྒྲུབ་བསྡད་ཀི་ཡོད་རེད།
ངེས་པར་དུ་དགོས་ཀི་ཡོད་རེད། ཨི་ད་ག་ནང་བཞིན་གྱི

04:52ལུས་པོའི་བདེ་ཐང་གཅིག་པོ་ཡིས་ང་ཚོར་འདང་གི་ཡོད་མ་རེད།
ག་རེ་ཟེར་ལབ་ན་ནང་རྣམ་པར་རྟོག་པའི་རྐྱེན་པས་ཡང་དགའ་སྡུག་མང་པོ་ཞིག་ཡོང་གི་ཡོད་རེད།

05:01དེ་འདྲ་དེ་རྣམ་པར་རྟོག་པ་ཁོ་རང་གི་ཐོག་ནས་ཐབས་ཤེས་ཤིག་བཙལ་ནས།
05:07རྣམ་རྟོག་གི་ཨེ་ནི་ཐོག་ནས་གཅིག་དགའ་པོ་ཡོང་བསྡད་ཡག
རྣམ་རྟོག་གི་ཐོག་ནས་མི་དགེ་བ་ཡོང་བསྡད་ཡག་དེ་ལ།
རྣམ་རྟོག་ཁོ་རང་གི་ཐོག་ནས།05:17དགའ་སྡུག་གི་ག་རེ་ཟེར་བ་རེད།
ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།
ད་དགའ་སྡུག་གི་རྒྱུ་རྐྱེན་གཅིག་རྣམ་རྟོག་ཁོ་རང་ངོས་ནས་བསྒྲུབ་རྒྱུ་རེད་མ་གཏོགས།
05:24ནང་གི་སེམས་ཀི་དགའ་སྡུག་བྱུང་བསྡད་པ་དེ་ལ་ཁབ་བརྒྱབས་ནས་ཕན་ཡག་ཅིག་དང་།
གཅིག་བཤགས་བཅོས་བྱས་ནས་ཕན་ཡག་འདྲ་བོ་གཅིག་དང་།
དངུལ་མང་པོ་ཡོད་ན་དེས་སེལ་ཡག་ཅིག་མི་འདུག་ག05:33རེད་བ། ཨོ་ཧུ།
ཨོ་ཧུ། ལུས་པོའི་དཀའ་སྡུག་སྡུག་བསྔལ་ཟེར་ཡག་དེ་གའི་དེ། དཔེར་ན།
འཚོ་བས་ཕོངས་པའི་སྡུག་བསྔལ་གྱིས་མཚོན་པས།
གཅིག་ཚ་གྲང་གི་སྡུག་བསྔལ་གྱིས་མཚོན་པས།05:43དེ་འདྲས་ཀི་སྡུག་བསྔལ་དེ་གའི་དེ་དངུལ་ཡོད་ན།
ཨེ་ནི་ཁོ་གང་ལྟར་ཨེ་ནི་སྨན་བཅོས་བྱེད་ཡག་གི་མཚོན་པས།
གཅིག་ཟ་བཏུང་ལོངས་སྤྱོད་ཨེ་ནི་ཕུན་སུམ་ཚོགས་པ།
05:52ད་ག་ནང་བཞིན་གི་གནས་ཁང་ཕུན་སུམ་ཚོགས་པ།
ཁོར་ཡུག་ཕུན་སུམ་ཚོགས་པ། གཉེན་ཉེ་དུ་ཕུན་སུམ་ཚོགས་པ།
དེ་འདྲས་གཅིག་གི་ངང་ནས་ལུས་པོའི་བདེ་ཐང་དེ་སྒྲུབ་ཐུབ་ཀི་ཡོད་རེད།
06:01ལུས་པོའི་བདེ་སྐྱིད་དེ་བསྒྲུབ་ཐུབ་ཀི་ཡོད་རེད།
ཨ་ད་ཡིན་ནས་ཨི་ཨི་གཅིག་ཕྱི་ཡི་ད་དངུལ་དང་དངོས་པོ་ལ་བརྟེན་ནས།06:11སྒྲུབ་ཐུབ་ཡག་ཡོད་བསྡད་པའི་ཆ་རྐྱེན་དེ་གའི་དེ་ཕུན་སུམ་ཚོགས་པོ་ཞིག་ཡོད་པ་ཡིན་ནས་སེམས་འཁྲུག་བྱས།
མ་སྐྱིད་པ་བྱེད་བསྡད་མཁན་མང་པོ་ཡོང་གིན་འདུག་ག06:20
བྱས་ཙང་དེ་འདྲས་ཀི་ད་སེམས་འཁྲུག་བསྡད་ཡག་གི་མ་སྐྱིད་པ་ཡོང་བསྡད་ཡག་དེ་ཕྱི་དངོས་པོའི་མཐུན་རྐྱེན་མ་འདང་བའི་རྐྱེན་བྱས་ནས་དཀའ་ངལ་བྱུང་བ་མ་རེད།
06:29ནང་བསམ་བློའི་གཏོང་སྟངས་ཀིས་གཅིག་མ་འགྲིགས་ནས་ཨེ་ནི་སེམས་འཁྲུག་བསྡད་པ་ཡིན་པ་རེད།
སེ་དེ་འདྲས་ཡིན་དུས་ནས།06:36གང་ལྟར་ང་རང་ཚོས་དོན་གཉེར་བྱེད་ཡག་གི་སེལ་རྒྱུའི་སྡུག་བསྔལ་དང༌།
བསྒྲུབ་རྒྱུའི་བདེ་སྐྱིད་ལ་ཡ།06:45གཙོ་བོ་ལུས་ཚོར་ལ་བརྟེན་བསྡད་པའི་ཨེ་ནི་བདེ་སྡུག་ཅིག་དང༌།
གཙོ་བོ་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་ཅིག་གཉིས་ཡོད་བསྡད་པ་དེ་གསལ་པོ་རེད་འདུག་ག
06:53
སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ད་དེ་གཉིས་པོ་དེའི་ནང་ནས་ག་རེ་གལ་ཆེ་ཡི་རེད་ཟེར་ལབ་ན།
07:01ག་གིའི་སྦེ་འགངས་འདྲ་བོ་ཆེ་གི་རེད་ཟེར་ལབ་ན།
ཕལ་ཆེར་ནང་བསམ་བློའི་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་དེ་ཕལ་ཆེར་འགངས་ཆེ་བ་རེད་བཞག
07:09དེ་ཡིན་པའི་རྒྱུ་མཚན་ག་རེ་རེད་ཟེར་ལབ་ན།
ཨི་ལུས་པོའི་དཀའ་ངལ་མང་པོ་གཅིག་སེམས་ཀྱིས་ཨེ་ནི་ཚེམས་པ་དེ་གིས།

07:18ལུས་པོའི་དཀའ་ངལ་ཟིལ་གྱིས་གནོན་་ཐུབ་ཀི་འདུག་ག ལུས་པོའི་གཅིག་དཔེར་ན་གཅིག
དཔེར་ན་ང་རང་ཚོའི་གཅིག་སོ་སོ་ཆབ་སྲིད་ཀྱི་དམིགས་ཡུལ་འདྲ་བོ།

07:29
གཅིག་ད་ག་ནང་བཞིན་གི་གཅིག་སོ་སོའི་ད་གཅིག་ད་གང་ལྟར་དམིག་ཡུལ་འདྲ་བོ་ཡང་ད་ག་ནང་བཞིན་དཔེར་ན་རྩེད་མོའི་གཅིག་ད་འགྲན་བསྡུར་གི་ཐོག་ནས།

07:39
གཅིག་མིང་བླང་ཡག་གི་བཟོ་འདྲ་བོ་གཅིག་དེ་འདྲས་ཀི་གང་ལྟར་བསམ་བློའི་ཐོག་ནས་དོན་དུ་གཉེར་བའི་དོན་དག་ཅིག་འགྲུབ་ཡག་གི་དོན་དག་ལ།

07:49ལུས་པོས་དཀའ་ལས་ཞེ་བོ་རྒྱག་ཐུབ་མཁན་ཡོང་གི་འདུག་ག

07:52
ད་ག་ནང་བཞིན་ང་རང་ཚོས་ཆོས་ཉམས་ལེན་བྱེད་མཁན་ཅིག་གིས་ནང་བསམ་བློའི་ཐོག་ནས་གཅིག་གི་མཐར་པ་དང་ད་མཐར་པ་ཐམས་ཅད་མཁྱེན་པ་ད་གང་ཤེས་ཏེ་ད་སྔོན་ལ་སྤྱིར་བཏང་འདྲ་བོ་བཤད་པ་ཡིན་ན།

08:02གང་ལྟར་ནང་ཆོས་ཕྱོགས་ཀི་ཐོག་ནས།
ཡང་སོ་སོའི་དམིགས་ཡུལ་གཅིག་བསྒྲུབ་ཡག་ཅིག་བཞག་ནས།
དེ་བསྒྲུབ་ཡག་གི་ཆེད་དུ་ལུས་པོའི་དཀའ་ངལ་དང་དུ་ལེན་ནས།

08:10དང་དུ་ལེན་ནས་དཀའ་ངལ་ཁྱད་དུ་བསད་པ་མང་པོ་ཞིག་ཡོང་གི་འདུག་ག
དེ་གའི་དེ་ཁོ་དང་དུ་བླངས་ནས་དཀའ་ངལ་དེ་ཨེ་ནི་མྱོང་གི་ཡོད་རེད་མ་གཏོགས།

08:19མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་བྱུང་བ་མ་རེད་བ།
དེ་འདྲས་་ཡིན་དུས་ནང་སེམས་ཀྱིས་ཡིད་ཚིམས་པ་དེས་ལུས་པོ་ལ་བརྟེན་པའི་དཀའ་ངལ་དེ་སྡུག་བསྔལ་དེ་གའི་དེ།

08:30དང་དུ་བླང་ཐུབ་ཡག་ཡོང་གི་ཡོད་རེད་བ།
དེས་སེམས་ལ་མ་སྐྱིད་པ་ཡོང་རྒྱུའི་ཚབ་ལ་སེམས་ལ་ལྷག་པར་དུའང་ཡིད་ཚིམ་པ་ཡོང་ཡག་ཅིག་ཡོང་ཡག་འདུག་ག

08:39
ད་དེ་ལས་ལྡོག་ནས་ནང་བསམ་བློ་འཁྲུག་བསྡད་ཡོད་ན་ཕྱི་ཡི་དངོས་པོའི་མཐུན་རྐྱེན་ག་ཚད་ཀི་བཟང་པོ་ཞིག་ཡོད་པ་ཡིན་ནས།

08:47དེས་ནང་སེམས་ཀྱི་མ་སྐྱིད་པ་ཡོད་བསྡད་པ་དེ་ཟིལ་གྱིས་གནོན་ཐུབ་ཀི་མི་འདུག་ག
སེ་དེ་འདྲས [...]

2023-04-02 16:18 UTC, Tenzindharten requested changes
1. 03:38[ཨ་]ཨེ་ནི་དུས་ཕྱིས་སུ་[འབད་]ཕིའི་དུས་ད་ལྟ་ཡིན་ནས། ད་བཅོམ་ལྡན་འདས་ཀྱི་གཅིག་བྱིན་རླབས་ཡོང་ལ། [ཡག་དང༌།] བཅོམ་ལྡན་འདས་ཀྱི་ཞལ་མཇལ་ཡག་དང་དེ་ཚོའི་གྲས་དེ་ཡོང་ཐུབ་ཡག་མེད་མཁན་གཅིག
2. 03:46ཨེ་ནི་རྒྱུད་སྡེའི་དཀྱིལ་འཁོར་དེ་ཚོའི་གྲས་[གྲལ་]དེ་ཡོང་ཐུབ་ཡག་ཡོང་ཤེས་ཀྱི་མ་རེད་པ། དེ་འདྲས་ཡིན་དུས་ཙ་ནས་བཅོམ་ལྡན་འདས་འདི། ཨེ་ནི སངས་རྒྱས་ཟེར།
3. 03:54ད་རྒྱ་གར་ལ་སངས་རྒྱས་པའི་མཛད་པ་མཛད་ཡག་དེ། གསར་དུ་སངས་རྒྱས་པའི་མཛད་པ་མཛད་པ་ཙམ་རེད་མ[་ཏོག་]གཏོགས།  ངོ་ཐོག་སངས་རྒྱས་ཡག་[སྔོན་]་སྔ་མ་ནས་སངས་རྒྱས་ཚར་པ་རེད་ཟེར།
4.  04:02ད་ཡང་སངས་རྒྱས་རྒྱས་པ་ཞིག་རེད་ཟེར་གིན་[ཀྱི]་ཡོད་མ་རེད་གདའ། སློབ་པ་ལམ་གྱི་གནས་སྐབས་མེད་ཟེར་གིན་ཡོད་མ་རེད་གདའ། [ཏ།] སློབ་པ་ལམ་གྱི་གནས་སྐབས་སྔོན་དུ་འགྲོ་བའི་ཐོག་ནས་མངོན་པར་རྫོགས་པ་སངས་རྒྱས་ནས།[ནི། ]སངས་རྒྱས་པའི།
5.  04:11འོ་ན་ཨེ་ནི་རྒྱ་གར་[དུ་]ལ་ཕེབས་བསྡད་ཡག་དེ་[གང་]ག་འདྲས་[ཅིག་]རེད་ཟེར་ལབ་ན། དེ་མཆོག་གི་སྤྲུལ་སྐུ་ཟེར་ཡག་དེ་རེད་ཟེར། མཆོག་གི་སྤྲུལ་སྐུ་དེ་ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་ལས་སྤྲུལ་ཡོང་གི་ཡོད་རེད་ཟེར།
6. 04:19ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་དེ{་གང་}ག་འདྲས་[འདྲ]་རེད་ཟེར་ལབ་ན། ཆོས་སྐུའི་དབྱིངས་ལས་ཤར་བསྡད་པ་རེད་སེ། [[ཟེར།] ད་སྐུ་བཞི་[ཤེས]་ཟེར་[བྱས་]གྱིས་ནས་[ནི་]ཡེ་ཤེས་ཆོས་ཀྱི་སྐུ་ཡོང་ཐུབ་ཡག་དེ་ཡང༌།
7.  04:27རྩ་བ་རང་བཞིན་རྣམ་དག་གི་ག་རེ་ཟེར་བ་[དགོས་]རེད་ཕ་གིའི་སྟོང་པ་ཉིད་དེ་དང༌། [ཨ་]ཨེ་ནི་སེམས་བདེན་སྟོང་དེ་དང་སེམས་བདེན་སྟོང་དེ་ཡོད་པ་ཡིན་དུས་ཙ་ནས།
8. 04:37དེ་མངོན་སུམ་དུ་རྟོགས་དེ་མངོན་དུ་གྱུར་ནས། ཨེ་ནི་དེའི་སྟེང་གི་ག་རེ་ཟེར་དགོས་རེད་ད་དེའི་སྟེང་གི་[ཨ་]ཨེ་ནི་ཕིའི་[རྦད་]དྲི་མ་ཐམས་ཅད་ལོག་ཆོས་ཀྱི་དབྱིངས་སུ་དག་སོང་བའི་གནས་སྐབས་ཀྱི།
9.  04:47དག་པ་གཉིས་ལྡན་གྱི་དབྱིངས་ངོ་བོ་ཉིད་སྐུ་དེ་བཞག་[ཅིང༌།] དེ་ལས་ཡེ་ཤེས་ཆོས་སྐུ། དེ་ལས་ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་ཤར་བསྡད་མཁན། དེ་ལས་སྤྲུལ་པའི་སྐུ་ཤར་བསྡད་པ།
10.  04:56སྐུ་བཞི་ཟེར་ཡག་གི་རྣམ་གཞག་དེ་གསུང[ས་]བསྡད་ཡག་དེ་[ཨ་]ཨེ་ནི་གཅིག་འདུག་ག [ཨ་]ཨེ་ནི་སངས་རྒྱས་སྟངས་དེ་ལྷག་པར་སྔགས་དང་འབྲེལ་ནས་བསམ་བློ་བཏང་བ་ཡིན་ན། ད་ལྟའི་ང་རང་ཚོའི་གསལ་རིག་གི་ཤེས་པ་འདིའི་སྟེང་ནས།
11.  05:05འདུག་[ཟེ]སེ་བྱས་ནས་[ནི་]སྐུ་བཞི་སྒྲུབ་སྟང་གཅིག་[ཅིག]་མར་ཅིག་བཤད་ཡོང་དུས། ཨོ་ད་དེ་ད་ལོས་བདེན་བསམ་ནས་སེམས་ནང་ལོག་ལ་ཡ་རྟོགས་པ་ད་སྐྱེ་ཡི[ས་ཀྱི]་ཡོད་མ་རེད་དེ།[ལྟས།]
12. 05:13དེ་ནས་མར་[ཏོག་]བསམ་བློ་ཞིག་བཏང་པ་[བ་]ཡིན་ན། དེ་ལ་གནོད་པ་ཧ་ལམ་མཐོང་ཐུབ་ཡག་མེད་པ། ད་དེ་ད་[ཏ་]ཏན་ཏན་ཡིན་ས་རེད་ཏ། དེ་ཡ་མཚན་པོ་འདུག་ག་བསམ་ནས་བློ་ལ་ཤར་ཡག་ཅིག་ཡོང་བསྡད་ཀིན་[གི་]འདུག་ག
2023/04/2

2023-04-03 05:18 UTC, Tenzindharten requested changes
05:23སེ་ཨོ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས། ད་དེ་འདྲ་ལྟ་བུའི་སྐུ་བཞིའི་བདག་ཉིད་ཀྱི་སངས་རྒྱས་ཞེས་གསུང་གི་ཡོད་རེད། ད་དེ་འདྲས་ཡིན་པ་ཡིན་ཙང་། ཨེ་ནི་ད་ལྟ་འདིར་དེ་ནས་བྱ་རྒོད་ཕུང་པོའི་རིར་བཀའ་བར་པ་མཚན་ཉིད་མེད་པའི་ཆོས་འཁོར་བསྐོར།
05:33ཞེས་པ་ལ་སོགས་པ་ད་ཐེག་པ་ཆེན་པོའི་མར་གསུང་[ས་]སྟངས་ཁོ། ད་དངོས་ཡོད་གནས་ཚུལ་ལ་ཡ་ཁོ་དེ་བདེན་པ་ཡིན་བསྡད་པ་གཅིག [ཞིག་གི]
05:41ད་ད་ལྟ་བཤད་མ་ཐག་པའི་རྒྱུ་མཚན་དེ་གའི་[རྒྱས་]དེ་ལ་བརྟེན་ནས་ད་ཤེས་ཐུབ་ཡག་ཅིག་[ཤིག་]རེད་ཤག ད་དེ་ནས་གྲུབ་མཐའ་བཞི་པ་དང་།
05:51ཐེག་པ། ཨེ་ནི་འདི་མར་བར་]གྲུབ་མཐའ་ལྔ་པ་དང་། ཐེག་པ་[ཨ]་ཨེ་ནི་བཞི་པ་ཡོད་མ་རེད་བྱས་ནས་གསུང་བཞག་བ་དེ་[དུས༌]གནད་འགག་སེ་[ཟེར]་གལ་མིན་འདུག
05:57ཨིའི་ད་དེའི་[ཞུ་]གཞུག་གུ་དེར་[འདིར་]འདི་གཅིག་[ཅིག་]འདུག་ག རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ། རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་བས་གཞལ་ན་རྟག་ཆད་ཀྱི་མཐའ་གཉིས་ཀར(་ལྟུང་ཞིང་།) ལྟུང་ཡང༌སེ། རང་རང་གི་ལུགས་ལ་དབུ་མ་པར་འདོད་དེ།
06:16རྟག་ཆད་ཀྱི་མཐའ་གཉིས་དང་བྲལ་བའི་དབུས་ཁས་ལེན་པར་རློམ་པའི་ཕྱིར་རོ་སེ།། ད་ཐུབ་པའི་དགོངས་པ་ཨིའི་མཐར་ཐུག་པ་དེ།
06:26རིགས་པས་གནོད་པ་མེད་པ་ཞིག་དགོས་[ཀྱི]་ཀི་རེད་པ། ད[་རིག་]རིགས་པས་གནོད་པ་མེད་པ་ད་ཐུབ་པས་[ཨ་]ཨེ་ནི་ལྟ་བ་མི་འདྲ་བ་གསུངས་བཞག་ཡག་ཅིག་དེ་འདྲའི[་ཡི་]ཕ་གིའི།
06:36ཆོས་ཚུལ་མི་འདྲ་བ་གསུངས་བཞག་པ་དེ་གའི་[་རྒྱས་]དེ། ཨི་གདུལ་བྱའི་ཁམས་དང་མོས་པ་སྣ་ཚོགས་པ་ཡོད་པ་ཡིན་དུས་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀྱི་རྗེས་སུ་[འབྲངས་]འབྲང་མཁན་གྱི་གདུལ་བྱའི་ནང་ལས་[ལ་]ཡང་ཁམས་དང་མོས་པ་མི་འདྲ་བ་ཡོད་པ་ཡིན་དུས་ཙ་ནས།
06:45དེའི་ཁམས་དང་མོས་པ་དང་བསྟུན་ནས་ད་བཅོམ་ལྡན་འདས་ཀྱིས་ཨིའི་གསུངས་པ་རེད། དེ་གསུང[ས་]དགོས་ཀྱི་རེད། ག་རེ་རེད་ཟེར་ལབ་ན་གང་གི[ས་]ཐུགས་བརྩེས་ཉེར་བཟུང་ནས། ། ཟེར་ཡག་འདི་ཡིན་པ་རེད།
06:53ཨིའི་ད་མཁྱེན་པ་བླ་ན་མེད་པ་ཡོད་པ་ཡིན་དུས་ཙ་ནས། ཨིའི་ག་རེ་ཟེར། སྔོན་མཐའ་མངོན་ནམ་ཞེས་ཞུས་ཚེ། །
ཐུབ་པ་ཆེན་པོས་མིན་ཞེས་གསུངས། །
07:02ག་རེ་ཟེ། བྱས་ནས་[ནི་]ད་འདི་ད་ལྟ། ད་ད་ལྟ་ཁམས་དང་མོས་པ་ཇི་བཞིན་པ་ཅིག
07:11ཇི་བཞིན་པ་མཁྱེན་ནས། དེའི་དོན་དུ་འགྱུར་ན་ལུང་བསྟན། དེའི་དོན་དུ་མ(་འ)གྱུར་ན་ལུང་མ་བསྟན་པ་གཅིག་[ཅིག]་གི་ག་རེ་ཟེར་ལུང་མ་བསྟན་པ་ཡིན་དུས་ཙ་ནས།
07:21ལུང་དུ་མ་བསྟན་པའི་མཛད་པ་དེས་ཀུན་མཁྱེན་ཡིན་པ་ད་ལྟ་ཤེས་ད་ལྟ་བསྒྲུབ་དགོས་ཀྱི་འདུག ཀུན་མཁྱེན་ཡིན་པ་ཤེས་ཐུབ་ཡག་རེད་ཤག་ཟེར་བྱས་འདི་གསུང་གི་འདུག་ག
07:30སེ་དེ་འདྲས་[འདྲ]་ཡིན་པ་ཡིན་དུས་ཙ་ནས། ད་གང་ལྟར་གདུལ་བྱའི་ཁམས་དང་མོས་པ་དང་འཚམས་པ་གཅིག་གི་[ཨ་]ཨེ་ནི་ཆོས་བསྟན་ནས་ཡོད་པ་ཡིན་དུས།
07:37བཅོམ་ལྡན་འདས་ཀྱིས་གསུང་ཚད་དེ་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀྱི་དགོངས་པ་མཐར་ཐུག་ཡིན་པ་དེ་བཤད་ཐུབ་ཡག་མི་འདུག་ག མི་འདྲ་བ་མང་པོ་ཞིག་ཡོང་གི་ཡོད་རེད་པ། ད་བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་དེ
།07:47རིགས་པས་གནོད་པ་མེད་པ་[ཞིག་]གཅིག་དགོས་ཀྱི་ཡོད་རེད། དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཨིའི་མགོན་པོ་ཀླུ་སྒྲུབ་ཀྱི་བཞེད་པ་ཐུན་མོང་མ་ཡིན་པ། ཨེ་ནི་སངས་རྒྱས་བསྐྱངས་དང༌། ཟླ་བ་གྲགས་པ་གཉིས་ཀྱིས་ད་མར་བཀྲལ་བཞག་པའི།
07:56དབུ་མའི་ལྟ་བ་ཐ་སྙད་དུ་ཡང་རང་མཚན་བཀག་ནས། [ཨ་]ཨེ་ནི་མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གི་[གྱི་]དེ་བཞིན་ཉིད་གསུང[ས་]བསྡད་ཡག་དེ། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་རྟེན་འབྱུང་ཕྲ་མོ།
08:06ཨིའི་དེ་རྒྱུ་མཚན་དུ་བྱས་ཏེ་རང་བཞིན་གྱིས་སྟོང་པ་ཡིན་པ་བཤད་བསྡད་ཡག་གི་རྟེན་འབྱུང་གི་དེ་ཁོ་ཉིད་ཟེར་བསྡད་མཁན་དེ་ད་བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་ཡིན་པ་གཅིག་[ཞིག][་ཨ]་ཨེ་ནི་ཁོ་ཤེས་ཐུབ་ཡག་ཅིག་ཡིན་པ་རེད། 
08:16བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་རིགས་པས་གནོད་ན། དེ་ཁྱད་མཚར་ཞེ་བོ་ཆགས་པ་རེད་པ་ཨེ་ནི། དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙ་ནས་རྗེ་རིན་པོ་ཆེས།
08:24དོན་བཞིན་གཟིགས་ནས་ལེགས་གསུངས་པ།། ཁྱོད་ཀྱི་རྗེས་སུ་སློབ་པ་ལ།། རྒུད་པ་ཐམས་ཅད་རིང་དུ་གྱུར།།
ཉེས་ཀུན་རྩ་བ་ལྡོག་ཕྱིར་རོ།། ཁྱོད་ཀྱི་བསྟན་ལས་ཕྱིར་ཕྱོགས་པས། །
ཡུན་རིང་ངལ་བ་བསྟེན་བྱས་ཀྱང༌། །
08:34ཕྱི་ཕྱིར་སྐྱོན་རྣམས་བོས་པ་བཞིན།། བདག་ཏུ་ལྟ་བ་བརྟན་ཕྱིར་རོ། །ཨེ་མའོ་མཁས་པས་འདི་གཉིས་ཀྱི། །
ཁྱད་པར་ཁོང་དུ་ཆུད་གྱུར་པ། །དེ་ཚེ་རྐང་གི་ཁོང་ནས་ནི། །
ཁྱོད་ལ་ཅི་ཕྱིར་གུས་མི་འགྱུར། ། ཟེར་བྱས་ནས་[ནི་]རྗེ་རིན་པོ་ཆེ[ས]་ཡིས་བསྡོམས་སྐྱོན་ཡག་དེ་ཟབ་པོ་ཞེ་བོ་[ཅིག]་འདུག་ག
08:44ཨ་དེ་འདྲ་ཡིན་དུས་བཅོམ་ལྡན་འདས་ལ་ཡ་ཤེས་ནས་དད་པ་ཐོབ་པ་ཟེར་ཡག་དེ། དེ་འདྲའི་གཅིག[་ཞིག]་གི་མཐའ་ཡས་པ་གཅིག་[ཞིག་]གི་གང་ས་གང་ལ་ཡ་ད།
08:53སྣ་ཁུག་དང་མ་སོང་ནས་རྒྱུས་བྱས། བརྩད་གཅོད་བྱས། བརྩད་གཅོད་བྱས། བརྩད་གཅོད་བྱས་དྲི་མ་སྣོམ། ཨེ་ནི་དེ་གའི་[རྒྱས་]དེ་ཕྱོགས་བསྡོམས་བརྒྱབ། ཕྱོགས་བསྡོམས་བརྒྱབ། ཕྱོགས་བསྡོམས་[བརྒྱབ་]བརྒྱབས་ནས་དེའི་འབྲས་བུ་དེ་ལ་ཡ།
09:02ཨོ་བཅོམ་ལྡན་འདས་དེ་[ནི་]མི་འདྲ་བ་གཅིག་[ཞིག་]རེད་འདུག་ག་བསམ་པ་གཅིག་ཤེས་པའི་ཐོག་ནས། ཨེ[་ཨ]་ནི་སངས་རྒྱས་ལ་སྐྱབས་སུ་མཆིའོ་ཟེར་ཡག་ཅིག་དགོས་རེད་མ་གཏོགས།[ཏོག] ཨ་ཕས་བསླབས་བྱུང༌། ཨ་མས་[བསླབ]བསླབས་བྱུང་ཟེར་བྱས་ནས་[ནི་ཨ་]ཨེ་ནི་སངས་རྒྱས་པའི་ཆོས་ཟེར་ལབ་ན།
09:12[ཇབ་]བྱབ་ཆུང་བ་ཆགས་པ་རེད།

༢༠༢༣་༠༤་༣ ཉིན། stt001_19_otr ཞེས་པའི་མཇུག་རྫོགས།

2023-04-03 07:34 UTC, Tenzindharten requested changes
00:00མཛད་པ་བཅུ་གཉིས་ཀྱི་དང་པོ་དགུ་བྱང་སེམས་དང༌། ཕྱི་མ་གསུམ་སངས་རྒྱས་ཀྱི་མཛད་པར་ཁས་ལེན་ནོ། །ཆོས་འཁོར་ལ་ཨིའི་མཐོང་ལམ་གྱིས་ཁྱབ་པ་དང༌། 
00:09ཆོས་འཁོར་ལ་མཐོང་ལམ་གྱིས་ཁྱབ་པ་དང༌། ཨིའི་ལུང་གི་ཆོས་འཁོར་ལ་བདེན་བཞིའི་ཆོས་འཁོར་གྱིས་ཁྱབ་པར་འདོད་དོ།།  མངོན་པ་སྡེ་བདུན་པོ་སངས་རྒྱས་ཀྱིས།
00:18ད་སྔོན་ལ་ལུང་གི་ཆོས་འཁོར་དང་། བདེན་བཞིའི་ཆོས་འཁོར་གྱིས་ཁྱབ་པར་འདོད་དོ་ཟེར་གྱིས། [བྱས།] དེ་ནས་ཡ། ད་དེ་ཨིའི་མངོན་པ་སྡེ་བདུན་པོ་སངས་རྒྱས་ཀྱིས་གསུངས་པའི་བཀར་ཁས་ལེན།
00:27བཀའ་ལ་སྒྲ་ཇི་བཞིན་པས་ཁྱབ་བོ། ། བཀའ་ལ་ཡ་དྲང་ངེས་གཉིས་བཞག་ཡག་དེ་འདྲའི་མེད་པ་བྱས། བཀའ་ལ་སྒྲ་ཇི་བཞིན་པས་ཁྱབ། [བོ།] ད་དེ་ནས་ཆོས་སྐོར་དེ་ཚར་བ་བྱས། ད་དེ་གནད་འགག་ཆེན་པོ་ཟེར་གལ་མི་འདུག
00:37ད་དེ་ནས་མར་བྱང་སེམས་སྲིད་པ་ཐ་མ་བས་བྱང་ཆུབ་མངོན་དུ་བྱེད་པའི་གནས་ནི་འདོད་ཁམས་ཁོ་ནར་ངེས། 
00:46འོག་མིན་སྟུག་པ་བཀོད་པའི་རྣམ་གཞག་དང༌། །ལོངས་སྐུའི་རྣམ་གཞག་ཁས་མི་ལེན། །དེར་མ་ཟད་རྣམ་མཁྱེན་ཡང་མི་འདོད། །
00:54ད་ག་རེ་ཟེར་བ་[དགོས་]རེད་ཕ་གིའི། ཨིའི་ཀུན་མཁྱེན་ཟེར་ཡག་འདྲ་བོ། ཤེས་བྱའི་ཆོས་གང་དང་གང་ཡིན་ནས།[་ཡང༌།]
01:02ཆོས་རེ་རེ་ལ་ཡ་ཞེ་ས་མ་ཞུས་ན། ཐུགས་ཕར་གཏད་པ་ཡིན་ན་མཁྱེན་མཁན། དེ་[འདྲ]འདྲས་ཡིན་དུས་ཙ་ནས།
01:11ཐུགས་གཏད་ན་མ་མཁྱེན་ཡག་གི་ཆོས་གཅིག་[ཀྱང]་མེད་པ་བྱས། ཐམས་ཅད་མཁྱེན་ཨེ་[ཨ་]ནི་ཀུན་མཁྱེན། རྣམ་པ་ཐམས་ཅད་མཁྱེན་ཟེར་པ་ཡིན་ན་དུས་གཅིག་ལ་ཤེས་བྱ་མཐའ་དག་མཁྱེན་ཡག་དེ་མེད་པ་བྱས།
01:21ཨིའི་་་ཐེག་པ་གསུམ་གྱི་དགྲ་བཅོམ་ལ་ལྷག་བཅས་པས་ཁྱབ་སྟེ། ཨིའི་་་ལྷག་མེད་མྱང་འདས་མངོན་དུ་བྱེད་པའི་ཚེ།
01:31མར་མེ་ཤི་བ་ལྟར་རིག་པ་རྒྱུན་ཆད་པར་འདོད། དེ་འདྲས་[འདྲ་]ཡིན་དུས་མཐར་ཐུག་ཐེག་པ་གསུམ་བཤད། 
01:37ད་དེའི[་ཞུ་]གཞུག་གུ་དེར་[འདིར]་སངས་རྒྱས། ཆོས། དགེ་འདུན་ཟེར་ཡག་དེ། སངས་རྒྱས་སུ་བྱེད་པའི་བྱེད་ཆོས་དང༌། དགེ་འདུན་དུ་བྱེད་པའི་བྱེད་ཆོས་ཀྱི་[ཨ]་ཨེ་ནི།
01:48ག་རེ་ཟེར་བ་[དགོས་]རེད་ཡེ་ཤེས་དེ་ལ་[ཨ]་ཨེ་ནི་སངས་རྒྱས་དཀོན་མཆོག་དང༌། ཆོས་དཀོན་མཆོག དགེ་འདུན་དཀོན་མཆོག་བཞག་གི་ཡོད་རེད་མ་གཏོགས།[ཏོག། དེའི་ད་གང་ཟག་ཟེར་དགོས་རེད་ཕུང་པོ་དེ་ལ་བརྩི་ཡི་ཡོད་མ་རེད་གསུང་གི་ཡོད་པ་འདྲ། 
01:56ཨིའི་གགཟུགས་སྐུ་ནི་སྔར་བཞིན་[་འདི་ནས་ཏག་ཏག་ཅིག་མི་གསལ་བས་བསྐྱར་ཞིབ་གནང་དགོས]་་སངས་རྒྱས་དཀོན་མཆོག་ནི་དེའི་ཐུགས་རྒྱུད་ཀྱི་ཟད་མི་སྐྱེའི་ཡེ་ཤེས་ལ་འདོད། །
02:05ད་ཉོན་མོངས་ཟད་པ་དང༌། སླར་མི་སྐྱེ་བ་ཞེས་པའི་ཟད་མི་སྐྱེ་ཞེས་པའི་ཡེ་ཤེས་དེ་ཉིད་སངས་རྒྱས་ཡིན།
དེ་བཞིན་དུ་སློབ་པ་འཕགས་པ་རྣམས་ཟག་བཅས་ཡིན་པས།
02:14དགེ་འདུན་དཀོན་མཆོག་མིན་ཡང་། དགེ་འདུན་ཡིན་ལ། དགེ་འདུན་དཀོན་མཆོག་ནི་དེའི་ཐུགས་རྒྱུད་ཀྱི་ལམ་བདེན་ལ་འདོད་དོ། །


02:21ཆོས་དཀོན་མཆོག་སངས་རྒྱས་དང་ཉན་རང་གཉིས་ཀའི་རྒྱུད་ཀྱི་མྱང་འདས་དང་འགོག ཨིའི་སངས་རྒྱས་དང་ཉན་རང་གཉིས་ཀའི་རྒྱུད་ཀྱི་འགོག 
02:31རྒྱུད་ཀྱི་མྱང་འདས་དང་འགོག་བདེན་དེ་དེ་ཡིན་པའི་ཕྱིར། འོ་དེ་འདྲའི་གཅིག་གསུངས་ཤག འོ་ད་དེ་གྲུབ་པ་བྱས། ཨིའི། ད་དེ་ནས་མདོ་སྡེ་པས།
02:41མདོ་སྡེ་པའི་ལུགས་བཤད་པ་ལ། ད་མཚན་ཉིད། དབྱེ་བ། སྒྲ་བཤད། འདོད་ཚུལ་བྱས་ནས་[ནི་]ད་བཞི་པ་འདོད་ཚུལ་བཤད་པ་ལ། 
02:49གཞི་ཡི་འདོད་ཚུལ། ལམ་གྱི་འདོད་ཚུལ། འབྲས་བུའི་འདོད་ཚུལ། དང་པོ་ལ་ཡུལ་དང་ཡུལ་ཅན། བྱས་ད་དེ།
02:57ཨིའི། བློས་རིག་པར་བྱ་བ་ཡུལ་གྱི་མཚན་ཉིད། ད་དེ་[མར]་མ་ཤེས་པ་[བྱས]་གལ་མི་འདུག ད་དེ་ལ་དབྱེ་ན། ཨིའི་དབྱེ་ཚུལ་ད་མི་འདྲ་བ་བྱས་ནས་[ནི]་བདེན་པ་གཉིས་སུ་དབྱེ་བ།
03:06ད་ཡུལ་ལ་དབྱེ་ན་བདེན་པ་གཉིས་སུ་དབྱེ་བ། རང་མཚན་དང་སྤྱི་མཚན་གཉིས་སུ་དབྱེ་བ། མདོ་སྡེ་པའི་ལུགས་ཀི་[གི་]ད་[དེ་]བདེན་གཉིས་རྣམ་གཞག་ཤེས་པ་ལ། 
03:15རང་སྤྱིའི་རྣམ་གཞག་ཤེས་དགོས་ཡག་དེ་དཔེ་གལ་ཆེན་པོ་ཡིན་པ་རེད། རང་སྤྱི་གཉིས་སུ་དབྱེ་བ༑ དགག་སྒྲུབ་གཉིས་སུ་དབྱེ་བ། མངོན་ལྐོག་གཉིས་སུ་དབྱེ་བ༑ དུས་གསུམ་དུ་དབྱེ་བ། གཅིག་དང་ཐ་དད་གཉིས་སུ་དབྱེ་བའོ། །
03:25དང་པོ་ནི། ཨིའི། སྒྲ་དང་རྟོག་པས་བཏགས་པ་ལ་མ་ལྟོས་པར་རང་གི་སྡོད་ལུགས་ཀྱི་ངོས་ནས་རིགས་པས་དཔྱད་བཟོད་དུ་གྲུབ་པའི་ཆོས་དེ་དོན་དམ་བདེན་པའི་མཚན་ཉིད། 
03:35དངོས་པོ་དང༌། དོན་དམ་བདེན་པ། རང་མཚན། མི་རྟག་པ། འདུས་བྱས། བདེན་གྲུབ་རྣམས་དོན་གཅིག
03:44ད་དེ་བདེན་གྲུབ་ག་རེ་ཟེར་གྱི་ཡོད་ན། ཨིའི། ད་ད་ག་དེ་གལ་ལུགས་ཀྱི་བདེན་གྲུབ་བསམ་བློ་བཏང་ན་མགཏོགས་[ཏོག་]གཞན་ཡང།
03:54འདུས་མ་བྱས་ཀྱི་ཆོས་ཀྱི་དེ་བདེན་གྲུབ་བརྩི་ཡིས་རེད་པ། བྱས་ཙང་ད་དངོས་པོ་དང་། དོན་དམ་བདེན་པ་དང་། རང་བཙན་དང་། མི་རྟག་པ་དང་། འདུས་བྱས་དང་། བདེན་གྲུབ་རྣམས་དོན་ཅིག
04:02རྟོག་པས་བཏགས་པ་ཙམ་དུ་གྲུབ་པའི་ཆོས་དེ་ཀུན་རྫོབ་བདེན་པའི་མཚན་ཉིད། དངོས་མེད་ཀྱི་ཆོས་དང་ཀུན་རྫོབ་བདེན་པ་དང༌། སྤྱི་མཚན་དང༌། རྟག་པ་དང༌། འདུས་མ་བྱས་ཀྱི་ཆོས་དང༌། [བ]རྫུན་པར་གྲུབ་པ་རྣམས་དོན་གཅིག
04:11ཨིའི་་་་་ད་བདེན་གཉིས་ཀྱི་སྒྲ་བཤད། འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ཆོས་ཅན། 
04:21ཀུན་རྫོབ་བདེན་པ་ཞེས་བྱ་སྟེ། བློ་ཀུན་རྫོབ་པའི་ངོར་བདེན་པའི་ཕྱིར། ད་རྟོག་པ་ཨིའི་སྒྲ་དོན་ད་སྒྲ་དོན་སྣང་བ་ཟེར་དགོས་རེད་པས། ད་གང་ལྟར་དེ་འདྲ་ཡི།
04:30དོན་སྤྱིས་བསླད་བསྡད་མཁན་གྱི་དེ་འདྲ་འདྲ་བོའི་ཨིའི་བློ་འཁྲུལ་པ་ཟེར་དགོས་མེད་འགྲོ། [འདྲོ་]ད་བློ་ཀུན་རྫོབ་པའི་ངོར་བདེན་པའི་ཕྱིར་རོ། །
04:40འདིའི་ཀུན་རྫོབ་པ་ནི་རྟོག་པ་སྟེ། རང་མཚན་མངོན་སུམ་དུ་མཐོང་བ་ལ་སྒྲིབ་པས་ན་ཀུན་རྫོབ་པ་ཞེས་བྱའོ། །
04:48ད་རང་མཚན་ཟེར་ཡག་དེ་ཁོ་དོན་གྱིས་[གྱི]་ག་རེ་ཟེར། གང་ཕྱིར་དངོས་ཀུན་རང་བཞིན་གྱིས། །
རང་རང་ངོ་བོ་ལ་གནས་ཕྱིར། ། བྱས་ནས་[ནི་]གསུང[ས]་བསྡད་ཡག་གི་རང་རང་གི་རང་མཚན་གི
04:58ངོ་བོ་འདྲ་བོ་རེ་རེ་ཡོད་བསྡད་པ། ད་དེ་མཐོང་བ་ལ་སྒྲིབ་པར་བྱེད་མཁན་དོན་སྤྱིས་བསླད་ནས་ཁོ་སྒྲིབ་པར༌བྱེད་ཀྱི་ཡོད་པ་ཡིན་དུས་རང་མཚན་མངོན་སུམ་དུ་མཐོན་བ་ལ་སྒྲིབ་པས་ན་ཀུན་རྫོབ་པ་ཞེས་བྱ་བའོ།
05:09།འདི་ཡང་སྒྲ་བཤད་ཙམ་ཡིན་[གྱི]གྱིས། བློ་ཀུན་རྫོབ་པ་རྟོག་པའི་ངོར་བདེན་པ་ཡིན་ན། ཀུན་རྫོབ་བདེན་པ་ཡིན་པས་ཁྱབ་པ་མེད་དེ། དོན་དམ་བདེན་པའི་མཚན་གཞི་བུམ་པ་ལྟ་བུ་ཡང༌། བློ་ཀུན་རྫོབ་པ་རྟོག་པའི་ངོར་བདེན་པའི་ཕྱིར།
05:19གང་ཟག་གི་བདག་དང༌། སྒྲ་རྟག་པ་ལྟ་བུ་བློ་ཀུན་རྫོབ་པ་རྟོག་པའི་ངོར་བདེན་པ་ཡང་། [ཡིན་ཡང༌།] ཐ་སྙད་དུ་ཡང་མ་གྲུབ་པའི་ཕྱིར། བུམ་པ་ལ་དོན་དམ་བདེན་པ་ཞེས་བྱ་སྟེ།
05:28བློ་དོན་དམ་པའི་ངོར་བདེན་པའི་ཕྱིར། འདིའི་བློ་དོན་དམ་པ་ནི། སྣང་ཡུལ་ལ་མ་འཁྲུལ་བའི་ཤེས་པ་ལ་བྱའོ། །
05:36བདེན་གཉིས་ཀྱི་འཇོག་ཚུལ་འདི་རིགས་པའི་རྗེས་འབྲང་གི་མདོ་སྡེ་པའི་ལུགས་ཡིན་ལ། ཨིའི་ལུང་གི་རྗེས་འབྲང་གི་མདོ་སྡེ་པས། 
05:43བདེན་གཉིས་ཀྱི་རྣམ་གཞག་སྔར་བྱེ་སྨྲས་ལུགས་ཀྱི[ས]་ད་བདེན་གཉིས་ཀྱི་རྣམ་གཞག་བཤད་པ་དང་མཐུན་པ་ཁས་ལེན་ནོ།གསུངས་ཤག འོ་ཡ།
05:52ད་འདིར་རང་སྤྱི་གཉིས་ཟེར་བསྡད་ཡག་དེ། རང་མཚན་དང་སྤྱི་མཚན་ཟེར་བསྡད་ཡག་གི་ད་དོན་དམ་པར་དོན་བྱེད་ནུས་པའི་ཆོས། [དེ།] རང་མཚན་གྱི་མཚན་ཉིད།
06:02ད་དངོས་པོའམ་གཅིག་དོན་བྱེད་ནུས་པ་ཟེར་ལབ་དུས་ཁོ་རང་ཕ་གིའི། ཕན་གནོད་འདྲེན་མཁན་ཞིག་ཡོང་བསྡད་གི་འདུག་ག ད་དེ་དོན་དམ་པར་དོན་བྱེད་ནུས་པ་རང་མཚན་རེད་ཟེར། 
06:12མཚན་གཞི་ནི་བུམ་པ་ལྟ་བུ། དོན་དམ་པར་དོན་བྱེད་མི་ནུས་པའི་ཆོས་དེ། སྤྱི་མཚན་གྱི་མཚན་ཉིད། མཚན་གཞི་ནི། ད་འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ། ད་རང་འཛིན་པའི་རྟོག་པ་སྐྱེ་ཡག་དེ་འདྲ་ད་གཅིག
06:21འདི་ཡང་ད་བྱེད་པ་ཟེར་གྱི་ཡོད་ན་མེད་ན་མི་ཤེས་ཏེ། ད་གང་ལྟར་དེ་འདྲའི[་ཡི་]རྒྱུ་འབྲས་ཀྱི་དོན་བྱས་པའི་བྱ་བ་བྱེད་ཡག་ཞེ་དྲག་ཡོད་མ་རེད་པ།
06:28ད་འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ལྟ་བུ། ད་སྤྱི། བྱེ་བྲག་ཟེར་ཡག་དེ་ཚོའི་གྲས་[གྲལ]་རྟོག་པས་བཀོད་བཞག་པ་ཞིག་རེད་འདུག་ག རྟོག་པས་བཀོད་བཞག་པ་གཅིག་མ་གཏོགས།[ཏོག]
06:36དངོས་པོའི་རང་མཚན་འདྲ་བོ་རང་བཞིན་འདྲ་བོ་འདི་འདྲ་གཅིག་གི་བཞག་ཡག་ཡོད་མ་རེད་པ། སྤྱི་དང༌། བྱེ་བྲག་དང༌། ལྡོག་པ་དང་།
06:44ད་གཅིག་དང་ཐ་དད་ཟེར་དབྱེ་བ་ཕྱེ་ཡག་དེ་གའི་[རྒྱས་]དེ། བློས་ཕར་བཅོས་ནས་[ནི་]བློས་བཏགས་ནས། ཨིའི་[ནི་དོན་དེ་གའི་[རྒྱས་]དེ་བཞག་ཡོང་གི་ཡོད་རེད་པ་ད།
06:54ད་བློས་རྟོགས་ཡག་ད་ཡོད་རེད་ཡིན་ནས་[ནའི]་དེ་[རྒྱས་]གའི་དེ་ཁོ་ངོ་བོ་འདྲ་བོ་དེ་བཞག་ཀ་ཕྱིན་པ་ཡིན་ན། བློས་ཕར་བཏགས་བཞག་པ་ཞིག་མ་གཏོགས་[ཏོག་]དོན་[གྱི]་གྱིས་ངོས་ནས་ག་རེ་ཟེར་བ་[དགོས]་རེད་ད། ད་དོན་གྱི་ངོས་ནས་ཟེར་དགོས་རེད་པས་ད་ཡང་གང་ལྟར།
07:04ཨིའི་གཅིག་གི་ཕན་ནུས་ཀྱི་ཞུ་དགོས་རེད་པས་ད། རྒྱུ་འབྲས་ཀྱི་རྒྱུ་འབྲས་ཀྱི་དེ་འདྲའི་སྐྱེ་བྱ་སྐྱེ་བྱེད་ཀྱི་བཟོ་འདྲ་བོ་དེ་འདྲ་ཡིས་བྱ་བ་བྱེད་ཐུབ་ཡག་ཅིག་མེད་པ་ཡིན་དུས་ཙ་ནས།
07:14སྤྱི་མཚན་དུ་གསུང་ཀི[ས་ཀྱི་]ཡོད་པ་རེད། གཅིག་དང་ཐ་དད། འགལ་བ་དང་འབྲེལ་བ་ལ་སོགས་པ་སྒྲོ་བཏགས་པའི་ཆོས་རྣམས་སྤྱི་མཚན་ཡིན་མོད་ཀྱང༌། དེ་དག་ཡིན་ན་སྤྱི་མཚན་ཡིན་མི་དགོས།
07:23དེ་མཚན་གཞི་བཞག་ག་[པར་]ཕྱིན་པ་ཡིན་ན་ཡང་ཁོ་འདུས་བྱས་ཀྱི་ཆོས་བཞག་ཐུབ་ཀྱི་རེད་པ། དོན་བྱེད་ནུས་པས་ཆོས་བཞག་ཐུབ་ཀྱི་རེད་པ། རྣམ་འགྲེལ་ནས་ག་རེ་ཟེར།
07:30མཁས་པ་རྣམས་ཀྱིས་བྱས་པ་ཡིན། ། གསུངས་པ་ནང་བཞིན་དེ་འདྲ་གཅིག་ཡོང་གི་འདུག་ག ད་ཁོ་ཐ་སྙད་འདྲ་མི་[མིན]་འདྲ་དེ་གའི་[རྒྱས་]དེ་ད་ལྟ་བློས་ཡིད་བློ་རྟོག་པ་ཟེར་ཡག་དེ་འདུ་ཤེས་གཡེར་པོ་ཞེས་གསུངས་ནས།[ནི།]
07:39ཁོས་སྤུ་རིས་མང་པོ་ཕྱེ་ནས་ད་གཤམ་དེ[ར་]ནས་མར་གཞན་སེལ་ཟེར་ཡག་དེ་ཐོན་ཡོང་གི་རེད། འོ་ད་ཁོས་གཅིག་རྟོག་པས་ཡུལ་དེ་དང་དེ།
07:47སྤུ་རིས་རུ་འདྲ་ཕར་ཆ་ཕྱེ་ནས། [ཨ་]ཨེ་ནི་ཡུལ་གྱི་ཡུལ་གྱི་ཁྱད་ཆོས་བྱེ་བྲག་པ་གཅིག་[ཞིག་]བློས་བཟུང་ཡོང་གི་ཡོད་རེད་པ། རྟོག་པ་ཟེར་དུས་ཙ་ནས།[ནི།]
07:57དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་འོ་ད་དེ་འདྲས་རྟོག་པས་བྱས་བཞག་པ་གཅིག་དང་འབྲེལ་ག་རེ་ཟེར་གཅིག་དང་ཐ་དད་ཟེར་ཡག་འདྲ་བོ། གཅིག་འགལ་བ་འབྲེལ་བ་ཟེར་ཡག་འདྲ་བོ་དེ་འདྲ་ད་ཕྱེ་བསྡད་ཡག་དེ་ཚོའི་གྲས་[གྲལ་]དེ་སྤྱི་མཚན་རེད་བྱས་ཡིན་པ་རེད།
08:07ད་དེ་ནས་དགག་སྒྲུབ་གཉིས་སེ།[ཟེ།] དགག་བྱ་དངོས་སུ་བཅད་པའི་ཚུལ་གྱིས་རྟོགས་པར་བྱ་བ་དགག་པའི་མཚན་ཉིད།
08:16དགག་སྒྲུབ་གཉིས་ཟེར་ཡག་ད་དགག་པ་ཟེར་ཡག[་གང་འདྲ་]ག་འདྲས་རེད་ཟེར་ལབ་ན། གང་ལྟར་དོན་དེ་ད་དོན་དེ།
08:25བློ་ལ་ཡ་ཤར་ཡོང་དུས་ཙ་ནས་གཅིག་ཡིན་གཅིག་མིན་གཅིག་དེ་དགག་བྱ་གཅིག་ཕར་བསལ་ནས། དགག་བྱ་བཅད་སྟོབས་ཀྱིས་སྒོ་ནས།
08:35བློ་ལ་ཤར་དགོས་ཡག་ཅིག་ཡིན་པ་ཡིན་ན་དགག་པ། དཔེར་ན་བུམ་པ་མེད་པ། དཔེར་ན་ག [...]

2023-04-03 08:51 UTC, Tenzindharten requested changes
00:00 ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་གི་སྐད་ཆ་བཤད་ཡོང་དུས་ཙ་ནས།
ཨིའི་ཆོས་ལུགས་དང་འབྲེལ་བ་སླེབ་ཀི་ཡོད་རེད།

00:07 ཨིའི་འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་ཡ། ད་ཨིའི། ད་ལོ་ཕེ་གིའི་སྟོང་ཕྲག་ཁ་ཤས་ཀྱི་རིང་ལ་ཡ།
གང་ལྟར་མིའི་སྤྱི་ཚོགས་ནང་ལོག་ལ་ཆོས་ཟེར་ཡག་ཅིག་བྱུང་ཡིན་པ་རེད།

00:19 ཨིའི་ད་ཆོས་རིགས་ཁ་ཤས་ཨིའི་ཞེ་དྲག་དེ་སེ་གལ་ཡོད་མ་རེད།
ད་གཅིག་ཨིའི་ད་གཅིག་ཉི་མ་གསོལ་ཡག་གི་བཟོ་འདྲ་བོ།

00:27 གཅིག་(ཅིག)་དེ་བ་གཅིག་ཨེ་ནི་ཨིའི་ག་རེ་ཟེར་བ་རེད།
ཕ་གིའི་མེ་མེ་མེ་ལ་ཡ་ད་གཅིག་ད་ག་རེ་ཟེར་བ་རེད། རྩ་ཆེན་པོ་བརྩི་ཡག་བཟོ་འདྲ་བོ།

00:36 ད་དེ་འདྲའི་མི་འདུག་སྟེ། ཨེ་ནི་གཅིག་ད་ཨིའི་ལྷ་ཡོད་རེད།
ཀླུ་ཡོད་རེད་ཟེར་ཡག་འདྲ་བོ་བཤད་ཀྱིས་དེ་འདྲའི་ཐོག་ནས།
གཅིག་དད་པ་བྱེད་བསྡད་ཡག་འདྲ་བོ་གཅིག་ཡོང་བསྡད་ཀི་འདུག་ག

00:45ད་དེ་གའི་དེ་ལ་ལྟ་གྲུབ་ཟེར་གལ་མི་འདུག་ག
གྲུབ་མཐའ་ཟེར་གལ་བཤད་ཡག་མི་གདུག་ག

00:49ད་ཨིའི། ད་གྲུབ་མཐའ་ཡོད་བསྡད་པའི་ཆོས་ལུགས་དེ་གའི་དེ།
ཕལ་ཆེར་རྒྱ་གར་ནང་ལ་ཆ་བཞག་ན་ཕལ་ཆེར་ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་ཕྱིན་པ་མིན་འགྲོ།

00:58ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་མཚམས་ནས། ཨེ་ནི་ད། ལྟ་གྲུབ་བཤད་ནས་དེའི་ཐོག་ནས་ཨིའི་ད་ཆོས་ཀྱི་ཨིའི་ག་རེ་ཟེར་བ་རེད་ཕ་གིའི།

01:08ད་ཆོས་དད་ཅིག་བཤད་ཡོང་གིན་ཡོད་རེད།

01:10ཨིའི་བྱས་ནས་དེ་འདྲའི། ད་་ལྟ་གྲུབ་ཡོད་བསྡད་མཁན་གྱི་ཕལ་ཆེར་ཆོས་ལུགས་གཙོ་ཆེ་བ་དེ་གའི་དེ།

01:19 ད་རྒྱ་གར་ནང་གི་ཆོས་ལུགས་ཆ་བཞག་ནས་འདྲ།
ཨེ་ནི་ཨིའི་རིམ་པས་གཅིག་གི་ཨི་ད་དཔེར་ན་འཇིའུ་ལ་ཆ་བཞག་ནས།

01:28འཇིའུ་སྡེ་ཟེའི་ཆ་བཞག་ནས་འདྲ། ཨེ་ནི་ཡེ་ཤུ་ཡིན་ནས་རེད། ཁ་ཆེ་ཡིན་ནས་རེད།
གཅིག་ད་ཨ་ག་རེ་ཡོད་རེད་ཨེ་ནི།

01:38ད་དེ་ལ་སོགས་པའི་གང་ལྟར་དེ་ལ་སོགས་པའི་ད་གཅིག་གྲུབ་མཐའ་ཡོད་བསྡད་མཁན་གྱི་ཆོས་ལུགས་དེ་གའི་དེ་ཚང་མ་ལོག་གིས་བསླབ་བྱ་རྒྱག་ཡག་དེ།
མི་སེམས་པ་བཟང་པོ་བྱེད་དགོས་རེད། བྱམས་པ་དགོས་རེད།

01:48བརྩེ་བ་དགོས་རེད་ཟེར་ཡག་དེ་བཟོད་པ་དགོས་རེད། ཆོག་ཤེས་དགོས་རེད།
ཨེ་ནི་རང་རང་གི༌ཕ་གིའི་བསླབ་པ་སྲུང་དགོས་ཀྱི་རེད།

01:56རང་རང་གི་ཆོས་ལུགས་ནས་བཤད་བཞག་པའི་བསླབ་པ་སྲུང་དགོས་ཀི་རེད་ཟེར་བྱས་ནས་བཤད་བསྡད་མཁན་གཅིག་ཚང་མ་གཅིག་པ་རེད་འདུག་ག
དེ་འདྲས་ཡིན་དུས་ཆོས་ལུགས་ཁག་དེ་གའི་དེ་ཡིས་སྙིང་པོ་ག་རེ་བཤད་ཀི་ཡོད་རེད་ཟེར་ལབ་ན།

02:06མི་ལ་ལྷན་སྐྱེས་ཀི་ཡོད་བསྡད་པ་དང་།ལྷན་སྐྱེས་ཀི་ཡོད་བསྡད་པའི་ཐོག་ལ་མི་ལ་དགོས་མཁོ་ཡོད་བསྡད་པའི་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གལ་ཆེན་པོ་ཡིན་པ་གཅིག་ཆོས་ལུགས་ཚང་མས་བཤད་ཀི་འདུག་ག

02:15
ད་བྱམས་པ་དང་བརྩེ་བ་ཨ་སྒྲུབ་སྟངས་དེ་ལ་ཨེ་ནི་ཨིའི་ཐབས་ཤེས་མི་འདྲ་བ་བྱས་ཀྱིས།

02:24རིགས་གཅིག་གིས་འཇིག་རྟེན་བཀོད་པ་པོ་ཡོད་རེད་ཟེར་བྱས་ནས། [ནི།]
འཇིག་རྟེན་བཀོད་པ་པོ་དེ་བརྩེ་བའི་བདག་ཉིད་རེད། མཁྱེན་པའི་བདག་ཉིད་རེད། ཇི་ཙམ།
དེ་འདྲས་ཡིན་དུས་ཙ་ནས།

02:34འཇིག་རྟེན་བཀོད་པ་ལ་ང་ཚོས་བརྩེ་བ་བྱེད་དགོས་རེད། དད་པ་བྱེད་དགོས་རེད།
གུས་པ་བྱེད་དགོས་རེད། ཇི་ཙམ་གྱིས་འཇིག་རྟེན་བཀོད་པ་པོ་ལ་ཡ།
དད་པ་དང་བརྩེ་བ་དང་གུས་བྱས་པ་དེའི་ཚོད་ཀྱིས།

02:43རང་ཉིད་ཀིས་ཨེ་ནི་གཅིག་དད་པ་དང་། གཅིག་བརྩེ་བ་ཟེར་ཡག་དེ་ཚོའི་གྲས།
རང་ཉིད་ཀྱིས་ད་ཉམས་ལེན་བྱེད་དགོས་ཡག་ཅིག་དང་།

02:49
ཨེ་ནི་འཇིག་རྟེན་བཀོད་པ་པོ་གཅིག་གིས་བཀོད་བཞག་པའི་ང་རང་ཚོ་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་ཨེ་ནི་གཅིག་བརྩེ་བ་བྱེད་དགོས་རེད་ཟེར་ཡག་ཅིག

02:56
དཔེར་ན་ད་ལྟ་འདིའི་མུ་སི་ལིམ་ད་ལྟ་འདི་ཀོ་རན་ནང་ལོག་ལས་འདི་འདྲས་བཤད་ཀིས་བཤད་ཀི་ཡོད་པ་རེད།

03:03ངས་ད་ལྟ་ཁ་ཆེ་ངོ་ཤེས་པ་གཅིག་སྐད་ཆ་བྱུང་།
ཁ་ཆེ་བླ་མ་གཅིག་སྐད་ཆ་བྱུང་། ཨེ་ནི་ཀོ་རན་ནང་ལོག་ལ་ཡ་ཨེ་ནི།

03:10
འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པའི་ད་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་ང་ཚོ་བྱམས་བརྩེ་བྱེད་དགོས་རེད་ཟེར་བྱས་ནས་དེ་འདྲ་ཡོད་རེད་སེ།

03:20སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས། སྒྲུབ་བྱེད་འདི་འཇིག་རྟེན་བཀོད་པ་ཡིས་བཀོད་ནས།
འཇིག་རྟེན་བཀོད་པ་པོ་ཟེར་ཡག འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པ་རེད་ཟེར་ཡག་དེ།
སྒྲུབ་བྱེད་དེ་འདྲའི་གཅིག་བཀོད་ཀི་ཡོདརེད།

03:29བཀོད་པའི་གྲུབ་དོན་སྙིང་པོ་འདྲ་བོ་དེ།
ཨི་བྱམས་པ་དང་བརྩེ་བ་དང་དེ་ཚོ་དགོས་ཀི་རེད་ཟེར་ཡག་ཅིག

03:34ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གཅིག་པོ་ཡིས་འདང་གི་ཡོད་མ་རེད།
ང་ཚོ་ད་ག་རེ་བྱས་ནས་ཡང་མི་མཐུན་པ་དང༌།
འཁྲུག་པ་རྒྱག་ཡག་ཡོང་གིན་་ཡོད་པ་ཡིན་དུས། ཨེ་ནི་བཟོད་པ་དགོས་རེད།

03:44ཨིའི་གཅིག་ག་རེ་ཟེར་བ་རེད།
ཕ་གིའི་ཨེ་ནི་ཆོག་ཤེས་དགོས་རེད་ཟེར་ཡག་དེ་ཚོའི་གྲས་ཀྱི་བསླབ་བྱ་དེ་སླེབ་ཡོང་གིན་འདུག་ག
སྙིང་པོ་སྙིང་པོ་དེ་བྱམས་བརྩེའི་སྒང་ལ་ཡ་སྐད་ཆ་བཤད་ཀི་ཡོད་རེད་བ། 
03:52
སེ་དེ་འདྲས་[འདྲ]་ཡིན་པ་ཡིན་དུས་ཙ་ནས།
ད་ལྟ་དུས་རབས་ཉི་ཤུ་རྩ་གཅིག་པ་གཅིག་ཚན་རིག་ཡར་རྒྱས་ཧ་ཅང་ད་ཚད་མཐོན་པོ་སླེབས་བསྡད་པ།

04:01གཅིག་དངོས་པོ་ཡར་རྒྱས་སྤྱིར་བཏང་བཤད་པ་ཡིན་ན།
ཧ་ཅང་གི་ད་ཚད་མཐོ་པོ་སླེབས་བསྡད་པའི་དུས་རབས་འདིའི་ནང་ལ་ཡིན་ནས།
འཛམ་གླིང་ཤར་ནུབ་ག་ས་ག་ལ་ཡ་ཆོས་ལ་ཡ་དོ་སྣང་བྱེད་མཁན་གཅིག

04:12འཛམ་བུ་གླིང་འདིའི་སྒང་གི་མི་མང་བ་དེ་གའི་དེ།
ཆོས་ལ་དད་པ་ཅིག་ཡོད་མེད་མི་ཤེས་ཏེ།
ད་གང་ལྟར་ཆོས་ལ་དད་པ་བྱེད་མཁན་འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་མང་པོ་གཅིག་དུས་ད་ལྟ་ཡིན་ནས་ཡོད་བསྡད་པ་རེད།

04:21དེ་ཁྲལ་དང་ཁྲིམས་ཀྱི་ཐོག་ནས་བཟོས་པ་གལ་མ་རེད།
རང་བཞིན་གྱིས་མི་ལ་ཡ་ཁོ་ཕན་ཐོགས་གཅིག་ཡོད་བསྡད་པ་གཅིག་དང་།
ཁོ་དགོས་མཁོ་ཡོད་བསྡད་པ་་གཅིག་མཐོང་བ་ཡིན་དུས་ཙ་ནས།

04:29 མི་རིགས་གཅིག་གིས་ཆོས་ལ་ཡ་དོ་སྣང་བྱས་བསྡད་ཡག་ཅིག་ཆགས་བསྡད་ཀི་་ཡོད་རེད་བ།
དེ་འདྲས་ཡིན་དུས་ཙ་ནས།

04:34སྙིང་པོ་འདི་དངོས་པོ་ཡར་རྒྱས་ཀྱིས་ལུས་པོ་བདེ་ཐང་བཟོ་ཡི་ཡོད་རེད།
ལུས་པོའི་གཅིག་ཕ་གིའི།

04:43ཚོར་བ་བདེ་སྐྱིད་ཡོང་ཡག་གི་གང་ལྟར་ཆ་རྐྱེན་དེ་གའི་དེ་དངོས་པོ་ཡར་རྒྱས་ཀྱི་ཐོག་ནས་སྒྲུབ་བསྡད་ཀི་ཡོད་རེད།
ངེས་པར་དུ་དགོས་ཀི་ཡོད་རེད། ཨིའི་ད་ག་ནང་བཞིན་གྱི

04:52ལུས་པོའི་བདེ་ཐང་གཅིག་པོ་ཡིས་ང་ཚོར་འདང་གི་ཡོད་མ་རེད།
ག་རེ་ཟེར་ལབ་ན་ནང་རྣམ་པར་རྟོག་པའི་རྐྱེན་པས་ཡང་དགའ་སྡུག་མང་པོ་ཞིག་ཡོང་གི་ཡོད་རེད།

05:01དེ་འདྲ་དེ་རྣམ་པར་རྟོག་པ་ཁོ་རང་གི་ཐོག་ནས་ཐབས་ཤེས་ཤིག་བཙལ་ནས།
05:07རྣམ་རྟོག་གི་ཨེ་ནི་ཐོག་ནས་གཅིག་དགའ་པོ་ཡོང་བསྡད་ཡག
རྣམ་རྟོག་གི་ཐོག་ནས་མི་དགེ་བ་ཡོང་བསྡད་ཡག་དེ་ལ།
རྣམ་རྟོག་ཁོ་རང་གི་ཐོག་ནས།
05:17དགའ་སྡུག་གི་ག་རེ་ཟེར་བ་རེད།
ཕ་གིའི་ག་རེ་ཟེར་བ་རེད།
ད་དགའ་སྡུག་གི་རྒྱུ་རྐྱེན་གཅིག་རྣམ་རྟོག་ཁོ་རང་ངོས་ནས་བསྒྲུབ་རྒྱུ་རེད་མ་གཏོགས།
05:24ནང་གི་སེམས་ཀི་དགའ་སྡུག་བྱུང་བསྡད་པ་དེ་ལ་ཁབ་བརྒྱབས་ནས་ཕན་ཡག་ཅིག་དང་།
གཅིག་བཤགས་བཅོས་བྱས་ནས་ཕན་ཡག་འདྲ་བོ་གཅིག་དང་།
དངུལ་མང་པོ་ཡོད་ན་དེས་སེལ་ཡག་ཅིག་མི་འདུག་ག
05:33རེད་བ། ཨོ་ཧུ།ཨོ་ཧུ། ལུས་པོའི་དཀའ་སྡུག་སྡུག་བསྔལ་ཟེར་ཡག་དེ་གའི་དེ། དཔེར་ན།
འཚོ་བས་ཕོངས་པའི་སྡུག་བསྔལ་གྱིས་མཚོན་པས།
གཅིག་ཚ་གྲང་གི་སྡུག་བསྔལ་གྱིས་མཚོན་པས།
05:43དེ་འདྲས་ཀི་སྡུག་བསྔལ་དེ་གའི་དེ་དངུལ་ཡོད་ན།
ཨེ་ནི་ཁོ་གང་ལྟར་ཨེ་ནི་སྨན་བཅོས་བྱེད་ཡག་གི་མཚོན་པས།
གཅིག་ཟ་བཏུང་ལོངས་སྤྱོད་ཨེ་ནི་ཕུན་སུམ་ཚོགས་པ།
05:52ད་ག་ནང་བཞིན་གི་གནས་ཁང་ཕུན་སུམ་ཚོགས་པ།
ཁོར་ཡུག་ཕུན་སུམ་ཚོགས་པ། གཉེན་ཉེ་དུ་ཕུན་སུམ་ཚོགས་པ།
དེ་འདྲས་གཅིག་གི་ངང་ནས་ལུས་པོའི་བདེ་ཐང་དེ་སྒྲུབ་ཐུབ་ཀི་ཡོད་རེད།
06:01ལུས་པོའི་བདེ་སྐྱིད་དེ་བསྒྲུབ་ཐུབ་ཀི་ཡོད་རེད།
ཨ་ད་ཡིན་ནས་ཨིའི་་ཨིའི་གཅིག་ཕྱི་ཡི་ད་དངུལ་དང་དངོས་པོ་ལ་བརྟེན་ནས།
06:11སྒྲུབ་ཐུབ་ཡག་ཡོད་བསྡད་པའི་ཆ་རྐྱེན་དེ་གའི་དེ་ཕུན་སུམ་ཚོགས་པོ་ཞིག་ཡོད་པ་ཡིན་ནས་སེམས་འཁྲུགས་བྱས།
མ་སྐྱིད་པ་བྱེད་བསྡད་མཁན་མང་པོ་ཡོང་གིན་འདུག་ག
06:20བྱས་ཙང་དེ་འདྲས་ཀི་ད་སེམས་འཁྲུག་བསྡད་ཡག་གི་མ་སྐྱིད་པ་ཡོང་བསྡད་ཡག་དེ་ཕྱི་དངོས་པོའི་མཐུན་རྐྱེན་མ་འདང་བའི་རྐྱེན་བྱས་ནས་དཀའ་ངལ་བྱུང་བ་མ་རེད།
06:29ནང་བསམ་བློ[འི་]གཏོང་སྟངས་ཀིས་གཅིག་མ་འགྲིགས་ནས་ཨེ་ནི་སེམས་འཁྲུག་བསྡད་པ་ཡིན་པ་རེད།
སེ་དེ་འདྲས་ཡིན་དུས་ནས།
06:36གང་ལྟར་ང་རང་ཚོས་དོན་གཉེར་བྱེད་ཡག་གི་སེལ་རྒྱུའི་སྡུག་བསྔལ་དང༌།
བསྒྲུབ་རྒྱུའི་བདེ་སྐྱིད་ལ་ཡ།
06:45གཙོ་བོ་ལུས་ཚོར་ལ་བརྟེན་བསྡད་པའི་ཨེ་ནི་བདེ་སྡུག་ཅིག་དང༌།
གཙོ་བོ་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་ཅིག་གཉིས་ཡོད་བསྡད་པ་དེ་གསལ་པོ་རེད་འདུག་ག
06:53སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ད་དེ་གཉིས་པོ་དེའི་ནང་ནས་ག་རེ་གལ་ཆེ་ཡི་རེད་ཟེར་ལབ་ན།
07:01ག་གིའི་[སྦེ་]་གལ་འགངས་འདྲ་བོ་ཆེ་གི་རེད་ཟེར་ལབ་ན།
ཕལ་ཆེར་ནང་བསམ་བློའི་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་དེ་ཕལ་ཆེར་འགངས་ཆེ་བ་རེད་བཞག
07:09དེ་ཡིན་པའི་རྒྱུ་མཚན་ག་རེ་རེད་ཟེར་ལབ་ན།
ཨིའི་ལུས་པོའི་དཀའ་ངལ་མང་པོ་གཅིག་སེམས་ཀྱིས་ཨེ་ནི་ཚེམས་པ་དེ་གིས།

07:18ལུས་པོའི་དཀའ་ངལ་ཟིལ་གྱིས་གནོན་་ཐུབ་ཀི་འདུག་ག ལུས་པོའི་གཅིག་དཔེར་ན་གཅིག
དཔེར་ན་ང་རང་ཚོའི་གཅིག་སོ་སོ་ཆབ་སྲིད་ཀྱི་དམིགས་ཡུལ་འདྲ་བོ།

07:29
གཅིག་ད་ག་ནང་བཞིན་གི་གཅིག་སོ་སོའི་ད་གཅིག་ད་གང་ལྟར་དམིག་ཡུལ་འདྲ་བོ་ཡང་ད་ག་ནང་བཞིན་དཔེར་ན་རྩེད་མོ[འི]་གཅིག་ད་འགྲན་བསྡུར་གི་ཐོག་ནས།

07:39
གཅིག་མིང་བླང་ཡག་གི་བཟོ་འདྲ་བོ་གཅིག་དེ་འདྲས་ཀི་གང་ལྟར་བསམ་བློའི་ཐོག་ནས་དོན་དུ་གཉེར་བའི་དོན་དག་ཅིག་འགྲུབ་ཡག་གི་དོན་དག་ལ།

07:49ལུས་པོས་དཀའ་ལས་ཞེ་བོ་རྒྱག་ཐུབ་མཁན་ཡོང་གི་འདུག་ག

07:52
ད་ག་ནང་བཞིན་ང་རང་ཚོས་ཆོས་ཉམས་ལེན་བྱེད་མཁན་གཅིག་གིས་ནང་བསམ་བློའི་ཐོག་ནས་གཅིག་གི་ཐར་པ་དང་ད་ཐར་པ་ཐམས་ཅད་མཁྱེན་པ་ད་གང་ཤེས་ཏེ་ད་སྔོན་ལ་སྤྱིར་བཏང་འདྲ་བོ་བཤད་པ་ཡིན་ན།

08:02གང་ལྟར་ནང་ཆོས་ཕྱོགས་ཀི་ཐོག་ནས།
ཡང་སོ་སོའི་དམིགས་ཡུལ་གཅིག་བསྒྲུབ་ཡག་ཅིག་བཞག་ནས།
དེ་བསྒྲུབ་ཡག་གི་ཆེད་དུ་ལུས་པོའི་དཀའ་ངལ་དང་དུ་ལེན་ནས།

08:10དང་དུ་ལེན་ནས་དཀའ་ངལ་ཁྱད་དུ་བསད་པ་མང་པོ་ཞིག་ཡོང་གི་འདུག་ག
དེ་གའི་དེ་ཁོ་དང་དུ་བླངས་ནས་དཀའ་ངལ་དེ་ཨེ་ནི་མྱོང་གི་ཡོད་རེད་མ་གཏོགས།

08:19མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་བྱུང་བ་མ་རེད་བ།
དེ་འདྲས་་ཡིན་དུས་ནང་སེམས་ཀྱིས་ཡིད་ཚིམས་པ་དེས་ལུས་པོ་ལ་བརྟེན་པའི་དཀའ་ངལ་དེ་སྡུག་བསྔལ་དེ་གའི་དེ།

08:30དང་དུ་བླང་ཐུབ་ཡག་ཡོང་གི་ཡོད་རེད་བ།
དེས་སེམས་ལ་མ་སྐྱིད་པ་ཡོང་རྒྱུའི་ཚབ་ལ་སེམས་ལ་ལྷག་པར་དུའང་ཡིད་ཚིམས་པ་ཡོང་ཡག་ཅིག་ཡོང་ཡག་འདུག་ག

08:39
ད་དེ་ལས་ལྡོག་ནས་ནང་བསམ་བློ་འཁྲུག་བསྡད་ཡོད་ན། ཕྱི་ཡི་དངོས་པོའི་མཐུན་རྐྱེན་ག་ཚད་ཀི་བཟང་པོ་ཞིག་ཡོད་པ་ཡིན་ནས།

08:47དེས་ [...]

2023-04-04 04:00 UTC, tsultrim-dolma commented
00:00ད་དེ་འདྲ་ཡིན་དུས་ཙ་ནས། ཨེ་ནི་ཨི་ཀླུ་སྒྲུབ་ཡབ་སྲས་ལ་སོགས་པ།
འོ་ད་དེ་གའི་དེ་གི ཨིའི་དཔེར་ན་ད་ཀླུ་སྒྲུབ་ཀྱིས
00:09གང་གི་ཐུགས་བརྩེས་ཉེར་བཟུང་ནས། །
ལྟ་བ་ཐམས་ཅད་སྤང་པའི་ཕྱིར། །
དམ་པའི་ཆོས་ནི་སྟོན་མཛད་པ། །
གཽ་ཏམ་དེ་ལ་ཕྱག་འཚལ་ལོ། །
ཞེས་གསུངས་ཡག་དེ་དང༌། ཨེ་ནི་རྩ་བ་ཤེས་རབ་ཀྱི་དབུ་དེ་ལ་ཡ།
00:18གང་གིས་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང༌། །འགག་པ་མེད་པ་སྐྱེ་མེད་པ། །
ཆད་པ་མེད་པ་རྟག་མེད་པ། །འོང་བ་མེད་པ་འགྲོ་མེད་པ། །
ཐ་དད་དོན་མིན་དོན་གཅིག་མིན། །སྤྲོས་པ་ཉེར་ཞི་ཞི་བསྟན་པ། །
རྫོགས་པའི་སངས་རྒྱས་སྨྲ་རྣམས་ཀྱི། །དམ་པ་དེ་ལ་ཕྱག་འཚལ་ལོ། །ཟེར་བྱས་ནས།
00:27ཨི་དེ་འདྲའི་བསྟོད་ཕྱག་མཛད་སའི་ཡུལ་དེ་ད་བསམ་གྱིས་མི་
ཁྱབ་པ་གཅིག་ཡིན་པ་གཅིག་ཨེ་ནི་ཚོད་དཔག་བྱེད་ཐུབ་ཡག་ཅིག་འདུག་ག
00:33ཨོ་ད་དེ་ད་ཁྱད་མཚར་གཅིག་ཡོད་ས་རེད། མི་འདྲ་བ་གཅིག་ཡོད་ས་རེད་
བསམ་པ་དྲན་ཡག་ཅིག་འདུག་ག
00:37དེ་འདྲས་ཡིན་དུས་ཙ་ནས་ཨི་ཨེ་ནི། ཨི་ཨི་དེ་འདྲས་ཡིན་དུས་ལོ
་ཉིས་སྟོང་ལྔ་བརྒྱའི་གོང་དུ་བྱུང་བཞག་པའི་སངས་རྒྱས་བཅོམ་ལྡན་འདས་དེ།
00:47མི་ཕལ་པ་གཅིག་ད་མིན་པ་གཅིག་མི་རང་དགའ་བ་མིན་བསྡད་པ་གཅིག་ད་ཚོད་དཔག་བྱེད་ཐུབ་ཡག་རེད།
དེ་ཙམ་དུ་མ་ཟད་པའི་ཨེ་ནི།
00:57ཉན་ཐོས་སྡེ་པའི་གཞུང་ནས་བཅོམ་ལྡན་འདས་ཨེ་ནི་རྒྱ་གར་ལ་འཁྲུངས་དུས་ཙ་ནས།
ཨེ་ནི་ད་ཚེ་འདི་ལ་གསར་དུ་སངས་རྒྱས་མཁན་གྱི་བྱང་ཆུབ་སེམས་དཔའ་སེམས་ཅན་གཅིག་བྱས།
ད་དེས་ཨེ་ནི་རྡོ་རྗེ་གདན་གྱི་གནས་ལ་ཡ་ཨེ་ནི།
01:16སྔོན་ལ་ཐོག་མར་ད་ག་རེ་ཟེར་བ་རེད་ཕ་གིའི་ལོ་དྲུག་དཀའ་སྤྱད་དེ་ཚོ་མཛད།
མཐར་ཨེ་ནི་རྡོ་རྗེ་གདན་གྱི་གནས་ལ་མངོན་པར་རྫོགས་པ་སངས་རྒྱ
ས་པའི་མཛད་པ་མཛད་ཡག་དེ།
01:25འོད་རེ་ད་དེ་ནས་སངས་རྒྱས་པའི་མཛད་པ་མཛད་ནས་དེ་ནས་ད་གཅིག་
ག་ཚད་རེད་ལོ་བཞི་བཅུ་ཞེ་གྲངས་གཅིག ཨེ་ནི་སེ་ད་སེ་སངས་རྒྱས་གནང་བྱས་ད།
01:35ད་སེམས་ཅན་ལས་ཡོངས་སུ་འདས་ནས་སངས་རྒྱས་ཆགས་ནས་ལོ་བཞི་བཅུ་ཞེ་གྲངས་ཤིག་བཞུགས།
དེ་ནས་ཨེ་ནི་སངས་རྒྱས་ཚར་བའི་དེ་ནས་
01:44ག་རེ་ཟ་རྩྭ་མཆོག་གྲོང་ལ་ཡ་ཨེ་ནི་མྱ་ངན་ལས་འདས་པའི་རྗེས་ལ།
ཨེ་ནི་བདུད་བཞི་ཁར་བཅོམ་ནི། འཆི་བདག་གི་བདུད་བཅོམ། ཕུང་པོའི་བདུད་བཅོམ་ནས།
01:52ད་དེ་ནས་ཕུང་པོ་ལྷག་མ་མེད་པ་ཨེ་ནི་མྱང་ངན་ལས་འདས་པ་རེད་ཟེར།
དེ་ནས་ཨེ་ནི་མར་མེ་ཤི་བ་ནང་བཞིན་རིག་པ་རྒྱུན་ཆད་པ་རེད་ཟེར་
བྱས་ནས་ད་བཤད་བསྡད་ཡག་ཅིག་ཡོད་རེད་པ།
02:01ད་འདི་ཨེ་ནི་རྒྱུ་མཚན་མི་ལྡན་པ་ཞིག་ཆགས་ཀི་ཡོད་རེད།
འདིའི་བཤད་པ་བཤད་པ་ག་རེ་ཟེར་བཤད་སྟངས་འདི།
02:10ད་གཏི་ཐུག་ཆགས་པ་རེད། བསམ་བློ་ཞིག་བཏང་པ་ཡིན་ན།
བསྐལ་ཆེན་གྲངས་མེད་གསུམ་གྱི་བར་ལ་ཡ་ཚོགས་བསགས་ནས། རྒྱུ་རླབས་ཆེན་པོ་དེ་འདྲའི་
གཅིག་གིས།
02:20འབྲས་བུ་དེ་ལོ་བཞི་བཅུ་ཞེ་གྲངས་གཅིག་གི་ཨེ་ནི་མངོན་
པར་རྫོགས་པའི་སངས་རྒྱས་ནས་ལོ་བཞི་བཅུ་ཞེ་གྲངས་གཅིག་གི་
ད་སེམས་ཅན་གྱི་དོན་མཛད་ཡག་མ་གཏོགས་བྱུང་མེད་ན། རྒྱུ་འབྲས་གོ་འཛོལ་རེད་འདུག་ག
02:30རྒྱུ་ད་ག་འདྲ་བོ་གཅིག་ལ་བསླབས་ནས། བྱང་ཆུབ་ཀྱི་སེམས་ཀྱིས་ཀུན་ནས་བསླངས་ཏེ།
ཨེ་ནི་ཕྱིན་དྲུག་ལ་ཡ་བསླབ་ཡག་དེ་ག་རང་བོ་གཅིག་གི་སྐུ་ལས་སྐྱོན་ནས་མཐའ་མ་ལོ་
བཞི་བཅུ་ཞེ་གྲངས་གཅིག་མ་གཏོགས་ཨེ་ནི་དེའི་འབྲས་བུ།
02:40མེད་པ་ཞིག་ཡིན་ན་དེ་ནི་ཐབས་སྐྱོ་པོ་རེད་པ། རྒྱུ་འབྲས་འཆོལ་ཡོང་གི་འདུག་ག
དཔེར་ན། ང་རང་ཚོའི་འཇིག་རྟེན་གྱི་བྱ་བ་ཞིག་ཡིན་པ་ཡིན་ནས། དཀའ་ལས་ཞེ་བོ་བརྒྱབས་
ནས་བསྒྲུབས་བཞག་པའི་འབྲས་བུ་དེ།
02:50དེ་ལ་དཔག་པ་གཅིག་གིས་དཀའ་ལས་བརྒྱབས་ནས་རྒྱག་རིན་ཆོག་པའི་འབྲས་བུ་ཞིག་
དགོས་ཀྱི་རེད་མ་གཏོགས་དེ་མེད་ན་ཨེ་ནི་ག་རེ་ཟེར་བ་རེད་དཀའ་ལས་ཆེ་ལ་དོན་གོ་
ཆུང་བ་ཆགས་ཡོང་ཆགས་ཡོང་གི་རེད་པ།
02:58སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས་དེ་ཡང་མ་བདེ་བ་གཅིག་ཆགས།
གཉིས་ནས་ཨེ་ནི་ཨི་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི། འོ་འགྲིག་ཤག
03:09ཨི་གཉིས་ནས་ད་ཐེག་པ་ཆེ་ཆུང་སྔགས་དང་བཅས་པ་དེ་
གའི་དེ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ་ཨི་སྐུ་ཚེ་གཅིག་ལ་ཡ་ད་ག་རེ་ཟེར་བ་རེད།
03:19སྐུ་ཚེ་གཅིག་གི་རིང་ད་ག་རང་ལ་སྐུ་ཚེ་གཅིག་ད་ལོ་བརྒྱད་བཅུ།
བརྒྱད་བཅུ་ཙམ་བཞུགས་བཞག་པའི་དུས་ཡུན་དེ་ག་རང་གི་ནང་ལོག་ལ་ཡ་
ལམ་ཡོངས་སུ་རྫོགས་པ་དེ་གའི་དེ་ཨེ་ནི།
03:28ཐུགས་ལ་ཡ་ཤར་ནས་གཅིག་གསུངས་པ་རེད་ཟེར་ལབ་དགོས་བྱུང་ནས་དཔེ་ཁག་པོ་རེད།
ལྷག་པར་དུ་ཡང་ཨེ་ནི་ཕུང་པོ་ལྷག་མ་སངས་ཕུང་པོ་ལྷག་མ་མེད་པར་མྱ་
ངན་ལས་འདས་ནས་ཕེ་གིའི་ད་དེ་ཡི་རིག་པའི་རྒྱུན་ཆད་པ་ཡིན་ན།
03:38ཨེ་ནི་དུས་ཕྱིས་སུ་ཕིའི་དུས་ད་ལྟ་ཡིན་ནས།
ད་བཅོམ་ལྡན་འདས་ཀྱི་གཅིག་བྱིན་རླབས་ཡོང་ལ།
བཅོམ་ལྡན་འདས་ཀྱི་ཞལ་མཇལ་ཡག་དང་དེ་ཚོའི་གྲས་དེ་ཡོང་ཐུབ་ཡག་མེད་མཁན་གཅིག03:46ཨེ་ནི་རྒྱུད་སྡེའི་དཀྱིལ་འཁོར་དེ་ཚོའི་གྲས་དེ་ཡོང་ཐུབ་ཡག་ཡོང་ཤེས་ཀྱི་མ་རེད་པ།
དེ་འདྲས་ཡིན་དུས་ཙ་ནས་བཅོམ་ལྡན་འདས་འདི། ཨེ་ནི
སངས་རྒྱས་ཟེར།03:54ད་རྒྱ་གར་ལ་སངས་རྒྱས་པའི་མཛད་པ་མཛད་ཡག་དེ།
གསར་དུ་སངས་རྒྱས་པའི་མཛད་པ་མཛད་པ་ཙམ་རེད་མ་གཏོགས།
ངོ་ཐོག་སངས་རྒྱས་ཡག་སྔ་མ་ནས་སངས་རྒྱས་ཚར་པ་རེད་ཟེར།04:02ད་ཡང་སངས་རྒྱས་རྒྱས་པ་ཞིག་རེད་ཟེར་གིན་ཡོད་མ་རེད་གདའ།
སློབ་པ་ལམ་གྱི་གནས་སྐབས་མེད་ཟེར་གིན་ཡོད་མ་རེད་གདའ།
སློབ་པ་ལམ་གྱི་གནས་སྐབས་སྔོན་དུ་འགྲོ་བའི་ཐོག་ནས་མངོན་པར་རྫོགས་པ་སངས་རྒྱས་ནས།
སངས་རྒྱས་པའི།
04:11འོ་ན་ཨེ་ནི་རྒྱ་གར་ལ་ཕེབས་བསྡད་ཡག་དེ་ག་འདྲས་རེད་ཟེར་ལབ་ན།
དེ་མཆོག་གི་སྤྲུལ་སྐུ་ཟེར་ཡག་དེ་རེད་ཟེར།
མཆོག་གི་སྤྲུལ་སྐུ་དེ་ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་ལས་སྤྲུལ་ཡོང་གི་ཡོད་རེད་ཟེར།
04:19ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་དེ་ག་འདྲས་རེད་ཟེར་ལབ་ན།
ཆོས་སྐུའི་དབྱིངས་ལས་ཤར་བསྡད་པ་རེད་སེ།
ད་སྐུ་བཞི་ཟེར་གྱིས་ནས་ཡེ་ཤེས་ཆོས་ཀྱི་སྐུ་ཡོང་ཐུབ་ཡག་དེ་ཡང༌།04:27རྩ་བ་རང་བཞིན་རྣམ་དག་གི་ག་རེ་ཟེར་བ་རེད་ཕ་གིའི་སྟོང་པ་ཉིད་དེ་དང༌།
ཨེ་ནི་སེམས་བདེན་སྟོང་དེ་དང་སེམས་བདེན་སྟོང་དེ་ཡོད་པ་ཡིན་དུས་ཙ་ནས།
04:37དེ་མངོན་སུམ་དུ་རྟོགས་དེ་མངོན་དུ་གྱུར་ནས།
ཨེ་ནི་དེའི་སྟེང་གི་ག་རེ་ཟེར་དགོས་རེད་ད་དེའི་སྟེང་གི་ཨེ་ནི་ཕིའི་དྲི་མ་ཐམས་ཅད་ལོག་ཆོས་ཀྱི་དབྱིངས་སུ་དག་སོང་བའི་གནས་སྐབས་ཀྱི།
04:47དག་པ་གཉིས་ལྡན་གྱི་དབྱིངས་ངོ་བོ་ཉིད་སྐུ་དེ་བཞག དེ་ལས་ཡེ་ཤེས་ཆོས་སྐུ།
དེ་ལས་ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་ཤར་བསྡད་མཁན། དེ་ལས་སྤྲུལ་པའི་སྐུ་ཤར་བསྡད་པ།
04:56སྐུ་བཞི་ཟེར་ཡག་གི་རྣམ་གཞག་དེ་གསུང་བསྡད་ཡག་དེ་ཨེ་ནི་གཅིག་འདུག་ག
ཨེ་ནི་སངས་རྒྱས་སྟངས་དེ་ལྷག་པར་སྔགས་དང་འབྲེལ་ནས་བསམ་བློ་བཏང་བ་ཡིན་ན།
ད་ལྟའི་ང་རང་ཚོའི་གསལ་རིག་གི་ཤེས་པ་འདིའི་སྟེང་ནས།
05:05འདུག་སེ་བྱས་ནས་སྐུ་བཞི་སྒྲུབ་སྟང་གཅིག་མར་ཅིག་བཤད་ཡོང་དུས།
ཨོ་ད་དེ་ད་ལོས་བདེན་བསམ་ནས་སེམས་ནང་ལོག་ལ་ཡ་རྟོགས་པ་ད་སྐྱེ་ཡི་ཡོད་མ་རེད་དེ།
05:13དེ་ནས་མར་བསམ་བློ་ཞིག་བཏང་པ་ཡིན་ན། དེ་ལ་གནོད་པ་ཧ་ལམ་མཐོང་ཐུབ་ཡག་མེད་པ།
ད་དེ་ད་ཏན་ཏན་ཡིན་ས་རེད་ཏ།
དེ་ཡ་མཚན་པོ་འདུག་ག་བསམ་ནས་བློ་ལ་ཤར་ཡག་ཅིག་ཡོང་བསྡད་ཀིན་འདུག་ག
05:23སེ་ཨོ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས། ད་དེ་འདྲ་ལྟ་བུའི་སྐུ་བཞིའི་
བདག་ཉིད་ཀྱི་སངས་རྒྱས་ཞེས་གསུང་གི་ཡོད་རེད། ད་དེ་འདྲས་ཡིན་པ་ཡིན་ཙང་།
ཨེ་ནི་ད་ལྟ་འདིར་དེ་ནས་བྱ་རྒོད་ཕུང་པོའི་རིར་བཀའ་བར་པ་མཚན་ཉིད་
མེད་པའི་ཆོས་འཁོར་བསྐོར།
05:33ཞེས་པ་ལ་སོགས་པ་ད་ཐེག་པ་ཆེན་པོའི་མར་གསུང་སྟངས་ཁོ།
ད་དངོས་ཡོད་གནས་ཚུལ་ལ་ཡ་ཁོ་དེ་བདེན་པ་ཡིན་བསྡད་པ་གཅིག
05:41ད་ད་ལྟ་བཤད་མ་ཐག་པའི་རྒྱུ་མཚན་དེ་གའི་དེ་ལ་བརྟེན་ནས་ད་ཤེས་ཐུབ་ཡག་ཅིག་རེད་ཤག
དེ་འདྲས་གཅིག་རེད། ད་དེ་ནས་གྲུབ་མཐའ་བཞི་པ་དང་།
05:51ཐེག་པ། ཨེ་ནི་བསྡེ་པ་གྲུབ་མཐའ་ལྔ་པ་དང་། ཐེག་པ་ཨེ་ནི་བཞི་པ་ཡོད་མ་རེ
ད་བྱས་ནས་གསུང་བཞག་བ་དེ་གནད་འགག་སེ་གལ་མིན་འདུག
05:57ཨིའི་ད་དེའི་གཞུག་གུ་དེར་འདི་གཅིག་འདུག་ག རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ།
རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་བས་གཞལ་ན་རྟག་
ཆད་ཀྱི་མཐའ་གཉིས་ཀར་ལྟུང་ཞིང་། ལྟུང་ཡང༌སེ། རང་རང་གི་ལུགས་ལ་དབུ་མ་པར་འདོད་དེ།
06:16རྟག་ཆད་ཀྱི་མཐའ་གཉིས་དང་བྲལ་བའི་དབུས་ཁས་ལེན་པར་རློམ་པའི་ཕྱིར་རོ་སེ།།
ད་ཐུབ་པའི་དགོངས་པ་ཨིའི་མཐར་ཐུག་པ་དེ།
06:26རིགས་པས་གནོད་པ་མེད་པ་ཞིག་དགོས་ཀི་རེད་པ། ད་རིགས་པས་གནོད་པ་མེད་པ་
ད་ཐུབ་པས་ཨེ་ནི་ལྟ་བ་མི་འདྲ་བ་གསུངས་བཞག་ཡག་ཅིག་དེ་འདྲའི་ཕ་གིའི།
06:36ཆོས་ཚུལ་མི་འདྲ་བ་གསུངས་བཞག་པ་དེ་གའི་དེ། ཨི་གདུལ་བྱའི་ཁམས་དང་མོས་པ་སྣ་
ཚོགས་པ་ཡོད་པ་ཡིན་དུས་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀྱི་རྗེས་སུ་
འབྲང་མཁན་གྱི་གདུལ་བྱའི་ནང་ལས་ཡང་ཁམས་དང་མོས་པ་མི་འདྲ་བ་ཡོད་པ་ཡིན་དུས་ཙ་ནས།
06:45དེའི་ཁམས་དང་མོས་པ་དང་བསྟུན་ནས་ད་བཅོམ་ལྡན་འདས་ཀྱིས་ཨིའི་གསུངས་པ་རེད།
དེ་གསུང་དགོས་ཀྱི་རེད། ག་རེ་རེད་ཟེར་ལབ་ན་གང་གི་ཐུགས་བརྩེས་ཉེར་བཟུང་ནས། །
ཟེར་ཡག་འདི་ཡིན་པ་རེད།
06:53ཨིའི་ད་མཁྱེན་པ་བླ་ན་མེད་པ་ཡོད་པ་ཡིན་དུས་ཙ་ནས། ཨིའི་ག་རེ་ཟེར།
སྔོན་མཐའ་མངོན་ནམ་ཞེས་ཞུས་ཚེ། །
ཐུབ་པ་ཆེན་པོས་མིན་ཞེས་གསུངས། །
07:02ག་རེ་ཟེ། བྱས་ནས་ད་འདི་ད་ལྟ། ད་ད་ལྟ་ཁམས་དང་མོས་པ་ཇི་བཞིན་པ་ཅིག
07:11ཇི་བཞིན་པ་མཁྱེན་ནས། དེའི་དོན་དུ་འགྱུར་ན་ལུང་བསྟན།
དེའི་དོན་དུ་མ་འགྱུར་ན་ལུང་མ་བསྟན་པ་གཅིག་གི་ག་རེ་ཟེར་
ལུང་མ་བསྟན་པ་ཡིན་དུས་ཙ་ནས།
07:21ལུང་དུ་མ་བསྟན་པའི་མཛད་པ་དེས་ཀུན་མཁྱེན་ཡིན་པ་ད་ལྟ་ཤེས་ད་ལྟ་བསྒྲུབ་དགོས་ཀྱི་འདུག
ཀུན་མཁྱེན་ཡིན་པ་ཤེས་ཐུབ་ཡག་རེད་ཤག་ཟེར་བྱས་འདི་གསུང་གི་འདུག་ག
07:30སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས། ད་གང་ལྟར་གདུལ་བྱའི་ཁམས་དང་མོས་
པ་དང་འཚམས་པ་གཅིག་གི་ཨེ་ནི་ཆོས་བསྟན་ནས་ཡོད་པ་ཡིན་དུས།
07:37བཅོམ་ལྡན་འདས་ཀྱིས་གསུང་ཚད་དེ་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀྱི་
དགོངས་པ་མཐར་ཐུག་ཡིན་པ་དེ་བཤད་ཐུབ་ཡག་མི་འདུག་ག
མི་འདྲ་བ་མང་པོ་ཞིག་ཡོང་གི་ཡོད་རེད་པ།
ད་བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་དེ།
07:47རིགས་པས་གནོད་པ་མེད་པ་གཅིག་དགོས་ཀྱི་ཡོད་རེད།
དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཨིའི་མགོན་པོ་ཀླུ་སྒྲུབ་ཀྱི་བཞེད་པ་ཐུན་མོང་མ་ཡིན་པ།
ཨེ་ནི་སངས་རྒྱས་བསྐྱངས་དང༌། ཟླ་བ་གྲགས་པ་གཉིས་ཀྱིས་ད་མར་བཀྲལ་བཞག་པའི།
07:56དབུ་མའི་ལྟ་བ་ཐ་སྙད་དུ་ཡང་རང་མཚན་བཀག་ནས། ཨེ་ནི་མིང་རྐྱང་བཏགས་ཡོད་
ཙམ་གི་དེ་བཞིན་ཉིད་གསུང་བསྡད་ཡག་དེ། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་རྟེན་
འབྱུང་ཕྲ་མོ།
08:06ཨིའི་དེ་རྒྱུ་མཚན་དུ་བྱས་ཏེ་རང་བཞིན་གྱིས་སྟོང་པ་ཡིན་པ་
བཤད་བསྡད་ཡག་གི་རྟེན་འབྱུང་གི་དེ་ཁོ་ཉིད་ཟེར་བསྡད་མཁན་དེ་ད་
བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་ཡིན་པ་གཅིག་ཨེ་ནི
་ཁོ་ཤེས་ཐུབ་ཡག་ཅིག་ཡིན་པ་རེད།
08:16བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་ [...]

2023-04-05 18:11 UTC, Tenzindharten requested changes
00:00ད་དེ་འདྲ་ཡིན་དུས་ཙ་ནས། ཨེ་ནི་ཨིའི་ཀླུ་སྒྲུབ་ཡབ་སྲས་ལ་སོགས་པ།
འོ་ད་དེ་གའི་དེ་གི ཨིའི་དཔེར་ན་ད་ཀླུ་སྒྲུབ་ཀྱིས
00:09གང་གི་ཐུགས་བརྩེས་ཉེར་བཟུང་ནས། །
ལྟ་བ་ཐམས་ཅད་སྤང་པའི་ཕྱིར། །
དམ་པའི་ཆོས་ནི་སྟོན་མཛད་པ། །
གཽ་ཏམ་དེ་ལ་ཕྱག་འཚལ་ལོ། །
ཞེས་གསུངས་ཡག་དེ་དང༌། ཨེ་ནི་རྩ་བ་ཤེས་རབ་ཀྱི་དབུ་དེ་ལ་ཡ།
00:18གང་གིས་རྟེན་ཅིང་འབྲེལ་བར་འབྱུང༌། །འགག་པ་མེད་པ་སྐྱེ་མེད་པ། །
ཆད་པ་མེད་པ་རྟག་མེད་པ། །འོང་བ་མེད་པ་འགྲོ་མེད་པ། །
ཐ་དད་དོན་མིན་དོན་གཅིག་མིན། །སྤྲོས་པ་ཉེར་ཞི་ཞི་བསྟན་པ། །
རྫོགས་པའི་སངས་རྒྱས་སྨྲ་རྣམས་ཀྱི། །དམ་པ་དེ་ལ་ཕྱག་འཚལ་ལོ། །ཟེར་བྱས་ནས།
00:27ཨི་དེ་འདྲའི་བསྟོད་ཕྱག་མཛད་སའི་ཡུལ་དེ་ད་བསམ་གྱིས་མི་
ཁྱབ་པ་གཅིག་ཡིན་པ་གཅིག་ཨེ་ནི་ཚོད་དཔག་བྱེད་ཐུབ་ཡག་ཅིག་འདུག་ག
00:33ཨོ་ད་དེ་ད་ཁྱད་མཚར་གཅིག་ཡོད་ས་རེད། མི་འདྲ་བ་གཅིག་ཡོད་ས་རེད་
བསམ་པ་དྲན་ཡག་ཅིག་འདུག་ག
00:37དེ་འདྲས་ཡིན་དུས་ཙ་ནས་ཨི་ཨེ་ནི། ཨིའི་་ཨིའི་དེ་འདྲས་ཡིན་དུས་ལོ
་ཉིས་སྟོང་ལྔ་བརྒྱའི་གོང་དུ་བྱུང་བཞག་པའི་སངས་རྒྱས་བཅོམ་ལྡན་འདས་དེ།
00:47མི་ཕལ་པ་གཅིག་ད་མིན་པ་གཅིག་མི་རང་དགའ་བ་མིན་བསྡད་པ་གཅིག་ད་ཚོད་དཔག་བྱེད་ཐུབ་ཡག་རེད།
དེ་ཙམ་དུ་མ་ཟད་པའི་ཨེ་ནི།
00:57ཉན་ཐོས་སྡེ་པའི་གཞུང་ནས་བཅོམ་ལྡན་འདས། ཨེ་ནི་རྒྱ་གར་ལ་འཁྲུངས་དུས་ཙ་ནས།
ཨེ་ནི་ད་ཚེ་འདི་ལ་གསར་དུ་སངས་རྒྱས་མཁན་གྱི་བྱང་ཆུབ་སེམས་དཔའ་སེམས་ཅན་གཅིག་བྱས།
ད་དེས་ཨེ་ནི་རྡོ་རྗེ་གདན་གྱི་གནས་ལ་ཡ་ཨེ་ནི།
01:16སྔོན་ལ་ཐོག་མར་ད་ག་རེ་ཟེར་བ་རེད་ཕ་གིའི་ལོ་དྲུག་དཀའ་སྤྱད་དེ་ཚོ་མཛད།
མཐར་ཨེ་ནི་རྡོ་རྗེ་གདན་གྱི་གནས་ལ་མངོན་པར་རྫོགས་པ་སངས་རྒྱ
ས་པའི་མཛད་པ་མཛད་ཡག་དེ།
01:25འོད་རེ་ད་དེ་ནས་སངས་རྒྱས་པའི་མཛད་པ་མཛད་ནས་དེ་ནས་ད་གཅིག་
ག་ཚད་རེད་ལོ་བཞི་བཅུ་ཞེ་གྲངས་གཅིག ཨེ་ནི་སེ་ད་སེ་སངས་རྒྱས་གནང་བྱས་ད།
01:35ད་སེམས་ཅན་ལས་ཡོངས་སུ་འདས་ནས་སངས་རྒྱས་ཆགས་ནས་ལོ་བཞི་བཅུ་ཞེ་གྲངས་ཤིག་བཞུགས།
དེ་ནས་ཨེ་ནི་སངས་རྒྱས་ཚར་བའི་དེ་ནས་
01:44ག་རེ་ཟ་རྩྭ་མཆོག་གྲོང་ལ་ཡ་ཨེ་ནི་མྱ་ངན་ལས་འདས་པའི་རྗེས་ལ།
ཨེ་ནི་བདུད་བཞི་ཁར་བཅོམ་ནི། འཆི་བདག་གི་བདུད་བཅོམ། ཕུང་པོའི་བདུད་བཅོམ་ནས།
01:52ད་དེ་ནས་ཕུང་པོ་ལྷག་མ་མེད་པ་ཨེ་ནི་མྱང་ངན་ལས་འདས་པ་རེད་ཟེར།
དེ་ནས་ཨེ་ནི་མར་མེ་ཤི་བ་ནང་བཞིན་རིག་པ་རྒྱུན་ཆད་པ་རེད་ཟེར་
བྱས་ནས་ད་བཤད་བསྡད་ཡག་ཅིག་ཡོད་རེད་པ།
02:01ད་འདི་ཨེ་ནི་རྒྱུ་མཚན་མི་ལྡན་པ་ཞིག་ཆགས་ཀི་ཡོད་རེད།
འདིའི་བཤད་པ་བཤད་པ་ག་རེ་ཟེར་བཤད་སྟངས་འདི།
02:10ད་གཏི་ཐུག་ཆགས་པ་རེད། བསམ་བློ་ཞིག་བཏང་པ་ཡིན་ན།
བསྐལ་ཆེན་གྲངས་མེད་གསུམ་གྱི་བར་ལ་ཡ་ཚོགས་བསགས་ནས། རྒྱུ་རླབས་ཆེན་པོ་དེ་འདྲའི་
གཅིག་གིས།
02:20འབྲས་བུ་དེ་ལོ་བཞི་བཅུ་ཞེ་གྲངས་གཅིག་གི་ཨེ་ནི་མངོན་
པར་རྫོགས་པའི་སངས་རྒྱས་ནས་ལོ་བཞི་བཅུ་ཞེ་གྲངས་གཅིག་གི་
ད་སེམས་ཅན་གྱི་དོན་མཛད་ཡག་མ་གཏོགས་བྱུང་མེད་ན། རྒྱུ་འབྲས་གོ་འཛོལ་རེད་འདུག་ག
02:30རྒྱུ་ད་ག་འདྲ་བོ་གཅིག་ལ་བསླབས་ནས། བྱང་ཆུབ་ཀྱི་སེམས་ཀྱིས་ཀུན་ནས་བསླངས་ཏེ།
ཨེ་ནི་ཕྱིན་དྲུག་ལ་ཡ་བསླབ་ཡག་དེ་ག་རང་བོ་གཅིག་གི་སྐུ་ལས་སྐྱོན་ནས་མཐའ་མ་ལོ་
བཞི་བཅུ་ཞེ་གྲངས་གཅིག་མ་གཏོགས་ཨེ་ནི་དེའི་འབྲས་བུ།
02:40མེད་པ་ཞིག་ཡིན་ན་དེ་ནི་ཐབས་སྐྱོ་པོ་རེད་པ། རྒྱུ་འབྲས་འཆོལ་ཡོང་གི་འདུག་ག
དཔེར་ན། ང་རང་ཚོའི་འཇིག་རྟེན་གྱི་བྱ་བ་ཞིག་ཡིན་པ་ཡིན་ནས། དཀའ་ལས་ཞེ་བོ་བརྒྱབས་
ནས་བསྒྲུབས་བཞག་པའི་འབྲས་བུ་དེ།
02:50དེ་ལ་དཔག་པ་གཅིག་གིས་དཀའ་ལས་བརྒྱབས་ནས་རྒྱག་རིན་ཆོག་པའི་འབྲས་བུ་ཞིག་
དགོས་ཀྱི་རེད་མ་གཏོགས་དེ་མེད་ན་ཨེ་ནི་ག་རེ་ཟེར་བ་རེད་དཀའ་ལས་ཆེ་ལ་དོན་གོ་
ཆུང་བ་ཆགས་ཡོང་ཆགས་ཡོང་གི་རེད་པ།
02:58སེ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས་དེ་ཡང་མ་བདེ་བ་གཅིག་ཆགས།
གཉིས་ནས་ཨེ་ནི་ཨི་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི། འོ་འགྲིག་ཤག
03:09ཨི་གཉིས་ནས་ད་ཐེག་པ་ཆེ་ཆུང་སྔགས་དང་བཅས་པ་དེ་
གའི་དེ་སྟོན་མཁན་གྱི་སྟོན་པ་དེ་ཨི་སྐུ་ཚེ་གཅིག་ལ་ཡ་ད་ག་རེ་ཟེར་བ་རེད།
03:19སྐུ་ཚེ་གཅིག་གི་རིང་ད་ག་རང་ལ་སྐུ་ཚེ་གཅིག་ད་ལོ་བརྒྱད་བཅུ།
བརྒྱད་བཅུ་ཙམ་བཞུགས་བཞག་པའི་དུས་ཡུན་དེ་ག་རང་གི་ནང་ལོག་ལ་ཡ་
ལམ་ཡོངས་སུ་རྫོགས་པ་དེ་གའི་དེ་ཨེ་ནི།
03:28ཐུགས་ལ་ཡ་ཤར་ནས་གཅིག་གསུངས་པ་རེད་ཟེར་ལབ་དགོས་བྱུང་ནས་དཔེ་ཁག་པོ་རེད།
ལྷག་པར་དུ་ཡང་ཨེ་ནི་ཕུང་པོ་ལྷག་མ་སངས་ཕུང་པོ་ལྷག་མ་མེད་པར་མྱ་
ངན་ལས་འདས་ནས་ཕེ་གིའི་ད་དེ་ཡི་རིག་པའི་རྒྱུན་ཆད་པ་ཡིན་ན།
03:38ཨེ་ནི་དུས་ཕྱིས་སུ་ཕིའི་དུས་ད་ལྟ་ཡིན་ནས།
ད་བཅོམ་ལྡན་འདས་ཀྱི་གཅིག་བྱིན་རླབས་ཡོང་ལ།
བཅོམ་ལྡན་འདས་ཀྱི་ཞལ་མཇལ་ཡག་དང་དེ་ཚོའི་གྲས་དེ་ཡོང་ཐུབ་ཡག་མེད་མཁན་གཅིག
03:46ཨེ་ནི་རྒྱུད་སྡེའི་དཀྱིལ་འཁོར་དེ་ཚོའི་གྲས་དེ་ཡོང་ཐུབ་ཡག་ཡོང་ཤེས་ཀྱི་མ་རེད་པ།
དེ་འདྲས་ཡིན་དུས་ཙ་ནས་བཅོམ་ལྡན་འདས་འདི། ཨེ་ནི
སངས་རྒྱས་ཟེར།
03:54ད་རྒྱ་གར་ལ་སངས་རྒྱས་པའི་མཛད་པ་མཛད་ཡག་དེ།
གསར་དུ་སངས་རྒྱས་པའི་མཛད་པ་མཛད་པ་ཙམ་རེད་མ་གཏོགས།
ངོ་ཐོག་སངས་རྒྱས་ཡག་སྔ་མ་ནས་སངས་རྒྱས་ཚར་པ་རེད་ཟེར།
04:02ད་ཡང་སངས་རྒྱས་རྒྱས་པ་ཞིག་རེད་ཟེར་གིན་ཡོད་མ་རེད་གདའ།
སློབ་པ་ལམ་གྱི་གནས་སྐབས་མེད་ཟེར་གིན་ཡོད་མ་རེད་གདའ།
སློབ་པ་ལམ་གྱི་གནས་སྐབས་སྔོན་དུ་འགྲོ་བའི་ཐོག་ནས་མངོན་པར་རྫོགས་པ་སངས་རྒྱས་ནས།
སངས་རྒྱས་པའི།
04:11འོ་ན་ཨེ་ནི་རྒྱ་གར་ལ་ཕེབས་བསྡད་ཡག་དེ་ག་འདྲས་རེད་ཟེར་ལབ་ན།
དེ་མཆོག་གི་སྤྲུལ་སྐུ་ཟེར་ཡག་དེ་རེད་ཟེར།
མཆོག་གི་སྤྲུལ་སྐུ་དེ་ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་ལས་སྤྲུལ་ཡོང་གི་ཡོད་རེད་ཟེར།
04:19ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་དེ་ག་འདྲས་རེད་ཟེར་ལབ་ན།
ཆོས་སྐུའི་དབྱིངས་ལས་ཤར་བསྡད་པ་རེད་སེ།
ད་སྐུ་བཞི་ཟེར་གྱིས་ནས་ཡེ་ཤེས་ཆོས་ཀྱི་སྐུ་ཡོང་ཐུབ་ཡག་དེ་ཡང༌།
04:27རྩ་བ་རང་བཞིན་རྣམ་དག་གི་ག་རེ་ཟེར་བ་རེད་ཕ་གིའི་ཨིའི་སྟོང་པ་ཉིད་དེ་དང༌།
ཨེ་ནི་སེམས་བདེན་སྟོང་དེ་དང་སེམས་བདེན་སྟོང་དེ་ཡོད་པ་ཡིན་དུས་ཙ་ནས།
04:37དེ་མངོན་སུམ་དུ་རྟོགས། དེ་མངོན་དུ་གྱུར་ནས།
ཨེ་ནི་དེའི་སྟེང་གི་ག་རེ་ཟེར་དགོས་རེད་ད་དེའི་སྟེང་གི་ཨེ་ནི་ཕིའི་དྲི་མ་ཐམས་ཅད་ལོག་ཆོས་ཀྱི་དབྱིངས་སུ་དག་སོང་བའི་གནས་སྐབས་ཀྱི།
04:47དག་པ་གཉིས་ལྡན་གྱི་དབྱིངས་ངོ་བོ་ཉིད་སྐུ་དེ་བཞག དེ་ལས་ཡེ་ཤེས་ཆོས་སྐུ།
དེ་ལས་ལོངས་སྤྱོད་རྫོགས་པའི་སྐུ་ཤར་བསྡད་མཁན། དེ་ལས་སྤྲུལ་པའི་སྐུ་ཤར་བསྡད་པ།
04:56སྐུ་བཞི་ཟེར་ཡག་གི་རྣམ་གཞག་དེ་གསུང་བསྡད་ཡག་དེ་ཨེ་ནི་གཅིག་འདུག་ག
ཨེ་ནི་སངས་རྒྱས་སྟངས་དེ་ལྷག་པར་སྔགས་དང་འབྲེལ་ནས་བསམ་བློ་བཏང་བ་ཡིན་ན།
ད་ལྟའི་ང་རང་ཚོའི་གསལ་རིག་གི་ཤེས་པ་འདིའི་སྟེང་ནས།
05:05འདུག་སེ་བྱས་ནས་སྐུ་བཞི་སྒྲུབ་སྟངས་གཅིག་མར་གཅིག་བཤད་ཡོང་དུས།
ཨོ་ད་དེ་ད་ལོས་བདེན་བསམ་ནས་སེམས་ནང་ལོག་ལ་ཡ་རྟོགས་པ་ད་སྐྱེ་ཡི་ཡོད་མ་རེད་དེ།
05:13དེ་ནས་མར་བསམ་བློ་ཞིག་བཏང་པ་ཡིན་ན། དེ་ལ་གནོད་པ་ཧ་ལམ་མཐོང་ཐུབ་ཡག་མེད་པ།
ད་དེ་ད་ཏན་ཏན་ཡིན་ས་རེད་ཏ།
དེ་ཡ་མཚན་པོ་འདུག་ག་བསམ་ནས་བློ་ལ་ཤར་ཡག་ཅིག་ཡོང་བསྡད་ཀིན་འདུག་ག
05:23སེ་ཨོ་དེ་འདྲས་ཡིན་དུས་ཙ་ནས། ད་དེ་འདྲ་ལྟ་བུའི་སྐུ་བཞིའི་
བདག་ཉིད་ཀྱི་སངས་རྒྱས་ཞེས་གསུང་གི་ཡོད་རེད། ད་དེ་འདྲས་ཡིན་པ་ཡིན་ཙང་།
ཨེ་ནི་ད་ལྟ་འདིར་དེ་ནས་བྱ་རྒོད་ཕུང་པོའི་རིར་བཀའ་བར་པ་མཚན་ཉིད་
མེད་པའི་ཆོས་འཁོར་བསྐོར།
05:33ཞེས་པ་ལ་སོགས་པ་ད་ཐེག་པ་ཆེན་པོའི་མར་གསུང་སྟངས་ཁོ།
ད་དངོས་ཡོད་གནས་ཚུལ་ལ་ཡ་ཁོ་དེ་བདེན་པ་ཡིན་བསྡད་པ་གཅིག
05:41ད་ད་ལྟ་བཤད་མ་ཐག་པའི་རྒྱུ་མཚན་དེ་གའི་དེ་ལ་བརྟེན་ནས་ད་ཤེས་ཐུབ་ཡག་ཅིག་རེད་ཤག
དེ་འདྲས་གཅིག་རེད། ད་དེ་ནས་གྲུབ་མཐའ་བཞི་པ་དང་།
05:51ཐེག་པ། ཨེ་ནི་[བ]སྡེ་པ་གྲུབ་མཐའ་ལྔ་པ་དང་། ཐེག་པ་ཨེ་ནི་བཞི་པ་ཡོད་མ་རེ
ད་བྱས་ནས་གསུང་བཞག་བ་དེ་གནད་འགག་སེ་གལ་མིན་འདུག
05:57ཨིའི་ད་དེའི་གཞུག་གུ་དེར་འདི་གཅིག་འདུག་ག རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ།
རང་རྒྱུད་པ་མན་ཆད་ཀྱི་རང་སྡེ་འདི་དག་ཐལ་འགྱུར་བས་གཞལ་ན་རྟག་
ཆད་ཀྱི་མཐའ་གཉིས་ཀར་ལྟུང་ཞིང་། ལྟུང་ཡང༌སེ། རང་རང་གི་ལུགས་ལ་དབུ་མ་པར་འདོད་དེ།
06:16རྟག་ཆད་ཀྱི་མཐའ་གཉིས་དང་བྲལ་བའི་དབུས་ཁས་ལེན་པར་རློམ་པའི་ཕྱིར་རོ་སེ།།
ད་ཐུབ་པའི་དགོངས་པ་ཨིའི་མཐར་ཐུག་པ་དེ།
06:26རིགས་པས་གནོད་པ་མེད་པ་ཞིག་དགོས་ཀི་རེད་པ། ད་རིགས་པས་གནོད་པ་མེད་པ་
ད་ཐུབ་པས་ཨེ་ནི་ལྟ་བ་མི་འདྲ་བ་གསུངས་བཞག་ཡག་ཅིག་དེ་འདྲའི་ཕ་གིའི།
06:36ཆོས་ཚུལ་མི་འདྲ་བ་གསུངས་བཞག་པ་དེ་གའི་དེ། ཨི་གདུལ་བྱའི་ཁམས་དང་མོས་པ་སྣ་
ཚོགས་པ་ཡོད་པ་ཡིན་དུས་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀྱི་རྗེས་སུ་
འབྲང་མཁན་གྱི་གདུལ་བྱའི་ནང་ལས་ཡང་ཁམས་དང་མོས་པ་མི་འདྲ་བ་ཡོད་པ་ཡིན་དུས་ཙ་ནས།
06:45དེའི་ཁམས་དང་མོས་པ་དང་བསྟུན་ནས་ད་བཅོམ་ལྡན་འདས་ཀྱིས་ཨིའི་གསུངས་པ་རེད།
དེ་གསུང་དགོས་ཀྱི་རེད། ག་རེ་རེད་ཟེར་ལབ་ན་གང་གི་ཐུགས་བརྩེས་ཉེར་བཟུང་ནས། །
ཟེར་ཡག་འདི་ཡིན་པ་རེད།
06:53ཨིའི་ད་མཁྱེན་པ་བླ་ན་མེད་པ་ཡོད་པ་ཡིན་དུས་ཙ་ནས། ཨིའི་ག་རེ་ཟེར།
སྔོན་མཐའ་མངོན་ནམ་ཞེས་ཞུས་ཚེ། །
ཐུབ་པ་ཆེན་པོས་མིན་ཞེས་གསུངས། །
07:02ག་རེ་ཟེ། བྱས་ནས་ད་འདི་ད་ལྟ། ད་ད་ལྟ་ཁམས་དང་མོས་པ་ཇི་བཞིན་པ་ཅིག
07:11ཇི་བཞིན་པ་མཁྱེན་ནས། དེའི་དོན་དུ་འགྱུར་ན་ལུང་བསྟན།
དེའི་དོན་དུ་མ་འགྱུར་ན་ལུང་མ་བསྟན་པ་གཅིག་གི་ག་རེ་ཟེར་
ལུང་མ་བསྟན་པ་ཡིན་དུས་ཙ་ནས།
07:21ལུང་དུ་མ་བསྟན་པའི་མཛད་པ་དེས་ཀུན་མཁྱེན་ཡིན་པ་ད་ལྟ་ཤེས་ད་ལྟ་བསྒྲུབ་དགོས་ཀྱི་འདུག
ཀུན་མཁྱེན་ཡིན་པ་ཤེས་ཐུབ་ཡག་རེད་ཤག་ཟེར་བྱས་འདི་གསུང་གི་འདུག་ག
07:30སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས། ད་གང་ལྟར་གདུལ་བྱའི་ཁམས་དང་མོས་
པ་དང་འཚམས་པ་གཅིག་གི་ཨེ་ནི་ཆོས་བསྟན་ནས་ཡོད་པ་ཡིན་དུས།
07:37བཅོམ་ལྡན་འདས་ཀྱིས་གསུང་ཚད་དེ་བཅོམ་ལྡན་འདས་རང་ཉིད་ཀྱི་
དགོངས་པ་མཐར་ཐུག་ཡིན་པ་དེ་བཤད་ཐུབ་ཡག་མི་འདུག་ག
མི་འདྲ་བ་མང་པོ་ཞིག་ཡོང་གི་ཡོད་རེད་པ།
ད་བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་དེ།
07:47རིགས་པས་གནོད་པ་མེད་པ་གཅིག་དགོས་ཀྱི་ཡོད་རེད།
དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཨིའི་མགོན་པོ་ཀླུ་སྒྲུབ་ཀྱི་བཞེད་པ་ཐུན་མོང་མ་ཡིན་པ།
ཨེ་ནི་སངས་རྒྱས་བསྐྱངས་དང༌། ཟླ་བ་གྲགས་པ་གཉིས་ཀྱིས་ད་མར་བཀྲལ་བཞག་པའི།
07:56དབུ་མའི་ལྟ་བ་ཐ་སྙད་དུ་ཡང་རང་མཚན་བཀག་ནས། ཨེ་ནི་མིང་རྐྱང་བཏགས་ཡོད་
ཙམ་གི་དེ་བཞིན་ཉིད་གསུང་བསྡད་ཡག་དེ། མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་རྟེན་
འབྱུང་ཕྲ་མོ།
08:06ཨིའི་དེ་རྒྱུ་མཚན་དུ་བྱས་ཏེ་རང་བཞིན་གྱིས་སྟོང་པ་ཡིན་པ་
བཤད་བསྡད་ཡག་གི་རྟེན་འབྱུང་གི་དེ་ཁོ་ཉིད་ཟེར་བསྡད་མཁན་དེ་ད་
བཅོམ་ལྡན་འདས་ཀྱི་དགོངས་པ་མཐར་ཐུག་ཡིན་པ་གཅིག་ཨེ་ནི
་ཁོ་ཤེས་ཐུབ་ཡག་ཅིག་ཡིན་པ་རེད།
08:16བཅོམ་ལྡན་འད [...]

2023-04-05 18:20 UTC, Tenzindharten requested changes
00:00མཛད་པ་བཅུ་གཉིས་ཀྱི་དང་པོ་དགུ་བྱང་སེམས་དང༌།
ཕྱི་མ་གསུམ་སངས་རྒྱས་ཀྱི་མཛད་པར་ཁས་ལེན་ནོ།
།ཆོས་འཁོར་ལ་ཨིའི་མཐོང་ལམ་གྱིས་ཁྱབ་པ་དང༌།
00:09ཆོས་འཁོར་ལ་མཐོང་ལམ་གྱིས་ཁྱབ་པ་དང༌།
ཨིའི་ལུང་གི་ཆོས་འཁོར་ལ་བདེན་བཞིའི་ཆོས་འཁོར་གྱིས་ཁྱབ་པར་འདོད་དོ།།
མངོན་པ་སྡེ་བདུན་པོ་སངས་རྒྱས་ཀྱིས།
00:18ད་སྔོན་ལ་ལུང་གི་ཆོས་འཁོར་དང་།
བདེན་བཞིའི་ཆོས་འཁོར་གྱིས་ཁྱབ་པར་འདོད་དོ་ཟེར་གྱིས།  དེ་ནས་ཡ།
ད་དེ་ཨིའི་མངོན་པ་སྡེ་བདུན་པོ་སངས་རྒྱས་ཀྱིས་གསུངས་པའི་བཀར་ཁས་ལེན།
00:27བཀའ་ལ་སྒྲ་ཇི་བཞིན་པས་ཁྱབ་བོ། །
བཀའ་ལ་ཡ་དྲང་ངེས་གཉིས་བཞག་ཡག་དེ་འདྲའི་མེད་པ་བྱས། བཀའ་ལ་སྒྲ་ཇི་བཞིན་པས་ཁྱབ།
ད་དེ་ནས་ཆོས་སྐོར་དེ་ཚར་བ་བྱས། ད་དེ་གནད་འགག་ཆེན་པོ་ཟེར་གལ་མི་འདུག
00:37
ད་དེ་ནས་མར་བྱང་སེམས་སྲིད་པ་ཐ་མ་བས་བྱང་ཆུབ་མངོན་དུ་བྱེད་པའི་གནས་ནི་འདོད་ཁམས་ཁོ་ནར་ངེས།
00:46འོག་མིན་སྟུག་པ་བཀོད་པའི་རྣམ་གཞག་དང༌། །ལོངས་སྐུའི་རྣམ་གཞག་ཁས་མི་ལེན།
།དེར་མ་ཟད་རྣམ་མཁྱེན་ཡང་མི་འདོད། །
00:54ད་ག་རེ་ཟེར་བ་རེད་ཕ་གིའི། ཨིའི་ཀུན་མཁྱེན་ཟེར་ཡག་འདྲ་བོ།
ཤེས་བྱའི་ཆོས་གང་དང་གང་ཡིན་ནས།
01:02ཆོས་རེ་རེ་ལ་ཡ་ཞེ་ས་མ་ཞུས་ན། ཐུགས་ཕར་གཏད་པ་ཡིན་ན་མཁྱེན་མཁན།
དེ་འདྲས་ཡིན་དུས་ཙ་ནས།
01:11ཐུགས་གཏད་ན་མ་མཁྱེན་ཡག་གི་ཆོས་གཅིག་མེད་པ་བྱས།
ཐམས་ཅད་མཁྱེན་ཨེ་ནི་ཀུན་མཁྱེན།
རྣམ་པ་ཐམས་ཅད་མཁྱེན་ཟེར་པ་ཡིན་ན་དུས་གཅིག་ལ་ཤེས་བྱ་མཐའ་དག་མཁྱེན་ཡག་དེ་མེད་པ་བྱས།
01:21ཨིའི་་་ཐེག་པ་གསུམ་གྱི་དགྲ་བཅོམ་ལ་ལྷག་བཅས་པས་ཁྱབ་སྟེ།
ཨིའི་་་ལྷག་མེད་མྱང་འདས་མངོན་དུ་བྱེད་པའི་ཚེ།
01:31མར་མེ་ཤི་བ་ལྟར་རིག་པ་རྒྱུན་ཆད་པར་འདོད།
དེ་འདྲས་ཡིན་དུས་མཐར་ཐུག་ཐེག་པ་གསུམ་བཤད།
01:37ད་དེའི་གཞུག་གུ་དེར་སངས་རྒྱས། ཆོས། དགེ་འདུན་ཟེར་ཡག་དེ།
སངས་རྒྱས་སུ་བྱེད་པའི་བྱེད་ཆོས་དང༌། དགེ་འདུན་དུ་བྱེད་པའི་བྱེད་ཆོས་ཀྱི་ཨེ་ནི།
01:48ག་རེ་ཟེར་བ་རེད་ཡེ་ཤེས་དེ་ལ་ཨེ་ནི་སངས་རྒྱས་དཀོན་མཆོག་དང༌། ཆོས་དཀོན་མཆོག
དགེ་འདུན་དཀོན་མཆོག་བཞག་གི་ཡོད་རེད་མ་གཏོགས།
དེའི་ད་གང་ཟག་ཟེར་དགོས་རེད་ཕུང་པོ་དེ་ལ་བརྩི་ཡི་ཡོད་མ་རེད་གསུང་གི་ཡོད་པ་འདྲ།
01:56ཨིའི་གགཟུགས་སྐུ་ནི་སྔར་བཞིན་་་སངས་རྒྱས་དཀོན་མཆོག་ནི་དེའི་ཐུགས་རྒྱུད་ཀྱི་ཟད་མི་སྐྱེའི་ཡེ་ཤེས་ལ་འདོད།
།
02:05ད་ཉོན་མོངས་ཟད་པ་དང༌།
སླར་མི་སྐྱེ་བ་ཞེས་པའི་ཟད་མི་སྐྱེ་ཞེས་པའི་ཡེ་ཤེས་དེ་ཉིད་སངས་རྒྱས་ཡིན།
དེ་བཞིན་དུ་སློབ་པ་འཕགས་པ་རྣམས་ཟག་བཅས་ཡིན་པས།
02:14དགེ་འདུན་དཀོན་མཆོག་མིན་ཡང་། དགེ་འདུན་ཡིན་ལ།
དགེ་འདུན་དཀོན་མཆོག་ནི་དེའི་ཐུགས་རྒྱུད་ཀྱི་ལམ་བདེན་ལ་འདོད་དོ། །

02:21ཆོས་དཀོན་མཆོག་སངས་རྒྱས་དང་ཉན་རང་གཉིས་ཀའི་རྒྱུད་ཀྱི་མྱང་འདས་དང་འགོག
ཨིའི་སངས་རྒྱས་དང་ཉན་རང་གཉིས་ཀའི་རྒྱུད་ཀྱི་འགོག

02:31རྒྱུད་ཀྱི་མྱང་འདས་དང་འགོག་བདེན་དེ་དེ་ཡིན་པའི་ཕྱིར།
འོ་དེ་འདྲའི་གཅིག་གསུངས་ཤག འོ་ད་དེ་གྲུབ་པ་བྱས། ཨིའི། ད་དེ་ནས་མདོ་སྡེ་པས།
02:41མདོ་སྡེ་པའི་ལུགས་བཤད་པ་ལ། ད་མཚན་ཉིད། དབྱེ་བ། སྒྲ་བཤད།
འདོད་ཚུལ་བྱས་ནས་ད་བཞི་པ་འདོད་ཚུལ་བཤད་པ་ལ།
02:49གཞི་ཡི་འདོད་ཚུལ། ལམ་གྱི་འདོད་ཚུལ། འབྲས་བུའི་འདོད་ཚུལ།
དང་པོ་ལ་ཡུལ་དང་ཡུལ་ཅན། བྱས་ད་དེ།
02:57ཨིའི། བློས་རིག་པར་བྱ་བ་ཡུལ་གྱི་མཚན་ཉིད། ད་དེ་མ་ཤེས་པ་གལ་མི་འདུག
ད་དེ་ལ་དབྱེ་ན། ཨིའི་དབྱེ་ཚུལ་ད་མི་འདྲ་བ་བྱས་ནས་བདེན་པ་གཉིས་སུ་དབྱེ་བ།
03:06ད་ཡུལ་ལ་དབྱེ་ན་བདེན་པ་གཉིས་སུ་དབྱེ་བ།
རང་མཚན་དང་སྤྱི་མཚན་གཉིས་སུ་དབྱེ་བ།
མདོ་སྡེ་པའི་ལུགས་ཀི་ད་བདེན་གཉིས་རྣམ་གཞག་ཤེས་པ་ལ།
03:15རང་སྤྱིའི་རྣམ་གཞག་ཤེས་དགོས་ཡག་དེ་དཔེ་གལ་ཆེན་པོ་ཡིན་པ་རེད།
རང་སྤྱི་གཉིས་སུ་དབྱེ་བ༑ དགག་སྒྲུབ་གཉིས་སུ་དབྱེ་བ། མངོན་ལྐོག་གཉིས་སུ་དབྱེ་བ༑
དུས་གསུམ་དུ་དབྱེ་བ། གཅིག་དང་ཐ་དད་གཉིས་སུ་དབྱེ་བའོ། །
03:25དང་པོ་ནི། ཨིའི།
སྒྲ་དང་རྟོག་པས་བཏགས་པ་ལ་མ་ལྟོས་པར་རང་གི་སྡོད་ལུགས་ཀྱི་ངོས་ནས་རིགས་པས་དཔྱད་བཟོད་དུ་གྲུབ་པའི་ཆོས་དེ་དོན་དམ་བདེན་པའི་མཚན་ཉིད།
03:35དངོས་པོ་དང༌། དོན་དམ་བདེན་པ། རང་མཚན། མི་རྟག་པ། འདུས་བྱས།
བདེན་གྲུབ་རྣམས་དོན་གཅིག
03:44ད་དེ་བདེན་གྲུབ་ག་རེ་ཟེར་གྱི་ཡོད་ན། ཨིའི།
ད་ད་ག་དེ་གལ་ལུགས་ཀྱི་བདེན་གྲུབ་བསམ་བློ་བཏང་ན་མགཏོགས་གཞན་ཡང།
03:54འདུས་མ་བྱས་ཀྱི་ཆོས་ཀྱི་དེ་བདེན་གྲུབ་བརྩི་ཡིས་རེད་པ།
བྱས་ཙང་ད་དངོས་པོ་དང་། དོན་དམ་བདེན་པ་དང་། རང་བཙན་དང་། མི་རྟག་པ་དང་།
འདུས་བྱས་དང་། བདེན་གྲུབ་རྣམས་དོན་ཅིག
04:02རྟོག་པས་བཏགས་པ་ཙམ་དུ་གྲུབ་པའི་ཆོས་དེ་ཀུན་རྫོབ་བདེན་པའི་མཚན་ཉིད།
དངོས་མེད་ཀྱི་ཆོས་དང་ཀུན་རྫོབ་བདེན་པ་དང༌། སྤྱི་མཚན་དང༌། རྟག་པ་དང༌།
འདུས་མ་བྱས་ཀྱི་ཆོས་དང༌། རྫུན་པར་གྲུབ་པ་རྣམས་དོན་གཅིག
04:11ཨིའི་་་་་ད་བདེན་གཉིས་ཀྱི་སྒྲ་བཤད། འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ཆོས་ཅན།
04:21ཀུན་རྫོབ་བདེན་པ་ཞེས་བྱ་སྟེ། བློ་ཀུན་རྫོབ་པའི་ངོར་བདེན་པའི་ཕྱིར།
ད་རྟོག་པ་ཨིའི་སྒྲ་དོན་ད་སྒྲ་དོན་སྣང་བ་ཟེར་དགོས་རེད་པས། ད་གང་ལྟར་དེ་འདྲ་ཡི།
04:30དོན་སྤྱིས་བསླད་བསྡད་མཁན་གྱི་དེ་འདྲ་འདྲ་བོའི་ཨིའི་བློ་འཁྲུལ་པ་ཟེར་དགོས་མེད་འགྲོ།
ད་བློ་ཀུན་རྫོབ་པའི་ངོར་བདེན་པའི་ཕྱིར་རོ། །
04:40འདིའི་ཀུན་རྫོབ་པ་ནི་རྟོག་པ་སྟེ།
རང་མཚན་མངོན་སུམ་དུ་མཐོང་བ་ལ་སྒྲིབ་པས་ན་ཀུན་རྫོབ་པ་ཞེས་བྱའོ། །
04:48ད་རང་མཚན་ཟེར་ཡག་དེ་ཁོ་དོན་གྱིས་ག་རེ་ཟེར།
གང་ཕྱིར་དངོས་ཀུན་རང་བཞིན་གྱིས། །
རང་རང་ངོ་བོ་ལ་གནས་ཕྱིར། ། བྱས་ནས་གསུང་བསྡད་ཡག་གི་རང་རང་གི་རང་མཚན་གི
04:58ངོ་བོ་འདྲ་བོ་རེ་རེ་ཡོད་བསྡད་པ། ད་དེ་མཐོང་བ་ལ་སྒྲིབ་པར་བྱེད་
མཁན་དོན་སྤྱིས་བསླད་ནས་ཁོ་སྒྲིབ་པར༌བྱེད་ཀྱི་ཡོད་པ་ཡིན་དུས་
རང་མཚན་མངོན་སུམ་དུ་མཐོན་བ་ལ་སྒྲིབ་པས་ན་ཀུན་རྫོབ་པ་ཞེས་བྱ་བའོ།

05:09འདི་ཡང་སྒྲ་བཤད་ཙམ་ཡིན་གྱིས། བློ་ཀུན་རྫོབ་པ་རྟོག་པའི་ངོར་བདེན་པ་ཡིན་ན།
ཀུན་རྫོབ་བདེན་པ་ཡིན་པས་ཁྱབ་པ་མེད་དེ།
དོན་དམ་བདེན་པའི་མཚན་གཞི་བུམ་པ་ལྟ་བུ་ཡང༌།
བློ་ཀུན་རྫོབ་པ་རྟོག་པའི་ངོར་བདེན་པའི་ཕྱིར།
05:19གང་ཟག་གི་བདག་དང༌།
སྒྲ་རྟག་པ་ལྟ་བུ་བློ་ཀུན་རྫོབ་པ་རྟོག་པའི་ངོར་བདེན་པ་ཡང་།
ཐ་སྙད་དུ་ཡང་མ་གྲུབ་པའི་ཕྱིར། བུམ་པ་ལ་དོན་དམ་བདེན་པ་ཞེས་བྱ་སྟེ།
05:28བློ་དོན་དམ་པའི་ངོར་བདེན་པའི་ཕྱིར། འདིའི་བློ་དོན་དམ་པ་ནི།
སྣང་ཡུལ་ལ་མ་འཁྲུལ་བའི་ཤེས་པ་ལ་བྱའོ། །
05:36བདེན་གཉིས་ཀྱི་འཇོག་ཚུལ་འདི་རིགས་པའི་རྗེས་འབྲང་གི་མདོ་སྡེ་པའི་ལུགས་ཡིན་ལ།
ཨིའི་ལུང་གི་རྗེས་འབྲང་གི་མདོ་སྡེ་པས།
05:43བདེན་གཉིས་ཀྱི་རྣམ་གཞག་སྔར་བྱེ་སྨྲས་ལུགས་ཀྱི་ད་བདེན་གཉིས་ཀྱི་རྣམ་གཞག་བཤད་པ་དང་མཐུན་པ་ཁས་ལེན་ནོ།གསུངས་ཤག
འོ་ཡ།
05:52ད་འདིར་རང་སྤྱི་གཉིས་ཟེར་བསྡད་ཡག་དེ།
རང་མཚན་དང་སྤྱི་མཚན་ཟེར་བསྡད་ཡག་གི་ད་དོན་དམ་པར་དོན་བྱེད་ནུས་པའི་ཆོས།
རང་མཚན་གྱི་མཚན་ཉིད།
06:02ད་དངོས་པོའམ་གཅིག་དོན་བྱེད་ནུས་པ་ཟེར་ལབ་དུས་ཁོ་རང་ཕ་གིའི།
ཕན་གནོད་འདྲེན་མཁན་ཞིག་ཡོང་བསྡད་གི་འདུག་ག
ད་དེ་དོན་དམ་པར་དོན་བྱེད་ནུས་པ་རང་མཚན་རེད་ཟེར།
06:12མཚན་གཞི་ནི་བུམ་པ་ལྟ་བུ། དོན་དམ་པར་དོན་བྱེད་མི་ནུས་པའི་ཆོས་དེ།
སྤྱི་མཚན་གྱི་མཚན་ཉིད། མཚན་གཞི་ནི། ད་འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ།
ད་རང་འཛིན་པའི་རྟོག་པ་སྐྱེ་ཡག་དེ་འདྲ་ད་གཅིག
06:21འདི་ཡང་ད[་བྱེད་]བྱས་པ་ཟེར་གྱི་ཡོད་ན་མེད་ན་མི་ཤེས་ཏེ།
ད་གང་ལྟར་དེ་འདྲའི་རྒྱུ་འབྲས་ཀྱི་དོན་བྱས་པའི་བྱ་བ་བྱེད་ཡག་ཞེ་དྲག་ཡོད་མ་རེད་པ།
06:28ད་འདུས་མ་བྱས་ཀྱི་ནམ་མཁའ་ལྟ་བུ། ད་སྤྱི།
བྱེ་བྲག་ཟེར་ཡག་དེ་ཚོའི་གྲས་རྟོག་པས་བཀོད་བཞག་པ་ཞིག་རེད་འདུག་ག
རྟོག་པས་བཀོད་བཞག་པ་གཅིག་མ་གཏོགས།
06:36དངོས་པོའི་རང་མཚན་འདྲ་བོ་རང་བཞིན་འདྲ་བོ་འདི་འདྲ་གཅིག་གི་བཞག་ཡག་ཡོད་མ་རེད་པ།
སྤྱི་དང༌། བྱེ་བྲག་དང༌། ལྡོག་པ་དང་།
06:44ད་གཅིག་དང་ཐ་དད་ཟེར་དབྱེ་བ་ཕྱེ་ཡག་དེ་གའི་དེ།
བློས་ཕར་བཅོས་ནས་བློས་བཏགས་ནས། ཨིའི་དོན་དེ་གའི་དེ་བཞག་ཡོང་གི་ཡོད་རེད་པ་ད།
06:54ད་བློས་རྟོགས་ཡག་ད་ཡོད་རེད་ཡིན་ནས་དེ་གའི་དེ་ཁོ་ངོ་བོ་འདྲ་བོ་དེ་བཞག་ཀ་ཕྱིན་པ་ཡིན་ན།
བློས་ཕར་བཏགས་བཞག་པ་ཞིག་མ་གཏོགས་དོན་གྱིས་ངོས་ནས་ག་རེ་ཟེར་བ་རེད་ད།
ད་དོན་གྱི་ངོས་ནས་ཟེར་དགོས་རེད་པས་ད་ཡང་གང་ལྟར།
07:04ཨིའི་གཅིག་གི་ཕན་ནུས་ཀྱི་ཞུ་དགོས་རེད་པས་ད།
རྒྱུ་འབྲས་ཀྱི་རྒྱུ་འབྲས་ཀྱི་དེ་འདྲའི་སྐྱེ་བྱ་སྐྱེ་བྱེད་ཀྱི་བཟོ་འདྲ་བོ་དེ་འདྲ་ཡིས་བྱ་བ་བྱེད་ཐུབ་ཡག་ཅིག་མེད་པ་ཡིན་དུས་ཙ་ནས།
07:14སྤྱི་མཚན་དུ་གསུང་ཀི་ཡོད་པ་རེད། གཅིག་དང་ཐ་དད།
འགལ་བ་དང་འབྲེལ་བ་ལ་སོགས་པ་སྒྲོ་བཏགས་པའི་ཆོས་རྣམས་སྤྱི་མཚན་ཡིན་མོད་ཀྱང༌།
དེ་དག་ཡིན་ན་སྤྱི་མཚན་ཡིན་མི་དགོས།
07:23དེ་མཚན་གཞི་བཞག་ག་ཕྱིན་པ་ཡིན་ན་ཡང་ཁོ་འདུས་བྱས་ཀྱི་ཆོས་བཞག་ཐུབ་ཀྱི་རེད་པ།
དོན་བྱེད་ནུས་པས་ཆོས་བཞག་ཐུབ་ཀྱི་རེད་པ། རྣམ་འགྲེལ་ནས་ག་རེ་ཟེར།
07:30མཁས་པ་རྣམས་ཀྱིས་བྱས་པ་ཡིན། ། གསུངས་པ་ནང་བཞིན་དེ་འདྲ་གཅིག་ཡོང་གི་འདུག་ག
ད་ཁོ་ཐ་སྙད་འདྲ་མི་འདྲ་དེ་གའི་དེ་ད་ལྟ་བློས་ཡིད་བློ་རྟོག་པ་ཟེར་ཡག་དེ་འདུ་ཤེས་གཡེར་པོ་ཞེས་གསུངས་ནས།
07:39ཁོས་སྤུ་རིས་མང་པོ་ཕྱེ་ནས་ད་གཤམ་དེ་ནས་མར་གཞན་སེལ་ཟེར་ཡག་དེ་ཐོན་ཡོང་གི་རེད།
འོ་ད་ཁོས་གཅིག་རྟོག་པས་ཡུལ་དེ་དང་དེ།
07:47སྤུ་རིས་རུ་འདྲ་ཕར་ཆ་ཕྱེ་ནས།
ཨེ་ནི་ཡུལ་གྱི་ཡུལ་གྱི་ཁྱད་ཆོས་བྱེ་བྲག་པ་གཅིག་བློས་བཟུང་ཡོང་གི་ཡོད་རེད་པ།
རྟོག་པ་ཟེར་དུས་ཙ་ནས།
07:57དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས་འོ་ད་དེ་འདྲས་རྟོག་པས་བྱས་བཞག་པ་གཅིག་དང་འབྲེལ་ག་རེ་ཟེར་གཅིག་དང་ཐ་དད་ཟེར་ཡག་འདྲ་བོ།
གཅིག་འགལ་བ་འབྲེལ་བ་ཟེར་ཡག་འདྲ་བོ་དེ་འདྲ་ད་ཕྱེ་བསྡད་ཡག་དེ་ཚོའི་གྲས་དེ་སྤྱི་མཚན་རེད་བྱས་ཡིན་པ་རེད།
08:07ད་དེ་ནས་དགག་སྒྲུབ་གཉིས་སེ།
དགག་བྱ་དངོས་སུ་བཅད་པའི་ཚུལ་གྱིས་རྟོགས་པར་བྱ་བ་དགག་པའི་མཚན་ཉིད།
08:16དགག་སྒྲུབ་གཉིས་ཟེར་ཡག་ད་དགག་པ་ཟེར་ཡག ག་འདྲས་རེད་ཟེར་ལབ་ན།
གང་ལྟར་དོན་དེ་ད་དོན་དེ། དོན་དེ།
08:25བློ་ལ་ཡ་ཤར་ཡོང་དུས་ཙ་ནས་གཅིག་ཡིན་གཅིག་མིན་གཅིག་དེ་དགག་བྱ་གཅིག་ཕར་བསལ་ནས།
དགག་བྱ་བཅད་སྟོབས་ཀྱིས་སྒོ་ནས།
08:35བློ་ལ་ཤར་དགོས་ཡག་ཅིག་ཡིན་པ་ཡིན་ན་དགག་པ། དཔེར་ན་བུམ་པ་མེད་པ།
དཔེར་ན་གཞི་འདིར་དཔེར་ན་གླང་ཆེན་མེད་པ་ཟེར་ལབ་པ་ཡིན་ན།
08:42མེད་རྒྱུའི་གླང་ཆེན་གྱི་རྣམ་པ་འདྲ་བོ་ཤར་བའི་སྒོ་ནས་དེ་དང་བྲལ་བའམ།
དེས་སྟོང་པ་ཞིག་བློ་ལ་ཤར་དགོས་ཀྱི་འདུག་ག སེ་དེ་འདྲས་ཡིན་པ་ཡིན་དུས་ཙ་ནས།
08:51དགག་བྱ་དངོས་སུ་བཅད་པའི་ཚུལ་གྱིས་རྟོགས་པར་བྱ་བ་དགག་པའི་མཚན་ཉིད།
དེ་དང་གཞན་སེལ་དོན་གཅིག དེ་ལ་དབྱེ་ན་མེད་དགག་གི་གཞན་སེལ་དང༌།
མ་ཡིན་དགག་གི་གཞན་སེལ་གཉིས།
09:01ད་ [...]

2023-04-18 07:30 UTC, Tenzindharten requested changes
00:00 ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་གི་སྐད་ཆ་བཤད་ཡོང་དུས་ཙ་ནས། ཆོས་ལུགས་དང་འབྲེལ་བ་སླེབས་ཀྱི་ཡོད་རེད། 

00:09 འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་ཡ་ལོ་སྟོང་ཕྲག་ཁ་ཤས་ཀྱི་རིང་ལ་ཡ་གང་ལྟར་མིའི་སྤྱི་ཚོགས་ནང་ལོག་ལ་ཆོས་ཟེར་ཡག་ཞིག་བྱུང་ཡིན་པ་རེད། 

00:19 ད་ཆོས་རིགས་ཁ་ཤས་ཞེ་དྲག་དེ་སེ་གལ་ཡོད་མ་རེད་ད་ཅིག་གི་ཉི་མ་སོལ་ཡག་གི་བཟོ་འདྲ་བོ། 

00:27 ཅིག་དེ་བ་ཅིག་གི་ག་རེ་ཟེར་དགོས་རེད་ཕ་གི་མེ་ལ་ཡ་ཅིག་གི་ད་ག་རེ་ཟེར་དགོས་རེད་རྩ་ཆེན་པོ་བརྩི་ཡག་གི་བཟོ་འདྲ་བོ།

00:36 ད་དེ་ནས་མར་རེད་ཨེ་ནས་གཅིག་གི་ད་ལྷ་ཡོད་རེད་ཀླུ་ཡོད་རེད་ཟེར་ཡག་འདྲ་བོ་བཤད་བྱས་དེ་འདྲ་ཡི་ཐོག་ནས་དད་པ་བྱས་བསྡད་ཡག་འདྲ་བོ་གཅིག་ཡོང་བསྡད་ཀྱི་་འདུག་ག

00:45 ད་དེ་རྒྱས་ལ་ནི་ལྟ་གྲུབ་ཟེར་གལ་མི་འདུག་ག་གྲུབ་མཐའ་ཟེར་གལ་བཤད་ཡག་མི་གདུག་ག

00:49ད་གྲུབ་མཐའ་ཡོད་བསྡད་པའི་ཆོས་ལུགས་དེ་རྒྱས་དེ་ཕལ་ཆེར་རྒྱ་གར་ནང་ལ་ཆ་བཞག་ན་ཕལ་ཆེར་ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་ཕྱིན་པ་མིན་འགྲོ

00:58 ལོ་སྟོང་ཕྲག་གསུམ་ཙམ་ཀྱི་མཚམས་ནས་ཨེ་ནས་ད་ལྟ་གྲུབ་ཅེས་བྱས་ནས་དེའི་ཐོག་ནས་ད་ཆོས་ཀྱི་ག་རེ་ཟེར་དགོས་རེད་ཕ་གི

01:08ད་ཆོས་དད་གཅིག་བཤད་ཡོང་གི་ཡོད་རེད།

01:10བྱས་ནི། དེ་འདྲ་ཡི་ད་ལྟ་གྲུབ་ཡོད་བསྡད་མཁན་གྱི་ཕལ་ཆེར་ཆོས་ལུགས་གཙོ་ཆེ་བ་དེ་རྒྱས་དེ།

01:19ད་རྒྱ་གར་ནང་གྱི་ཆོས་ལུགས་ལ་ཆ་བཞག་ནའི་འདྲ་ཨེ་ནས་རིམ་པའི་ཅིག་གི་ད་དཔེར་ན་འཇིའུ་ལ་ཆ་བཞག་ནས།

01:28འཇིའུ་ཆོད་ལུགས་ལ་ཆ་བཞག་ནས་འདྲ་ཨ་ནི་ཡེ་ཤུ་ཡིན་ནས་རེད་ཁ་ཆེ་ཡིན་ནས་རེད་ཅིག་གི་ད་ག་རེ་ཡོད་རེད་ཨེ་ནས།

01:38ད་དེ་ལ་སོགས་པའི་གང་ལྟར་དེ་ལ་སོགས་པའི་ད་ཅིག་གྲུབ་མཐའ་ཡོད་བསྡད་མཁན་གྱི་ཆོས་ལུགས་དེ་རྒྱས་དེ་ཚང་མ་ལོག་གི་བསླབ་བྱ་རྒྱབ་ཡག་དེ་ཨེ་ནས་མི་སེམས་པ་བཟང་པོ་བྱེད་དགོས་རེད། བྱམས་པ་དགོས་རེད། 

01:48 བརྩེ་བ་དགོས་རེད་ཟེར་ཡག་དེ་བཟོད་པ་དགོས་རེད། ཆོག་ཤེས་དགོས་རེད་ཨེ་ནས་རང་རང་གི༌ཕི་གིའི་བསླབ་པ་སྲུང་དགོས་ཀྱིརེད།

01:56རང་རང་གི་ཆོས་ལུགས་ནས་བཤད་ཞག་པའི་བསླབ་པ་སྲུང་དགོས་ཀྱི་རེད་ཟེར་བྱས་ནས་བཤད་བསྡད་མཁན་ཅིག་ཚང་མ་གཅིག་པ་རེད་འདུག་ག  དེ་འདྲ་ཡིན་དུས་ཆོས་ལུགས་ཁག་དེ་རྒྱས་དེ་ཡིས་སྙིང་པོ་ག་རེ་བཤད་ཀྱི་ཡོད་རེད་ཟེར་ལབ་ན།

02:06མི་ལ་ལྷན་སྐྱེས་ཀྱི་ཡོད་བསྡད་པ་དང་། ལྷན་སྐྱེས་ཀྱི་ཡོད་བསྡད་པའི་ཐོག་ལ་མི་ལ་དགོས་མཁོ་ཡོད་བསྡད་པའི་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གལ་ཆེན་པོ་ཡིན་པ་ཅིག་ཆོས་ལུགས་ཚང་མས་བཤད་ཀྱི་འདུག་ག 

02:15ད་བྱམས་པ་དང་བརྩེ་བ་སྒྲུབ་སྟངས་དེ་ལ་ཨེ་ནས་ཐབས་ཤེས་མི་འདྲ་བ་བྱས་ཅས།

02:25རིགས་གཅིག་གིས་འཇིག་རྟེན་བཀོད་པ་པོ་ཡོད་རེད་ཟེར་བྱས་ནི། འཇིག་རྟེན་བཀོད་པ་པོ་དེ་བརྩེ་བའི་བདག་ཉིད་རེད་མཁྱེན་པའི་བདག་ཉིད་རེད། ཇི་ཙམ་དེ་འདྲ་ཡིན་དུས་ཙ་ནས།

02:34འཇིག་རྟེན་བཀོད་པ་ལ་ང་ཚོས་བརྩེ་བ་བྱེད་དགོས་རེད། དད་པ་བྱེད་དགོས་རེད། གུས་པ་བྱེད་དགོས་རེད། ཇི་ཙམ་གྱིས་འཇིག་རྟེན་བཀོད་པ་པོ་ལ་ཡ་དད་པ་དང་བརྩེ་བ་དང་གུས་བྱས་པ་དེའི་ཚོད་ཀྱིས།

02:43རང་ཉིད་ཀྱི་ཨེ་ནས་གཅིག་གི་དད་པ་དང་གཅིག་གི་བརྩེ་བ་ཟེར་ཡག་དེ་ཚོའི་གྲས་རང་ཉིད་ཀྱིས་ད་ཉམས་ལེན་བྱེད་དགོས་ཡག་ཅིག་དང་།

02:49ཨེ་ནས་འཇིག་རྟེན་བཀོད་པ་པོ་གཅིག་གིས་བཀོད་བཞག་པའི་ང་རང་ཚོ་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་ཨེ་ནས་ཅིག་བརྩེ་བ་བྱེད་དགོས་རེད་ཟེར་ཡག་ཅིག

02:56དཔེར་ན་ད་ལྟ་འདི་མུ་སི་ལིམ་ད་ལྟ་འདི་ཀོ་རན་ནང་ལོག་ལའི་འདི་འདྲ་བཤད་ཀྱི། དེ་འདྲ་བཤད་ཀྱི་ཡོད་པ་རེད།

03:03ངས་ད་ལྟ་ཁ་ཆེ་ངོ་ཤེས་པ་ཅིག་ལ་སྐད་ཆ་བྱུང་ཁ་ཆེའི་བླ་མ་ཅིག་སྐད་ཆ་འདྲ་བོ་བྱུང་ཨེ་ནས་ཀོ་རན་ནང་ལོག་ལ་ཡ་ཨེ་ནས།

03:10འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པའི་ད་སེམས་ཅན་ཚང་མ་ལོག་ལ་ཡ་ང་ཚོ་བྱམས་བརྩེ་བྱེད་དགོས་རེད་ཟེར་བྱས་ནས་དེ་འདྲ་ཡོད་རེད་སེ།

03:20དེ་འདྲ་ཡིན་དུས་ཙ་ནས་སྒྲུབ་བྱེད་འདི་འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་ནས་འཇིག་རྟེན་བཀོད་པ་པོ་ཟེར་ཡག་ཅིག འཇིག་རྟེན་བཀོད་པ་པོས་བཀོད་པ་རེད་ཟེར་ཡག་དེ་སྒྲུབ་བྱེད་དེ་འདྲ་ཞིག་འགོད་ཀྱི་ཡོདརེད། 

03:29བཀོད་པའི་གྲུབ་དོན་སྙིང་པོ་འདྲ་བོ་དེ་བྱམས་པ་དང་བརྩེ་བ་དང་དེ་ཚོ་་དགོས་ཀྱི་རེད་ཟེར་ཡག་ཅིག

03:34ད་བྱམས་པ་དང་བརྩེ་བ་ཟེར་ཡག་དེ་གཅིག་པུས་འདང་གི་ཡོད་མ་རེད༌ང་ཚོ་ད་ག་རེ་བྱས་ནས་ཡང་མི་མཐུན་པ་དང༌། འཁྲུག་པ་རྒྱབ་ཡག་འདྲ་བོ་ཡོང་གི་ཡོད་པ་ཡིན་དུས་ཨེ་ནས་བཟོད་པ་དགོས་རེད།

03:44གཅིག་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི་ཨེ་ནས་ཆོག་ཤེས་དགོས་རེད་ཟེར་ཡག་དེ་ཚོའི་གྲས་ཀྱི་བསླབ་བྱ་དེ་སླེབ་ཡོང་གི་འདུག་ག སྙིང་པོ་སྙིང་པོ་དེ་བྱམས་བརྩེའི་སྒང་ལ་ཡ་སྐད་ཆ་བཤད་ཀྱི་ཡོད་རེད་པ།

03:52དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ད་ལྟ་དུས་རབས་ཉི་ཤུ་བརྩ་ཅིག་པ་ཅིག་ཚན་རིག་ཡར་རྒྱས་ཧ་ཅང་ད་ཚད་མཐོན་པོ་སླེབ་བསྡད་ཡོད་པ།

04:01གཅིག་དངོས་པོ་ཡར་རྒྱས་སྤྱིར་བཏང་བཤད་པ་ཡིན་ན་ཧ་ཅང་གི་ད་ཚད་མཐོ་པོ་སླེབས་བསྡད་པའི་དུས་རབས་འདིའི་ནང་ལ་ཡིན་ནས། འཛམ་གླིང་ཤར་ནུབ་ག་ས་ག་ལ་ཡ་ཆོས་ལ་ཡ་དོ་སྣང་བྱེད་མཁན་གཅིག

04:12འཛམ་བུ་གླིང་འདིའི་སྒང་གི་མི་མང་བ་དེ་གའི་དེ་ཆོས་ལ་དད་གཅིག་ཨ་ཡོད་མེད་མི་ཤེས་ཏེ་ད་གང་ལྟར་ཆོས་ལ་དད་པ་བྱེད་མཁན་འཛམ་བུ་གླིང་འདིའི་སྒང་ལ་མང་པོ་གཅིག་དུས་ད་ལྟ་ཡིན་ནས་ཡོད་བསྡད་པ་རེད།

04:21དེ་ཁྲལ་དང་ཁྲིམས་ཀྱི་ཐོག་ནས་བཟོས་པ་གས་མ་རེད། རང་བཞིན་གྱིས་མི་ལ་ཡ་ཁོ་ཕན་ཐོགས་གཅིག་ཡོད་བསྡད་པ་གཅིག་དང་། ཁོ་དགོས་མཁོ་ཡོད་བསྡད་པ་གཅིག་མཐོང་བ་ཡིན་དུས་ཙ་ནས།

04:29མི་རིགས་གཅིག་གིས་ཆོས་ལ་ཡ་དོ་སྣང་བྱས་བསྡད་ཡག་ཅིག་ཆགས་བསྡད་ཀྱི་ཡོད་རེད་བ། དེ་འདྲ་ཡིན་དུས་ཙ་ནས།

04:34སྙིང་པོ་འདི་དངོས་པོ་ཡར་རྒྱས་ཀྱི་ལུས་པོ་བདེ་ཐང་བཟོ་ཡི་ཡོད་རེད། ལུས་པོའི་གཅིག་ཕ་གིའི།

04:43ཚོར་བ་བདེ་སྐྱིད་ཡོང་ཡག་གི་གང་ལྟར་ཆ་རྐྱེན་དེ་རྒྱས་དེ་དངོས་པོ་ཡར་རྒྱས་ཀྱི་ཐོག་ནས་སྒྲུབ་བསྡད་ཀྱི་ཡོད་རེད་ངེས་པར་དུ་དགོས་ཀྱི་ཡོད་རེད། དེ་ག་ནང་བཞིན་གྱི

04:52ལུས་པོའི་བདེ་ཐང་ཅིག་པོ་ཡི་ང་ཚོར་འདང་གི་ཡོད་མ་རེད། ག་རེ་ཟེར་ལབ་ན་ནང་རྣམ་པར་རྟོག་པས་རྐྱེན་པས་ཡང་དགའ་སྡུག་མང་པོ་ཞིག་ཡོང་གི་ཡོད་རེད། 

05:01དེ་འདྲ་དེ་རྣམ་པར་རྟོག་པ་ཁོ་རང་གི་ཐོག་ནས་ཐབས་ཤེས་ཤིག་བཙལ་ཏེ། 

05:07རྣམ་རྟོག་གི་ཨེ་ནས་ཐོག་ནས་གཅིག་དགའ་པོ་ཡོང་བསྡད་ཡག རྣམ་རྟོག་གི་ཐོག་ནས་མི་དགེ་བ་ཡོང་བསྡད་ཡག་དེ་ལ་རྣམ་རྟོག་ཁོ་རང་གི་ཐོག་ནས།

05:17དགའ་སྡུག་གི་ག་རེ་ཟེར་དགོས་རེད་ཕ་གིའི་ག་རེ་ཟེར་དགོས་རེད་ད་དགའ་སྡུག་གི་རྒྱུ་རྐྱེན་གཅིག་རྣམ་རྟོག་ཁོ་རང་ངོས་ནས་བསྒྲུབ་རྒྱུ་རེད་མ་གཏོགས།

05:24ནང་གི་སེམས་ཀྱི་དགའ་སྡུག་བྱུང་བསྡད་པ་དེ་ལ་ཁབ་བརྒྱབས་ནས་ཕན་ཡག་ཅིག་དང་། གཅིག་བཤགས་བཅོས་བྱས་ནས་ཕན་ཡག་འདྲ་བོ་གཅིག་དང་། དངུལ་མང་པོ་ཡོད་ན་དེས་སེལ་ཡག་ཅིག་མི་འདུག་ག

05:33 རེད་པ། ལུས་པོའི་དཀའ་སྡུག་སྡུག་བསྔལ་ཟེར་ཡག་དེ་རྒྱས་དེ། དཔེར་ན། འཚོ་བས་ཕོངས་པའི་སྡུག་བསྔལ་གྱི་མཚོན་པའི། ཅིག་ཚ་གྲང་གི་སྡུག་བསྔལ་གྱིས་མཚོན་པའི།

05:43 དེ་འདྲས་ཀྱི་སྡུག་བསྔལ་དེ་གའི་དེ་དངུལ་ཡོད་ན་ཨེ་ནས་ཁོ་གང་ལྟར་ཨེ་ནས་སྨན་བཅོས་བྱེད་ཡག་གི་མཚོན་པའི། གཅིག་ཟ་བཏུང་ལོངས་སྤྱོད་ཨེ་ནས་ཕུན་སུམ་ཚོགས་པ། 

05:52ད་ག་ནང་བཞིན་གྱི་གནས་ཁང་ཕུན་སུམ་ཚོགས་པ། ཁོར་ཡུག་ཕུན་སུམ་ཚོགས་པ། གཉེན་ཉེ་དུ་ཕུན་སུམ་ཚོགས་པ། དེ་འདྲ་གཅིག་གི་ངང་ནས་ལུས་པོའི་བདེ་ཐང་དེ་སྒྲུབ་ཐུབ་ཀྱི་ཡོད་རེད། 

06:01ལུས་པོའི་བདེ་སྐྱིད་དེ་སྒྲུབ་ཐུབ་ཀྱི་ཡོད་རེད། ད་ཡིན་ནས་གཅིག་གི་ཕྱི་ཡི་ད་དངུལ་དང་དངོས་པོ་ལ་བརྟེན་ནས།

06:11སྒྲུབ་ཐུབ་ཡག་ཡོད་བསྡད་པའི་ཆ་རྐྱེན་དེ་གའི་དེ་ཕུན་སུམ་ཚོགས་པོ་ཞིག་ཡོད་པ་ཡིན་ནས་སེམས་འཁྲུགས་བྱས། མ་སྐྱིད་པ་བྱེད་བསྡད་མཁན་མང་པོ་ཡོང་གི་འདུག་ག

06:20བྱས་ཙང་དེ་འདྲ་ཡི་ད་སེམས་འཁྲུག་བསྡད་ཡག་གི་མ་སྐྱིད་པ་ཡོང་བསྡད་ཡག་དེ་ཕྱི་དངོས་པོའི་མཐུན་རྐྱེན་མ་འདང་བའི་རྐྱེན་བྱས་ནས་དཀའ་ངལ་བྱུང་བ་མ་རེད།

06:29ནང་བསམ་བློ་གཏོང་སྟངས་ཀྱི་གཅིག་མ་འགྲིགས་ནས་ཨེ་ནས་སེམས་འཁྲུགས་བསྡད་པ་ཡིན་པ་རེད། དེ་འདྲ་ཡིན་དུས་ནས།

06:36གང་ལྟར་ང་རང་ཚོས་དོན་གཉེར་བྱེད་ཡག་གི་སེལ་རྒྱུའི་སྡུག་བསྔལ་དང༌། བསྒྲུབ་རྒྱུའི་བདེ་སྐྱིད་ལ་ཡ།

06:44གཙོ་བོ་ལུས་ཚོར་ལ་བརྟེན་བསྡད་པའི་ཨེ་ནས་བདེ་སྡུག་ཅིག་དང༌། གཙོ་བོ་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་ཅིག་གཉིས་ཡོད་བསྡད་པ་གསལ་པོ་རེད་འདུག་ག

06:53དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙ་ནས་ད་དེ་གཉིས་པོ་དེའི་ནང་ནས་ག་རེ་གལ་ཆེ་ཡི་རེད་ཟེར་ལབ་ན།

07:01ག་གི་རྦད་འགངས་འདྲ་བོ་ཆེ་ཡི་རེད་ཟེར་ལབ་ན་ཕལ་ཆེར་ནང་བསམ་བློའི་ཡིད་བློ་ལ་བརྟེན་བསྡད་པའི་བདེ་སྡུག་དེ་ཕལ་ཆེར་འགངས་ཆེ་བ་རེད་ཤག 

07:09དེ་ཡིན་པའི་རྒྱུ་མཚན་ག་རེ་རེད་ཟེར་ལབ་ན། ལུས་པོའི་དཀའ་ངལ་མང་པོ་ཞིག་སེམས་ཀྱིས་ཨེ་ནས་ཚེམ་པ་དེ་ཡི།

07:18ལུས་པོའི་དཀའ་ངལ་ཟིལ་གྱིས་གནོན་ཐུབ་ཀྱི་འདུག་ག ལུས་པོའི་གཅིག་དཔེར་ན་གཅིག དཔེར་ན་ང་རང་ཚོའི་གཅིག་སོ་སོ་ཆབ་སྲིད་ཀྱི་དམིགས་ཡུལ་འདྲ་བོ། 

07:29གཅིག་གི་ད་ག་ནང་བཞིན་གི་གཅིག་གི་སོ་སོའི་ད་གཅིག་ད་གང་ལྟར་དམིགས་ཡུལ་འདྲ་བོ་ཡང་ད་ག་ནང་བཞིན་དཔེར་ན་རྩེད་མོའི་གཅིག་ད་འགྲན་སྡུར་གྱིས་ཐོག་ནས།

07:39གཅིག་མིང་བླང་ཡག་གི་བཟོ་འདྲ་བོ་གཅིག་དེ་འདྲ་ཡི་གང་ལྟར་བསམ་བློའི་ཐོག་ནས་དོན་དུ་གཉེར་བའི་དོན་དག་གཅིག་འགྲུབ་ཡག་གི་དོན་དག་ལ།

07:49 ལུས་པོས་དཀའ་ལས་ཞེ་བོ་གཅིག་རྒྱག་ཐུབ་མཁན་ཡོང་གི་འདུག་ག

07:52ད་ག་ནང་བཞིན་ང་རང་ཚོས་ཆོས་ཉམས་ལེན་བྱེད་མཁན་གཅིག་གིས་ནང་བསམ་བློའི་ཐོག་ནས་གཅིག་གི་ཐར་པ་དང་ད་ཐར་པ་ཐམས་ཅད་མཁྱེན་པ་ད་གང་ཤེས་ཏེ་ད་སྔོན་ལ་སྤྱིར་བཏང་འདྲ་བོ་བཤད་པ་ཡིན་ན།

08:02གང་ལྟར་ནང་ཆོས་ཕྱོགས་ཀྱི་ཐོག་ནས་ད་སོ་སོའི་དམིགས་ཡུལ་ཞིག་སྒྲུབ་ཡག་ཅིག་བཞག་ནས་དེ་སྒྲུབ་ཡག་གི་ཆེད་དུ་ལུས་པོའི་དཀའ་ངལ་དང་དུ་ལེན་ནས།

08:10དང་དུ་ལེན་ནས་དཀའ་ངལ་ཁྱད་དུ་བསད་པ་མང་པོ་ཞིག་ཡོང་གི་འདུག་ག་དེ་གའི་དེ་ཁོ་དང་དུ་བླངས་ནས་དཀའ་ངལ་དེ་ཨེ་ནས་མྱོང་གི་ཡོད་རེད་མ་གཏོགས།

08:19མི་འདོད་བཞིན་དུ་སྡུག་བསྔལ་དེ་བྱུང་བ་མ་རེད་པ། དེ་འདྲ་ཡིན་དུས་ནང་སེམས་ཀྱི་ཡིད་ཚིམ་པ་དེས་ལུས་པོ་ལ་བརྟེན་པའི་དཀའ་ངལ་དེ་སྡུག་བསྔལ་དེ་རྒྱས་དེ།

08:29དང་དུ་ལེན་ཐུབ་ཡག་ཡོང་གི་ཡོད་རེད་པ། དེས་སེམས་ལ་མ་སྐྱིད་པ་ཡོང་རྒྱུའི་ཚབ་ལ་སེམས་ལ་ལྷག་པར་དུའང་ཡིད་ཚིམ་པ་ཡོང་ཡག་ཅིག་ཡོང་ཡག་འདུག་ག

08:39ད་དེ་ལས་ལྡོག་ནས་ནང་བསམ་བློ་འཁྲུགས་བསྡད་ཡོད་ན་ཕྱི་ཡི་དངོས་པོའི་མཐུན་རྐྱེན་ག་ཚོད་ཀྱི་བཟང་པོ་ཞིག་ཡོད་པ་ཡིན་ནས།

08:47དེས་ནང་སེམས་ཀྱི་མ་སྐྱིད་པ་ཡོད་བསྡད་པ་དེ་ཟིལ་གྱིས་གནོན་ཐུབ་ཀྱི་མི་འདུག་ག དེ་འདྲ་ཡན་དུས་གཙོ་བོ་ཡིད་བློ་ལ་བརྟེན་པའི་བདེ་སྡུག་དེ།

08:56འགངས་ཆེ་བ་དེ་རེད་ཤག་ཕན་གནོད་ཤུ [...]

2023-04-18 07:45 UTC, closed without merging