stt001 pull
MonlamAI/STT001 pull request #9
Opened 2023-01-24 10:55 UTC by DickyiDolma1376

pull stt001

2023-03-30 14:26 UTC, geshecelon requested changes
02:10 ཐ་མི་ལ་ཡང་ནང་གསེས་ཀྱི་ཐ་ཡང་ང་ཚོས་ཅིག་འེས་ག་རེ་ཟེར་འོ་ཅིག་ཐ། ༼ཐ་ཡི་ཚབ་ད་བྲི་ན་ལེགས། ཕྱིན་ཆད་ད་ཡིག་བྲི་རོགས་༽
02:26 ཡང་ཅིག་ཐ་ཁྱེད་རང་ཚོ་ཀོ་རི་ལ་ཆ་བཞག་ན་ཅིག་ཞིང་ལས་འདྲ་བོ་བྱས་ཅས་༼ཅིག་བྱེད་བསྡད་མཁན་༽བསྡད་མཁན་ད་ག་ནང་བཞིན་ཉ་ཟིན་བསྡད་མཁན་ཉ་གཏོང་པ་དེ་ཚོས་དྲས་དེ་འོ་ཅིག་ཁ་ཐུག་ཁ་ཐུག་སོ་སོ་འཚོ་བ་སྐྱལ་ཡས་ཀྱི་འེ་ལས་དེ་མ་གཏོགས་འོ་དེ་ལས
03:23 དེ་གཞིར་བཞག་གིས་ཐོག་ནས་འེས་རྣམ་དཔྱོད་འདྲ་བོ་གསར་པ་ཅིག་གིས་འེས་ཁོ་ཅིག་ཡང་འེས་གྲུབ་མཐའ་ཚད་འདྲ་བོ་ཅིག་འེས་སྦྱོར་བ་༼འཇོག་པ་༽ཡང་།
03:42 འཁྲུལ་འཁོར་འཁྲུལ་ཆས་ལ་བརྟེན་ནས་འཁྲུལ་ཆས་བརྟེན་ཨ་ནེ་རྕིས་༼རྩིས་༽བརྒྱབ་ནས་འེས་ཚད་གཞལ་རྩིས་བརྒྱབ་འདི་འདྲ་ཡི་ཐོག་ནས་དངོས་པོའི་གནས་ལུགས་གཏན་ལ་འབབ་བསྡད་པ་ཅིག་ཡོང་བསྡད་ཀྱི་འདུག་ག།
04:15ཐ་འདི་བརྡས་དྲངས་ནས་འེ་གྲུབ་མཐའ་སྨྲ་བ་འདིགཞུང་ལུགས་ལ་༼དེ་ལ་ཚགས་དུང་ཆད་འདུག༽སྦྱངས་དེ་གཞི་ལམ་འབྲས་གསུམ་གྱི་རྣམ་བཞག་ཟེར་དགོས་བྱུང་ན་ཡང་འདི་རྙོག་དྲ་ཚ་བོ་ཞིག་མིན་འགྲོ་འོ་དཔེར་ན
04:26རྒྱང་འཕེན་པ་ཟོ་རེ་འདྲ་བོ་རྒྱང་འཕེན་པ་གཅིག་འེས་འེས་རྒྱང་འཕེན་པ་ལ་ནང་གསེས་ཅིག་བརྕི་ཡི་༼རྩིས་༽་འདུག་ག་རྒྱང་འཕེན་པ།
04:50ཡང་ན་ཚད་འདི་ཁ་རྐྱང་རྐྱང་གི་བདེ་སྐྱིད་འདི་འབྲས་བུ་ལ་བཞག་འདི་སྒྲུབ་བྱེད་ཐབས་དེའི་ལམ་ལ་བཞག་འདི་༼འདིའི་༽གཞི་མ་འདྲ་བོ་ཅིག་བཞག་ཅས་ཡང་ན་གཞི་ལམ་འབྲས་གསུམ་སྦྱངས་ན་མ་གཏོགས།
06:12 གྲུབ་པའི་མཐའ་ཞེས་བརྗོད་པའི་ཕྱིར་ཟེར་འོ་ཐ་དེ་འདྲ་ཅིག་རེད་ཞག། ༼བཞག་༽
06:26 འེས་འདི་རེད་པར་༼འདི་རེད་འདུག་ག་༽གྲུབ་མཐའ་ལ་ཞུགས་པ་དང་འེས་མ་རེད་གྲུབ་མཐའ་ལ་མ་ཞུགས་པ་དང་གྲུབ་མཐའ་ཞུགས་པའོ། ༼རྫོགས་ཚིག་རྗེས་ལ་ཤད་གཉིས་ངེས་པར་བྲི་རོགས་༽
06:36  དང་པོ་གྲུབ་མཐའ་ལ་མ་ཞུགས་པ་འདི་རིགས་པས་སྦྱར་བའི་གཞུང་ལུགས་ལ་མ་བརྟེན་པར་རང་དགར་ཚེ་འདིའི་བདེ་བ་ཙམ་དོན་དུ་གཉེར་བའོ། ༼རྫོགས་ཚིག་རྗེས་ལ་ཤད་གཉིས་ངེས་པར་བྲི་རོགས་༽

06:56 ཕྱི་ནང་གི་གྲུབ་མཐའ་སྨྲ་བ་རྣམས་ཀྱི་ཐ་ཤལ་བ་མུ་སྟེགས་རྒྱང་འཕེན་པས་ཀྱང་ཕྱི་ནང་གི་ ༼གྲུབ་མཐའ་ཕྱི་ནང་གི་༽རྒྱུ་འབྲས་རྣམས་ཡོད་མེད་དཔྱོད་པ་ལ་ཞུགས་ནས།
07:13 དབྱེ་ན་འེས་གཉིས། ཕྱི་རོལ་པ་དང་ནང་པ་འོ།་ ༼རྫོགས་ཚིག་རྗེས་ལ་ཤད་གཉིས་ངེས་པར་བྲི་རོགས་༽

དེ་རིང་འདི་ལ་མཚམས་འཇོག་རྒྱུ་ཡིན། རྗེས་སུ་མུ་མཐུད་དེ་ནོར་བཅོས་བྱེད་ཆོག

2023-03-31 02:41 UTC, DickyiDolma1376 commented
ལགས་སོ།རྒན་ལགས།

On Thu, 30 Mar 2023, 19:56 geshecelon, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> 02:10 ཐ་མི་ལ་ཡང་ནང་གསེས་ཀྱི་ཐ་ཡང་ང་ཚོས་ཅིག་འེས་ག་རེ་ཟེར་འོ་ཅིག་ཐ། ༼ཐ་ཡི་ཚབ་ད་བྲི་ན་ལེགས།
> ཕྱིན་ཆད་ད་ཡིག་བྲི་རོགས་༽
>
> 02:26 ཡང་ཅིག་ཐ་ཁྱེད་རང་ཚོ་ཀོ་རི་ལ་ཆ་བཞག་ན་ཅིག་ཞིང་ལས་འདྲ་བོ་བྱས་ཅས་༼ཅིག་བྱེད་བསྡད་མཁན་༽བསྡད་མཁན་ད་ག་ནང་བཞིན་ཉ་ཟིན་བསྡད་མཁན་ཉ་གཏོང་པ་དེ་ཚོས་དྲས་དེ་འོ་ཅིག་ཁ་ཐུག་ཁ་ཐུག་སོ་སོ་འཚོ་བ་སྐྱལ་ཡས་ཀྱི་འེ་ལས་དེ་མ་གཏོགས་འོ་དེ་ལས
>
> 03:23 དེ་གཞིར་བཞག་གིས་ཐོག་ནས་འེས་རྣམ་དཔྱོད་འདྲ་བོ་གསར་པ་ཅིག་གིས་འེས་ཁོ་ཅིག་ཡང་འེས་གྲུབ་མཐའ་ཚད་འདྲ་བོ་ཅིག་འེས་སྦྱོར་བ་༼འཇོག་པ་༽ཡང་།
>
> 03:42 འཁྲུལ་འཁོར་འཁྲུལ་ཆས་ལ་བརྟེན་ནས་འཁྲུལ་ཆས་བརྟེན་ཨ་ནེ་རྕིས་༼རྩིས་༽བརྒྱབ་ནས་འེས་ཚད་གཞལ་རྩིས་བརྒྱབ་འདི་འདྲ་ཡི་ཐོག་ནས་དངོས་པོའི་གནས་ལུགས་གཏན་ལ་འབབ་བསྡད་པ་ཅིག་ཡོང་བསྡད་ཀྱི་འདུག་ག།
>
> 04:15ཐ་འདི་བརྡས་དྲངས་ནས་འེ་གྲུབ་མཐའ་སྨྲ་བ་འདིགཞུང་ལུགས་ལ་༼དེ་ལ་ཚགས་དུང་ཆད་འདུག༽སྦྱངས་དེ་གཞི་ལམ་འབྲས་གསུམ་གྱི་རྣམ་བཞག་ཟེར་དགོས་བྱུང་ན་ཡང་འདི་རྙོག་དྲ་ཚ་བོ་ཞིག་མིན་འགྲོ་འོ་དཔེར་ན
>
> 04:26རྒྱང་འཕེན་པ་ཟོ་རེ་འདྲ་བོ་རྒྱང་འཕེན་པ་གཅིག་འེས་འེས་རྒྱང་འཕེན་པ་ལ་ནང་གསེས་ཅིག་བརྕི་ཡི་༼རྩིས་༽་འདུག་ག་རྒྱང་འཕེན་པ།
>
> 04:50ཡང་ན་ཚད་འདི་ཁ་རྐྱང་རྐྱང་གི་བདེ་སྐྱིད་འདི་འབྲས་བུ་ལ་བཞག་འདི་སྒྲུབ་བྱེད་ཐབས་དེའི་ལམ་ལ་བཞག་འདི་༼འདིའི་༽གཞི་མ་འདྲ་བོ་ཅིག་བཞག་ཅས་ཡང་ན་གཞི་ལམ་འབྲས་གསུམ་སྦྱངས་ན་མ་གཏོགས།
> 06:12 གྲུབ་པའི་མཐའ་ཞེས་བརྗོད་པའི་ཕྱིར་ཟེར་འོ་ཐ་དེ་འདྲ་ཅིག་རེད་ཞག། ༼བཞག་༽
> 06:26 འེས་འདི་རེད་པར་༼འདི་རེད་འདུག་ག་༽གྲུབ་མཐའ་ལ་ཞུགས་པ་དང་འེས་མ་རེད་གྲུབ་མཐའ་ལ་མ་ཞུགས་པ་དང་གྲུབ་མཐའ་ཞུགས་པའོ།
> ༼རྫོགས་ཚིག་རྗེས་ལ་ཤད་གཉིས་ངེས་པར་བྲི་རོགས་༽
> 06:36
> དང་པོ་གྲུབ་མཐའ་ལ་མ་ཞུགས་པ་འདི་རིགས་པས་སྦྱར་བའི་གཞུང་ལུགས་ལ་མ་བརྟེན་པར་རང་དགར་ཚེ་འདིའི་བདེ་བ་ཙམ་དོན་དུ་གཉེར་བའོ།
> ༼རྫོགས་ཚིག་རྗེས་ལ་ཤད་གཉིས་ངེས་པར་བྲི་རོགས་༽
>
> 06:56 ཕྱི་ནང་གི་གྲུབ་མཐའ་སྨྲ་བ་རྣམས་ཀྱི་ཐ་ཤལ་བ་མུ་སྟེགས་རྒྱང་འཕེན་པས་ཀྱང་ཕྱི་ནང་གི་
> ༼གྲུབ་མཐའ་ཕྱི་ནང་གི་༽རྒྱུ་འབྲས་རྣམས་ཡོད་མེད་དཔྱོད་པ་ལ་ཞུགས་ནས།
> 07:13 དབྱེ་ན་འེས་གཉིས། ཕྱི་རོལ་པ་དང་ནང་པ་འོ།་
> ༼རྫོགས་ཚིག་རྗེས་ལ་ཤད་གཉིས་ངེས་པར་བྲི་རོགས་༽
>
> དེ་རིང་འདི་ལ་མཚམས་འཇོག་རྒྱུ་ཡིན། རྗེས་སུ་མུ་མཐུད་དེ་ནོར་བཅོས་བྱེད་ཆོག
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MonlamAI/STT001/pull/9#pullrequestreview-1365259169>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5CX4PMZSZBOOWY3G3G2D6TW6WJY3ANCNFSM6AAAAAAUE5YCXE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-31 07:48 UTC, geshecelon requested changes
08:48 ཡང་ཨ་ནི་འཇིག་རྟེན་བཀོད་པ་པོས་དཀོན་མཆོག་ལ་ཡ་རང་གི་ཐ་ག་རེ་༼ཞུ་དགོས་རེད་༽ཟེར་གོ་ཐ་ཕར་གི་འེས་མི་ཚེ་ཡོངས་རྫོགས་ལོག་དཀོན་མཆོག་དེ་ལ་ཡ་
08:59 ཐ་རག་ལས་འདས་པ་ཞིག་དང༌། དཀོན་མཆོག་དེར་ལ་ལྟོས་བསྡད་མཁན་ཞིག་བརྩི་ཆས་དེ་འདྲ་ཡི་ཐོག་ནས་འབད་ཡིད་ཁྱེད་ཤེས་ཀྱི་བསམ་པ་ཤུགས་ཆེན་པོ་ཞེ་པོ་ཞིག་འདུག་ག།
09:05  ད་ཡང་རྒྱང་འཕེན་པ་འདྲ་བོ་ཐ་༼གང་ལྟར་༽ང་རང་ཚོའི་མཐོང་ཆོས་ཀྱི་ཐ་ག་རེ་ཡོད་པ་འདི་རེད།
09:15 མ་གཏོགས་དེ་ལས་ལྷག་པའི་ཅིག་སྐྱབས་ཟེར་ཡས་ཞིག་ཅིག་ཤེས་དགོས་སེས་གང་མིན་འདུག་ག
09:19 འོ་ཡ་ཐ་བྱས་ན་བྱམས་ཆོས་ཤིག་༼ཇ་མཆོད་༽སྟོན་མཁས་བྱམས་ཆོས་༼ཇ་མཆོད་༽ཁྱེད་རང་ཚོ་གྲ་སྒྲིག་གས་སེ་ཡོད་པས་འོ་ཐ་གྲ་སྒྲིག་ཡོད་ན་ལབ་ཤིག་ཐ།
10:21 དེ་འདྲ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽ད་ཐ་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་ཟེར་ཡས་འདི། 
11:59 སྡུག་བསྔལ་གྱི་རྩ་བ་ཨ་ནི་བདག་ཏུ་འཛིན་པའི་བདག་འཛིན་གྱི་བྱེད་ཀྱི་ཡོ་རེད།སྡུག་བསྔལ་གྱི་རྕ་བ་༼རྩ་བ་༽ཆགས་སྡང་གིས་བྱས། 
12:05 ཆགས་སྡང་གི་རྩ་བ་བདག་ཏུ་འཛིན་པས་བྱས། དེ་འདྲ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽་བདག་ཏུ་འཛིན་པ་དེ་ཕྱིན་ཅི་ལོག་པའི་བློ་མིན་པ་ཅིག།༼རྗེས་འཇུག་ག་ཡི་རྗེས་སུ་ཤད་མི་དགོས།༽ 
12:14 ཕྱིན་ཅི་མི་ལོག་པའི་བློ་ཞིག་ཡིན་པ་ཡིན་ན་འེས་ཁོ་དེར་ལ་གཉེན་པོ་ཡོང་ཡས་མེད་པ་རེད། དེ་ལ་འགལ་ཟླ་ཡོང་གྱི་རེད་དེ། ཡིན་ནས་དེར་ལ་གཉེན་པོ་ཡོང་ཐུབ་ཡས་ཡོ་མ་རེད།
 ཉིན་གུང་ཞལ་ལག་གི་སྔོན་ལ་ཆུ་ཚོད་ཕྱེད་ཀ་ཙམ་ནོར་བཅོས་བྱས་པའི་མཚམས་དེ་འདི་ཡིན།

2023-04-01 07:04 UTC, DickyiDolma1376 commented
རྒན་ལགས་དེའི་མཇུག་ནས་ནོར་བཅོས་མེད་དམ།
On Fri, 31 Mar 2023, 13:18 geshecelon, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
>
> 08:48 ཡང་ཨ་ནི་འཇིག་རྟེན་བཀོད་པ་པོས་དཀོན་མཆོག་ལ་ཡ་རང་གི་ཐ་ག་རེ་༼ཞུ་དགོས་རེད་༽ཟེར་གོ་ཐ་ཕར་གི་འེས་མི་ཚེ་ཡོངས་རྫོགས་ལོག་དཀོན་མཆོག་དེ་ལ་ཡ་
> 08:59 ཐ་རག་ལས་འདས་པ་ཞིག་དང༌།
> དཀོན་མཆོག་དེར་ལ་ལྟོས་བསྡད་མཁན་ཞིག་བརྩི་ཆས་དེ་འདྲ་ཡི་ཐོག་ནས་འབད་ཡིད་ཁྱེད་ཤེས་ཀྱི་བསམ་པ་ཤུགས་ཆེན་པོ་ཞེ་པོ་ཞིག་འདུག་ག།
> 09:05
> ད་ཡང་རྒྱང་འཕེན་པ་འདྲ་བོ་ཐ་༼གང་ལྟར་༽ང་རང་ཚོའི་མཐོང་ཆོས་ཀྱི་ཐ་ག་རེ་ཡོད་པ་འདི་རེད།
>
> 09:15 མ་གཏོགས་དེ་ལས་ལྷག་པའི་ཅིག་སྐྱབས་ཟེར་ཡས་ཞིག་ཅིག་ཤེས་དགོས་སེས་གང་མིན་འདུག་ག
>
> 09:19 འོ་ཡ་ཐ་བྱས་ན་བྱམས་ཆོས་ཤིག་༼ཇ་མཆོད་༽སྟོན་མཁས་བྱམས་ཆོས་༼ཇ་མཆོད་༽ཁྱེད་རང་ཚོ་གྲ་སྒྲིག་གས་སེ་ཡོད་པས་འོ་ཐ་གྲ་སྒྲིག་ཡོད་ན་ལབ་ཤིག་ཐ།
>
> 10:21 དེ་འདྲ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽ད་ཐ་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་ཟེར་ཡས་འདི།
>
> 11:59 སྡུག་བསྔལ་གྱི་རྩ་བ་ཨ་ནི་བདག་ཏུ་འཛིན་པའི་བདག་འཛིན་གྱི་བྱེད་ཀྱི་ཡོ་རེད།སྡུག་བསྔལ་གྱི་རྕ་བ་༼རྩ་བ་༽ཆགས་སྡང་གིས་བྱས།
> 12:05 ཆགས་སྡང་གི་རྩ་བ་བདག་ཏུ་འཛིན་པས་བྱས།
> དེ་འདྲ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽་བདག་ཏུ་འཛིན་པ་དེ་ཕྱིན་ཅི་ལོག་པའི་བློ་མིན་པ་ཅིག།༼རྗེས་འཇུག་ག་ཡི་རྗེས་སུ་ཤད་མི་དགོས།༽
> 12:14 ཕྱིན་ཅི་མི་ལོག་པའི་བློ་ཞིག་ཡིན་པ་ཡིན་ན་འེས་ཁོ་དེར་ལ་གཉེན་པོ་ཡོང་ཡས་མེད་པ་རེད།
> དེ་ལ་འགལ་ཟླ་ཡོང་གྱི་རེད་དེ། ཡིན་ནས་དེར་ལ་གཉེན་པོ་ཡོང་ཐུབ་ཡས་ཡོ་མ་རེད།
> ཉིན་གུང་ཞལ་ལག་གི་སྔོན་ལ་ཆུ་ཚོད་ཕྱེད་ཀ་ཙམ་ནོར་བཅོས་བྱས་པའི་མཚམས་དེ་འདི་ཡིན།
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MonlamAI/STT001/pull/9#pullrequestreview-1366429217>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5CX4PKV5JXDWPLPXOA72HTW62D6XANCNFSM6AAAAAAUE5YCXE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-01 07:10 UTC, geshecelon requested changes
12:47 དེའི་བདེན་པ་ནི་ནམ་ཡིན་ན་ཡང་དེ་ཡིས་རིག་ཐུབ་པ་ཅིག་ཡོང་གི་རེད། སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽བདེན་པ་རིག་པའི་བློ་དེ་ཨ་ནི་ཕྱིན་ཅི་ལོག་ཏུ་འཛིན་པའི་བློ་དེ་ལ་ག་དུས་ཡིན་ན་ཡང་གནོད་མཁན་ཆགས་བསྡད་ཀྱི་རེད་བ།

13:04 སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽འེས་ཆོས་ཐམས་ཅད་སྟོང་ཞིང་བདག་མེད་པ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས༽བདག་ཏུ་འཛིན་པ་དེ་ཕྱིན་ཅི་ལོག་པའི་བློ་ཡིན་པ་ཞིག་བཤད་ཐུབ་ཡས་ཞིག་དང་།

མཚམས་འདི་ནས་ STT001-07 ཞུས་དག་ཟིན།

2023-04-01 07:31 UTC, geshecelon requested changes
00:00ད་དེས༼འདི༽་འེས་ང་རང་ཚོ་ད་གྲུབ་མཐའ་གོང་འོག་ཚང་མ་ལོག་གི་དབང་པོའི་ཤེས་པ་ཟེར་ཡས་འདི།
00:54སོ་ཁ་སང་ཞུས་པ་ནང་བཞིན་རེད་challenging༼ཆའ་ལེན་ཇིན་༽སླེབས་ཀྱི་ཡོ་རེད་ད།challengingསླེབས་03:05མིན་རྒལ་དུ་མཉམ་པ་འོ་གསུངས་བཞག།༼རྗེས་འཇུག་ག་ཡི་རྗེས་ལ་ཤད་མ་བྲི་རོགས།༽  ཚིག་དང་མིང་ཡི་དེ་དག་ནི་གཟུགས་ཙམ་འདུ་བྱེད་དག་ཏུ་འདུས་གསུངས་པ་ནང་བཞིན་

06:09 བྱས་ཙང་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཁོ་འཁྲུལ་བའི་བློ་ཆགས་འདུག་ག། ༼ཤད་དེ་མ་བྲི་རོགས་༽ འོ་སོ་ད་ཁོ་གསལ་ཡས་བློ་དེ་ཨ་ནི་འེས་དཔེར་ན། མི་སྡུག་པ་མཐོང་བའི་བློ།
ཆཱ་ལེན་ཇིན་
07:07 མཚམས་འདི་བར་ནོར་བཅོས་ཞུས་ཟིན། མུ་མཐུད་དེ་རྗེས་སུ་ཞུ་རྒྱུ་ཡིན།

2023-04-01 07:40 UTC, DickyiDolma1376 commented
Laso Genla

On Sat, 1 Apr 2023, 12:40 geshecelon, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> 12:47 དེའི་བདེན་པ་ནི་ནམ་ཡིན་ན་ཡང་དེ་ཡིས་རིག་ཐུབ་པ་ཅིག་ཡོང་གི་རེད།
> སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽བདེན་པ་རིག་པའི་བློ་དེ་ཨ་ནི་ཕྱིན་ཅི་ལོག་ཏུ་འཛིན་པའི་བློ་དེ་ལ་ག་དུས་ཡིན་ན་ཡང་གནོད་མཁན་ཆགས་བསྡད་ཀྱི་རེད་བ།
>
>
> 13:04 སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽འེས་ཆོས་ཐམས་ཅད་སྟོང་ཞིང་བདག་མེད་པ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས༽བདག་ཏུ་འཛིན་པ་དེ་ཕྱིན་ཅི་ལོག་པའི་བློ་ཡིན་པ་ཞིག་བཤད་ཐུབ་ཡས་ཞིག་དང་།
>
> མཚམས་འདི་ནས་ STT001-07 ཞུས་དག་ཟིན།
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MonlamAI/STT001/pull/9#pullrequestreview-1367822305>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5CX4PMGYOIGBVVBBZOJM2DW67IGVANCNFSM6AAAAAAUE5YCXE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-04 05:58 UTC, geshecelon requested changes
07:07དེ་ཁོ་སྐྱེས་ཡས་བྱམས་པ་སྐྱེས་ཡོང་དུས། ཁོ་འོས་པ་རེད་འདུག་ག། ཁོ་རྒྱུ་མཚན་ལྡན་པ་རེད་འདུག་ག། སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙམ་ནས་འེས་ལྡོག་ཕྱོགས་ཀྱི་07:15སྐྱོན་ཡོད་བསྡད་ཉན་གྱི་བློ་དེ་གས་དེ་འཁྲུལ་བས ༼པས་༽་བློ་དང༌། སྐྱོན་མེད་དེའི་09:05མ་འཁྲུལ་བའི་བློ་དེས་གིས་ཨ་ནི་ཁོ་མི་ཚེ་༼ཚེའི་༽འགྲོ་སྟངས་དེ་དེ་གས་དེ་ག་རེ་ཟེར་གོ་ཕར་གས་ཐབས་ཤེས་འདྲ་བོ་བྱས་ཡོང་དུས་ཨ་ནི་འདོད་པ་ནང་བཞིན་ཞིག་ཡོང་ཡས་ཀྱི་ད་རེ་བ་ཅིག།

09:13ཁོ་བརྒྱབ་དགོས་ཡོ་རེད་རེ་བ་ཞིག་རྒྱབ་ཀྱི་ཡོ་རེད།སོང་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙམ་ནས་ང་རང་ཚོ་སྤྱིར་སྟངས་ད་དེ་རིང་ཁ་སང་འཛམ་བུ་གླིང་འདི་སྒང་ལ་09:19སློབ་སྦྱོང་གལ་ཆེན་པོ་རེད་བརྗོད་པའི་རྩ་བ་འདི་ལ་ཐུག་གི་ཡོ་རེད་པ། ཁོ་ཚད་མའམ་མ་འཁྲུལ་བའི་བློ་ཅིག་གིས་འདོད་པའི་དོན་འགྲུབ་དགོས་ཀྱི་ཡོ་རེད་མ་གཏོགས།09:26འཁྲུལ་བའི་བློ་ཅིག་གིས་རྨོངས་པ་འེས་ཡང་ན་དོ་སྣང་ཁྱོན་ནི་མེད་བསྡད་པ། ཡང་ན་དོ་སྣང་ཡོད་པ་ཡིན་ནའང་ཁོ་དོན་དེར་ལ་ཕྱིན་ཅི་ལོག་ཏུ་འཛིན་བསྡད་ཉན་09:35འཁྲུལ་བའི་བློ་ཅིག་གིས་དོན་དེ་སྒྲུབ་ཐུབ་ཀྱི་ཡོ་མ་རེད་པ། ད་དེ་འདྲ་ཡིན་དུས་འཁྲུལ་བ་དང་མ་འཁྲུལ་བ། ཚད་མ་ཚད་མིན་ཟེར་ཡས་དེའི་དབྱེ་བ་ཕྱེ་བ་དེ་རྩ་དོན་སྒང་ལ་སླེབས་ཀྱི་འདུག་ག། ༼ཤད་དེ་མེད་པ་བཟོ་རོགས།༽

10:24དེ་ལ་ང་རང་ཚོ་སངས་རྒྱས་པའི་གཞུང་གི་ནང་ལོག་ནས་དབང་པོའི་ཤེས་པས་འེས་དེ་དང་དེ་འཛིན་པ་ཙམ་མ་གཏོགས། དེ་བཟང་ངན་དུ་རྟོགས་པ་དེ་མེད་པ་རེད། 10:33སྔོན་པོ་འཛིན་གྱིས། སྔོན་པོའོ་སྙམ་དུ་མི་འཛིན་གསུངས་པ་ནང་བཞིན་གི་འེས་སྔོན་འཛིན་མིག་ཤེས་ལྟ་བུས་འེ་འེ་༼འེ་འེ་ཞེས་པ་དེ་མེད་པ་ལྟ་བུ་སྣང་།༽སྔོན་པོ་འཛིན་པ་ཙམ་མ་གཏོགས་

10:50འེས་རྟོག་པས་རྟོག་པ་༼རྟོག་པས་༽བྱས་པ་ནང་བཞིན་ཅིག་དབང་པོ་ཤེས་པས་བྱེད་ཀྱིས་ཡོ་མ་རེད་ཁོ་ཡུལ་དེ་སྣང་ཙམ་དེ་དང་དེ་དེ་དང་དེའི་བསམ་པ་ཅིག་མ་གཏོགས་མེད་བྱས། 
11:44ཨ་ནི་ག་རེ་བཞུ་༼ཞུ་༽གོ་རེད་ཕར་གས་འེས་རྣལ་འབྱོར་མངོན་སུམ་གསུང་བསྡད་ཡས་དེ་འདྲ་ཅིག་གསུང་གི་ཡོ་རེད།དེ་གསལ་མི་རྟོགས་བློ་འབྲས་ཅན།

མཚམས་འདི་ནས་རྗེས་སུ་བྱ་རྒྱུ་ཡིན།

2023-04-05 04:22 UTC, geshecelon requested changes
12:56འེས་  གསུམ་པ་ལམ་གྱི་རང་བཞིན་ལ་ཐིག་པ་གསུམ་གྱི་ལམ་ལ་ཚོགས་ལམ། སྦྱོར་ལམ། མཐོང་ལམ། སྒོམ་ལམ། མི་སློབ་ལམ་དེ་ལམ་ལྔ་ཡི་རྣམ་བཞག་མཁས་ལེན་ཀྱོགས་༼ཀྱང་༽།13:09ས་བཅུའི་ཡེ་ཤེས་མི་འདོད། ཤེས་བཟོད་སྐད་ཅིག་མ་བཅུ་དྲུག་གི་སྐད་ཅིག་མ་དང་པོ་འེས་བཅོ་ལྔ་མཐོང་ལམ།
13:48སྒོམ་ལམ་རྡོ་རྗེ་ལྡན་པའི་ཏིང་ངེ་འཛིན་ལ་བརྟེན་ནས། ཉོན་མོངས་ཅན་གྱི་སྒྲིབ་པ་སྒྲིབ་པའི་ཐོབ་པ་ཆད་པའི་ཚུལ་གྱིས་སྤངས་ཏེ་དགྲ་བཅོམ་པའི་འབྲས་བུ་མངོན་དུ་བྱེད་དོ།།13:57བསེ་རུ་ལྟ་བུའི་རང་རྒྱལ་རྣམས་ཀྱིས་གང་ཟག་རང་རྐྱ་ཐུབ་པའི་རྫས་ཡོད་ཀྱིས་སྟོང་པར་རྟོགས་པས་ཟེར་༼ཟེར་དེ་མེད་པ་ལྟ་བུ་སྣང་༽།
14:22ཚོགས་དང་འབྲེལ་ཏེ་ཚོགས་ལམ་ཆེན་པོ་མན་ཆད་དུ་ཉམས་སུ་བླངས་ནས་སྦྱོར་ལམ་དྲོད་ནས་མི་སློབ་ལམ་གྱི་བར་སྟན་ཐོག་གཅིག་ལ་མངོན་དུ་བྱེད་དོ་ཟེར་༼ཟེར་དེ་མེད་པ་ལྟ་བུ་སྣང་༽།
14:48ཞུགས་གནས་བརྒྱད་པོ་གང་རུང་ལ་འཕགས་པས་ཁྱབ་པར་འདོད་དོ༑ ༼རྫོགས་ཚིག་འདི་ལ་ཤད་གཉིས་དགོས་༽འབྱོར་ལམ་རྟེན་གཅིག་ནས་བཟུང་སྟེ་ཟེར་ཡས་དེ་མིན་པ་ཡིན་པ་རེད།

15:01  དེ་ནས་བསྐལ་པ་བརྒྱར་མཚན་བཟང་གི་འེས་རྒྱུ་བསྒྲུབས་ཏེ་ཟེར་༼ཟེར་དེ་མེད་པ་ལྟ་བུ་སྣང་༽བྱང་ཆུབ་སེམས་དཔའ་ངེས་གནས་ཀྱིས་མཚན་རྣམ་པར་མི་འཇིག་གི་ལས་བསགས་ཡས་བསྐལ་པ་བརྒྱ་ཡི་བར་དུ།

མཚམས་འདི་ནས་ Stt001-22 ནོར་བཅོས་ཚར་སོང་།

2023-04-13 09:55 UTC, geshecelon requested changes
00:00གྲུབ་པ་ཡོད་པ་མཐའ་ཟེར་ལབ་དུས་ཁོ་ཚད་རོ་ཅིག་བསམ་བློ་གཏང་ནས་ད་ལུང་མཐའ་བརྙེད་པ་གང་ཡིན་ན་མིན་ནས།།༼ཚང་མའི་རྗེས་ལ་ཤད་གཉིས་རེ་བྲིས་འདུག ཤད་གཅིག་ལས་མི་དགོས། རྫོགས་ཚིག་ཡིན་ན་ཤད་གཉིས་དགོས།༽

06:12གྲུབ་པའི་མཐའ་ཞེས་བརྗོད་པའི་ཕྱིར་ཟེར་འོ་ད་དེ་འདྲ་ཅིག་རེད་བཞག།༼ག་རྗེས་ཤད་མི་དགོས།༽

06:16འེས་ལྕང་སྐྱ་སྒྲུབ་མཐའི་ནང་ལ་ཡང་གཞུང་ལུགས་ཟེར་ཡས་འདི་ག་རེ་ཟར་འདི་གཞི་ལམ་འབྲས་གསུམ་ཟེར་ཡས་དེ་གསུངས་མིན་འདུག།༼ག་རྗེས་ཤད་མི་དགོས།༽

མདོར་ན་གའི་རྗེས་ལ་ཤད་མི་དགོས། གལ་ཏེ་རྫོགས་ཚིག་ག་ཡིག་ཡིན་ན་ཤད་གཅིག་བྲི་དགོས།

2023-04-24 03:05 UTC, geshecelon requested changes
STT001-07 DATE: 24 APRIL, 2023

00:13འདི་འདྲ་བོ་བཞག་བསྡད་ཡས་དེ་ལ་གྲུབ་མཐའ་ཟེར་ན་འགྲིགས་ཀྱི་མི་འགྲོ།༼དེ་ལ་ཤད་མི་དགོས།༽
00:17བྱས་འདི་འདྲ་གྲུབ་མཐའ་འོ། ༼རྫོགས་ཚིག་ཡིན་ན་ཤད་གཉིས་དགོས།༽ད་དེ་ལ་སྤྱིར་གང་ཟག་ལ་དབྱེ་ན་ཟེར།

00:59སྙིང་རྗེ་ད་འབུ་དེ་ཉིན་མ་ཁ་ཤས་ཕྱིན་སོང་ཨ་ཙི་ད་འདི་ཆུ་ར་བོ་ཞིག་འཐུང་དགོས་ཀྱི་ཡོ་རེད་ཅི་བྱེད་དགོས་བསམས་ནས་ག་ལེར་འབུ་དེ་ཚུར་བསྒྲུགས་ཅས་༼བྱས་༽་ཨེ་ནི་ཆུ་ཐིག་ཚོད་ཅིག་བླུགས་བཅས་བྱས་ངའི་གཟབ་གཟབ་བྱས་ཀ་བྱས་པ་ཡིན།

03:18ཨེ་ནི་རང་གི་འདི་སྒང་ལ་ཅིག་ཕལ་གས་འེས་རྣམ་དཔྱོད་འདྲ་བོ་ཕར་བཏོན་ཅས།༼བྱས༽
03:42འཁྲུལ་འཁོར་འཁྲུལ་ཆས་ལ་བརྟེན་ནས། འཁྲུལ་ཆས་བརྟེན་ཨེ་ནི་རྩིས་བརྒྱབ་ནས་འེས་ཚད་གཞལ་རྩིས་བརྒྱབ་འདི་འདྲ་ཡི་ཐོག་ནས་དངོས་པོའི་གནས་ལུགས་གཏན་ལ་འབབ་བསྡད་པ་ཅིག་ཡོང་བསྡད་ཀྱི་འདུག་ག།༼ཤད་མི་དགོས།༽

04:14ད་འདི་བརྡས་དྲངས་ནས་འེ་གྲུབ་མཐའ་སྨྲ་བ་འདི་གཞུང་ལུགས་ལ་སྦྱངས་དེ་གཞི་ལམ་འབྲས་གསུམ་གྱི་རྣམ་བཞག་ཟེར་དགོས་བྱུང་ན་ཡང་འདི་རྙོག་དྲ་ཚ་བོ་ཞིག་མིན་འགྲོ་འོ་དཔེར་ན།04:26རྒྱང་འཕེན་པ་ཟོ་རེ་འདྲ་བོ་རྒྱང་འཕེན་པ་གཅིག་འེས་འེས་རྒྱང་འཕེན་པ་ལ་ནང་གསེས་ཅིག་རྕིས་ཡི་༼རྩིས་གི་༽འདུག་ག་ད་རྒྱང་འཕེན་པ།
04:44དེ་ལ་བརྟེན་པས་ལམ་གྱི་འབྲས་བུའི་རྣམ་གཞག་ཟེར་ཡས་ཅིག་བཤད་ཡས་ཡོད་འགྲོ་མེད་འགྲོ། ༼ཤད་མི་དགོས།༽
05:44བྱས་ན་འདི། འེས། ཞི་༼གཞི།༽ལམ་འབྲས་གསུམ་གྱི་རྣམ་བཞག་རང་གི་བློ་ངོར་གྲུབ་པའི་ཚུལ་ལུང་དང་རིག་པའི་ལམ་ནས་འེས་སྨྲ་བ་བྱེད་པ་སྟེ་སེ་ཨེ་ནི་གྲུབ་འབྲས།
06:12གྲུབ་པའི་མཐའ་ཞེས་བརྗོད་པའི་ཕྱིར་ཟེར།།༼ཤད་གཉིས་མི་དགོས།༽ འོ་ད་དེ་འདྲ་ཅིག་རེད་བཞག།༼ཤད་མི་དགོས།༽
07:04རིགས་པ་ལྟར་སྣང་ལ་ཡང་དག་པའི་རིགས་པར་རློམས་ནས་རང་གི་གཞུང་ལུགས་འཛུགས་པའི་ཕྱིར་རོ་ཟེར།།༼ཤད་གཉིས་མིད་དགོས།༽
07:09གཞི་ལམ་འབྲས་གསུམ་ཟེར་ཡས་འདི་མིན་འདུག།༼ཤད་མི་དགོས།༽ འདི་ཁྱད་གས་གལ་མིན་འདུག།༼ཤད་མི་དགོས།༽
09:15མ་གཏོགས་དེ་ལས་ལྷག་པའི་ཅིག་ད་སྐྱབས་ཟེར་ཡས་ཅིག་ཤེས་དགོས་སེས་གང་མིན་འདུག་ག།༼ཤད་མི་དགོས།༽
09:27ཕྱི་ནང་གི་གྲུབ་མཐའ་སྨྲ་བའི་ཁྱད་པར་ཡོད་དེ་སྟོན་པ་བསྟན་པ་ལྟ་བ་གསུམ་གྱི་སྒོ་ནས་འབྱེད་པའི་ཕྱིར།།༼ཤད་གཉིས་མི་དགོས༽
09:44ལྟ་བ་རྟག་གཅིག་རང་དབང་ཅན་གྱི་བདག་གིས་སྟོང་པར་འདོད་པའི་ཁྱད་པར་གསུམ་དང་ལྡན་ཞིང༌ཟེར།།༼ཤད་གཉིས་མི་དགོས༽
09:59འེས་འདུས་བྱས་ཐམས་ཅད་མི་རྟག་པ།།༼ཤད་གཉིས་མི་དགོས༽ ཟག་བཅས་ཐམས་ཅད་སྡུག་བསྔལ་བ།།༼ཤད་གཉིས་མི་དགོས༽ ཆོས་ཐམས་ཅད་སྟོང་ཞིང་བདག་མེད་པ།།༼ཤད་གཉིས་མི་དགོས༽ མྱང་ངན་ལས་འདས་པ་ཞི་བ་ཟེར་ཡས།
10:14དེ་མི་འདོད་མཁན་དེ་ཨེ་ནི། འེས་ད་ཆོས་འདི་ལས་ཕྱི་རོལ་དུ་གྱུར་པའི་ད་གྲུབ་མཐའ་སྨྲ་བ་ཟེར་ཆོག་གི་མེད་འགྲོ།།༼ཤད་མི་དགོས༽
10:22དེ་འདྲ་ཡིན་དུས་རྕ་ནས་༼རྩ་ནས་༽ད་ལྟ་ལྟ་བ་བཀའ་བཏགས་ཀྱི་ཕྱག་རྒྱ་བཞི་ཟེར་ཡས་འདི།
10:56འེས་དེ་ཅིག་གོ་གི་འདུག་ག འདུས་བྱས་ཐམས་ཅད་མི་རྟག་པ་ཟེར་དུས་ཙ་ནས་འེས་འགྱུར་བ་འགྲོ་བསྡད་ཡས་འདི་ཅིག་བཤད།།༼ཤད་གཉིས་མི་དགོས༽
11:29འེས་དེའི་གཞན་དབང་དུ་ཡོད་བསྡད་མཁན་དེ་གས་དེ་དང་དེ་གས་དེ་ཨེ་ནི་སྡུག་བསྔལ་བ་རེད་ཟེར།།༼ཤད་གཉིས་མི་དགོས༽
11:41ཨེ་ནི་ཟག་མེད་དེ་ག་འདི། འེས་ད་ག་རེ་ཟེར་གོ་ཕར་ཟག་མེད་དེ་མ་ཡིན་པའི་ཟག་བཅས་འདི་ག་འདི་སྡུག་བསྔལ་བའི་རང་བཞིན་རེད་ཟེར།།༼ཤད་གཉིས་མི་དགོས༽
11:59སྡུག་བསྔལ་གྱི་རྩ་བ་ཨེ་ནི་བདག་ཏུ་འཛིན་པའི་བདག་འཛིན་གྱི་བྱེད་ཀྱི་ཡོ་རེད། སྡུག་བསྔལ་གྱི་རྩ་བ་ཆགས་སྡང་གིས་བྱས།།༼ཤད་གཉིས་མི་དགོས༽

12:14ཕྱིན་ཅི་མི་ལོག་པའི་བློ་ཅིག་ཡིན་པ་ཡིན་ན། འེས་ཁོ་དེ་ལ་གཉེན་པོ་ཡོང་ཡས་མེད་པ་རེད། དེ་ལ་འགལ་ཟླ་ཡོང་གྱི་རེད་དེ། ཡིན་ནས་དེ་ལ་གཉེན་པོ་ཡོང་ཐུབ་ཡས་ཡོ་མ་རེད།།12:24ཡིན་ནས་འོ་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ཕྱིན་ཅི་ལོག་པའི་བློ་ཡིན་པ་ཡིན་དུས་རྩ་ནས། ཕྱིན་ཅི་ལོག་པའི་བློ་ཡིན་བློ་གཅིག་ཡིན་ཕྱིན་ཅད་ལ་ག་དུས་ཡིན་ནས་དེ་ལ་འགལ་ཟླ་ཡོང་བསྡད་ཀྱི་རེད།།༼ཤད་གཉིས་མི་དགོས༽
12:33འོ་དོན་ལ་འེས་མ་ཡིན་པ་ཅིག་ཨེ་ནི་ཡིན་པར་འཛིན་བསྡད་མཁན་ཅིག་ཡིན་དུས་རྩ་ནས་ཁོ་ཕྱིན་ཅི་ལོག་གི་བློ་ཆགས་པ་རེད།།༼ཤད་གཉིས་མི་དགོས༽
12:41ཁོ་དེ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་དོན་གྱི་ཡིན་ཚུལ་དེ་ག་དུས་ཡིན་ནས་ཁོ་བདེན་པ་ཞིག་ལ་བསྡད་བསྡད་ཀྱི་ཡོ་རེད།།༼ཤད་གཉིས་མི་དགོས༽
12:47དེའི་བདེན་པ་ནི་ནམ་ཡིན་ན་ཡང་དེ་ཡིས་རིག་ཐུབ་ཡག་ཅིག་ཡོང་གི་རེད།། སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་རྩ་ནས་བདེན་པ་རིག་པའི་བློ་དེ་ཨེ་ནི་ཕྱིན་ཅི་ལོག་ཏུ་འཛིན་པའི་བློ་དེ་ལ་ག་དུས་ཡིན་ནས་གནོད་མཁན་ཆགས་བསྡད་ཀྱི་རེད་བ།།༼ཤད་གཉིས་མི་དགོས༽
12:57སོ་དེ་འདྲ་ཡིན་དུས་ཁོ་ལ་གཉེན་པོ་འདུག་ག གཉེན་པོ་ཡོད་པ་ཙམ་དུ་མ་ཟད་པར་ཁོ་ཕྱིན་ཅི་མ་ལོག་པའི་བློ་ཆགས་ནས། ཁོ་རྒྱབ་བརྟེན་གྱི་ཚད་མ་ཡོད་པས་ཡིན་དུས་ཁོ་སྟོབས་ལྡན་རེད་འདུག་གཉེན་པོ་སྟོབས་དང་ལྡན་པ་རེད་འདུག་ག།༼ཤད་མི་དགོས།༽
13:04སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་རྩ་ནས་འེས་ཆོས་ཐམས་ཅད་སྟོང་ཞིང་བདག་མེད་པ་ཡིན་དུས་རྩ་ནས་བདག་ཏུ་འཛིན་པ་དེ་ཕྱིན་ཅི་ལོག་པའི་བློ་ཡིན་པ་ཞིག་བཤད་ཐུབ་ཡས་ཅིག་དང་།13:11དེ་འདྲ་བའི་བདག་ཏུ་འཛིན་པའི་བློ་དེ་ལ་གཉེན་པོ་སྟོབས་ལྡན་ཡོད་པ་དང་དེའི་དབང་གིས་གང་ལྟར་དེ་བློ་དེ་ཤུགས་ཆུང་དུ་ཆུང་དུ་འགྲོ་ཡས་དང་།
13:19ད་འགག་ཐུབ་ཡས་ཡོད་པ་ཟེར་ཡས་དེ་བསམ་བློ་མང་པོ་ཞིག་གཏོང་དགོས་ཡས་ཞིག་རེད།།༼ཤད་གཉིས་མི་དགོས༽


ཤད་ཚང་མ་ཡག་པོ་བྱས་ནས་གཟིགས་རོགས། ག་ཡི་རྗེས་ལ་ཤད་མི་དགོས། གལ་ཏེ་རྫོགས་ཚིག་ཡིན་ཤད་གཉིས་དགོས། དེ་མིན་ཤད་གཅིག་ལས་མི་དགོས། ག་ཡི་རྗེས་ལ་ཤད་མི་དགོས། འོན་ཀྱང་ག་རྫོགས་ཚིག་ཡིན་ན་ཤད་གཅིག་བྲི་དགོས། 

ད་རིང་ཡར་འབུལ་རྒྱུའི་ཆ་གཞི་ཡོད་དེ་ནོར་འཕྲུལ་མང་པོ་ཡོད་སྟབས། འབུལ་ཐུབ་ས་མ་རེད།

2023-04-25 02:54 UTC, geshecelon requested changes
04:58 ཤེས་ཁོང་ཚོ་ཚེ་ཕྱི་མ་བཤད་ཀྱི་ཡོ་མ་རེད། ཨེ་ཚེ་འདི་ལ་འེ་ཅི་གང་མཐོང་བསྡད་པ་དང་གང་བློ་ལྷན་སྐྱེས་ལ་ཅི་ཡོད་བསྡད་པ་དེ་རྕམ་༼ཙམ་༽ཞིག་རེད་མ་གཏོགས་དེ་ལས་ལྷག་གས།

2023-04-26 07:39 UTC, geshecelon requested changes
DATE: 26 APRIL, 2023
STT001-28 

00:21ད་སྒྲུབ་བྱེད་ད་དེ་རེད། ད་གཞི་གཞི་གྲུབ་ཚད་ལ་རྟོག་པས་བཏགས་ཙམ་གྱིས་ཁྱབ་པ་ཁས་ལེན་ཞིན་༼ཞིང་༽ད་གང་ལྟར་ཡང་།

00:53 ནང་ལ་བསམ་བློ་ཅིག་བཏང་པ་ཡིན་ན་འདྲ། བློ་འདུག་སེ་བློ་ལ་ཡར་དོན་གང་དང་གང་ཡིན་ནས་འདི་འདུག་སེ་སྣང་དུས་ཙམ་ནས་དོན་གྱི་ངོས་ནས་ཡོད་པ་ཞིག་སྣང་གི་འདུག་ག།༼ཤད་མི་དགོས།༽

01:29ཁོ་རས་ངོ་བོ་འདི་འེས་དོན་གྱི་ངོས་ནས་གྲུབ་པ་འདྲ་བོ་ཅིག་སྣང་གི་ཡོ་རེད་དེ༌༼དེ་ལ་ཚགས་དུང་མེད།༽། བཙལ་གར་ཕྱིན་ན་རྙེད་རྒྱུ་མེད་བསྡད་མཁན།
01:37འེས་ད་འབྲས་བུ་སྐྱེས་ཟེར་བསྡད་ཡས་དེ་ཡས། འེས་བཙལ་གར་ཕྱིན་པ་ཡིན་ན་འེས་རྙེད་ཡས་མེད་བསྡད་པ་ཅིག།༼དེ་ལ་ཤད་མི་དགོས།༽འོ་འདི་འདྲ་ཡིན་པ་ཡིན་དུས་ཙམ་ནས།

02:01འེས་སྐྱེ་འཇིག་གནས་གསུམ་བྱེད་མཁན་ཅིག་ཡོད་པ་རེད། རེད་པ་ད་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙམ་ནས་ད་དེ་ཡོད་སྟངས་དེ་ག་རེ་ཟེར་ལབ་ན་ཨ་ནི་མིང་གི་དབང་གིས་ཡོད་པ་ཅིག།༼ཤད་མི་དགོས།༽
02:10མ་གཏོགས་འགྲོ་ས་གཞན་དག་མེད་པ་རེད་ད། སོ་དེ་འདྲ་ཡིན་དུས་མིང་གི་དབང་གིས་ཡོད་ཙམ་ཞིག་ཡིན་པ་ཡིན་དུས་མིང་གི་དབང་གིས་ཡོད་ཙམ་༼མམ་༽རྟོག་པས།02:18བཏགས་ཙམ་ཞིག་ཡིན་པ་ཡིན་དུས་ཙམ་ནས། དོན་གྱི་ངོས་ནས་གྲུབ་པས་སྟོང་པ་རེད། དོན་གྱི་ངོས་ནས་གྲུབ་པ་དེར་རང་མཚན་ཟེར་གྱི་ཡོ་རེད།
02:43ད་དེ་ནས་བདེན་པ་གཉིས་བཤད་ཡོང་དུས་ཙམ་༼ཙ་༽ནས་ཐ་སྙད་དཔྱོད་བྱེད་དང༌།ཐ་སྙད་ཐ་སྙད་དཔྱོད་བྱེད་ཀྱི་འེས་དོན་དམ་དཔྱོད་བྱེད་ཟེར་ཡས་དེ་འེས་ཚིག་དེ་དང་།
03:02ཐ་སྙད་དཔྱོད་བྱེད་རེད་ཟེར།༼ཟེར་དེ་མེད་པ་ལྟ་བུ་སྣང་།༽ མཚམས་གང་འདྲ་ཅིག་ནས་དོན་དམ་དཔྱོད་བྱེད་ལ་འགྲོ་ཡི་ཡོད་རེད་ད་དེ་ལས་ཨ་ནི་ཁྱད་པར་ཆེན་པོ་ཡོད་པ་རེད།
03:19ཡིན་དུས་ཙམ་ནས་ད་དེ་ཡོད་པ་ར་ལ་ཆ་བཞག་རེད་བར་ད་བློ་གནོད་མེད་ལ་འེས་འཕྲལ་གི་འཕྲུལ་གྱི་༼རྒྱུའི༽གནོད་པ་མེད་པས་བློ་གནོད་མེད་ལ་སྣང་ཡས་སྣང་བསྡད་ཡས་དེ།03:31ཡོད་པ་བྱས་ད་འེས་བློ་གནོད་མེད་སྣ་༼སྣང་བའི་༽དབང་གིས་བཞག་པ་མ་ཡིན་པར་ཡུལ་རང་གི་ཐུན་མོང་མ་ཡིན་པའི་སྡོད་ལུགས་ཀྱི་ངོས་ནས་གྲུབ་པ་ཡོད་དང་མེད་དཔྱད་ཡོང་དུས་ཙ་ནས།
03:39ཨ་ནི་དོན་དམ་དཔྱོད་བྱེད་དུ་འགྲོ་ཡི་ཡོད་པ་རེད།དཔེར་ན། གང་ཟག་ཟེར་ཡས་ངའམ་གང་ཟག་ཟེར་ཡས་དེ་འེས་སྣང་ཙམ་དེས་མ་ཟིན་པར་འེས་ད་འགྲིག་བཞག་ང་འམ་གང་ཟག།༼ཤད་མི་དགོས།༽

 05:13གང་ལྟར་༼གང་ལྟར་དེ་མི་འདུག་སྙམ།༽བྱེད་པོ་དང་ལས་ཅིག་ཏུ་འགྲོ་ཡས་སོ་གང་ལྟར་གདགས་ཆོས་དེ་གདགས་གཞི་ལ་བརྟེན་ནས་བཞག་པ་རེད། གང་ལ་བརྟེན་ནས་བཏགས་བསྡད་ཡས་ཀྱི་བརྟེན་ས་ཁོ།
05:21བརྟེན་ས་ཁོའི་ནང་ནས་བཞག་པ་ཡིན་ན། དེ་ལ་བརྟེན་ནས་བཞག་དགོས་ཡས་མིན་འདུག་ག།༼ཤད་མི་དགོས།༽ ཁོ་རང་བཞག་བཞག་ན་འགྲིགས་ཀྱི་རེད་པ།
05:26སངས་རྒྱས་བསྐྱངས་ཀྱི་གསུངས་པ་ནང་བཞིན་གྱི། དངོས་པོ་རང་མཚན་ཉིད་ཀྱིས་གྲུབ་པ་ཡིན་ན། རེད་ད་ཨ་ནི་དེ་ཉིད་བཞག་པས་ཆོག་གི །བརྟེན་ནས་བཏགས་པས་ཅི་བྱ།༼དེ་ལ་ཤད་གཅིག་སྣོན་དགོས། དོན་ལ་ཤད་གཉིས་དགོས། གང་ཡིན་ཟེར་ན་དེ་ཚིགས་བཅད་ཡིན།༽
05:42ཆོས་གང་དང་གང་ཡིན་ནས་དེ་རེད་ཟེར་ལབ་བཞག་ན་འགྲིགས་ཀྱི་ཡོ་རེད་བ། ཨ་ནི་བརྟེན་ནས་བཏགས་པ་རེད་མིན་འདུག་ག་ཨ་ནི་བརྟེན་ནས་འབྱུང་བ་མ་རེད་མིན་འདུག་ག།༼ཤད་མི་དགོས།༽

05:57 རྙེད་རྒྱུ་ཞིག་ཡོད་ན༑ ད་དེ་དོན་དམ་དུ་གྲུབ་པརེད། ངོ་བོ་ཉིད་ཀྱིས་གྲུབ་པ་རེད་ཨ་ནི་བརྟེན་ནས་བཏགས་པ་མ་རེད། འོ་དེ་འདྲ་འདྲ་བུ་རེད་དེས་འདྲའི་ད་ཁྱད་པར་ཆེན་པོ་ཞིག་དོན་ཡོང་གི་འདུག་ག།༼ཤད་མི་དགོས།༽

06:25དཔེ་མི་སྲིད་པའི་གལ་ཆེན་པོ་རེད་བཞག།༼ཤད་མི་དགོས།༽ གཟུགས་དེ་འེས་སྟོང་གཞི་བྱས་ནས་དེ་གང་གིས་སྟོང་པ་རེད་ལབ་ན། དེའི་སྟེང་ལ་ཡར་གང་རེ་ཟེར་གོ་ཕར་གིས་འེས་ཆོས་ཆོས་གཞན་ཞིག།༼ཤད་མི་དགོས།༽

06:43སྣང་ཙམ་དེས་མ་ཚིམ་པར་སྣང་ཙམ་ཅིག་གི་གཟུགས་བཞག་རྒྱུ་རེད་མ་གཏོགས། དེ་ལས་བརྒལ་ནས་གཟུགས་ཟེར་ཡས་ཞིག་རྙེད་ཡས་མེད་པ་ཟེར༼རེད།༽།

06:55གཟུགས་གཟུགས་སྟོང་པ་ཉིད་ཀྱིས་སྟོང་བར་མི་བྱེད་དེ། གཟུགས་ཉིད་སྟོང་པ་ཉིད་དང་ཟེར་ནི་དཔེ་གལ་ཆེན་པོ་རེད་བཞག།༼ཤད་མི་དགོས།༽ དཔེ་གསལ་པོ་རེད་བཞག་འོ་དེ་འདྲ་འདྲ་བོ་གསུངས་ཡོ་༼བ་༽རེད།

རྗེས་སུ་མུ་མཐུད་དེ་བྱ་རྒྱུ་ཡིན།

2023-04-28 03:05 UTC, geshecelon requested changes
DATE: 28 APRIL, 2023
STT001-28 

07:15འེས་ཡིད་ཀྱི་རྣམ་ཤེས་དེ་གང་ཟག་གི་མཚན་གཞིར་མི་འདོད་པ་བྱས་རྙེད་གི་༼རྒྱུ་༽མེད་བསྡད་པ་བྱས་གང་ཟག་ལ་ལྡན་མིན་འདུ་བྱེད་ཀྱིས་ཁྱབ། བློ་ལ་ཚད་མ་དང༌། ཚད་མིན་གྱི་བློ་གཉིས་ཡོད།

08:00མ་འོངས་པ་དང་ད་ལྟ་བའི་ཚིག་མེད་འགྲོ་འཇིག་པ་ཟེར་ཡས་དེ་རྒྱུའི་སྐྱེས་པ་རེད་བ་ད་འཇིག་པ་ཟེར་ཡས་དེ་རྒྱུའི་སྐྱེས་པ་ཡིན་དུས་ཙམ་ནས་འཇིག་པ་གྲུབ་པ་དེས་གྲུབ་པའི་དུས་ཁོ་རང༼ཚངས་དུང་དགོས།༽།

08:20རེད་བ་འེས་དཔེར་ན་འེས་སྐྱེས་ཟིན་༼ན་༽རྒྱུས་བྱ་བ་བྱེད་དགོས་ཡས་མིན་འདུག་སྟེ། ཡིན་ནས་སྐྱེ་བ་དེ་རྒྱུས་བྱེད་ཀྱི་ཡོ་རེད་བ་བྱས་ཙང་སྐྱེས་བ་དེ་རྒྱུའི་བྱེད་ཀྱི་ཡོད་པ་ཡིན་དུས་ཙམ་ནས།
09:02མིང་རྐྱང་བཏགས་ཡོད་ཙམ་གྱི་ཕྱི་དོན་བཞག་ཆོག་གི་རེད་ཟེར༼ཟེར་དེ་མེད་པ་ལྟ་བུ་འདུག༽། སོ་དེ་གཉིས་པོ་དེ་རྫས་གཅིག་མ་རེད་ཟེར་༼ཟེར་དེ་མེད་པ་ལྟ་བུ་འདུག༽རྫས་ཐ་དད་བཤད་ཀྱི་རེད་ཟེར་༼ཟེར་དེ་མེད་པ་ལྟ་བུ་འདུག༽ངོ་བོ་ཐ་དད་བཞག་གི་འཇོག་རེད་ཟེར༼ཟེར་དེ་མེད་པ་ལྟ་བུ་འདུག༽།
09:19རྣལ་འབྱོར་མངོན་སུམ་ལ་འཁྲུལ་མ་འཁྲུལ་གཉིས་ཡོད་ཟེར་གསུངས་བསྡད་ཡས་ད་དེ་གི་གང་ལྟར་ཨ་ནི་འེས་སྟོང་ཉིད་མངོན་གསུམ་༼སུམ་༽དུ་རྟོགས་བསྡད་ཉན་རང་མཚན་གྱི་སྣང་བ་
09:49རང་གི་སྣང་བ་ལ་མངོན་སུམ་གྱི་ཚད་མ་ཡིན་པས་ཁྱབ་སྟེ་ཟེར༼ཟེར་དེ་མེད་པ་ལྟ་བུ་འདུག༽། སྒྲ་གཏང་འཛིན་རྟོགས་པ་དེ་རང་གི་སྣང་བ་ལ་མངོན་སུམ་ཚད་མ་ཡིན་པའི་ཕྱིར་ཟེར༼ཟེར་དེ་མེད་པ་ལྟ་བུ་འདུག༽།
09:55ད་ཤེས་པ་ཞིག་ཡིན་ཕྱིན་ཆད་ལ། ཁོ་རང་ཡུལ་ཅིག་གི་རྣང་པ་ཅིག་ཤར་གྱི་ཡོ་རེད་ཁོ་རྣམ་པ་ཅིག་ཤར་བསྡད་ཀྱི་ཡོ་རེད། ཤེས་པ་ལོག་ཤེས་ཡིན་ན་༼ནས་༽རེད།
10:16འདི་འདྲ་ཅིག་ཡིན་པ་ཡིན་དུས་ཙམ་ནས་འོ་བློ་ཕྱིན་ཅི་ལོག་མ་ལོག་གང་ཡིན་ནས། རང་རང་ལ་ཡར་སྣང་བ་ཡོ་རེད་ཟེར༼ཟེར་དེ་མེད་པ་ལྟ་བུ་འདུག༽། སྣང་བ་དེ་བློ་དེར་ལ་མངོན་གྱུར་རེད་ཟེར།
10:53འེས་ཁྱད་པར་འདི་ནི་གང་ཟག་གི་བདག་མེད་སྐབས་༼སྐབས་༽དེར་གང་ཟག་གི་བདག་མེད་ཟེར་བསྡད་ཡས་དེ། གང་ཟག་རང་རྐྱ་ཐུབ་པའི་རྫས་ཡོད་ཀྱིས་སྟོང་པ་དེ་ཙམ་ལ་གང་ཟག་གི་བདག་མེད་ཟེར་གྱི་ཡོ་མ་རེད་ཟེར།
11:40གཉིས་པ་ལམ་གྱི་སྤང་བྱ་ཟེར། ད་གཉིས་པོ་དེ་ད་ཕར་དེ་འདྲ་ཡིན་ས་རེད་ཕུང་པོ་བློ་ཡུལ་དུ་ཤར་བའི་སྒོ་ནས་གང་ཟག་བློར་ཤར་དགོས་འདུག་ག།༼ཤད་མི་དགོས།༽ ད་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙམ་ནས།
12:09གང་ཟག་གི་བདག་འཛིན་རྩ་བ་ནས་ཕར་ཁེགས་པ་ཅིག་ཡོང་བ་ལ་ཡང་། ཆོས་ཀྱི་བདག་མེད་རྟོགས་དགོས་ཀྱི་ཡོ་རེད།སོ་དེ་འདྲ་ཡིན་པ་ཡིན་དུས་འེས་གང་ཆོས་ཀྱི་བདག་འཛིན་དེ་ཉོན་སྒྲིབ་ཏུ་བཞག།༼ཤད་མི་དགོས།༽
12:19འེ་རང་རྒྱུད་པ་མན་ཆད་ཀྱིས་ད་ལྟ་ཆོས་ཀྱི་བདག་འཛིན་ཤེས་སྒྲིབ་ཏུ་བཞག་གི་འདུག་ག་འོ་ད་ལྟ་འདི་གི་ལུགས་འདིར་ཆོས་ཀྱི་བདག་འཛིན་ཉོན་སྒྲིབ་ཏུ་བཞག།12:27སོ་ཉོན་མོངས་ལ་བཞག།༼ཤད་མི་དགོས།༽ དེ་འདྲ་ཡིན་པ་ཡིན་དུས་ཙམ་ནས་འེས་ཉན་རང་དགྲ་བཅོམ་པ་དང་ཅིག་ཉེས་༼ཉན་༽རང་ཉེས་༼ཉན་༽རང་དགྲ་བཅོམ་པའི་ཉོན་སྒྲིབ་སྤངས་པ་ཅིག།༼ཤད་མི་དགོས།༽12:49ད་བཞུག་གོ་བཞུག་གོ་དེས་བཞུག་གོ་དེས་ཐལ་འགྱུར་བ་རྣམས་ཀྱི་ཁྱད་ཆོས་ཀྱི་གཙོ་བོ་ནི། བརྟེན་ནས་བཏགས་པའི་གཏན་ཚིགས་ལ་བརྟེན་ནས་ཕྱི་ནང་གི་ཆོས་རྣམས་ལ་རང་གི།༼ཤད་མི་དགོས།༽

IT’S FINISHED NOW. I WILL GO TO DASA TOMORROW AND WHEN I COME BACK YOU WILL FINISH THE TWO FILES THAT I DID THE CORRECTION.

2023-05-15 05:13 UTC, geshecelon requested changes
Date: 15. 05. 2023 
STT001-22 

03:05མིན་རྒལ་དུ་མཉམ་༼མོ་༽པ་འོ་གསུངས་བཞག ཚིག་དང་མིང་ཡི་དེ་དག་ནི་གཟུགས་ཙམ་འདུ་བྱེད་དག་ཏུ་འདུས་གསུངས་པ་ནང་བཞིན།

03:48བདག་མེད་ཕྲ་མོར་ཁས་ལེན་ནོ།༼རྫོགས་ཚིག་ལ་ཤད་གཉིས་དགོས།༽ སྡེ་པ་བཅོ་བརྒྱད་ཀྱི་ནང་ནས་མང་བཀུར་ལྔས་རང་རྐྱ་ཐུབ་པའི་རྫས་ཡོད་ཀྱིས་སྟོང་པའི་གང་ཟག་གི་བདག་མེད་ཕྲ་མོར་མི་འདོད་དེ།
04:02ཁས་མི་ལེན་ཏེ་གཞི་གྲུབ་ན་ཆོས་བདག་ཡིན་པས་ཁྱབ་པ་ཁས་ལེན་པའི་ཕྱིར།   འུམ་འུམ་ད་དེ་ནས༼འུམ༽། འེས་ད་མི་རྟག་སོགས་བཅུ་དྲུག
04:33འེས་གཉིས་པ་ལམ་གྱི་སྤངས་བྱ་ལ་ཉོས་མོངས་ཅན་དང་ཉོན་མོངས་ཅན་མ་ཡིན་པའི་མི་འོ་རེད་ད་དེ་ནས་དེ་བར་དུ་ཅིག་ལབ་གོ་བྱེད་དོ་འོ།༼རྫོགས་ཚིག་ལ་ཤད་གཉིས་དགོས།༽
05:01བློ་བཅོས་ཡས་ཟེར་ཡས་ཁོ་འེས་བློ་ཁོ་རང་གི་ནང་ལོག་ནས་བཅོས་ཡས་རེད་མ་གཏོགས། ཤེན་༼གཞན་༽ཐབས་ཤེས་ཡོ་མ་རེད་བ།
05:53ཁོ་གང་ལྟར་རྣམ་རྟོག་གིས་འེས་ཕར་གས་སྒྲོ་ར་བོ་བཏགས་ནས་འེས་ཡུལ་སྡུག་པ་ལྟ་ཡས་དང༌། ཡུལ་སྡུག་པ་ལ་སྣང་ཡས། མི་སྡུག་པ་སྣང་ཡས།།༼ཤད་གཉིས་མི་དགོས།༽
14:30འེས་དམན་པའི་དགྲ་བཅོམ་པ་ཡང་རང་གི་སྤངས་རྟོགས་ལས་ཉམས་ནས་རྒྱུན་ཞུགས་སུ་འགྱུར་བ་སྲིད་པས་ཉམས་པའི་ཆོས་༼ཅན་༽ཀྱི་དགྲ་བཅོམ་པ་ཟེར་ཡས་དེ་ཡིན་པ་རེད།14:40ཁས་ལེན་ནོ།། ཉན་ཐོས་ལ་དགེ་འདུན་ཉི་ཤུ་དང༌། ཞུགས་གནས་བརྒྱད་ཀྱི་རྣམ་གཞག་འེས་རྣམ་གཞག་རྩིས་ཡང་ཅིག་ཅར་བ་ཁས་མི་ལེན།

Kindly finish this, I will submit this as soon as possible.

2023-05-22 06:50 UTC, merged